### ISSUE TITLE
🐧 Issue v20.0.2

### ISSUE THREAD

**Issue by Orsucciu** [itchio/itch#1011]
Dear itch app team, 

I would appreciate to have the possibility to download games not available for my system. I use Linux but i'm sure that Wine would let me play most of the windows games.

Thank you.

**Comment by fasterthanlime** [comment]
Hey there, thanks for the feedback! Eventually, I'd like to integrate Wine directly with the itch app, see #433. I'm not exactly sure how it'll work yet — I like for example how PlayOnLinux/PlayOnMac lets you download different versions of Wine and associate it with certain games, so you can use known good versions!

There's a couple of other points that require some thinking: how would Linux<->Windows filesystem work (one wineprefix per game?), how would launching games work (detect .exe just like we do on Windows?), what about sandboxing? etc. But nothing impossible, in time!

**Comment by fasterthanlime** [comment]
Closing in favor of #433
