### ISSUE TITLE
🏁 Issue v20.0.2 - No option for downloading multiple items from a game bundle.

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1015]
Dear itch app team, 

I bought a game bundle (Juegos Ranchs Fantastic Arcade).  When I went to download the bundle from the app it showed me the five games in the bundle.  I was only allowed to select one to download, and now that single game gets listed as "the version" of that bundle.  There are no options to install the remaining games in the bundle.

I have another purchased game that had two sections; the game, and some extras.  Same deal: Once I had installed just one of those downloads  (the game) I no longer had any way to go back and install the rest (the game extras).

**Comment by fasterthanlime** [comment]
Hey there, thanks for the report! That's a known issue, see #929. In the meantime, you can always download everything you purchase individually from the itch.io website!

**Comment by fasterthanlime** [comment]
itch v25 is out and it solves that issue, see https://github.com/itchio/itch/issues/929#issuecomment-422093212
