### ISSUE TITLE
Auto-download full games when already owned

### ISSUE THREAD

**Issue by big-samantha** [itchio/itch#1017]
Currently, when you click the download button for a game, you're prompted to pick a download if there is a demo and full version available. If you already own the game, it should just pick the full game automatically.

**Comment by fasterthanlime** [comment]
Since there might be cases when someone wants to install the demo anyway, I've just made it clearer which uploads are demo and which aren't:

![screen shot 2016-12-05 at 12 48 11](https://cloud.githubusercontent.com/assets/7998310/20883974/1c741294-bae9-11e6-9158-a2819c5ade5a.png)
