### ISSUE TITLE
Updating some games I bought: "API error: you must buy this game to download"

### ISSUE THREAD

**Issue by Xananax** [itchio/itch#1018]
All the games in this screenshot 

http://i.imgur.com/Qzkw3sV.png

Give me "itch.io API error: you must buy this game to download".

However, I have bought each of these games, and the download has been added to the queue through my library's "update" function.

To be clear: those are all games I have bought and am trying to update. I haven't had this error with any game I am downloading for the first time.

Even stranger, most of those are marked "up to date" when going to their respective page, even after pressing "check for update".

I've tried deleting and re-installing one of those fresh ("When Development is the Game", an ebook), and it worked. Haven't done that with the others in case they're needed to reproduce.

**Comment by fasterthanlime** [comment]
Hey, thanks for the report!

I have an idea of what might cause this, but I'd love to take a look at your itch log to confirm — you can open it from the Preferences tab, or find it here:

  * Windows: `%APPDATA%/itch/logs/itch.txt`
  * Linux: `~/.config/itch/logs/itch.txt`
  * macOS: `~/Library/Application Support/itch/logs/itch.txt`

**Comment by Xananax** [comment]
Hey, sorry for not specifying my architecture (Arch Linux). Full log here:
http://sprunge.us/SIDD

The log has a bunch of `[reactors/tasks] Should download xxxx, has dl key ? false` before spouting the error, so I suppose it's some sort of hash that has changed? I haven't updated in a long while.

**Comment by fasterthanlime** [comment]
Thanks, that gives me a good idea what to look for.

One last thing, can I also get a look at `itch.updater.txt` ? (same folder)

**Comment by Xananax** [comment]
Sure, `cat ~/.config/itch/logs/itch.updater.txt`:

http://sprunge.us/hjZe

**Comment by fasterthanlime** [comment]
Bug fixed, new release tagged, give it about 15 minutes to become available in AUR :shipit: 

Thanks a ton for the report!

**Comment by Xananax** [comment]
Thanks a ton for the incredibly prompt fix!

**Comment by fasterthanlime** [comment]
v21.0.1 is up now: https://aur.archlinux.org/packages/itch/ — can you confirm that it fixes it for you?

**Comment by Xananax** [comment]
Updated, I confirm, it works. Thanks a bunch!
