### ISSUE TITLE
Cannot view several collections

### ISSUE THREAD

**Issue by nickfourtimes** [itchio/itch#1025]
Clicking on several of my collections results in blank pages. I can still see "+X items hidden by filters" (see image) but no actual titles. Note that the collections that show as blank differ whether I set the app fullscreen or windowed.

![capture](https://cloud.githubusercontent.com/assets/215674/20681723/cdccaa78-b572-11e6-8699-bd9f2d2a8eaa.JPG)

**Comment by fasterthanlime** [comment]
If you press Shift+F12, are there any errors shown ?

**Comment by nickfourtimes** [comment]
Hmm... only thing I see in the Console is:
`C:\Users\nrudz\AppData\Local\itch\app-21.0.1\resources\app.asar\node_modules\react-dimensions\index…:200 Wrapper div has no height or width, try overriding style with `containerStyle` option`

**Comment by fasterthanlime** [comment]
What's your OS again? Can you paste the itch log somewhere? (you can open it from the Preferences tab, in the 'Advanced' section).

Can you try (with devtools open) focusing the app's window, hitting Shift+F5, and looking at the devtools console again?

Also, your collections display fine here for some reason!

![screen shot 2016-11-28 at 20 13 22](https://cloud.githubusercontent.com/assets/7998310/20682191/4c964704-b5a7-11e6-8a42-ea86a8c8f106.png)

**Comment by nickfourtimes** [comment]
I'm using Windows 10 Home 64-Bit. I'm including a zipped version of the log here (is that appropriate?). 
[itchlog.zip](https://github.com/itchio/itch/files/617236/itchlog.zip)

If I hit Shift-F5, I noticed the page I'm looking at becomes visible, while the others no longer display the collections (i.e., by hitting Shift-F5 I can basically look at one collection at a time). I don't see anything other than the wrapper-div error copied above when I look in the Console though...

**Comment by fasterthanlime** [comment]
Ah, I think I got it! Does resizing the window make the collection appear again? :)

**Comment by nickfourtimes** [comment]
Yeah... I always use the app fullscreen, and as above some of the collections were showing if I switched to windowed and vice versa. Anyway, if it's windowed, and the collection is invisible, and I resize the window, the collections do become visible again.

**Comment by fasterthanlime** [comment]
Cool! Then it's a simple sizing issue, I'll get out a fix asap.
