### ISSUE TITLE
🏁 Issue v21.0.1 - No way to Add to Collection from an item page view?

### ISSUE THREAD

**Issue by ziz** [itchio/itch#1028]
Dear itch app team, 

When viewing an item page (such as, say, https://stevencolling.itch.io/16x16-dungeon-crawl-assets) in a browser, there is a floating button in the top right to "add to collection".  In the app, there is no such option, and I can't find a way to add things to collections from the app.

Could the app support collection management?

**Comment by fasterthanlime** [comment]
Hey there!

It's definitely planned, see #108 — in the meantime, if you're logged into the website from the app (see #672), and the window is wide enough, the button is there:

![screen shot 2016-11-30 at 10 09 59](https://cloud.githubusercontent.com/assets/7998310/20746224/2e60d60c-b6e5-11e6-8970-1f3bfbdfe59e.png)

So really the battle plan looks like this:

  * Support auto-login (#672)
  * Show 'Add to collection' button even on narrow views (no known issue opened about that)

and in parallel:

  * Add API support for editing collections, and take advantage of that in the app

**Comment by ColsterJ** [comment]
I'm glad this has been acknowledged and there are plans... I know there's lots of work to do on the app, but I hope this is a feature that gets added soon! It's fundamental to the game discovery process.

**Comment by fasterthanlime** [comment]
Quick little update:

The app now logs you into the website properly, so you can use the web controls to add a game to a collection:

![image](https://user-images.githubusercontent.com/7998310/45692116-4b534800-bb5a-11e8-8a28-6d65b52cd7e9.png)
