### ISSUE TITLE
Handling of Creator-Removed Games in Collections in App

### ISSUE THREAD

**Issue by khbecker** [itchio/itch#1031]
Hi,

I have a collection where one of the games was removed from Itch by its creator ( https://dadako.itch.io/pirate-pop ). The website seems to have automatically removed the game from my collection (which is what I would expect) since it doesn't show up anywhere there, but the itch app still shows the game. There doesn't appear to be a way to remove the game from the collection in the Itch app. Is there any way to manage collections at all from the app? If not, that would be a useful feature.

My itch username is km3k, if that helps you see what my account data looks like on the website. I'm using Itch 21.0.4, but this has been happening for a while now.

**Comment by Wolfenpilot687** [comment]
Hi there! It seems like I have the same problem, with Itch 23.0.0! Removed games, while disappeared from the collection in the website, remain on the app and seem irremovable by any means.

**Comment by khbecker** [comment]
This is still an issue in 23.2.1.

**Comment by fasterthanlime** [comment]
Turns out this is an API issue, see https://github.com/itchio/itch.io/issues/611

**Comment by fasterthanlime** [comment]
This has been fixed in the API, closing.
