### ISSUE TITLE
Ability to move items between install locations

### ISSUE THREAD

**Issue by fluffy-critter** [itchio/itch#1033]
I accidentally installed a bunch of stuff to the default ~/Library/ install location without realizing that my preferred location wasn't set as the default. It'd be nice if there were a way to easily move files into the other location.

**Comment by fasterthanlime** [comment]
One of the blockers for that is that, on Windows, sometimes games are installed via... installers, which store the install path somewhere else — so if we move the contents of the folder manually, uninstalling will break (and so will any created shortcuts, etc.).

Ideally the feature would allow "moving all games", and if any of them are installer-based, warn that "3 of them can't be moved, proceed anyway", and then it'd move all the ones it can move!

**Comment by fluffy-critter** [comment]
Ah, yeah, that makes sense. I'm used to being spoiled by the folder-is-the-entire-installation aspect of macOS. :)

I guess in the meantime I can just filter by the old install location and then manually uninstall/reinstall all of them.

**Comment by Deozaan** [comment]
@plaidfluff Another workaround is to copy everything over and then make the vanilla install location a junction to your custom/preferred location.

In fact, doing something like this may even solve (read: work around) the problem on Windows. @fasterthanlime

**Comment by fluffy-critter** [comment]
I'm primarily using a Mac so I'd want to use a symlink instead, but yeah that isn't a terrible idea.

**Comment by fasterthanlime** [comment]
So, v25 shipped and that's *still* not a feature, HOWEVER you can sorta do it manually

If you just move all the app folders to another install location and use the "Scan install locations" button (or restart the app, or add the install location after you've moved the game folders), then they should pop up, ready to be used.

**Comment by hsandt** [comment]
> If you just move all the app folders to another install location and use the "Scan install locations" button

Thanks I come from https://itch.io/t/3399170/moving-install-locations and I couldn't find a way to have the moved apps recognized, but the button worked. I added the full path + screenshots for users who need more information:

Preferences > Manage install locations > Scan install locations for games
(it took a bit of time, maybe restarting the app would have been faster, I'm not sure)

<img width="463" height="340" alt="Image" src="https://github.com/user-attachments/assets/2512dc3d-8f8a-437c-95d1-22ee4c47e82d" />

<img width="828" height="132" alt="Image" src="https://github.com/user-attachments/assets/637995f3-d44d-40f8-aa23-5cef34c3ca4d" />

Unfortunately, the thread I mentioned has been auto-archived. Would be nice if a mod could just post on that thread a link to this issue, which contains the solution.
