### ISSUE TITLE
Please allow "new folder" button from OSX file picker

### ISSUE THREAD

**Issue by fluffy-critter** [itchio/itch#1034]
On OSX, when specifying an install location it would be nice if the "new folder" button were available. Relatedly, creating a new folder from Finder within the currently selected view doesn't make it appear in the file picker until I navigate away and back into that location. Probably just a couple of options need to be set on the file picker.

**Comment by fasterthanlime** [comment]
That's a great point and I'd love to do that, but it'll probably require us submitting a PR to electron as it doesn't seem to support that currently: https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback

**Comment by fluffy-critter** [comment]
Ah, that's unfortunate. I kind of figured there was a platform-independent framework in the way...

Fixing this in Electron will at least fix a lot of OSX experiences. :)

**Comment by fluffy-critter** [comment]
Nice! Simple fixes are best fixes.
