### ISSUE TITLE
Allow download file not explicitly marked for a particular OS.

### ISSUE THREAD

**Issue by local-minimum** [itchio/itch#1035]
Some games the downloads have not been properly tagged for specific OS:s, if there is none for your OS but non-tagged files, allow the user to select one of those.

Example [Depression Quest](https://the-quinnspiracy.itch.io/depressionquest/)

As with the example, the dev probably has given clear hints that Itch could use too.

**Comment by fasterthanlime** [comment]
> Example Depression Quest

Fixed!

> As with the example, the dev probably has given clear hints that Itch could use too.

The app auto-detects a lot of things, but platforms from uploads is not something I'll go for, there's just too big a chance of it going wrong.

*To clarify: if games are badly tagged, report them, we'll fix them. There's a bunch of other things that depend on games being tagged correctly. We can definitely improve the UI for tagging (force picking something, suggest based on file name — but it should still be the developer's action to tag a game with a given platform)*

**Comment by local-minimum** [comment]
Fair point, however the feedback could be better in the app when this triggers because it mostly looked like the game disappeared when bought in the bundle and that was quite confusing.

**Comment by fasterthanlime** [comment]
> Fair point, however the feedback could be better in the app when this triggers because it mostly looked like the game disappeared when bought in the bundle and that was quite confusing.

Was it hidden in the game grid because "Only compatible" was checked? Or was it just that there was no "Install" button and it showed "Not compatible with {os}" instead ?

**Comment by local-minimum** [comment]
It was my impression that it was hidden in the game grid. I don't think I have purposely selected "Only compatible", but could be it is default?

In any case, from the user experience I think it would be better to always keep them visible because else I don't see how I'd be able to actually see those games that I own but don't have compatible OS other than searching for the game in general on itch. Unless the "Only compatible" filter is on the actual tab, in which case I did miss it. Maybe the page should say "{0} items filtered out due to {1}" or something when this is triggered? 

To slightly side-track, I couldn't find a way to display the bundle-page itself in itch, so after buying the bundle (and this one had many games) it was confusing and hard to figure out which of all my games were actually the new bundle games.

**Comment by fasterthanlime** [comment]
![filter-highlight](https://cloud.githubusercontent.com/assets/7998310/20837184/3bdebce4-b8a3-11e6-97a5-626bcbd57efc.png)

> To slightly side-track, I couldn't find a way to display the bundle-page itself in itch [...]

I agree bundle visibility once you bought it could definitely use improvements, although for itch to get better at it the website+API needs to improve first. It's on our list :)

**Comment by local-minimum** [comment]
I guess I didn't consider it as the filter-field was empty. But lets consider this issue closed.
