### ISSUE TITLE
Add various DirectX redistributables to prereqs repositories

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1042]
See https://itch.io/docs/itch/integrating/manifest.html, Prerequisites section

**Comment by MichaelDePiazzi** [comment]
+1 for this. In particular, I need the June 2010 run-times. I think this must be the most common version as it's the only one Steam offer in their list of redistributables. Here are the download links:
Full installer: https://www.microsoft.com/en-au/download/details.aspx?id=8109
Web installer: https://www.microsoft.com/en-au/download/details.aspx?id=35

**Comment by MichaelDePiazzi** [comment]
@fasterthanlime Any idea when the DirectX redists (and also .NET Framework redists - issue #1061) might be added? Just curious because you added them as part of the v22.0.0 milestone, but that version has since been and gone. Thanks!

**Comment by fasterthanlime** [comment]
> @fasterthanlime Any idea when the DirectX redists (and also .NET Framework redists - issue #1061) might be added? Just curious because you added them as part of the v22.0.0 milestone, but that version has since been and gone. Thanks!

It is done! :shipit: (in b009d2c83625fddf3c73d632a872bfdc47dc2213)

See https://itch.io/docs/itch/integrating/prereqs/dx.html

**Comment by quyse** [comment]
> See https://itch.io/docs/itch/integrating/prereqs/dx.html

Hmm, June 2010 redist is listed as 9.0c, but is actually not DirectX9-specific, is it? At least June 2010 DXSDK contains DX versions up to 11, and so runtime does too.

**Comment by fasterthanlime** [comment]
oh

**Comment by fasterthanlime** [comment]
time to rename it to dx-june-2010 before anyone uses it

**Comment by fasterthanlime** [comment]
Renamed:

![dx-june-2010](https://user-images.githubusercontent.com/7998310/28217384-42b70ab8-68b5-11e7-81b4-724645082011.png)
