### ISSUE TITLE
Tray notifications on Windows 7 are shown with "stop" icon

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1056]
![image](https://cloud.githubusercontent.com/assets/416215/21075312/7be627b4-bf1f-11e6-9ab3-befc202fc89a.png)

**Comment by fasterthanlime** [comment]
Yeah, we noticed that in a round of QA, I don't think we found a solution for that :/ the `icon` parameter of `displayBalloon` seems not to work (or maybe we're just misusing it) https://github.com/electron/electron/blob/master/docs/api/tray.md
