### ISSUE TITLE
Update notification obscures 'url' field on a new tab

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1059]
Stumbled across this small usability thing.
![image](https://cloud.githubusercontent.com/assets/416215/21081163/0d908530-bfd2-11e6-98da-d453014ab3b3.png)
(It says "Downloading update...")
Notification about itch update shows right over 'url' field on the "New Tab" page, so it's hard to enter an url :) It's stupid, but it seems like there's no way to hide it or move it, and url field is the bottom-most thing on a page, so it cannot be scrolled upwards.

**Comment by quyse** [comment]
Well, I suddenly realized that it was in a virtual machine with small screen resolution. On "normal" screen the field is not on the bottom of the window, so most users won't see this problem.

**Comment by fasterthanlime** [comment]
v25 it out, and it doesn't show a status message like that when it self-updates - it does it in the background, and then it shows a notification in the titlebar. So that's not an issue anymore!
