### ISSUE TITLE
Add various .NET Framework redistributables to prereqs repositories

### ISSUE THREAD

**Issue by MichaelDePiazzi** [itchio/itch#1061]
In particular, I'm after the .NET Framework 4.5.1 redistributables. In regards to other versions to potentially add, these are the versions Steam currently provides (I've included the download links for offline and web installers for convenience):

- 4.6
  - Offline: https://www.microsoft.com/en-au/download/details.aspx?id=48137
  - Web: https://www.microsoft.com/en-au/download/details.aspx?id=48130
- 4.5.1
  - Offline: https://www.microsoft.com/en-au/download/details.aspx?id=40779
  - Web: https://www.microsoft.com/en-au/download/details.aspx?id=40773
- 4.0 Client Profile
  - Offline: https://www.microsoft.com/en-au/download/details.aspx?id=24872
  - Web: https://www.microsoft.com/en-au/download/details.aspx?id=17113
- 4.0
  - Offline: https://www.microsoft.com/en-au/download/details.aspx?id=17718
  - Web: https://www.microsoft.com/en-au/download/details.aspx?id=17851
- 3.5 Client Profile
  - Offline: https://www.microsoft.com/en-au/download/details.aspx?id=5007
  - Web: https://www.microsoft.com/en-au/download/details.aspx?id=14037
- 3.5
  - Offline: https://www.microsoft.com/en-au/download/details.aspx?id=25150
  - Web: https://www.microsoft.com/en-au/download/details.aspx?id=22

I'm not sure if all of these need to be included, or if there are others that may be needed. But this is what Steam currently provides fwiw.

**Comment by MichaelDePiazzi** [comment]
This is probably worth considering:
https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

As of 12 January 2016, versions 4, 4.5, and 4.5.1 are no longer supported by Microsoft. Versions 3.5, 4.5.2, 4.6 (and higher) are still supported.

With that in mind, 4.5.2 should probably be used instead of 4.5.1.

4 could be dropped also assuming you don't want to support Windows XP (it was the last version that worked with XP).

Download links for 4.5.2:

- Offline installer: https://www.microsoft.com/en-au/download/details.aspx?id=42642
- Web installer: https://www.microsoft.com/en-au/download/details.aspx?id=42643

**Comment by fasterthanlime** [comment]
@MichaelDePiazzi Do you have an opinion as to whether the offline or web installer are superior?

Microsoft recommends the web one, and I'm inclined to use it, since it will not download much if everything is already installed (it may have better "check if it's already installed" heuristics than we do). Plus it probably serves file from their CDN, whereas redists are right now served only from a US server (that'll change in the future, but we don't live in the future right now).

Of course users will need internet connectivity with the web one, but it's the same with the offline one due to how redists work right now (they're downloaded on-demand).

I was just curious if you had any additional experience to share about either!

---

edit: Also, aren't some versions of the .NET frameworks shipped by default on some versions on windows? I hear 3.5 on Win 8 is hairy, for example: http://www.ubergizmo.com/how-to/install-net-3-5-on-windows-8/ - I wonder if I'll have to implement logic based on the version of windows you have, too..

**Comment by MichaelDePiazzi** [comment]
@fasterthanlime My experience has mainly been with the offline installers. But I don't see any problem with using the web installers. As you mention, there are some pros to this and internet connectivity is already required to download a redist via itch anyway.

And yes, each version of Windows shipped with a different version of the .NET Framework. Wikipedia has some details here: https://en.wikipedia.org/wiki/.NET_Framework#Release_history
Also some details from Microsoft for newer frameworks (v4+): https://msdn.microsoft.com/en-us/library/8z6watww(v=vs.110).aspx

Personally, I wouldn't bother with 3.5 for now unless someone requests it. It's pretty old now (released in 2007). 4 is also only really required if you still want to support Windows XP (as it's the last version of the framework it supported). I think for now just adding support for 4.5.2 and 4.6 will be a good starting point. If someone needs a different version, then they can always request it and just go from there.

**Comment by fasterthanlime** [comment]
> Personally, I wouldn't bother with 3.5 for now unless someone requests it. It's pretty old now (released in 2007). 4 is also only really required if you still want to support Windows XP (as it's the last version of the framework it supported). I think for now just adding support for 4.5.2 and 4.6 will be a good starting point. If someone needs a different version, then they can always request it and just go from there.

Are "xna-4.5" and "xna-4.6" good prerequisite names, or would anyone have a valid reason to want "4.5.1" specifically over "4.5.2" ?

---

reminder to myself, .NET installers seem to accept `/q /norestart` (like msiexec), see [this page](https://msdn.microsoft.com/en-us/library/ee390831(v=vs.110).aspx)

**Comment by MichaelDePiazzi** [comment]
> Are "xna-4.5" and "xna-4.6" good prerequisite names, or would anyone have a valid reason to want "4.5.1" specifically over "4.5.2" ?

Maybe call it something like "net" instead of "xna" though. XNA Framework is a different thing (although it does depend on .NET Framework 4). I would probably name the pre-req with the specific version as well (e.g. "net-4.5.2") so it's clear what version of the framework it installs.

And I don't think anyone should need 4.5.1 over 4.5.2 as it's meant to be fully compatible with all prior 4.x versions. MS no longer support versions 4-4.5.1 anyway, so I can't think of any good reason why you'd still want to install them.

**Comment by fasterthanlime** [comment]
> Maybe call it something like "net" instead of "xna" though.

Oh woops, of course :)

> I would probably name the pre-req with the specific version as well (e.g. "net-4.5.2") so it's clear what version of the framework it installs.

That was the crux of my question. For example, there's various versions of the Visual C++ Redist 2015 - but they're all supposed to be backwards-compatible, so there's really no need to "pick" an older one. If MSFT comes out with 4.5.3 at some point, new installs would probably want the .NET 4.5.3 framework, right? If it's just named "net-4.5" they wouldn't have to change their manifest. Does that rationale make sense?

**Comment by MichaelDePiazzi** [comment]
> If MSFT comes out with 4.5.3 at some point, new installs would probably want the .NET 4.5.3 framework, right?

No, not necessarily. It depends what version of the .NET Framework the application targets. For example, my game targets .NET 4.5.1. So as long as .NET 4.5.1 or a higher 4.x version is installed, it will work. For example, the latest .NET 4.7 could be installed and that will work. So if a newer version does come out, it doesn't need to be installed. But if it is, it will still work.

So really, you could just install the highest 4.x version and that will work. But there's a couple of reasons why you might not want to do that:

- You probably don't want to force an install of a newer version of the framework on a users PC if they don't need it. Most users only have the version that shipped with their OS. So you probably only want to update that if you need to.
- MS eventually drop support for older OS's. For example, .NET 4 was the last version for Windows XP, 4.6 was the last version for Vista.

Ideally, it would be good if you could specify which version of the .NET framework your game targets as the pre-req (e.g. "net-4.5.1" in my case). Then itch checks which version is installed and installs an appropriate update if necessary. For example, you could take the following action for each target framework version _(I'm assuming Vista is the minimum OS itch supports)_:

- **4, 4.5, 4.5.1, 4.5.2**: Installs 4.5.2 only if the target framework is not installed.
- **4.6**: Installs 4.6 if it's not installed.
- **4.6.1, 4.6.2, 4.7**: Won't work with Vista. Installs the target framework if it's not installed. _(I probably wouldn't worry about these versions for now until someone requests them)_

btw, if you haven't already found these, here's some useful links:

- [.NET Framework Versions and Dependencies](https://msdn.microsoft.com/en-us/library/bb822049(v=vs.110).aspx) - Has details on all the versions, which OS's they can be installed on / were shipped with, and how to determine which version is installed.
- [Deploying the .NET Framework](https://msdn.microsoft.com/en-us/library/jj152927(v=vs.110).aspx) - Has a heap of info on installing the framework

**Comment by fasterthanlime** [comment]
4.5.2 and 4.6 are now available, #1308 will track the "determine which version needs to be installed from the registry entry's value & current OS" feature (which I can't ship without upgrading the app, and many major changes are pending before that)

See the new [prereqs documentation](https://itch.io/docs/itch/integrating/prereqs/) for names & details.

Thanks a lot again for all the info @MichaelDePiazzi, it's been precious today and it'll be invaluable for #1308.

**Comment by MichaelDePiazzi** [comment]
@fasterthanlime Awesome, thanks man! And no worries, glad I could help out in some way :)
