### ISSUE TITLE
DNS issues (can't resolve CDN's ip)

### ISSUE THREAD

**Issue by Leosolano229** [itchio/itch#1063]
Dear itch app team, 

Hello

I was trying to download ravenfield, but I can't download ANY game! D':
It says that it couldn't access the file after about 30 minutes and I can't download anything!

I'm using windows 10

**Comment by fasterthanlime** [comment]
Hey, can you attach the app log here? You can open it in the Preferences tab, in the Advanced section.

Also, would you be able to post a screenshot of what the app shows when it says it can't access the file?

**Comment by Leosolano229** [comment]
[itch.txt](https://github.com/itchio/itch/files/649376/itch.txt)
Hello!

Thanks for answering so quickly!

I've attached the app log and the screenshot, this one is new so, as you can see I still can't download any games.

Thanks for your time

![itch](https://cloud.githubusercontent.com/assets/24537948/21148180/08bb0d04-c11d-11e6-88ca-9ae9459de82e.png)

**Comment by fasterthanlime** [comment]
It looks like you're having DNS issues (your computer can't find `w3g3a5v6.ssl.hwcdn.net`).

I recommend telling your computer to use more reliable DNS servers, like Google Public DNS: https://developers.google.com/speed/public-dns/docs/using

Also, out of curiosity, are you using a proxy to connect to the internet?

**Comment by Leosolano229** [comment]
Yeap! That was It! I just changed the DNS address and it worked.
Thanks!

And no, I'm not using a proxy

**Comment by fasterthanlime** [comment]
Awesome, thanks for reporting back!
