### ISSUE TITLE
Godot-based game fails to launch on Mac via itch app

### ISSUE THREAD

**Issue by IBwWG** [itchio/itch#1066]
In case this is an itch error...

https://github.com/godotengine/godot/issues/7300

That is to say, the itch app reports the error (-10825).  Is that an itch error code, or something else?

![mac-probs1](https://cloud.githubusercontent.com/assets/16719964/21181456/4f40c2c8-c1fe-11e6-9c43-4d64a2add712.png)
![mac-probs2](https://cloud.githubusercontent.com/assets/16719964/21181455/4f407458-c1fe-11e6-8ae0-84efb49def29.png)

**Comment by fasterthanlime** [comment]
@IBwWG can you try running exactly the same butler command as last time? There was an issue that has been fixed recently: https://itch.io/t/51336/incantations-for-properly-packaging-mac-build

**Comment by fasterthanlime** [comment]
To expand on the issue:

- There was an issue in butler's backend that resulted in symbolic links missing from .zip files generated by it
- This was fixed recently
- Pushing your latest mac build (you can just pass the .app folder to butler) should generate a working archive.

**Comment by IBwWG** [comment]
That totally worked.  Furthermore, whether uploading a naked .app or one in a .zip (as Godot generates), and whether downloading directly or via the itch.io app, everything works!  Thanks so much, I guess I just had unlucky timing with this one!

**Comment by fasterthanlime** [comment]
> Thanks so much, I guess I just had unlucky timing with this one!

On one hand, the issue had been here for longer than I'm comfortable with (I guess Unity games work fine even if no symlinks are there? also, my macbookpro died and I was doing most of the mac QA), and on the other hand - your build was processed a few minutes before I pushed the fix so, yeah, timing is a crazy thing :)
