### ISSUE TITLE
Check for changes to collections.

### ISSUE THREAD

**Issue by jonbro** [itchio/itch#107]
If you launch the app, change a collection on the website, then come back to the app, the collection is not updated.

**Comment by fasterthanlime** [comment]
for now, collections are fetched when you click them in the sidebar.

so just click it again, new games should appear

**Comment by fasterthanlime** [comment]
for later, we need to think up a better scheme. polling seems expensive

**Comment by fasterthanlime** [comment]
heuristic idea: recheck for currently focused collection when app gains focus

(show spinner instead of game count while it's loading?)

**Comment by jonbro** [comment]
Yeah, I was thinking the regain focus is a good checking solution.
