### ISSUE TITLE
Manifest docs confusion

### ISSUE THREAD

**Issue by margaretdax** [itchio/itch#1077]
I recently published my first small project on itch.io here mollrow.itch.io/graphics-i

While trying to figure out how to get the manifest file right to have a "launch" option instead of "open" I got pretty confused about how to form a valid manifest (this because the project was marked as Other so I was just doing everything wrong)

https://github.com/itchio/itch/issues/92#issuecomment-224846852

https://itch.io/docs/itch/integrating/manifest.html

It was unclear to me which of these was correct or if the manifests shown in the docs had more placeholder text than I originally thought

**Comment by fasterthanlime** [comment]
I'm confused as to how you ended up on #92 though - it's not uncommon for GitHub issues to contain in-progress work, finding out all the outdated information in those and editing them one by one would take some time :wink: 

More importantly, how can I make the official docs page less confusing?

**Comment by margaretdax** [comment]
Maybe a couple of quick notes about the TOML syntax you're commonly using? I've had no exposure to it so the significance of single vs double square brackets wasn't clear, and #92 made me think it was possible that [[actions]] was somehow placeholder. I don't think I would have got that far if I had my category set properly though. Regardless I think a few quick comments on TOML syntax would help boost confidence in forming a proper manifest

**Comment by fasterthanlime** [comment]
I remember updating the manifest docs since that issue was opened, and there is now a validator that you can use (it's integrated into butler).

See the updated page at https://itch.io/docs/itch/integrating/manifest.html
