### ISSUE TITLE
Itch Should Support --version Flag and Allow Debug Console Even in Prod Build

### ISSUE THREAD

**Issue by niedzielski** [itchio/itch#1089]
**Enable --version Flag**
Executing `itch --version` should print app version for easy bug reporting

**Allow Debug Console**
The ability to debug issues in any version of the app is super useful for reporting bugs accurately and development. There's no reason to completely disable this functionality, just hide it under help or advance preferences

**Comment by fasterthanlime** [comment]
I agree about `--version`, have been wanting to do that for a while.

For debug console, do you mean chrome devtools? You can open then (even in production builds) with Shift+F12, or by exporting `DEVTOOLS=1` (to debug the main app) or `DEVTOOLS=2` (to debug all webviews)

**Comment by niedzielski** [comment]
> `--version`
Sounds good.

> DevTools
Sweet, that's just what I meant! Sorry, I didn't see your note in the dev readme.
