### ISSUE TITLE
Switch to itchSetup

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1093]
This is just a checklist of things to do before moving to the new install system:

  - [x] win: Common Forms GUI https://github.com/itchio/itchSetup/commit/804b3d26b0f573379997473a7b9724e01d00f550
  - [x] mac: Cocoa GUI https://github.com/itchio/itchSetup/commit/2deff7fd51734f3877036f7b03e207f020c8d6ca
  - [x] linux: GTK3 GUI https://github.com/itchio/itchSetup/commit/3f5b98022123fc63f8c7eb1712d5fc74d69f45ac
  - [x] setup: Find & extract latest build https://github.com/itchio/itchSetup/commit/2129316a5a0d668a9340a2241f3c717a26cb989f
  - [x] mac: relauncher https://github.com/itchio/itchSetup/commit/ec6432df7c45c4fff2d61161835c3224514cd871
  - [x] mac: verify bundles before installing https://github.com/itchio/itchSetup/commit/230f78d4fa5aff4db948b78850f51e8ee64a62ac
  - [x] win: create uninstaller registry entry https://github.com/itchio/itchSetup/commit/75c1db5df4ac1d28cab4b167e241720fd78ed62a
    - [ ] and use UncompressedSize for estimated size instead of os.Walk
    - [ ] and update it on update
    - [x] and remove it on uninstall https://github.com/itchio/itchSetup/commit/a8cfee439a990e380047a67438b05c8d98f5674c
  - [x] win: create shortcut on install https://github.com/itchio/itchSetup/commit/e57fb6197f26a36ad778098f9b014ed85183b220
    - [ ] and update it on update
    - [x] and remove it on uninstall https://github.com/itchio/itchSetup/commit/a8cfee439a990e380047a67438b05c8d98f5674c
  - [x] win: install versions in separate folders https://github.com/itchio/itchSetup/commit/a8cfee439a990e380047a67438b05c8d98f5674c
    - [x] and have itchSetup launch the most recent one https://github.com/itchio/itchSetup/commit/81ac256ef3226612a2ae429d3b5be769b3ca6745
    - [x] have itchSetup's own relaunch logic because shortcut points to itchSetup https://github.com/itchio/itchSetup/commit/81ac256ef3226612a2ae429d3b5be769b3ca6745
    - [ ] and clean up older versions when updating
  - [x] win: kill running instances when uninstalling https://github.com/itchio/itchSetup/commit/019a2068002280a6d8a3bbb70dfeda9c39c87cb7
  - [x] support building for itch and kitch
    - https://github.com/itchio/itchSetup/commit/f19cd4fbee0b644f3c3b88c166c0b007c358075a
    - https://github.com/itchio/itchSetup/commit/1f861ff339a5a967e3dda5c9c90969b0fdd92de5
    - [x] create kitch project and add it to itchSetup
  - [ ] win: implement --squirrel-install etc. logic
  - [x] vendor all dependencies of itchSetup https://github.com/itchio/itchSetup/commit/df5f6b2960302d3a0a8f00b1eceae73d736ab287
  - [x] i18n the entire itchSetup thingy https://github.com/itchio/itchSetup/commit/8f4fc13175b7acddcf4d7cb1cddec69fae519d72
  - [ ] find upgrade path
    - [ ] and fall back to verify+heal
    - [ ] and fall back to full redownload
    - [ ] while respecting platform-specific upgrade strategy
  - wharf backend:
    - [ ] add changelog
    - [ ] add option to enforce semver
  - [x] make setup compile on CI, all platforms https://github.com/itchio/itchSetup/commit/912abb5d35ae7179484a35eb328ca38c4efcfbeb
    - [x] windows, linux: and UPX it https://github.com/itchio/itchSetup/commit/310e0303f06a1f72d120e84353a9eefd9dac05bf
    - [ ] and package mac as an .app
  - [x] make itch not complain if Update.exe is gone 729f521f4f48dd355eb0b758044d37d485681913
    - [ ] and spawn itchUpdater to update shortcut instead
  - [ ] design command-line interface for update operation
    - [ ] and JSON output format
    - [ ] and have the app call to and consume it
  - [ ] have app pass proxy settings and itchSetup respect it
  - [ ] add ibrew formula for itchSetup
    - [ ] change CI build to deploy there
    - [ ] mac: add special case to find executable inside .app bundle
    - [ ] win: add special case to install itchSetup to `%LOCALAPPDATA%/itch`
  - [ ] have itchSetup send telemetry events when
    - [ ] install starts
    - [ ] install completes
    - update completes
      - [ ] incremental
      - [ ] heal
      - [ ] download
  - [x] modify butler to accept API key via environment variable https://github.com/itchio/butler/commit/2a440fdef58bff4717d674343cc55e0ade821e33
  - [x] change CI config of itch to push builds to butler https://github.com/itchio/itch/commit/fe1d63c751ca0856fcf191784c8f3372a6ddc8fd
  - [ ] scope down hard-coded download API key better, or find key-less way to do it
- [ ] change itch.io/app to distribute itchSetup instead of normal builds

**Comment by aaronfranke** [comment]
Is there an ETA for the completion of this checklist? It seems you have been working on it for quite some time, half a year or so. I ask because a major change like this seems to be an obstacle for other improvements such as #1135 and who knows what else.

**Comment by fasterthanlime** [comment]
> Is there an ETA for the completion of this checklist?

That is a very fair question, and - there isn't an ETA at the moment.

I'm super excited about itchSetup to make the whole install & self-update process smoother, and allow us to ship updates faster.

However, before that happens:

  - There is a "stability update" in the works for the whole app (completely unrelated to the install/self-update process). You can track its progress [on this branch](https://github.com/itchio/itch/tree/sqlite-first) (which will get merged to master as soon as feature parity is reached) and [this project](https://github.com/itchio/itch/projects/1)
  - When that's done, I'll take a break from "infrastructure work" and ship a few features @leafo has been asking for (game ratings, collections management, etc.)
  - There's also https://github.com/itchio/capsule which has been pending for a while now, and would definitely have more immediate impact than itchSetup.

---

There are things blocked by itchSetup, such as:

  - Allowing the app to be installed in a folder that isn't `%LOCALAPPDATA%/itch` on Windows
  - Never seeing an obscure .NET stacktrace again
  - Serving downloads+updates of the app itself via our CDN, rather than github releases (ie. Amazon S3)
  - Not having a large majority of Linux users lag a few versions behind because, I get it, it gets annoying to manually download a new .deb/.rpm - and the repo setup thing is in the docs, but not automated. So it's not the users' fault, just a consequence of how things are set up right now.

However, #1135 is not one of them. I'll address it directly in that issue's thread, since I have more info about it now than I did back then.

**Comment by aaronfranke** [comment]
Thank you for replying. The future looks good, I very much appreciate the effort to make a better distribution system. I did recently add the Itch app to my [Linux-tools program install script](https://github.com/aaronfranke/Linux-tools/blob/master/ubuntu-only/programs-to-install.sh) since I didn't want to have to look up the install guide again, with its many commands.

**Comment by fasterthanlime** [comment]
Hey v25 did ship with itch-setup! Closing this.
