### ISSUE TITLE
Documentation about Linux sandboxing is incorrect (or there's a problem)

### ISSUE THREAD

**Issue by jgandert** [itchio/itch#1095]
I followed the manual steps here https://itch.io/docs/itch/using/sandbox/linux.html
```
sudo chown root:root ~/.config/itch/bin/firejail
sudo chmod u+s ~/.config/itch/bin/firejail
```

I'm on Ubuntu 16.04. When I executed `~/.config/itch/bin/firejail whoami && echo "All good!"` I got "Permission Denied".

Only when executing the above with sudo, I get "All good!"

Edit: Interesting. Now after starting, I get "There was a problem during setup: unarchiver failed: firejail .." and I can't start itch anymore. After removing the SETUID bit, it starts again.

**Comment by fasterthanlime** [comment]
Can you post the results of `ls -lhA ~/.config/itch/bin/firejail` ? Here's what I get:

```
$ ls -lhA ~/.config/itch/bin/firejail
-rwsrwxr-x 1 root root 303K Jun 20  2016 /home/amos/.config/itch/bin/firejail
```

Both the manual & automatic procedure work here. Which itch version are you running, btw?

**Comment by jgandert** [comment]
After `sudo chmod u+s` this was:

-rws------ 1 root root 303K Jun 20  2016 

22.2.0

I have now set the same permissions and it works.

**Comment by fasterthanlime** [comment]
> After sudo chmod u+s this was:
> 
> -rws------ 1 root root 303K Jun 20 2016

Ah yes, that won't work :) `o+x` needs to be set. Any idea why it had such permissions in the first place, though? When extracted from the 7z archive and instructions are followed, it has the correct permissions!

```
amos at watson in ~/.config/itch/bin 
$ curl -L -O https://dl.itch.ovh/firejail/linux-amd64/v0.9.41/firejail.7z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95255  100 95255    0     0   159k      0 --:--:-- --:--:-- --:--:--  159k

amos at watson in ~/.config/itch/bin 
$ ./unarchiver/unar firejail.7z
firejail.7z: 7-Zip
  firejail  (309496 B)... OK.
Successfully extracted to "./firejail".

amos at watson in ~/.config/itch/bin 
$ ls -lhA firejail
-rwxrwxr-x 1 amos amos 303K Jun 20  2016 firejail

amos at watson in ~/.config/itch/bin 
$ sudo chown root:root firejail

amos at watson in ~/.config/itch/bin 
$ sudo chmod u+s firejail

amos at watson in ~/.config/itch/bin 
$ ls -lhA firejail
-rwsrwxr-x 1 root root 303K Jun 20  2016 firejail
```

Did you run any other commands, by chance? What happens if you run `touch firejail-fake && ls -lhA firejail-fake` ? and what's the output of `cat /etc/mtab | grep "/\s"`

**Comment by jgandert** [comment]
I don't remember any particular commands I ran, but maybe I set the wrong permissions while restoring the earlier state, when the sandbox didn't work.

However, I think I got the "Permission denied" right after the very first time I entered the two commands from the docs. Does it matter if itch is still running while running them?

`touch firejail-fake && ls -lhA firejail-fake` returns these permissions:

-rw-rw-r-- 1 anon anon 0 Dez 30 15:45 firejail-fake

Anyway, in hindsight I may have caused this, so feel free to close this. I'll create a new report if something pops up again. Thanks! :)

**Comment by fasterthanlime** [comment]
> However, I think I got the "Permission denied" right after the very first time I entered the two commands from the docs. Does it matter if itch is still running while running them?

Shouldn't matter (as long as nothing is being actively launched with firejail - but since it wasn't SUID yet it couldn't have)

> Anyway, in hindsight I may have caused this, so feel free to close this. I'll create a new report if something pops up again. Thanks! :)

I'll close now since the issue is fixed for you but I'm glad this thread exists in case someone encounters the same problem! (Dear someone if you found this thread by google, comment with your situation, please!)
