### ISSUE TITLE
🏁 Can't download any game -- v22.2.0

### ISSUE THREAD

**Issue by Xananax** [itchio/itch#1098]
Dear itch app team, every time I download a game, I get

```
getting expired URLs from URL source (timezone issue?)
```

The only reference to this error I could find is [here](https://git.itch.ovh/itchio/httpkit/blob/4b8efa7b22b0120e12877c016e43bda74f16e016/httpfile/httpfile.go#L169).

This can happen 16% in a download, so I doubt it's a URL thing; also, a few games did download without a hitch.

My assessment: this has nothing to do with expiration or timezones, this is just a timeout due to my connection being very slow these days.

on Win10 by the way

**Comment by fasterthanlime** [comment]
> My assessment: this has nothing to do with expiration or timezones, this is just a timeout due to my connection being very slow these days.

I concur. Also, I've been working on exactly this yesterday, so I'll finish up my work and deploy it today and we'll see if that helps!

**Comment by fasterthanlime** [comment]
butler v2.3.0 is out, and it should try a bit harder in the face of slow/unreliable connections. Can you give it a shot? All you need to do is:

  * Quit the itch app (Ctrl+Q) - don't just close the window
  * Start it up again

That'll update butler to the latest version (you might see "Updating dependency butler to v2.3.0" flashing briefly - or less briefly, depending on your connection). Then try downloading a game again, let me know if it improves/worsens things!

**Comment by Xananax** [comment]
> or less briefly, depending on your connection

Indeed, after a brief 12 minutes long flash (my connection is really slow you guys have no idea how bad we have it in non-1st world countries), it worked better :) Thanks!

**Comment by fasterthanlime** [comment]
Hey, glad it helped you! Makes working on this feel more purposeful :) I'm guessing we can close this issue then?

**Comment by Xananax** [comment]
Yea, we can, but actually, the problem is not games not downloading (I was considering opening a different issue for that), but about the message; if I wasn't a bit code-savvy, I would have no idea what the error message meant; I'd argue it should be changed for the more vague yet more common "connection timed out".

**Comment by fasterthanlime** [comment]
Thankfully, [that message is now gone](https://github.com/itchio/httpkit/commit/80d30c13228746c60ffa0d1ced5ba0b2e1bc5194#diff-3616e21372ef53afe11ab914e30438faL193)!
