### ISSUE TITLE
Remove 'mtime comparison' behavior when installing archives

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#1099]
Exodemon keeps updating, yet hovering over the "Version" the popup says it's November 1st.

So, is it updating, or is it downloading junk data?

Logs: 
itch.txt https://gist.github.com/LiamDawe/3d88549b7cecd1781deec924c8ba5199
itch_updater.txt https://gist.github.com/LiamDawe/cd5f04d5ce9ee7170ddd2073d97309a6
game log: https://gist.github.com/LiamDawe/358f8afade5d9ec69d0a68ea3861b1e2

Timezone: GMT

I can reproduce it by telling Exodemon to update, the app says it's up to date, but then the desktop notifications tells me it was updated.

**Comment by fasterthanlime** [comment]
Oh, it's because of their halloween version u_u'.

They pulled it out, so now there's an *older* upload (0.3.92) that's the "best upload" when the updater is looking for updates. But since it's not newer, the installer isn't installing it. I'll work on a fix.

**Comment by LiamDawe** [comment]
Any movement on this? Had to remove the game due to constant notifications and downloads for it.
