### ISSUE TITLE
"Play In Browser" games need to be handled better

### ISSUE THREAD

**Issue by AethericGames** [itchio/itch#1100]
Ideally, html5 and flash games should run in the itch browser, if and when that's possible. If it's not possible, there should be some kind of indication that something is missing from the page, with a link to open it in the default browser.

Currently, if you look at the page for a "Play In Browser" game, it just looks like the normal page, except the game is not there. Rather than skipping the incompatible content, why not replace it with a big fat button that says "Play this game in your default browser" or something similar.

**Comment by fasterthanlime** [comment]
> Currently, if you look at the page for a "Play In Browser" game, it just looks like the normal page, except the game is not there

Except you can install it, and then play it, like any ol' game :)

Flash support is probably off the table, don't want to be responsible for this particular attack vector.

**Comment by AethericGames** [comment]
I can totally understand not wanting to support Flash! That's probably a good call.

Unfortunately, I'm not seeing an install button when "Kind of Project" is set as Flash, and the "This file will be playable in the browser" option hides the compatibility options. (Not sure about html5 as I've only tested with flash.) It would best if there was some indication that something is missing, otherwise it just looks like the game is unfinished or broken.

As a work around, I'll upload a separate downloadable swf file.

**Comment by fasterthanlime** [comment]
itch v25 does show "Open page" for Flash games:

![image](https://user-images.githubusercontent.com/7998310/45692455-1a274780-bb5b-11e8-8240-6ede25968eac.png)
