### ISSUE TITLE
App shouldn't keep downloaded files around after install

### ISSUE THREAD

**Issue by readingsnail** [itchio/itch#1101]
Dear itch app team, so downloaded app file is not useless aren't you?

so, i want to clear downloaded app file menu (yeah, like /Users/hitchhiker/Library/Application Support/itch/download) i think it's useless, why? updating -> redownload -> cache is stack -> my SSD storage is so painful...

**Comment by fasterthanlime** [comment]
I agree - I'm working on changing how the app handles the downloads folder.

Currently, it keeps around downloaded files as long as a game is installed - for faster reinstall.

In the next versions, it won't! Just a little bit of patience and the problem will resolve itself :)

In the meantime, you can remove all files in the downloads folder manually, it doesn't impact how itch runs!

**Comment by fasterthanlime** [comment]
> In the next versions, it won't!

And so the next version has shipped, and it doesn't keep those files around!
