### ISSUE TITLE
VC+ 2015 Redist Prerequisite

### ISSUE THREAD

**Issue by EmptyKeys** [itchio/itch#1102]
Would be cool to have this one avail and supported by App manifest.

**Comment by fasterthanlime** [comment]
Agreed! I need to take some time to complete our prereqs database, the .NET Runtimes belong in there too (see #1096 and #1061)

**Comment by EmptyKeys** [comment]
Cool. Yeah, i know about other ones, DirectX too.  Thanks, for adding those.

**Comment by fasterthanlime** [comment]
I've worked on this today, made good progress. Since the 2015 runtime is a bit larger, I've been working on UI to indicate progress, so the player doesn't feel lost. It'll land in the next app version :)

**Comment by EmptyKeys** [comment]
Perfect, thanks.

**Comment by fasterthanlime** [comment]
This is shipping in v23.0.0 which should be out any minute!

**Comment by EmptyKeys** [comment]
Great. I will test in this week. :)

**Comment by EmptyKeys** [comment]
Did few tests and something is wrong. I will open new issue.
