### ISSUE TITLE
no tray icon on KDE

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#1106]
Using KDE on Antergos (Arch Linux), there is no tray icon for the itch app

**Comment by fasterthanlime** [comment]
Does KDE support libappindicator (and, do you have it installed?)

**Comment by LiamDawe** [comment]
Well, I have libappindicator-gtk2 installed apparently.

**Comment by LiamDawe** [comment]
I should note, that this is the only application that doesn't give me an icon in the KDE tray.

Are there any logs I can provide from the app or KDE that could help solve this?

**Comment by RavenRohr** [comment]
Same thing happens with KDE on Mint 17 for me, though you can still interact with the spot where the icon should be as though it were there, you just can't see it.

**Comment by LiamDawe** [comment]
Yeah, same on KDE Antergos, there's a space where it should be and I can also interact with it. Just the image hasn't loaded. Wrong format or location possibly?

**Comment by fasterthanlime** [comment]
I've tried reproducing this by installing Plasma on my Elementary install and it was broken all over (way before launching itch). I'll try with a VM of a kde-centric distro, stay tuned.

**Comment by LiamDawe** [comment]
Any movement on this? :)

**Comment by notklaatu** [comment]
This works correctly for me on 23.1.1 and 23.4.0 using both KDE4 on Slackware and 5 on Fedora.

**Comment by LiamDawe** [comment]
I still don't get an icon btw, up to date KDE on Ubuntu 17.04.

**Comment by forest-hermit** [comment]
It's there (and clickable) but it doesn't show any icon. Hope it could be solved with minor effort.

![screenshot_20170724_184307](https://user-images.githubusercontent.com/11406902/28534149-f366ad4a-709f-11e7-84bf-f5b002815112.png)

**Comment by fasterthanlime** [comment]
If someone wants to get a fix in for this, I'm fairly certain following the [Setting up itch for development](https://itch.io/docs/itch/developing/getting-started.html) guide and finding out what goes wrong on kde exactly would be faster than me spinning up a VM for that :)

The relevant code is here: https://github.com/itchio/itch/blob/master/src/reactors/tray.ts

**Comment by forest-hermit** [comment]
My specs:

![kinfo](https://user-images.githubusercontent.com/11406902/28542471-89b4a6f0-70bc-11e7-9374-43e41e550278.png)

**Comment by LiamDawe** [comment]
Just an update, on Ubuntu 17.10 itch also no longer has a tray icon.

I think Ubuntu with the move to Gnome Shell now uses this by default: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by afettouhi** [comment]
I can confirm this on Arch Linux as well with KDE Plasma 5 (5.11.3 as of this writing) and kitch 24.8.0.

**Comment by fasterthanlime** [comment]
Quick update: Ubuntu 17.04 and Ubuntu 17.10 ~let us all down~ broke tray icons in two different ways, see

  * 17.04: https://github.com/electron/electron/issues/9046
  * 17.10: https://github.com/electron/electron/issues/10887

The 17.10 fix mentions that electron 1.8.0 uses Chrome 60, which has ~dirty dirty workarounds~ a fix for recent Ubuntus apparently.

Seeing how itch v25's schedule got way out of control, it's not unreasonable to think that it'll ship with electron 1.8.0, fixing this issue ~once and for all~ for the time being.

**Comment by vanyasem** [comment]
To get the icon working on KDE you need to _remove_ `libappindicator-gtk2` at all (or replace with a dummy package).

For Arch that would be `sudo pacman -Rdd libappindicator-gtk2` (ignoring dependencies).

After removing the package, the icon is back. Other apps that depend on libappindicator **won't break**.

Same applies to Electron apps that depend on `libappindicator-gtk3` (e.g. riot-desktop).

![2018-01-05-005412_199x103_scrot](https://user-images.githubusercontent.com/13350458/34585959-db78ff64-f199-11e7-90f2-aa28566280bd.png)

**Comment by vanyasem** [comment]
To get the icon working on KDE you need to _remove_ `libappindicator-gtk2` at all (or replace with a dummy package).

For Arch that would be `sudo pacman -Rdd libappindicator-gtk2` (ignoring dependencies).

After removing the package, the icon is back. Other apps that depend on libappindicator **won't break**.

Same applies to Electron apps that depend on `libappindicator-gtk3` (e.g. riot-desktop).

The icon is noticeably lower in quality than the ones from "native" apps on a HiDPI monitor, but still better than having no icon at all. 

![2018-01-05-010109_3840x155_scrot](https://user-images.githubusercontent.com/13350458/34586205-e916a1fc-f19a-11e7-86e2-20dccc4b84ca.png)

**Comment by forest-hermit** [comment]
In Kubuntu 18.04 still happens.

**Comment by fasterthanlime** [comment]
> In Kubuntu 18.04 still happens.

Unsurprising, as there have been no updates :) Subscribe to #1766 to test the new version in advance!

**Comment by forest-hermit** [comment]
I test it with Kitch yesterday and still happens.
