### ISSUE TITLE
"Help Translate Itch in Your Language": dead link (and probably wrong percent)

### ISSUE THREAD

**Issue by Xananax** [itchio/itch#1107]
The language progression for `En-Us` is reported at 56%; I assume this is wrong?
![itch.io app](http://i.imgur.com/5FsT0Oa.png)

Also, when clicking on the link, this page is reached:
![dead page on ovh](http://i.imgur.com/BYQTAFW.png)

On Windows 10, using v23.0.0

**Comment by quyse** [comment]
Oh, also I remember the text "translated NN%" on the link used to be itself translated in the current language. Now it always says "translated" in English. Probably it went this way after Weblate upgrade.

**Comment by fasterthanlime** [comment]
I have no earthly idea where weblate is pulling the "en-US" % from.. maybe an average of all translations? I could special-case it so it just doesn't show up.

**Comment by Xananax** [comment]
Well it's really low importance, but yea, if it's an easy fix, worth it for that extra 0.001% of polish.

**Comment by fasterthanlime** [comment]
Both the percentage and the link seem correct in itch v25.
