### ISSUE TITLE
🏁 Suggestion: Add already downloaded games

### ISSUE THREAD

**Issue by SableDante** [itchio/itch#1110]
Dear itch app team, 

As a suggestion, a way to install already downloaded games to the Itch app would be lovely.  I have already downloaded a dozen or so games manually and I can find no way to add them to this app without re-downloading them.

Thanks,

**Comment by fasterthanlime** [comment]
So, the main issue with that is knowing which version of the game you have. I guess as a simple first step, the app could just assume whatever you have is the "current version" and suggest you update when another update comes out?

What I'd rather do though is have the app check the contents of the game you're importing, and figure out which version it is (and repair it if needed).

**Comment by SableDante** [comment]
As a suggestion, wouldn't it be easy to contain the game version in an xml in the zip file, that way the itch.io program could see what version is the zip file contains and then update as necessary?

**Comment by fasterthanlime** [comment]
> As a suggestion, wouldn't it be easy to contain the game version in an xml in the zip file, that way the itch.io program could see what version is the zip file contains and then update as necessary?

Unfortunately, developers control the contents of zip files, not itch.io - otherwise, that would've been an option.

Technically, developers using https://itch.io/docs/butler/ have .zip archives generated itch.io side, but that's still a minority of games nowadays, so the app should cater for both butler-powered and non-butler-powered games.

**Comment by SorenSaket** [comment]
Couldn't you use the receipt.json to track the version, or are you already doing that? If so It would be that hard to detect already installed games.

**Comment by fasterthanlime** [comment]
> Couldn't you use the receipt.json to track the version, or are you already doing that? If so It would be that hard to detect already installed games.

v25 does that - but that doesn't do anything for games installed manually (by extracting a .zip file downloaded directly from the website!)

**Comment by SorenSaket** [comment]
I have the games I installed via a previous itch client, so the receipt.json file where there. Then when I reset my pc, I re downloaded itch. The games installed previously didn't show up even though i targeted the folder they where in.

**Comment by fasterthanlime** [comment]
> I have the games I installed via a previous itch client, so the receipt.json file where there. Then when I reset my pc, I re downloaded itch. The games installed previously didn't show up even though i targeted the folder they where in.

Yup, that's what happens with v23, the current stable version.

v25 is not released yet, I've been working very hard to get it released for a while now!

**Comment by fasterthanlime** [comment]
> v25 is not released yet, I've been working very hard to get it released for a while now!

v25 has been released, it works as advertised.
