### ISSUE TITLE
🏁 Suggestion: Add the option to remove a single game from a collection

### ISSUE THREAD

**Issue by jakopo87** [itchio/itch#1112]
There is an option to delete the entire collection, but not one to remove a single game from it

**Comment by leafo** [comment]
If you go here: https://itch.io/my-collections and hover over the game in question there's a remove button. Does that work for you?

**Comment by jakopo87** [comment]
yes, i found it later, tho it would be useful to have it inside the collection too, because it is a little hard to find

**Comment by fasterthanlime** [comment]
> yes, i found it later, tho it would be useful to have it inside the collection too, because it is a little hard to find

I agree. Since this is the app's issue tracker: full collection management is planned inside the app, so I'm closing this: it's already part of our roadmap :)
