### ISSUE TITLE
🏁 Issue v23.1.0

### ISSUE THREAD

**Issue by DethBringa** [itchio/itch#1117]
Dear itch app team, Itch is great except 2 things that I think need added:

1) The "back" mouse button doesn't work in app. 
A small annoyance and would be nice to be able to just press the back button on my mouse instead of the back arrow at the top.

2) right click, open in new tab. 
This (imo) is a VERY needed feature in the app. Its quite frustrating when browsing to see something that looks interesting, check it and find its not, then have to press the back button and scroll all teh way down to where you were before.

**Comment by fasterthanlime** [comment]
> The "back" mouse button doesn't work in app.
> A small annoyance and would be nice to be able to just press the back button on my mouse instead of the back arrow at the top.

So I just looked into it and it's not something electron supports out of the box yet: https://github.com/electron/electron/issues/6996 - I suggest commenting on that thread to express your interest!

> right click, open in new tab.
> This (imo) is a VERY needed feature in the app. Its quite frustrating when browsing to see something that looks interesting, check it and find its not, then have to press the back button and scroll all teh way down to where you were before.

Actually, you can do it right now with ctrl-click, middle-click (or meta-click on macs)! I've been wanting to add a context menu even in web views though, so let me take a look at this now.

**Comment by fasterthanlime** [comment]
The next version will have a "Open in new tab" context menu (with proper behavior!)
