### ISSUE TITLE
API invalid key

### ISSUE THREAD

**Issue by SkyTech6** [itchio/itch#1118]
https://itch.io/api/1/KEY/game/#####/download_keys?user_id=######

Hello, I passed in the app manifest (in Itch App) api key to this GET and it returned 

{"errors":["invalid key"]}

I believe that error is saying that the KEY parameter is wrong? When it is what gets returned by ITCHIO_API_KEY environment variable (which works in my other GET calls). 

----

Another interesting note about this call is that if I try this call with my Web API Key then it tells me that 

{"errors":["invalid game_id"]}

When I'm absolutely certain that's not an invalid game_id, it's the game_id of a game that a fellow developer publicly sells here on itch.

----

UPDATE: Sorry! I was getting so confused until I found that comment on another issue for the fix (mentioned in comment below)... please do close. No issue here.

**Comment by SkyTech6** [comment]
Hmm.... 

https://github.com/itchio/itch.io/issues/536

I found there that you say to use our specific api keys in the KEY parameter instead of the Session Key, is that correct?

**Comment by fasterthanlime** [comment]
See the "Making requests with the API key" section of this page: https://itch.io/docs/itch/integrating/manifest.html

P.S: don't post API keys in public github issues :)

**Comment by SkyTech6** [comment]
Opps, my bad. Edited it out.
