### ISSUE TITLE
Dragon Game Designs

### ISSUE THREAD

**Issue by barmage** [itchio/itch#1122]
I have recently purchased the package of 3 rpg games from this developer and am having problems with them. Firstly none of the three games will run after install through your app. Secondly if I download and install independent of your app Mines of Grimvale will not run but the other 2 do run ok. Please advise.

**Comment by fasterthanlime** [comment]
Hey - for Mines of Grimvale, you should get in touch with the developer directly - their e-mail is at the bottom of [that page](http://dragongamedesigns.com/sotg/index.html).

For the two others: did they come as an installer? (when you double-clicked the .exe, did it show a few steps, ask for an install location etc.? It might be an installer type that's not supported by the app. You could mention it to the developers if you're already reaching out - feel free to point them to this page: https://itch.io/docs/itch/integrating/platforms/windows.html

Thanks!
