### ISSUE TITLE
Cannot purchase anything if IP address is wrong (because of VPN)

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1128]
```
Sorry, we can't accept your purchase at this time due to the updated 2015 VAT regulations. Your billing address does not match your purchase location (NL).
```

Because of VPN enabled my IP address (Netherlands) doesn't correspond to my billing address (Russia). It's very annoying to fill out the whole form and get only this.

I understand it's probably up to your payment provider, and I'm not sure if you can do something about this. Still it's stupid, after all they probably can figure out themselves that my credit card is from Russian bank if they don't trust what I'm typed into. <s>Also I thought you're a US-based company, so there're no EU regulations in between.</s> Nevermind, the guys who made the game are in EU.

For example, Steam allows me to purchase anytime whether VPN is enabled or not.

Even if I pay with Bitcoin it still asks for address and denies payment.

**Comment by quyse** [comment]
And to make it actual bug report and not just rant, it's impossible to copy bitcoin address from the app on my Linux system. It's a link and not selectable, clicking it sends to google (probably because I don't have bitcoin protocol handler registered, I'm using web app), and `copy` button doesn't work.

**Comment by quyse** [comment]
Ok, game is bought, sorry for the noise. Feel free to close the issue if nothing can be done about it :)

**Comment by leafo** [comment]
Sorry, because of how we need to collect VAT for buyers in the EU we force people with european IP addresses to see this form. Maybe a good solution would be to skip the requirement if they provider a billing address that is outside of the EU
