### ISSUE TITLE
Itch.io App Game Installation Problem.

### ISSUE THREAD

**Issue by iPushObeseKids** [itchio/itch#1130]
Dear itch app team, ​I tried downloading a game from the app and it took a long time and didn't go up in percentage for a long while, so i just let it run in the background. I checked on it and it says an error occurred, I tried again and after a long amount of time the same thing happened. For the record, I have never used Itch before so I am unaware of what may be causing the problem. I have the app installed too, I even tried uninstalling and reinstalling the app then trying it, which didn't help. I tried downloading and installing another game instead to see if it was the game itself, which wasn't the case. It has nothing to do with my internet either, I have around 75 megabits per second download and upload speed. I looked online for a little while and couldn't find any answers, please help me so I can play. (Also if some terminology is wrong like the download and upload speed its because I'm not that smart with computers).

**Comment by fasterthanlime** [comment]
Our CDN has been acting funny these past few days, retrying it now might just work.

We're still looking into these issues.

**Comment by iPushObeseKids** [comment]
Okay well I now feel dumb, a simple restart of my computer fixed it. I knew it had to be something simple and stupid xD
