### ISSUE TITLE
🏁 Issue v23.2.1

### ISSUE THREAD

**Issue by s33k3r86** [itchio/itch#1131]
Dear itch app team, 

I purchased the play for peru bundle for $2, so that I could get all of the games on the list, and didn't receive an email for downloads, nor did I have it credited to my profile/my games on the app. I can confirm that I had $2 deducted from my bank account so it would be great if I could get that email sent with the game downloads. I would like that email - and all future emails for purchases made on itch.io - to be sent to s33k3r86@protonmail.com. This should alleviate any future issues. Thank you.

s33k3r
![screenshot_20170211-073549](https://cloud.githubusercontent.com/assets/24859208/22854988/46c3ab26-f02d-11e6-9cab-2f3d58b915cb.png)
![screenshot_20170211-073554](https://cloud.githubusercontent.com/assets/24859208/22854991/4ce08664-f02d-11e6-9caa-d1640145d79b.png)

**Comment by leafo** [comment]
Hey, our support email is the best place to get in touch with us for lost purchases: support@itch.io

Keep in mind, if you already know what email you used to complete the purchase then you can use thsi page to recover the purchase: https://itch.io/docs/buying/already-bought

If you're not sure, or  you may have entered the wrong email, then make sure you include PayPal transaction ID or the name on your card when you email our support address.

Thanks
