### ISSUE TITLE
Suggestion: autodetect Operating System

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1134]
Is there a way to automatically detect which OS the client is running on and show me the games I can actually buy and play (e.g., show only macOS-tag games on start)?

**Comment by mattiascibien** [comment]
@fasterthanlime about this I think that identifying the underline os is a pretty simple task with node. Is there any way to query the itch.io API to filter based on OS?

**Comment by fasterthanlime** [comment]
The app does detect your os & filter games in native views (when you pick the 'Compatible' filter) - as for the website, it filters the homepage by default, but not other pages.

This is actually a website feature request!

**Comment by mattiascibien** [comment]
Ok... Sry.

Ottieni Outlook per Android<https://aka.ms/ghei36>


________________________________

**Comment by fasterthanlime** [comment]
The front page does show only games compatible with your OS now!
