### ISSUE TITLE
Close tab 'cross' icon is shown atop menu

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1136]
...and even clickable.
![image](https://cloud.githubusercontent.com/assets/416215/23043610/eebc8f9e-f4ad-11e6-8eeb-794ce02d0d2f.png)

**Comment by fasterthanlime** [comment]
Now that's efficiency!

Jokes aside, I think this might be a remnant of CSS hacks we added to make hint.css work (which we don't use anymore)

**Comment by mattiascibien** [comment]
I found the thing. It seems that the zindex is set to 100 when inpsecting with DevTools. Fixed with #1145
