### ISSUE TITLE
Use-case: game jams

### ISSUE THREAD

**Issue by Alloyed** [itchio/itch#1137]
So I like participating in gamejams, and beyond submitting games I also try to play as many as I can.

The itch app helps a lot with getting a game downloaded and running and all that, but the workflow for lots of small games is less than ideal IMO. Here's the process I've got so far
1. go to gamejam page
2. click on _every_ game, add to collection "name of gamejam"
3. install and play the game. I keep track of whether or not I've played X game, whether or not I've got a good recording of me playing it, did I upload the video etc. on a piece of paper.
4. If I think I'm done with the game I'll remove it from the collection, so I can get that dopamine rush of a todo list getting smaller

And my problems with this, explicitly stated:
* step two is a major hassle, especially because I'm going to be adding every game no matter what. Sometimes games get added after I do this and I can completely miss them, too.

Adding a simple "add all games to collection" button would fix this handily, but it might be hyper-specific to me  ¯\\_(ツ)_/¯ 
* keeping all the information in 3 out of band like I am makes it hard to use and go back to. Every time I want to pick out a new game I have to to go make sure I haven't done anything with it, and then sometimes I have to go back and re-add a game because I messed up the recording. This is problem that I'm sure all sorts of people could have, from let's players to people who form backlogs of games.

A tag system seems ideal, but that sounds hard. a "notes" field, having the games marked by whether or not you've played them would also be nice, and maybe easier to implement? Actually, saying the word "backlog" gave me a silly idea: trello, but for games you still need to play.

This is a bit of a braindump so if you like more feedback or clarification feel free to ask. Again, even having an itch app at all is super useful, so ty~

**Comment by fasterthanlime** [comment]
In-app collection editing is definitely been asked for a lot, so it's on my radar. Mass-add / mass-install is also something I'm looking at!

As for notes/tags, it's lower-priority but also definitely worth looking into in the future!

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/907
