### ISSUE TITLE
🏁 Issue v23.2.1

### ISSUE THREAD

**Issue by tomking0019** [itchio/itch#1138]
Dear itch app team, 

As someone who uses an SSD for their OS, it would be nice for you to add the option in the installer to change the installation directory or change the directory in which games are installed to.

Thanks.

**Comment by fasterthanlime** [comment]
> change the directory in which games are installed to.

Already a thing! See "Install locations" in Preferences.

> change the installation directory

This'll come with itchSetup, see #1093
