### ISSUE TITLE
Prevent screen from sleeping/screensaver showing up while playing

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1139]
Not every game prevents screen from turning off or showing up screensaver after some time of inactivity. The specific problem I have is that playing on Linux with gamepad doesn't count as "activity", so every 5 minutes screen goes dark right in the middle of game session. Maybe itch app can prevent that during game sessions? I can see usage of `powerSaveBlocker` API in `html.ts`, may it also work for native games? Also a checkbox in settings for that behavior (enabled by default) would be nice.

**Comment by quyse** [comment]
Well, using `powerSaveBlocker` works for native games too. I'll make a PR if you don't mind!

**Comment by fasterthanlime** [comment]
Yeah, that's a good idea, go ahead! 👍
