### ISSUE TITLE
Could not access remote file (Costa Rica / Central America)

### ISSUE THREAD

**Issue by Leosolano229** [itchio/itch#1142]
Dear itch app team, 

Hello, my name is Leo
![itch](https://cloud.githubusercontent.com/assets/24537948/23107340/109951dc-f6c1-11e6-8376-2b58a33227e6.png)

I'm using Windows 10, and itch version 23.2.1

I'm having the problem "could not access remote file" every time I try to download any game, not only the one I'm downloading  at the moment. 

If someone could help me I would appreciate it.

Thanks.

P.D: Screenshot of the error attached

**Comment by fasterthanlime** [comment]
Hey Leo,

Which country are you downloading from?

**Comment by Leosolano229** [comment]
Costa Rica (Central America)

**Comment by Leosolano229** [comment]
Hello?

**Comment by fasterthanlime** [comment]
Hey - have you tried again recently? Could be a temporary error.

**Comment by Leosolano229** [comment]
No :( It's been like that for about two weeks now

**Comment by fasterthanlime** [comment]
If you hover over the error message, what does the tooltip show ? (esp. the end of the message).

Does it end in "or established connection failed because connected host has failed to respond" ?

**Comment by Leosolano229** [comment]
No not really, It's just numbers

**Comment by fasterthanlime** [comment]
Is this still happening ?
