### ISSUE TITLE
Certificate error: net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#1148]
I'm getting the following error dialog when running Itch. I haven't run it in a while, so I'm not sure how long this has been going on. I was running v22.0.0 (or so) and it self-updated to v23.2.1. I experienced it both before and after the update today.

>There was an error with the certificate for www.google-analytics.com issued by Cisco Umbrella Secondary SubCA sea-SG.
>
>Please check your proxy configuration and try again.
>
>If you ignore this error, the rest of the app might not work correctly.
>
> [Ignore and continue] [Quit]

It appears to pop up any time I load any game page. The main catalog itself, my collections, my library, and my creations pages all seem unaffected.

I have to click Ignore and continue 2+ times to get the dialog to go away. Then it pops up again when I load another game page, or reload the current game page.

I'm not using a proxy, but I am using an ad blocker and other "tracker" disablers that probably makes google-analytics.com point to localhost or something similar.

Other than this error popping up all the time, the itch app seems to work fine.

**Comment by fasterthanlime** [comment]
This thread has some elements of response: https://news.ycombinator.com/item?id=11762492

> OpenDNS/Cisco Umbrella is basically a DNS-level security service that analyzes your DNS queries, blocks known malware domains, etc.
>
> For some high-risk domains - depending on some settings - it will also switch to MitM'ing the connection to take a closer look at the traffic and block it on that level if necessary. It might also just be necessary to show the "This domain is blocked" page when you're requesting a site via https. Usually, your employer would pre-install their CA certificate, which would bypass the HSTS warning, but I suppose this might be a BYOD setting (or they just forgot/didn't like the idea of Cisco being able to MitM all the things).

Can you think of anything in your network stack that does that?

**Comment by Deozaan** [comment]
Yes. My ad blocker installs its own certificate so it can filter HTTPS traffic.

**Comment by fasterthanlime** [comment]
It looks like https://github.com/electron/electron/issues/1956 may have something to do with it.

I don't know enough to figure out exactly what causes your Adblocker's certificate not to be detected/imported and how to fix it at the moment :(

**Comment by Deozaan** [comment]
FWIW, I'm using AdGuard: https://adguard.com/

**Comment by fasterthanlime** [comment]
v25 no longer shows a modal with certificate errors, but I still think AdGuard installing its own certificate is fishy.

**Comment by Deozaan** [comment]
As stated previously, AdGuard has to install its own certificate so it can filter ads served over HTTPS. I believe it has to be explicitly enabled (opt-in), so I don't consider it to be "fishy" behavior. But yes, it does open you to the possibility that AdGuard could misbehave. It's a security trade-off people should be aware of when deciding whether or not to enable that particular feature.

Thanks for the fix.
