### ISSUE TITLE
Placeholder cover for cover-less games

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#115]
Currently React seems to think we'd like to see whatever the old cover at that grid position was

**Comment by uklein-a** [comment]
![no cover](https://cloud.githubusercontent.com/assets/10395335/11824344/b179864e-a33e-11e5-939c-07c3d067b753.png)

Here's a quick placeholder I made in 5 minutes, if anyone can make something better, that'd be nice.

**Comment by fasterthanlime** [comment]
I was thinking maybe some vector graphics instead? The website has a star
