### ISSUE TITLE
Having an outdated butler in $PATH on windows results in shenanigans

### ISSUE THREAD

**Issue by JeroenDStout** [itchio/itch#1152]
![image](https://cloud.githubusercontent.com/assets/14242454/23826976/290f0ef8-06a9-11e7-92b6-07489d0f97ef.png)

Trying to download Evangeline results in only this. The library offers the choice between files to download, but the download tabs only gives the result posted above, without any further information.

**Comment by fasterthanlime** [comment]
Can you include:

  * Which OS you're using: Windows/Linux/macOS ?
  * Which country you're downloading from

As for the game, I assume it's this one? https://raconteur-games.itch.io/evangeline

**Comment by JeroenDStout** [comment]
Ah, yes:

* Windows 7
* The Netherlands

The game is the one you linked, yes.

**Comment by fasterthanlime** [comment]
Can you post the full app log? (Preferences -> Advanced -> Open app log)

**Comment by JeroenDStout** [comment]
Here it is:

[itch.txt](https://github.com/itchio/itch/files/839498/itch.txt)

I had not checked before, but other downloads fail as well.

**Comment by JeroenDStout** [comment]
I feel such a fool - I just realised that the Butler I use to upload may be the same as I use to download. It is, of course. I updated my version of Butler manually and the problem went away.

I am sure you warned about this in documentation but after so many months I forgot :-\ sorry

**Comment by fasterthanlime** [comment]
Oh. The weird part is, when checking for butler's version / updating / launching it, itch is supposed to ignore whatever is already in `$PATH`... so that's strange.

**Comment by fasterthanlime** [comment]
I'm going to re-use this issue as tracking the PATH issue - feel free to Unsubscribe from notifications (right-hand-side section of Github issues) for this thread if you want to avoid spam :)

**Comment by fasterthanlime** [comment]
v25 always specifies the complete path when launching/checking butler, so that issue has been solved!
