### ISSUE TITLE
Faster switching between channels

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1153]
Currently to switch game's channel in itch app I need to 'Uninstall' game first and then click 'Install' again, and choose a channel. ('Reinstall' command just reinstalls current channel's content without asking for new channel, it's a bit confusing btw). So content from new channel is downloaded from scratch, without using wharf's magic patches. May the app somehow switch channels faster and consume less traffic?

One way would be to use "healing" and let app convert local content of the current branch into content of the new branch, it may be fast if channels' bytes are similar. I've got an impression that wharf works that way, but I did not follow its development closely enough to be sure if it's efficient or works at all :)

And another possible way is to simply allow multiple branches to coexist on local drive, so you don't need to remove current branch, and you don't need to download new branch from scratch if you downloaded it already.

**Comment by fasterthanlime** [comment]
> One way would be to use "healing" and let app convert local content of the current branch into content of the new branch, it may be fast if channels' bytes are similar. I've got an impression that wharf works that way, but I did not follow its development closely enough to be sure if it's efficient or works at all :)

v25 has a "Switch version" feature and does use healing for that!

![image](https://user-images.githubusercontent.com/7998310/45691162-54dbb080-bb58-11e8-9f4c-d373f4e6db56.png)

Patches are way more efficient, but they're only generated between each build in ascending order, not between each possible combination.

It's not possible to have two installs with different builds of the same channel at the moment.
