### ISSUE TITLE
Tab just shows "?" after request time out

### ISSUE THREAD

**Issue by local-minimum** [itchio/itch#1157]
I also had on odd tab just before that seemed to not be appropriate (image included) and never completed whatever it considered loading...

Event log:

```
Error: Request timed out

stack:
Error: Request timed out
    at Timeout.setTimeout (C:\Users\Martin Zackrisson\AppData\Local\itch\app-23.3.1\resources\app.asar\appsrc\util\net.ts:139:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
![itcherror](https://cloud.githubusercontent.com/assets/8041100/23924746/4548c7ac-090c-11e7-9d44-b44bd4f8ce97.png)

**Comment by fasterthanlime** [comment]
Did that crash the app? Where did the error log come from exactly?

**Comment by local-minimum** [comment]
Yes sorry for the combo issue.

The error came from connection issue but may simple have related to my connection being sluggish  (we have fiber so it really shouldn't be) yesterday and not relating specifically to the included image.

The app did in general behave a bit strange (possibly due to the connectivity issues). When I searched for Andyman404 I got no results as answer, but when I then removed the search, it presented me with some results among which the user andyman404.

The page included in the screenshot came from having as only tab the game page of his new hijab-game and then updating itch, upon reload after update this was all I was seeing. It seemed to not do anything, the page, but the mouse cursor displayed the loading/working on something sprite animation.

Sorry again for making a messy issue with many probably different small issues. It really wasn't very bothersome to deal with though the search thing was a bit annoying. I just figured I'd let you know anyhow so you decide if it's worth investigating.

**Comment by fasterthanlime** [comment]
No problem but again, my main question is: did it crash the app? We've had some reports of net requests failing bringing down the app, and I'm trying to find where those come from, so I'm wondering if it's another instance or something unrelated.

**Comment by local-minimum** [comment]
Sorry no forgot to answer that. It didn't crash the app, but I could have seen the update process seeming to have stalled the app permanently since it took really some time without any indications that things were working.

**Comment by local-minimum** [comment]
That is to say, I was surprisingly patient and in normal state I would have thought it hung. Since I was patent, it did indeed work & update itself.

**Comment by fasterthanlime** [comment]
The self-updater is notoriously slow on windows (I have no control over that, but might change the UI to be less distracting). The app kept working while it was updating though, right? It shouldn't stall anything the app is doing.

**Comment by local-minimum** [comment]
I actually didn't test it. I figured I didn't want to mess with the update. As a side suggestion, if you could supply some percentage message on both download and update message at the bottom of the app, it would help with confidence in that stuff is working.

**Comment by fasterthanlime** [comment]
> if you could supply some percentage message on both download and update message at the bottom of the app, it would help with confidence in that stuff is working.

I wish I could, but Squirrel.Mac & Squirrel.Windows do not provide that info. That's why I'm actually thinking of just hiding the `Updating` indicator, and only displaying an indicator when the update is ready.

**Comment by local-minimum** [comment]
The downloader seems to have some progress info

https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/FileDownloader.cs#L34

and I suppose this is why there's no progress for update

https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs#L34

**Comment by fasterthanlime** [comment]
> The downloader seems to have some progress info
> 
> https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/FileDownloader.cs#L34

Yep, and it's hidden behind electron's [auto-updater api](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md). Presumably because Squirrel.Mac lacks the feature.

I've had a [pet project](https://github.com/itchio/itchSetup) that would fix all that but I can't justify spending the amount of resources it'd require to actually ship it.

I think showing `Downloading update...` was a mistake in the first place. Squirrel is really designed for `invisible updates`, much like Atom does, or Chrome for that matter. I'll probably keep a progress indicator, but in the `Preferences` tab, so most users aren't bothered by it (that's what Chrome does).

**Comment by retropipes** [comment]
I'm getting weird menu behavior on macOS Sierra 10.12.3 with this update. The Application menu says "undefined ()" for all items except Preferences and Quit. The items themselves work normally.
<img width="165" alt="odd itch menus" src="https://cloud.githubusercontent.com/assets/7102537/24071508/ff75a326-0ba9-11e7-95af-cc91a59ecafc.png">

**Comment by fasterthanlime** [comment]
@wrldwzrd89 and there's no `undefined {}` strings anywhere else in the app?

**Comment by retropipes** [comment]
@fasterthanlime Not that I've seen so far. The Windows version doesn't seem to be affected, but then again it doesn't actually use the menu bar.

**Comment by fasterthanlime** [comment]
> The Windows version doesn't seem to be affected, but then again it doesn't actually use the menu bar.

Fun fact: you can make it appear temporarily by pressing alt :)

I'll look into the macOS issue.

**Comment by fasterthanlime** [comment]
Bunch of issues in this one eh?

The request time-out shouldn't be happening in itch v25 anymore.

The macOS menu issue was fixed a while ago.

itch's self-updater is now powered by the same technology as butler and it is much faster.

Looks like we're good for a closing!
