### ISSUE TITLE
Poor text rendering for action buttons (windows)

### ISSUE THREAD

**Issue by jamieslyman** [itchio/itch#1158]
Launch, Open, Install and any other red buttons have weird artifacts on them.

**Comment by fasterthanlime** [comment]
Does it look like a circle expanding out when you click? Or is it something else?

If it's the circle thing, that's by design :)

**Comment by jamieslyman** [comment]
No, it has a strange barely-noticeable gradients at the edges and around the letters (i.e. the actual images have artifacts). I doubt it's because of the resolution of my screen (1280x1024), but it might be.

**Comment by fasterthanlime** [comment]
Can you post a screenshot?

**Comment by wdcook4** [comment]
![image](https://cloud.githubusercontent.com/assets/3598140/24063301/7dda4840-0b35-11e7-8f66-f0aa8170bd42.png)

**Comment by jamieslyman** [comment]
![capture](https://cloud.githubusercontent.com/assets/3598140/24063371/bcb4dd3c-0b35-11e7-8ef1-86f0527990d3.PNG)

**Comment by fasterthanlime** [comment]
Oh, I see. That's text-shadow to make it more readable on the pink background, but it appears the text rendering on Windows + non-retina screens is quite unfortunate :(

I'll see if changing the styling slightly could improve that, thanks.

**Comment by fasterthanlime** [comment]
The buttons look fine in v25 imho:
 
![image](https://user-images.githubusercontent.com/7998310/45693369-3b893300-bb5d-11e8-9f73-d27bebbd6639.png)

I remember that changing the font format used for Lato made a world of difference.
