### ISSUE TITLE
Implement itchio://install/GAMEID

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#116]
Use undocumented API endpoint `/api/1/API_KEY/game/GAME_ID`

Anyone want to give it a shot? Entry point is here: https://github.com/itchio/itch/blob/7cbe896b9d8a0866e1817fc2fa69b5960ac967d5/app/metal.js#L47

Basic plan:
- parse URL (split on `/`, switch on first segment)
- launch API request (see `stores/game-store.js`)
- once game is fetched, cache it in local db (see `db/util.js`)
- once it's in DB, call `cave_queue` with game id
- it should appear in `Installed` until it's uninstalled

**Comment by rplnt** [comment]
This will of course need user confirmation. And even then I wonder if it's safe. Would it be possible to implement either a callback on server or (probably better) include some sort of verification that the url was indeed created by itch.io. Might be viable to limit it to user and/or time.

Disclaimer: I have no idea _how_ to securely implement it. Just think that a 3rd party shouldn't be able to spam users with install requests. And if it were properly secured (is it possible?), one might even skip the user confirmation step.

**Comment by fasterthanlime** [comment]
> This will of course need user confirmation

Good point, I'll make sure it does ask for confirmation. I don't think there's any proper way to 'secure it'. Attacking will still be possible, but if cilcking on a link brings the application to the top & ignores any other url requests, it shouldn't be possible to spam you too badly (you can just alt-tab back to whatever you were doing).

Note that at least in browser, opening custom URL protocols is heavily restricted — afaict you can only do it from a click event handler. So a simple js script could not attack you that way.

However if it's an app running on your computer, then it can open as many itchio:// (or http://, etc.) URLs as it wants. Then again don't install software you don't trust :)
