### ISSUE TITLE
Keep download progress after quit

### ISSUE THREAD

**Issue by buckle2000** [itchio/itch#1160]
Well, please make the app remember downloading items when quitting.

**Comment by fasterthanlime** [comment]
Just to clarify the current state of things:

  * On app quit, current downloads are "forgotten" ...
  * ... but the partial downloads are still on disk
  * So, manually starting the donwload again will resume them

**Comment by sigmap** [comment]
I would very much appreciate this feature and it would make the itch desktop client more attractive to users and especially steam users.

**Comment by fasterthanlime** [comment]
Marking as duplicate of #1465
