### ISSUE TITLE
Ability to change a channel's internal name

### ISSUE THREAD

**Issue by IBwWG** [itchio/itch#1162]
I didn't realize this until today when I removed my game's minimum price and tried to download it: https://ibwwg.itch.io/mathildagame/

The game has for a long time no longer been in beta.  I've renamed the "pretty print" part of each channel's name, but the channel itself still has the word "beta" in it, and when you download it, the zip file is name after the channel's internal name.

So now I have a choice, I can leave it be, looking bad, or I can ditch these channels and reupload everything, punishing any current users who want to update by taking away one of itch's nicest features for big game downloads, diffed downloading.

It'd be nice if I could just change the internal name with a butler command...

**Comment by fasterthanlime** [comment]
As far as the aesthetics go, I think @granpc has pending changes that would fix what name the .zip have when downloaded via the website.

As far as the one true name goes, I.. have been planning to implement something that would let you copy a channel to another channel (so it's not painful for you to upload), and I think it was @quyse who requested letting users switch channels via the app? (It could be manual or automatic following a channel name change). All the code in butler is already there it's really just a matter of integrating it into the app.

Hopefully in the short term the aesthetic change would be enough?

**Comment by IBwWG** [comment]
That's cool, if no users can see 'beta' anymore, I don't care if it's still part of my upload script.

As for switching channels, would it cause users a re-download?  That's what I'm trying to avoid for them...

**Comment by fasterthanlime** [comment]
> As for switching channels, would it cause users a re-download? That's what I'm trying to avoid for them...

The way "revert to build X" works (which is the way switching channels would work) is by "repairing" the install, only downloading what's actually different between the two builds (ideally per block, right now, per file). If all the files are the same, it would not actually download anything (just the hashes, then check that it matches - quite fast).

**Comment by IBwWG** [comment]
Sweet, that'd be awesome.
