### ISSUE TITLE
[linux] game Icelandic viking vs pineapple pizza broken for v0.11.3

### ISSUE THREAD

**Issue by Nemoder** [itchio/itch#1163]
:rotating_light: Game [Icelandic viking vs pineapple pizza](https://uso.itch.io/icelandic-viking-vs-pineapple-pizza) is broken for me.

Linux version was pulled, nevermind.

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Hey, v0.11.3 is over a year old at this point ([December 22, 2015](https://github.com/itchio/itch/releases/v0.11.3)), please upgrade to the latest (see the [releases](https://github.com/itchio/itch/releases/) page) and send another report if the issue persists.

Thanks a bunch! 🌟
