### ISSUE TITLE
Isolate.exe will not run?

### ISSUE THREAD

**Issue by benhamill** [itchio/itch#1164]
:rotating_light: All games are broken for me if I check the "Enable itch.io sandbox" preference. I realize this is experimental, but maybe this log will help. Every time I try to launch a game, it asks for admin rights so it can set up the sandbox (which I assume is about creating an "itch" user) and then it fails and aborts.

:book: Here's the complete [debug log](https://gist.github.com/52bd16f65179c721601329efc74e1f6f).

:running: I'm happy to answer any questions about my system or try out work-arounds if it'll help debug. I tried uninstalling itch, nuking all the remaining stuff in AppData/Local and AppData/Roaming and removing the users the sandbox had installed at some previous time. After reinstalling itch, the problem persists.

**Comment by fasterthanlime** [comment]
> Every time I try to launch a game, it asks for admin rights so it can set up the sandbox (which I assume is about creating an "itch" user) and then it fails and aborts.

You assumed right!

> I'm happy to answer any questions about my system or try out work-arounds if it'll help debug. I tried uninstalling itch, nuking all the remaining stuff in AppData/Local and AppData/Roaming and removing the users the sandbox had installed at some previous time. After reinstalling itch, the problem persists.

That's very kind, I'd also like to know why isolate fails for you.

My first question is: do you have any antivirus software running (that isn't built into win10)?

Second question: from cmd.exe, what's the output of:

```
%APPDATA%\itch\bin\isolate.exe --print-itch-player-details
```

**Comment by benhamill** [comment]
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\ben>%APPDATA%\itch\bin\isolate.exe --print-itch-player-details

C:\Users\ben>
```

Am I meant to be running it as an admin or similar?

**Comment by fasterthanlime** [comment]
> Am I meant to be running it as an admin or similar?

Nope, regular user, so this is fine

I'm assuming `echo %ERRORLEVEL%` right after that command shows `1` ?

**Comment by benhamill** [comment]
That's correct:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\ben>%APPDATA%\itch\bin\isolate.exe --print-itch-player-details

C:\Users\ben>echo %ERRORLEVEL%
1

C:\Users\ben>
```

**Comment by fasterthanlime** [comment]
isolate is no longer used by itch v25, all the sandboxing logic has been ported to butler.

Please open a new issue if the sandbox is broken for you on itch v25. You can download it from https://itch.io/app
