### ISSUE TITLE
Can't play local games if login fails

### ISSUE THREAD

**Issue by stuartlangridge** [itchio/itch#1167]
Currently as I write this there is some problem with the itch.io website; it's down. That's fine; these things happen. However, this also means that the itch desktop app, when started, shows a login error and a login form and that's it. I therefore can't play any of my locally installed games!

**Comment by fasterthanlime** [comment]
That was fixed in 1a7f8e24883e11a56cb96a900ca800d14854bdf1 which isn't in a stable release yet.

Let me see if I can ship a new version now.

**Comment by fasterthanlime** [comment]
Quick update: releasing a new stable version forced me to solve the "native electron modules" problem I wasn't expecting to have to solve so soon.

I believe I've cracked it, so a stable release is on its way in the next hour.

**Comment by fasterthanlime** [comment]
Shipped [v23.4.0](https://github.com/itchio/itch/releases/tag/v23.4.0) which fixes it.

Incidentally, the website is up, so you can't test it :)
