### ISSUE TITLE
Filter out (sensitive) user information from debug log before posting to gist

### ISSUE THREAD

**Issue by uvok** [itchio/itch#1170]
OS: Gentoo Linux, amd64
Itch version: itch-23.4.0-amd64

When posting debug logs to gist, could you remove (possibly sensitive) user data from the log?

What I found in the logs is the user name, when itch in placed in the user home directory. The username can be determined from various paths in the log (... /home/username/...) - maybe replace with just "user"? 

Same may apply for Windows.

**Comment by ghost** [comment]
Applies to Windows too.

**Comment by fasterthanlime** [comment]
v25's report system doesn't include any personal info and is private by default.
