### ISSUE TITLE
Oceania Download Speeds

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1173]
Dear Itch app team, 
I've been having a problem with downloading applications, its the speed, on average I get **20 KB/s** which is unacceptable, and I know its not my internet because _Steam_ downloads at a much higher rate. please Fix this or get a **New Zealand/Oceania Server**.

**Comment by fasterthanlime** [comment]
Hey, thanks for the feedback!

That's with the app, right? Can you try the following in your web browser:

  * Go to https://georgebatch.itch.io/hot-date
  * Click `Download now`, then `No thanks, just take me to the downloads`
  * Download the windows version

Note the download speed over the course of this download and report back.

And then. this:

  * Go to https://georgebatch.itch.io/hot-date
  * Click `Download now`, then `No thanks, just take me to the downloads`
  * *Before* clicking download, click the grey `Downloads not starting?` link, click `Enable alternate download mode`, *then* download the windows build.

Also note the download speed and report back.

Thanks in advance! 🌟
