### ISSUE TITLE
Game engine tab camel-case request

### ISSUE THREAD

**Issue by nhurde** [itchio/itch#1182]
Dear itch app team, 

I was wondering if there is a way to get my Game Engine tab camel-capitalized.

For the following two tags:
https://itch.io/game-assets/tag-gamepencilengine
I would like it to say either "Game Pencil Engine" or "GamePencilEngine"

Also the same for https://itch.io/game-assets/tag-gamepencil
I would like it to say either "Game Pencil" or "GamePencil"

Please let me know if that is possible or not.

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/901
