### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by buckle2000** [itchio/itch#1183]
Dear itch app team, why itch.io app cannot download 2+ games simultaneously?
Download speed is always around 80KB/s.

**Comment by fasterthanlime** [comment]
Where are you downloading from?

**Comment by buckle2000** [comment]
From the desktop app in China.
Also in ~~US LA~~, Japan, Singapore, Hong Kong with VPN.

---
I've emailed leafo and leafo said all games are streamed through CDN. But it's still slow.

**Comment by fasterthanlime** [comment]
> I've emailed leafo and leafo said all games are streamed through CDN. But it's still slow.

Yep, we don't have edge nodes enabled for Asia yet - can you figure the IP of the server you're downloading from? I'm interested which edge node is serving China

**Comment by buckle2000** [comment]
*redacted*

**Comment by fasterthanlime** [comment]
Ah, looks like a US-based server (Phoenix Arizona). No wonder it's slow :/

I'll bring it up!

**Comment by jgandert** [comment]
I'm from Germany. I also just had very slow download speed (15 kb/s :open_mouth:) on itch for a while. 

Now it's back to normal though. :)
