### ISSUE TITLE
Top-level crash, net::ERR_CONNECTION_RESET, during dependency installation

### ISSUE THREAD

**Issue by majhalhouse** [itchio/itch#1187]
Event log:

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by fasterthanlime** [comment]
Can you describe the exact circumstances where this happened? Along with details on your computer, your connection (which country/isp, 2g/3g/4g/wifi, etc.)

I've had a few reports like this but have been unable to track it down so far :(

**Comment by majhalhouse** [comment]
Certainly, I am using Windows 10 pc with 8gb ram, I have a broadband
connection with 20mbps speed. Service provider is den boomband, delhi,
india. I installed itch and logged in with my new itch id atindersingher ,
after completing the authentication it began installing unrar dependency.
Then i shifted focus to Google chrome. After some time the app crashed. My
net connection resets according to itch app.
