### ISSUE TITLE
Show supplied VERSION when "revert to given build"

### ISSUE THREAD

**Issue by josefnpat** [itchio/itch#1188]
I use the `--userversion` when using `butler push` extensively, and it's really nice because it shows up in `butler status` and on the itch.io website:

![image](https://cloud.githubusercontent.com/assets/646162/24976766/586b3352-1f90-11e7-907b-190a7d8ec635.png)

(This is very useful for tracking down issues)

The problem is that when I attempt to "revert to a given build" it only shows the timestamp and the itchio internal ID, which is pretty useless for me.

![image](https://cloud.githubusercontent.com/assets/646162/24976648/f20e4220-1f8f-11e7-9535-e702f4166104.png)

If a `--userversion` is supplied, can we show that here as well / instead?

**Comment by fasterthanlime** [comment]
Yep, that's a good point. That dialog needs some love

**Comment by josefnpat** [comment]
❤️  you rock @fasterthanlime

**Comment by josefnpat** [comment]
Would you like me to try and take a crack at this? Not sure how simple it is.

I see the line right here: https://github.com/itchio/itch/blob/master/src/reactors/tasks/revert-cave.ts#L90

**Comment by fasterthanlime** [comment]
There's 200+ commits unmerged from sqlite-first into master right now, so submitting patches against master isn't the best idea right now.

I'll ping you again in 2-3 days if that's ok ?

**Comment by josefnpat** [comment]
Good luck with your merge!

**Comment by josefnpat** [comment]
bump

**Comment by fasterthanlime** [comment]
Got a big cleanup release shipping soon :tm: and this issue is part of the milestone — so it's being taken care of :)

**Comment by josefnpat** [comment]
awesome, thanks!

**Comment by GranPC** [comment]
This is a backend issue, I'm on it!!

**Comment by GranPC** [comment]
This is now fixed (and has actually been for a week or so!) -- closing!
