### ISSUE TITLE
🏁 Feedback v23.4.0

### ISSUE THREAD

**Issue by PumpkinMaster69** [itchio/itch#1189]
Event log:

```
Error: ENOSPC: no space left on device, write
```

**Comment by fasterthanlime** [comment]
Yeahhh your disk is full :)

This shouldn't crash the app - it should detect when you're low (like 100MB left?) and stop there - it doesn't do that yet.

As a tip, you can empty out `%APPDATA%/itch/downloads` - if you've been installing a bunch of games, then there's a bunch of .zips in there you can safely erase. That should give you a few hundred megabytes back.

**Comment by fasterthanlime** [comment]
Duplicate of #801 / #874
