### ISSUE TITLE
v0.9.3 — Empty dashboard is confusing for everyone

### ISSUE THREAD

**Issue by ScarylePoo** [itchio/itch#119]
I see no games.

https://i.imgur.com/2bSOgaI.png

Just installed, windows 10, 64bit.

**Comment by fasterthanlime** [comment]
This is actually a case of #100 

The Dashboard usually contains games _you_ have uploaded to itch.io — it's not the front page, or featured games, or anything.

Currently, you have to add a game to a collection (if it's a new collection, log in again — if you add games to an existing collection, click on its label again in the client to have it refresh). I'll make sure to make it easier and less confusing in the next versions.

**Comment by ScarylePoo** [comment]
Perhaps I was unclear:
https://i.imgur.com/WidmLsz.png

https://i.imgur.com/SoiOtww.png

https://i.imgur.com/GObUyO9.png

Nowhere in this app do I see a listing of games to download.

**Comment by fasterthanlime** [comment]
@ForbodingAngel you were perfectly clear :) the app is confusing to people who 1) are not developers 2) have never bought anything 3) don't have any collections.

I'm working on making that experience better in the next version. In the meantime, if you want to play game, add them to a collection from the itch.io website, then you'll be able to install it from itch.

Here's a [video by wasteland dan](https://www.youtube.com/watch?v=kL39RHPc42c) (unaffiliated) that shows how to do it (only the first minute is relevant).

**Comment by ScarylePoo** [comment]
Ok, I get it now. You should add a tab that basically shows what I get at the site, and allow doing it through the app. Without that it's like... why do I need this app if I have to do it manually anyway?

Fwiw, I am a dev, but tbh that's kinda besides the point. The app doesn't really announce itself or it's intentions very well.

**Comment by fasterthanlime** [comment]
Replicating all the browse functionality in the app is going to take some time — in the meantime, the itchio:// protocol should help (buttons on game pages that open the game in the app with one click)

**Comment by ScarylePoo** [comment]
Yeah I get it now. A bit confusing but regardless, thanks for the awesome
app. It really does make it a lot easier :-)

**Comment by fasterthanlime** [comment]
Here's what I came up with:

![empty-state](https://cloud.githubusercontent.com/assets/7998310/11859527/0f92d810-a46c-11e5-9dbd-e27a43930ae6.gif)

It'll be in the next release :)
