### ISSUE TITLE
Invalid apt key

### ISSUE THREAD

**Issue by bpearson** [itchio/itch#1190]
Tried following the instructions on the website (https://itch.io/docs/itch/installing/linux/ubuntu-and-debian.html) for Ubuntu, but it complains about an invalid packet on the key:
`gpg: [don't know]: invalid packet (ctb=00)
gpg: keydb_get_keyblock failed: Value not found
gpg: [don't know]: invalid packet (ctb=00)
gpg: /tmp/tmp.UWLFNLqXV8/pubring.gpg: copy to '/tmp/tmp.UWLFNLqXV8/pubring.gpg.tmp' failed: Invalid packet
gpg: error writing keyring '/tmp/tmp.UWLFNLqXV8/pubring.gpg': Invalid packet
gpg: [don't know]: invalid packet (ctb=00)
`

**Comment by wilcoxm** [comment]
@bpearson try this:

sudo apt-key add <key>

Superuser permissions is required.

Close this issue if this solves the problem.

**Comment by fasterthanlime** [comment]
@miwilc Thasnks! I believe the issue is separate though!

**Comment by bpearson** [comment]
Yeah that works but now bintray is asking for a login?

**Comment by bpearson** [comment]
Ahh, never mind, it must have been my system, I built it and it all works now.
