### ISSUE TITLE
Top-level crash, net::ERR_NETWORK_CHANGED during login

### ISSUE THREAD

**Issue by niedzielski** [itchio/itch#1191]
This is a really specific issue to Chromium and Ubuntu / Ubuntu Gnome v17.04. Ubuntu v16.10 worked fine but v17.04 and Google Chrome / Chromium / Itch seem to be having terribly flaky networking. Chrome and Chromium just show a "your connection has been interrupted" message and require a refresh. Itch seems to crash, unfortunately, during login and dependency installation. I'm not sure if you want to tackle this bug or hope that Electron and Ubuntu cooperate better. It seems to work ok now that I'm able to login after a couple refreshes.

Event log:
```
Error: net::ERR_NETWORK_CHANGED
    at Error (native)
```

**Comment by fasterthanlime** [comment]
Do you have links to other discussions of this problem? If it's that bad, surely there's a record of it somewhere?

**Comment by niedzielski** [comment]
@fasterthanlime, not yet. I just upgraded to Ubuntu GNOME v17.04 on Friday. I was previously using Ubuntu v16.10 and never had any issue like this. The only additional detail I've collected so far is that the bug doesn't seem to occur in Firefox but does appear in Vagrant / VirtualBox. The closest known issue I've found is [this](https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1586528) but I'm uncertain if it's really the same root cause. The reason I reported the bug here is that you may want to check that the Itch login sequence gracefully handles ERR_NETWORK_CHANGED but I'm sorry I don't have repro steps.

**Comment by fasterthanlime** [comment]
> you may want to check that the Itch login sequence gracefully handles ERR_NETWORK_CHANGED but I'm sorry I don't have repro steps.

Yeah, network troubles in general are notoriously hard to reproduce "proper". I usually end up faking error codes to test it. According to the issue thread you linked, if something is restarting network-manager, chromium would definitely detect that as a network change.

I can treat `ERR_NETWORK_CHANGED` as a "network error" in itch's network code, not sure how much that would help though. If the network changes while it's logging in, it would behave as if you were offline, [logging you in anyway](https://github.com/itchio/itch/blob/706b07f6af94b05b7c2ebdb03dd6b380fca8f2e0/appsrc/reactors/login.ts#L108-L114). I'm not sure which is the best behavior here.

**Comment by niedzielski** [comment]
I can only speculate. BTW, I think I was prompted by the app to file this issue because an unhandled Error was thrown which probably points to a bug. This is a little off topic but is there any reason the report issue button doesn't include a stack trace? Or does `at Error (native)` indicate that the issue was deep inside Electron native code? I ask because a trace would have been super helpful for this issue and probably lots of others too.

Most of my programming lately is in Java and we use something called [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) to test endpoint clients at the unit level including unexpected responses. It's worked very well. I've heard nock is a similar solution for JavaScript but have never used it myself. [This overview](http://jakepruitt.com/2014/11/13/nock.html) makes it look nice though :] I certainly don't mean to oversimplify the difficulty of testing, I just wanted to share some thoughts!

**Comment by fasterthanlime** [comment]
> I can only speculate. BTW, I think I was prompted by the app to file this issue because an unhandled Error was thrown which probably points to a bug. This is a little off topic but is there any reason the report issue button doesn't include a stack trace? Or does at Error (native) indicate that the issue was deep inside Electron native code? I ask because a trace would have been super helpful for this issue and probably lots of others too.

I agree it would be super helpful, and in *most* cases there is actually a full stack trace. But this report is only one instance of another bug that has been reported a few times before, where there is no stack trace and the error is only caught by the last-chance handler (errors are normally handled more gracefully, shown in the UI with the option to retry, ,or trigger automatic retries etc.)

It's particularly hard to diagnose because it's not a server error, it's a network stack failure - sometimes it's ERR_DISCONNECTED, sometimes it's ERR_NETWORK_CHANGED, etc., but I haven't been able to trace exactly where it comes from exactly. I'll try a bit more today!

Edit: just as I'm writing this, [another one comes in](https://github.com/itchio/itch/issues/1195) 🦑
