### ISSUE TITLE
Support GALLIUM_HUD environment variable

### ISSUE THREAD

**Issue by beniwtv** [itchio/itch#1193]
**Itch.io app 23.4.0 - Manjaro Linux (64 bit)**

**Problem description**

I am launching the itch.io app with the following command line:

`$ GALLIUM_HUD="fps+cpu+GPU_load" <path/to/itch>`

Games launched with itch then should display a nice FPS graphic, but nothing shows up.
When I launch a game manually from the ".config/itch" directory with that option, it works fine.

Sandbox enabled/disabled does not make a difference.

Also, starting Steam with that option works fine, all games get the overlay.

I am assuming this is because the itch app cleans the environment before executing a game - but would it be possible to allow this environment variable ("GALLIUM_HUD") to pass through if set?

I use that feature for my streams and it would be nice to have on itch :)

**Comment by fasterthanlime** [comment]
Hmm, indeed it does (clean the environment before executing a game). Would an app-wide preference where you can edit a list of key/values acceptable ? It seems like it would be a better UX than having to quit/start itch again whenever you want to change one.

**Comment by beniwtv** [comment]
Yes, that would be awesome. This way it could be more generic, too :)

**Comment by fasterthanlime** [comment]
closing in favor of #366
