### ISSUE TITLE
[Request] Rewards API

### ISSUE THREAD

**Issue by SkyTech6** [itchio/itch#1194]
It would be great if through the server-side API we could check to see if a player has purchased a Reward for our games. This way it can be used for in-game rewards such as kickstarter bonuses (or even DLC).

I was thinking something along the lines of 

GET https://itch.io/api/1/KEY/game/GAME_ID/REWARD_ID/download_keys

with the user_id, download_key, email parameters available as with the other API calls.

Of course this would also require that we could see "Reward IDs" in our Dashboard perhaps. Maybe even one of the Fields can be one where we can assign the reward an ID?

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/903
