### ISSUE TITLE
🏁 Feedback v23.4.0 - Backup and Restore feature?

### ISSUE THREAD

**Issue by surashu** [itchio/itch#1197]
Is it possible to add a Backup and Restore feature similar to Steam's? Or probably, an option to locally re-import game folders so that they don't need to be re-downloaded?

**Comment by fasterthanlime** [comment]
in itch v25, install locations are scanned for previously-installed games.

It also scans for games installed with previous versions of the app, but only if the %APPDATA% folder is still there (as it is where older versions of the app used to store installed game info).
