### ISSUE TITLE
Rearranging open pages sometimes doesn't work if scrolling is needed to get to drop position

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1199]
Version: 23.4.0

To reproduce:
1. Open more tabs than can be shown in the current window height.
2. Drag a tab down so that the list starts scrolling. Don't drop yet.
3. Observe that the shown drop position is not where the mouse is.
4. Drop.
5. Observe that the tab wasn't necessarily dropped in the right place or moved at all.

**Comment by fasterthanlime** [comment]
I'm not able to reproduce in itch v25:

![drag-tabs](https://user-images.githubusercontent.com/7998310/45691720-65d8f180-bb59-11e8-9701-fa61a15a57aa.gif)
