### ISSUE TITLE
v0.8.1 - Error on login: socket hang up

### ISSUE THREAD

**Issue by Jeasonfire** [itchio/itch#120]
When I try to login on Arch Linux, it gives this error message:
![screenie](https://cloud.githubusercontent.com/assets/1842446/11807806/ea54e310-a324-11e5-8df8-108f8a45802c.png)
I installed the program from the [AUR repo](https://aur.archlinux.org/packages/itch/).
Screenshot because I couldn't select the text to copy it.

**Comment by fasterthanlime** [comment]
I've never seen that error before, sounds like it is a generic network issue?

Can you post the output of `curl -v https://itch.io/country` ?

**Comment by fasterthanlime** [comment]
Just saw it in my logs while developing:

```
Unhandled rejection Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketCloseListener (_http_client.js:235:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
From previous event:
    at Client.request (/Users/amos/Dev/itch/app/util/api.js:62:19)
    at User.request (/Users/amos/Dev/itch/app/util/api.js:107:24)
    at User.collection_games (/Users/amos/Dev/itch/app/util/api.js:166:17)
    at fetch_collection_games (/Users/amos/Dev/itch/app/stores/game-store.js:95:15)
From previous event:
    at fetch_collection_games (/Users/amos/Dev/itch/app/stores/game-store.js:104:6)
    at fetch_games (/Users/amos/Dev/itch/app/stores/game-store.js:149:14)
    at /Users/amos/Dev/itch/app/stores/store.js:87:12
    at /Users/amos/Dev/itch/app/dispatcher/app-dispatcher.js:98:11
    at Array.forEach (native)
    at Dispatcher.dispatch (/Users/amos/Dev/itch/app/dispatcher/app-dispatcher.js:95:36)
    at Object.self.open_url.setup_status.focus_panel.self_update_error.self_update_downloaded.cave_queue.cave_queue_uninstall.cave_update.cave_progress.cave_implode.cave_ex
plore.cave_thrown_into_bit_bucket.cave_probe.set_progress.notify.login_with_password.login_failure.fetch_games.path [as fetch_games] (/Users/amos/Dev/itch/app/actions/app-a
ctions.js:209:19)
    at /Users/amos/Dev/itch/app/stores/collection-store.js:40:157
From previous event:
    at cache_collections (/Users/amos/Dev/itch/app/stores/collection-store.js:40:135)
```

@leafo are the itch.io servers seeing abnormal load ?

**Comment by Jeasonfire** [comment]
Oh, now there was no error. I guess it was a problem with itch.io servers? Ludum Dare might've caused a bit of traffic :) Sorry for the late response, closing this now!

**Comment by fasterthanlime** [comment]
> I guess it was a problem with itch.io servers?

We're looking into it right now, reopening to track that. (Feel free to unsubscribe from the notifications using the GitHub controls on the top-right of the thread)

**Comment by ProfessorKaos64** [comment]
Sorry to semi-hijack. I still get this on SteamOS, using the amd64 Deb file from the desktop. I wasn't sure if I should open a new issue or if it was my doing.

**Comment by fasterthanlime** [comment]
@professorkaos64 I saw a comment of yours on this thread, but it looks like you deleted it?

I'm interested in re-occurences of this — in 0.12.0 (next release) there are other fixes that may prevent socket hangups. Some things were happening that outright blocked the renderer process, such as:
- RPC from a react component to a browser/node-side store (it's implemented using synchronous IPC, which blocks both processes and is really really bad and we're avoiding at all costs in any new code and phasing out wherever possible)
- Synchronous dialog calls. They've now been changed to callbacks.

Even with all that, I suppose socket hangups are still possible, on occasion — I think the login window needs better error handling / at least a retry button or something. Right now, if setup fails, there's no way out except quitting & restarting the app completely.

**Comment by mdeguzis** [comment]
I added it again below.  A reboot of SteamOS solved it. However,  without using Xephyr I can't get it to launch on SteamOS, but that's my own problem really (I know you can't account for everything). Log is under the first issues section.

**Comment by mdeguzis** [comment]
https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/itch.io

**Comment by fasterthanlime** [comment]
@ProfessorKaos64 would you mind opening a separate thread for SteamOS-specific issues?

It'd be fun to have Itch run well from SteamOS in BPM. Actually I have my own controller-driven interface in mind...

**Comment by mdeguzis** [comment]
will do, any help is very appreciated. I will be patient to any movement on that, as I'm sure a lot of SteamOS folks would love to get this going.

**Comment by mdeguzis** [comment]
Added #294 , which contains a link to my wiki page, with a lot of info. Included there is current hacky work, strace logs, steam stdout logs, and more.
