### ISSUE TITLE
Comment editor behaves in non-standard way with selected text

### ISSUE THREAD

**Issue by codingthat** [itchio/itch#1201]
Well, for links it works great.

Selecting text and clicking bold, italics, etc., however, just does nothing (at least on Chromium on Linux.)

Also, selecting text and then hitting delete or backspace doesn't get rid of the selection, but moves the cursor to one end of it before executing the command on just one character.

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/900
