### ISSUE TITLE
🏁 Issue v23.4.0

### ISSUE THREAD

**Issue by Etude87** [itchio/itch#1202]
Dear itch app team, 

I can't install : Fantasy Hex Tiles, etc...(so many resource files)
I can't uninstall : Tiled, Tiled2Unity
Folder name was wrong : [ Royalty FREE Loops music ] undercover missions, etc...(first character was space...)
I can't buy 0.10 price products. Please fix or add cart.

**Comment by fasterthanlime** [comment]
Most of these should've been fixed by itch v25.

The $0.50 minimum purchase price is a website limitation, see https://github.com/itchio/itch.io/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+minimum+price
