### ISSUE TITLE
Install problem with AtlanInfection(mac)

### ISSUE THREAD

**Issue by Lubiuxio** [itchio/itch#1207]
When I just press the install button the game will say it's downloaded for a split second then go back to not being downloaded. Please help/fix this. This has happened with a few other games, but I do not remember specifically their names.

**Comment by fasterthanlime** [comment]
The reason is mostly external uploads - AtlanInfection is uploaded on mediafire for example.

I'd love to kill off external uploads soon, in the meantime the app should handle them better though - I'll keep it in mind!
