### ISSUE TITLE
DMG Mounting Hangs

### ISSUE THREAD

**Issue by rossimo** [itchio/itch#1209]
With the Mac version of Hex Kit, the installer hangs just after the logs mention the DMG is being mounted.

**Comment by fasterthanlime** [comment]
Hi 🌟 !

Can you post the full logs along with a link to Hex Kit?

**Comment by rossimo** [comment]
Hex Kit is here:
https://cone.itch.io/hex-kit

The log is here:
https://gist.github.com/rossimo/bd62423dfb86a8a820f45167a985d9ff

**Comment by fasterthanlime** [comment]
Closing as master uses seven-zip to extract DMG files (while downloading!) so we don't have to deal with mounting/converting/unmounting anymore.

![image](https://user-images.githubusercontent.com/7998310/35510517-a794f6b8-04f8-11e8-9954-28012c9a47b1.png)
