### ISSUE TITLE
Visual C++ Redistributable Packages for Visual Studio 2013

### ISSUE THREAD

**Issue by bjorn** [itchio/itch#1217]
With Microsoft Visual C++ Redistributables for 2010 and 2015 being automatically installable, [the 2013 ones](https://www.microsoft.com/en-us/download/details.aspx?id=40784) are strangely missing. Unfortunately, that is exactly the one I need for Tiled. So here's my request to add:

* `vcredist-2013-x86`
* `vcredist-2013-x64`

I've started to work on shipping Tiled snapshot builds for Windows through itch and properly depending on this redistributable would allow me to drop `MSVCP120.DLL` and `MSVCR120.DLL` from the included files (which I guess is not the proper way to do it, though it seems to work).

**Comment by bjorn** [comment]
@fasterthanlime I guess this request should have the label `prereqs`.

**Comment by fasterthanlime** [comment]
Beating the iron while it's hot, eh? Fair enough, I'm on it.

**Comment by bjorn** [comment]
@fasterthanlime Honestly, I just noticed the label when you pointed to the updated documentation on the other issue, and it made me realize this poor issue was still missing it. :-)

**Comment by fasterthanlime** [comment]
One website emergency later, it's all done 🌟
