### ISSUE TITLE
Binding side mouse clicks for page back/forward navigation

### ISSUE THREAD

**Issue by muhammadabdulrahim** [itchio/itch#1221]
I have a gaming mouse, a Corsair M65 Pro RGB. It has two buttons on the left side. In most browsers, the top of the pair is bound to page forward, whereas the bottom is bound to page backward. This is behavior that is seemingly instant to a user, as I did not need to set these bindings manually. Since itch is a gaming app, I feel this functionality should be supported in itch's browser. As a note, Steam's browser supports this behavior.

I am running the Windows 10 build of the itch app.

**Comment by fasterthanlime** [comment]
The reason this isn't in the app yet is that I thought it wasn't possible in electron - as it turn out, it should work just fine on Windows - we can figure out macOS & Linux support later!

**Comment by fasterthanlime** [comment]
This will be in the next stable release :)
