### ISSUE TITLE
🏁 Issue v23.4.1

### ISSUE THREAD

**Issue by zfett** [itchio/itch#1224]
Dear itch app team, On a game's store screen that I own, the text that records and displays when I last played a game is broken in German. See attached image.
![image](https://cloud.githubusercontent.com/assets/21271081/26262450/de2a3d56-3ca2-11e7-85b1-5a51431d7059.png) Notably where it says "Zuletzt gespielt {{time ago}}"

**Comment by fasterthanlime** [comment]
Looks like the translators turned "time_ago" into "time ago", breaking the substitution :)

I just [committed a fix](https://github.com/itchio/itch/commit/49e09f537d94633fae27f4865a774e7ba28e01f8) - it should load up for you if:

  * You go in Preferences and hit the "reload" icon next to the language picker

Or:

  * Restart the app

Let me know if that fixes it for you!

**Comment by zfett** [comment]
It's fixed! Thanks!
