### ISSUE TITLE
Remove the box on top of the screen

### ISSUE THREAD

**Issue by Stelios-Kourlis** [itchio/itch#1225]
It really annoys me whenever I see the little white box on top of the screen

![old itch](https://cloud.githubusercontent.com/assets/19624186/26275601/6602b378-3d6d-11e7-9258-79fa4a3be46e.png)

I don't know why but its annoying to me, I would prefer it like this

![new itch](https://cloud.githubusercontent.com/assets/19624186/26275608/92d10b20-3d6d-11e7-8a32-2d257c39c66c.png)

That's all!

**Comment by fasterthanlime** [comment]
itch has been frameless for a few releases now!

![image](https://user-images.githubusercontent.com/7998310/45690096-e39afe00-bb55-11e8-9d34-8cb18dd42419.png)
