### ISSUE TITLE
Gameplay video ignores timestamp on app

### ISSUE THREAD

**Issue by vncastanheira** [itchio/itch#1226]
I've noticed after linking a Youtube gameplay video that the app does not start from the specified time.
The same thing, however, does not happen on an updated browser like Chrome 58 and Firefox 53, which I tested.

Not trying to promote anything but here's the link where that happens: https://epiplon.itch.io/ld38
Youtube link: https://youtu.be/MwY1-PtcDqs?t=6093

Itch: v23.4.1
OS: Windows 10 64bit build 15063.296

**Comment by fasterthanlime** [comment]
So, the steps to reproduce are:

  * Go on https://epiplon.itch.io/ld38
  * Click play
  * It should start at second 6093 ?

Because on my latest chrome, it starts at the beginning.

Or should I be trying to click on https://youtu.be/MwY1-PtcDqs?t=6093 directly from the app ?

**Comment by vncastanheira** [comment]
Youtube usually saves your last position when you watch a video, so that might be why it started at 6093 at my machine and not yours (or anyone's).

In that case, I just think it is a nice idea to consider the arguments from Youtube links on your game page. Like in this case, start the video from the specified time.

**Comment by fasterthanlime** [comment]
> In that case, I just think it is a nice idea to consider the arguments from Youtube links on your game page. Like in this case, start the video from the specified time.

Ah, so the issue is that we're actually stripping the `?t=6093` when emitting the youtube embed code, is that it?

**Comment by vncastanheira** [comment]
> Ah, so the issue is that we're actually stripping the ?t=6093 when emitting the youtube embed code, is that it?

Yes, it is. 😆
