### ISSUE TITLE
butler auto-retry logic is flawed

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#123]
[Tue, 15 Dec 2015 11:56:16 GMT] [cave-store] starting download
[Tue, 15 Dec 2015 11:56:16 GMT] [cave-store] [download => find-upload] need upload id
[Tue, 15 Dec 2015 11:56:16 GMT] [cave-store] starting find-upload
[Tue, 15 Dec 2015 11:56:16 GMT] [tasks/find-upload] bought game, using download key
[Tue, 15 Dec 2015 11:56:17 GMT] [tasks/find-upload] got a list of 3 uploads
[Tue, 15 Dec 2015 11:56:17 GMT] [tasks/find-upload] post-filters, 1 uploads left
[Tue, 15 Dec 2015 11:56:17 GMT] [cave-store] [find-upload => download] undefined
[Tue, 15 Dec 2015 11:56:17 GMT] [cave-store] starting download
[Tue, 15 Dec 2015 11:56:18 GMT] [tasks/download] d/l from http://commondatastorage.googleapis.com/itchio/upload2/game/35259/111362?GoogleAccessId=507810471102@developer.gserviceaccount.com&Expires=1450180588&Signature=bNeXSE2t6E0Zh2je%2FzR01sE3J%2Bvgq%2BNvLY%2FwX1NgZYbBXqnJJU4NzdirTOX8Fl3OASj2KZBFIzgeHqqsAB4MhkyEYCp35uV%2FCR7AKtg%2FXe6qdq5HKMCmyDbnefAF%2BmRlV9pdmTWWVQIkdnJ0ZeHF2QHYinx5J1kJFIv38HTpYeU=
[Tue, 15 Dec 2015 11:56:18 GMT] [util/http] butler: existing file is 0 bytes long
[Tue, 15 Dec 2015 11:56:18 GMT] [util/http] butler: Asking for range bytes=0-
[Tue, 15 Dec 2015 11:56:19 GMT] [util/http] butler: server 200'd, does not support byte ranges
[Tue, 15 Dec 2015 11:56:19 GMT] [util/http] butler: Response content length = 103391413
[Tue, 15 Dec 2015 11:59:00 GMT] [util/http] butler: While downloading, got error read tcp 192.168.0.9:53046->74.125.24.128:80: read: connection reset by peer
[Tue, 15 Dec 2015 11:59:00 GMT] [util/http] butler: Retrying... (2 tries left)
[Tue, 15 Dec 2015 11:59:00 GMT] [util/http] butler: existing file is 0 bytes long
[Tue, 15 Dec 2015 11:59:00 GMT] [util/http] butler: Asking for range bytes=0-
[Tue, 15 Dec 2015 11:59:01 GMT] [util/http] butler: While downloading, got error server error: http 400 Bad Request
[Tue, 15 Dec 2015 11:59:01 GMT] [util/http] butler: Retrying... (1 tries left)
[Tue, 15 Dec 2015 11:59:01 GMT] [util/http] butler: existing file is 0 bytes long
[Tue, 15 Dec 2015 11:59:01 GMT] [util/http] butler: Asking for range bytes=0-
[Tue, 15 Dec 2015 11:59:01 GMT] [util/http] butler: While downloading, got error server error: http 400 Bad Request
[Tue, 15 Dec 2015 11:59:01 GMT] [cave-store] server error: http 400 Bad Request

**Comment by fasterthanlime** [comment]
That sounds like a temporary download error failure. Are you on wi-fi? Do you experience spotty internet connectivity sometimes?

I'd blame itch.zone but the log shows it's downloading straight from Google Cloud Storage and [they don't seem to have an outage](https://status.cloud.google.com/).

Can you try again a few minutes apart ?

**Comment by LiamDawe** [comment]
Seems it worked this time.

Feature request then: Don't error out, keep it at whatever % it was, and auto-retry later?

**Comment by fasterthanlime** [comment]
@NaughtySquid resuming downloads definitely does work, if you either kill the client or have the connection drop, the next download will pick up where it left off.

Auto-retrying later in case of server unavailability sounds like a good idea.

**Comment by fasterthanlime** [comment]
> resuming downloads definitely does work, if you either kill the client or have the connection drop, the next download will pick up where it left off.

```
[Tue, 15 Dec 2015 11:56:19 GMT] [util/http] butler: Response content length = 103391413
# ~three minutes elapsed here
[Tue, 15 Dec 2015 11:59:00 GMT] [util/http] butler: While downloading, got error read tcp 
```

wait, actually, that's a butler bug: its internal retry mechanism does _not_ take into account what you've already downloaded. but if butler exits and is started again, it'll work.

I think we just need to take out the retry logic from [butler](https://github.com/itchio/butler) and let the client handle it (with cooldowns, etc.)

**Comment by fasterthanlime** [comment]
Closed in https://github.com/itchio/butler/commit/142525ed456aacb79289bd84e70b35b66e21d647
