### ISSUE TITLE
Opening a folder should open using my default file explorer

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#1231]
In Preferences where you can modify the install locations, there's a handy little folder icon which I interpret to mean "open this folder."

What happens is the directory is opened as a tab within Itch, displaying the games similarly to how they are displayed in my library.

What I think should happen instead is that the directory should be opened in Windows Explorer (since I'm on Windows) so I can browse the files on my drive.

**Comment by fasterthanlime** [comment]
There used to be two icons:

  * One that showed which games are installed in this location
  * One that opened the folder in your file explorer

Now, the icon does the former, and there's a link at the top of the opened tab to do the latter.

The idea was to keep the preferences UI a bit cleaner/more readable :)

**Comment by Deozaan** [comment]
I don't get it. What's the point of having the app show which games are installed in that location when you can clearly see which games are in that location by opening up the file explorer to that directory?

**Comment by fasterthanlime** [comment]
> I don't get it. What's the point of having the app show which games are installed in that location when you can clearly see which games are in that location by opening up the file explorer to that directory?

If you want to remove an install location for example, you'll have to uninstall games installed to that location. That's why the app allows filtering by "install location" - so that you can clean it up before removing it.

Seeing the folder is all good & fine (especially now that folder names are actually human-readable! wasn't the case pre-v0.14.x) but you can't really uninstall from there.

**Comment by Deozaan** [comment]
I see. Thanks for explaining the rationale behind how it works. That does make more sense. And thanks for pointing out how you can still open that file location with the link to the top.
