### ISSUE TITLE
Can't manage blocked users

### ISSUE THREAD

**Issue by iwanPlays** [itchio/itch#1234]
When reporting a user via comment you can block them. However you cannot unblock them.

If for example a developer were to accidentally block a user (for example itch.io/profile/pineberrygames ) when trying to ban them for spamming YouTube videos containing circumvention of technological measures, they will be unable to block the user, allowing them to spam freely form then on without the developer noticing very much.

Add a section to the settings that allows managing blocked users please.

EDIT: I would like to point out that this ticket, being a straight (just like #123), cannot be anything other than a maximum priority ticket approved by destiny itself. #

**Comment by fasterthanlime** [comment]
And now it's https://github.com/itchio/itch.io/issues/652 ! Sorry :)
