### ISSUE TITLE
Squirrel.Windows error

### ISSUE THREAD

**Issue by Fox-Islam** [itchio/itch#1236]
Dear itch app team, 
I'm not sure what this error means but it came up after (while?) downloading an update to the itch.io app (I'm running v23.2.1, Windows 10 64-bit)
![image](https://cloud.githubusercontent.com/assets/28842757/26523213/8f7ceb90-430a-11e7-97a6-7a49244d8b6b.png)

Also is there any way of seeing what the progress is on the update download? I run on a pretty slow connection (600kbps peak) so it would be nice to know how long I can expect the update to take

**Comment by fasterthanlime** [comment]
Unfortunately, that's a Squirrel.Windows error (the installer/updater system we use), and it looks hairy - were you trying to install another app at the same time? Or did you quit/restart the app at some point?

It should eventually succeed - or, there's always the option of downloading the latest installer from https://itch.io/app and running it - it'll update without any issues.

As for progress report: I wish that was possible, but again, that's a Squirrel.Windows limitation :(

I've been working on another solution: https://github.com/itchio/itchSetup - which can show progress (and is actually quite a bit faster). But it's not ready yet!

**Comment by Fox-Islam** [comment]
Yeah, I had restarted the app before it started downloading the update (because it said it was searching for an update to the client for about half an hour, which I thought was a little lengthy)

Thankfully the itch app works great regardless of the version, I'll give it another attempt at pulling the update once my internet connection's a little less congested.

**Comment by fasterthanlime** [comment]
Cool! I'm going to close this since Squirrel.Windows being wonky at times is a known issue but eventually it works.

itchSetup will solve everything (as all yet-unreleased software always does) but in the meantime what I'll do is make the update process more discreet, so that it's not as alarming to users :)
