### ISSUE TITLE
Missing text in Application Menu on Itch.app for Mac

### ISSUE THREAD

**Issue by philomory** [itchio/itch#1238]
![itch](https://cloud.githubusercontent.com/assets/200123/26525967/0f8073e0-4304-11e7-8fb5-bb3b536e15a4.png)

The four instances of `undefined {}` should say "About itch", "Hide itch", "Hide Others" and "Show All", respectively. 

Also, in the Help menu, there's an item, `Version 23.4.1 {}` that should probably just be "Version 23.4.1" (without the `{}` characters).

This is itch 23.4.1, running on Mac OS X 10.11.4.

**Comment by fasterthanlime** [comment]
Thanks for the detailed report! This has already been fixed in master and will be deployed in the next major version.

**Comment by fasterthanlime** [comment]
No longer a thing in v25, so, closing.
