### ISSUE TITLE
🏁 Issue v23.4.1 External app store links not shown in app

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [itchio/itch#1241]
Dear itch app team,
I added store links (Windows store) to my game and it shows up on the itch website but I cant find anything about it in the itch app. Is it possible to add the store links there as well?

sincerrely
Alexander S.

**Comment by fasterthanlime** [comment]
Found the issue, working on a fix!

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch/issues/1241
