### ISSUE TITLE
Preorder placeholders are considered actual uploads, they shouldn't

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [itchio/itch#1242]
Dear itch app team, 
I just added a pre order placeholder for one of my games but the itch app has an install button showing an error cause there are no files to install (I uploaded a jpg placeholder). It would be great if the install button could be changed to "Pre-Order" if you have pre order items. :)

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/895
