### ISSUE TITLE
🏁 Issue v23.4.1 Text preview does not show Headings in proper size

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [itchio/itch#1243]
Dear itch app team, 
when I edited some of my game pages today I noticed that the Heading 1-6 formats appear much bigger in the editor than on the actual page. Maybe its possible to change this so you see the real size in the editor? Heading 4 just looks like bold text on the game page but in the editor it's a few sizes bigger.

**Comment by fasterthanlime** [comment]
That's a good point - although, please report site issues to the proper issue tracker: https://github.com/itchio/itch.io/issues

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/653
