### ISSUE TITLE
Editing profile theme color - submit behavior

### ISSUE THREAD

**Issue by samuelesque** [itchio/itch#1245]
Pressing enter from color input box when editing profile theme toggles first game in list from show/hide.
I'd expect a "save" submit, or, perhaps nothing at all.

Difficult to capture with a .gif, so here's an [11 second YouTube video](https://www.youtube.com/watch?v=-kADhG-No6k) outlining the problem.

Chrome Version 58.0.3029.110 (64-bit)
Windows 10 Version 1703 - Build 15063.332

**Comment by fasterthanlime** [comment]
Ah, this is a website issue, moving to https://github.com/itchio/itch.io/issues/655
