### ISSUE TITLE
Appear differently when app has focus

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1246]
Because frameless

**Comment by kuon** [comment]
I think it should be more obvious than Spotify for example, how just slightly darker title color.

**Comment by fasterthanlime** [comment]
do you have any concrete suggestions? I was thinking outline + some color changes, maybe something more obvious can be done (we have the full power of CSS at our disposal after all)

**Comment by kuon** [comment]
The thing is, the app can be interacted with even when not focused, so it should not be on content (like full dim).

I'd go with title/buttons color change (just more obvious than spotify 2% light change) and I'd also put the itch.io logo in grayscale.

For the outline, it's standard windows behavior too, so I'd adjust it too.

**Comment by fasterthanlime** [comment]
> I'd go with title/buttons color change (just more obvious than spotify 2% light change) and I'd also put the itch.io logo in grayscale.
> 
> For the outline, it's standard windows behavior too, so I'd adjust it too.

That makes sense. Except for the itch.io logo because it's already monochrome :) I can dim it, though!
