### ISSUE TITLE
🏁 Cover image for downloaded game doesn't properly update from gif to non-gif

### ISSUE THREAD

**Issue by ShawnCowles** [itchio/itch#1247]
I have my own game installed via the itch.io app. Previously the game's cover image was a gif. I recently replaced it with a static image. When looking at the game's page in the In the itch.io app, however, the game cover still shows the gif. When I hover the cover image it turns into the expected, non-gif, cover image.

![cover image bug](https://cloud.githubusercontent.com/assets/1155528/26755427/daa6e116-4841-11e7-9ee9-88856a0217c8.gif)

**Comment by fasterthanlime** [comment]
That has to do with how the app remembers game records.

There's `coverUrl` and `stillCoverUrl`. If there's both, the app shows the "GIF" indicator, and the `stillCoverUrl` one - and the `coverUrl` one on hover.

So, now that it's no longer a GIF, it does exactly the same, except both are static images. There's a bunch of technical solutions to this problem, I'm not sure which @leafo wants to implement.

The app could have a special case when saving game records: if `stillCoverUrl` is undefined in the game response object, it could explicitly null out `stillCoverUrl`. Or the response could actually contain a JSON null (but I'm almost certain it's hard to do in lua).

Anyway, the problem only shows for you (and anyone who already has installed the game or added it to a collection). New users won't see it.

**Comment by fasterthanlime** [comment]
This doesn't appear to be an issue in itch v25 anymore:

![image](https://user-images.githubusercontent.com/7998310/45494851-3c435300-b772-11e8-85fb-9d3e36232b66.png)

Switching from an animated cover to a static one does zero out the animated cover field:

![image](https://user-images.githubusercontent.com/7998310/45494875-4cf3c900-b772-11e8-89dc-c7baa9c9756e.png)

You can download itch v25 from: https://itch.io/app
