### ISSUE TITLE
Wrong search result when hitting enter quickly.

### ISSUE THREAD

**Issue by kuon** [itchio/itch#1248]
It might be desired behavior, but when typing in the search box, and hitting enter directly without waiting for results doesn't go to the right result.

For example, if I type "overland" quickly in the search box, followed by enter, without waiting for the search results to update, it doesn't go to the overland page, but some "random" search result.

The sequence is as follow:

- I start typing "overland" in the search box
- When I am at "over" some results appears, let's say first result is A
- I continue to type "land" to get "overland" in the search box and hit enter
- Page of game A opens, instead of searching for "overland" and going there

**Comment by fasterthanlime** [comment]
that's something that always bothered me with twitter's search box, I'm sure it can't be *that hard* to fix actually.

(note that search is getting revamped completely)

**Comment by fasterthanlime** [comment]
@kuon is this still an issue in the beta? https://fasterthanlime.itch.io/install-kitch

**Comment by kuon** [comment]
I'm under arch so I grabbed the source of the v24.34.0-canary release. I hope it's the right one. And yes, the issue is still present with this release. I did `npm install & npm start`.

I also noticed that while playing with the search field, I often have no result (might be related to the dev build I grabbed).

**Comment by fasterthanlime** [comment]
> I also noticed that while playing with the search field, I often have no result (might be related to the dev build I grabbed).

That could be #1901 

> And yes, the issue is still present with this release.

So what you expect is, when you press enter and the query has changed (but the results haven't been returned yet), it should wait for the results, then open the first result?

**Comment by kuon** [comment]
> So what you expect is, when you press enter and the query has changed (but the results haven't been returned yet), it should wait for the results, then open the first result?

Yes.

I just tried it, and typed "dicey" + return and found myself on the "domiverse" page because it was the displayed result (after typing "d").

**Comment by fasterthanlime** [comment]
I hope you're happy @kuon, look what you made me do:

![enter-quickly](https://user-images.githubusercontent.com/7998310/42644173-32e0b59e-85fb-11e8-8a01-5bc3c1c1ab53.gif)

(this is me hitting "Ctrl+Shift+F", typing "dicey" then Enter quickly)

This will land in the next build.
