### ISSUE TITLE
🏁 Issue v23.4.1 Embedded games not shown in itch app

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [itchio/itch#1250]
Dear itch app team, 
it seems html5 or unity embedded games are only visible on the normal website but not inside the app. I have an install button but get an error cause there are no files to install. When I open it in a browser I see the game. Is it possible to show them in the app too?

**Comment by fasterthanlime** [comment]
The way I see it, it's a website bug - uploads that are used for HTML5 embeds should never be "hidden / prevented from being downloaded". When they are, you see the behavior you describe.

If you just uncheck "Hide this file / prevent it from being downloaded", you'll see that the Install button works just fine :)
