### ISSUE TITLE
Mouse back/forward button not working

### ISSUE THREAD

**Issue by TheHardew** [itchio/itch#1264]
I have a mouse with 4th and 5th button, for going back/forward. It automatically works in chrome, windows explorer, steam and other apps I can't remember. Unfortunately, the itch.io app doesn't support it, I have to manually press the back icon.

Itch app 23.4.1
Windows 10 home insiders preview build 16199

**Comment by fasterthanlime** [comment]
This has been fixed in master and will be released in v25 :)
