### ISSUE TITLE
Game not installed after crash

### ISSUE THREAD

**Issue by jackjt8** [itchio/itch#1272]
Itch v23.4.1

Win10 Home v1703 Build 15063.413

I've noticed this happen to both Unity and UE4 titles, I'm unsure about other engines but I'm looking out for them. For whatever reason, if the game crashes itch will forget about them. The games will still launch just fine if ran via their exes but they will not show up in itch's library. It is possible to install the game again and itch picks it back up after this.

**Comment by fasterthanlime** [comment]
Do you have a way to reproduce this reliably? Like, a set of steps that makes it happen every time?

It definitely shouldn't happen! (And I haven't seen it happen before, so I'm curious).

**Comment by jackjt8** [comment]
Not really reliably. All I have been able to figure out is if the game crashes it disappears from itch's library. 

A game that tends to crash at least once or twice a day would be Airmen. Sometimes it crashes due to Radar_pre_leak_64 other times... no errors in event viewer. Each time it crashes I find I need to reinstall it.

It might just be Windows 10 itself really messing up, which really wouldn't surprise me.

**Comment by fasterthanlime** [comment]
Can you zip your whole `%APPDATA%/itch/cave-logs` folder and upload it as an attachment here?

(Alternatively, send it to hello@itch.io and mention "app" in the subject line)

**Comment by jackjt8** [comment]
[cave-logs.zip](https://github.com/itchio/itch/files/1089701/cave-logs.zip)

**Comment by fasterthanlime** [comment]
Cool, those logs tell me it happened once with Airmen, and once with Raft.

Can you also upload `%APPDATA%/itch/marketdb/caves` zipped?

**Comment by jackjt8** [comment]
Strange, It's occurred much more than that. I've had to reinstall Airmen at least 3 times and I've had it happen once with Ravenfield 5.

[caves.zip](https://github.com/itchio/itch/files/1091416/caves.zip)

**Comment by fasterthanlime** [comment]
When it happens, do you have the game open as a tab? Or are you installing/launching from the library tab or a collection tab?

Also, what exactly happens - the `Launch` button turns back into an `Install` button? Something else?

**Comment by fasterthanlime** [comment]
Oh hey some of those files are full of null bytes

... is your %APPDATA% on something other than a local hard drive / SSD ?

**Comment by jackjt8** [comment]
I do game installations from a mixture of collection and game tabs. While I always `Launch` from the library tab.  After a crash, the game is missing from the library tab and going to a collection tab or game tab shows `Install`. 

Actually, checking `%appdata%\Roaming\itch\apps\` again, I'm seeing duplicate game folders for Airmen and Raft. (ie Airmen & Airmen 2) Not seeing that for any others so that might explain some things.

I'm not sure why it's full of null bytes. I have a single 1TB HDD with 2 partitions (notebook) and I have only moved Documents, Downloads, Music, Pictures, & Videos over to the `D:\` drive due to the limited space of `C:\`. I've not tried to move anything else over, at least not since I did a clean install of Windows a few months ago. The full path, minus my username, is `C:\Users\_username_\AppData\Roaming\itch`.

**Comment by fasterthanlime** [comment]
Well then, I have no idea why this is the first report I'm getting about this exact failure condition (although it [looks like others are having similar problems on win10?](https://community.aseprite.org/t/file-full-of-zero-bytes/31)) but the good news is that the next major version of the app won't be writing installation info directly to disk as json files, but using SQLite instead (which does its own locking, and writes to a single file, without renaming).

So, it's probably not worth the effort to implement at workaround for the old app version - I'm 99% confident that particular issue will simply not exist on the new, SQLite-backed version of the app. Sounds good?

**Comment by fasterthanlime** [comment]
Potential same issue here: https://superuser.com/questions/845270/what-could-cause-the-files-to-be-replaced-with-null-bytes-size-and-timestamp-no#comment1114595_845270 - have you been running defragmentations lately? (and/or does Win10 do it automatically)

**Comment by jackjt8** [comment]
It's likely an issue with my install of Windows. Windows 10 is well known for misbehaving on systems for no apparent reason. I'm not too knowledgeable when it comes to all that stuff, but it seems like that should work. Then again, this is Windows 10. Will have to wait and see how the new version fairs.

By default defragging is automatic. I had turned it off but it seems an updated turned it back on. Checking when they last ran it seems the last defrag was 17-06-07 for `C:` and 17-06-15 for `D:`. I've only recently started using Itch so it's unlikely that this is the cause. There is on boot defragging that is sometimes ran, but... I didn't need to reboot for most of these.

**Comment by fasterthanlime** [comment]
v25 is out, it uses SQLite for storing caves, and SQLite is known to work around a bunch of bs filesystems tend to pull off. (I'm still pretty sure that was just a nasty Win10 bug, but I guess we'll never know!)

Please re-open if you see what appears to be the same issue in v25.

You can download the new app from https://itch.io/app
