### ISSUE TITLE
🏁 Feedback v23.4.1 - Suggestions: Adding from local drive

### ISSUE THREAD

**Issue by coder1000** [itchio/itch#1274]
Dear itch app team:

(I've made it to git from the "feedback" menu option in the app.)

I can't seem to find an obvious way to add titles that have  been downloaded from the itch website and/or are on the local drive. A related action would be to be able to add titles not even a part of itchio at all, similar to the option in Steam (lowest left button "+ ADD A GAME" > "Add a Non-Steam Game"). It could make the app a great overall game manager. (Just a limited title with a run button ... why leave the itch app if everything is right there? Especially if folders or tagging were also someday added.)

Would you consider allowing the user to add games from the local drive? (Or is it there and I missed it?)

-- coder1000

**Comment by fasterthanlime** [comment]
We've been playing with both ideas, will let you know when it's ready!

**Comment by fasterthanlime** [comment]
Closing in favor of #1706
