### ISSUE TITLE
Overriding the default directory in installer-based games causes issues on computers with multiple user accounts.

### ISSUE THREAD

**Issue by waltdestler** [itchio/itch#1279]
My game (https://waltdestler.itch.io/cosmoteer) uses Inno Setup because it requires the .NET Framework and some DirectX components to be installed as prerequisites. (AFAIK these are not yet support in itch manifests.) In general, I'm very pleasantly surprised at how well the itch app handles this, with one caveat...

I noticed that when Itch runs the installer, it changes the installation directory from the default (`Program Files`) to `AppData\Roaming\itch\apps`. This can cause a couple problems when the game is installed on computers with multiple user accounts:

- The game will be installed in the start menu for all users, but will only be accessible by the user who installed the game via the itch app.
- If another user also installs the game (either via the itch app or by manually installing), it changes the registered installation directory of the game, such that if the first user tries to uninstall the game, it will uninstall the 2nd user's copy and not the 1st.

This probably only affects a small number of itch users, so maybe not such a big deal, but I figured I should point it out.

**Comment by fasterthanlime** [comment]
Thanks for the detailed report.

I don't think there's a good way to work around this issue in general - we need the default install location to be something the current user has read/write access to, hence %APPDATA%.

However, for computers with multiple users, I'd recommend adding another install location and making it the default, so that the games installed are available for all Windows users on the system.

**Comment by fasterthanlime** [comment]
I've documented the issue over at https://itch.io/docs/itch/installing/known-issues.html (it'll update in a bit) - so, I'll be closing this.

Also, I think it should have all the prerequisites you need now? https://itch.io/docs/itch/integrating/prereqs/ feel free to open another issue if there's still missing prereqs.
