### ISSUE TITLE
🏁 Feedback v23.4.1

### ISSUE THREAD

**Issue by yvan-sraka** [itchio/itch#1280]
Event log:

```
API Error: invalid collection

stack:
API Error: invalid collection
    at Client.<anonymous> (C:\Users\yvans\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\api.ts:91:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\yvans\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment]
This brought down the whole app? What's your itch.io username ?

**Comment by yvan-sraka** [comment]
No, only one page .. My itch.io username is [yvansraka](https://yvansraka.itch.io/) :wink:!

**Comment by fasterthanlime** [comment]
> No, only one page

Oh, good! Were you trying to view a collection of yours?

**Comment by yvan-sraka** [comment]
I'm not sure, I do not remember, but it's true that I deleted one of my collections yesterday, and it's possible that this page was opened in this tab, but then I think that in this case a 404 error would be a better message!

**Comment by fasterthanlime** [comment]
That's almost certainly what happened, and I completely agree. Will keep it in mind!

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/1281
