### ISSUE TITLE
🏁 Issue v23.4.1 can't install (unicode title?)

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#1288]
Dear itch app team, 
my game fails to install: https://candle.itch.io/the-dark-third

[2017-07-01 @ 23:16:27.341] [reactors/tasks] Error in task install: *os.PathError mkdir C:\Users\mark\AppData\Roaming\itch\apps\ \aeropause-windows: The system cannot find the path specified.
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/fs.go:165 (0x7d7641)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/fs.go:107 (0x7e7859)
C:/Go/src/path/filepath/path.go:351 (0x50a100)
C:/Go/src/path/filepath/path.go:376 (0x50a37f)
C:/Go/src/path/filepath/path.go:398 (0x50a585)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/fs.go:138 (0x7d728a)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:560 (0x7e602a)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:445 (0x7e4e2c)
C:/Go/src/runtime/proc.go:185 (0x42a186)
C:/Go/src/runtime/asm_386.s:1629 (0x44f991)

[2017-07-01 @ 23:16:27.341] [reactors/tasks] Install failed for fresh cave, destroying
[2017-07-01 @ 23:16:27.344] [reactors/tasks] Error in install: *os.PathError mkdir C:\Users\mark\AppData\Roaming\itch\apps\ \aeropause-windows: The system cannot find the path specified.

**Comment by fasterthanlime** [comment]
hahahahaha yes. I guess we should be falling back to the slug and, if everything else fails, `game-:gameid`.

---

(side-note: I still remember folks who were pissed at folders being UUIDs in an old version of the itch app instead of something human-readable. THIS WAS WHY)

**Comment by bguyl** [comment]
If you take the last part of URI instead of game's name, it may resolve your issue and stay human readable.

**Comment by fasterthanlime** [comment]
> If you take the last part of URI instead of game's name, it may resolve your issue and stay human readable.

That's more less the plan, yep! (That's what I meant by `the slug`).

**Comment by fasterthanlime** [comment]
In (the upcoming) v25, the game installs correctly as the app uses the slug:

![slug-based](https://user-images.githubusercontent.com/7998310/28969535-3886238c-7925-11e7-8d63-c43ff0cbc42f.png)

Closing to keep track of what's still to do for v25!
