### ISSUE TITLE
Ubuntu Software Center icon, description, website and screenshot

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#129]
Figure out how to get all of those working. 

I'm guessing [AppStream](http://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html) — but I have no idea where what should go and how to get it working with fpm

**Comment by LiamDawe** [comment]
Might not be worth it right now, as FYI the USC is being replaced in 16.04: http://www.omgubuntu.co.uk/2015/11/the-ubuntu-software-centre-is-being-replace-in-16-04-lts

**Comment by fasterthanlime** [comment]
Ah _sigh_. Hopefully they keep AppStream around ?

**Comment by LiamDawe** [comment]
Well, the article claims it will use this https://wiki.gnome.org/Apps/Software

**Comment by fasterthanlime** [comment]
Ah cool, they use AppData which is an AppStream subset, and they even have a validator. This'll be easy

**Comment by fasterthanlime** [comment]
> TIP:Use _at_ rather than @ if you're worried about the email address being harvested by spammers.

Hahaha but they still live in 2003 though

**Comment by fasterthanlime** [comment]
This is a good issue if someone wants to help — by providing a template AppData file in the format described in https://people.freedesktop.org/~hughsient/appdata/

I'll integrate it into our CI scripts so that it appears in the right place in the .deb package.

Screenshot URLs can be taken from #771 and https://github.com/itchio/itch/blob/master/release/common.js contains a bunch of variable sthat might correspond directly to fields required for the AppData.

The long description could be adapted from this page: https://itch.io/app

**Comment by fasterthanlime** [comment]
(id is itch.desktop, license is [MIT](https://github.com/itchio/itch/blob/master/LICENSE), so is metadata license, summary is the github project's description, update_contact is maintainer address in common.js linked above, project_group is probably just `itch.io` ?)

**Comment by Moth-Tolias** [comment]
>  Permissible license codes include:
> 
> CC0-1.0
> CC-BY-3.0
> CC-BY-SA-3.0
> GFDL-1.3

@fasterthanlime the specs seem to say only these ones are acceptable licences for the metadata... what would you advise?

**Comment by Moth-Tolias** [comment]
i'm just, uh, gonna leave this here
[app data for itch.xml.txt](https://github.com/itchio/itch/files/372644/app.data.for.itch.xml.txt)

**Comment by fasterthanlime** [comment]
Reopening, Ubuntu Software Center is a jerk and requires special .deb fields instead of reading appstream.

**Comment by fasterthanlime** [comment]
Okay, so, I'm super sorry about the outcome of this and any profanity that may pop in later in that thread, but: it doesn't look like this is fixable.

First of all, there's like 12 variants of the AppStream spec floating around on the internet, all disagreeing on which fields are required - but no big deal, just add them all. Then there's 3 validator tools, 1 of which won't run, 1 of which is deprecated, and 1 of which is written in D (_sigh_).

After fixing ALL the warnings and reading through all pages I could find a dozen times each, it looks like, in fact:
- upstream developers (so, like, us) are supposed to write appstream metadata
- then we're supposed to abide by all the insane packaging rules
- then we're supposed to find a maintainer that's willing to add us to an official repo
- then the repo is backed by like a hundred tools, one of which extracts appstream metadata (and mirrors screenshots, etc.)
- then you can finally use the Gnome Software app which is a fork of the Ubuntu Software Center which means, of course, that it's slow and that it won't work (been trying to install trivial updates for an hour, I know)

So if you have a third-party .deb, you're out of luck. You're so out of luck, in fact, that even if you specify the License field in your .deb package, it'll show up as "NON-FREE" prominently in the Software app. I naively thought the software app would look up `/usr/share/metainfo/itch.appdata.xml` inside the .deb package (it's _right there_ after all! and both the GNU ar and the GNU tar format (whose idea was this?) have random access so they could get away with just decompressing a few bytes?!?!?) but nooo it's all stripped because "it would mean users would have to download more data otherwise".

Oh and btw installing any .deb graphically on the latest Ubuntu has been [broken for a while](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1573206) so yeah fuck upstream (ie. us) I guess.

Super sorry but marking this as "wontfix". The only fix will be to just finally get rid of .deb and .rpm packages altogether and implement Squirrel.Linux so the app can update itself (yes, Josh, with a switch to turn it off, sure, why not). It'll _still_ be less trouble than all that.

I truly regret spending so much time making our .deb and .rpm packages good. I wish I had spent that time elsewhere. Anywhere else really.

</rant>
