### ISSUE TITLE
🍎 undefined {} items in menu

### ISSUE THREAD

**Issue by buntekuh** [itchio/itch#1293]
Dear itch app team, 

on Mac, when clicking "itch.io" the view stays blank. However, If I type the url "itch.io" on another tab, the page loads fine.
When opening the "itch" menu item, most entries show a "undefined{}", see attached screenshot.

![bildschirmfoto 2017-07-05 um 12 01 56](https://user-images.githubusercontent.com/13592/27859698-de67ba68-6179-11e7-9fe9-b0984fa84c9e.png)
![bildschirmfoto 2017-07-05 um 12 02 20](https://user-images.githubusercontent.com/13592/27859699-de680a4a-6179-11e7-96a8-a089f9452f59.png)

**Comment by fasterthanlime** [comment]
Hey there,

`undefined {}` in mac menu is a known issue for v23.4.1, next major version will fix that.

As for the `itch.io` tab being blank, that one's new. Does anything happen if you hit the `refresh` button on that tab?

**Comment by buntekuh** [comment]
You're right, hitting reload actually works. So it's not so much of an 
issue.

Thanks


Am 05.07.17 um 15:30 schrieb Amos Wenger:

**Comment by fasterthanlime** [comment]
v23.4.2 was released and it fixes that issue!

**Comment by buntekuh** [comment]
thanks!


Am 17.07.17 um 11:07 schrieb Amos Wenger:
