### ISSUE TITLE
Right sidebar is hidden on first open of restricted game

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1294]
Open a restricted-access game in itch app (but the one you have access to). Right sidebar appears for a brief moment, and then disappears.
Refresh button helps most of the time, bringing right sidebar back, but not every time.

It happens for me with almost 100% probability when I start the app (having restricted game as a current tab left from previous session). It happens a bit rarer when I open restricted game from My creations or Collections, but still very frequent. It seems to not happening at all with public games.

Of course I'm logged into itch browser under my itch account.

**Comment by fasterthanlime** [comment]
Draft/restricted behavior is definitely snafu in v23.4.1, I'll see how the latest branch behaves.

**Comment by fasterthanlime** [comment]
Doesn't seem to be an issue anymore in itch v25, please re-open if it still is.
