### ISSUE TITLE
Give react-intl a shot

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1300]
- [x] Hook up provider
  - [x] Work around react not re-rendering on context change bug
  - [x] Completely get rid of I18nProps
  - [x] Get rid of full `localizer/` package
  - [x] Get rid of interleave
  - [x] Reduce usage of `injectIntl` to a strict minimum

**Comment by fasterthanlime** [comment]
:shipit: 🌟 ✨

**Comment by quyse** [comment]
So, is any of FormatJS syntax for plurals/etc supposed to work already? I tried syntax for plurals in `sqlite-first` branch, and it doesn't seem to work, just shows format string as is.

**Comment by fasterthanlime** [comment]
> So, is any of FormatJS syntax for plurals/etc supposed to work already? I tried syntax for plurals in sqlite-first branch, and it doesn't seem to work, just shows format string as is.

What's your example string ?

**Comment by quyse** [comment]
I replaced one of the strings in `src/static/locales/ru.json`:
```json
    "sidebar.collection.subtitle": "{itemCount} {itemCount, plural, one {приложение}, few {приложения}, many {приложений} } в коллекции",
```
And got:
![2017-07-08-171734_529x151_scrot](https://user-images.githubusercontent.com/416215/27986058-aecda648-6401-11e7-970a-09e16386f7e2.png)

Simple substitutions with single braces (`{itemCount}`) actually work as well as with double, but if there's plural syntax in a string, everything is displayed as is.

**Comment by quyse** [comment]
Oh, sorry, it actually works! I re-read the docs https://formatjs.io/guides/message-syntax/#plural-format, and fixed the string:

```json
    "sidebar.collection.subtitle": "{itemCount} {itemCount, plural, one {приложение} few {приложения} other {приложений} } в коллекции",
```

So I have to use `other` instead of `many`, and there should be no commas between `one`, `few` and `other` clauses. That's quite tricky syntax.

ADD: and space between braces in the end `} }` is mandatory. :thinking:

**Comment by fasterthanlime** [comment]
> Oh, sorry, it actually works!

ahAH!

I'm not familiary with the FormatJS syntax yet, but hey if it lets us do those things nicely (and it let us get rid of my old i18n code, which was *eerily similar* to the old code) then that's good.

As a note: please don't use the plural syntax in locales just yet (via https://weblate.itch.ovh/ for example) as old versions of the app will definitely choke on that. I'll start converting locales over to the new format a little while after v25 is out.

**Comment by quyse** [comment]
> please don't use the plural syntax in locales just yet (via https://weblate.itch.ovh/ for example) as old versions of the app will definitely choke on that

Yep, that's what I thought too!
