### ISSUE TITLE
🏁 Feedback v23.4.1 - Suggestion: Show the size of the download beside the Install button

### ISSUE THREAD

**Issue by surashu** [itchio/itch#1303]
For games with multiple downloads available, you can see a popup that shows how big the download will be.

![github1](https://user-images.githubusercontent.com/12764163/28064539-a6d75dc2-6667-11e7-9c7c-f187e38f56b3.png)

For games that download straight away, there's no way to know how big it is because the client hides the download links from the page itself. My suggestion is that for games that install straight away without the popup above, show the size beside the Install button. Something like this.

![github2](https://user-images.githubusercontent.com/12764163/28064855-be7cb322-6668-11e7-86e3-6d316914b444.png)

That or just don't hide the download links at the bottom of the game page. If the user clicks on them, they still get installed normally and the client will treat it as if the Install button was clicked.

![github3](https://user-images.githubusercontent.com/12764163/28065003-5fcf8d4e-6669-11e7-8615-8b1fd4c4a0a3.png)

**Comment by fasterthanlime** [comment]
itch v25 is out, and while it doesn't show it *right in the install button*, it has a dialog that lets you pick which upload you want to install, what size it'll download, and how much space it needs on disk:

![ruggnar](https://user-images.githubusercontent.com/7998310/45497134-5af81880-b777-11e8-810d-5b0766ee6cee.gif)

You can download itch v25 from https://itch.io/app
