### ISSUE TITLE
Cannot install - "update" has stopped working.

### ISSUE THREAD

**Issue by Berserker66** [itchio/itch#1324]
So, I launch the itchSetup.exe on Win10 64Bit and after a bit of loading this is what I get:

https://i.imgur.com/5A0wHkZ.png

Which is the German version of "Update has stopped working".

When I tell it to open the log file, it opens this file in editor:
https://pastebin.com/hvWntGRk
Which references Discord, not itch io.

**Comment by fasterthanlime** [comment]
It's weird that there's no itch references at all in the log - the Discord app & ours use the same installer system, so it makes sense that they would appear in the same log file.

Do you have any antivirus software?

**Comment by Berserker66** [comment]
Avira Antivirus.

I tried again with it off, no difference.

**Comment by fasterthanlime** [comment]
Then I'm out of ideas at the moment :( I could start releasing an installer-less version of the app, but then we'd lose self-update

**Comment by fasterthanlime** [comment]
itch v25 is out, and it uses a different installer, so I'm hoping this problem doesn't exist anymore.
