### ISSUE TITLE
the help translate link is broken in-app for en_GB

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#1327]
In the preferences section, the help translate button leads to a broken link for en_GB, it goes here https://weblate.itch.ovh/projects/itch/itch/en-GB/ which doesn't exist

**Comment by muhammadabdulrahim** [comment]
This isn't just en-GB. I'm having the same problem with en-US. Using Win10 itch v23.6.0

**Comment by muhammadabdulrahim** [comment]
Looked more into it. Under `src/components/preferences.tsx` there's this bit of code on line 346:

```ts
    let translateUrl = `${urls.itchTranslationPlatform}/projects/itch/itch`;
    const english = /^en/.test(lang);
    if (!english && lang !== "__") {
      translateUrl += `/${lang}`;
    }
```

I believe the intent is that the link should go to https://weblate.itch.ovh/projects/itch/itch/ and show 100% translation completion, however that is not the case. Using my system default (en-US) it claims itch is only 58% translated, but switching explicitly to English (presumably US) brings up 100%. The code above should work just fine if the default language is set to `en-US` or `en-GB`, but I'm under the suspicion that is not the case here as the string concatenation within the if statement is called even on English.

**Comment by fasterthanlime** [comment]
Actually, that code works properly, it's just not in v23.6.0 (or any of the v23.x releases)!

You can check the currently-released version of the app in branch `v23`, which has, in `src/components/preferences.tsx`:

```typescript
    let translateUrl = `${urls.itchTranslationPlatform}/projects/itch/itch`;
    if (lang !== "en" && lang !== "__") {
      translateUrl += `/${lang}`;
    }
```
