### ISSUE TITLE
Community to Early Access Games Unavailable to Purchasers

### ISSUE THREAD

**Issue by SolarLune** [itchio/itch#1328]
Hey, there. 

Basically, you can't easily get to the community of an early access game, even after purchasing it, from within the itch app. For example, it's not possible to get to Overland's community unless you visit the game's page from a browser.

Itch version: 23.2.1.

**Comment by fasterthanlime** [comment]
Looks like it shows up correctly in itch v25:

![image](https://user-images.githubusercontent.com/7998310/45689011-214a5780-bb53-11e8-9287-4d80b149d4fa.png)
