### ISSUE TITLE
Add game to collection. And remove from collection from itch app. How to do?

### ISSUE THREAD

**Issue by eecollante10** [itchio/itch#1332]
- Mac osx sierra
- itch 23.4.2

**Comment by fasterthanlime** [comment]
Adding:

  * Open game in a tab
  * Click the 'Add to collection' button on the top-right of game pages (the app's window must be large enough) to add a game to a collection.

To remove from a collection:

  * Open the "Collections" tab
  * Click "Manage my collections"

So basically, use the website, from the app. Native collection editing facilities will be added to later versions of the app!
