### ISSUE TITLE
Support .jars out of the box

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#134]
Let's not turn into a java installation manager just yet but... if `java -jar game.jar` works it's that many games that just work

**Comment by fleskesvor** [comment]
[packr](https://github.com/libgdx/packr) is distributed under the Apache 2 license and is pretty lightweight, so I _think_ an alternative might be to either ship it with the app, or encourage developers to package their games with it. (Which they need to do if they want to distribute their games on additional distribution platforms anyway.)

**Comment by fasterthanlime** [comment]
I'm all for educating developers on how to better pack their games — but that's a long-term goal.

In the short-term though, I'd like to get as many games possible running with itch

Thanks for the link though! We need to figure out a way to put together a game packaging/redistribution guide /cc @leafo

**Comment by xSke** [comment]
+1

**Comment by fasterthanlime** [comment]
Closed by https://github.com/itchio/itch/commit/6deec89f583ff67de66e2ed5539123b34d363eaa
