### ISSUE TITLE
Investigate browser performance claims

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1349]
Compare chrome loading URL vs app:

http://leafo.net/dump/slowbrowser.mp4

**Comment by fasterthanlime** [comment]
Start app with `DEVTOOLS=2`, record the Network tab of the relevant devtools.

**Comment by fasterthanlime** [comment]
(Note that your video is comparing apples & oranges - itch first opens itch.io/my-collections, then it gets redirected to itch.io/login?return_to=etc., whereas you paste the login URL directly into chrome)

**Comment by fasterthanlime** [comment]
Here's what I was able to find. In itch, there's a delay after the initial HTML is loaded:

![my-purchases-itch-2](https://user-images.githubusercontent.com/7998310/28390193-53021354-6cd9-11e7-8008-be04e50e3115.png)

Chrome strangely starts loading resources immediately - before it's even started receiving the HTML.

![my-purchases-chrome](https://user-images.githubusercontent.com/7998310/28390234-78374eb4-6cd9-11e7-90e7-d51f009c2258.png)

I wouldn't be surprised at all if Chrome is doing some preloading. This might be available to electron apps behind a flag, or it might be a chrome-only feature.

**Comment by fasterthanlime** [comment]
New, much better theory: the script injected into all web pages requires some modules, and that takes time:

![module-require](https://user-images.githubusercontent.com/7998310/28390399-38e66ec4-6cda-11e7-95ee-86623591de1e.png)

**Comment by fasterthanlime** [comment]
@leafo I just pushed a fix, please confirm that perf is now on par with what you'd expect
