### ISSUE TITLE
Support .love games out of the box

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#135]
Only question is how do they let us know which love version they need?

**Comment by Ragzouken** [comment]
you could extract https://love2d.org/wiki/Config_Files from the .love and try to extract the version number (foolproof would be to execute the lua file, but then you'd need to embed lua lol)

**Comment by fasterthanlime** [comment]
There's a discussion going on in the itch community forums as well: http://itch.io/t/11981/lve-2d-love-file-support

**Comment by fasterthanlime** [comment]
> but then you'd need to embed lua lol

..or just a lua parser! [luaparse](https://github.com/oxyc/luaparse) is only 90k with deps, 23k zipped.

**Comment by LiamDawe** [comment]
An alternative is to get people using a launcher file if they aren't using a normal executable, Steam does this.

**Comment by fasterthanlime** [comment]
> An alternative is ...

So do we, we launch `.bat` files in priority on Windows, and `.sh` on Linux and OSX in the absence of an .app bundle

**Comment by nunodonato** [comment]
I just posted on the forum before checking this page!

Maybe how about starting with an easy(fast) solution and then improve it over time? For now, any .love game will not work in linux. Instead of bundling dependencies, or trying to install stuff, just assume that the developer has notified that love needs to be installed, and run "love file.love" from the itch.io app. Probably it will be easy to detect if "love" is a valid command or not, and notify the user if its not installed.

**Comment by fasterthanlime** [comment]
> Maybe how about starting with an easy(fast) solution and then improve it over time?

:+1:

**Comment by Alloyed** [comment]
Assuming itch wants users to provide their own love install, it might be fine to ignore version numbers entirely:
1. Most users will only have the latest stable version of love installed
2. There is no standard way to have multiple love installs side-by-side
3. Opening a .love file in the wrong version of love will generate a warning anyways

so for the times that doing `love the-game.love` doesn't work the best thing you can do is to get the user to resolve the situation themselves by manually pointing to a different version of love/using a [wrapper script](https://github.com/Alloyed/flirt).

**Comment by aaronfranke** [comment]
Considering [you just released a .love game](https://fasterthanlime.itch.io/capitalism-simulator) you may wish to make this a higher priority. It's a bit silly for the Itch app to not support the apps from the creator of the Itch app :stuck_out_tongue:

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/808
