### ISSUE TITLE
Collections should be shown in order returned by API

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1351]
They look sorted by id asc now.

https://itch.io/api/1/me/my-collections

![2017-07-19_11-32-08](https://user-images.githubusercontent.com/15198/28383478-229e5ffa-6c76-11e7-9698-0b4ced3778fc.png)

**Comment by fasterthanlime** [comment]
in v25, they appear in API order (unless a different sort is specified)

![image](https://user-images.githubusercontent.com/7998310/45494157-c38fc700-b770-11e8-8742-8b4fa96501de.png)

This is achieved through the `profile_collections` table: https://github.com/itchio/butler/blob/decbb11f56397bbce7ac41697718c52a1a197cff/database/models/profile_collection.go

(psst you can download v25 from https://itch.io/app @leafo, I hear it's "cool")
