### ISSUE TITLE
Update logo in sidebar

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1353]
Use the new round one, not old square one

http://itch.io/static/images/itchio-textless-white.svg

![2017-07-19_11-43-30](https://user-images.githubusercontent.com/15198/28383897-8b21c610-6c77-11e7-8c39-096656627544.png)

**Comment by fasterthanlime** [comment]
Please make sure to update http://itch.io/static/images/itchio-textless-black.svg as well (that's what I baked in itch's icon font in the first place)

**Comment by fasterthanlime** [comment]
well, I'd fix it but icomoon is down for me at the moment (keeps loading forever..)

**Comment by leafo** [comment]
updated the image on the site

**Comment by fasterthanlime** [comment]
Done.

Btw I'm sure we could find better icons for library & dashboard (and use them on the website too for consistency? - I'm fairly happy with the "Collections" one)

![updated-icon](https://user-images.githubusercontent.com/7998310/28408932-5323284a-6d39-11e7-8e5f-fb08a29e3864.png)
