### ISSUE TITLE
🏁 Issue v23.4.2

### ISSUE THREAD

**Issue by ShinySky42** [itchio/itch#1369]
Dear itch app team, 

Project Hedra is actually on sale at 100% of reduction, but when I choose to download the game, it won't ad it to my Library
Thanks you to fix it,

regards

**Comment by fasterthanlime** [comment]
So you're downloading it from the itch.io app?

Can you post the address of the game's page ?

**Comment by ShinySky42** [comment]
forget about that, I just linked the game to my account, Sorry for the inconvenience

**Comment by fasterthanlime** [comment]
No problem! 🌟
