### ISSUE TITLE
Apparently Corrupted Game Install: cannot launch, local files don't exist, cannot uninstall

### ISSUE THREAD

**Issue by ShawnCowles** [itchio/itch#1370]
The game in question is [Star Commander](https://membranesoftware.itch.io/star-commander)

And here is the [debug log](https://gist.github.com/c20685fa2c39c39245e4f53138f055a3) from trying to launch it.

It seems that something went wrong with downloading the game.  The Star Commander folder doesn't exist under "AppData\Roaming\itch\apps". I can't launch the game, and the itch.io app appears to freeze when I try to uninstall the game. Nor can I find a place to manually deregister the game from the itch.io app.

**Comment by fasterthanlime** [comment]
Probably an MSI file that doesn't respect TARGETDIR/INSTALLDIR. I'd point the developer to https://itch.io/docs/itch/integrating/platforms/windows.html

**Comment by fasterthanlime** [comment]
Revisiting this just now, v25 does allow you to uninstall a game "forcefully" if graceful uninstallation fails.

oh, also: the app detects if TARGETDIR/INSTALLDIR aren't respected:

![image](https://user-images.githubusercontent.com/7998310/45689128-6ff7f180-bb53-11e8-86a5-fd3c49c99274.png)
