### ISSUE TITLE
Itch.io "package manager"

### ISSUE THREAD

**Issue by violetastcs** [itchio/itch#1372]
I think this is a good idea because say, for example, a game included a software that your can't distribute easily due to licencing (such as games made in the blender game engine, since it's distributing the blender game run time you can't publish more than 1000 copies unless you get a licence to do so from the blender foundation) or due to other reasons (I know python is rather hard to compile to an .exe). So, my Idea is that you could optionally supply a list of dependencies for the game and the itch,io client would install them (if you are using the website then it would just show the dependencies). And, to get around the "no distribution" problem, the developers could just supply links to a download for the dependency and (like I said) itch.io does the rest for you! This could also be useful for cross platform games that use engines like love2d, as they would just have to supply the .love file and the engine downloads the right version for their operating system.

If this was implemented, it would DEFINITELY make me pick Itch.io over gamejolt once again

Thanks in advance!

**Comment by fasterthanlime** [comment]
Prerequisites do that job: https://itch.io/docs/itch/integrating/prereqs/
