### ISSUE TITLE
Itch desktop edition prevents pulseaudio from working.

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1375]
When I boot into a game the audio works fine. Then I close it, and pulse doesn't work anymore. When I try to load pulse it never stops loads.

This has happened to me on multiple games (Funny enough they are all unity games.)
Raft & Ancient Warfare 2 are the most noticeable examples.

**Comment by fasterthanlime** [comment]
What happens if you launch these games without the itch app? Does it break pulse as well?

Also: what distribution are you running, which version, have you ever had problems like this before?

**Comment by fasterthanlime** [comment]
I've experienced pulse crashing on me when running games, but I'm pretty sure they would also crash pulse if ran independently.

The OP has deleted their github account so, closing this now :(
