### ISSUE TITLE
Visual C++ Preqreqs documentation is incorrect

### ISSUE THREAD

**Issue by thothonegan** [itchio/itch#1377]
In docs/integrating/prereqs/vc.md ( https://itch.io/docs/itch/integrating/prereqs/vc.html ), it says to use 'vc-redist-2010-x86' and such for each version of MSVC. However, this returns a 404 error that the redist doesnt exist. Apparently they're actucally named vcredist-2010-x86 . (for all of the redists : 2010, 2013, 2015, 2017).

As a quick example:
* https://dl.itch.ovh/itch-redists/vc-redist-2017-x86/info.json
vs
* https://dl.itch.ovh/itch-redists/vcredist-2017-x86/info.json

**Comment by fasterthanlime** [comment]
Good catch, thanks! The docs will update themselves in a little bit.
