### ISSUE TITLE
After first installation of a game its version cannot be changed

### ISSUE THREAD

**Issue by borbware** [itchio/itch#1378]
When you install a game for the first time, a "Multiple downloads are available" dialogue appears. If you choose a wrong version - too bad! Even after uninstallation, you cannot pick the correct version anymore.

**Comment by fasterthanlime** [comment]
> Even after uninstallation

Hum, that sounds really fishy.

I'm not able to reproduce this: when I install https://sophieh.itch.io/roseandtime - pick one download, then uninstall, and try to install again, I get the choice again. Are you sure you weren't installing a game for which some uploads were removed afterwards?

I agree that there should be a way to switch versions while the game is installed though :)

**Comment by Sojurn7** [comment]
I have a copy that is not a full version there is no easy mode and the first day all I get is endless amount of zombies can not play to heard. I will uninstall this game and try is over if not removing your site and reporting it to the gaming association in Microsoft.

**Comment by fasterthanlime** [comment]
> I agree that there should be a way to switch versions while the game is installed though :)

v25 shipped with that feature. It also lets you install multiple uploads in parallel.
