### ISSUE TITLE
Support for Ludum Dare

### ISSUE THREAD

**Issue by FrozenCow** [itchio/itch#138]
http://ludumdare.itch.io/ is great, but I couldn't find a good way to add it to itch. Is there a good way? If not, what would be a good way to implement such a thing in itch?
Most preferably with some way to open the review pages on Ludum Dare. Streamlining game playing + reviewing!

**Comment by fasterthanlime** [comment]
At first I had in mind a browser extension that adds `itchio://` url but that's pending on #116. 

We also want to start having `itchio://` links on itch.io itself, but hopefully in a non-intrusive manner: shouldn't be an "ad" on a game page (devs own game pages), and it shouldn't be in the face of those who don't want to use the client (it'll never be required).

**Comment by FrozenCow** [comment]
That sounds like an even better idea. However, how can game ids be determined from an Ludum Dare game? Is there an even more undocumented API call? :P

**Comment by fasterthanlime** [comment]
> Is there an even more undocumented API call? :P

Not yet but you never expect the spanish inqui-@leafo
