### ISSUE TITLE
Allow translating text within the app

### ISSUE THREAD

**Issue by RichardLuo0** [itchio/itch#1395]
Please add the translate function，thank you

**Comment by fasterthanlime** [comment]
Can you expand a little bit on that?

The app is translated into 20+ languages, but the website isn't. Are you talking about the website? Or about specific games on itch.io?

**Comment by RichardLuo0** [comment]
just like that:
![1](https://user-images.githubusercontent.com/22096448/29128759-537b7c24-7d57-11e7-9ba6-f5a5c241c79d.png)

**Comment by fasterthanlime** [comment]
I don't see a feasible way to do that for now.
