### ISSUE TITLE
🏁 Issue v23.4.2

### ISSUE THREAD

**Issue by Sojurn7** [itchio/itch#1397]
Dear itch app team, where the hell are all your reviews to let people know if a game is shit game or not for this game survive the zombies needs to be in the trash, It make you glad we have steam site not the best but at lease we are not getting ripped off. last game I get from here...

**Comment by muhammadabdulrahim** [comment]
Click the "More information" tab. Same for app and web browser...

**Comment by fasterthanlime** [comment]
Yup, pretty much what @muhammadabdulrahim said.

Also, for website issues, please use this tracker: https://github.com/itchio/itch.io/issues
