### ISSUE TITLE
Warn about 'close to tray' behavior

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#140]
1. Warn about minimizing to tray instead of quitting the first time
2. Give the option to disable the `minimizing to tray` behavior? I still feel like itch is rather well-behaved (you can tell it back off anytime with CtrlOrCmd-Q) but some might want that. And I feel like the world is collectively scarred from Skype enough to warrant such an option.
3. Make that option settable from the first warn dialog, e.g. a "Gee, no thanks, just quit when I do that" button, and remember that, and indicate where the user can change its mind.

`1.` is easy, but I kinda want to do all three at once and this requires a settings dialog of some sort, so it won't be in 0.9.4-next

**Comment by fasterthanlime** [comment]
Hey we have a settings pane now! so it doesn't seem too hard to do.

**Comment by fasterthanlime** [comment]
The Slack app pops a balloon up when you close the main window, seems like a good compromise.

**Comment by elisee** [comment]
For the upcoming redesigned Superpowers app, we'll have a tray icon too so this is interesting.

One thing I added yesterday is to [minimize the window before hiding it](https://github.com/superpowers/superpowers-app/blob/eb8b62859424343efcfdda1e3f6a8dc5a76cbdb9/src/main.ts#L101) when it is closed by the user, to convey the fact that the app isn't closing. Couldn't find a way to detect when the minimize animation has finished so went with a "feels good enough" 200ms delay.

Showing a balloon notification when the last window is closed in next on my list...

**Comment by fasterthanlime** [comment]
We do that now!

**Comment by quyse** [comment]
@fasterthanlime On my development machine (Arch Linux) I'm using `xmonad` tiling window manager, which doesn't have any sort of traditional tray panel. So after closing the window it's still running invisibly, and the only way to actually close itch app is to manually kill the process. Therefore the option to disable 'close to tray' behavior would be much appreciated :)
