### ISSUE TITLE
Handle single files again (in core)

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1407]
Test page (private): https://itch-test-account.itch.io/zipped-installer-2

**Comment by retropipes** [comment]
Thanks for opening this, as this issue definitely affects some of the assets I've acquired. They're uploaded as a non-archive single image, which itch doesn't know what to do with, and falsely reports install failure, when in fact what's happened is the file has been downloaded, but itch is missing the logic to get it copied to the install folder, so it thinks install failed...

**Comment by fasterthanlime** [comment]
@wrldwzrd89 are you seeing this with itch v23.4.2 (stable) or with kitch (beta builds) ?

**Comment by retropipes** [comment]
@fasterthanlime itch 23.4.2 (the stable version).

**Comment by retropipes** [comment]
I've tested this in kitch and noticed the exact same behavior there too.
