### ISSUE TITLE
Investigate if `src/` folder is still necessary for prod builds

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1427]
I suspect everything we need (but the `init.js` files) are in .cache

Also, the compiled files have inline sourcemaps so it should bre ok.

Right now there's two copy of the 4MB emoji png for example.

**Comment by aaronfranke** [comment]
Distributing the source code along with the program is a nifty feature for power users, might be worth keeping if the disk usage is minimal.

**Comment by fasterthanlime** [comment]
In my last test build, the `src/` folder was around 10MB, whereas `.cache` was 8MB.

Note that the `src/` folder also contains stuff like webfonts and an emoji spritesheet. For folks who want to read the source offline, releases are tagged on GitHub so you can just read it from here, and when trying to pinpoint an issue using the Chrome devtools, for example, that's where inline sourcemaps come in - they contain the original source code already.

**Comment by fasterthanlime** [comment]
We don't use electron-compile anymore, everything is bundled with parcel, the `src` folder is not necessary anymore.
