### ISSUE TITLE
🏁 Issue v23.4.2 - Extracting archive with Japanese file names result in corrupted filenames.

### ISSUE THREAD

**Issue by surashu** [itchio/itch#1432]
Example: https://herbna.itch.io/futayuri

If you install the above game using the itch.io client, it will fail to run because it can't find one of the plugin files.
![image](https://user-images.githubusercontent.com/12764163/29539478-93915744-86fc-11e7-9da5-9481af69e609.png)

This doesn't happen when I download the zip manually and extract using 7-Zip. So I inspected  the itch.io client's folder for the game and see that the plugin file got renamed to gibberish.
![image](https://user-images.githubusercontent.com/12764163/29539523-e41f6ce6-86fc-11e7-86c4-7921ab43538e.png)

There are other files named in Katakana in the game's folder that got renamed to gibberish too. The `receipt.json` file also contains the broken file names.
![image](https://user-images.githubusercontent.com/12764163/29539581-307ebc4a-86fd-11e7-9d03-543dcbed7a5a.png)

This is how the file's name should be displayed.
![image](https://user-images.githubusercontent.com/12764163/29539647-6f07d97e-86fd-11e7-8320-14cc272050ca.png)

**Comment by fasterthanlime** [comment]
futayuri installs & runs fine in the itch v25 client: 

![image](https://user-images.githubusercontent.com/7998310/45688247-28706600-bb51-11e8-9a69-f0090b0ea78e.png)

(we detect character sets in .zip files - utf8 is preferred, then shift-jis if we detect it with a high enough confidence index, then cp-437 as a fallback).
