### ISSUE TITLE
Feature Request: itch:// protocol as an alias of itchio://

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch#1434]
Personally, I think it would be nicer if `itch://` worked as well as `itchio://`. `itch` is faster to type than `itchio`, it's easier to remember, and it better represents Itch since Itch now has a very good desktop app, it's not just a website extension, so the io part is not necessary to describing the platform.

But of course, `itchio://` should be kept for backwards compatibility.

Blocks: https://github.com/itchio/itch.io/issues/701

**Comment by fasterthanlime** [comment]
I'd like to have @leafo's thoughts about this.

**Comment by aaronfranke** [comment]
Is @leafo planning to give his thoughts about this?
