### ISSUE TITLE
Downloading epub file unpacks it instead of moving it to relevant directory

### ISSUE THREAD

**Issue by Xananax** [itchio/itch#1440]
When downloading the epub version of

https://notimetoplay.itch.io/when-development-is-the-game

The download executes correctly and downloads `74112.epub`, but the installed archive results in 

```
│   mimetype
│
├───.itch
│       receipt.json
│
├───META-INF
│       container.xml
│
└───OEBPS
    │   content.opf
    │   toc.ncx
    │
    ├───Images
    │       attack-vector-177.jpg
    │       bas-relief.png
    │       ...etc
    │
    └───Text
            350_the-art-of-ascii.html
            a-look-at-card-games.html
            acknowledgements.html
            ...etc
```

**Comment by fasterthanlime** [comment]
itch v25 is out, and it correctly downloads the .epub as-is, instead of extracting it:

![image](https://user-images.githubusercontent.com/7998310/45496815-97774480-b776-11e8-8f69-38c683afb61f.png)

You can download itch v25 from https://itch.io/app

**Comment by Xananax** [comment]
Excellent, thank you so much for all the hard work
