### ISSUE TITLE
🐧 Kitch v24.1.7 doesn't account for timezones but Itch v23.4.2 does

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch#1446]
![kitch-time](https://user-images.githubusercontent.com/1646875/29738034-fa9b0126-89de-11e7-80f2-8fd5859f9fec.png)

On the left, you can see Itch v23.4.2, at the right of the window it says "Bought a minute ago".

On the right, you can see Kitch v24.1.7, at the bottom of the window it says "Bought in 5 hours".

Refreshing the page does not fix the problem, neither does restarting Kitch.

My Timezone is UTC-5. My OS is Linux, Xubuntu 16.04 64-bit.

**Comment by fasterthanlime** [comment]
That's probably an import problem, I'll look into it.

**Comment by fasterthanlime** [comment]
> That's probably an import problem, I'll look into it.

It wasn't an import problem at all, but I did find a fix :)

![bought-ago](https://user-images.githubusercontent.com/7998310/29749430-97b4e5c4-8b2b-11e7-90fb-351d6cd03492.png)

**Comment by fasterthanlime** [comment]
(I'll release a new kitch build soon so you'll be able to check that it's fixed)

**Comment by aaronfranke** [comment]
Confirmed fixed.
