### ISSUE TITLE
Add Java to prerequisites list

### ISSUE THREAD

**Issue by Ezard** [itchio/itch#1452]
- Should ideally support the latest release of several major versions (at least Java 7 and Java 8, maybe Java 6 but probably not)
- Since Java is cross-platform, should work on all of Windows, macOS and Linux

**Comment by fasterthanlime** [comment]
Adding Java as a prerequisite isn't in my plans for now. My personal recommendation to folks shipping java games is to use something like https://github.com/libgdx/packr to distribute native executables instead.

(Even if we did use the JRE's "silent install" option on Windows, that wouldn't solve the problem for macOS & Linux, which both have specific installation methods that are awkward to automate)

**Comment by Ezard** [comment]
Ah okay, thanks, wasn't aware of the macOS/Linux problems

**Comment by Ezard** [comment]
@fasterthanlime I came up with a much simpler solution

If Java is specified as a prerequisite, then the itch client simply runs a `java -version` command, and opens a dialog telling the user to either download Java or update it (with a link to https://java.com/download/), depending on whether java is on their path and whether it's greater than or equal to the version specified in the manifest

Or if Java is on their path and the version checks out then the game would obviously just be launched

If you're too busy working on other stuff, then I'd be happy to implement it myself - just point me at the relevant section of the codebase and I'll get cracking

**Comment by retropipes** [comment]
Even there, we really should encourage future Java game developers to use Java 9 (or later) and the `jlink` tool to build native packages with the Java bits built-in. Then this can be wrapped in a DMG / MSI / TGZ archive for upload. Itch will then not need to even deal with it.

**Comment by Ezard** [comment]
@wrldwzrd89 yep, I agree - this issue was created before Java 9 was a thing, so can probably be closed now 🙂

**Comment by fasterthanlime** [comment]
Alright, since there seems to be consensus here, I'll be closing this.

Note that since this was opened, I've added more logic for launching .jar files: first it checks if you have a JVM, and if not, it tells you you should install one. If you do have one, it launches it with your currently installed JVM. This is not a silver bullet, as your JVM might be too old, but it did work for all the games I tried.
