### ISSUE TITLE
Investigate granting lstat-only access to $USERPROFILE to make more recent electron games work in itch.io sandbox on windows

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1470]

**Comment by fasterthanlime** [comment]
Research!

---

**Electron games start working if you grant R (read) access to every folder leading up to the app's folder**. The reason is that they do an `fs.realpath` on some file in the app's root folder, and node.js tries to `lstat` every parent folder to, well, figure out and resolve any symlinks.

So if the game is in `C:\Users\amos\AppData\Roaming\itch\apps\LOCALHOST`, then you need to grant R to:

  * `C:\Users\amos`
  * `C:\Users\amos\AppData`
  * `C:\Users\amos\AppData\Roaming`
  * `C:\Users\amos\AppData\Roaming\itch`
  * `C:\Users\amos\AppData\Roaming\itch\apps`

(Note: I tried giving `RA` (read attributes) and `REA` (read extended attributes) only and it wouldn't work. I'd be happy if we could give stricter permissions than `R` but I don't know what they are. There's a bunch of them).

These should not have any inheritance - we only want to let the electron app lstat these folders exactly.

This sounds bad it's not really:

  * Giving READ access to a folder does not give access to the files in it, so you can't steal anything that way
  * It does make `lstat` (and thus `realpath`) succeed though, which is all electron/node.js is asking for.
  * These all belong to the user running the itch app, so we don't need administrator privileges to adjust their permissions.
  * There's only a handful of them, it's not thousands of file.

---

The above could be done as calls to icacls (like we do right now), something like:

```bash
icacls.exe C:\Users\amos /grant "itch-player-59922ff6:R" 
```

..but actually, we can't, because icacls *always* walks the full directory structures (all sub-folders and files, recursively), even without `/T`, or `(CI)`, or `(OI)`, and even if it ends up modifying only the DACL of the exact path you give it. I don't know why it does that, I should probably find out why it does that before adopting the proposed fix.

I tried dropping to pure Win32 API to do it instead, but [SetNamedSecurityInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379579(v=vs.85).aspx) has the exact same behavior. Here's what it looks like:

![share4](https://user-images.githubusercontent.com/7998310/29887839-071c3c88-8dbf-11e7-863d-c17ef1cfc95e.png)

---

`SetFileSecurity` however, is able to change the permissions for a single directory *without walking the full tree*, which is awesome. However, the code required to perform any changes is quite lengthy:

  * First we use `GetNamedSecurityInfo` to retrieve a security descriptor for the folder, along with its current discretionary ACL (discretionary access control list)
  * Then we initialize and fill out an `EXPLICIT_ACCESS` structure with the rights we want to grant or revoke
  * Then we merge that ACE (access control entry) into the existing ACL (to retain existing permissions)
  * Then, we convert the security descriptor to absolute format (needed to be able to modify it)
    * This involves a *bunch* of API memory allocations and two calls to `MakeAbsoluteSD`
  * Then we write our new DACL into the security descriptor via `SetSecurityDescriptorDacl`
  * Then we finally call `SetFileSecurity` with that security descriptor

And it works!

![sample-evil-app ong](https://user-images.githubusercontent.com/7998310/29888301-c0c5fd08-8dc0-11e7-8bb2-0c3b0c09fd2d.PNG)

Since there's no inheritance going on, we need to do that N times, as mentioned earlier, for each folder from $USERPROFILE up to the game's install folder. A better way would be to do it for folders that the itch-player user cannot read yet, but it seems to be like the code to do that will be long. It might be necessary though, because there can be install folders in other locations (like an external drive).

(Note that itch-player already has `R` access to `C:\` and `C:\Users`, so we don't need to mess with those).

(Note also that we might want to use `GetFileSecurity` instead of `GetNamedSecurityInfo` for consistency. The {Get,Set}FileSecurity functions are marked as deprecated, but they're also listed as the only low-level functions available. Maybe in 8 versions of windows we'll have to find another fix)

---

The complete source code for a solution is here: https://gist.github.com/fasterthanlime/ea38871666bc7cc486c272650523c9e1

It needs to be cleaned up, and I'd rather be writing that in golang, directly in butler - it *will* require writing a bunch of our own bindings most probably, because I seriously doubt anyone is calling these particular functions in Windows.

---

Other thoughts: from the looks of this, it seems like we could completely do away with our `icacls` usage and just call `SetFileSecurity` ourselves on the app's install folder, with container inheritance (CI) and object inheritance (OI) - this would significantly speed up start-up time for games that contain many files, when the sandbox is enabled.

**Comment by gryte** [comment]
After reading this, I'm pretty confident this is related to what I'm experiencing when trying to launch Left from the itch.io desktop app on Windows 10.

Cross-referencing hundredrabbits/Left/issues/44

**Comment by fasterthanlime** [comment]
@gryte quick update in image form:

![image](https://user-images.githubusercontent.com/7998310/36063022-be7c000a-0e77-11e8-8038-96c767210270.png)

**Comment by fasterthanlime** [comment]
Now done in master.
