### ISSUE TITLE
Select From Multiple Games in a Single Download

### ISSUE THREAD

**Issue by ghost** [itchio/itch#148]
For a game collection like East Van EP, pressing the "launch" button after install will only launch the game in the first folder. Ideally, there would be a way to select which game in the download to launch. I experienced this problem on OS X.

**Comment by fasterthanlime** [comment]
Related issues: #92, #96 

Since this requires UI, it won't be part of 0.9.4-next, but definitely keeping it in mind for later versions.

**Comment by fasterthanlime** [comment]
Closing in favor of #92

**Comment by roseroser** [comment]
Thanks for you friends
