### ISSUE TITLE
Make sure `chalk` is a dep, not a devDep

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1493]
See https://github.com/itchio/itch/issues/1491

**Comment by tanmayameher** [comment]
sorry i have the same problem on arch linux.
But, what is meant by this sentence of yours. "chalk is a dep, not a devdep"?
Please, help. What can i do to avoid this error. It's happening during opening of application :)

**Comment by fasterthanlime** [comment]
See https://github.com/itchio/itch/issues/1499
