### ISSUE TITLE
I have GiBs of disk space but Tacoma doesn't have enough space to install?

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#1496]
`[2017-09-02 @ 17:45:24.228] [reactors/tasks] Install failed for fresh cave, destroying
[2017-09-02 @ 17:45:24.238] [reactors/tasks] Error in install: *os.PathError write C:\Users\mark\AppData\Roaming\itch\downloads\554056-40061.zip-stage/Tacoma_Data\sharedassets7.resource: There is not enough space on the disk.
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:202 (0x7301e8)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:210 (0x73063f)
C:/Go/src/runtime/asm_386.s:1635 (0x452d81)`

**Comment by Ragzouken** [comment]
Oh okay i didn't realise it was an 11GB game! but... i can't work out how to free up the space used downloading/installing it after it failed

**Comment by fasterthanlime** [comment]
> i can't work out how to free up the space used downloading/installing it after it failed

Delete C:\Users\mark\AppData\Roaming\itch\downloads\554056-40061.zip-stage ?

**Comment by Ragzouken** [comment]
Just to steer this to something more useful (after this time trying to install night in the woods) i think that if itch fails to install due to disk space it seems to be leaving around the failed install -- so natually it seems however much space you create it's always eaten up by your last try. I had three failed installs of NITW hanging around in my itch folder but was able to install after deleting them all.

**Comment by fasterthanlime** [comment]
@Ragzouken yep, that's definitely what v23 does :( sorry about that.

v25 (upcoming) contains many improvements regarding disk space usage - during and after installing games - and never leaves temp files hanging around, no matter what the outcome of the install. I can't wait to ship it!

**Comment by Ragzouken** [comment]
yeah i actually was just reading the other thread where you explained this ha, so sorry to make you repeat yourself!
