### ISSUE TITLE
Implement new 'feedback' system tied to itch.io

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1511]
Issues were previously posted to github, which is bad because:

  * It forces users to have a GitHub account
    * some might give up at this stage, so we don't see some reports
  * The (anonymous) gist linked in the GitHub issue is anonymous, so they can't delete it (only remove the link), and it might contain personal info (like login name, host name, CPU model, GPU model etc.). Nothing critical but still annoying.

So the plan it so post it on itch.io instead, and have it visible by
  * The reporter
  * itch.io employees
  * The developer of the game if we decide to reassign the ticket to them

Instead of just posting a bunch of text, the info posted to itch.io should be structured, so we can group issues by meaningful categories.

**Comment by ghost** [comment]
Current feedback system should be blocked. Anonymous gists are being killed.

https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by fasterthanlime** [comment]
This is well on its way.

However, I want to open beta testing for v25 before the issues platform is ready - the plan is to roll the simplest pastebin service, with the following characteristics:

  * Posting a report generates a unique URL
  * The report is opened in a browser after it's sent
  * Whoever views the report can delete it
  * Only I (and anyone who has the URL) can access reports
  * I plan to review reports, convert them to github issues, and delete them as soon as possible

Additionally, the service will be deleted (and all the associated data wiped) when the beta is over and the real issues system "takes over".

I believe this is a reasonable temporary solution for beta testing.

---

Additionally, reports will include *part* of the info provided by https://www.npmjs.com/package/systeminformation - in particular, `cpu()`, `graphics()`, and `osInfo()`.

**Comment by fasterthanlime** [comment]
Screenshots!

![image](https://user-images.githubusercontent.com/7998310/41864134-2aa44f76-78a9-11e8-8056-7f22ecd9884f.png)

![image](https://user-images.githubusercontent.com/7998310/41864160-3b96abe4-78a9-11e8-9086-ff7990527b92.png)

![image](https://user-images.githubusercontent.com/7998310/41864173-43d62262-78a9-11e8-8211-0e53c2a90d25.png)

![image](https://user-images.githubusercontent.com/7998310/41864181-4ac882e0-78a9-11e8-9e4c-9c851fa92f2d.png)
