### ISSUE TITLE
Don't use butler to clean download folders (at least not in preboot)

### ISSUE THREAD

**Issue by ghallberg** [itchio/itch#1519]
Using Arch, with kitch from AUR.

When I start the program I get the login screen, and manage to log in, but after that there's no content in the window.

Running from terminal, I get an error:
![partial-2017-09-16-09 38 22](https://user-images.githubusercontent.com/672910/30510389-1e9887c0-9ac3-11e7-8502-26d1828f99e2.png)

This is what I see in the client: 
![full-2017-09-16-09 37 03](https://user-images.githubusercontent.com/672910/30510391-24af06f2-9ac3-11e7-9fec-649e0238b4a7.png)

**Comment by fasterthanlime** [comment]
Alright, the log messages are unrelated to the blank window. I'm investigating further.
