### ISSUE TITLE
🐧 desktop client doesn't understand ebooks

### ISSUE THREAD

**Issue by clayote** [itchio/itch#1520]
When hthr released [THREE DAYS](https://hthr.itch.io/three-days) it showed up as a book in my feed, but when I clicked through to the page for the story itself, there was no install button; instead, I saw the notice "Not available on GNU/Linux". It's just a PDF, it should download anywhere.

I got her to mark it as a game for all platforms to make the download happen, but this predictably failed to present a smooth experience in the app, which presented a launch button but failed to launch a game that didn't have any executables in it.

So she switched it back to a book...and...it's still showing up as a game to me? I tried clearing my browsing data but it's still the same! It even says "View game" in the feed, now.

I'm on vanilla Ubuntu 17.04.

**Comment by fasterthanlime** [comment]
The issue here is the page's classification: it should be set to "Book", not "Game".

![classification](https://user-images.githubusercontent.com/7998310/30516956-67394a7e-9b4e-11e7-8eaf-c44cc1c28874.png)

As long as it's "Game", the app will try to launch it.
