### ISSUE TITLE
Launching 'Xob' made Bitdefender quarantine the Itch client

### ISSUE THREAD

**Issue by omgitsraven** [itchio/itch#1522]
Here is the sequence of events that's happening:

1. I bought the hurricane relief bundle, which came with this game: https://mrtedders.itch.io/xob
2. I installed it in the Itch desktop client.
3. I clicked the button to launch it, and instead, the Itch client window disappeared.
4. I launched the Itch client again and tried launching Xob again several times, with the same result each time.
5. Eventually, Bitdefender Security started giving me popups saying "infected file detected", and it 'quarantined' the Itch client from my computer. It said it quarantined 50 files, but in fact it only quarantined these as far as I can tell:
- c:\users\andrew\appdata\local\itch\itch.exe
- c:\users\andrew\appdata\locallow\crØss games\equinox\unity\ea15cb2d-f22d-4bd4-b40c-6c5dacf16fe7\analytics\archivedevents\150568900700001.2f5a4bc7\e
- c:\users\andrew\appdata\roaming\itch\bin\unarchiver\unar.exe
- c:\users\andrew\appdata\locallow\crØss games\equinox\unity\ea15cb2d-f22d-4bd4-b40c-6c5dacf16fe7\analytics\archivedevents\150568900700001.2f5a4bc7\s
- c:\users\andrew\appdata\roaming\itch\bin\butler.exe
- c:\users\andrew\appdata\locallow\crØss games\equinox\unity\ea15cb2d-f22d-4bd4-b40c-6c5dacf16fe7\analytics\values
- c:\users\andrew\appdata\roaming\itch\bin\elevate.exe
- c:\users\andrew\appdata\locallow\unity technologies\viking village\unity\local.f4583d0a2ff37e54aa0f5cd66da8ab2c\analytics\archivedevents\150568974100001.47361a60\e
- c:\users\andrew\appdata\roaming\itch\bin\isolate.exe
- c:\users\andrew\appdata\locallow\unity technologies\viking village\unity\local.f4583d0a2ff37e54aa0f5cd66da8ab2c\analytics\archivedevents\150568974100001.47361a60\s
- c:\users\andrew\appdata\roaming\itch\bin\dllassert\dllassert32.exe
- c:\users\andrew\appdata\locallow\unity technologies\viking village\unity\local.f4583d0a2ff37e54aa0f5cd66da8ab2c\analytics\values
It seems to be all files from games I launched in this same session.
6. I restored all the files from quarantine, but the Itch client would no longer launch, even after a reboot.
7. I reinstalled the Itch client from scratch, and it launched like before, but trying to launch Xob just acted the same as before; the client disappeared and Bitdefender started methodically deleting all the executables in the Itch folder.

I know this is probably largely Bitdefender's screwup, but it seems like you should at least be aware that it's going to be happening for Itch users who are also using Bitdefender. I'm on Windows 7 64-bit, Bitdefender Antivirus Plus 2018, and whatever the latest version of the Itch client is (as I've just manually reinstalled it and it happened again).

**Comment by fasterthanlime** [comment]
Unfortunately Antivirus software often makes our job more complicated, but it's good to be aware that it exists, so, I appreciate the detailed report here, thanks!

I'll definitely take a closer look at Xob, but first - does it happen with any game at all or just Xob?

**Comment by omgitsraven** [comment]
Only Xob; I played several other games before that and had no trouble.

**Comment by fasterthanlime** [comment]
Another question: do you have the itch.io sandbox enabled?

**Comment by omgitsraven** [comment]
This is the first I've heard of the itch.io sandbox, so if it isn't enabled by default, then no.

**Comment by fasterthanlime** [comment]
> This is the first I've heard of the itch.io sandbox, so if it isn't enabled by default, then no.

It isn't, thanks for the response! It works by adding another less-privileged user to your computer, so I can see antivirus software going crazy over it.

**Comment by fasterthanlime** [comment]
Alright, the VirusTotal report for Xob is clean: https://www.virustotal.com/#/file/c994852663231edda368b0ca81b4fdf949fbc9efa2949332061d1a7c319b88d9/detection

I could try running ProcMon to see what kind of system calls it makes / what files it touches when it's running, but I wouldn't know exactly what to look for. Did BitDefender name the menace in any way? (They usually have pretty obscure names, but it might be worth a shot)

**Comment by omgitsraven** [comment]
Unfortunately it just says that "Advanced Thread Defense" detected them as "potentially mailicious"; in the detailed log they're all just flagged with "Malware".

**Comment by omgitsraven** [comment]
Also, just to be clear—I'm not even sure whether Xob even got as far as launching (I certainly never saw a window for it). I think Bitdefender saw the Itch client *trying* to launch Xob, scanned it in advance, and shut the client down for making the attempt based on some heuristic about Xob's contents, not even something Xob did (because as far as I'm aware, it didn't have a chance to do ANYTHING.)

**Comment by fasterthanlime** [comment]
> c:\users\andrew\appdata\locallow\crØss games\equinox\unity\ea15cb2d-f22d-4bd4-b40c-6c5dacf16fe7\analytics\values

the fact that this path even exists means Xob did launch - although I wouldn't be surprised if it launched in a sandbox BitDefender uses to analyzes the behavior of programs.

Out of curiosity, did you try downloading Xob on its own and launching it (while having BitDefender enabled)? If it still triggers it, the next step is probably to reach out to Xob's developer and have them submit BitDefender as a false positive here: https://www.bitdefender.com/submit/

(Now that I see it, that form looks familiar, I'm pretty sure I've had to use it before)

**Comment by omgitsraven** [comment]
That's the folder for an unrelated game: https://cr0ss.itch.io/justice-bear-equinox Like I said, it marked everything I'd launched previously in that session as being part of the malicious files.

As for downloading and running Xob on its own: yes, that sets BitDefender off. I'll mention it to the developer, but there's still the larger issue that any flagged file can take down someone's entire Itch client, and various other games they'd installed through it.

**Comment by fasterthanlime** [comment]
> but there's still the larger issue that any flagged file can take down someone's entire Itch client, and various other games they'd installed through it.

I definitely agree, but that's BitDefender's behavior :( I think the ball is in their court on this one.

We've reached out before to another AV vendor and they requested we opt into their "Safe computing" program, uploading each build of the itch app by FTP before we release it - I don't think we can afford doing something similar for all vendors :/

For your particular case, I'd just add itch's install folder `%LOCALAPPDATA%/itch` and `%APPDATA%/itch` to the whitelist, if BitDefender has the concept of whitelists.

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/1717
