### ISSUE TITLE
If user mistakenly installed 64-bit build on 32, tell them what's going on.

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1524]

**Comment by aaronfranke** [comment]
As in, a 64-bit game on a 32-bit OS? A warning is definitely a good idea.

Though, personally I would vote for dropping 32-bit Itch if it requires much effort to maintain. MacOS already warns the user if they try to run a 32-bit app (and in the future, will refuse to run them)

**Comment by fasterthanlime** [comment]
I'm pretty sure this issue is a losing battle.

After some consideration, I think that's something that should be fixed on the backend - you shouldn't be able to install a 64-bit build on a 32-bit OS.

Any message I add for that would just be cryptic to the user.
