### ISSUE TITLE
Electron 1.8.0 is not a release version of electron anymore

### ISSUE THREAD

**Issue by haatweiller** [itchio/itch#1532]
I've tried to install the following versions:
- 23.4.2 via AUR itch
- 24.4.0-canary via AUR kitch
- dev via git

All failed on installing Electron 1.8.0, most recent released version is 1.7.8. Electron 1.8.0 was dropped because of a security risk.

By changing line 117 in package.json to ` "electron": "^1.7.8", ` it fixed the issue.

OS: Arch Linux

**Comment by fasterthanlime** [comment]
I'll release a new kitch version that relies on 1.7.8, thanks for the ping!

Just to make sure though, 23.4.2 failed because of something else right? (an npm bug) - that one shouldn't be on electron 1.8.0.

**Comment by haatweiller** [comment]
Indeed 23.4.2 gives a different error, `npm ERR! May not delete: /tmp/electron-packager/linux-x64/itch-linux-x64/resources/app/node_modules/.bin`

This can possibly be because I installed through the GitHub and my Node.JS knowledge is slacking.

**Comment by fasterthanlime** [comment]
> Indeed 23.4.2 gives a different error, npm ERR! May not delete: /tmp/electron-packager/linux-x64/itch-linux-x64/resources/app/node_modules/.bin
> 
> This can possibly be because I installed through the GitHub and my Node.JS knowledge is slacking.

Cool, that's the expected error - you had me worried for a minute that I pushed an upgrade to the stable channel without knowing it ;)

**Comment by fasterthanlime** [comment]
kitch v24.5.0 is out, should fix that issue, please report back!

**Comment by haatweiller** [comment]
Yes installs without an issue. Also, starts without an issue.
