### ISSUE TITLE
Kitch 24.5 fails to build arch

### ISSUE THREAD

**Issue by StripedMonkey** [itchio/itch#1537]
In trying to update kitch to the latest version it fails,
[Log](https://hastebin.com/ukawicojiq.php)
I've tried clearing the cache and reinstalling but it seems to be the same thing every time.

Current version of kitch is 23.3 (installed Apr 13) I've not used it in a while due to life and whatnot so I realize thats kinda old. current installed version of node is --0.3.2-- 6.11.3

Let me know if you need anything! (also the itch package is 23.4 and is flagged out of date since July 16th)

**Comment by fasterthanlime** [comment]
> current installed version of node is 0.3.2

oh wow, I didn't even know that version existed - looks like it's from 2011 - kitch definitely needs a more recent nodejs to run its compile scripts now!

I guess I should put a minimum version in `makedepends` ? 

https://github.com/itchio/itch/blob/6bc1ed8e9093a7b7649068317c5099c6dc9f31e4/release/templates/PKGBUILD.in#L13-L16

**Comment by StripedMonkey** [comment]
WELL, this is why you don't just *assume* that `node` means nodejs when you are grabbing all the stupid info -.- (My fault) I stupidly decided to do `pacman -Qi node` when apparently node is something completely different. The current version of **nodejs** is 6.11.3-1 I'm not sure as to the reason but I have the LTS release /shrug

**Comment by fasterthanlime** [comment]
> The current version of nodejs is 6.11.3-1 I'm not sure as to the reason but I have the LTS release

Ah, that makes more sense :) You'll need 7.6 or newer, see [this guide](https://github.com/itchio/itch/blob/master/docs/developing/getting-started.md)

**Comment by StripedMonkey** [comment]
In that case you probably should require a higher version, currently Atom-git (you know, the text editor) *requires* the LTS release on arch. I'm not sure if this is an old thing that could be changed but I'm sure that eventually someone will come along with both the dev version of itch and Atom.

I'll ask about that but its not exactly your problem ;)

**Comment by StripedMonkey** [comment]
Using nodejs 8.7 worked fine, so yea. I would definitely suggest putting in a version check for it. In addition since we are on the subject of the AUR packages I would suggest you update the itch package as well. Its been flagged out of date since July.
