### ISSUE TITLE
Release a .rpm package

### ISSUE THREAD

**Issue by ogbaba** [itchio/itch#154]
Hello, it would be great if you could make an .rpm package and publish it.

**Comment by fasterthanlime** [comment]
Took a stab at it in https://github.com/itchio/ci.itch.ovh/commit/15e6f51716cffdd78a57db178f956800e4e9185a — if all goes well, 0.10.4 should have an .rpm package.

**Comment by fasterthanlime** [comment]
itch now has rpm packages, you can grab 0.10.4 from https://github.com/itchio/itch/releases — feel free to open separate issues if those packages are problematic!
