### ISSUE TITLE
Trying to download The Norwood Suite gives "truncate" download error 🏁 Issue v23.4.2

### ISSUE THREAD

**Issue by omgitsraven** [itchio/itch#1541]
Dear itch app team, 

I just bought The Norwood Suite: https://cosmoddd.itch.io/the-norwood-suite and tried to install it in the Itch client.
Starting the download immediately produces an error in the downloads tab; the download's status becomes "Download error", and below that it says "truncate C:\Users\Andrew\AppData\Roaming\itch\downloads\610401.exe: An attempt was made to move the file pointer before the beginning of the file."

Other games still install successfully. Rebooting my computer did not help. Disabling my antivirus did not help. Installing through the website rather than the Itch client works fine.

**Comment by fasterthanlime** [comment]
Looks like the Norwood suite is hosted on Dropbox (which isn't app-friendly) instead of using https://itch.io/docs/butler to upload large games.

**Comment by fasterthanlime** [comment]
Looks like the Norwood suite fixed their uploads in some way? Anyway it installs and runs fine in itch v25.

![image](https://user-images.githubusercontent.com/7998310/45690387-7045bc00-bb56-11e8-80ec-a8baa00dd105.png)
