### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by kylekwanpoopsed** [itchio/itch#1543]
Event log:

```
Error: net::ERR_SSL_PROTOCOL_ERROR
```

**Comment by fasterthanlime** [comment]
Are you using a proxy? If so, what proxy software is it?

**Comment by kylekwanpoopsed** [comment]
No.  But for some odd reason I just had to restart my PC for it to work.  I have no idea why...

**Comment by fasterthanlime** [comment]
Cool, thanks for reporting back what fixed it for you!
