### ISSUE TITLE
Randomizer Data Inaccessible

### ISSUE THREAD

**Issue by Colorbee094** [itchio/itch#1550]
Dear itch app team,
In your randomizer portion of the app, I found some games that I'd be particularly interested in delving into. The problem stems from a lack of capability to figure out what games those were. I pressed the "I Like It" button, but have no way of retrieving such data, and therefore playing those games.

**Comment by fasterthanlime** [comment]
Hey there,

If the game you're viewing is compatible, there should be an install button in the right sidebar:

![image](https://user-images.githubusercontent.com/7998310/31542082-f36f594e-b010-11e7-8515-6a87c7d26124.png)

If there's no install button, it's probably that the game doesn't have a compatible version!

We're aware that the randomizer experience in the app isn't ideal, but it should be at least functional -
 we'll adjust it in the next versions :)

**Comment by Colorbee094** [comment]
It's not that I can't install the games, I can't go back on my history and look at the games I've liked but haven't installed.

**Comment by fasterthanlime** [comment]
Thanks for the clarification! That's a website issue, opened https://github.com/itchio/itch.io/issues/724 to track it.
