### ISSUE TITLE
Support browser back and forward key

### ISSUE THREAD

**Issue by jgandert** [itchio/itch#1552]
Some mice / trackballs have browser back and forward keys. Having that functionality in the itch browser would be nice.

I'm using Ubuntu where this works with Firefox, but I'm pretty sure it works on Windows as well.

VK_BROWSER_BACK, VK_BROWSER_FORWARD

**Comment by muhammadabdulrahim** [comment]
There was a previous issue I opened about this same thing. It's marked closed, but I'm unsure if it was ever attended to. #1221

**Comment by fasterthanlime** [comment]
This [has been implemented](https://github.com/itchio/itch/commit/76da27a3a67915798986e19b37dceef0b4c22b08) and is still planned for the next major version (which has been in the making for several months now! :shipit:)

**Comment by jgandert** [comment]
@fasterthanlime Great to hear! Happy new year :)
