### ISSUE TITLE
docs: Bad link to executable search heuristics

### ISSUE THREAD

**Issue by salty-horse** [itchio/itch#1555]
The file [`docs/integrating/manifest.md`](https://github.com/itchio/itch/blob/master/docs/integrating/manifest.md) mentions "built-in heuristics" to find the executable to launch and links to `README.md`.

In the generate docs, this means the link at [https://itch.io/docs/itch/integrating/manifest.html]() links to [https://itch.io/docs/itch/integrating/](), which does not describe the heuristics.

**Comment by fasterthanlime** [comment]
Doesn't seem to be an issue in the current version of https://itch.io/docs/itch/integrating/manifest.html - closing!
