### ISSUE TITLE
readFile unit test fails on windows (\r\n vs \n)

### ISSUE THREAD

**Issue by alexnask** [itchio/itch#1557]
Screenshot of the test run:  
![image](https://user-images.githubusercontent.com/265903/31884585-4779ac64-b7f6-11e7-99f2-869980946503.png)

Obviously, the error is trivial, just a matter of unix vs windows newlines, although I did not modify the txt fixture, so I would expect it to still just have a unix newline in there.

**Comment by alexnask** [comment]
It appears git automatically uses \r\n on windows regardless of how the files were committed, so I'm not sure if this is even an itch bug or not anymore.

**Comment by fasterthanlime** [comment]
Oh my what are you doing here @shamanas :)

I run tests routinely on Windows both locally & on the CI, but both git clients check out with the "source" line separator, which is "\n" in that repository.

This should help maybe?

```
git config --global core.autocrlf input
```

(see https://help.github.com/articles/dealing-with-line-endings/#platform-linux )

**Comment by alexnask** [comment]
@fasterthanlime Right, thanks for that, I was unaware of this setting :)  

Closing.
