### ISSUE TITLE
🏁 Grey Lilies ↔ v23.4.2

### ISSUE THREAD

**Issue by ElTipejoLoco** [itchio/itch#1558]
:rotating_light: game [Grey Lilies](https://toki-production.itch.io/grey-lilies) is broken for me.

:book: Here's a truncated [debug log](https://gist.github.com/ElTipejoLoco/812ae86496eff026432558b8c91f3f33).

:running: Another failed install from the itch app. It looks like some checksum errors happen all of a sudden when attempting to extract the zip file? Not really sure what's going on there.

It looks like whatever's happening might be due to two of the pc version's zipped files being corrupted (love.ogg and epic.ogg), and when the itch app detects this it just gives up wholesale instead of extracting the files that do work. I decided to send a post the developer's way to inform them of this and maybe they'll reupload their game and that'll fix the whole issue.

**Comment by muhammadabdulrahim** [comment]
I tried installing this myself (name changed to Black Lilies) and had no problem, on Windows 10, v23.6.0. Try upgrading?

**Comment by fasterthanlime** [comment]
It definitely looks like it was an issue with the .zip that the developer has resolved since. Thanks @muhammadabdulrahim for checking it out, I guess we can close this now!
