### ISSUE TITLE
🏁 Kharon's Crypt - Even Death May Die ↔ v23.4.2

### ISSUE THREAD

**Issue by ElTipejoLoco** [itchio/itch#1559]
:rotating_light: game [Kharon's Crypt - Even Death May Die](https://hebilee.itch.io/kharonscrypt) is broken for me.

:book: Here's a truncated [debug log](https://gist.github.com/ElTipejoLoco/b2f1476c9a50ef73b9f833f037920089).

:running: Another failed install from the itch app. This one's probably due to the download being linked to from Mediafire, maybe? The debug log implies the app gets a bit confused by this sort of thing. Not sure what should be done about this on the app's side of things, really.

**Comment by fasterthanlime** [comment]
Indeed! Mediafire's not supported (or planned to be supported), the fix is for the game's develope to do a regular upload on itch.io (potentially with https://itch.io/docs/butler if the file is big)

**Comment by ElTipejoLoco** [comment]
Alright. I'll post a comment on the game's page telling the dev and any future potential "download isn't working in app" posters as much and linking them here if they're interested in reading more.

Should I close this issue since it's essentially working as intended with regards to the app?

**Comment by fasterthanlime** [comment]
> Should I close this issue since it's essentially working as intended with regards to the app?

Closing myself now!
