### ISSUE TITLE
App installer crashes on windows vista 32 bits

### ISSUE THREAD

**Issue by empty-fortress** [itchio/itch#156]
The installer launches, then this pops up:

![itchio_app_install_bug](https://cloud.githubusercontent.com/assets/2658281/11855860/12ceedda-a44d-11e5-88af-b9a94c142f1a.png)

Roughly translated it says "Procedure entry point Shell_NotifyIconGetRect can't be found in dynamic link library SHELL32.dll". When dismissed it pops up once or twice more, then the installer crashes.

Let me know if you need more details!

**Comment by matiasbeckerle** [comment]
At first sight, unfortunately, seems that Electron doesn't support Vista. References:
- https://discuss.atom.io/t/shell-notifyicongetrect-shell32-dll-error-on-vista/20159
- https://github.com/atom/electron/issues/691
- https://discuss.atom.io/t/does-using-xp-make-atom-hopeless/22022/2

**Comment by fasterthanlime** [comment]
Yep :( Really sorry to hear that @empty-fortress but there doesn't seem to be much we can do — we depend on electron too much and they don't seem interested in supporting versions older than Win7

**Comment by empty-fortress** [comment]
no big deal, I'll just stick to the website. Thanks for looking into this!
