### ISSUE TITLE
🏁 Feature Request: Download Location Dialogue or Notice

### ISSUE THREAD

**Issue by claws61821** [itchio/itch#1560]
Dear itch app team, 

Please include in an upcoming update either one of the following features:

1. A selection dialogue at time of download to allow the user to choose from among configured download locations
2. A notice on the Preferences page alerting users to the necessity of manually changing the default 
download location

Please also include the following:
3. A static indicator as to the purpose of the symbols in the fourth and fifth columns of the Install Locations table on the Preferences page

Thank You
---
Upon further review, I see that there is a static indicator of the current default location and that there is a dynamic 'tool tip' hover message indicating how to change the default location. This does not inherently tell a user that he or she must change the download location in this manner for every library entry. The presence of this information in the Help document is appropriate, but it is less than an optimal resolution.

**Comment by garyoa1** [comment]
Agreed. Never noticed any choice. Perhaps most today still have only one main drive but even those with multiples may be using an SSD for their main. Which leaves disk space at a premium on those drives since they're generally small. I'll likely be uninstalling and using the spam filter to take care of anything from itch.

**Comment by fasterthanlime** [comment]
@claws61821 I agree the experience isn't optimal :) Your suggestions are things we already had in mind for further versions.

I'm thinking of showing a dialog by default, showing you where it'll be installed and letting you pick another location - and a checkbox that says "don't ask me again" so the next installs involve less clicking.

**Comment by garyoa1** [comment]
Thank you. :) Maybe I'll re install it once that fix is applied. But I don't think a checkbox is required. It may be that the user wants to move it somewhere else and won't be able to if the option doesn't re-appear.

**Comment by TinKelp** [comment]
Hi, I have some suggestions for related issues.

1) Being able to auto-detect itch games. I reinstalled the itch app after a Windows restoration and I don't see a way to make it recognize the 30+ itch games I kept on a secondary drive. 

2) Being able to move an already installed game from one installation directory to another. Uninstalling and then reinstalling is a workaround but I'd rather just be able to have the app move things over for me.

Thank you for reading.

**Comment by fasterthanlime** [comment]
@TinKelp both these features are planned.

**Comment by aaronfranke** [comment]
@TinKelp @fasterthanlime Perhaps each "apps" folder should contain a file called .applist or something which holds a list of installed games and their status?

**Comment by fasterthanlime** [comment]
@aaronfranke that's already the case :)

![image](https://user-images.githubusercontent.com/7998310/33930019-d0150c04-dfeb-11e7-8b98-b8a934558920.png)

There were other technical challenges, but they've been mostly solved in the upcoming version of the app.

**Comment by fasterthanlime** [comment]
itch v25 is out, and here's what it does:

  * On first launch, it scans where itch v23 *used* to list installed applications, and tries to import those
  * On each launch, and whenever adding an install location, or when asked explicitly (via the "Scan install locations for games" button), it scans install locations for receipts.

For example, here's what I have installed right now:

![image](https://user-images.githubusercontent.com/7998310/45495863-6e55b480-b774-11e8-890c-80f50db8b412.png)

Then, if I delete all installed game info (simulating a re-install):

![image](https://user-images.githubusercontent.com/7998310/45495893-7e6d9400-b774-11e8-9735-711d7aec668f.png)

My library shows up empty:

![image](https://user-images.githubusercontent.com/7998310/45495907-89c0bf80-b774-11e8-9e1b-9022320fc78e.png)

Then I can use the scan dialog:

![scan-install-locations](https://user-images.githubusercontent.com/7998310/45495941-a0ffad00-b774-11e8-98cd-2402941d3b1c.gif)

Hopefully this addresses everything in this issue.

You can download itch v25 from https://itch.io/app

**Comment by fasterthanlime** [comment]
(oh, also: it does let you pick an install location when queuing a game now:

![image](https://user-images.githubusercontent.com/7998310/45496029-d3a9a580-b774-11e8-8a1d-f7b4f0621038.png)

I think the dropdown should let you add a location, that's what #2085 is for)

**Comment by aaronfranke** [comment]
The only thing that this doesn't do, compared to Steam, is let you add a new install location from the app's download page.
