### ISSUE TITLE
🏁 Issue v23.4.2

### ISSUE THREAD

**Issue by ymstnt** [itchio/itch#1562]
Dear itch app team, 

when I try to launch a game, I get this error:
spawn icacls ENOENT

I'm using Windows 8.1

Here is the log: [https://gist.github.com/TNTking65/5508a97d31408b17ba831ca78f4cc7fc](https://gist.github.com/TNTking65/5508a97d31408b17ba831ca78f4cc7fc)

**Comment by fasterthanlime** [comment]
At some point, your `PATH` environment variable was modified, and some built-in windows tools are now missing from it.

1. I encourage you to fix your path (`wmic.exe` is in `C:\Windows\System32\wbem\` for example, and `icacls.exe` is in `C:\Windows\System32`)
2. In the meantime, you can probably just disable the itch.io sandbox and run games.

You're bound to see other problems on your computer though, not having `C:\Windows\System32` and `C:\Windows\System32\wbem` in your PATH is definitely an issue!

Here's an article on how to edit your PATH: https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/
