### ISSUE TITLE
🏁 Issue v23.5.1

### ISSUE THREAD

**Issue by binarycrusader** [itchio/itch#1563]
Dear itch app team,

Please consider adding the ability to follow a developer when viewing their game/application.  If there is a way to do so, it isn't obvious to me.  This functionality appears to be only available in a web browser.

**Comment by fasterthanlime** [comment]
That functionality is available in the client.

![image](https://user-images.githubusercontent.com/7998310/45687872-2fe33f80-bb50-11e8-8c2d-6f47564f5702.png)

Previously, those buttons were hidden if the window was too narrow. Now they just move to the top instead:

![image](https://user-images.githubusercontent.com/7998310/45687915-45586980-bb50-11e8-9b70-4b1ca4326442.png)
