### ISSUE TITLE
🐧 Issue v23.5.1

### ISSUE THREAD

**Issue by PhoenixRiver** [itchio/itch#1566]
Dear itch app team, 

I can't upgrade with my Mint package system because it gives me this error when trying to scan the itch repository:

Failed to fetch https://dl.bintray.com/itchio/deb/dists/xenial/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)Some index files failed to download. They have been ignored, or old ones used instead.

I'm happy to wait if the upgrade is not urgent as I'm quite keen not to have to start doing upgrades manually! :)

Hope this helps and if there is any more information I can give you then I'm happy to provide what I can.

Phoenix *<:@)

P.S. I should probably say I'm running Linux Mint 18.1 (Serena) using their standard update manager (though Synaptic also gives the same error message).

**Comment by fasterthanlime** [comment]
I'm not sure why the 386 file is missing from xenial release, sounds like a Bintray quirk.

https://bintray.com/itchio/deb/itch/23.6.0 lists all the "Indexed distribution", can you find any other that works for you?

**Comment by PhoenixRiver** [comment]
> I'm not sure why the 386 file is missing from xenial release, sounds like a
> Bintray quirk.

Huh... odd.

> https://bintray.com/itchio/deb/itch/23.6.0 lists all the "Indexed
> distribution", can you find any other that works for you?

Possibly but then that'd be a solution I'd have to unfix when you next
release to check if the next one worked... as I said I'm happier just
to wait for the next version to see if that fixes things. If there is
still a problem I'll report it and see if there is a usable workaround
at that point. I hope you don't mind.

Phoenix

**Comment by fasterthanlime** [comment]
I'm going to try deploying the assets to bintray again, and if it's still missing then.. we'll have to contact Bintray support.

**Comment by fasterthanlime** [comment]
I had to delete the 23.6.0 version from Bintray and deploy a third time, but the 386 package is now there for xenial :)

**Comment by PhoenixRiver** [comment]
> I had to delete the 23.6.0 version from Bintray and deploy a third time, but
> the 386 package is now there for xenial :)

Excellent, thank you for the fix - any idea of the cause? Seems like a
bintray problem I guess...

**Comment by fasterthanlime** [comment]
> Excellent, thank you for the fix - any idea of the cause? Seems like a
> bintray problem I guess...

I have no idea except a temporary problem on Bintray's side, since

  * the i386 and amd64 files are uploaded
  * and *then* the "version" is published on bintray

(those are 3 separate API calls). So there can't be any race conditions, I really don't know what happened! (especially since it worked fine for other codewords - except xenial)
