### ISSUE TITLE
Closing itch.io app shuts down game - Unity doesn't save

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1567]
Original report from https://github.com/itchio/itch.io/issues/742

---

So I had this reported from one of my beta testers:

> Bad Bug?   My program seems to have closed while i was alt tabbed.     I lost all my progress.    When i just restarted the program, I was back on the 2nd map.  I lost all my progess since the last time i quit out to the menu.     I was on the 3rd map.(edited)
> Does this mean it crashed and didn't save?
> oh i see how it happened....  that's horrible
> I quit out of Itch.io!    i closed that program... and it shuts down my Nowhere Prophet!!
> it shuts it down so hard that it doesn't even bother to save.

As far as I can tell the app closes hard and then doesn't save properly. The game is built with Unity and uses

OnApplicationPause() 
and 
OnDisable() (which is also called when destroying)

to save the game state. Obviously this did not seem to happen here.

---

Note: this is for the (hidden) page of the https://sharkbombs.itch.io/nowhere-prophet beta

**Comment by fasterthanlime** [comment]
@Democide do you know if your tester had the itch.io sandbox enabled ?

**Comment by Democide** [comment]
To quote the user in question: 

> I have no idea what the itch.io sandbox is....  so i am assuming i don't have it enabled.  Unless it is enabled by default
> All I did was install the Itch.io app, and launched the beta program through that app.
> I found it now in my "Security and Privacy" settings.   Mine is not checked,  so I do not have it enabled.

**Comment by fasterthanlime** [comment]
The itch app now warns that exiting it will quit games that are running:

![image](https://user-images.githubusercontent.com/7998310/45687785-ebf03a80-bb4f-11e8-904e-7b4ba9f1b650.png)
