### ISSUE TITLE
Zip size limit for Zero-K

### ISSUE THREAD

**Issue by Licho1** [itchio/itch#1570]
Hello,
we are currently distributing portable version of zero-k 
https://zerok.itch.io/zero-k
but we had to restrict what is in the package, to fit 750MB file size limit on itch. 
The game engine and maps are not packaged, and have to be downloaded by the game itself.
Would it be possible to increase limit for us?

**Comment by fasterthanlime** [comment]
With https://itch.io/docs/butler/ you can upload up to 30GB, hopefully that should be enough :)

The guide should be easy enough to follow, let me know how it works for you!

**Comment by Licho1** [comment]
Ok thanks, we will look into it!
