### ISSUE TITLE
App crashing on each startup on mac.

### ISSUE THREAD

**Issue by Fahrenheit** [itchio/itch#1572]
I get this error and I'm not sure what to do. It did this upon first startup and I've reinstalled it multiple times. 

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
*** CFEqual() called with NULL first argument ***

**Comment by fasterthanlime** [comment]
That sounds like https://github.com/electron/electron/issues/10561 - is there anything over there that is helpful to you?

**Comment by fasterthanlime** [comment]
If you ever get a chance to try itch v25 (download it from https://itch.io/app), and it still crashes, feel free to re-open this issue!
