### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by ironbulldog** [itchio/itch#1574]
app won't install don't know why

![image](https://user-images.githubusercontent.com/34258922/33587815-18323ac2-d92d-11e7-818f-87f22de0da4c.png)

**Comment by fasterthanlime** [comment]
Can you copy-paste the contents of the editor that opens up when you click 'Open Setup Log' ?

**Comment by fasterthanlime** [comment]
Please re-open if that's still an issue with itch v25: https://itch.io/app

It uses a different installer as the previous versions.
