### ISSUE TITLE
Suggestion for itch client distributed with appimage

### ISSUE THREAD

**Issue by askme765cs** [itchio/itch#1575]
No bother,but I have to say,,,when I got error informations when I try to install itch client in my arch ,It really sucks.Using appimage to distribute the newest client versions may be a good idea,as anyone can use it just by download and run.I love itch.io a lot ,as it is such an amazing platform for so many great games,but the  way of  installing the client can be improved such as using appimage to make it even better.
by the way,if you decide to offer the client appimage version,I will do what i can do as much as possible  to make it come true.

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/683
