### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by BrennanHolm** [itchio/itch#1578]
I get no splash screen either.

[failedlog.txt](https://github.com/itchio/itch/files/1557773/failedlog.txt)

**Comment by fasterthanlime** [comment]
Seems like an Antivirus issue, this thread has suggestions: https://github.com/atom/atom/issues/10383#issuecomment-170818516

**Comment by fasterthanlime** [comment]
Please re-open if that's still an issue with itch v25: https://itch.io/app

It uses a different installer as the previous versions.
