### ISSUE TITLE
🏁 Issue v23.6.0

### ISSUE THREAD

**Issue by ElTipejoLoco** [itchio/itch#1582]
Dear itch app team, 
![itcherr_cert_date_invalid](https://user-images.githubusercontent.com/22507424/34341597-56f855f0-e960-11e7-9aae-7236f28aebc0.png)
I'm getting this error on any page that loads (or rather, attempts to load) the square-ish thumbnails for games (the Download list, the Library, the main page, and the right-hand info sidebar for each game's page), as well as any other individual image on the site that is hosted on img.itch.zone. The message triggers once per load attempt on screen. I'm guessing the SSL certificate for img.itch.zone needs a peek, or the handshake check for the app needs to be made a little bit more lenient? Not sure. In any case, the error messages can be "ignored," but with a large enough library or download list (which can automatically populate due to updates), it can get a little RAM intensive very quickly.
Just in case: I'm on a Windows 10 Pro 1709 (16299.125 Build) machine.

#1583 This issue appears to be directly related, actually.

Edit: It looks like the issue's been resolved, and it was probably just an SSL certificate issue. So I'm thinking it should be safe to close both this issue and 1583's, unless something comes up- like deciding to make the handshake failure error message something that triggers once per page/session as opposed to per object.

**Comment by fasterthanlime** [comment]
Closing as instructed! I've seen that message up until v23 a few times, usually it was either 1) certificates having legitimately expired 2) electron being too old / its built-in CA list being out of date.
