### ISSUE TITLE
There was an error with the certificate for img.itch.zone 

### ISSUE THREAD

**Issue by joshuah345** [itchio/itch#1583]
i ran the itch.io client after installing it yesterday and i got this error.
![captureitch](https://user-images.githubusercontent.com/29195927/34341726-a830d22a-e96b-11e7-81b3-d4767cce21c3.PNG)

it doesn't let me continue and i'm forced to quit.
Windows 10 Home 10.0.16299 Build 16299

**Comment by nothjarnan** [comment]
I'm experiencing the same issue.

Windows 10 Home v1703 build 15063.786 (64bit)

**Comment by quyse** [comment]
For me the itch.io frontpage is displayed without pictures in a normal browser too because of security error. Probably needs to be fixed ASAP @leafo @fasterthanlime

**Comment by nothjarnan** [comment]
Issue seems to be resolved now.
