### ISSUE TITLE
libXScrnSaver should be an optional RPM dependency

### ISSUE THREAD

**Issue by M-Pixel** [itchio/itch#1584]
The RPM package has `libXScrnSaver` listed as a required dependency. On OpenSUSE, which does not have `libXScrnSaver`, I am given the choice between not installing itch.io, or ignoring the dependency and potentially breaking the package. If I choose to ignore the dependency, and install the client anyways, it works perfectly. I think `libXScrnSaver` should probably be marked as an optional dependency instead, so that the user is not prompted or told that itch will be broken when none of their repositories contain `libXScrnSaver`. Otherwise, it is impossible to install it with `--non-interactive`.

**Comment by fasterthanlime** [comment]
We no longer support the RPM repository, so, closing this.

itch v25 ships with its own installer, it's the recommended way of installing it: https://itch.io/app
