### ISSUE TITLE
🏁🍎🐧 Cross-Platform Itch App Manifests

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch#1587]
https://itch.io/docs/itch/integrating/manifest.html

If this is already possible, I apologize, but it's not listed on the App Manifests page.

What I'm looking for is a way to provide a single app manifest that covers multiple operating systems at once. Currently you have to create separate `.itch.toml` files for each OS. For example, with a Unity game, the file in the Windows zip would link to `FooBar.exe` while the Linux zip would link to `FooBar.x86_64`. It is annoying to have to maintain multiple copies of `.itch.toml` for each OS. This also makes it difficult if you want to distribute a single ZIP that includes versions for multiple OSes.

Instead, I propose something like this:

    [[actions]]
    os = "windows"
    name = "play"
    path = "FooBar.exe"

    [[actions]]
    os = "linux"
    name = "play"
    path = "FooBar.x86_64"

Alternatively, perhaps something like this:

    [[actions.windows]]
    name = "play"
    path = "FooBar.exe"

    [[actions.linux]]
    name = "play"
    path = "FooBar.x86_64"

On Windows, the Linux actions would be simply ignored, as would any Mac actions, etc.

**Comment by fasterthanlime** [comment]
@aaronfranke out of curiosity, does your app require actions besides "play" ?

because if it doesn't, you don't need a manifest at all.

(I'll comment on the actual feature request depending on the response to this)

**Comment by aaronfranke** [comment]
It does. And, I used a Unity example to be generic, but the app I'm thinking of has the same executable per-OS, just launched different ways (it's built with Mono, so it's an exe on Linux, just with `mono game.exe`)

**Comment by aaronfranke** [comment]
Related wiki page: https://itch.io/docs/itch/integrating/quickstart.html

> If you are also distributing a level editor, etc., you really should ship an app manifest to let your players choose.

Which is immediately followed by: 

> The app can tell the difference between Linux, Mac OS, and Windows executables — which allows you to distribute all three in a single archive. 

Without single app manifest files that work on multiple platforms, _it is currently impossible to do both of these at once_. This is on top of the already stated fact that for games that ship in multiple archives, one for each platform, it's annoying to have a separate manifest for each platform.

**Comment by aaronfranke** [comment]
Good work, thanks for https://github.com/itchio/itch/issues/1642! I'll close this issue once the fix arrives downstream to the [build](https://itch.io/app).

Don't forget about the [documentation](https://github.com/itchio/itch/blob/master/docs/integrating/manifest.md)! Also, to improve readability, I would like to suggest moving the API key stuff to another page (and linking to it on the Manifests page). Not everyone shipping a manifest will need API keys, and shorter documentation pages are easier to read and scroll through. 

For those who do wish to use API keys, you can include more information if there is a separate API key page. After reading it, I can't really tell what scoping is, how to use it, or why it matters.  Furthermore, examples of Unity game integration would be nice.

**Comment by fasterthanlime** [comment]
Thanks for the friendly reminders @aaronfranke :) I'm not forgetting about it, but I'm in non-master-branch land again, porting even more stuff over to butler (all the login, search, session & local database stuff).

**Comment by fasterthanlime** [comment]
Eyy, itch v25 shipped! And it does implement all that.
