### ISSUE TITLE
Sandbox doesn't work if the default install folder was changed 🐧 Issue v23.6.0

### ISSUE THREAD

**Issue by WildCoder** [itchio/itch#1601]
Dear itch app team,

I changed the default install folder to a mounted partition where I have more space than my home partition. Everything works fine unless I enable the Itch.io sandbox flag. The chroot fails and the game won't launch.

Thanks for the good work!

**Comment by aaronfranke** [comment]
Have you checked the permissions on the mounted partition?

**Comment by WildCoder** [comment]
My user has rwx on the apps folder and below, group has rx.
Does the sandbox require any other permission?

**Comment by fasterthanlime** [comment]
This is probably an issue/limitation of firejail, and it may have been fixed since, the version the itch app ships is a bit oudated. Looking at it is in our roadmap, but not for right now!

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/1150
