### ISSUE TITLE
🏁 Issue v23.6.0

### ISSUE THREAD

**Issue by RabidGuy** [itchio/itch#1603]
Dear itch app team, I am unable to uninstall https://00000000.itch.io/0000000-00-00000. I'm not sure what this game is or why the uninstall button fails.

**Comment by fasterthanlime** [comment]
It's a harmless game that contains hidden messages for you to find.

I'm sorry about issues with uninstalling it, the main issue is that it seems to create a directory with an empty name when installing it :(

That issue will no longer exist in future versions of the app, but int he meantime I'd recommend opening the game's install directory (right click on the game's tab -> "Show local files") and removing it.

The next version of the app will also have an option to remove it from the "installed" listing even if it wasn't able to uninstall properly.

**Comment by fasterthanlime** [comment]
Looks like that game is no longer available.
