### ISSUE TITLE
Unable to unsubscribe from Itch.io digest

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1610]
I'm not able to unsubscribe through the Itch.io client.

Sidenote : There's a misspell in the unsubscribe message. It says "X is no longer *subscribd*. Sorry to see you go"

**Comment by fasterthanlime** [comment]
I'm not able to reproduce - the unsubscribe link works fine for me on v23.6.1.

What happens for you when you click Unsubscribe in the client?

**Comment by ghost** [comment]
I'm on v23.6.0 (waiting for distribution to give me the update)

I click on it, I click unsubscribe, go back and it still says I'm subscribed. 

I can go on in this loop indefinitely.

**Comment by leafo** [comment]
Can you send me a link to your profile page if possible so I can check your account. If you don't want to share it publicly you can email support@itch.io

**Comment by leafo** [comment]
It looks like reloading the page with a GET request will trigger you to resubscribe, so if you unsubscribe, then reload the page you'll get subscribed again. I'd say this is a bug. Is this what you're experiencing?

(I fixed the typo btw, thanks)

**Comment by leafo** [comment]
I updated the subscribe/unsubscribe page to no longer change status on GET request. Could you try again to see if that fixed the issue for you?

**Comment by ghost** [comment]
Your fix worked! Thanks @leafo
