### ISSUE TITLE
proxy settings timeout

### ISSUE THREAD

**Issue by Mart100** [itchio/itch#1611]
So i just downloaded itch. There was nothing wrong with the download. But when I try to open itch. It does nothing. I tried deleting all itch files and redownloading it again without success. I found this error under Roaming/itch/logs/itch.txt : 
`
[2018-01-22 @ 18:13:49.481] [preboot] Could not detect proxy settings: proxy resolution timed out
`
Im using Windows 10. And im not using a proxy or vpn

**Comment by fasterthanlime** [comment]
The `proxy resolution timed out` message is harmless (I get it too, because I'm not using a proxy).

Could you expand on "it does nothing" - is there a window opening? Does it show all blank, or is it dark gray? Does it show an icon in the tray area? (you might need to expand it, windows hides some by default).

Also, please attach your full itch app log (the file you were looking at).

**Comment by Mart100** [comment]
Full log:

[2018-01-24 @ 12:19:29.340] [itch] itch 23.6.0 on electron 1.7.9
[2018-01-24 @ 12:19:29.840] [xdg-mime] non-linux platform, skipping xdg-mime
[2018-01-24 @ 12:19:29.841] [preboot] Set up certificate error handler
[2018-01-24 @ 12:19:29.852] [preboot] No proxy detected
[2018-01-24 @ 12:19:29.856] [locales] Waiting a bit before downloading en locale...
[2018-01-24 @ 12:19:29.867] [reactors/setup] setup starting

And sometimes (not all the times i try to start it). I get a windows popup:
`the instructions at 0x0000000074E72AB6 directs to the memory at 0x00000000007C7C4000. The memory can not be written. Click OK if you want to close the application`
I translated this on my own. Becouse my windows in in another language so it might be a bit off.
It gives a loading mouse thing. But nothing opens at all.
I took a look in task manager. And when i open it. It stays open for about 4sec. than automaticly closes.
I surfed on the internet. and saw that popup might have something to do becouse of a lack of RAM. but I got 16gb so I dont think that is the case.
I have never seen this issue before on my pc.

**Comment by fasterthanlime** [comment]
Then I'm out of ideas :(

I'd recommend trying itch v23.6.1 (it ships with a newer electron) - and then following generic advice for that particular error message, for example: https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/the-memory-could-not-be-written/21e2d589-04d7-42bd-9836-d089067edbb2?auth=1

**Comment by Mart100** [comment]
hmm. Thanks for the help. Is there a way i can install itch on my other drive?. That whould probaly fix it

**Comment by fasterthanlime** [comment]
Unfortunately there's no way to install the app on another drive (games it install, yes, but not the app itself) at the moment. Sorry :(

Have you tried following the instructions? `sfc /scannow` in particular?
