### ISSUE TITLE
Embedded Youtube video play causes newly opened HTTP content not to render 🐧 Issue v23.6.1

### ISSUE THREAD

**Issue by CloudyProton** [itchio/itch#1616]
On Debian 9.3, pages which are accessed through HTTPS show only a white screen. This also happened on v23.6.0 and upgrading to 23.6.1 fixed it temporarily but the issue has resurfaced.

![screenshot from 2018-01-23 20-43-56](https://user-images.githubusercontent.com/34248863/35310437-60470832-007f-11e8-9386-fcc4b7398a1b.png)

Library and Collections pages are unaffected. Restarting restores page rendering temporarily (will update this issue if I discover what is causing it).

**Already have an update:** _It seems that playing an embedded Youtube video on any store page will trigger this condition._

**Comment by fasterthanlime** [comment]
Thanks for the report & the helpful update!

Can you post the part of the app log (`~/.itch/logs/itch.txt.0`) where it shows your computer's specs? Mine (on windows) looks like this:

```
[2018-01-23 @ 13:06:23.992] [diego] diego here, looking around
Caption                   OSArchitecture  Version     
Microsoft Windows 10 Pro  64-bit          10.0.15063  

Caption                               MaxClockSpeed  Name                                             
Intel64 Family 6 Model 37 Stepping 5  3077           Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz  

Name                         
NVIDIA GeForce GTX 1060 3GB  

diego out
```

Also:

  * Whether you're using Xorg or Wayland
  * Which graphics driver is active

You could also try starting itch from the command-line, after having run `export ELECTRON_ENABLE_LOGGING=true` and look out for lines like this in the output:

```
[792:0124/112442.668:INFO:CONSOLE(1)] "hi", source:  (1)
```

**Comment by fasterthanlime** [comment]
I'm not able to reproduce on elementaryOS (debian-based), with itch v23.6.1 - it plays just fine for me:

![youtube-embed](https://user-images.githubusercontent.com/7998310/35330588-584bbf9e-0104-11e8-8777-2e3e31b7dbe2.png)

**Comment by quyse** [comment]
Looks similar to #809.

**Comment by fasterthanlime** [comment]
I definitely think it's an #809 duplicate.

**Comment by CloudyProton** [comment]
The same issue is also triggered by viewing the purchase window which also renders all white. The only way for me to pay for a game is through a full web browser.
