### ISSUE TITLE
bad...

### ISSUE THREAD

**Issue by Furryapple** [itchio/itch#1641]
So Long waiting.... want fix faster loading!!!

**Comment by fasterthanlime** [comment]
Hi there!

Mind describing in some more details what you're experiencing?

In particular:

  * On which platform: Windos, macOS or Linux?
  * Which version of the app: v23.6.1 (the latest) or something else?
  * What is slow in particular:
    * Is it downloading the app's installer?
    * Is it the app's startup?
    * Is it the app installing dependencies? ("Installing butler", etc.)
    * Is it the web browsing inside the app?
    * Is it installing games?
    * Is it launching games?
    * Is a particular game slow?
  * Which country are you using the app from? (this could explain download speeds)

Please give as many details as possible - the more precise a report is, the better chance it has to lead to a resolution. Thanks! 🌟
