### ISSUE TITLE
Support for Debian 7 (wheezy)

### ISSUE THREAD

**Issue by UnarmedLad** [itchio/itch#1651]
While following [this guide](https://itch.io/docs/itch/installing/linux/ubuntu-and-debian.html) to install itch on Debian 7, after running `sudo apt-get install itch`, I get the following error message:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  itch : Depends: libpango-1.0-0 (>= 1.14.0) but it is not installable
>         Depends: libpangocairo-1.0-0 (>= 1.14.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.

And indeed, packages `libpango-1.0-0` and `libpangocairo-1.0-0` are not available in the standard wheezy repository. Does this mean that Debian 7 is currently not supported?

**Comment by fasterthanlime** [comment]
> Does this mean that Debian 7 is currently not supported?

It appears so, yep.

Looking at the various Debian releases, it appears Debian 7 is an LTS until May 2018 - I'm not sure we have the resources to support such an old release (the current stable is Debian 9.2)

**Comment by fasterthanlime** [comment]
I'm going to close this but I'm still curious if itch v25 runs on Debian 7 - https://itch.io/app

It's not a .deb package anymore, it has a setup program (our own - it's not that bad, I promise). You'll need GTK3 and what chromium needs (mostly X libraries).
