### ISSUE TITLE
Logging out and in again with a different account failed

### ISSUE THREAD

**Issue by elisee** [itchio/itch#166]
Hey! I tried switching from my own `elisee` account to the `sparklinlabs` account in the app. Logging out seemed to work fine, but I got stuck on "Contacting dovecote" with the rotating heart while logging in again with the `sparklinlabs` account. (I'm not sure if this was a logic bug in the app or somehow a network failure.)

I got a few errors in the devtools which might help:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.warning @ C:\Users\elisee\AppData\Local\itch\app-0.10.1\resources\app.asar\node_modules\react\node_modules\fbjs\lib\warning.js:45
C:\Users\elisee\AppData\Local\itch\app-0.10.1\resources\app.asar\node_modules\mori\mori.js:217 Uncaught Error: No item 0 in vector of length 0
28C:\Users\elisee\AppData\Local\itch\app-0.10.1\resources\app.asar\node_modules\react\lib\ReactCompositeComponent.js:559 Uncaught TypeError: Cannot read property '_currentElement' of null
C:\Users\elisee\AppData\Local\itch\app-0.10.1\resources\app.asar\app\stores\app-store.js:24 checking for self updates...
44C:\Users\elisee\AppData\Local\itch\app-0.10.1\resources\app.asar\node_modules\react\lib\ReactCompositeComponent.js:559 Uncaught TypeError: Cannot read property '_currentElement' of null
C:\Users\elisee\AppData\Local\itch\app-0.10.1\resources\app.asar\node_modules\react\lib\SimpleEventPlugin.js:580 Uncaught TypeError: Cannot read property 'remove' of undefined
```

Closing the app and reopening it presented me with the login screen and I was able to log into the `sparklinlabs` account.

Just tried reproducing the bug and it failed again once out of like 5 attempts.

**Comment by fasterthanlime** [comment]
Interesting, should be pretty easy to prevent

**Comment by fasterthanlime** [comment]
Where lots of things happening at the time you switched accounts ?

**Comment by fasterthanlime** [comment]
@elisee also, was that 0.10.1 ?

**Comment by elisee** [comment]
Yes, 0.10.1. No game downloads were running. Can't exclude that some account data wasn't still downloading in the background but I think it had been a little while since I opened the app.

**Comment by fasterthanlime** [comment]
@elisee since 0.10.0 when switching back to the app, it refreshes your collections + owned games, so that might be it.

I fully understand why steam's "Change account" functionality reboots the app, it's much easier to do. But I haven't lost all hope that we can make change account work without that.

**Comment by fasterthanlime** [comment]
@elisee please re-open if you can reproduce — there might still be some of that in the output, but it shouldn't crash the app anymore

**Comment by elisee** [comment]
Thanks, can't seem to reproduce it!
