### ISSUE TITLE
🏁 Issue v23.6.1

### ISSUE THREAD

**Issue by Kaiyumie** [itchio/itch#1690]
Dear itch app team, 
Whenever I attempt to download a game from your website, nothing happens. The only pop-up I get is a "Thank you for downloading" screen. Nothing shows up on the bottom of my screen indicating that the download process is taking place. I've checked my browser's download history and none of the games that I wish to download show up.

As for installing the Itch.io app on my desktop, the same games I want to download fail, for when downloading, it claims that a remote file cannot be found.

**Comment by fasterthanlime** [comment]
Hi,

Can you link to the games you're trying to download? Thanks!

**Comment by Kaiyumie** [comment]
Here are the links, as you wished
https://tokimekiwaku.itch.io/liar-liar
https://tokimekiwaku.itch.io/liar-liar-2
https://yndr4hope.itch.io/freetime-event-theatrical-release
https://yndr4hope.itch.io/freetime-event-poolside-edition
https://adamgryu.itch.io/tomato-town
https://flamebait.itch.io/epidemic-plagues-and-prayers
https://pddev.itch.io/urbex
https://ycjy.itch.io/no-transmission
https://raft.itch.io/raft
https://jamiesime.itch.io/lonely-things
https://tokimekiwaku.itch.io/blood-idol-wakabayashi

**Comment by fasterthanlime** [comment]
Hey, sorry for the late response.

I tried a few from the list and they seem to download and install fine.

1. Can you send a screenshot of what you see exactly when the "remote file cannot be found" message appears?
2. From which country are you downloading?
