### ISSUE TITLE
Add OpenAL prereqs

### ISSUE THREAD

**Issue by ltjax** [itchio/itch#1701]
I want to switch my game from an installer to using a butler-friendly folder, but I currently have two prereqs that my installer takes care of, the vs2017 runtime and OpenAL. The first one is already covered.

According to https://gamedev.stackexchange.com/questions/49121/deploying-monogame-without-openal-or-installer, a silent installer really is the only good way to deploy it.

On a side question: Can I use the prereqs section to install from an installer that I bundle with my game? The docs do not make that clear..

**Comment by fasterthanlime** [comment]
Shipping the OpenAL DLLs installed by the installer is indeed not going to work, but shipping OpenALSoft should work for everyone: http://kcat.strangesoft.net/openal.html - can you give it a shot?

> On a side question: Can I use the prereqs section to install from an installer that I bundle with my game? The docs do not make that clear..

Nope, you can only specify from the pre-approved list. The app doesn't just run anything with Administrator privileges ;)

**Comment by ltjax** [comment]
Yea, that was my fallback plan, with the downside from the OAL Soft readme: "Just be aware this will prevent other system-installed OpenAL implementations from working."
But I'm not sure how relevant that is anymore anyways, and people who want to get that working will probably be able to just tinker with the dlls

**Comment by fasterthanlime** [comment]
@ltjax I just added the OpenAL redist as `openal-1.1` (it's not listed in the docs yet) - can you give it a shot?

**Comment by ltjax** [comment]
Thanks! I'll report back after I tested it..

**Comment by ltjax** [comment]
@fasterthanlime Build pushed and works. Thank you!

I was wondering tho - is there a good way to test this without pushing the build / installing on a fresh machine? This is kind of testing in production...

**Comment by fasterthanlime** [comment]
> This is kind of testing in production...

The best kind of testing! :shipit: ... just kidding :)

You can run `butler --elevate test-prereqs openal-1.1` to try it the prereqs on your machine - but not the complete launch process.

You can also (and I recommend it) have a hidden page ("Private" or "Restricted" visibility) that you push to and test this version before you push it out to everyone.

---

Now that the big rewrite/cleanup is almost done for itch v25, I'm thinking of adding developer tools to itch that would let you launch any folder as if it were an installed app, so you can see exactly what would happen if it were installed.

---

As for replicating the "fresh machine" state, if you have a good idea, I'm open to it. We do a bunch of automated testing on a bunch of things, but automatically setting up Windows VMs, going through UAC prompts etc., is something we haven't quite cracked yet.

**Comment by fasterthanlime** [comment]
Closing as OpenAL has been a prereq for a while.
