### ISSUE TITLE
Continuos cpu and gpu usage while itch.io is running in the backgound.

### ISSUE THREAD

**Issue by luckcolors** [itchio/itch#1702]
Itch.io version: v23.4.2
System os: Windows 10 Pro 64 Bit
Similar issue: #685 (not sure if they meant minimized in the tray or just having the window minimized, so i opned this new issue)

I wanted to report current itch.io system resource usages in my system.
![capture](https://user-images.githubusercontent.com/3228598/36076994-92d2c004-0f64-11e8-8782-18952e5037ec.PNG)
The cpu usage of the first itch.io process sometime spikes up to 7%.
While gpu always sits around the 1-2% value.

Let me know if this is actually an issue (i think it is, if only in the tray icon itch.io should definetely not use the gpu)
Interestingly opening itch.io UI and then closing it Removes the GPU usage completely and the cpu usages get to 0%, with the occasional 1% usage.

I'll follow up on this a couple of hours to report if the sitiation remains the same.
I hope this info helps you guys! :)

**Comment by luckcolors** [comment]
Itch.io hasn't srated to use cpu again.
This means only happens after i start my machine.

**Comment by fasterthanlime** [comment]
itch v25 is out, so I was curious to see if this was still an issue.

I'm seeing 0.1%-0.2% spikes, but it's otherwise pretty stable:

![v25-cpu](https://user-images.githubusercontent.com/7998310/45500832-e675a780-b77f-11e8-8ad2-8db1f62bafcd.gif)

You can download itch v25 at https://itch.io/app
