### ISSUE TITLE
Proper mutex between game install & game running

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1714]

**Comment by fasterthanlime** [comment]
One way to do it would be to have lockfiles in `.itch/` containing the PID of the game (or wrapper). It seems pretty straightforward to do now in butlerd.

**Comment by fasterthanlime** [comment]
Another question pops up: in downloads_drive, what do we do when we have a download queued for a game that is currently running (we know because we just checked `.itch/pid.json`).

I vote for an error constant that deprioritizes a download. However, this may lead to a situation where:

  * An update for game `FooBar` is the only queued download
  * `FooBar` is running
  * downloads_drive attempts to update `FooBar` every second or so

This might not be a big deal, but it might add significant noise to the log. It's not that hard to "wait till the PID file disappears (or the corresponding process exits)", but how would that interact with other downloads being queued

**Comment by retropipes** [comment]
This is almost certainly related to other database locking issues. Fixing those may very well fix this one.

**Comment by fasterthanlime** [comment]
So, in v23, the electron app was in charge of queuing downloads *and* performing them. Whereas in v25, we're more in a "distributed" scenario, where multiple processes cooperate to achieve something.

So right now, v25 will refuse to queue a download if a game is running (and the relevant menu entries are grayed out) - but if somehow a download is queued and a game starts running, then nothing prevents both of those occuring. This could be achieved by clicking really fast before the UI updates.

So it's not really an implementation bug, more like a design flaw that needs to be addressed.

But yeah, I think launching a game or starting a reinstall/heal/patch operation on a game should acquire a mutex and the others should wait until it's done.
