### ISSUE TITLE
🏁 Issue v23.6.1: Dragging and dropping a file onto the library breaks the app

### ISSUE THREAD

**Issue by oznogon** [itchio/itch#1722]
## Steps to reproduce

1. Open the itch.io app on Windows 10.
2. Drag a file onto the Library.

## Expected behavior

Nothing happens.

## Observed behavior

The file is opened inside the itch.io app. There is no back button or keyboard shortcut. Closing the window and reopening it has no effect. To continue using the app, you must quit it from the system tray and restart it.

## Screenshots

![capture4](https://user-images.githubusercontent.com/19192104/36637574-a9e906fc-1993-11e8-9f65-16ae675b30fe.PNG)
![capture5](https://user-images.githubusercontent.com/19192104/36637575-aa074ff4-1993-11e8-94d9-049699305a7b.PNG)

## Why would you do this

Dragging a file while waiting for the app to launch, then dropping it a split second after the app has launched and taken over the screen.

**Comment by fasterthanlime** [comment]
Thanks for the report! The `Why would you do this` section made me chuckle.

We actually found this bug while testing v25 (the next major version of the app) and it has been fixed in master.

**Comment by fasterthanlime** [comment]
itch v25 is drag-proof!

![dragging](https://user-images.githubusercontent.com/7998310/45500404-df01ce80-b77e-11e8-8c27-f8c808a490e5.gif)

and it's out now: https://itch.io/app
