### ISSUE TITLE
🏁 Issue v23.6.1

### ISSUE THREAD

**Issue by LoliWaifuDFC** [itchio/itch#1723]
Dear itch app team, 

I keep getting this error whenever i try to download something.

truncate (folder where my games go) an attempt was made to move the file pointer before the beginning of the file.  

I have tried changing where the games go still doesn't work.  
![helppp](https://user-images.githubusercontent.com/36870086/36705861-455010ca-1b35-11e8-93ef-3ca98e041f6d.png)

Any advice or help will be appreciated. I will try uninstalling and reinstalling.  Thank you. Hope for a swift reply!

**Comment by LoliWaifuDFC** [comment]
ok so its just this game? i can install others now just fine?

**Comment by fasterthanlime** [comment]
Ya, sure enough, the uploads for Doki Doki! RainClouds are bit.ly links.

I'd recommend leaving a comment on the page telling them to upload directly to itch.io. If it's a large game, they can use https://itch.io/docs/butler/ 👍
