### ISSUE TITLE
🏁 Feedback v23.6.1

### ISSUE THREAD

**Issue by muhammadabdulrahim** [itchio/itch#1724]
Event log:

```
Error: ENOSPC: no space left on device, write
    at Object.<anonymous> (<USERPATH>\AppData\Local\itch\app-23.6.1\resources\app.asar\appsrc\util\sf.ts:135:21)
    at Generator.next (<anonymous>)
    at fulfilled (<USERPATH>\AppData\Local\itch\app-23.6.1\resources\app.asar\app\util\sf.js:4:58)
    at <anonymous>
```

Crashed while trying to install [You Played Yourself](https://iseeicy.itch.io/you-played-yourself) v1.2. Replaced my actual user path with `<USERPATH>` in the log up above.

**Comment by fasterthanlime** [comment]
You're out of disk space :)

Might want to free some up, look in %APPDATA%\itch\downloads for temporary files you can delete.

**Comment by muhammadabdulrahim** [comment]
Gotcha. Is there an easy way to swap which drive itch is installed on without having to reinstall everything? I think I accidentally installed on my SSD when I meant to install on the HDD. If not I can just reinstall everything. Thanks for the help!
