### ISSUE TITLE
🏁 Issue v23.6.1

### ISSUE THREAD

**Issue by PureAsbestos** [itchio/itch#1725]
Dear itch app team, 
when first setting up sandbox mode on windows, if you click the 'Learn more' button, it takes you to
https://itch.io/docs/itch/sandbox/windows.html#one-time-setup
instead of
https://itch.io/docs/itch/using/sandbox/windows.html#one-time-setup

**Comment by fasterthanlime** [comment]
This has been fixed upstream in https://github.com/itchio/itch/commit/48163120d144dbc4a8fb33a0ca56ea14027a8839 - the fix will be included in the next major release.
