### ISSUE TITLE
Implement client side decoration on Linux

### ISSUE THREAD

**Issue by ma1onso** [itchio/itch#1733]
Help to initiative: https://wiki.gnome.org/Initiatives/CSD

Using elementary os (ubuntu 16.04)

**Comment by fasterthanlime** [comment]
From that page:

> We should first work with upstream Electron to add GNOME-style CSD support at a platform level. Once that is in place, we can start approaching individual app developers.

The current bleeding-edge version of the app is borderless, which isn't quite CSD but it doesn't look so out of place:

![image](https://user-images.githubusercontent.com/7998310/37220227-3f1a76f2-23c6-11e8-8999-0edd884a822a.png)

**Comment by ma1onso** [comment]
Thanks @fasterthanlime waiting for next release. Any chance for test bleeding-edge version?

**Comment by fasterthanlime** [comment]
> Thanks @fasterthanlime waiting for next release. Any chance for test bleeding-edge version?

Usually you could just clone https://github.com/itchio/itch at master and run `npm i` then `npm start` but I wouldn't recommend it this week, because there's been a lot of things moving around, it'll stabilize soon :)

**Comment by fasterthanlime** [comment]
itch v25 is out! It's frameless, nobody's complained about client-side decorations yet.

You can get it from https://itch.io/app :shipit:
