### ISSUE TITLE
🏁 Issue v23.6.1

### ISSUE THREAD

**Issue by amymaitre** [itchio/itch#1736]
Dear itch app team, I just purchased Lieve Oma and downloaded itchio to my desktop. For starters, when I first opened the game the resolution was very low to the point that the text was unreadable and looked like scribbles. I already knew that something was wrong so I closed the game and reopened it. Now it doesn't even open full screen. It opens to this tiny tiny window where I can't even say that I can play the game at that size. I can't resize or enlarge the window. This is really frustrating just because I just purchased and downloaded this game and app to only have an issue as soon as I begin working with them. Could someone please resolve my issue, thank you.

**Comment by fasterthanlime** [comment]
I remember Lieve Oma starting with a very small resolution when I tried it, I'm pretty sure there was an options screen where you could switch to a larger resolution - although I think I remember the controls for the options screen weren't super intuitive either.

I see you've opened a ticket for a refund though, so I'll be closing this issue.
