### ISSUE TITLE
[win32] Broken game for v0.10.2 (disconnect?)

### ISSUE THREAD

**Issue by wec22** [itchio/itch#174]
Game [Bellular Hexatosis](http://neotenomie.itch.io/bellular-hexatosis) is broken for me.

Here's the [debug log](https://gist.github.com/98737935497aabdb2936).

**Comment by fritzy** [comment]
Have you tried reinstalling? The error looks like it was disconnected. I believe the newest version fixes issues with dropping connections like happened for this install.

**Comment by fasterthanlime** [comment]
> the newest version

apparently this is using v0.10.2 — but it does sound like it was disconnected.

@wec22 have you tried installing the same game again ?

**Comment by fasterthanlime** [comment]
Please re-open if you can reproduce
