### ISSUE TITLE
🏁 v23.6.1 Bitdefender still randomly quarantines files

### ISSUE THREAD

**Issue by Eriwhan** [itchio/itch#1748]
Event log:

```
Error: EPERM: operation not permitted, open 'C:\Users\HP\AppData\Roaming\itch\logs\itch.txt'
```

**Comment by fasterthanlime** [comment]
Well, that's a new one.

What kind of Antivirus are you running?

**Comment by Eriwhan** [comment]
I'm running on bitdefender. This error happen each time I close my laptop and it's running fine when I reinstall the app...It happened like 2-3 times..

**Comment by fasterthanlime** [comment]
Then I'm not really surprised, BitDefender really dislikes our app, from my tests: https://github.com/itchio/itch/issues/1717#issue-297824693

You can add a bunch of folders to the whitelist, see: https://itch.io/docs/itch/installing/windows.html
