### ISSUE TITLE
[darwin] Broken game for v0.10.2

### ISSUE THREAD

**Issue by JetLennit** [itchio/itch#175]
Game [Aseprite](http://dacap.itch.io/aseprite) is broken for me.

Here's the [debug log](https://gist.github.com/fab2bac063bf2bd338e9).

Note: Technically not a game... but a tool. Still would love it to be fixed!

**Comment by fritzy** [comment]
this is related to #19. Once there is DMG support or Aseprite includes a different installer, this issue will be resolved.

**Comment by fasterthanlime** [comment]
Absolutely — closing in favor of #19

**Comment by fasterthanlime** [comment]
@JetLennit itch 0.12.0 is out with DMG support, Aseprite works great now :)

You can upgrade with the 'Help -> Check for Update' menu item.
