### ISSUE TITLE
🐧 Issue v23.6.1

### ISSUE THREAD

**Issue by ibrokemypie** [itchio/itch#1757]
Dear itch app team, 
When running Ancient Warfare 2 with the sandbox enabled, launching fails with 
```
An error occurred while launching Ancient Warfare 2

Error: error(s) while installing sandbox: Error: pkexec failed with code 127, stderr = Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address
```

**Comment by fasterthanlime** [comment]
Interesting! Which linux distribution is that?

**Comment by ibrokemypie** [comment]
Arch linux, package installed from the AUR

**Comment by fasterthanlime** [comment]
Which desktop environment? pkexec should work fine anywhere, but [one never knows](https://forums.virtualbox.org/viewtopic.php?f=7&t=74456)

**Comment by ibrokemypie** [comment]
i3-gaps as the WM, no DE

**Comment by fasterthanlime** [comment]
Ah, that's it then. You're going to need an authentication agent running.

This answer seems like it has everything you need: https://superuser.com/a/389408

---

Reproducing the answer here in case it goes down:

Elevation uses several components:

-   the program must be running in a **ConsoleKit** or **systemd-logind session** -- ideally, *all* of your X11 programs should be in the same session.

    If your distribution uses *systemd*, run `loginctl show-session "$XDG_SESSION_ID"` and look for "State=active".

    Otherwise, run `ck-list-sessions` and verify that it shows your X11 session as both "local = TRUE" and "active = TRUE".

-   the session must have a **PolicyKit agent** -- this is the piece of software that displays elevation prompts.

    Run `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1` and see if it helps.

To test elevation, you can use `pkexec /bin/sh` or `pkaction`
