### ISSUE TITLE
🏁 Feedback v23.6.1 Open PDF-only files inside the client

### ISSUE THREAD

**Issue by sprite-1** [itchio/itch#1760]
Dear itch app team, 

Please make it so that when you download a project that only contains a PDF file, instead of opening the folder by default, open the PDF on a new tab in the client. Since it's pretty much just running a version of Chrome, I'm sure it can load it just fine. It also reduces the steps needed to view the content.

**Comment by fasterthanlime** [comment]
It doesn't look like Electron ships with Chrome's pdf viewer (it's an addon afaict).

There are solutions to display PDFs within Electron apps, but they use pdf.js, which is something else entirely: https://github.com/gerhardberger/electron-pdf-window

(Opening a pdf URL in the app just prompts for a download right now).
