### ISSUE TITLE
mega.co.nz downloads are not supported (and will never be)

### ISSUE THREAD

**Issue by Xehala23** [itchio/itch#1763]
Dear itch app team, 
i noticed that some games will not installl if you press '' install ''   because the files are redirected to Mega.nz

**Comment by fasterthanlime** [comment]
Yep, mega.co.nz will never be supported.

We're planning (well, I'm planning) on deprecating external uploads, but in the meantime, you'll just have to go through the website for those, or lobby for the game's developers to [do things right](https://itch.io/docs/itch/integrating/quickstart.html) instead :)

**Comment by Xehala23** [comment]
awe well that sucks x3x
