### ISSUE TITLE
🏁 Suggestion v23.6.1

### ISSUE THREAD

**Issue by Radaxsly** [itchio/itch#1765]
Dear itch app team, 
Im not sure if there is a way, could not find it but I would like to know the game size before I download. Limited internet data problems.

Regards
Thorne

**Comment by fasterthanlime** [comment]
Hey Thorne,

That's one of the features planned for the next app version :) Thanks for the feedback!

**Comment by fasterthanlime** [comment]
Hey, itch v25 is out, and it has that feature:

![image](https://user-images.githubusercontent.com/7998310/45492923-d1901880-b76d-11e8-8f6b-da7f60dfe785.png)

You can download it from https://itch.io/app
