### ISSUE TITLE
Revoked download key should(?) remove game from user's library in the desktop app

### ISSUE THREAD

**Issue by BernsteinA** [itchio/itch#1769]
Currently:
- The game remains visible in my library
- Clicking on the game takes me to the "A password is required to view this page" screen
- Clicking Launch runs the game
- Check for update causes error "Could not check for updates: [Object object]"
- Verify integrity appears to function.
- Re-install appears to function.

**Comment by fasterthanlime** [comment]
itch v25 is released, you can get it from https://itch.io/app

---

Here's what should happen in v25:

  * The game should disappear from your "Owned items"
  * However, if it's installed it should remain installed
  * Update checks should gracefully fail (it just won't find any)
  * Re-install should fail (you don't have permission to download it again - v23 kept a copy of the archive around so "re-install" didn't download)
  * Verify integrity should fail (you don't have permission to download the signature either)
  * It won't uninstall it for you though.

Re the last point: if you weren't using the app, you would've been able to download the game and keep it on your disk. There's no point in us automatically deleting the game from disk, it doesn't add any security - the cat's out of the bag!
