### ISSUE TITLE
Custom prerequisites for app manifest

### ISSUE THREAD

**Issue by hach-que** [itchio/itch#1773]
We ship some prerequisites with our tool that need to run the first time the tool is run after being updated or installed from the itch app. Since the prereqs need admin elevation, we don't want to show a UAC prompt on every run.

What's the best way to handle this?

**Comment by fasterthanlime** [comment]
Hey June!

So, there's no plan to support "custom prerequisites" in the app, the policy is either:

  * They're generally useful & stable and should be added to our prereqs repos
  * Or they aren't

The problem with allowing custom prereqs is that it would allow malware authors to use itch's established goodwill to trick users into allowing installation of potentially harmful software.

In your case, I'd:

  * Have "check if prereqs are there" logic that doesn't require administrator privileges to run
    * For example, reading registry keys can often be done with basic user privileges
  * If they're not there, launch a copy of your process elevated (see [this SO thread](https://stackoverflow.com/questions/11586139/how-to-run-application-which-requires-admin-rights-from-one-that-doesnt-have-th)) to do just the prereqs installation you need, then let that copy exit and resume business as usual

That way, the UAC prompt would only pop up when prereqs actually need to be installed.

(Even if itch did allow custom prereqs btw, it would still pop a UAC prompt - there's no always-running itch service with administrator privileges, we try to keep the attack surface small)

**Comment by hach-que** [comment]
Yeah, we wouldn't expect it to *not* show a UAC prompt. I'm not sure if the current prereqs system skips UAC, but that's not something we'd want.

In our case, the prereqs are the prereqs installer for Unreal Engine 4. This isn't something itch.io can distribute generally (because the package is covered by the UE4 license agreement), but also isn't something we can easily check "has it changed since last run" since we don't control what's in it. That's why we kind of wanted an easy way to just tell the itch app to run the exe only the first time that the app has been installed / updated.

For now we're just handling it with a secondary launch option.

**Comment by fasterthanlime** [comment]
> In our case, the prereqs are the prereqs installer for Unreal Engine 4. This isn't something itch.io can distribute generally (because the package is covered by the UE4 license agreement), but also isn't something we can easily check "has it changed since last run" since we don't control what's in it. That's why we kind of wanted an easy way to just tell the itch app to run the exe only the first time that the app has been installed / updated.

Actually, the app takes care of UE4 prereqs already!

v23 is a bit careless (it just runs files that look like UE4 prereqs, then "calls it done" by writing a marker somewhere)

v25 actually checks that the Authenticode signature is valid, that it's the right published, and stores an sha256 of the file so it can run it again if it changes.
