### ISSUE TITLE
23.6.2 Isar failed with code 1 

### ISSUE THREAD

**Issue by henriiquecampos** [itchio/itch#1776]
https://github.com/itchio/itch/tree/v23.6.2 isn't opening on Solus OS Gnome x86_x64 using the tar.xz release. I get
```
Gtk-Message: 19:19:27.753: Failed to load module "canberra-gtk-module"
Mounting crash reporter
Fully mounted crash reporter
[2018-04-30 @ 19:19:28.252] [itch] itch 23.6.2 on electron 1.7.11
```
When opening from terminal

**Comment by fasterthanlime** [comment]
See https://github.com/itchio/itch/issues/1777#issuecomment-385616002 - that bug has been resolved.
