### ISSUE TITLE
[Fatal Bug] Client forces install of dependency butler and then hangs during install / "lsar failed with code 1"

### ISSUE THREAD

**Issue by bradenbest** [itchio/itch#1777]
Ever since version 23.6.2, I can't start the itch client up at all, because as soon as it starts up, it forces an install of dependency butler, which never finishes and hogs the client in the foreground. The install can't be skipped, and for some reason, it doesn't run in the background, which means you can't use the client. At all.

    [2018-04-30 @ 17:15:47.563] [reactors/self-update] Checking...
    [2018-04-30 @ 17:15:48.148] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/deb_x64/23.6.1: 200
    [2018-04-30 @ 17:16:44.842] [reactors/navigation] Not logged in, not saving tabs yet...
    [2018-04-30 @ 17:16:45.092] [reactors/fetch] Fetching the usuals
    [2018-04-30 @ 17:19:38.135] [reactors/navigation] Not logged in, not saving tabs yet...
    [2018-04-30 @ 17:19:38.387] [reactors/fetch] Fetching the usuals
    [2018-04-30 @ 17:20:38.848] [reactors/navigation] Not logged in, not saving tabs yet...
    [2018-04-30 @ 17:20:39.129] [reactors/fetch] Fetching the usuals

It's 17:35. The entire Butler repo is only 45 MiB in size

    $ du -h butler/
    ....
    45M     butler/

Should it really take 20+ effing minutes to install? No. It's clearly hanging. I've downloaded multi-gigabyte files faster than this.

By the way, the log just now updated:

    [2018-04-30 @ 17:35:08.363] [reactors/navigation] Not logged in, not saving tabs yet...
    [2018-04-30 @ 17:35:08.618] [reactors/fetch] Fetching the usuals

It's more of the same. Time is 17:38 now. Almost 25 minutes.

# Update.

The time is now 18:35. It's been 80 minutes since I launched itch and it's still "fetching the usuals". The damn thing hasn't even budged. 

Also, the only reason the log updates is because I roll my mouse over the window. *So it's literally been doing nothing for the past 80 minutes.* 

This is completely broken. Horrible update. I'm killing it now. Fuck this.

**Comment by bradenbest** [comment]
17:46, no change. That's 31 minutes.

**Comment by bradenbest** [comment]
# Update 2

After killing and restarting it, it's still hung. Oh, but this time it's a full-blown error.

    There was a problem during setup: lsar failed with code 1

**Comment by bradenbest** [comment]
Added [fatal bug] to the title to emphasize that this is a serious issue.

**Comment by bradenbest** [comment]
# Update 3

I decided to investigate what's going wrong. Going into `~/.config/itch/bin`, I found this:

    $ ls -l
    total 312
    -rwxrwxr-x 1 braden braden    127 Apr 30 19:41 butler.7z
    ...

I found this via `locate lsar`. Now, clearly there is something wrong with butler.7z. There's no way it's 127 bytes. I assumed it was truncated, but

    $ cat butler.7z
    <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>

Your server is serving crap.

**Comment by bradenbest** [comment]
# Update 4

I finally managed to fix my issue. *My* issue. I'm still leaving this issue up because this happens on a fresh install and it still renders the program unusable.

Here's how I fixed it.

1. After googling "itchio butler binary x86_64 linux", I wound up [here](https://itch.io/docs/butler/installing.html), the only website on the entire internet that has a pre-compiled binary of butler (sorry, but I'm not willing to learn how to compile a project in a language that I don't use in a repo that lacks a Makefile or anything even resembling a build system)

2. I took this binary, threw it into `itch/bin`, and `chmod +x`'d it.

3. I also `chmod +x`'d the files in itch/bin/unarchiver, and **removed** `butler.7z`, for good measure.

(NB: this fix also works on windows, minus a few operations like chmod)

Good thing I'm a fucking genius. Cause I don't think a normal user would have figured that out in a million years.

Of course, I'm being facetious about the genius thing. But that's what it feels like when I have to put my I.T. hat on every time I want to perform a basic task. Like, "shit, if it were 2012, I'd have no idea wtf to do". The fact that it took me, a programmer and sysadmin with 6 years of Linux experience, 3+ hours to solve this, is a death spell for "normal" users who *don't* spend 98% of their time in a terminal.

**Comment by webmasterjedi** [comment]
Had this issue today on Windows 10. Followed the instructions to download and install Butler here: https://itch.io/docs/butler/installing.html and overwrote the butler.exe I had. Seemed to fix the issue for me.

**Comment by hach-que** [comment]
I can also confirm I'm experiencing the issue. Downloading butler.exe manually from the link in the previous comment into `%APPDATA%\itch\bin` and restarting the itch app resolves the issue.

**Comment by bradenbest** [comment]
@hach-que @webmasterjedi Hmm, that's strange, cause I didn't have a `butler` executable at all, on neither my Linux box nor my Windows 10 VM. Only a `butler.7z` 127 bytes in size, consisting of an XML error message served by whatever server itch was talking to. The `lsar` component of `unarchiver/` was attempting to work with that file, but since it's XML junk instead of a proper 7zip archive, it fails, hence the "There was a problem during setup" message. 

I think reddit calls that software gore.

**Comment by fasterthanlime** [comment]
The bug is now fixed.

Here's what happened:

  * https://github.com/itchio/butler/commit/4e2a5b069d43392de9d3f60c01e8d04507005fa3 (22 days ago) broke part of the the `ci-build.sh` script into `ci-package.sh`
  * this was done so that butler could be deployed both to http://dl.itch.ovh/ (used by itch v23) and https://fasterthanlime.itch.io/butler (used by itch v25)
  * numerous bleeding-edge releases of butler went through CI and were deployed to both endpoints
  * however bleeding-edge releases don't update the `LATEST` file on dl.itch.ovh
  * yesterday, v13.0.0 was released
  * because `CI_VERSION` was not defined in `ci-package.sh` (a problem fixed by https://github.com/itchio/butler/commit/7dd2b52c4f80a0527d7a96460a64ed6e139c0ec4 ), the `LATEST` file was empty, resulting in v23's dependency install code to make a request to non-existent file <http://dl.itch.ovh/butler/windows-amd64//butler.7z>
  * incidentally, v23 never did check, when downloading a dependency, that it got a 200 HTTP code https://github.com/itchio/itch/blob/v23/appsrc/util/net.ts#L188-L221 - a bug that's never been relevant until now

Everything is back to normal.

**Comment by bradenbest** [comment]
@fasterthanlime Bravo on a quick response+fix! It's devs like you that restore my faith in the software development profession. My finger's mashing the 'F' key hard, if you know what I'm sayin' ( ͡° ͜ʖ ͡°)
