### ISSUE TITLE
Distinguish empty state (downloads, collections, library) from "loading" state

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1779]
After itch is launched, opening any of Library/Collections/My creations tabs at first shows an empty state for a few seconds ("Everything is filtered away", "No collections", etc) and only then displays actual non-empty list of things. Every time I see that I get confused for a second. Would be nice to show "Loading..." instead.

**Comment by fasterthanlime** [comment]
I believe v25 makes that distiction.

While it's loading, a loading indicator is displayed. When it's done loading, and there's nothing to show, it display "nothing to see here".

![image](https://user-images.githubusercontent.com/7998310/45492553-dbfde280-b76c-11e8-891e-59ca389cde1c.png)

It's not the art piece of the year, but I think it gets the job done for now!
