### ISSUE TITLE
Enable systemwide installs to share games accross users on a computer

### ISSUE THREAD

**Issue by frivoal** [itchio/itch#1781]
I have several users on my computer with different logins (I mean OS accounts, not itch accounts). The account for my daughter is set up not to have internet access, as she is too young to do that unsupervised.

I'd like to log in as me, install a few games with itch, and have them be accessible to her, without needing to give her network access or credentials to my itch account.

Ideally, when I install a game, I'd like to have the choice between installing it for the local user (as now), or in a system-wide shared location (e.g. /opt/itch/... for linux) and have the games show up in the system's menu, so that they can be found and started without itch.

**Comment by fasterthanlime** [comment]
One thing you could do is:

  * Add an install location (`/opt/itch`, why not!)
  * Install games there
  * Create shortcuts for your daughter to launch them

Install locations were a bit hard to grasp in previous versions of the app, I recommend trying out itch v25, I think it's clearer: https://itch.io/app
