### ISSUE TITLE
No compatible downloads even though there are?

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#1787]
I was testing my games with the app, and encountered one stating there are no compatible downloads:

![image](https://user-images.githubusercontent.com/15093567/39853629-2a2a4834-53d8-11e8-84b4-c00e7e6d64bf.png)

My only guess for this error would be if there weren't any builds for my OS.. but the game in question does have Windows builds and I'm on Windows 10:

![image](https://user-images.githubusercontent.com/15093567/39853707-8eeed1c2-53d8-11e8-9e26-32657bbdf50c.png)

Running itch version 26.6.3 on Windows 10.

There is no difference in how this game is packaged from my other games (except that it has a 32 bit and 64 bit Windows version, something I later dropped doing). :/

**Comment by fasterthanlime** [comment]
Has it been 27 days already!

I meant to reply to this earlier, but here goes: we don't have (for now! I've been working on it) proper "architectures" data on the server.

However, 64-bit executables won't run on 32-bit windows, for example, so the itch app still makes an effort to "guess" which upload is the right one.

Here, what's tripping itch v23 up is that the name contains both "64" (from "64bit") and "32" (from... "LD32"). So it ends up excluding the only upload.

I'm making sure v25 doesn't do the same mistake, adding it to the milestone now.

**Comment by TangentFoxy** [comment]
Thank you!

**Comment by fasterthanlime** [comment]
> Has it been 27 days already!

More like 126 days.

itch v25 is out, and it lets you pick either:

![image](https://user-images.githubusercontent.com/7998310/45499942-b3321900-b77d-11e8-9441-60a291e6bb93.png)

You can grab it from https://itch.io/app :shipit:
