### ISSUE TITLE
🏁 [Feedback] Issue v23.6.3 - itch io app is ADWARE and violates your privacy

### ISSUE THREAD

**Issue by jcdenton2k** [itchio/itch#1788]
Dear itch app team, your application keeps giving certificate errors.
I'm running Win7 SP1 x64 and I don't know why the updated certificates can't be included in the app itself.

All of them are Google-related errors such as this one:
https://i.imgur.com/XUrShgc.png

So I don't know why you even have Google Analytics or other crap running in the itch game browser.  Might make me just fork a non-adware version of it if this keeps up.

EDIT:  I traced the error to my DNS-level blocking of everything from Google Analytics somehow causing issues with your application.  **There is NO reason that anything in your application should be making calls to Google Analytics, DoubleClick, or other adware services.**  I'm uninstalling your itch io malware until you remove this trash and KEEP it out.

**Comment by fasterthanlime** [comment]
https://itch.io uses Google Analytics, and it's the default page v23 loads.

itch v25 is out, and it lets you disable the web browser (in Preferences), so you could search for and install games without it ever contacting Google servers.

You can download itch v25 from here: https://itch.io/app

Please remain civil in future exchanges.
