### ISSUE TITLE
Action required if you have a manifest with only prerequisites

### ISSUE THREAD

**Issue by LennardF1989** [itchio/itch#1801]
I added a manifest to my Windows game for the prerequisites I wanted to have installed. Upon trying to launch the game from the itch.io app, it complained the manifest contained no actions.

I had to manually add a "play" action, in order to get the game to launch again.

This is kind of counter-intuitive, because it is never explicitly mentioned in the docs, neither does `butler validate` complain about its absence.

I would expect that the itch.io client would follow its normal launching protocol, if there are no actions available, but still install the prerequisites.

**Comment by fasterthanlime** [comment]
> I would expect that the itch.io client would follow its normal launching protocol, if there are no actions available, but still install the prerequisites.

That's perfectly reasonable and is in fact how itch v25 behaves (the next major version).

Adding this issue to the project so it can be closed when it ships!

**Comment by fasterthanlime** [comment]
Hey, it shipped!

You can get itch v25 from https://itch.io/app

It should install prerequisites fine, even if you have no actions listed. Let me know if that's not working for you.
