### ISSUE TITLE
Allow users to set manual startup arguments

### ISSUE THREAD

**Issue by LennardF1989** [itchio/itch#1804]
Depending on the amount of arguments you have for a game, it's an exponentially growing list of launch options. Would be cool if the player can set his own startup arguments in the game settings.

Or, if we want to stay in a somewhat controlled environment. Add something to the manifest file, that allows the developer to register possible startup arguments, after which the user can just "toggle" one or more of them on or off. But I can imagine this becomes nasty real quick once arguments are no longer just toggles and/or become conditional :P

**Comment by fasterthanlime** [comment]
Yeah this is probably out of scope for the itch app.

The idea is that if your game and your editor are both in one .exe (but create a different window - so you can't easily have an in-game button for "Open editor"), then you can pass arguments.

It's more of an escape hatch, not a replacement for an options screen :)

**Comment by LennardF1989** [comment]
I see, it was more so that if a game has a bunch of arguments to start the game in different ways, for example: OpenGL vs DirectX, Disable Sound, Safemode, etc. For some people, a combination of these arguments would be needed to get the game in a working condition. If I have to add every possible combination as an action to the manifest, I'm going to have a bad time. But you make a good case for having a launcher for that, too...
