### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by omgitsraven** [itchio/itch#1806]
Dear itch app team, 

When I try to install this game https://xavierekkel.itch.io/omg through the app, the installation begins, but then just becomes an "install" button again. It works fine if I download it from the website.

**Comment by fasterthanlime** [comment]
v25 is out, and it seems to install & run fine with it:

![image](https://user-images.githubusercontent.com/7998310/45491389-e66aad00-b769-11e8-94b0-b7ebd17ada2a.png)

You can download itch v25 from https://itch.io/app

**Comment by omgitsraven** [comment]
Yep, working now, thanks!
