### ISSUE TITLE
Add some way to report game crashes?

### ISSUE THREAD

**Issue by szabba** [itchio/itch#181]
When I try to start a game and it closes with a non-zero exit code without opening a window, there's no way to report it. It would be awesome to be able to do it the same as for failed installs.

Arch Linux | v 0.10.2

**Comment by fasterthanlime** [comment]
Agreed.

If someone wants to contribute that: it's relatively straightforward to redirect the game's stdout + stderr to the same log, `tasks/launch.js` and `util/log.js` are good places to start
