### ISSUE TITLE
Says up-to-date, but then updates. (🏁 Issue v23.6.3)

### ISSUE THREAD

**Issue by garageagleMC** [itchio/itch#1811]
Dear itch app team, 

When I click `Check for update` on a game page, I see something from the bottom pop up that says `Ball Platformer is up-to-date.`, but then the game starts updating. Am I missing something?

**Comment by fasterthanlime** [comment]
I'm not sure what happened then, but I'm going to close this regardless, unless you can reproduce it with the latest beta: https://fasterthanlime.itch.io/install-kitch - v23 will no longer be updated.
