### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by maxrios1999** [itchio/itch#1820]
Dear itch app team,

When installing an application, if you exit out of Itch, local files are not installed. This causes the application to appear in the library but with no local files. This results in re-installing and uninstalling to never finish. This occurred when using Tiled2Unity. It could also be a problem with the other developers.

Thanks!

Here's a screenshot of the library and log.
![inkedcapture_li](https://user-images.githubusercontent.com/39229431/40458096-0ea6a756-5ec8-11e8-8f84-a0dfda83e052.jpg)

**Comment by fasterthanlime** [comment]
itch v25 is out, and it handles installation/uninstalltion very differently from v23.

Please re-open this issue if you're able to reproduce it with itch v25.

You can download it from https://itch.io/app
