### ISSUE TITLE
HTML games breaks on relative paths

### ISSUE THREAD

**Issue by anissen** [itchio/itch#1823]
Since a recent change, relative paths breaks HTML games.

I have a HTML game with the following script:

```<script type="text/javascript" src="./stoneset.js"></script>```

This _used_ to work. However, now the game fails to load entirely (stuck at the "Loading the game for the first time"-screen).

Changing the line to avoid relative paths like this
```<script type="text/javascript" src="stoneset.js"></script>```
fixes the issue.

**Comment by fasterthanlime** [comment]
This is the tracker for the desktop app, I've moved your issue here: https://github.com/itchio/itch.io/issues/836
