### ISSUE TITLE
Re-enable auto login

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1826]

**Comment by fasterthanlime** [comment]
Actually I'm fairly happy with no auto-login for now.

**Comment by rcorre** [comment]
Out of curiosity, why was this removed? I found this issue as I was wondering why I have to click my name every time I start the app. Not a huge issue, but it is a slightly annoying inconvenience.

**Comment by VinnyFonseca** [comment]
I've got all my launchers to auto-start hidden, itch is the only one that pops up and asks me to click my name. It is a small thing, but it is a bit inconvenient. Could this be reopened?

**Comment by fasterthanlime** [comment]
I'm working on v26 (the next version) and auto-login is back in.

**Comment by mizunarei** [comment]
Please make sure that this is added. Sorry for the remainder, but this is an essential feature for a pc launcher usage.

**Comment by cflavio** [comment]
Any news about this one? Thanks!

**Comment by mizunarei** [comment]
Can you please bump this into release? It has been nearly three years and us normal people want the feature :(

**Comment by gedrocht** [comment]
Please do not make me fork this lmao

**Comment by kanak8618** [comment]
My itch.io account is disabled. I was send mail 2 times but not resolve my issue how can i solve it ?
![Screenshot_1](https://github.com/user-attachments/assets/07f0a3d0-4d64-4105-8276-f9ba08718640)
