### ISSUE TITLE
Itch client only launches "games" 🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by omgitsraven** [itchio/itch#1827]
Dear itch app team, 

I have a project on Itch, which isn't a game, but which IS a windows executable that I want to be launchable through the Itch app. I had set its "classification" property to "other", since it didn't fit any of the categories that were listed.

I added the file to the project, and set it to be "executable", but the Itch app would only open the containing folder, not launch it. Also, I had set it as being for Windows, but the Itch app wasn't displaying the platform icons, and users on Linux were still being shown the option to download it.

Eventually, as I was poking through all the settings, I tried changing the project's "classification" property from "other" to "game" on a whim, and that made everything work perfectly.

Why is the itch client looking at the nature of the project when determining how to handle a download, rather than looking at the executable/platform settings on the downloads themselves? (Alternately, if that can't be changed, then the setting for the "classification" property currently called "game" should probably be renamed to "software", to avoid this confusion in the future? I had no idea that changing its classification would affect how the downloads are handled, I thought it was just for where the projects are listed on the site.)

**Comment by fasterthanlime** [comment]
Replying in a hurry: the fix is to pick the "tool" classification.

I'd like to rename "tool" to "software" at some point, pending @leafo's approval.

**Comment by omgitsraven** [comment]
Ahh, OK... Yeah, "tool" isn't really a useful descriptor for this project either, so I'd just ignored it... (The project is a virtual puppet that you control with a gamepad.) I can think of lots of other non-game non-tool software projects that could get distributed (a hands-off generative animation, a VR tour of an environment, etc), so definitely having a general "software" category seems important.

I'm even tempted to say that having "game" as a category to mean "executable files" isn't a great idea, even with "physical game" in the same list to contrast it -- what if someone comes up with a word game played verbally between two people the way Twenty Questions is, and distributes the instructions on Itch as a PDF? That wouldn't be a "physical game" because no physical pieces are used once you've memorized the rules, but it WOULD be a game, but there wouldn't be a platform-specific executable to launch...

If that Classification setting is going to be the only way to turn features on and off, it should probably just be a choice of those features, and leave the actual nature of the project as a separate field from what features it's expecting to use (or at the very least, it should *indicate* what features are going to be available for each option, so people who choose "other" will realise what they're locking themselves out of.)

**Comment by fasterthanlime** [comment]
> I added the file to the project, and set it to be "executable"

In that scenario, v25 does launch the executable. At least it should! Please re-open if it doesn't.
