### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by LOKSTED** [itchio/itch#1833]
[deleted]

**Comment by fasterthanlime** [comment]
Hey there,

1. Which country are you downloading from?
2. Which game are you downloading?
3. Do you have any antivirus software enabled?

**Comment by LOKSTED** [comment]
Sorry for being so late, I am downloading from Thailand, It happened to every game, I have Windows Defender Enabled. *EDIT* I am downloading it directly to the External HDD, I don't know if that will be the problem. I can't download games to internal storage because it's just 250 GB. But I don't have a problem when using steam with External HDD. External HDD has USB 3.0. -HDD is 480MBPS-

**Comment by fasterthanlime** [comment]
Thanks for the additional information.

I don't think I'll be able to help you much right now - I really want to make a network diagnostics tool so we can help figure out what's going on for users in Asia. I also want to start recording download speed session speeds in a non-personally-identifiable way, although that might take a bit of time.

Does disabling Windows Defender for a while (with no other programs running) help at all or not?

**Comment by LOKSTED** [comment]
Sry for being late again. No i dont think disabling any programs helps.

**Comment by ghost** [comment]
Am having the same issues in germany, only the app download drops from 100 kbit to 15 kbit, and fails eventually. downloading a game I purchased had the usual 1-2 mbit. Aren't you guys opting for a download client anytime soon?

**Comment by fasterthanlime** [comment]
> Am having the same issues in germany, only the app download drops from 100 kbit to 15 kbit, and fails eventually. downloading a game I purchased had the usual 1-2 mbit.

I'm not sure this is the same problem. Are you talking about downloading the https://itch.io/app installer? Or installing a game using the app? I think you mean the former, and the OP means the latter.

**Comment by ghost** [comment]
the installer fails to download

**Comment by fasterthanlime** [comment]
> the installer fails to download

I've experienced the same (from France) - sometimes downloads from Amazon AWS or Google Cloud are ridiculously slow (in the 100kbit/s range). The [next version](https://fasterthanlime.itch.io/install-kitch) (v25) will not have that problem, as it'll be entirely served from our CDN (which has its own class of problems, but that's a story for another time). So, good news!

**Comment by fasterthanlime** [comment]
v25 is out, everything is served from our CDN - there's no reliance on github's S3 bucket nor cloudflare anymore, please open a different issue if you're still having bandwidth problems with that version!
