### ISSUE TITLE
Itch client "stuck" in image

### ISSUE THREAD

**Issue by syssunn** [itchio/itch#1849]
### Steps to reproduce the problem
1. Open itch client and a web browser
2. Drag and drop an image from the web browser to the itch client

### What's going on? Describe the problem in as much detail as possible.
If I drag and drop an image (jpg, png, etc) from the web browser to the itch client, then the itch app will get stuck in the image web subdomain. This issue persists even if I close and reopen itch.
![giphy](https://user-images.githubusercontent.com/38988934/40888659-9730d13a-6730-11e8-83bd-63974560eaef.gif)

### Information about the software:
OS: Manjaro 17.1.10 stable x86-64
itch: itch 23.6.3-1 (from AUR)

**Comment by fasterthanlime** [comment]
Yup, that's a known v23 bug, unfortunately. See #1722 

> This issue persists even if I close and reopen itch.

What actually happens is that the window is hidden then shown again. If you properly quit itch (tray icon => quit), then it'll show the client again :).

**Comment by syssunn** [comment]
Oh, that's true, my mistake. I didn't notice the app hid to the panel tray after closing it. Thanks for the notice ^_^
