### ISSUE TITLE
Dark mode theme on game/profile pages.

### ISSUE THREAD

**Issue by lparkermg** [itchio/itch#1852]
When editing a theme for a game page/profile page, would it be possible to have a dark mode theme, which would show for those that have dark mode activated?

**Comment by leafo** [comment]
the profile page theme editor currently has a dark background, and the game page theme editor has a light background (in between migrating to new theme editor code). Is the dark background you see on the profile theme editor not what you're looking for?

**Comment by lparkermg** [comment]
Ahh I may not have explained properly, it would be having a different colour scheme on the actual profile page/game page that you can edit, the one that other users would see rather than the theme editor itself.

So like I have a relatively bright page as my profile page, where as I'd also want to accommodate those who have dark mode enabled with a dark theme.

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/891
