### ISSUE TITLE
Sniff & exclude directx installer

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#186]

**Comment by fasterthanlime** [comment]
If someone could open various directx installers with a hex editor and find some strings the uniquely identify them (very low risk of false positive), then we could easily penalize them. I don't want to rely on file paths ever.

A good way to know where to download directx is the winetricks script: https://github.com/Winetricks/winetricks — we might end up using something similar to install dependencies

**Comment by smiley** [comment]
DirectX installers are usually just named `DXSetup.exe`, but they have more defining features:
- Digitally signed by Microsoft (sniffing out `Microsoft` in the "Issued To" field of the final certification is OK)
- Contains the name "DirectX" in the "Product Description" field

I took a bunch from my Steam library and it looks like they use `dsetup.dll` or `dsetup32.dll`, so that too can be used as a marker.

**Comment by fasterthanlime** [comment]
> I don't want to rely on file paths ever.

oh look at 19-day-ago me talking!

turns out we already 0-score if the file contains `uninst`, and for all the games in my library right now, it seems the "dxwebsetup.exe" path is really prevalent:

```
$ find ./ -name '*.exe' -print0 | xargs -0 file {} | grep "self-"
./JiR8SaL7lztNzbkZ/pidgin-uninst.exe:                                                    PE32 executable (GUI) Intel 80386, for MS Windows, Nullsoft Installer self-extracting archive
./JUK75jhXU35xX3PJ/win64/dxwebsetup.exe:                                                 PE32 executable (GUI) Intel 80386, for MS Windows, MS CAB-Installer self-extracting archive
./PZ9cADLOhnAsmynW/dxwebsetup.exe:                                                       PE32 executable (GUI) Intel 80386, for MS Windows, MS CAB-Installer self-extracting archive
./xdJ9tJXS5I1O34SE/uninstall.exe:                                                        PE32 executable (GUI) Intel 80386, for MS Windows, Nullsoft Installer self-extracting archive
./z0BXe7r2Uj3zYe1Z/win32/dxwebsetup.exe:                                                 PE32 executable (GUI) Intel 80386, for MS Windows, MS CAB-Installer self-extracting archive
```

**Comment by smiley** [comment]
`dxwebsetup.exe` is the web-based stub installer, any game packing a redistributable package will fail that check.

And none of the suggestions I made rely on file paths, all are just standard PE features... :confused:

**Comment by fasterthanlime** [comment]
> dxwebsetup.exe is the web-based stub installer, any game packing a redistributable package will fail that check.

unfortunately, yes

> And none of the suggestions I made rely on file paths, all are just standard PE features...

yes, and they're good candidates for the future (just opened #332) — but there's already too much fresh code for 0.12.

do you know a javascript library to parse PE headers? I don't :(

right now, this filtering happens at launch time (when a user clicks' Launch'), so it has to be fast — but on the plus side, if one version of the app gets it wrong, a later version has a chance to fix it. Ideally, it'd be done at configure time, only re-done if there was a problem, but, again, let's see for next versions.
