### ISSUE TITLE
Google Play badge is outdated

### ISSUE THREAD

**Issue by salty-horse** [itchio/itch#1862]
When a game is available to download on Google Play, itch uses this badge:

https://static.itch.io/images/store_badges/google.png
![](https://static.itch.io/images/store_badges/google.png)

The badge is in the old style, showing Google's logo in a serif font. Google's [guidelines](https://play.google.com/intl/en_us/badges/) say to use this new badge:

https://play.google.com/intl/en_us/badges/images/badge_new.png
![](https://play.google.com/intl/en_us/badges/images/badge_new.png)

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/890
