### ISSUE TITLE
Clicking on a game's thumbnail should open a tab in client, not redirect to website

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#187]
Complications:
- no such screen exists now
- what to display, where, how ?
- has to work offline, so can't just webview the game's page, obviously
- has to be closely integrated with the app (1-click install, launch, 2-click uninstall)

**Comment by fasterthanlime** [comment]
part of #184

**Comment by jvdgoot** [comment]
Problem here is that as a user I lose the context of where I was, I was browsing a game in the app and then I'm bounced to a different app on my computer.

Simplest fix would to be give some kind of indicator that this would happen.

An alternative to integrating a game view would be the ability to start the installation in the app from the website.

The most important thing here is that context and flow is maintained. Now it feels like bouncing between two disparate and separate interfaces.

**Comment by fasterthanlime** [comment]
> An alternative to integrating a game view would be the ability to start the installation in the app from the website.

That is definitely what #116 is hinting towards.

The next step is either for @leafo to start integrating those in the itch.io website directly or — in the meantime — for someone to code a browser extension to add those on any page.

I wanted to do the latter but had to use my time elsewhere so far!

**Comment by fasterthanlime** [comment]
cf. #285, ~~which is part of 0.12.x~~

**Comment by fasterthanlime** [comment]
Ah, we do that now!
