### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by JinxLuckless** [itchio/itch#1874]
Dear itch app team,

I purchased MewnBase earlier tonight and am looking forward to playing it. However, I would like to play it from within the itch.io client. When I go to the entry for MewnBase from within the client, it prompts me to buy it, instead, which I've already done. I'm able to download the game via my browser and set it up that way, but I would much prefer just playing it in the client.

I am on Windows 10 if that helps, and have closed out of entirely and then reopened the client, but it still doesn't seem to update and show that I've purchased the game. Thanks!

**Comment by fasterthanlime** [comment]
Hey there,

Are you logged into the app with a different account than the one you purchased Mewnbase with? I've looked into the account you purchased with (JinxLuckless) and it doesn't seem like that account was used with the app at all!

**Comment by fasterthanlime** [comment]
Update: it was a case of two accounts! I've merged them manually.
