### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by joshgiesbrecht** [itchio/itch#1876]
Dear itch app team, 

There are books, RPG docs, and asset packs in which there are multiple zip files and I'd like to download them all, and still use the itch app to manage this. But the app is only letting me choose one file to install (as far as I can see). Please make an option to install multiple files! (maybe specifically for non-games esp, ie. anything without a Launch option?)

thx
 - josh

**Comment by fasterthanlime** [comment]
Hey josh,

itch v25 is out, and it lets you install any upload you want, even multiple uploads per game:

![image](https://user-images.githubusercontent.com/7998310/45490968-cd153100-b768-11e8-8194-a4a983569f76.png)

You can download v25 directly from https://itch.io/app
