### ISSUE TITLE
🏁 Preferences resetting after every update

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1877]
Heya! Everytime my client is being updated my settings get reverted back to the default, resetting my language preferences and disabling launch-on-boot. Could this be fixed? Thank you!

**Comment by fasterthanlime** [comment]
Hey there,

Your preferences are stored in `%APPDATA%\itch\preferences.json`. This file isn't touched by the app's installer when it updates itself. (It wasn't touched by Squirrel.Windows up until v23, and it's not touched by itch-setup for v25 and up).

However, it's possible a third-party program is touching it. I'd recommend keeping a copy of it somewhere, and making sure nothing is messing with it when you don't expect it!
