### ISSUE TITLE
🏁 Issue v23.6.3 - Request to be able to modify the command line for games launched through the client

### ISSUE THREAD

**Issue by Daren-42** [itchio/itch#1878]
Dear itch app team, 

Could you add an option that would allow me to configure command line options when launching from the itch.io desktop client?

For example, I like to use the following command line option for unity based games so I can play them in Borderless Windowed mode:
-popupwindow -screen-height 1080 -screen-width 1920 -screen-fullscreen 0

Thank you,
DreadPirateDuo

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/366
