### ISSUE TITLE
Stop refreshing every page whenever you switch tabs

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#1879]
At the very least, PLEASE stop refreshing the main page every time I leave the tab. I saw a couple games I was interested in checking out at the same time and opened one, then the main page refreshed before I could click the other.. very frustrating to have it constantly refreshing. >.<

**Comment by fasterthanlime** [comment]
I haven't experienced this in v25 (with tabs enabled, see Preferences), please re-open if it's still an issue.

You can download v25 from https://itch.io/app
