### ISSUE TITLE
[Suggestion]itch.io Android app

### ISSUE THREAD

**Issue by ghost** [itchio/itch#1880]
Hello,

I'm a big fan of the games on itch.io and was hoping someone could create and android version of the itch.io desktop client.  I don't have a computer and have always preferred apps over browser on mobile. So I would LOVE to be able to use an itch.io mobile app on my Android phone. If it helps I have an LG V20 (non-root) with Android 7.0 installed on it.  (I reaaally hate having to use mobile browsers, lol)

**Comment by fasterthanlime** [comment]
Hey Josh,

I've been thinking about an itch.io mobile app, not sure yet what form it would take, but it's on my mind.

I'm closing this issue though, because it's not related to the desktop client ;)
