### ISSUE TITLE
[Sandbox enabled] Cannot open any game

### ISSUE THREAD

**Issue by CloudyProton** [itchio/itch#1887]
On a clean install (Linux) and all default settings except for itch.io sandbox enabled, no game can be launched. They crash out with the error: "application crashed. process exited with code 127".

Reading the crash logs all indicate some error reading the ~/itch/isolate-app.profile and claims the path to the executable as "no such file or directory".

**Comment by fasterthanlime** [comment]
itch v25 just released, you can get it from https://itch.io/app

Please re-open this issue if you can reproduce it with itch v25!
