### ISSUE TITLE
CRAFTING

### ISSUE THREAD

**Issue by Sojurn7** [itchio/itch#1888]
HOW do you craft I have only a few tool to craft but I seen others craft buildings so how do you craft I want to show this on You Tube because I like the game play but issue of crafting can not show it.

**Comment by Sojurn7** [comment]
HOW do you guy expect to sale a game if no one is sponsoring it I want to do this I I like Valheim the game but can not craft anything other then what he could at the start not even a fire HOW DO YOU CRAFT!

**Comment by fasterthanlime** [comment]
This is the issue tracker for https://itch.io/app, not for any particular game.
