### ISSUE TITLE
Cannot install game

### ISSUE THREAD

**Issue by Alexzander-Hurd** [itchio/itch#1890]
Hi, I recently saw a game called En Garde and thought I might like to try it but upon trying to install the game it opens the downloads tab and starts but doesn't start downloading. I have tried multiple times, closed the app and opened it again and force quit the app but I'm still having the same problem

**Comment by fasterthanlime** [comment]
Is it this one? https://engarde.itch.io/en-garde

It seems to install fine in itch v25, which was recently released.

You can download itch v25 from https://itch.io/app
