### ISSUE TITLE
Error installing itch.io for ubuntu 18.04/mint 19.

### ISSUE THREAD

**Issue by tyuio8** [itchio/itch#1891]
Hi ! In the installation process of a linux debian base, you show this line of installation for ubuntu 18.04 :

"ITCHIO_DEB="deb https://dl.bintray.com/itchio/deb xenial main"

It's exactly the same as the one from ubuntu 16.04. 18.04 is named Bionic beaver, not xenial. Is this normal ?
Oh, and yeah, the installation doesn't work on my linux, the terminal can't find the folder to update, and i suppose it's cause the name isn't good.

Thank you!

**Comment by fasterthanlime** [comment]
> It's exactly the same as the one from ubuntu 16.04. 18.04 is named Bionic beaver, not xenial. Is this normal ?

It is! The package works on both.

> Oh, and yeah, the installation doesn't work on my linux, the terminal can't find the folder to update, and i suppose it's cause the name isn't good.

Can you paste terminal output or screenshots? Hard to tell what's going on from that :)

**Comment by fasterthanlime** [comment]
v25 doesn't ship with a deb package anymore, it has its own installer: https://itch.io/app
