### ISSUE TITLE
Search only returns local games?

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1901]

**Comment by kuon** [comment]
Follow up from #1248.

It is returning results for game I don't have in my library, and it is not returning results for game I do have. I'll do a bit more tests and let you know if I can find a pattern.

**Comment by fasterthanlime** [comment]
@kuon there was no pattern - it was randomly missing JSON-RPC notifications because it was closing an EventSource too soon.

I changed the endpoint, and it should not happen in the next build.
