### ISSUE TITLE
Crash when closing app

### ISSUE THREAD

**Issue by kuon** [itchio/itch#1910]
Under linux XFCE, when closing the app window, it crashes with the following message:

`crash-reporter reporting: uncaught exception: TypeError: Cannot read property 'native' of undefined`

Using 24.34.0-canary

**Comment by fasterthanlime** [comment]
@kuon does it still happen in v24.36.0 (or higher) ?

**Comment by kuon** [comment]
@fasterthanlime Nop, seems fixed, it nows properly goes into notification area.
