### ISSUE TITLE
i18n: Review missing translations

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1913]
* [x] The whole sidebar
  * In preferences:
    * [x] Scan install location for games
      * No additional items found (status message)
    * [x] Components (broth)
    * [x] Check for game updates
    * [x] Enable tabs
  * In applog:
    * [x] Level
    * [x] Info, Warning, Error, etc.
  * itch://library/installed
    * [x] Manage install locations (button)
    * [x] "View all..."
    * [x] All filters
  * itch://collections
    * [x] "Updated <relative time>"
  * itch://dashboard
    * [x] views, downloads, purchases
  * Manage cave
    * [x] Published
    * [x] Installed
    * [x] Powered by butler
  * Downloads
    * [x] Pause downloads
    * [x] Resume downloads
  * External downloads are a bad idea dialog

Added @quyse's items:

  * [x] itch://collections: "N games" in collection, "View all..." link
  * [x] itch://collections/col_id: filter/sort buttons, "Nothing to see here" for empty view
  * [x] itch://library - "View all..." link
  * [x] itch://library/owned: filter/sort buttons, "Filter..." textbox, "Nothing to see here" for empty view
  * [x] itch://library/installed: "Filter..." textbox
  * [x] itch://locations: "View all..." link
  * [x] itch://locations/appdata (default location?): filter/sort buttons
  * [x] itch://dashboard: filter/sort buttons, "Filter..." textbox
  * [x] Downloads: active download's action ("install")
![2018-07-19-011651_470x119_scrot](https://user-images.githubusercontent.com/416215/42910795-7ee42e6c-8af1-11e8-90f5-43ce9501ffa1.png)
  * [x] The whole "Send feedback" window
  * [x] Main search combobox in sidebar: "No description" label for games without description; type in "test" for example.

**Comment by fasterthanlime** [comment]
I've just reviewed all the strings I feel are missing, I'll add them soon.

/cc @quyse, can you think of any I've missed?

**Comment by quyse** [comment]
@fasterthanlime Yeah, a few more things:

* itch://collections: "N games" in collection, "View all..." link
* itch://collections/col_id: filter/sort buttons, "Nothing to see here" for empty view
* itch://library - "View all..." link
* itch://library/owned: filter/sort buttons, "Filter..." textbox, "Nothing to see here" for empty view
* itch://library/installed: "Filter..." textbox
* itch://locations: "View all..." link
* itch://locations/appdata (default location?): filter/sort buttons
* itch://dashboard: filter/sort buttons, "Filter..." textbox
* Downloads: active download's action ("install")
![2018-07-19-011651_470x119_scrot](https://user-images.githubusercontent.com/416215/42910795-7ee42e6c-8af1-11e8-90f5-43ce9501ffa1.png)
* The whole "Send feedback" window
* Main search combobox in sidebar: "No description" label for games without description; type in "test" for example.

I'll comment here if I see more :)

**Comment by quyse** [comment]
Game with multiple downloads, choosing cancel in selection dialog:
![2018-07-19-192055_422x50_scrot](https://user-images.githubusercontent.com/416215/42956549-e938de38-8b88-11e8-9097-efdf3ccbc886.png)

**Comment by fasterthanlime** [comment]
@quyse I think I caught them all! (including your last comment about the cancelled notification).

Good to close for now?

**Comment by quyse** [comment]
Still untranslated:
* "Installed" filter button in itch://library/owned
* "Filter..." editbox in dashboard, library owned/installed, collection view
* Cancel button in feedback dialog

Also "Dear itch app team," initial message in feedback dialog, not sure though if it's OK to encourage people write in their languages :)

Other than that, seems you covered everything!

**Comment by fasterthanlime** [comment]
> Also "Dear itch app team," initial message in feedback dialog, not sure though if it's OK to encourage people write in their languages :)

I considered that but, except if they write in English, French, Spanish, German, or Italian, I'm not sure I can be of much help (and even then..)
