### ISSUE TITLE
By default, collections list should show most recent entries first

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1926]
On library page as well

**Comment by fasterthanlime** [comment]
So.. we should never use API order?

Currently API order is the default sort for:

  * `itch://collections` (stripes of each of your collections)
  * `itch://collections/:cid` (serie of a single collection)

Do you want both of these to be sorted by collection_game.updated_at by default?

(Also, I wonder what the "API order" should be called)

**Comment by leafo** [comment]
The API order appears to be correct, the order in the app looks different. My "interesting" collection (with over 2k items) is showing early additions first, instead of what's returned first in the api: https://api.itch.io/collections/71828/collection-games
