### ISSUE TITLE
[win32] Broken game for v0.10.2

### ISSUE THREAD

**Issue by TideGear** [itchio/itch#193]
Game [Forget-Me-Not](http://nyarlu.itch.io/forget-me-not) is broken for me.

Here's the [debug log](https://gist.github.com/93a8d15ed25943058925).

**Comment by fasterthanlime** [comment]
Hey, thanks for your report! :tada:

The reason is that uploads weren't properly tagged by the developer — there's more information here: http://itch.io/board/12011/itch-app-development

I fixed up this game, it should at least download now.
