### ISSUE TITLE
kitch/UX: Consider making the default apps install location a subfolder inside the user's chosen installation path

### ISSUE THREAD

**Issue by notNSANE** [itchio/itch#1939]
This should greatly increase UX since I'm pretty sure most users that choose a custom itch install location will also choose a custom apps install location.

Hope that makes sense :P

**Comment by fasterthanlime** [comment]
I see what you're driving at, but it's really important to both the old & the new install system to have a distinction between:

  * Where the app's binaries are installed
  * Where the app's data resides

When you uninstall the app it wipes the binaries, but not the data, so if you just want to reinstall another version of the app, that works fine.

The installer assumes the folder with the app's binaries is completely under its control - ie. it can rename/move/delete/add anything in there without consequences (as long as there's a working copy of the app at the end).

What I am planning on doing is, when queuing a game, having the app ask you where you want to install it (along with which upload to install, if there are several). From there you could easily add another install location, it would make the whole thing a lot more obvious than it is now.

**Comment by notNSANE** [comment]
Makes a lot of sense.

But I still think that NOT showing the user where the app's binaries are being installed (meanwhile) it's a bit of an issue. 

Maybe include an extra step or option in the installer, so the user knows where those are?

**Comment by fasterthanlime** [comment]
> But I still think that NOT showing the user where the app's binaries are being installed (meanwhile) it's a bit of an issue.
> 
> Maybe include an extra step or option in the installer, so the user knows where those are?

The installer (on Windows) shows where the app's binaries are (by default, `C:\Users\jane\AppData\Local\itch`), it doesn't show where the app's data is (by default, `C:\Users\jane\AppData\Roaming\itch`) - but neither does chrome (it stores your profiles, your cookies, your browser cache, offline app data, etc. - all there - so it's similar to itch).

The idea in introducing a modal when you install something is that it would always show you where something is going to be installed, along with this lil' widget:

![image](https://user-images.githubusercontent.com/7998310/42714060-0fc75afc-86f2-11e8-8862-62644cf8a6e4.png)

That gives you a quick idea of how much space you have.

**Comment by fasterthanlime** [comment]
Closing as "install dialog" is a separate issue.
