### ISSUE TITLE
Some free games show the Buy now button in collections

### ISSUE THREAD

**Issue by aviraccoon** [itchio/itch#194]
I think this happens when both minimum price and disable all payments checkbox are set. [Example](http://simonstalhandske.itch.io/setupexe) - min price is $15, but it's actually free on the website.

Using the newest master commit (2a666a7).

**Comment by fasterthanlime** [comment]
sounds like an API bug @leafo

**Comment by fasterthanlime** [comment]
it's true that "Disable all payments" doesn't change the min_price (in case you come back to edit game, re-enable payments, you expect the price to be the same)

in my mind, either the API should:
- return 0 for `min_price` when payments are disabled
- have a `payments_disabled` response field that I can use to compute `may_download` more accurately

I prefer the first option though, the 2nd one sounds like unnecessary internal exposure via the API.

**Comment by fasterthanlime** [comment]
> unnecessary internal exposure via the API.

for example a game might be free while in open beta but might plan to release at $15 — it's not our place to leak that info

**Comment by fasterthanlime** [comment]
This has been fixed server-side!

The API now returns 0 for `min_price` when payments are disabled.
