### ISSUE TITLE
kitch/UX: No "loading" animation (normally when switching from a local page to an app's itch landing site)

### ISSUE THREAD

**Issue by notNSANE** [itchio/itch#1942]
On slow connections this might make the user think the app has crashed (limit is ~5 seconds).

Maybe add a simple animation to the itch logo?

**Comment by fasterthanlime** [comment]
Actually there used to be a "scanner" animation on this button:

![loader](https://user-images.githubusercontent.com/7998310/42686232-8cdfc6ee-8695-11e8-9f28-17e2c3e30f45.gif)

I'll look into it.

**Comment by fasterthanlime** [comment]
There's a loading indicator under the address bar again now.
