### ISSUE TITLE
kitch/Installer/UI: Add a "Browse..." button instead of clicking on the install location to choose it

### ISSUE THREAD

**Issue by notNSANE** [itchio/itch#1944]
Goes against many, many, many, many, many years of install conventions :P

**Comment by fasterthanlime** [comment]
Ah, the installer, yeah. This will get fixed at the same time as #1914

**Comment by fasterthanlime** [comment]
Fixed in https://github.com/itchio/itch-setup/commit/ca5f39f9f5bd18a5040fc5644958f829c7c913bd (and subsequent commits!)
