### ISSUE TITLE
"Buy now" shown for owned library games, eventually becomes "Install"

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1945]
This bug report is from kristen. When she booted up the app every game in her library had "Buy now". When going to the game page, it still showed "Buy now." After taking the screenshot for this bug, she tabbed back into the app and it correctly showed install. Is there a delay before this data is synchronized?

<img width="1103" alt="buyno" src="https://user-images.githubusercontent.com/15198/42666078-b7b0f1b6-85f7-11e8-8dcd-43fd115623da.png">

**Comment by fasterthanlime** [comment]
So #1902 is going to make it better, but the buy flow (#1988) is still pretty bad, we should discuss that internally soon @leafo

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/1989
