### ISSUE TITLE
Getting an error when trying to update the app

### ISSUE THREAD

**Issue by TaylorAnderson** [itchio/itch#1967]
![image](https://user-images.githubusercontent.com/5308535/42776858-560ccfea-8906-11e8-8b90-c1757f96a38e.png)

Seeing this image when the app opens, and when I try to "Check for updates".

I'm on Windows 10, if that helps.  Let me know if you need any more info!

**Comment by fasterthanlime** [comment]
Yep, GitHub was returning HTTP 500 for every request of our update servers in the timeframe where you got that.

Should be fixed now.
