### ISSUE TITLE
ERR_NETWORK_CHANGED ruins butler ipc

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1979]
Steps to reproduce:

  * Launch a game
  * Unplug/plug an ethernet cable, disable/re-enable wi-fi, etc.
  * Watch the request get cancelled as Chrome believes we somehow *lost the ability to send packets over loopback*
  * Search the web
  * Find nothing
  * Consider working around this

**Comment by fasterthanlime** [comment]
Hey look if we don't use http/2 at all this works fine.

**Comment by balalrumy** [comment]
Possible Fix to err_network_changed Error is 
Fix 1:- Restart your modem
Fix 2: Flush DNS and reset TCP/IP
Fix 3: Clear your Browsing Data

Read in more details[ How to Fix err_network_changed Error in Google Chrome](https://technicalustad.com/err_network_changed/)

**Comment by fasterthanlime** [comment]
@balalrumy this bug was fixed in an earlier version of itch, but thanks anyway!

**Comment by balalrumy** [comment]
Welcome
