### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by HumanMcPerson** [itchio/itch#1983]
Dear itch app team, 

I am new to PC gaming, and I don't know anything about how to run files or how launchers work. I recently downloaded the app hoping to play a game that I've wanted to try, but I have no idea how to run the game. Is there a button that will just run the game or do I need to download something else? And no, I do not mean how do I submit my own game in it, I've searched google several times and all of them refer to 'how do i submit my own game' This is really frustrating because I have been wanted to play this game for a while and I don't understand how I can do it. Please either tell me how to actually run a game I downloaded(several times) or update the app to have a run button. 

I am using Windows 10, and it should be the latest version of itch.io.

**Comment by fasterthanlime** [comment]
Hi,

When you open a game's page in the itch.io app, you should see a panel on the right with a few buttons.

![image](https://user-images.githubusercontent.com/7998310/43046367-070577a0-8dc8-11e8-9aed-cf7ddac8e64e.png)

The top-most button should be "Install". If you click it and wait, it should become "Launch", If you click "Launch" the game should open.

If it doesn't do that, please link to the game you're trying to install & launch, so we can look into it. Thanks!
