### ISSUE TITLE
App should fetch owned keys after purchase

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1989]
We can tell when a game has been purchased from within the app, so we should queue a fresh fetch then.

It would be even better if we fetched only the keys for a particular game, but we'll need batch API endpoints for that.

**Comment by fasterthanlime** [comment]
> We can tell when a game has been purchased from within the app, so we should queue a fresh fetch then.

Actually, that's fairly hard to do because there's a bunch of checkout flows, and I don't want to do pattern matching on the html we show.

A meta tag at some point would be nice, or even a server header `X-Purchase-Completed` or whatever, just a way for the app to tell that there's been a new purchase.

Alternatively, we wouldn't even need t queue a full profile owned keys fetch if we could just query the API for download keys for specific games.

/cc @leafo @GranPC

**Comment by leafo** [comment]
`X-Itch-Download-Key-Id` and `X-Itch-Download-Key-Owner-Id` are now returned on download key pages, which should give you enough information to determine if refresh is necessary.

**Comment by fasterthanlime** [comment]
@leafo I have two follow-up requests:

  - [x] Include the `itch:path` meta tag on download key pages
  - [x] Include the `X-Itch-Download-**` headers on game pages too

**Comment by leafo** [comment]
Added the new ones
