### ISSUE TITLE
[linux] Broken game for v0.10.2

### ISSUE THREAD

**Issue by erbridge** [itchio/itch#200]
Game [White Rose](http://dissonent.itch.io/white-rose) is broken for me.

Here's the [debug log](https://gist.github.com/c52527cd6fc1cb5add9d).

**Comment by fasterthanlime** [comment]
Hey, thanks for the report! :tada:

RAR files are not supported and never will be —here's why: http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games

I suggest you contact the developer & link them to that page!

**Comment by erbridge** [comment]
Agreed. Appreciate you enforcing it :).

**Comment by fasterthanlime** [comment]
Thanks for your understanding! :+1:
