### ISSUE TITLE
OIDC Authorization Code Flow

### ISSUE THREAD

**Issue by axelvaindal** [itchio/itch#2011]
Hi,

I'm trying to implement an oauth provider for the Meteor js framework in order to be able to login in an application with a Itch.io account.
I have followed documentation guidelines, but I encounter difficulties retrieving `access_token` in order to finalize the login process.

The thing I am looking for is to make the Meteor server handle the login process completely, and as such, requesting an access token in order to retrieve scope `profile:me`.
Is there any way to retrieve an access token based on OIDC Authorization Code Flow, similarly as how Twitch handle such [login process](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc/#oidc-authorization-code-flow) ?

If not, is parsing the callback url client side the only way to retrieve such `access token` ?

Thanks in advance for your help,
Sincelerely,
@axelvaindal

**Comment by fasterthanlime** [comment]
Hey axel,

We don't support OIDC at the moment, so, yep, your best bet is to parse the callback url client-side, and POST it to your own server. Hopefully this shouldn't be too much trouble! The itch.io API documentation pages give some pointers, as I'm sure you've already discovered.

That said, we are planning on expanding our OAuth 2 support in the future, to support Authorization codes - there's no ETA for that, so I would recommend going with the Implicit Flow for now.

**Comment by axelvaindal** [comment]
@fasterthanlime 

Wow, fast answer, thanks ! 😄 

This is actually a trouble as I'm using [oauth](https://github.com/meteor/meteor/tree/devel/packages/oauth) package from the `meteor` framework which I assume expect a full completed OIDC Authorization Code Flow in order to connect 😟 .
I asked in the forum if there is by chance a way to get the hand back in order to process the `access_token` client side and then send it to the server but I'm afraid it won't be possible.

If not, I will postpone the package until OIDC is supported on your side, then release it so the community can use it to login with Itch.io

**Comment by fasterthanlime** [comment]
> This is actually a trouble as I'm using oauth package from the meteor framework which I assume expect a full completed OIDC Authorization Code Flow in order to connect 😟 .

Ah, it looks like they don't support the implicit flow at all.. which I guess is to be expected, since it's a (kinda) serverside framework.

What's your usecase for itch.io OAuth btw? Is it for a website/service, or a game?

**Comment by axelvaindal** [comment]
Yeah, implicit flow isn't implemented, so I'd to either create my own wrapper around OAuth in order to provide support for it, or wait until you have implemented OIDC.

I'm building a crowdsourcing platform for games focused on feedback gathering (game design, marketing) and community, and the studios we are working with may have already published their games on itch.io (as distribution and marketplace is not our top priority). Implementing Itch.io OAuth would make easier the relation between our platform (feedback) and Itch.io (distribution, marketplace) as studios would be able to import already provided data about the game and could keep their itch.io existing account while gathering feedback with our tools.

By the way, don't know the policy of itch.io external contribution, but if I can be of any help regarding OAuth and external services, let me know 🙂 

Edit:
-----

The package is online and available [here](https://github.com/M4dNation/accounts-itch). The only thing remaining is to update code to match the future implementation of the API on your side related to OIDC.

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/897

**Comment by pinklily69** [comment]
Hi there,

It's been 6 years, did you guys implement OIDC?
