### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by ghost** [itchio/itch#2027]
Dear itch app team, 
I get an error which is: failed to load: js / plugin / Custom Text on Title Screen.js
![failed to load](https://user-images.githubusercontent.com/41882351/43412811-5b51dcc4-93fc-11e8-836e-f39bcb20f48a.png)

**Comment by fasterthanlime** [comment]
That's a known issue with v23, see #1211 

You can use the v25 beta to play Total NC: Princess Park EDIT, download it here:

  * https://fasterthanlime.itch.io/install-kitch
