### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by sep332** [itchio/itch#2028]
Dear itch app team, 
I have my games installed on a network drive on Windows. You know, like \\\192.168.x.x\blah. But the itch.io launcher program removes one of the first backslashes, and then it can't launch \192.168.x.x\blah.

Thanks!

**Comment by fasterthanlime** [comment]
itch v25 is out, and it handles install/launching differently - please re-open if it still doesn't work with it.

You can download itch v25 from https://itch.io/app
