### ISSUE TITLE
Bad UX when editing blurb for a game in a collection

### ISSUE THREAD

**Issue by tobiasvl** [itchio/itch#2037]
I wrote a blurb for a game that I added to one of my collections.

If I go to the collection and click "Edit blurb", the blurb appears in a textbox, wrapped in a `<p></p>` tag. That's weird. Should I remove them or keep them in?

When I click "Save", I don't get sent back to the collection, but itch dumps the JSON representation of the blurb in my browser.

```{"success":true,"blurb":"<p>Blurb goes here<\/p>"}```

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/874

**Comment by tobiasvl** [comment]
Ah, haha, my mistake.

**Comment by fasterthanlime** [comment]
@tobiasvl just to make sure: are you seeing that issue only in the itch app, or can you reproduce it in another browser, say, Chrome or Firefox?

nvm I was just able to reproduce it in Chrome - just clicking 'Add blurb', entering anything, and saving, redirects to the JSON response.

**Comment by leafo** [comment]
Thanks for the report, sounds like javascript is missing from that dialog.

**Comment by leafo** [comment]
This is fixed now
