### ISSUE TITLE
Spawn EACCESS error when launching game

### ISSUE THREAD

**Issue by tomcashman** [itchio/itch#2056]
Two players have reported the following when launching the game on Windows 10. However, it is working fine for other players. Our game ID is [290116](https://alchemiccutie.itch.io/alpha).

I was able to confirm with one player that it occurs on Windows 10.

Any help is greatly appreciated :)

![itcherror](https://user-images.githubusercontent.com/1745420/44553672-7b135980-a72e-11e8-8b1f-e30c1c0f70c5.png)

**Comment by fasterthanlime** [comment]
I'm on mobile right now but is it possible that a) the game is 64-bit and b) those two users are running a 32-bit version of Windows?

**Comment by fasterthanlime** [comment]
> fasterthanlime commented 11 hours ago
> I'm on mobile right now but is it possible that a) the game is 64-bit and b) those two users are running a 32-bit version of Windows?

Replying to my past mobile self: nope, it's a 32-bit executable, it is dotNet though:

```
|-- 8.50 KiB alchemiccutie.exe windows-386 win(gui dotNet)
```

Also, it's pushed with butler, so there's no installer ~fuckery~ shenanigans at play here.

**Comment by fasterthanlime** [comment]
Just tried installing & running it myself with the latest itch stable (on 64-bit Windows 10.0.17134 Build 17134), both with and without sandbox, and everything works as it should, I can't think of anything else at the moment!

(Except asking users 1) whether they have the itch.io sandbox enabled 2) if they can click 'Show local files' and run the game manually)

**Comment by tomcashman** [comment]
I checked with player and they’re using Windows 10 64 bit version 16299.

Really bizarre.

**Comment by tomcashman** [comment]
Searching more it looks like an EACCESS error is something file permission related (https://msdn.microsoft.com/en-us/library/5814770t.aspx?f=255&MSPPError=-2147217396).

I wonder is something owned by a different/administrator account.

```
EACCES
Permission denied. The file's permission setting does not allow the specified access. This error signifies that an attempt was made to access a file (or, in some cases, a directory) in a way that is incompatible with the file's attributes.

For example, the error can occur when an attempt is made to read from a file that is not open, to open an existing read-only file for writing, or to open a directory instead of a file. Under MS-DOS operating system versions 3.0 and later, EACCES may also indicate a locking or sharing violation.

The error can also occur in an attempt to rename a file or directory or to remove an existing directory.
```

**Comment by fasterthanlime** [comment]
> Searching more it looks like an EACCESS error is something file permission related (https://msdn.microsoft.com/en-us/library/5814770t.aspx?f=255&MSPPError=-2147217396).
> 
> I wonder is something owned by a different/administrator account.

Yes, but you'd be surprised what errors node.js can throw when it tries to execute files (the next version of the app no longer uses node.js for that).

> (Except asking users 1) whether they have the itch.io sandbox enabled 2) if they can click 'Show local files' and run the game manually)

I thought I had mentioned checking the actual file permissions, but I didn't. Could you ask your players to do that? I mentioned the sandbox because it runs as a different user, although itch knows to change permissions as appropriate before launching.

**Comment by tomcashman** [comment]
I've checked with 2 players and they're not using sandbox and were able to launch via 'Show local files'.

**Comment by fasterthanlime** [comment]
> I've checked with 2 players and they're not using sandbox and were able to launch via 'Show local files'.

Ah, I forgot one of the usual suspects - are either of the players using third-party Antivirus software? (Anything in addition to Windows Defender)

**Comment by fasterthanlime** [comment]
@tomcashman I'm curious if the game works via https://fasterthanlime.itch.io/install-kitch for the affected players. That will become the stable version of itch soon-ish, so I'd like to know if the issue still exists there (again, it runs fine on Win10 for me both with stable itch and beta itch)

**Comment by fasterthanlime** [comment]
itch v25 is out: https://itch.io/app

It has a completely different way of installing and launching games, so it's definitely worth a try.

Please re-open if your players are still seeing that happen with v25 or higher.
