### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [itchio/itch#2074]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Itch on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by fasterthanlime** [comment]
Can you link to a game on itch.io that is distributed as a Flatpak package?

**Comment by LeandroStanger** [comment]
@nanonyme Could you help?

**Comment by fasterthanlime** [comment]
Here's my current take on it:

  * it looks like Flatpak packages are designed to be distributed via flatpak repos, and installed via the flatpak command-line utility
  * I don't think it's likely we'll find flatpak-packaged games as itch.io uploads on game pages

As for distributing the app as flatpak - it has its own installer and self-updater right now, I'm not interested in packaging it with flatpak at the moment.

**Comment by nanonyme** [comment]
Flatpak does allow for making self-contained deliverables. I've done them once or twice for piloting a test. The problem is updating them is a real PITA with lack of a proper update channel. It's far easier to have a bootstrap shim even if the application internally keeps updating itself. Eg Steam is designed like this.

**Comment by fasterthanlime** [comment]
So we could just make a flatpak for https://github.com/itchio/itch-setup ?

**Comment by nanonyme** [comment]
Maybe, I don't know details of your setup. Works best if your installer can live under /app and the rest of the software can be installed under XDG_DATA_HOME or so. Normally with Flatpak there's limitations where things can write and when the application is running, it can mostly write to directory that looks like user home but is a sandbox. You can declare which directories should be persisted

**Comment by fasterthanlime** [comment]
> Maybe, I don't know details of your setup. Works best if your installer can live under /app and the rest of the software can be installed under XDG_DATA_HOME or so. Normally with Flatpak there's limitations where things can write and when the application is running, it can mostly write to directory that looks like user home but is a sandbox. You can declare which directories should be persisted

That's where it gets hairy. To install and run, the app doesn't need to write to folders outside of: `~/.itch` and `~/.config/itch`.

But! You can add "install locations", which are folders where the app will be able to install games. And that usually doesn't play well with outside sandboxes at all.

**Comment by nanonyme** [comment]
With Steam we homed Steam under XDG_DATA_HOME/Steam so it installs all games during runtime under XDG_DATA_HOME/Steam/steamapps
There was some fairly hairy workarounds because about half of things were XDG aware and Flatpak has some peculiarities with names. Eg config instead of .config etc (so we ended up combining the two with symlinks and hoping for the best). In reality you should be using XDG_CONFIG_HOME when it's set

**Comment by fasterthanlime** [comment]
> In reality you should be using XDG_CONFIG_HOME when it's set

Mhh, we use `$XDG_DATA_HOME` in itch-setup for creating shortcuts, but we use `$HOME` directly for the install path: https://github.com/itchio/itch-setup/blob/ab2d122c4d266de58b5c40e693db70ffb9c5247d/native/native_linux.go#L43-L45

As for the app itself, it seems like electron is using `$XDG_CONFIG_HOME`: https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

To summarize:

  * itch-setup installs binaries and libraries to `$HOME/.itch`
  * itch stores its config files in `$XDG_CONFIG_HOME/itch`

**Comment by nanonyme** [comment]
Home directly is fine, Steam Flatpak does persist=. which keeps entire home. Problems arise when you want to write outside home

**Comment by nanonyme** [comment]
Note it's still not actual user home in this case but a sandbox

**Comment by fasterthanlime** [comment]
> Note it's still not actual user home in this case but a sandbox

Yeah that's fine.

> Problems arise when you want to write outside home

So custom install locations would be broken, but that's about it.

What's the story with custom protocols? The itch app registers `itch://`.

**Comment by nanonyme** [comment]
I have no idea about custom protocols. How are you registering them?

**Comment by fasterthanlime** [comment]
> How are you registering them?

With electron's facility: https://github.com/electron/electron/blob/451b1782acfef01dd0758e7b9ddb329700626b98/docs/api/app.md#appsetasdefaultprotocolclientprotocol-path-args

I'm assuming it uses xdg-mime, like we used to do manually in previous versions!

**Comment by nanonyme** [comment]
I doubt that works directly. Scheme registration is apparently possible but requires a specific file in application

**Comment by andreldmonteiro** [comment]
Please make the app available on flathub, been using steam in flatpak form for years and now just discovered the itch app isn't available there after buying the big bundle sale

**Comment by Pobega** [comment]
Now that the Itch app has support for using system Wine to run Windows games it would be great to get a Flatpak since it would be pretty non-trivial to also include vanilla wine with it.

(I'm a Fedora Silverblue user so I **don't** have a system wine -- I exclusively use containerized programs)

**Comment by loonycyborg** [comment]
https://github.com/wesnoth/wesnoth is now on itch.io and uses flatpak as a way to deploy on linux. Because of lack of a way to upload/link a flatpak repo to itch.io wesnoth won't be downloadable from itch on linux. I'm main wesnoth's packager and currently I'm not interested in making appimage packages too because they don't have anything resembling flatpak runtimes. Wesnoth has lots of dependencies, like pango, making dependency issues very likely, and no way I'm going to manage my own set of dependency .so files and the like.  Even for windows I use dependencies from msys2 now. So for linux I would require a targetable common runtime too, for example flatpak runtime or steam runtime. That's needed both to ensure lesser risk of sudden breakage for users and a smooth way to get security updates for those dependencies.

**Comment by nanonyme** [comment]
@loonycyborg I strongly recommend leveraging https://github.com/flathub/flatpak-external-data-checker whether using Flathub or not. It can automatically update your deps into manifest as long as you provide it metadata. It can also be automated to run through Github actions which is what Flathub does.

**Comment by loonycyborg** [comment]
> @loonycyborg I strongly recommend leveraging https://github.com/flathub/flatpak-external-data-checker whether using Flathub or not. It can automatically update your deps into manifest as long as you provide it metadata. It can also be automated to run through Github actions which is what Flathub does.

The only wesnoth dependency that isn't handled by freedesktop runtime is libboost and it's a bad idea to automatically update it since their updates are more likely to introduce a breaking change than a security fix.

**Comment by mossymossmoss** [comment]
Having itch on flathub would mean very easy access for many Fedora/Pop/Elementary (probably more) users. I would love to see it put on there and it seems to be a simple task

**Comment by Pobega** [comment]
> What's the story with custom protocols? The itch app registers itch://.

Registering custom protocols mostly "just works" if you ship a `.desktop` file with the protocol (from what I've experienced.) It's something I use in the [Fightcade Flatpak](https://github.com/flathub/com.fightcade.Fightcade/blob/master/fcade-quark.desktop).

In your case you'd just need `MimeType=x-scheme-handler/itch`.

The Fightcade Flatpak ships two desktop files (one for the launcher and one for the `fcade://` handler, each launch different binaries) so it is a little less complex than your setup, but certainly possible.

**Comment by VarLad** [comment]
@fasterthanlime Any incentive on this? A flatpak would be nice and doesn't seem too hard

**Comment by Ferk** [comment]
I stumbled upon this ticket when trying to find a way to install itch.io into my Steam Deck.

The deck has a read-only filesystem for the main OS, the recomended way to install software is through flatpak, ideally poblished through flathub, which is already set up by default. It would be great to be able to use itch.io software and games from the deck.

**Comment by Saijin-Naib** [comment]
Jumping in to say that a flatpak release would be amazing as it would make it usable on MUSL LIBC systems like Alpine (which I use for my Desktop)

**Comment by polyjitter** [comment]
Found this, and really disappointed to see that flatpak seems like it's just not gonna happen. Makes itch basically not usable on Silverblue. There's more than just preference to it - there are entire distros being built around flatpak-first desktop apps, especially ones based on ostree. 

I'd really like to use itch on my desktop. I run silverblue for a variety of reasons, one of which being that ostree makes keeping my system stable extremely hassle free, even with a bunch of tweaking. As of current status, I can't.

**Comment by Saladin1812** [comment]
even steamdeck uses flatpaks from flathub by default.. still its not convincing enough for itch to do it.. sadge.

**Comment by jpsnyder** [comment]
Would it be possible for someone to fork and create an unofficial flatpak client? Kind of like how we have heroic for epic.

**Comment by Pobega** [comment]
> Would it be possible for someone to fork and create an unofficial flatpak client? Kind of like how we have heroic for epic.

I haven't tested it, but there's already https://github.com/gjpin/itch-flatpak (top result in Google for `itch flatpak`)

**Comment by nanonyme** [comment]
@jpsnyder there is already unofficial itch on Flathub

**Comment by Saladin1812** [comment]
> @jpsnyder there is already unofficial itch on Flathub

There is NO itch on FLATHUB... the one repo that exists is NOT ON FLATHUB and is not a maintained flatpak.

**Comment by jpsnyder** [comment]
Ah yeah. Because that is what we really want. We want itch.io to show up on the software store on the steam deck.

**Comment by Doomsdayrs** [comment]
A bit late to the party but: https://flathub.org/en/apps/io.itch.itch
