### ISSUE TITLE
Use 'naked' install strategy for .gb files

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2076]
Those are Gameboy ROMs.

See #2075 

By the way, it would be nice to round up common file extensions for other ROM types and just add them all in one go.

Here's the current table: https://github.com/itchio/butler/blob/master/installer/installer_for_ext.go

**Comment by tobiasvl** [comment]
It would be great to round up other ROM types too, yeah! But perhaps `.gbc` could also be added in this round, which are Game Boy Color ROMs? Doesn't make much sense to support `.gb` but not `.gbc`.
