### ISSUE TITLE
Itch app not displaying sale price

### ISSUE THREAD

**Issue by tobiasvl** [itchio/itch#2082]
It seems that games/tools that are on sale are still displayed as full price in the main view in the itch app.

Example: PixaTool is "$28.44 or more" in the app. If you click "Buy now", however, you'll see that it's on sale for $9.95 in the purchase dialog window that appears.

**Comment by tobiasvl** [comment]
This seems to still be the case in the new version.

**Comment by fasterthanlime** [comment]
Looks like an easy fix! kitch has it, I'll push it to stable once I'm sure it's.. stable.

**Comment by fasterthanlime** [comment]
butler v14.4.0 shipped, it returns sale info in Fetch.Game, which itch v25.1.0 picks up.

You can check the version of butler the app is using in Preferences.
