### ISSUE TITLE
[linux] Broken game for v0.10.2

### ISSUE THREAD

**Issue by erbridge** [itchio/itch#210]
Game [AirC.A.T](http://tsfreddie.itch.io/aircat) is broken for me.

Here's the [debug log](https://gist.github.com/4f2018b3100bb738b031).

**Comment by fasterthanlime** [comment]
Hey @erbridge, this is fixed in 0.10.4, which I just released :)

**Comment by fasterthanlime** [comment]
@erbridge I also just updated the AUR package to 0.10.4 (first time working with AUR, it's quite friendly!) /cc @frozencow

**Comment by erbridge** [comment]
The AUR package is still at `0.10.2` as far as I can see.

The AUR is nice, especially since they switched it to git repos. I'm a big fan of Arch in general.

**Comment by fasterthanlime** [comment]
:o but I just pushed.

maybe I messed up something

**Comment by fasterthanlime** [comment]
@erbridge I think maybe I need to run 'mksrcinfo'

**Comment by Mrmaxmeier** [comment]
@fasterthanlime it seems like you also need to update the [source hash](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=itch#n18).

**Comment by fasterthanlime** [comment]
brb installing a vagrant box of archlinux (I don't have an arch install handy :|)

**Comment by erbridge** [comment]
@fasterthanlime That sounds right to me. See https://wiki.archlinux.org/index.php/Arch_User_Repository#Sharing_and_maintaining_packages for a full run down.

**Comment by fasterthanlime** [comment]
Alright, it should be good now :)

**Comment by erbridge** [comment]
Still seems to be failing for me on the extraction step.

**Comment by fasterthanlime** [comment]
> Still seems to be failing for me on the extraction step.

Can you post a new log?

**Comment by Mrmaxmeier** [comment]
I've tested a little and this particular tar doesn't seem to contain the magic tar sequence.
Linux `file` only recognizes it dynamicly.
I can't think of a case where using the file extension as a fallback could harm.

|  | file-type lib | `file` command |
| --- | --- | --- |
| 133269.tar (the packed game) | null | tar archive |
| first 512 bytes of 133269.tar | null | tar archive |
| first 511 bytes of 133269.tar | null | data |
| a_normal.tar (that I've packed) | application/x-tar | POSIX tar archive (GNU) |

**Comment by erbridge** [comment]
Sure: https://gist.github.com/c18dac9f24ba6320cb82

**Comment by fasterthanlime** [comment]
@Mrmaxmeier: sounds good, thanks for the research. Want to open a PR with such a fallback?

I suppose sniff.path is a good place for it

**Comment by fasterthanlime** [comment]
Fixed in 0.10.5

**Comment by FrozenCow** [comment]
For next time you could use:
https://gist.github.com/FrozenCow/335f394780cbfe26fca1
It updates the version, srcinfo, builds the package, lints the package
using namcap (results in a few warnings, but usually not a problem) and
creates a commit. You only need to push after that.

**Comment by fasterthanlime** [comment]
@FrozenCow ah, much appreciated, thanks!
