### ISSUE TITLE
[kitch] Tray Icon's right click menu mentions "Owned Items" instead of "Library"

### ISSUE THREAD

**Issue by notNSANE** [itchio/itch#2100]
Sorry for the poor report, bit of a rush :P 

It should say Library since it actually focus on the Library instead of the "Show all..." of the Owned Items menu.

![bje4syk](https://user-images.githubusercontent.com/7162375/45237230-77e2a680-b2b4-11e8-9cb8-9e078115671c.png)

**Comment by fasterthanlime** [comment]
Fixed in https://github.com/itchio/itch/commit/2eeafe9bcc16076604caa5a1b65d99788f1cdbf7
