### ISSUE TITLE
Cannot execute installer on Ubuntu 18.04

### ISSUE THREAD

**Issue by TheSHEEEP** [itchio/itch#2109]
When trying to execute the installer, I get this error:

```
2018/09/12 10:12:51 App name specified at build time: itch
2018/09/12 10:12:51 Locale:  C
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()
	/builds/itchio/itch-setup/src/github.com/itchio/itch-setup/main.go:129 +0x109d

```

**Comment by fasterthanlime** [comment]
Good catch, will release a fix asap.

**Comment by fasterthanlime** [comment]
Fix implemented, will comment again when it's released.

**Comment by fasterthanlime** [comment]
Alright, the fix is available both in the [build used for self-update](https://broth.itch.ovh/itch-setup) and for initial install on https://itch.io/app - can you try again? Thanks 🌟

**Comment by TheSHEEEP** [comment]
Works like a peanut oiled charm.
