### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by dfcuellar123** [itchio/itch#2110]
Dear itch app team, 
![itch](https://user-images.githubusercontent.com/12161029/45463779-3cd8dc80-b6d3-11e8-8ef5-b968c3ffa844.PNG)

**Comment by fasterthanlime** [comment]
Hey David,

Did those just disappear overnight? Or did you 1) reinstall your system 2) move your library 3) install itch recently for the first time?

The itch app is not (yet) able to detect games that were downloaded directly from the website.

Also, your screenshot shows itch v23. Please install the latest from: https://itch.io/app

If you install games with itch v25, you can:

  - Install games on an external drive (usb stick, hdd, etc.)
  - Move your library
  - Reinstall your system
  - etc.

and you'll be able to import those games you've installed with the app.

For games installed via the website, sorry - there's no way to add them for now.
