### ISSUE TITLE
v25 breaks manifest action containing "console = true"

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#2111]
We have a manifest action with:
```
[[actions]]
name = "Launch Server"
path = "server/Simbox.Server.exe"
console = true
```

As of v25 this action no longer launches the app properly -- I'm not sure if it's because the software notices the absense of a console and closes itself, or some problem with itch. Everything works fine if instead if we have the action run a batch script runs the executable with "start" (pictured in the screenshot here)

The workaround is very little trouble for us but I thought I'd report this in case that's a bug in the console 
mode.
![image](https://user-images.githubusercontent.com/527158/45479448-709d1c00-b73e-11e8-9acb-3f00d3eb7bdf.png)

**Comment by fasterthanlime** [comment]
I can confirm, I definitely left the console option for a "later update" but haven't got around to it before v25 release.

**Comment by fasterthanlime** [comment]
butler v14.6.0 will roll out soon, it supports the `console` attribute on Windows.

*note: butler is used by the app to launch games - you don't have to push a new build or anything. You can see the version of butler the app currently uses in the Preferences*
