### ISSUE TITLE
DMG files with APFS partitions can't be extracted

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2112]
When installing https://radicaldreamland.itch.io/esc, the .DMG is just copied to the install folder instead of being extracted.

![image](https://user-images.githubusercontent.com/7998310/45491932-3c8c2000-b76b-11e8-8ef8-5ac00dc5a567.png)

Note that `7za x` can't extract it, but `7z x` can (16.02, installed view homebrew)

**Comment by fasterthanlime** [comment]
It looks like that DMG is an APFS archive. I'm not holding my breath though, a request has been opened since June of 2017: https://sourceforge.net/p/sevenzip/feature-requests/1318/

**Comment by retropipes** [comment]
Is there any reason we can't leverage `hdiutil` and the like for this sort of thing - seeing as we have to support OS-specific quirks anyway?
