### ISSUE TITLE
Updates Aren't Detected on Restricted Game when Owner but not Admin

### ISSUE THREAD

**Issue by itsmichael** [itchio/itch#2115]
Clarification: "Owner" in this case means that the account owns a copy of the game. In this particular instance, this is done with a download key, since the game page is restricted.

**Game ID**: 273557
**OS**: Windows 10 Pro 64-bit, all updates installed
**Remembered Accounts List**: JacobGrand

**Reproduction Steps**:
1. Create game on itch.io using account A.
2. Mark it as restricted.
3. Push a build using butler _(I do not know if using butler here vs. the web interface makes a difference)_.
4. Give a download key to account B.
5. Account B claims the key.
6. Install the itch app.
7. Login to the itch app with account B.
8. Download and install the game.
9. Push a new build using butler.
10. Right-click on the game in the itch app and select the update check option.
11. The itch app will report that there are no updates, even though there is a new build available.
12. Use account A to give admin access to the game to account B.
13. Go back to the itch app, which is still logged into account B, and right-click on the game and choose the update check option.
14. The itch app will now detect that there is an update.

**Additional Information**:
Even if account B is not an admin, they still see the most recent build if they open the version change window. Account B can also manually switch to the most recent build and successfully download/install it, without admin access.

Admin access appears to only affect the update check.

**Comment by fasterthanlime** [comment]
Thanks, that was indeed a real bug (and a pretty silly mistake too!)

You can see the fix here if you're curious:

https://github.com/itchio/butler/commit/7ac84b75f4c24225b32254dfd4aacc515ecf8ee1

butler v14.5.0 will be rolled out soon, the app will automatically update to it.
