### ISSUE TITLE
itch app fails silently on linux if it does not find libgconf-2.so.4

### ISSUE THREAD

**Issue by caranha** [itchio/itch#2121]
Installed itch on a brand new ubuntu, but it was not launching.

Calling the app straight from the installer or .itch/itch was failing silently. I noticed that .itch/itch called .itch/app-25.1.0/itch, and trying to run THIS directly finally gave me the "libgconf-2.so.4 not found" error message. Apt-getting the library solved the problem.

This error probably should be given by .itch/itch or, even better, by the installer.

Cheers!

**Comment by ghost** [comment]
thanks for posting this problem including the workaround! i can confirm this problem on a fresh ubuntu 18.04 minimal installation + restored /home directory. installed worked, but itch didnt start or "did not showed up" after installation.

after installing the libgconf-2 it worked as expected.

`sudo apt install libgconf-2-4`

**Comment by fasterthanlime** [comment]
Quick update: I'm looking at shipping libgconf-2-4 directly with itch. Thanks for posting the workaround in the meantime!

**Comment by fasterthanlime** [comment]
Closing this as it shipped with v25.3.0 and I've had confirmations that it works fine, on top of my personal testing :)
