### ISSUE TITLE
"Check for updates" doesn't check for v25.0.0

### ISSUE THREAD

**Issue by tobiasvl** [itchio/itch#2123]
I'm using itch v23.6.3. When I click "Check for updates", it tells me "Your itch is up-to-date!" even though v25.0.0 is released.

This is on Windows 10.

**Comment by fasterthanlime** [comment]
That's true! And also on purpose.

itch v23 used Squirrel.WIndows and Squirrel.Mac to self-update. itch v25 uses itch-setup to self-update.

I've considered providing an automatic upgrade path but after much deliberation, have decided not to provide one. v25 is almost entirely new code, having one *clean* initial install seems like the safest way to go.

**Comment by tobiasvl** [comment]
Have you considered deprecating v23 at some point, and/or making a new v23 release with a notification that v25 is available but that the user has to upgrade manually? I can easily see this resulting in lots of people staying on v23 indefinitely since they assume the app self-updates.

**Comment by fasterthanlime** [comment]
> Have you considered deprecating v23 at some point, and/or making a new v23 release with a notification that v25 is available but that the user has to upgrade manually?

We have, it is done! It appears as a banner on the website, when viewed from a version of the app that's older than v25:

![screenshot at 2018-09-17 11-09-32](https://user-images.githubusercontent.com/7998310/45614594-55961900-ba6a-11e8-8fbd-ee00e3466435.png)

I agree that some users will stay on v23 longer this way, but I'm ok with that - it leaves us more time to deal with the new v25 issues before everyone is on it.

**Comment by tobiasvl** [comment]
Ahaaa, nice. I hadn't actually checked the itch.io front page from inside the app, sorry!
