### ISSUE TITLE
"Finalizing installation" can get stuck indefinitely

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2125]
From a support ticket:

> but now it is stuck since several hours - in the window the app opened - with the text
>
> "*finalizing installation* (right next to the still rotating loading circle)
and below the connection infos *2.7 MiB / 4.6 MiB @ 591 KiB/s - 3 seconds*"

I'm curious what could cause this. I'm thinking of using a proxy (or maybe chrome settings) to throttle the connection speed, and then cut the connection in the middle. I think it should just error out, possibly retry - at any rate, it really shouldn't just keep displaying the progress indefinitely.

This is not a problem for game installs, self-updates, prereqs installs etc. as those are downloaded with butler and have httpkit's full range of timeout detections. But those dependencies are installed via broth, so, that's node.js for you.

**Comment by Davpyu** [comment]
me too but on ubuntu 18.04, stuck on finalizing installation and with 4.4 MiB / 7.6 MiB @ 26 KiB/s - 2 minutes. yeah, im waiting this 3 hours but still stuck on there.
is there any solution?

**Comment by fasterthanlime** [comment]
I still have no idea what could be causing this, btw.

@InitalDevil If you close all instances of the app (you can probably just `killall itch` from a terminal) and launch it again, does it still happen? Or was it a one-time freak occurence?

**Comment by B-Eyes** [comment]
I'm also having the same issue, Win7 Ultimate 64 bit.  "Finalizing installation... 6.0 MiB/ 7.7 MiB".   Even after killing all instances in the task manager, and then restarting the installer, it downloads normally up to 6.0 MB and then gets stuck again.  Three times, same result every time.

**Comment by fasterthanlime** [comment]
@B-Eyes any third-party antivirus software?

Can you run & screenshot this https://fasterthanlime.itch.io/itch-diag ?

**Comment by B-Eyes** [comment]
Using Avast! antivirus, free version, updated, no exclusions.

![image](https://user-images.githubusercontent.com/44711999/47976185-d939b280-e076-11e8-929c-16a9055e2f4f.png)

**Comment by fasterthanlime** [comment]
This was due to incorrect error handling of node.js streams, it was closed in https://github.com/itchio/itch/commit/2556ce705f13b0fb78ea614cabd89c313eb1b38f#diff-04f53eb202fbb534555999f8fcf888a6
