### ISSUE TITLE
Itch app launch issue on latest Ubuntu 18.04

### ISSUE THREAD

**Issue by tomcashman** [itchio/itch#2132]
Itch app didn't launch at all on Ubuntu 18.04. When I tried command line I got this error:

`./itch: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
`

Resolved with
`sudo apt-get install libgconf-2-4`

**Comment by fasterthanlime** [comment]
Duplicate of https://github.com/itchio/itch/issues/2121
