### ISSUE TITLE
Hindi language Translation [Weblate]

### ISSUE THREAD

**Issue by ask6155** [itchio/itch#2133]
### Hindi Translation

I'd like to start translating for Hindi

It is one of the least translated languages for software!
I thought I could start here.
There was no Hindi section so I guess no one ever did it!
I'm a native speaker and I am ready to take on this task!

**Comment by fasterthanlime** [comment]
Hey @ask6155!

  * I made you a translation manager on Weblate
  * I added an empty Hindi translation & an entry in the list of languages available in Preferences
    * (it might not show up in the current version of the app but it'll show up in the next release)
  * You can start translating at https://weblate.itch.ovh/projects/itch/itch/hi/

**Comment by ask6155** [comment]
Thanks!
But I had a question...
What if there's a word which doesn't have a word in Hindi?
should I just spell it out?

**Comment by fasterthanlime** [comment]
> What if there's a word which doesn't have a word in Hindi?

Do you have any in mind? Ideally you'd find a way to convey the meaning!

Weblate has a "glossary" feature, so you can make up a Hindi word/series of word for a commonly used word in the English translation, and use it throughout your translation.

**Comment by ask6155** [comment]
ok!

**Comment by ask6155** [comment]
@fasterthanlime 
I have 2 questions:
1. What should I do with 

> {{stuff}} stuff

should I also translate {{stuff}}?

2. I didn't get the context of 

> to install

does it mean to install(this)?

**Comment by fasterthanlime** [comment]
1. these don't get changed at all - they're `{{stuff}}` in every language. If you change them the translation strings wont' work correctly!

2. Strings like "to install" or "to update" are "reasons for downloading". They go in a sentence like "Downloaded 12 minutes ago, to update"

**Comment by ask6155** [comment]
Thanks! That would save a lot of my time!
