### ISSUE TITLE
Window resizes when ANYTHING is clicked

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#2138]
Just installed v25 and as the title says, when I click anything at all, it resizes the window. I would like to be able to have it set on half my screen like I typically do with most apps, but it keeps re-centering and resizing to the default when I click something. :(

**Comment by fasterthanlime** [comment]
Can I get a few more details on your system? Which OS, and, if it's Linux, which DE/WM?

**Comment by TangentFoxy** [comment]
Windows 10

**Comment by fasterthanlime** [comment]
Cool, I'm able to reproduce on Windows:

  * Start itch app
  * Drag window to left half of screen
  * Click "Library"
  * Window snaps back to previous position

**Comment by TangentFoxy** [comment]
Exactly what I'm experiencing (except dragging to right but that's no appreciable difference). Thank you!

**Comment by fasterthanlime** [comment]
v25.2.0 is out, doesn't have that problem anymore o/
