### ISSUE TITLE
Windows 10 - Setup file labeled as malicous file

### ISSUE THREAD

**Issue by denniskaselow** [itchio/itch#214]
Windows 10 doesn't like the setup file. Doesn't trust certum.pl I'd guess?

![windows10](https://cloud.githubusercontent.com/assets/1937607/11917996/bb3b831a-a71e-11e5-9b2a-ed3e637e4553.png)

**Comment by fasterthanlime** [comment]
We've had a lot of reports of that :(

> Doesn't trust certum.pl I'd guess?

That's a possibility. Another is WinDefender monitoring itch.exe and realizing it calls `reg.exe` (to register the `itchio://` protocol) and `wmic` (cf. diego: https://github.com/itchio/itch/blob/master/docs/diego.md), both of which could be considered malwarey behavior?

I want to make at least the latter opt-in with an explicit dialog, but that warning was there since day 1 and I don't think their automatic system will care..

I flagged a complaint on Microsoft's security website a few days ago, we'll see what happens.

**Comment by fasterthanlime** [comment]
@denniskaselow @chuglydude Are you still experiencing this issue with 0.12.3 or higher? I've had some reports that people didn't see that warning anymore with the 0.12 series.

**Comment by ghost** [comment]
nope i still get the warning

```
  From: Amos Wenger <notifications@github.com>
```

 To: itchio/itch itch@noreply.github.com 
Cc: Ethan Klein ethansklein@yahoo.com
 Sent: Saturday, January 9, 2016 10:26 PM
 Subject: Re: [itch] Windows 10 - Setup file labeled as malicous file (#214)

@denniskaselow @chuglydude Are you still experiencing this issue with 0.12.3 or higher? I've had some reports that people didn't see that warning anymore with the 0.12 series.—

**Comment by denniskaselow** [comment]
I'm no longer experiencing the issue. The app now starts and I can log in.

But I'm also not getting the issue with the old file (0.10.4) anymore.

**Comment by denniskaselow** [comment]
After your first answer, I installed the certum-Certificate; which didn't change anything. It's possible that the only thing missing was a restart. But I've uninstalled the certificate again and restarted but I'm still not getting the initial 'Malicious File' warning for the old file. I've got no idea what windows is doing...

These are the certificates of certum that are still remaining for me, and I think those are the standard certificates (but I'm not sure).

![certumcerts](https://cloud.githubusercontent.com/assets/1937607/12220857/75912570-b783-11e5-88f1-9c3fe1df4c11.png)

@chuglydude Could you check if you have the same certificates or if I have to uninstall more of them to get Windows back to where it was before I installed the certificate?
Windows -> Run -> certmgr.msc -> Action -> Find certificates -> Enter certum in the contains-input

**Comment by leafo** [comment]
Potentially related error after downloading on edge with windows 10: 

![](http://leafo.net/shotsnb/2016-02-01_03-23-11.png)

**Comment by Deozaan** [comment]
I don't know if any of this will help, but here goes:

I noticed in your [Itch documentation](https://docs.itch.ovh/itch/master/installing/windows.html) that your signature is using SHA-1. [SHA-1 signed certificates are being deprecated ASAP by Microsoft](https://blogs.windows.com/msedgedev/2015/11/04/sha-1-deprecation-update/) and other companies, and could be related to why you're having this issue. Even though SHA-1 isn't set to be deprecated until next month (according to the link above), [it's already causing problems for some other software developers](https://www.foobar2000.org/fuckmicrosoft) (be sure to see the forum thread for more details).

Also, be aware that even if **your** signature is SHA-256 but someone, somewhere in the signing chain uses SHA-1, the entire thing is considered SHA-1 and therefore invalid/rejected.

**Comment by fasterthanlime** [comment]
@Deozaan Ah, thanks for the additional info. I knew certum.pl was going to be a temporary solution anyway, guess we'll have to give our share to the certificate mafia sooner or later.

**Comment by Deozaan** [comment]
@fasterthanlime Maybe try https://letsencrypt.org/ ?

**Comment by fasterthanlime** [comment]
@Deozaan as far as I know, that's only for SSL/TLS, not Authenticode :(

**Comment by Deozaan** [comment]
@fasterthanlime Ah. Shows you what I know about these things. :)

**Comment by fasterthanlime** [comment]
> Also, be aware that even if your signature is SHA-256 but someone, somewhere in the signing chain uses SHA-1, the entire thing is considered SHA-1 and therefore invalid/rejected.

I should've read that more closely. our certum.pl certificate chain uses SHA-1. ~~Looks like they provide [cert replacement for free](https://www.certum.pl/certum/414648.xml), going to try that.~~ Won't be buying from them again ~~once the cert expires though..~~

(Nevermind, the free exchange is for SSL certs, not code-signing certs.)

**Comment by Soulflare3** [comment]
Running the most recent installer (v18.9.0):
![Smartscreen Error Windows 10](http://i.imgur.com/KQQnHdX.png)

I'm on the Windows 10 Anniversary update (1607).

**Comment by fasterthanlime** [comment]
Well, now it's green so that's definitely an improvement!

Not sure what the next step to take is here.

**Comment by Soulflare3** [comment]
That should be caused by my windows theme, ~~which should also be the same case for the red dialog above~~. User's chosen accent color.

Actually, looks like his color is purple, so showing the accent color instead of red would definitely be preferred.

 ![Accents](http://i.imgur.com/cuV261C.png)

**Comment by fasterthanlime** [comment]
@Soulflare3 good point — my research shows the same dialog in blue

However, it's still a better dialog than this one:

![](https://cloud.githubusercontent.com/assets/1937607/11917996/bb3b831a-a71e-11e5-9b2a-ed3e637e4553.png)

The `Run Anyway` choice is now a button, and it calls it an `unrecognized app` instead of a `malicious file`. From what I can tell, since this code signing certificate is new, there's reputation that has to build up for a while before this warning disappears. Time will tell!

**Comment by Soulflare3** [comment]
@fasterthanlime I believe that would be the most likely scenario.

From a quick search to verify:

> Once this is done, the SmartScreen will continue to warn about the application until the certificate develops a reputation. 
> *P.S. The goal of the Application Reputation experience is to warn users, when appropriate, that a downloaded application has not yet established a reputation. [MSDN Blogs](https://blogs.msdn.microsoft.com/vsnetsetup/2013/01/09/windows-smartscreen-prevented-an-unrecognized-app-from-running-running-this-app-might-put-your-pc-at-risk/)

So that second one should definitely go away over time, and then it looks like this thread will be solved.

**Comment by Sentinelau** [comment]
Windows 7 had no problems installing it with version 18.9.0.0

**Comment by fasterthanlime** [comment]
Haven't had any reports of that for a while, our new code signing certificate seems to be working well!
