### ISSUE TITLE
Visual C++ 2013 prerequisite multiple installation problems

### ISSUE THREAD

**Issue by IoriBranford** [itchio/itch#2142]
## Procedure
1. Use itch v25 on Windows 7 64-bit
2. Install [Demonizer](https://ioribranford.itch.io/demonizer) demo for Win64 `demonizer-demo-win-64.zip`
3. Try to launch game

## Issues
1. DLLs included with the game are disregarded
2. 32-bit ("x86") version of MSVC++ 2013 redistributable is auto-detected as a prereq for the 64-bit ("x64") game exe
3. The prereq installation is very slow, even after 15 minutes still not complete, but the disk is mostly idle (and mine is an SSD)
4. Each cancel and retry leaves behind installation processes `butler.exe`, `itch.exe`, `vcredist_x86.exe`

![image](https://user-images.githubusercontent.com/7191895/46067705-57c43b80-c12c-11e8-8c68-281644e14867.png)

**Comment by fasterthanlime** [comment]
Hey, thanks for the report, I'm going to look into it.

While I look, you might want to switch the whole page to "Paid" (instead of $0 or Donate), and mark the demo files as demo (the checkboxes will appear when you switch to "Paid")

**Comment by fasterthanlime** [comment]
Quick update: I've fixed most of these issues, will release fixes soon:

![image](https://user-images.githubusercontent.com/7998310/46072143-e616dc80-c181-11e8-816c-da52a3ec3c1b.png)

I'm not entirely sure why `vcredist_x86.exe` would hang forever for you, though. That's unfortunate :( Did an UAC prompt pop up?

**Comment by fasterthanlime** [comment]
Another quick update: I've been testing with Demonizer, looks like the latest win32 demo you uploaded is missing some things ;)

![image](https://user-images.githubusercontent.com/7998310/46072228-20807980-c182-11e8-97bc-31935d4bb051.png)

**Comment by IoriBranford** [comment]
Thank you. There was never a UAC prompt.

I could not repro the demo missing its assets.

**Comment by fasterthanlime** [comment]
> There was no UAC prompt.

What do your UAC settings look like?

If you enable the itch.io sandbox, is there a UAC prompt after clicking "Continue" in the first-time setup dialog? (don't forget to disable it if it ends up not working).

> I could not repro the demo missing game files though.

I just tried to repro again and wasn't able either. Hmm.

> Thank you.

butler v14.12.0 is out, and it fixes those issues you brought up (except the UAC / prereq install getting stuck). You can force your itch app to upgrade to it in Preferences => Advanced => Components:

![image](https://user-images.githubusercontent.com/7998310/46073483-4e1af200-c185-11e8-9c86-94990fa353e3.png)

...otherwise it'll just update itself to it eventually (it checks shortly after startup, and every ~2 hours after that, with some variation)

**Comment by IoriBranford** [comment]
> What do your UAC settings look like?

Default setting:
![image](https://user-images.githubusercontent.com/7191895/46073945-1edf9300-c13b-11e8-93a0-25869559614b.png)

> If you enable the itch.io sandbox, is there a UAC prompt after clicking "Continue" in the first-time setup dialog? (don't forget to disable it if it ends up not working).

With sandbox enabled trying to run any build gets this: https://dale.itch.ovh/7C0Vknw6xmP5bPo4cPP8pDQr3c6m9csdhDldeIZafD5uonAFvuzORr9PGkEhFf88

But without sandbox, the first two issues are fixed so thanks.

**Comment by fasterthanlime** [comment]
> With sandbox enabled trying to run any build gets this:

Huh, `The stub received bad data.` is a message I've never seen before! The sandbox has limited support on Windows 7 anyway but.. I didn't expect that. According to the logs, the sandbox setup worked fine, so, I'm not sure what's going on.
