### ISSUE TITLE
[win32] Crash report for v0.10.4

### ISSUE THREAD

**Issue by lonelydarksider** [itchio/itch#215]
Crash log:

```
Error: EPERM: operation not permitted, open 'C:\Users\Parham\AppData\Roaming\itch\bin\7za.exe'
    at Error (native)
```

**Comment by lonelydarksider** [comment]
Can't start the client itself

**Comment by fasterthanlime** [comment]
@lonelydarksider is there a file named `7za.exe` in that directory? What happens if you double-click on it?

Can you create an empty text file next to it?

**Comment by fasterthanlime** [comment]
Also, if there's a `7za.exe` file, what size is it? (find out with right click on the file -> properties)

**Comment by ghost** [comment]
@fasterthanlime I just had this issue on the latest release (0.12.2). I have an `itch` folder in my AppData folder, but no `bin` folder inside it.

**Comment by fasterthanlime** [comment]
dupe of #353, 0.12.3 is coming
