### ISSUE TITLE
Before using verdict, makes sure all files are still there

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2152]
In fact, are we even checking the install folder still exists on launch?

**Comment by dos1** [comment]
All the files? Wouldn't that break some games like Doki-Doki Literature Club that delete some of its files as part of the gameplay?

**Comment by fasterthanlime** [comment]
All the files listed as launch targets :) So mostly executables.

**Comment by fasterthanlime** [comment]
> In fact, are we even checking the install folder still exists on launch?

We are, btw:

https://github.com/itchio/butler/blob/c64740d2d22e9cbf2cb86c93c4a3fb0eb899e8c6/endpoints/launch/launch.go#L45-L51
