### ISSUE TITLE
Stop creating a desktop shortcut repeatedly

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#2153]
I don't mind that one was automatically created on initial install, because I can delete it and be done with it...

Except it keeps being recreated.. ):

**Comment by fasterthanlime** [comment]
> Except it keeps being recreated.. ):

That's so you don't forget about us!

Just kidding :) It's an actual bug. Shortcuts get created unconditionally in post-install: https://github.com/itchio/itch-setup/blob/master/native/native_windows.go (so, after initial install and each upgrade).

I guess there should be a flag to not update the shortcut if it was deleted. There's already logic for that for pinned shortcuts.

**Comment by TangentFoxy** [comment]
:heart:
