### ISSUE TITLE
"platform" field for manifest actions needs to be documented

### ISSUE THREAD

**Issue by lsliwko** [itchio/itch#2155]
It seems that os field should filter for matching Operating System as in here:
https://github.com/itchio/itch/issues/1587

I am using Itch 25.2.0. On Mac OS X it still shows all options, .itch.toml as follows:

[[actions]]
name = "Play (Windows)"
path = "aof-start-windows.bat"
os = "windows"

[[actions]]
name = "Configuration (Windows)"
path = "aof-start-windows.bat"
args = ["-config"]
os = "windows"

[[actions]]
name = "Play (Linux)"
path = "aof-start-linux.sh"
os = "linux"

[[actions]]
name = "Configuration (Linux)"
path = "aof-start-linux.sh"
args = ["-config"]
os = "linux"

[[actions]]
name = "Play (Mac OS)"
path = "aof-start-macosx.command"
os = "macos"

[[actions]]
name = "Configuration (Mac OS)"
path = "aof-start-macosx.command"
args = ["-config"]
os = "macos"

**Comment by aaronfranke** [comment]
The code I provided in my feature request was just an example. The actual keyword is `platform`.

```
[[actions]]
platform = "linux"
name = "play"
path = "aof-start-linux.sh"
```

It does still need [documentation](https://itch.io/docs/itch/integrating/manifest-actions.html) so you can leave this issue open for now. CC @fasterthanlime

**Comment by lsliwko** [comment]
Alright, thanks!

**Comment by fasterthanlime** [comment]
> It does still need [documentation](https://itch.io/docs/itch/integrating/manifest-actions.html)

It does!

If someone wants to contribute documentation before I come around to it:

  * The repository for https://itch.io/docs/itch is https://github.com/itchio/itch-docs
  * The implementation for Platform filtering is https://sourcegraph.com/github.com/itchio/butler@4dbdb0829e70b9987193b13c8772204ec06cdfc9/-/blob/endpoints/launch/manifest/manifest.go#L19 (sourcegraph makes it easy to look around code)

**Comment by retropipes** [comment]
I attempted to handle it by creating [PR 2 in itch-docs](https://github.com/itchio/itch-docs/pull/2).

**Comment by fasterthanlime** [comment]
I've merged @wrldwzrd89's PR, https://itch.io/docs/itch/integrating/prereqs/ now mentions platforms. 🌟
