### ISSUE TITLE
AirConsole games don't seem to work

### ISSUE THREAD

**Issue by joemicmc** [itchio/itch#2165]
### Details
- Version: itch @ 25.3.0
- OS: Windows 10
- Steps: Launch html5 game (https://8bitape.itch.io/dungeoncrawl) from itch app

### Description
When the game is launched, websocket connections are closed:  
`WebSocket connection to 'wss://server-url' failed: WebSocket is closed before the connection is established.`

The game uses websockets to send messages from the screen to your smart phone.

If I load the game with my browser of choice, then everything is fine and dandy:

![image](https://user-images.githubusercontent.com/7323103/46869667-70b73700-ce24-11e8-8314-4a842e2930f5.png)
![image](https://user-images.githubusercontent.com/7323103/46869671-744abe00-ce24-11e8-907c-295b61e242c4.png)

Does the itch app browser support websockets?

**Comment by fasterthanlime** [comment]
> Does the itch app browser support websockets?

I had a doubt (since v25 upgraded several electron versions, and serves web games over another protocol, and ships with with a CSP, and...), but yes, it does!

![image](https://user-images.githubusercontent.com/7998310/46896220-5a3cca00-ce7c-11e8-867a-6e7b5be8bd3e.png)

See https://fasterthanlime.itch.io/ws-test

---

It looks like airconsole is doing a *lot* of stuff behind the scenes, one of them seems to break it.

(Note: that error message in particular is shown when *client code* calls `socket.close()` too early, so something's definitely going on).

**Comment by joemicmc** [comment]
Thanks for quick reply. I raised an issue with AirConsole: https://github.com/AirConsole/airconsole-api/issues/53

As a workaround I'm displaying a splash screen of sorts if launched from the app:

![image](https://user-images.githubusercontent.com/7323103/46906486-33be7380-cefc-11e8-8a34-2472bc5ed6d7.png)

**Comment by fasterthanlime** [comment]
I replied over there too!

**Comment by joemicmc** [comment]
Looks like they closed related issue: 

> `itch-cave://` is a problem. We require everything to be served over https or http.

Not sure what that means for this issue though!

**Comment by fasterthanlime** [comment]
> `itch-cave://` is a problem. We require everything to be served over https or http.

This issue looks like a dead-end then :(

There's no good alternatives for us:

  * Spinning up an http server would lock games out of some browser features (that only work with https)
  * Spinning up an https server is.. not really feasible (it involves generating a key pair and trusting it in that browser only, I've had issues with that in the past)
  * Intercepting https requests to a certain host also proved problematic in the past

Having a custom protocol is the only way for us to support various HTML5 game flavors out there. I'm curious why the AirConsole feels they have to restrict their games to http and https only (I'm not convinced yet that it's related to the actual error).

**Comment by fasterthanlime** [comment]
I replied again over there.
