### ISSUE TITLE
itch github wiki page is outdated 🕮

### ISSUE THREAD

**Issue by saildata** [itchio/itch#2166]
The itchio/itch [wiki page](https://github.com/itchio/itch/wiki) is outdated - readers are directed to the "/docs" folder in the main repo, which doesn't exist. 

This should be changed to reference the separate repository [itchio/itchdocs](https://github.com/itchio/itch-docs) where the docs live.

**Comment by fasterthanlime** [comment]
Ha, I wasn't aware someone had created a Wiki page for it!

I just edited it to change the link. (Note that anyone can edit it, apparently)
