### ISSUE TITLE
Error during install on Ubuntu 18.04

### ISSUE THREAD

**Issue by The1Krutz** [itchio/itch#2169]
While following [these instructions](https://itch.io/docs/itch/installing/linux/) attempting to install itch client on Ubuntu 18.04, got the following error:

> $ ./itch-setup 
> 2018/10/16 20:57:53 App name specified at build time: itch
> 2018/10/16 20:57:53 Locale:  en-US
> 2018/10/16 20:57:53 Initializing (itch) multiverse @ (/home/thomas/.itch)
> 2018/10/16 20:57:53 No multiverse information yet
> 2018/10/16 20:57:53 Initializing installer GUI...
> 2018/10/16 20:57:53 Loading image resources...
> 2018/10/16 20:57:53 Setting up progress bar...
> 2018/10/16 20:57:53 Positioning and showing window...
> 2018/10/16 20:57:54 Will install version 25.3.0
> 2018/10/16 20:58:05 [info] having network troubles...
> 2018/10/16 20:58:05 [info] Sleeping 0 seconds then retrying
> 2018/10/16 20:58:17 [info] having network troubles...
> 2018/10/16 20:58:17 [info] Sleeping 1 seconds then retrying
> 2018/10/16 20:58:18 Fatal error: Get https://w3g3a5v6.ssl.hwcdn.net/build/109986/414150-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1539748717&Signature=t4dThDfvwPVlkmHhlo8QriegWcoxumPp0%2FRofuFLOA47T0mf9QaBNmLpOgAiZYh9Pj1xMvqb3aAxrAcr5P2ECFh%2Bb2eVdGVYa%2F9hC4Fyze3ZNP%2BXSFbhctYLtzO%2FW8aUgpntw3l2XQsysxy9hSmHLTGS4lECrq2BjwgAof7sTXeq5bvMzTP%2BppEiS1ySe1NAHuf7zZ21TK5DX%2FqJ12eXBDwDRy06KycKI9i9aKaHbXq1nHmDc5P9LC4AHwu9p11DnHIVgSPuYmn3orC39gx9umT5ce5ER6L0MTUAsY9abpXbw6RDASTbFmFFpCP4DihhBM1lx7HiOiwNOtMShwgGSQ==&hwexp=1539749007&hwsig=303c2a3cb40c713d738638588de2c8da: unexpected EOF
> htfs connect
> htfs.Open (initial request)
> while opening remote signature file
> Warm-up error

Tried this a few times with no luck :(

**Comment by fasterthanlime** [comment]
What country are you installing from?

Do you sometimes experience network problems from where you're installing it? (sites not loading, etc.)

These kinds of errors often turn up to be network-related, not actual bugs (see https://github.com/itchio/butler/issues/166 ) - I'd be really happy if they were actual bugs, because then I could fix them for everyone :(

**Comment by The1Krutz** [comment]
I'm installing from the US, and have pretty reliable internet.

That said, I tried applying updates and rebooting, and now everything works fine. Seems to have been something on my end, not a bug.

Thank you!
