### ISSUE TITLE
Not all OS-specific download choices are shown

### ISSUE THREAD

**Issue by ghost** [itchio/itch#2174]
Edit: itch version 25.3.0, butler 14.13.0 but updating, itch-setup 1.12.0

I am running Debian testing 64-bit (actually, PureOS running GNOME 3.30.1; same thing since they basically just mirror upstream, though) . As shown here: ![windows-only](https://user-images.githubusercontent.com/634501/47180131-021f2100-d2dd-11e8-988f-13611e716d4d.png) the game I want to install has a little penguin icon indicating there is a Linux-compatible download, but the dropdown only has the Windows executable marked.

I think DDLC is RenPy so it very well might be just one package for all OS' (some Python scripts) but in that case the file should be labelled 'OS-agnostic' or something like that.

**Comment by fasterthanlime** [comment]
Hi!

The name of the upload on the page is "DDLC (Windows)", even though it's tagged for both Windows & Linux:

![image](https://user-images.githubusercontent.com/7998310/47283683-9c84aa80-d5e4-11e8-9c88-d96cf1589d7a.png)

Feel free to leave a comment to the developers on https://teamsalvato.itch.io/ddlc so they change the upload name, if you feel strongly about it!
