### ISSUE TITLE
Unexplained "Timed out while connecting to butlerd"

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2180]
Report:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Message
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Dear itch app team, I downloaded the app last night and when I opened it this morning it said it wasn`t responding. Then I deleted it and re-downloaded it, and it said the same thing.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Setup did not complete successfully:
Error: Timed out while connecting to butlerd
    at Timeout.setTimeout [as _onTimeout] (C:\Users\redacted\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:15126:28)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

I can't really tell what's going on without more logging, which should be feasible - setup just needs to log into a dual log writer: memory + main logger.

**Comment by fasterthanlime** [comment]
(I'm suspecting bad AV no cookie but hard to tell right now)

**Comment by SebastianPfliegel** [comment]
I have the exact same problem on Linux (openSUSE Tumbleweed). Even removing `~/.itch` and rerunning `itch-setup` didn't help. The weird thing about this I had this issue earlier and at most times after some time or reboot it did the trick. So I assumed there was just something offline at itch.io end. Now I always get this error. Happy to help investigating this.

**Comment by fasterthanlime** [comment]
@SebastianPfliegel thanks for offering to help!

I'd like you to:

  * Make sure you have v25.4.0 installed (it was released very recently, so you'll probably need to run itch-setup)
  * Launch the app, wait for it to get in the error condition
  * Upload a screenshot of the app
  * Upload `~/.config/itch/logs/itch.txt`

(btw: butlerd is something that itch starts, it runs on your own machine, so it's not part of our server infrastructure)

**Comment by SebastianPfliegel** [comment]
[itch.txt](https://github.com/itchio/itch/files/2567251/itch.txt)

Well, another reboot did the trick. I can start and close the app without any problems. In my log file you should see the error though.

I know that butlerd is the command line interface serving itch. I simply haven't took a closer look at the error days ago.

**Comment by fasterthanlime** [comment]
> Well, another reboot did the trick. I can start and close the app without any problems. In my log file you should see the error though.

I see the error, unfortunately, logging is insufficient to determine the root cause, I'll make a note to add better logging for these cases in the future!

**Comment by BlaixenU** [comment]
yup, reinstalling works

**Comment by MassivebutterpapperCodes** [comment]
run as admin if on windows 10
