### ISSUE TITLE
expired certificate error when trying to download latest version of client from broth.itch.ovh

### ISSUE THREAD

**Issue by dgholz** [itchio/itch#2183]
I see that version 25 needs to be manually installed, but when I click on the `Start Download` link on https://itch.io/app I get an error popup:

> **Certificate error: net::ERR_CERT_DATE_INVALID**
>
> There was an error with the certificate for `broth.itch.ovh` issued by `Let's Encrypt Authority X3`.
> Please check your proxy configuration and try again.
> _If you ignore this error, the rest of the app might not work correctly._

Choosing `Ignore and continue` doesn't start the download, so I tried visiting the page in firefox and clicking on the `Start Download` link & got this error:

> broth.itch.ovh uses an invalid security certificate.
> 
> The certificate expired on Monday, 29 October 2018, 11:00 pm. The current time is Monday, 29 October 2018, 11:59 pm.
> 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by fasterthanlime** [comment]
Thanks for the report, I'm on it.

**Comment by fasterthanlime** [comment]
The certificate has been renewed, but it looks like it's taking a few minutes to propagate. I'll post again when I have confirmation it works.

note: automatic monthly renewal was already set up, but the last (early) renewal failed because of a network timeout...

**Comment by fasterthanlime** [comment]
New certificate is up and running:
 
![image](https://user-images.githubusercontent.com/7998310/47688207-85e1e300-dbe4-11e8-8072-8d57f0023317.png)
