### ISSUE TITLE
Fails to update via Linux Mint's Update Manager

### ISSUE THREAD

**Issue by RabidGuy** [itchio/itch#2193]
I get an error each time I refresh the list of software updates in my Update Manager. I'm using Linux Mint but don't know what other information may be relevant.  Here is the error message:

The repository 'https://dl.bintray.com/itchio/deb arful Release' does not have a Release file.Data from such a repository can't be authenticated and is therefore potentially dangerous to use.See apt-secure(8) manpage for repository creation and user configuration details.Failed to fetch https://dl.bintray.com/itchio/deb/dists/arful/main/binary-amd64/Packages  404  Not FoundSome index files failed to download. They have been ignored, or old ones used instead.

**Comment by fasterthanlime** [comment]
That's correct - the .deb repository has been retired.

Please see https://itch.io/docs/itch/installing/linux/ubuntu-and-debian.html for more information!
