### ISSUE TITLE
Something went wrong: http 403 error

### ISSUE THREAD

**Issue by LinArcX** [itchio/itch#2195]
Hi. i download the installer from the site and after run it, i get this weird error:
[error](https://raw.githubusercontent.com/LinArcX/Ganje/master/Images/LinArcx/Screenshot%20from%202018-11-05%2023-05-58.png)
I open the link separately in other tab in my firefox and it show me 403 error:
https://broth.itch.ovh/itch/linux-amd64/LATEST
but if i use a proxy, everything will fine.

**Comment by fasterthanlime** [comment]
Are you downloading from one of the countries blocked by Google? https://support.google.com/a/answer/2891389?hl=en

**Comment by LinArcX** [comment]
Yes. i'm from iran.

**Comment by fasterthanlime** [comment]
> Yes. i'm from iran.

That's definitely it. I'm sorry, your best bet is to go through the website and use the "Alternate download mode" for now.

**Comment by LinArcX** [comment]
Why not?
Can you fix it in near future?
Also i can't find "Alternate download mode" in itch.io. You mean direct download from website?
