### ISSUE TITLE
🏁 Feedback v23.6.3

### ISSUE THREAD

**Issue by Koyyle** [itchio/itch#2196]
Event log:

```
Error: ENOSPC: no space left on device, write
```

**Comment by fasterthanlime** [comment]
1) You're out of disk space! You need to make some room :)

2) You're running an old version of the app, you can download the latest from here: https://itch.io/app

You might want to look into the `%APPDATA%\itch\apps\downloads` folder - the v23.x app was keeping more files than strictly necessary, you can delete all those safely.
