### ISSUE TITLE
Paypal registers my payment but itch doesn't mark the game as bought

### ISSUE THREAD

**Issue by gersande** [itchio/itch#2202]
I'm not sharing the screenshot from Paypal for privacy reasons, but if anybody wants to see proof that I bought the game I'm happy to share. 

I bought a visual novel through the itch.io desktop app on OS X. The app opened the Paypal window, I successfully sent the money to the author (I even confirmed with them), but when I use itch.io in the app or the browser, it just wants me to buy the game again. There is no record of my purchase. 

I don't know what to do. This is the only "help" or bug report place I could find.

**Comment by fasterthanlime** [comment]
Hey there,

Please send an e-mail to https://itch.io/support with the purchase details:

  * Your itch.io account username
  * The game you bought
  * The Paypal transaction ID if you have it

Our support team will help you get your hands on your purchase!
