### ISSUE TITLE
Error: JSON-RPC error 12000: itch.io API error (400): invalid collection

### ISSUE THREAD

**Issue by ghost** [itchio/itch#2206]
Hello, the first thing I would like to say is that I am not a native English speaker, so I am sorry for my English.

I have a problem with the Collections part, I had a collection but I deleted it, and now I have a new one but I keep appearing the previous one and I mark this error:

Error: JSON-RPC error 12000: itch.io API error (400): invalid collection

On the other hand, when I go to the part of My Library, it appears correctly.

I attach captures of both things.

<a href="https://ibb.co/mpjDxA"><img src="https://preview.ibb.co/dDUP4q/01.jpg" alt="01" border="0"></a>

<a href="https://ibb.co/cFsGHA"><img src="https://preview.ibb.co/mVRbHA/02.jpg" alt="02" border="0"></a>

I hope you can help me. Thanks.

**Comment by fasterthanlime** [comment]
> I had a collection but I deleted it,

Did this happen recently? Collections are cached for 30 minutes, so it might take a little while for it to stop showing up in the collections tab.

**Comment by ghost** [comment]
> > I had a collection but I deleted it,
> 
> Did this happen recently? Collections are cached for 30 minutes, so it might take a little while for it to stop showing up in the collections tab.

Hello, thanks for answering. It's been happening for about two weeks.

**Comment by katherinehackworth** [comment]
Has there been any update on this issue? Having it myself over a year later.

**Comment by ghost** [comment]
> Has there been any update on this issue? Having it myself over a year later.

The only thing that worked for me was to uninstall and clean all the folders, etc, from itchio, and then reinstall from scratch. And always update the application. I hope it can help you.

**Comment by katherinehackworth** [comment]
Yeah, I had to use Revo uninstaller to clear out all the data for the app. Kinda surprised because most uninstallers ask whether or not you want to keep any personal data still

**Comment by Nookie04** [comment]
> Yeah, I had to use Revo uninstaller to clear out all the data for the app. Kinda surprised because most uninstallers ask whether or not you want to keep any personal data still
And it worked?

**Comment by ghost** [comment]
> Yeah, I had to use Revo uninstaller to clear out all the data for the app. Kinda surprised because most uninstallers ask whether or not you want to keep any personal data still

And it worked?

**Comment by fasterthanlime** [comment]
> > Yeah, I had to use Revo uninstaller to clear out all the data for the app. Kinda surprised because most uninstallers ask whether or not you want to keep any personal data still
> 
> And it worked?

I have no idea what Revo uninstaller does but the offending data is in `%APPDATA%\itch\db\*`.

I have no idea why some folks are still seeing that issue, because there is logic that re-fetches all collections and finds out which ones are gone, so this really should not be happening. Deleting the database is not ideal either because then you'll have to re-import all games (although that part should be pretty smooth now).

I'm working on another versions of itch which I hope will not have the issue. I'll write tests specifically for that.

**Comment by ghost** [comment]
> > > Yeah, I had to use Revo uninstaller to clear out all the data for the app. Kinda surprised because most uninstallers ask whether or not you want to keep any personal data still
> > 
> > 
> > And it worked?
> 
> I have no idea what Revo uninstaller does but the offending data is in `%APPDATA%\itch\db\*`.
> 
> I have no idea why some folks are still seeing that issue, because there is logic that re-fetches all collections and finds out which ones are gone, so this really should not be happening. Deleting the database is not ideal either because then you'll have to re-import all games (although that part should be pretty smooth now).
> 
> I'm working on another versions of itch which I hope will not have the issue. I'll write tests specifically for that.

Thank you very much for answering. By the way, do you know anything about the integration with GOG Galaxy? The itch.io API is the only one that doesn't work for me.
I've used this one: https://github.com/Ertego/gog-galaxy-itch.io

**Comment by fasterthanlime** [comment]
I've seen that repository, the README says it's "a bit of a hack" and frankly that's an understatement :)

The recommended way to integrate with the itch client is butlerd, Playnite for example has proper integration!

**Comment by ghost** [comment]
> I've seen that repository, the README says it's "a bit of a hack" and frankly that's an understatement :)
> 
> The recommended way to integrate with the itch client is butlerd, Playnite for example has proper integration!

I didn't know Playnite, thanks for the advice!
