### ISSUE TITLE
everytime the app starts it increases the download count on the game's "analytics" 

### ISSUE THREAD

**Issue by pragmascript** [itchio/itch#221]
Everytime the app starts the download count of each installed game's analytics page
e.g. http://itch.io/game/summary/XXXXX is being increased by one.

**Comment by matiasbeckerle** [comment]
I think this happens for downloaded/installed games only. Saw the same behavior.

**Comment by fasterthanlime** [comment]
Yeah, that's not wanted behavior, let's see if we can get the app to check for updates reliably without doing that, keeping in mind that currently, the content an upload ID points to can change, which I'm very unhappy about it and we'll have to change server-side eventually. I suppose for now we could compare updated_at + the file size ?

Actually uploads don't have `updated_at` :( http://itch.io/api/1/me/game/3/uploads I guess for now we'll have to rely on file size.

**Comment by matiasbeckerle** [comment]
File size looks like a good alternative until `updated_at` become available.

`cave-store.js` line 322 queues new downloads `queue_task(record._id, 'download')`. Couldn't figure it out how to reuse the async task for "find-upload" before actually start the download :(.

**Comment by leafo** [comment]
you can also just use the id of the upload, each file has a unique id, and they only increase over time

**Comment by fasterthanlime** [comment]
@leafo When uploading something with the same name, doesn't it re-use the same id ?

**Comment by leafo** [comment]
it does not

**Comment by fasterthanlime** [comment]
ah that's very good then
