### ISSUE TITLE
🏁 Issue v23.6.3

### ISSUE THREAD

**Issue by loosegrid** [itchio/itch#2218]
Dear itch app team, when trying to download a file after purchasing through the app on windows 10, I get a windows message that says "You'll need a new app to open this itch". There seems to be no way to get Windows to recognize itch as the app to do whatever it's trying to do.
![2018-12-14 22_06_49-download mindustry by anuke - itch io - itch](https://user-images.githubusercontent.com/13005877/50000340-657fb380-ffed-11e8-9cae-d2ac607d989d.png)

**Comment by fasterthanlime** [comment]
You can download and install itch v25 from https://itch.io/app (you currently have v23, which is deprecated).

v25 correctly registers itself for `itch://` URLs. Sorry about that!
