### ISSUE TITLE
opening archive: creating zip extractor: api.itch.io: HTTP Range header not supported

### ISSUE THREAD

**Issue by retropipes** [itchio/itch#2219]
Game: Isleward (https://bigbadwaffle.itch.io/isleward)
Itch version: 25.4.0
butler version: 15.5.0
OS version: macOS 10.14.2 "Mojave"
Action at time of error: Computing space requirements pre-installation

<details>
<summary>
Error log
</summary>
`{"time":1544835805391,"level":20,"msg":"🙏 Fetch.Commons","name":"mcall"}
{"time":1544835806376,"level":20,"msg":"🙏 Fetch.Caves","name":"mcall"}
{"time":1544835806377,"level":30,"msg":"No cave for Isleward (#59398), attempting install","name":"m/reac/task/queue-game"}
{"time":1544835806385,"level":20,"msg":"🙏 Install.Locations.List","name":"rcall"}
{"time":1544835806386,"level":20,"msg":"🙏 Install.Plan","name":"rcall"}
{"time":1544835806398,"level":30,"msg":"> Planning install for Isleward - https://bigbadwaffle.itch.io/isleward"}
{"time":1544835806398,"level":30,"msg":"Picking first upload."}
{"time":1544835806399,"level":30,"msg":"  ☁ Isleward (Mac) :: Unknown size :: #720290"}
{"time":1544835806399,"level":30,"msg":"    Executable :: macOS all"}
{"time":1544835806400,"level":30,"msg":"No download session ID passed, using 6cff19d3-d0b5-4d8d-a4a9-f58ad6363082"}
{"time":1544835806876,"level":20,"msg":"🙏 Profile.Data.Put","name":"mcall"}
{"time":1544835807294,"level":30,"msg":"↝ For source (Isleward-1.1.1-darwin-x64.zip)"}
{"time":1544835807294,"level":30,"msg":"  Probing with dash..."}
{"time":1544835808163,"level":20,"msg":"  (took 869.538326ms)"}
{"time":1544835808164,"level":30,"msg":"  No results from configurator"}
{"time":1544835808165,"level":30,"msg":"  Probing as archive..."}
{"time":1544835808801,"level":20,"msg":"  (took 637.916129ms)"}
{"time":1544835808802,"level":50,"msg":"Planning failed: api.itch.io: HTTP Range header not supported\ngithub.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs/conn.go:133\ngithub.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs/conn.go:56\ngithub.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs/file.go:329\ngithub.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs.(*File).readAt\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs/file.go:473\ngithub.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/htfs/file.go:444\ngithub.com/itchio/butler/vendor/github.com/itchio/arkive/zip.readDirectoryEnd\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/arkive/zip/reader.go:482\ngithub.com/itchio/butler/vendor/github.com/itchio/arkive/zip.(*Reader).init\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/arkive/zip/reader.go:80\ngithub.com/itchio/butler/vendor/github.com/itchio/arkive/zip.NewReader\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/arkive/zip/reader.go:73\ngithub.com/itchio/butler/vendor/github.com/itchio/savior/zipextractor.New\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/savior/zipextractor/zipextractor.go:37\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.(*Info).GetExtractor\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:312\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.Probe\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:144\ngithub.com/itchio/butler/installer.GetInstallerInfo\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/installer/get_installer_info.go:80\ngithub.com/itchio/butler/endpoints/install.InstallPlan\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/endpoints/install/install_plan.go:131\ngithub.com/itchio/butler/butlerd/messages.(*InstallPlanType).Register.func1\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/messages/messages.go:1613\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:300\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:309\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/daemon/daemon.go:123\nruntime.goexit\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333\ngithub.com/itchio/butler/vendor/github.com/itchio/savior/zipextractor.New\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/savior/zipextractor/zipextractor.go:39\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.(*Info).GetExtractor\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:312\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.Probe\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:144\ngithub.com/itchio/butler/installer.GetInstallerInfo\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/installer/get_installer_info.go:80\ngithub.com/itchio/butler/endpoints/install.InstallPlan\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/endpoints/install/install_plan.go:131\ngithub.com/itchio/butler/butlerd/messages.(*InstallPlanType).Register.func1\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/messages/messages.go:1613\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:300\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:309\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/daemon/daemon.go:123\nruntime.goexit\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333\ncreating zip extractor\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.(*Info).GetExtractor\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:314\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.Probe\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:144\ngithub.com/itchio/butler/installer.GetInstallerInfo\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/installer/get_installer_info.go:80\ngithub.com/itchio/butler/endpoints/install.InstallPlan\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/endpoints/install/install_plan.go:131\ngithub.com/itchio/butler/butlerd/messages.(*InstallPlanType).Register.func1\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/messages/messages.go:1613\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:300\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:309\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/daemon/daemon.go:123\nruntime.goexit\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333\nopening archive\ngithub.com/itchio/butler/vendor/github.com/itchio/boar.Probe\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/boar/probe.go:160\ngithub.com/itchio/butler/installer.GetInstallerInfo\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/installer/get_installer_info.go:80\ngithub.com/itchio/butler/endpoints/install.InstallPlan\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/endpoints/install/install_plan.go:131\ngithub.com/itchio/butler/butlerd/messages.(*InstallPlanType).Register.func1\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/messages/messages.go:1613\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:300\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:309\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/daemon/daemon.go:123\nruntime.goexit\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333\ngithub.com/itchio/butler/installer.GetInstallerInfo\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/installer/get_installer_info.go:90\ngithub.com/itchio/butler/endpoints/install.InstallPlan\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/endpoints/install/install_plan.go:131\ngithub.com/itchio/butler/butlerd/messages.(*InstallPlanType).Register.func1\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/messages/messages.go:1613\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:300\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:309\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/daemon/daemon.go:123\nruntime.goexit\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333\ngithub.com/itchio/butler/endpoints/install.InstallPlan\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/endpoints/install/install_plan.go:133\ngithub.com/itchio/butler/butlerd/messages.(*InstallPlanType).Register.func1\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/messages/messages.go:1613\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:300\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/butlerd/router.go:309\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\t/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/daemon/daemon.go:123\nruntime.goexit\n\t/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333"}`
</details>

**Comment by fasterthanlime** [comment]
Okay, so, those are external uploads (ugh) which link to gitlab CI artifacts (double ugh) like so:

https://gitlab.com/Isleward/isleward-client/-/jobs/63742889/artifacts/raw/out/Isleward-1.1.1-win32-x64.zip

I'm fairly sure gitlab generates those .zip on the fly, so there's a reasonable explanation for not supporting range requests - however, itch v25 does require range request support.

I'd recommend letting the developer know about https://itch.io/docs/butler/

**Comment by retropipes** [comment]
Agreed - itch can't reasonably be expected to support this situation. The developer has been notified.
