### ISSUE TITLE
"update-desktop-database" not found in $PATH

### ISSUE THREAD

**Issue by AlexHoratio** [itchio/itch#2221]
Hey! I bet this has something to do with some missing library or something, but I'm getting this error in a "Something went wrong" popup when I'm running itch-setup:

``exec: "update-desktop-database": executable file not found in $PATH while updating desktop database`` 

I'm running Debian 9 with KDE Plasma 5, and it's a pretty fresh installation, hence why I suspect I'm missing something. Thanks!

**Comment by AlexHoratio** [comment]
UPDATE: Running ``sudo apt install desktop-file-utils`` installs the correct library and now things are working. Leaving this here in case anyone else runs into the same issue!

**Comment by fasterthanlime** [comment]
Ah, it might be worth gracefully skipping that part if update-desktop-database is missing. Also, I'm not sure what equivalent KDE Plasma provides?

**Comment by fasterthanlime** [comment]
Fixed in https://github.com/itchio/itch-setup/commit/053767107404c1041dae6277e42607b4f630029f, will ship soon.
