### ISSUE TITLE
if no downloads to pause, grey out 'pause downloads' button

### ISSUE THREAD

**Issue by ghost** [itchio/itch#2224]
If there are no downloads to pause, the 'pause downloads button should be greyed out'

**Comment by fasterthanlime** [comment]
I'm not sure about that one.

You might want to keep downloads paused even as you keep queuing new downloads (because you're currently on mobile internet), it's not clear to me that "having an empty download queue" should reset the state to "not paused".

**Comment by donwilkinsonart** [comment]
Ah, I think changing the button text to:

“Downloads paused” 

Would work to, because if you pause downloads and the button still says “pause downloads” it’s confusing.

**Comment by ghost** [comment]
Absolutely, fair point! Case closed.
