### ISSUE TITLE
Manage collections should be more prominent in desktop app, not hidden behind three dots

### ISSUE THREAD

**Issue by ghost** [itchio/itch#2225]
It's not immediately obvious that you can click on the three dots in the top right to get to 'manage collections'

I actually got to the manage collections page from a links somewhere else.

It would be great to feature 'manage collections' somewhere visibly on the collections page instead of behind the three dots which are so tiny and don't look visually connected to the page at hand.

**Comment by fasterthanlime** [comment]
That's a fair point.

Ideally, the app would allow editing collections natively, so this wouldn't be an issue!

Closing in favor of #1646
