### ISSUE TITLE
itch-setup app false positive? Spybot SD virus scanner

### ISSUE THREAD

**Issue by Palmsunday** [itchio/itch#2228]
Spybot - Search & Destroy
File Scanner 2.7.64.137
Log created at 2019-01-03 3:36:49 PM
Results Copyright (c) 2009-2019 Safer-Networking Ltd.

D:\SSD Downloads\itch-setup.exe
**Gen:Variant.Graftor.532430 (SpybotAV)**

Can somebody confirm this a false positive?
I scanned with Avast and it didn't come up with anything.
I will report to Spybot SD a false positive if anyone can verify.
I looked up the virus and it sounds nasty, don't want to take a chance.

**Comment by fasterthanlime** [comment]
Hi there,

Definitely a false positive. [itch-setup is open-source](https://github.com/itchio/itch-setup), built on our own CI servers and signed with our own codesigning certificate. It's not even a third-party installer program.

The VirusTotal says 1 out of 70 engines detected it as malicious, unfortunately there's not a lot more details there: https://www.virustotal.com/#/url/a21a8896138d7fa97ef1ddc9d97dfd54b2e155c0aa1ebba1d31689d3b5ad1417/detection

I read up on Graftor too, it says it's supposed to "install a trojan or make system changes without user consent" and uhh.. I don't know how they got that from what itch-setup does. It does download and write files (like an installer does), create desktop shortcuts and an uninstall entry in the registry (like an installer does), but that's all. Also, it only does all of that after the user pressed "Install".

Feel free to report the false positive to Spybot!

**Comment by Palmsunday** [comment]
Gr8! Thanks for the input, open source is my preferred software. I will report false positive to SB SD.

**Comment by Palmsunday** [comment]
Now the setup will not open when i click it, it doesn't open at all, any thoughts?
