### ISSUE TITLE
Unable to install itch-setup on Win10 x64

### ISSUE THREAD

**Issue by Palmsunday** [itchio/itch#2229]
I try to run itch-setup and nothing happens, nothing in Task Manager, the file is clean.
I even unblocked it via 'properties'.
When I try to run it 'as administrator' i get the following dialogue message:

"Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

I am the administrator and the only user on my machine. I have no clue as to what is the culprit, I've tried re-downloading the setup file several times.

UPDATE:
My AV was somehow blocking it without prompting me, I disabled 'live protection' and it fired up right away!
I tried deleting this post as to not waste anybodies time, so it can be closed immediately. Silly me. Duh.

btw it is Spybot SD that has an issue with itch just in case someone else has the same issue, just whitelist and submit false positive.

**Comment by fasterthanlime** [comment]
Ah, thanks for the update! I was reading my e-mail and only saw the original post, was expecting an unpleasant troubleshooting session :)
