### ISSUE TITLE
don't show log in fields when it's doing stuff while automatically logging you in

### ISSUE THREAD

**Issue by leafo** [itchio/itch#223]
when app first starts and it's logging you in from remembered credentials it should not show disabled log in inputs, confusing ux

![](http://leafo.net/shotsnb/2015-12-21_03-25-20.png)

**Comment by fasterthanlime** [comment]
@leafo actually shouldn't it show that but with prefilled username and dummy 8-char password? makes sense to me

**Comment by fasterthanlime** [comment]
I agree that it's "confusing UX" but the alternative seems even worse.
- by the time this happens, you've seen them once & you've seen what happens when you log in
- it maintains a strong consistency with the login dialog: logo, inputs, status, secondary actions

I'm open to other opinions though.

**Comment by leafo** [comment]
I think just showing a loading screen without any login information makes sense, since 99% of the time they will log in with no issues. There should be nothing on that screen that looks like it might be interactive, especially since it's going to change immediately in a few moments. (referring to register & forgot password as well)

**Comment by leafo** [comment]
:100:
