### ISSUE TITLE
Update of app adds bad code copies to code files(*.py files)

### ISSUE THREAD

**Issue by mundusnine** [itchio/itch#2230]
Issue in question: 
https://github.com/armory3d/armory/issues/1083

Quick Solution: 
Add possibility in itch app preferences to not minimize update download size( ergo just doing a fresh download all the time). Can be on a per app basis or just app wide.

**Comment by fasterthanlime** [comment]
Is this with v23 of the app? Assuming that:

  * armory is not (yet) using https://itch.io/docs/butler to push updates
  * this is with v23

then it's a known isuse. It will not happen with v25, and it will also be resolved if armory switches to butler (which I recommend they do).

**Comment by mundusnine** [comment]
I am using v25 on my computer.
![image](https://user-images.githubusercontent.com/29337013/50738103-6e077c00-119e-11e9-9f61-df410483ed3d.png)

 I don't know if @luboslenco uses butler.

**Comment by fasterthanlime** [comment]
> I am using v25 on my computer.

Did you start using itch at v25? Or is it possible you installed Armory with v23, then upgraded to itch v25, and upgraded Armory?

I'd like to take a look at `~/.config/itch/logs/itch.txt` if possible!

**Comment by mundusnine** [comment]
Started at v25 and installed Armory with v25.[itch.txt](https://github.com/itchio/itch/files/2737429/itch.txt)

**Comment by fasterthanlime** [comment]
From the armory3d issue:

> Itch has an updating system that tries to minimize the size of updates and this could be causing the issues we are seeing. Basically, I first installed the 2.7 version through the itch app and then installed the 2.8 06_alpha and the weirdness I saw in the code is probably caused by itch adding the new code of the 2.8 .py version in a copy of the .py files from the 2.7 version.

What exactly do you mean by that? Did the files on disk contain the code twice? Like that?

```python
# 2.7 version of the code starts
# 2.7 version of the code ends
# 2.8 version of the code starts
# 2.8 version of the code ends
```

edit; I'm fairly sure I found the issue, working on a fix

**Comment by fasterthanlime** [comment]
The issue has been identified and a fix is being released in butler v15.7.0, your app will shortly update to it automatically :)

**Comment by mundusnine** [comment]
@fasterthanlime  Sorry for not responding. I don't know if the issue you found was that files would have old bits of the code with the new bits. For example:
`function do(t:Int){ implementation}` 
and on the next iteration of the app the function would change but the old definition and the new one would both be added (in a diff probably). It would look something like this:
```
function do(t:Int){
      implementation
function do(t:Bool){
      implementation
}
```
Thank you for the fast response and fix! And hoping that you found the same issue or close too what I just described.

**Comment by fasterthanlime** [comment]
> I don't know if the issue you found was that files would have old bits of the code with the new bits. For example:

It would've.

Files that became smaller were not properly truncated - so on disk, there was "too much" file - the new file at the beginning, and the rest of the old file at the end. If the declarations were at the end of the old file, then they would appear twice!
