### ISSUE TITLE
Serve 64-bit installer for 64-bit windows to avoid bad AV no cookie

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2231]
Since a bunch of AV vendors are (to put it politely) poopyheads, and will randomly decide that 32-bit Golang executables are malware, it might be a good idea to serve the 64-bit version of the installer to 64-bit Windows users, even though it's completely unnecessary otherwise.

This requires some adjustments - itch-setup itself is built for Win64, but `install-itch` (the repackaged version for initial installs) currently only has a 32-bit build for Windows:

  * https://broth.itch.ovh/install-itch

So, a few scripts need adjustements, and then nuts.itch.zone needs to start serving the 64-bit build to 64-bit users. And then maybe we'll see a decrease in false positives reported.

**Comment by retropipes** [comment]
I am hopeful this resolves things... at least Windows Defender isn't one of the cranky AV engines!

**Comment by fasterthanlime** [comment]
Actually I did that 1-2 weeks ago, when I shipped the latest itch-setup!
