### ISSUE TITLE
Itch.io app updates corrupted for Dicey Dungeons

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch#2232]
Hello! When some users updated my game Dicey Dungeons from v0.14 to v0.15 on windows, they got this error message, which is Dicey Dungeons specific:

`bad node type, expected element but found 6`

It turned out to be an XML parsing error, caused by a corrupted XML file. This seemed to only affect users using the itch.io app.

It seems like, somehow, the itch.io app was downloading a broken update that wouldn't start. This happened twice: one set of users reported it when updating from v0.14 to v0.15. Another when updating from v0.15 to v0.15.1. For v0.15 and before, I updated the game using the website. For v0.15.1, I've started using butler.

The fix was to delete the game and reinstall it on the itch.io app.

(If you need any more information about this, let me know!)

**Comment by fasterthanlime** [comment]
I can confirm that:

  * I was affected by the bug when updating from v0.14 to v0.15
  * After the fix, I upgraded to v0.15.1 and did *not* experience the bug

So, I'm pretty confident it's fixed :)

The problem occured only when:

  * It was a non-butler upgrade
  * A file existed both in the older version and the newer version
  * The file in the newer version was smaller than the older version

The actual fix [occured here](https://github.com/itchio/savior/commit/fa53ef6e95620d2f5583580af460386f1fcb7190) and was [merged here](https://github.com/itchio/butler/commit/01559abfe37e5e4c5767e34517a4fcbf05a14f13), it shipped in butler v15.7.0, the itch app updates its own dependencies so everyone should have the new version within half an hour of having the app open, or the next time they open it.

And it does not occur anymore. Thanks again for the report @TerryCavanagh !

**Comment by TerryCavanagh** [comment]
Ah! Sorry I took so long to respond 😅 I have historical builds on my google drive, could have linked them to you easily! Anyway, glad you figured it out!
