### ISSUE TITLE
CJK font rendering

### ISSUE THREAD

**Issue by roseverte** [itchio/itch#2234]
![image](https://user-images.githubusercontent.com/12087152/51493084-a9cd5300-1de6-11e9-86ec-3d1a8e4ea49c.png)
Edit: since probably the text's content can be fixed through weblate, I changed the issue to the one I found here.
The kanji 閉じる misses the first top line (so it's like being cut at the top)
Is this fixable? Thank you.

**Comment by fasterthanlime** [comment]
> Edit: since probably the text's content can be fixed through weblate, I changed the issue to the one I found here.

Mhh, next time please don't edit an issue to another issue - just mark the old one as closed (comment whether it has been fixed or is wontfix) and open a new one.

> The kanji 閉じる misses the first top line (so it's like being cut at the top)
> Is this fixable? Thank you.

What dialog is that in exactly? Can you make a larger screenshot?

**Comment by roseverte** [comment]
Sorry for that. It's not a big deal, I just feel it would be better if it can be showed fully.
Basically it means "close" and appear in some occasion, like at the "Manage" when I click in one of the game
![image](https://user-images.githubusercontent.com/12087152/51829626-8cd1dc00-2320-11e9-89d6-15fdc96eedcd.png)

**Comment by fasterthanlime** [comment]
Interesting! I don't see it truncated here on Linux:

![image](https://user-images.githubusercontent.com/7998310/51830390-04d3de00-22f0-11e9-93c9-a936f357aa3a.png)

I'll try to reproduce on Windows

**Comment by roseverte** [comment]
I'm using Windows, so probably it depends on the default font which is used by itch io app in each OS?
I think the kanji font also looks weird before in other occasion, so I changed the sentence to katakana (kanji displayed in Mincho, while other in Gothic style, but only in several menu with big text on it)

If you don't understand Mincho and Gothic, you can imagine like, kanji appears in New Times Roman, and other letters(hiragana and katakana) look like Arial/ Tahoma. Something like that...

**Comment by roseverte** [comment]
![image](https://user-images.githubusercontent.com/12087152/51830694-07036000-2323-11e9-9452-8b112018a8bb.png)
found one for example. you can see the kanji 中 is displayed in different font than the others.

**Comment by fasterthanlime** [comment]
Ah, interesting! On Linux, here's what I see:

![image](https://user-images.githubusercontent.com/7998310/51831164-c0494200-22f1-11e9-9918-e11cc7fff495.png)

It looks like shipping Noto Sans CJK might be a good idea? https://www.google.com/get/noto/help/cjk/

**Comment by roseverte** [comment]
yes, I can see the linux display is perfect. I tried to install 1 of the Noto Sans CJK and it seems to be great :)

**Comment by fasterthanlime** [comment]
So, I just looked at the Noto CJK distribution, and a single font-weight (say, Noto Sans CJK Regular) is 16MB! Compressed, it's 14MB.

For comparison, the entire itch app currently fits in a 62 MiB zip file:

![image](https://user-images.githubusercontent.com/7998310/51982180-87e26900-2495-11e9-8195-5c294fcd34cc.png)

We could ship the Japanese-only versions of Noto Sans CJK, but then Korean/Simplified Chinese/Traditional Chinese don't get the benefits of this font...

@roseverte was that on Windows 10, or WIndows 7 ?

**Comment by roseverte** [comment]
mine is Windows 10
I don't think this is an urgent fix, so you can take your time if in case you want to ship it together with other language version update :)
Japanese fonts and other language fonts which are using various characters are always huge ><

**Comment by fasterthanlime** [comment]
> mine is Windows 10

:( I was hoping Win 10 shipped with decent fonts.

> so you can take your time if in case you want to ship it together with other language version update :)

Well, it's not really about timing, it's more about.. do we want to ship an additional 16MB (x number of weights, so if have Light, Regular, Bold, that's 48MB) to everyone? I don't know.

We could optionally install the fonts whenever japanese is selected, that could work?

**Comment by roseverte** [comment]
I think win 10 also shipped with Yu Gothic UI and other nice Japanese font. 
I don't know if it's because I'm using SEA Windows 10 (I have my Japanese Win 10 in my laptop if you need me to check) but the default font they choose is the font seems to not support Japanese well.
Optionally install is nice as well I think.

**Comment by roseverte** [comment]
Ah! I'm very sorry! I asked a Japanese friend to check it on his computer, and it seems it displayed well in Japanese ver. Win 10 
![image](https://user-images.githubusercontent.com/12087152/51988926-7f5f5200-24d8-11e9-80f6-a54363fde7f2.png)
the problem might be because I'm using SEA Win 10 on my desktop...

**Comment by fasterthanlime** [comment]
> the problem might be because I'm using SEA Win 10 on my desktop...

SEA = Southeast Asia ?

> Ah! I'm very sorry! I asked a Japanese friend to check it on his computer, and it seems it displayed well in Japanese ver. Win 10

Ah, very nice! Thanks a lot for checking :) I'm guessing we can close this now then?

**Comment by roseverte** [comment]
yes south east asia. I'm moving from Japan to SEA years ago, so now my main PC is SEA Windows.
and yes, feel free to close it! Thank you!
