### ISSUE TITLE
🏁 Issue v23.2.1

### ISSUE THREAD

**Issue by TWTolman** [itchio/itch#2239]
Dear itch app team, 

Hello I'm having a problem launching games from my itch desktop app.
I click and nothing happens. I've checked that I'm up to date so im not sure what else to do.
thanks!

**Comment by fasterthanlime** [comment]
@TWTolman hi there!

I'm not sure exactly why you're seeing that, but, v23.2.1 is definitely not the latest version of the app.

Here's what you can do:

  * Completely exit the itch app (Ctrl+Q)
  * Install itch v25 from https://itch.io/app
  * Try again!

If you still have trouble then, please re-open this issue and I'll as you for more details.
