### ISSUE TITLE
if rar will never be supported don't bother letting people download rars

### ISSUE THREAD

**Issue by leafo** [itchio/itch#224]
since it's just marked broken immediately after you download

**Comment by fasterthanlime** [comment]
good point

**Comment by fasterthanlime** [comment]
@leafo what should the UX be like? it's gonna be hard to _not_ show an `Install` button — but we could have a modal dialog + `Learn more..` button + auto cave-implosion when that happens, rather than marking it as broken.

**Comment by matiasbeckerle** [comment]
Right now `.rar` files are not being deleted from `users/{id}/archives`.

**Comment by Seegras** [comment]
Usability: Could you fix the pop-up window that tells you rar is not supported, to include the name of the game? Otherwise when installing multiple games, you still have no idea which one it was.

**Comment by fasterthanlime** [comment]
> Usability: Could you fix the pop-up window that tells you rar is not supported, to include the name of the game? Otherwise when installing multiple games, you still have no idea which one it was.

Yeah noticed that too, good point! Opened #344 to deal with it.
