### ISSUE TITLE
missing files in download list

### ISSUE THREAD

**Issue by dunn** [itchio/itch#2259]
(If this is just #2255 then go ahead and close.)

As of 25.4.0 (Windows and macOS), the app can't download the main game from https://vnstudioelan.itch.io/heart-of-the-woods

All that is made available in the dropdown is the demo and the NSFW patch:
![image](https://user-images.githubusercontent.com/985416/52917424-2b0ded80-32a0-11e9-8d72-0ee6b55da2a2.png)

<img width="883" alt="screen shot 2019-02-17 at 10 38 41 am" src="https://user-images.githubusercontent.com/985416/52917429-3d882700-32a0-11e9-99d3-2c897227bf5a.png">

My only guess is that this is because of the very large file size; the developers had to get Itch to bump the upload limit: https://twitter.com/vnstudioelan/status/1096617001898962945

**Comment by dunn** [comment]
The main file, `HeartoftheWoods-1.0.0-market.zip`, contains cross-platform launchers:
```
total 248
drwxr-xr-x@   3 alex  staff      96 Feb 17 12:35 HeartoftheWoods.app/
-rw-r--r--@   1 alex  staff  107520 Feb 15 21:23 HeartoftheWoods.exe
-rw-r--r--@   1 alex  staff    6376 Nov 19 05:55 HeartoftheWoods.py
-rwxr-xr-x@   1 alex  staff    2084 Nov 19 05:55 HeartoftheWoods.sh*
-rw-r--r--@   1 alex  staff     125 Jan  7 04:03 desktop.ini
drwxr-xr-x@   8 alex  staff     256 Feb 14 18:10 game/
drwxr-xr-x@   6 alex  staff     192 Feb  5  2018 lib/
drwxr-xr-x@ 101 alex  staff    3232 Nov 19 05:55 renpy/
```

**Comment by fasterthanlime** [comment]
The main upload isn't currently tagged with any platforms. It should be marked with Windows, macOS and Linux, see https://itch.io/docs/itch/integrating/troubleshooting-guide.html

**Comment by fasterthanlime** [comment]
Update: I fixed the platform tags for the main upload, it should work now.

Just for the record:

> My only guess is that this is because of the very large file size;

The app will happily install 15GB games :)

If you are in touch with the developers, please remind them that using butler is a really really good idea (and trivial if they already use steamcmd), see https://itch.io/docs/itch/integrating/quickstart.html

**Comment by dunn** [comment]
Thank you!
