### ISSUE TITLE
[linux] game Red Rogue broken for v0.11.0

### ISSUE THREAD

**Issue by erickopelt** [itchio/itch#226]
:rotating_light: Game [Red Rogue](http://st33d.itch.io/red-rogue) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f442301de7b8214106a3).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Interesting, looks like the linux distribution of Red Rogue is straight out an executable. Could it be self-extracting?

@erickeuller what happens if you download it manually & run it ? (assuming you trust the developer)

**Comment by beansmyname** [comment]
:rotating_light: Game [Red Rogue](http://st33d.itch.io/red-rogue) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d66cabc1ee8ef9f3c562).

:running: Downloaded executable from website runs fine.

**Comment by fasterthanlime** [comment]
@beansmyname same questions to you as I asked to @erickeuller 

It looks like it's just a linux executable, but I don't know if it's something like a command-line self-extracting archive, a graphical installer (a-la Loki installer), or just the game itself.

**Comment by erickopelt** [comment]
@fasterthanlime i have manually download and run the game and got this error message "error while loading shared libraries: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"

**Comment by fasterthanlime** [comment]
Ah, so it looks like it is just the game, thanks @erickeuller.

That said, it's badly packaged. I recommend getting in touch with the developer & pointing them towards https://github.com/itchio/itch/issues/86

In particular, libraries like that should either be compiled statically, or ship with the game, in a directory added to `LD_LIBRARY_PATH` by a launcher script.
