### ISSUE TITLE
App doesn't display properly

### ISSUE THREAD

**Issue by stepsani** [itchio/itch#2270]
Hi. Basically the app opens in the upper left corner of the screen and I can't log in or interact with it in any way. I tried to uninstall and reinstall. Version 25.4.0.
![photo_2019-03-07_14-59-18](https://user-images.githubusercontent.com/9203318/53961739-9998db00-40e9-11e9-8564-5745800662e9.jpg)

**Comment by fasterthanlime** [comment]
That's on Windows? Did you have another version of the app installed previously?

**Comment by stepsani** [comment]
Yes, it's on Windows. I only installed Itch once, so I guess no.

**Comment by fasterthanlime** [comment]
Windows 10?

Do you have multiple monitors? Do you have an nVidia, Intel, or AMD graphics card?

**Comment by stepsani** [comment]
Windows 10. It's a laptop with an Intel integrated card and a Nvidia dedicated card.

**Comment by fasterthanlime** [comment]
Could you try quitting the app completely with Ctrl+Q, then deleting the
`%APPDATA%\itch` folder and starting it up again?

**Comment by stepsani** [comment]
It works! Thanks!

**Comment by fasterthanlime** [comment]
Nice, thanks for the reply!
