### ISSUE TITLE
Error during warm-up

### ISSUE THREAD

**Issue by mijwimufi** [itchio/itch#2271]
> Something went wrong
> 
> itch-setup, v1.16.0, built on Jan 16 2019 @ 08:26:36, ref 3fd4a9f731e0c27f518a46b50e166b520cfd9239
> 
> rename C:\Users\<username removed>\AppData\Local\itch\staging\app-25.4.0 C:\Users\<username removed>\AppData\Local\itch\app-25.4.0: Access is denied.
> moving ready version to its proper place
> Error during warm-up

--

Anti-Virus (comodo cloud) shows it as a trusted application in the logs. I've elevated it to try and install on C: to test if it was an elevation problem-- solutions?

Is there a standalone full installer instead of downloading it through the setup process?

OS: Windows 10 v1809

**Comment by fasterthanlime** [comment]
> I've elevated it to try and install on C: to test if it was an elevation problem-- solutions?

This never ever helps, it only hurts :(

> Is there a standalone full installer instead of downloading it through the setup process?

You can grab a zip from https://fasterthanlime.itch.io/itch - but if your antivirus is already messing with the installer, I'm guessing you'll just have more problems later on (I don't recommend it).

I'm guessing Comodo Cloud locks the folder and that's why it can't be renamed? Renaming folders is a pretty basic operation, it's weird that it'd block that :( but at the same time, AV software sees itch-setup as "dropping executables" (which, yes, it's installing things), so it might freak out a bit.

If you have logs I'm happy to look at them.

**Comment by mijwimufi** [comment]
The installer is running through the AV in the logs, maybe its windows locking it now somewhere--firewall logs check out about the same as well allow-outgoing. Thank you for the fast response and the zip link~

> 2019-03-16 11:46:43,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:46:07,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:45:51,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:45:37,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:41:07,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:38:14,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:33:01,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:32:44,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:32:04,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:31:35,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:30:10,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app
> 2019-03-16 11:19:32,C:\Users\<username removed>\Downloads\itch-setup.exe,Trusted Installer,Installer and self-update helper for the itch app

**Comment by fasterthanlime** [comment]
> firewall logs check out about the same as well allow-outgoing

So, itch-setup *does* make outgoing connections (since it downloads the actual app), but a firewall usually own't interfere with filesystem operations.

If it was Windows itself, then a lot of other users would be having this issues (I'd drown in reports!) - so it's not the case at least not for default policies.

**Comment by mijwimufi** [comment]
All right, Ive made an installer log:

> 2019/03/16 12:18:15 =========================================
> 2019/03/16 12:18:15 itch-setup "v1.17.0, built on Feb 23 2019 @ 15:16:00, ref 8b2074fd782cd00976193c1a627f31b4e0ec2728" starting up at "2019-03-16 12:18:15.6180889 -0700 PDT m=+1.035000601" with arguments:
> 2019/03/16 12:18:15 "C:\\Users\\<username removed>\\AppData\\Roaming\\itch\\broth\\itch-setup\\versions\\1.17.0\\itch-setup"
> 2019/03/16 12:18:15 "--version"
> 2019/03/16 12:18:15 =========================================
> 2019/03/16 12:18:17 =========================================
> 2019/03/16 12:18:17 itch-setup "v1.17.0, built on Feb 23 2019 @ 15:16:00, ref 8b2074fd782cd00976193c1a627f31b4e0ec2728" starting up at "2019-03-16 12:18:17.2660894 -0700 PDT m=+0.741002801" with arguments:
> 2019/03/16 12:18:17 "C:\\Users\\<username removed>\\AppData\\Roaming\\itch\\broth\\itch-setup\\versions\\1.17.0\\itch-setup"
> 2019/03/16 12:18:17 "--appname"
> 2019/03/16 12:18:17 "itch"
> 2019/03/16 12:18:17 "--upgrade"
> 2019/03/16 12:18:17 =========================================
> 2019/03/16 12:18:17 App name specified on command-line: itch
> 2019/03/16 12:18:17 Locale:  en-US
> 2019/03/16 12:18:17 Could not get registry base dir: The system cannot find the file specified.
> 2019/03/16 12:18:17 Initial base dir: (C:\Users\<username removed>\AppData\Local\itch)
> 2019/03/16 12:18:17 Initializing (itch) multiverse @ (C:\Users\<username removed>\AppData\Local\itch)
> 2019/03/16 12:18:17 No multiverse information yet
> 2019/03/16 12:18:17 No version currently installed
> github.com/itchio/itch-setup/setup.(*Installer).Upgrade.func2
> 	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/upgrade.go:81
> github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/taskgroup.Do.func1
> 	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/taskgroup/taskgroup.go:24
> runtime.goexit
> 	C:/Go/src/runtime/asm_amd64.s:1333
> task 2
> github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/taskgroup.Do
> 	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/taskgroup/taskgroup.go:37
> github.com/itchio/itch-setup/setup.(*Installer).Upgrade
> 	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/setup/upgrade.go:64
> github.com/itchio/itch-setup/native.(*nativeCore).Upgrade
> 	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/native/native_windows.go:108
> main.main
> 	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/main.go:203
> runtime.main
> 	C:/Go/src/runtime/proc.go:201
> runtime.goexit
> 	C:/Go/src/runtime/asm_amd64.s:1333
> Fatal upgrade error
>

**Comment by fasterthanlime** [comment]
@endeph3ct yep, like I said, you're now having further errors.

itch-setup is used both for initial installation of itch and for self-update, so if you can't get the initial install past your AV (antivirus), then you'll keep having more trouble.

I'd suggest contacting Comodo, itch-setup is a legitimate program doing legitimate things and their AV shouldn't change Windows APIs to prevent it from working properly. Sorry :(
