### ISSUE TITLE
.net framework 4.7.1 fails to install as a prerequisite

### ISSUE THREAD

**Issue by katerd** [itchio/itch#2272]
I have re-targeted my game to use .net framework 4.7.1 following the addition of it to butler:  [Missing prereqs](https://github.com/itchio/butler/issues/184) but when launching the game I get the following error: 

> The message we got was: Some prereqs failed to install: net-4.7.1
> Sending us a report is the best way to make sure this gets fixed!

Versions:
- itch @ 25.4.0
- butler @ 15.8.0
- itch-setup @ 1.17.0

**Comment by fasterthanlime** [comment]
Turns out a few prereqs were broken by a ~recent change in butler, I've just deployed v15.9.0 which should fix all prereqs.

**Comment by fasterthanlime** [comment]
Here's a GIF of the `net-4.7.1` prereq working with butler v15.9.0

![net471](https://user-images.githubusercontent.com/7998310/54496175-a5a44a00-48ec-11e9-9559-7ce8753f5b59.gif)

You can use `Preferences -> Components -> Check for updates` to force an update to butler 15.9.0 (or Ctrl+Q and restart the app, or wait half an hour, etc.)
