### ISSUE TITLE
Installing Butler through Itch app doesn't work in recent macOS versions

### ISSUE THREAD

**Issue by malvese** [itchio/itch#2273]
I tried to install Butler through the app, but couldn't get it to work. The steps in the documentation didn't work for me. I added it to PATH, tried to make it executable, to no avail.
It seems like recent macOS versions only allow to use command line executables in `/usr/local/bin`.

I found two ways around:

1. Download Butler from github, move it to `/usr/local/bin`. Classic. No need to edit `bash_profile` as I believe `/usr/local/bin` is already in PATH by default.
2. Install via itch.app anyway, then symlink it in `/usr/local/bin` (`ln -s /Users/xxxx/Library/Application\ Support/itch/apps/butler/butler /usr/local/bin/butler`)
I prefer the second method as it still allows to update through the app. Also I think it could be done automatically by itch.app, as it's the way Homebrew and others install packages.

**Comment by fasterthanlime** [comment]
> It seems like recent macOS versions only allow to use command line executables in `/usr/local/bin`.

I hate to doubt you, but that seems *extremely unlikely*.

Here are things I would check first:

  * The file you're editing does get evaluated when you open a new terminal
    * Note: you need to start a new terminal *after* editing the file
  * The `$PATH` value is what you expect
    * You can type `echo $PATH` and press enter, look at the value - if it contains your path, then great!
    * Also, post it here, so that I can double check it
  * The `$PATH` value is valid
    * If you don't escape spaces, for example, you're going to have issues

If you'd just post the output of `echo $PATH`, then we could eliminate some failure modes!

Re homebrew: I agree it'd be nice to publish butler on homebrew!

**Comment by malvese** [comment]
Thank you for your fast reply!

Additional info:
- I use ZSH, butler is in my PATH but still doesn't work: `/Users/xxx/(some unrelated web dev things here)/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Library/Application\ Support/itch/apps/butler`
Butler has the executable flag: `-rwxrwxrwx  1 xxx  staff    22M 17 mar 19:39 butler`
Still, "zsh: command not found: butler"
- I just noticed if I use bash it works… I guess itch.app adds the path here automatically? Pretty sure I didn't add it myself here. But I fail to see any reason why it wouldn't work through ZSH?

Btw, I'm using macOS Mojave 10.14.3

**Comment by fasterthanlime** [comment]
> * I just noticed if I use bash it works… I guess itch.app adds the path here automatically?

Nope, the itch app always executes butler from its absolute path, it never adds it to `$PATH`.

Since it's working in bash, but not in zsh, I'd "echo $ENV` in both and see the differences. I'm assuming you'll need to edit `~/.zshrc` for zsh instead (the docs should probably mention that!).

**Comment by malvese** [comment]
Thank you for the help! I think this issue should be closed, as the problem is likely due to my config.

I commented paths in `bash_profile` so the only zshrc adds paths. Still the command works in bash but not zsh.
`echo $ENV` returns nothing, but `echo $PATH` returns the same in both bash and zsh.

**Comment by fasterthanlime** [comment]
> `echo $ENV` returns nothing, but `echo $PATH` returns the same in both bash and zsh.

Ah, my bad.

You might also want to try `hash -r` (and then `butler` again), and `which butler`.

Also, I'd recommend doing `export PATH="path with spaces/bar"` instead of `export PATH=path\ with\ spaces/bar` - the former is less error-prone.

I'd like to keep this issue open until you get it fixed or stop responding :) I'm sure others are having similar difficulties, we can probably adjust the docs to make it better.

**Comment by malvese** [comment]
Thank you for your patience!
New info: when I specify a path in the command it works.

```
$ ~/Library/Application\ Support/itch/apps/butler/butler -V
v15.9.0, built on Mar 17 2019 @ 19:30:12, ref 390d5d9dac357aa25ceaa5257476f0f724aac9b3
```
But still not from anywhere with just `$ butler`

Butler is in my PATH:
```
$ echo $PATH
_(some other stuff…)_/Library/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Library/Application Support/itch/apps/butler
```
Oh, interesting: if I replace `~/Library/Application\ Support/itch/apps/butler` with `/Users/my_username/Library/Application Support/itch/apps/butler` it works.

Also if I escape the space in "Application Support" and avoid double quotes it also works:
`export PATH=$PATH:~/Library/Application\ Support/itch/apps/butler`

Edit: this ugly thing works
`export PATH=$PATH:~/Library/"Application Support"/itch/apps/butler`

**Comment by fasterthanlime** [comment]
Uhhh maybe it doesn't expand `~` if it's in double quotes? What about

```
export PATH="$PATH:$HOME/Library/Application Support/itch/apps/butler"
```

**Comment by malvese** [comment]
Brilliant! Good catch, it works perfectly. Do you think it's also a good solution for other unix OSes?

And indeed:
```
$ cd /      -> OK
$ cd ~      -> OK
$ cd "~"    ->  cd: no such file or directory: ~
```

**Comment by fasterthanlime** [comment]
Seems like it behaves the same on http://www.msys2.org/ at least.

I've always been using `$HOME` instead of `~` in `~/.bashrc` and `~/.zshrc`, I guess I just remembered why :)

**Comment by fasterthanlime** [comment]
I've updated the docs, the updated version should be up on https://itch.io/docs/butler in a bit!

Thanks for responding consistently to this thread :)

**Comment by alexedev** [comment]
Hello. Looks like there is no butler in itch/apps anymore. I see it only in broth. 

![Screenshot 2019-05-29 at 15 02 45](https://user-images.githubusercontent.com/1526837/58559191-d70d9000-8222-11e9-9491-c7875ed167ca.png)

**Comment by fasterthanlime** [comment]
@alexedev Let me try to clarify:

  * `broth` is an internal folder - it is not for public use
  * `apps` contains whatever you have chosen to install from the app - it is not automatically installed there, you have to open https://fasterthanlime.itch.io/butler in the app and click Install.

**Comment by alexedev** [comment]
Wow, I did not understand it from the docs
works like a charm, thank you!
