### ISSUE TITLE
🏁 Issue v23.6.1

### ISSUE THREAD

**Issue by andyc06** [itchio/itch#2274]
Dear itch app team, 
This pertains to the Windows version of itch desktop. When Owned Items is in "List View", right clicking on a game doesn't bring up the context menu like it does in the "Tile View". It works like a left click and launches the integrated browser for that game's webpage. Thanks and cheers,
Andy

**Comment by fasterthanlime** [comment]
Hey @abcx06 

v25 of the app has been released months ago, you can:

  * Completely quit the itch app with Ctrl+Q
  * Download and install the latest from https://itch.io/app

**Comment by andyc06** [comment]
Thank you for letting me know. 23.6.1 told me it was up to date so I guess that part didn't work. But I'm happy to update and retest. Thanks!
