### ISSUE TITLE
The Error message during installing itch on windows 10 version

### ISSUE THREAD

**Issue by keven180** [itchio/itch#2276]
There are the log:
发生了一些错误

itch-setup, v1.16.0, built on Jan 17 2019 @ 00:26:36, ref 3fd4a9f731e0c27f518a46b50e166b520cfd9239

Get https://w3g3a5v6.ssl.hwcdn.net/build/116009/437360-archive-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1553183797&Signature=cD8RMK7EL%2FgRByM%2BcxWRWkZVNH%2B9xcsQ52YXLaWGBO1K2Hz4FWUQdfNNBD15BUhB1XUu0RwrrPsN3DClf%2FRTPTotbwU%2B6zQfqmluqn704Pg39nVBFald%2BxFtnzI4CEI%2B0IHTFUUHEcx%2BDiT%2Fe%2BWxiZW4WcRzabS95b1u%2B9A9ZbpVJNj1M%2Fw34H0pPaUzpYlIU5orUM863%2FjkzqsP%2FM39uYSgPun0Ry1zHMg7gTjD6r2BJwdh26gSg22tUKc8bPEHNgfAQ5L5ZmKkQw0SFUrVGsO4XaEvFe4sHlmULfXc9sHK02u4vdap5jd%2FSQ3IEbQTjww02ePurlyjcLcpJuJ7nA==&hwexp=1553184087&hwsig=d192bc9d61431cb47d86103eab8dc50d: unexpected EOF
htfs connect
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1324
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1324
while installing
Error during warm-up

**Comment by fasterthanlime** [comment]
Unfortunately, there are known issues re: downloading from our CDN from China. Sorry :(
