### ISSUE TITLE
Single executable gets unpacked?

### ISSUE THREAD

**Issue by quyse** [itchio/itch#2278]
The project in question: https://quyse.itch.io/flaw

If I download Windows version of the project via browser, single executable `model-editor.exe` gets downloaded, and runs as expected.

If I install it via latest stable itch app (clean install), it cannot be launched (the app says `Nothing that can be launched was found.`). The app folder looks like this:
![image](https://user-images.githubusercontent.com/416215/56090261-9c38de00-5ea8-11e9-8f10-e924d61bc255.png)

This looks like executable's sections, so apparently the executable is unpacked somehow?

The build was pushed via butler like this:
```
butler push windows quyse/flaw:model-editor-windows
```
Where `windows` is a folder with a single executable inside.

**Comment by fasterthanlime** [comment]
Seems like a regression due to my efforts to get ".tar.gz files pushed with butler" to install properly.

I'm probably going to revert that functionality, it's already caused trouble with redists in the past, sorry about the disturbance.

**Comment by fasterthanlime** [comment]
butler v15.10.0 (in CI right now) will fix this
