### ISSUE TITLE
[darwin] Broken game for v0.10.2

### ISSUE THREAD

**Issue by julientaq** [itchio/itch#228]
Game [Aseprite](http://dacap.itch.io/aseprite) is broken for me.

Here's the [debug log](https://gist.github.com/b428459c058049920913).

**Comment by fasterthanlime** [comment]
Hey julien, thanks for your report!

This will be fixed when #19 is :)

**Comment by fasterthanlime** [comment]
Ah, #19 was closed a while ago - Aseprite works fine on OSX!
