### ISSUE TITLE
Issue When Installing App (v25.4.0, itch-setup v1.18, rename: Access is Denied)

### ISSUE THREAD

**Issue by vizthex123** [itchio/itch#2283]
I get this error every time I try to install the app:

`Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:29:17, ref 57838bc373361f2c8938336674247f869999e862

rename C:\Users\Caleb\AppData\Local\itch\staging\app-25.4.0 C:\Users\Caleb\AppData\Local\itch\app-25.4.0: Access is denied.
moving ready version to its proper place
Error during warm-up`

**Comment by fasterthanlime** [comment]
Which version of Windows?

Any antivirus software besides Windows Defender?

**Comment by vizthex123** [comment]
Yes, I have McAfee anti-virus and I'm on the latest Win 10 release.

I've never had this issue before (I've had Win 10 since it came out) so I'm not sure what's wrong.

**Comment by vizthex123** [comment]
Yes, I have McAfee anti-virus and I'm on the latest Win 10 release.

I've never had this issue before (I've had Win 10 since it came out) so I'm not sure what's wrong.
