### ISSUE TITLE
Installation failure Kubuntu 19.04

### ISSUE THREAD

**Issue by lordgault** [itchio/itch#2289]
The installer runs and at a certain point launches this message:
https://imgur.com/PC4auho

Here I leave information of the terminal:
2019/04/27 09:13:28 "./itch-setup"
2019/04/27 09:13:28 =========================================
2019/04/27 09:13:28 App name specified at build time: itch
2019/04/27 09:13:28 Locale:  es-ES
2019/04/27 09:13:28 Initializing installer GUI...
2019/04/27 09:13:28 Using GTK UI
2019/04/27 09:13:28 Initializing (itch) multiverse @ (/home/patrick/.itch)
2019/04/27 09:13:28 (/home/patrick/.itch)(current = "25.4.0", ready = "")
2019/04/27 09:13:28 Loading image resources...
2019/04/27 09:13:28 Setting up progress bar...
2019/04/27 09:13:28 Positioning and showing window...
2019/04/27 09:13:28 Will install version 25.4.0
2019/04/27 09:13:29 Reading signature...
2019/04/27 09:13:29 Installing 161.71 MiB (72 files, 2 dirs, 0 symlinks)
2019/04/27 09:13:29 Looks like (25.4.0) is already installed to (/home/patrick/.itch/app-25.4.0)
2019/04/27 09:13:29 Let's just heal that
2019/04/27 09:13:29 Installing to (/home/patrick/.itch/app-25.4.0)
2019/04/27 09:13:29 Healing (/home/patrick/.itch/app-25.4.0)...
2019/04/27 09:13:30 0 B was healed @ 0 B / s (653.070519ms  total)
2019/04/27 09:13:30 Healed in-place
2019/04/27 09:13:30 No validate handler, assuming good!
2019/04/27 09:13:30 Determining whether or not we've been installed via an OS package...
2019/04/27 09:13:30 Copying self to (/home/patrick/.itch/itch-setup)
2019/04/27 09:13:30 install (/home/patrick/.itch/itch)
2019/04/27 09:13:30 install (/home/patrick/.itch/icon.png)
2019/04/27 09:13:30 install (/home/patrick/.local/share/applications/io.itch.itch.desktop)
2019/04/27 09:13:30 Updating desktop database for (/home/patrick/.local/share/applications)
2019/04/27 09:13:30 Fatal error: while updating desktop database: exec: "update-desktop-database": executable file not found in $PATH
patrick@patrick-pc:~/Descargas$

**Comment by Belthil** [comment]
This is the same as this previously reported issue: [#2221](https://github.com/itchio/itch/issues/2221)

> UPDATE: Running `sudo apt install desktop-file-utils` installs the correct library and now things are working. Leaving this here in case anyone else runs into the same issue!

**Comment by lordgault** [comment]
Yeah. It worked.
Thank you.

**Comment by fasterthanlime** [comment]
Fixed in https://github.com/itchio/itch-setup/commit/053767107404c1041dae6277e42607b4f630029f, will ship soon.
