### ISSUE TITLE
Norton keeps fudging with itch and butler?

### ISSUE THREAD

**Issue by ghost** [itchio/itch#2292]
I have Norton Security on my current machine, and it seems to keep interfering with my installation of itch and its connection to butler. I already checked [how to have the antivirus ignore itch](https://itch.io/docs/itch/installing/windows.html#antivirus-software), but the version of Norton doesn't possess a "whitelist" to place filepaths into. If it does, I didn't see it. How do I solve the problem with Norton?

**Comment by fasterthanlime** [comment]
Well, one possible avenue is to submit the butler.exe in question as a false positive to Norton: https://support.norton.com/sp/en/us/home/current/solutions/kb20100222230832EN_EndUserProfile_en_us

I've had problems in the past with AV vendors incorrectly identifying butler or itch-setup as malware, but nowadays our VirusTotal reports are clean for all .exe(s) involved.

My real advice if Norton doesn't support whitelisting folders is to... stop using it. Honestly, in 2019, Windows Defender + an occasional MalwareBytes scan + common sense when clicking around are more than enough. I'm sorry you're running into that :(

**Comment by ghost** [comment]
I see... Darn, I'll have to save up for MalwareBytes in that case.

EDIT: My mistake; there's also the free version of MB.
