### ISSUE TITLE
Tabs are gone

### ISSUE THREAD

**Issue by bradenbest** [itchio/itch#2297]
23.x opened links in their own tabs, like a browser. In 25.x, I do not see tabs anywhere, so it's just like the steam browser. This is a massive downgrade IMO.

**Comment by fasterthanlime** [comment]
After running a user survey, tabs were disabled by default in v25 - a lot of folks found them more confusing than helpful.

A few power users have requested for the option to remain, and so you can re-enable tabs in preferences:

![image](https://user-images.githubusercontent.com/7998310/58043345-3392f000-7b3d-11e9-848c-757c269d6b1d.png)

**Comment by bradenbest** [comment]
Oh, that's even better. Thanks!
