### ISSUE TITLE
There was a problem during setup: Timed out while connecting to butlerd

### ISSUE THREAD

**Issue by Robombie** [itchio/itch#2306]
I can't use Itch because it comes up with this message.

It won't let me copy the log, sorry.

I don't understand coding, and I just want to use Itch so if someone could figure this out that would be great. Not that I'll find games to play on Itch anyways.. *sigh*

**Comment by fasterthanlime** [comment]
This is usually caused by third-party antivirus (Avira, Norton, Avast, Qihoo360 etc.) - which one are you using?

I personally recommend sticking to Windows Defender + the occasional MalwareBytes (Free) scan. There's really no need to pay for Antivirus in 2019.

**Comment by Robombie** [comment]
I only use windows defender, that's what makes this so weird. I can't
figure it out but I thank you for your response.

**Comment by fasterthanlime** [comment]
Oh, in that case I'd love to take a look at your `%APPDATA%\itch\logs\itch.txt` !

**Comment by fasterthanlime** [comment]
@Robombie hmm I don't see any "Timed out while connecting to butlerd" in those logs!

**Comment by Robombie** [comment]
Maybe I sent you the wrong logs? This one has it at the end. Thanks for trying to help.

**Comment by fasterthanlime** [comment]
@Robombie I think your messages are getting truncated (so I can't see the end of the logs).

You can just send them as an attachment directly to https://itch.io/support
