### ISSUE TITLE
🐧 Feedback v25.4.0

### ISSUE THREAD

**Issue by kekonn** [itchio/itch#2308]
The windows all froze. I restarted i3 but they all went blank and then I got this error message.

Event log:

```
TypeError: Cannot read property 'native' of undefined
    at BrowserWindow.nativeWindow.on (/home/kekonn/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:4772:48)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
```

**Comment by fasterthanlime** [comment]
I've seen that before but haven't been able to track it down so far.

The problems are:

  * The stack trace is severely lacking :( Not sure who's at fault there
  * I can't figure out how to reproduce this reliably

Until either of these changes, I won't be able to fix this. A rewrite of the multi-window handling code might fix it. I've been thinking about removing multi-window support entirely (have preferences + downloads as tabs/popovers again)

**Comment by kekonn** [comment]
Hi!
I'm not sure about the stacktrace, but maybe it helps if you can think timeout related.

I was having some real issues with my notification system. Anytime an app wanted to notify for the first time during it's launch, it might hang for 5 minutes or more.

I've since fixed that issue, but the crash happened during a hang like that. Maybe that's a hint. I was updating Rings of Saturn at the time.

**Comment by fasterthanlime** [comment]
Was the game posting a notifcation, or was it the itch app posting a notification about a game?

**Comment by kekonn** [comment]
The latter scenario. Itch was downloading an update. I assume the update was done and it wanted to notify me about it.

Later I set up a different notification system and the hangs completely disappeared, so I'm entirely sure this is really a bug in the app, because it shouldn't have to deal with this, but maybe the report or fix for this case helps with stability elsewhere as well.

**Comment by fasterthanlime** [comment]
Well, I'm glad the issue is there (and thanks for reporting!) but since it's not reproducible I'm going to close it. It's still there for future reference!
