### ISSUE TITLE
Unity WebGL builds have fullscreen problems in Itch.io client 🏁 Issue v25.4.0

### ISSUE THREAD

**Issue by Chootin** [itchio/itch#2309]
Dear itch app team, 

We uploaded our game as a WebGL build for the GMTK Game Jam and found that, when played using the install option in the Itch.io client:
- there is no sound
- fullscreen chooses a very strange vertical aspect ratio, which doesn't suite the 1920x1080 displays we were trying it on
- the unity physics engine behaves in very strange ways

[Link to Game](https://blind-mystics.itch.io/one-putt-wonder)

Try the game in either Chrome or Firefox, then try it in the Itch.io Client.

We are using Unity 2019 and the LWRP along with Fmod version 1.10.08.

**Comment by fasterthanlime** [comment]
v23.6.3 is very old, please quit the app with Ctrl+Q and install the latest
from itch.io/app

**Comment by Chootin** [comment]
Oh interesting, I checked for updates using the in-client Check for Updates option and it said the client was up to date.

**Comment by Chootin** [comment]
Alright, I have downloaded and installed the latest version using the website and all issues other than the fullscreen issue are resolved.
