### ISSUE TITLE
No games in library after upgrading from v23.6.3 to v25

### ISSUE THREAD

**Issue by sigmap** [itchio/itch#2312]
I recently updated to v25 and noticed all the games in my library vanished. They are still in the place they were installed. But they aren't showing up. Is there a fix or a known issue. I'd hate to have to re-download/install the games that were in my library before the upgrade. As a side note all my tabs vanished too.

**Comment by fasterthanlime** [comment]
It's normal for the initial v23 import scan to take some time. Have they appeared in the meantime? You can also explicitly trigger a scan from "install locations". Explicit scans show found games in a dialog. If not, I'd be interested in taking a look at your itch log file.

As for tabs, they are disabled by default in v25, but you can re-enable them in Preferences.

**Comment by sigmap** [comment]
I had to let v25 sit open for about half an hour but it finally did it. Thanks.
