### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by nyagacu17** [itchio/itch#2319]
I have trouble logging in on the itch.io app on my MacOS. I have had this app almost a year but now when I enter the log in page it says;
"Post https://api.itch.io/login: x509: certificate signed by a unknown authority"

I have tried using this URL but nothing happens. I can log in to my account via internet but not through the app. What do I do?

**Comment by fasterthanlime** [comment]
Hey, I'm unable to reproduce on Windows with the latest itch.

In your browser, while logged into itch.io, can you access https://api.itch.io/profile alright?

Here's the relevant certificate:

![image](https://user-images.githubusercontent.com/7998310/64547790-ad89f780-d32d-11e9-8289-7a571b16ca04.png)

**Comment by nyagacu17** [comment]
No, I clicked the link all that came up was this
{"user":{"developer":false,"id":1411957,"url":"https:\/\/nyagacu17.itch.io","gamer":true,"username":"nyagacu17","press_user":false}}

**Comment by fasterthanlime** [comment]
> No, I clicked the link all that came up was this

Actually that's the expected output :) I'm not sure what's going on then. I'll keep looking.

**Comment by nyagacu17** [comment]
Alright, thank you :)

**Comment by fasterthanlime** [comment]
Not able to reproduce either on macOS 10.12.6 and the latest itch app.

Is your system clock correctly set? That's a common cause of failures when verifying normally-valid certificates. Any pending system updates? What version of macOS do you have?

**Comment by nyagacu17** [comment]
I have macOS X 10.11.6 version on a  MacBook Air 11 and I have checked the system clock and its seems to match my time zone here correctly

**Comment by nyagacu17** [comment]
Hello, can you still help me or is this unresolveable? I have updated all pending updates on my Mac

**Comment by fasterthanlime** [comment]
I'm kinda running out of ideas. Do you have a proxy set up?

Apparently certificate verification failures on macOS are common for Go programs: https://github.com/golang/go/issues/27175 :(

**Comment by nyagacu17** [comment]
No, i don't think i do. How do you see it? or how do i get it?

**Comment by fasterthanlime** [comment]
You can do a search in Settings for "Proxy", it should be in the "Network"
section. Proxies usually cause problems, so if you don't, that's good.

Have you tried completely removing the itch app and installing it again
from the download on https://itch.io/app ?

If that doesn't solve it, I'll try and make you a test executable to see
what's going on.

**Comment by nyagacu17** [comment]
Nope, it still dosen`t work :(

**Comment by theleakypen** [comment]
I'm having the same issue on my own itch app. I tried to delete the app and then install it fresh and the same error message shows up. 
![Screenshot 2019-09-28 23 51 40](https://user-images.githubusercontent.com/10987310/65826027-2ce35a80-e24c-11e9-804a-c3aa31f78be6.png)
![Screenshot 2019-09-28 23 52 02](https://user-images.githubusercontent.com/10987310/65826028-2ce35a80-e24c-11e9-8af8-27f32d7e7079.png)

**Comment by fasterthanlime** [comment]
@theleakypen And you're also on macOS, correct?

It seems like it from the fonts but just making sure.

**Comment by theleakypen** [comment]
Yep! To be fair my macbook is _old_ so if there's some weird OS interaction that might be solved by updating I'm SOL. But it _was_ working up until last week.

**Comment by nyagacu17** [comment]
Hi can you still help us or is this unresolveable?

**Comment by fasterthanlime** [comment]
Hi, I'm stll working on it, among with other things, sorry for the delay :(

**Comment by grrog** [comment]
Hello, just to say that I have exactly the same problem on macos 10.11.6 since early September.

**Comment by fasterthanlime** [comment]
@theleakypen @nyagacu17 @grrog I've just released butler v15.17.1, which is the same as v15.17.0, except compiled with the latest Go and from macOS Catalina - hopefully that resolves the problem, can y'all give it a try?

(Note that I was never able to reproduce the issues, so this is a shot in the dark, but hopefully it at least doesn't make it worse..)

**Comment by nyagacu17** [comment]
Yes, it worked! I can log in now on the app without problem. Thank you so much :)

**Comment by fasterthanlime** [comment]
> Yes, it worked! I can log in now on the app without problem. Thank you so much :)

Alright! Thanks for confirming the fix works.

**Comment by grrog** [comment]
Thank you for that :)

**Comment by theleakypen** [comment]
Looks like it worked! Thank you so much.
