### ISSUE TITLE
Quit option on sub-window confusing

### ISSUE THREAD

**Issue by leafo** [itchio/itch#232]
When I go to buy a game and it prompts me to complete the flow in a new window. Does it make sense to have a quit option here?

![](http://leafo.net/shotsnb/2015-12-21_10-28-49.png)

**Comment by fasterthanlime** [comment]
absolutely, and doing Cmd-W on OSX closes the main window instead of the purchase one.

the purchase window shouldn't have a menu at all imho

**Comment by fasterthanlime** [comment]
related: 5bf531487ca95f5abbee911d8c88d1ecef132b69 (forgot to mention)
