### ISSUE TITLE
Windows game requiring start through Itch.io launcher crashes when run on Linux using Wine/Lutris

### ISSUE THREAD

**Issue by TheristheWolf** [itchio/itch#2324]
Attempting to run Kemo Coliseum using the Windows build of the Itch.io app (emulated via Wine through Lutris on Linux Mint) results in a crash upon starting the program.  For most other Itch games run in this fashion (Windows app release run on Windows Itch.io desktop client via Wine through Lutris on Linux Mint), a similar error message and stack trace are generated (including a line such as `While handling prereqs: GetFileInformationByHandleEx [APP_EXECUTABLE_PATH]: Call not implemented.`) when attempting to launch the game; however, the pop-up window containing the error message has a button labeled "Continue" in the bottom right corner, and pressing that button causes Itch to spawn the intend game without further issue.

In contrast to most other titles, the buttons in the bottom right corner of the error message generated when attempting to start Kemo Coliseum are "Ok" (as acknowledgement of the error, and consent to report it to the devs if a check box is toggled on) and "Open folder in explorer".  One of the main things that sets Kemo Coliseum apart from other Itch apps is the fact that it effectively uses the Itch.io desktop launcher as a form of DRM; if the app is started by a means other than through the Itch.io launcher (such as by running the executable directly), the Kemo Coliseum program will display an error message on startup instead of showing the main menu.

Since Kemo Coliseum uses the Itch.io app as a DRM measure (by requiring a launch through Itch.io in order to not launch into an error screen), and since the game does not have a Linux port at present, this issue effectively prevents playing Kemo Coliseum on a Linux machine short of emulating a Windows OS for the purpose.  Other Windows exclusive and Windows/Mac games that use the Itch.io launcher as a DRM measure might also be affected.

Due to the nature of the error message, it seems plausible that Itch is attempting to make a function call (specifically, `GetFileInformationByHandleEx`) that Wine either lacks support for or insufficiently/incorrectly supports.  If you guys think that this is indeed a bug within Wine (or, alternatively, within Lutris), I can submit a bug report for the relevant project that references this one; just let me know.

Below are the Itch.io client's debug log and stack trace, as logged in [Dale](https://dale.itch.ovh/) in a report timestamped August 31, 19:37:01.  With respect to the "you must buy this game to download" warning, I have access to the game's builds because I have supported the Kemo Coliseum project on Patreon and linked my Patreon and Itch accounts together; consequently, I have _not_ purchased the game directly through Itch.  As far as I can tell, the fact that I have permissions to download and play a paid-only title without payment to Itch is causing the extraneous error message (note that on Windows, the Itch client does correctly download, install, and launch Kemo Coliseum in such circumstances).

The below logs document the Itch version as 25.4.0.  While the Butler and itch-setup versions do not appear to be documented, a seemingly congruent stack trace can be generated on Butler version 15.17.0 and itch-setup 1.18.0.

**System info**
`````
{
  "state": "Loading..."
}
`````
**Log**

`````
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

August 31, 2019, 14:33:35 [INFO] itch 25.4.0 launching 'Kemo Coliseum (For Patrons)' (#266338)
August 31, 2019, 14:33:35 [DEBUG] Locking (C:\users\ethan\Application Data\itch\apps\kemo-coliseum-patrons\.itch\runlock.json) for launch
August 31, 2019, 14:33:35 [INFO] → Launching Kemo Coliseum (For Patrons) - https://dudedlestudio.itch.io/kemo-coliseum-patrons
August 31, 2019, 14:33:35 [INFO]    on runtime 64-bit Windows
August 31, 2019, 14:33:35 [INFO]    (C:\users\ethan\Application Data\itch\apps\kemo-coliseum-patrons) is our install folder
August 31, 2019, 14:33:35 [WARN] Could not refresh upload: itch.io API error (400): /uploads/1132292: you must buy this game to download
August 31, 2019, 14:33:35 [INFO] Passed:
August 31, 2019, 14:33:35 [INFO]   ☁ kemo-coliseum-patrons-windows-patreon.zip :: 443.66 MiB :: #1132292
August 31, 2019, 14:33:35 [INFO]     Executable :: Windows all
August 31, 2019, 14:33:35 [INFO]     Build 38 for channel (windows-patreon) :: No explicit version :: #182034
August 31, 2019, 14:33:35 [DEBUG] No license agreement, continuing
August 31, 2019, 14:33:35 [INFO] Manifest with 3 actions, picking...



Error stack:
GetFileInformationByHandleEx C:\users\ethan\Application Data\itch\apps\kemo-coliseum-patrons\KemoColiseum.exe: Call not implemented.
github.com/itchio/lake/tlc.WalkAny
	C:/Users/amos/go/pkg/mod/github.com/itchio/lake@v0.0.0-20190703103538-f71861a8a3eb/tlc/walk.go:126
github.com/itchio/dash.Configure
	C:/Users/amos/go/pkg/mod/github.com/itchio/dash@v0.0.0-20190703110303-c813f12a029f/configure.go:168
github.com/itchio/butler/endpoints/launch.DetermineStrategy
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/strategy.go:94
github.com/itchio/butler/endpoints/launch.Launch.func4
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:190
github.com/itchio/butler/endpoints/launch.Launch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:200
github.com/itchio/butler/butlerd/messages.(*LaunchType).Register.func1
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/messages/messages.go:2733
github.com/itchio/butler/butlerd.(*Router).Dispatch.func2
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:310
github.com/itchio/butler/butlerd.(*Router).Dispatch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:319
github.com/itchio/butler/cmd/daemon.(*handler).Handle
	C:/Multi-Runner/builds/58469115/0/itchio/butler/cmd/daemon/daemon.go:115
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1337
github.com/itchio/butler/endpoints/launch.DetermineStrategy
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/strategy.go:99
github.com/itchio/butler/endpoints/launch.Launch.func4
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:190
github.com/itchio/butler/endpoints/launch.Launch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:200
github.com/itchio/butler/butlerd/messages.(*LaunchType).Register.func1
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/messages/messages.go:2733
github.com/itchio/butler/butlerd.(*Router).Dispatch.func2
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:310
github.com/itchio/butler/butlerd.(*Router).Dispatch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:319
github.com/itchio/butler/cmd/daemon.(*handler).Handle
	C:/Multi-Runner/builds/58469115/0/itchio/butler/cmd/daemon/daemon.go:115
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1337
github.com/itchio/butler/endpoints/launch.Launch.func4
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:192
github.com/itchio/butler/endpoints/launch.Launch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:200
github.com/itchio/butler/butlerd/messages.(*LaunchType).Register.func1
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/messages/messages.go:2733
github.com/itchio/butler/butlerd.(*Router).Dispatch.func2
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:310
github.com/itchio/butler/butlerd.(*Router).Dispatch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:319
github.com/itchio/butler/cmd/daemon.(*handler).Handle
	C:/Multi-Runner/builds/58469115/0/itchio/butler/cmd/daemon/daemon.go:115
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1337
github.com/itchio/butler/endpoints/launch.Launch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/launch/launch.go:202
github.com/itchio/butler/butlerd/messages.(*LaunchType).Register.func1
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/messages/messages.go:2733
github.com/itchio/butler/butlerd.(*Router).Dispatch.func2
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:310
github.com/itchio/butler/butlerd.(*Router).Dispatch
	C:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:319
github.com/itchio/butler/cmd/daemon.(*handler).Handle
	C:/Multi-Runner/builds/58469115/0/itchio/butler/cmd/daemon/daemon.go:115
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1337
`````

**Comment by fasterthanlime** [comment]
Hi! That is one hell of a use case, didn't realize Lutris did that (run the *entire itch app* within Wine), 

As far as I can tell, yes, that is a wine bug (or rather, a wine stub).

The relevant bit of code in butler is this: 

```go
        file, err := eos.Open(containerPath)
	if err != nil {
		return nil, errors.WithStack(err)
	}

	defer file.Close()

	stat, err := file.Stat()
	if err != nil {
		return nil, errors.WithStack(err)
	}
```

I've created a test Go program that showcases the system calls made: https://gist.github.com/fasterthanlime/ec8177b114fa9f711d90b95b49a0e236

With Go 1.13 on Windows 64-bit:

`gostat os C:\Users\amos\ntuser.ini` calls only Go's `os.Stat`, which translates into this Windows calls:

![image](https://user-images.githubusercontent.com/7998310/65435861-78979d80-de21-11e9-8ea4-b3026082482a.png)

`gostat file C:\Users\amos\ntuser.ini` calls Go's `os.Open`, then `.Stat` on the opened file, which translates into these Windows calls:

![image](https://user-images.githubusercontent.com/7998310/65435964-a41a8800-de21-11e9-900d-e63328cfce3a.png)

If we look at Wine 4.16's sources, in `dlls/kernelbase/file.c`, then indeed, we find that calling `GetFileInformationByHandleEx` with `FileAttributeTagInfo` is unimplemented:

![image](https://user-images.githubusercontent.com/7998310/65436282-3753bd80-de22-11e9-882f-faf1686286da.png)

So, definitely a wine bug. I can think of a workaround for this particular case, but it will affect other Go applications on Wine and it's probably not that terribly hard of a fix, so I'm strongly in favor of the Wine fix instead!

**Comment by leafo** [comment]
If you're just trying to play the game, the itch app enables games to implement DRM by giving them a special API key as an environment variable when the game is started. If you can get those values you can start the game not within the app.

There's more details here https://itch.io/docs/itch/integrating/manifest-actions.html under `API key & scoping`. The relevant environment variables are `ITCHIO_API_KEY` and `ITCHIO_API_KEY_EXPIRES_AT`

**Comment by TheristheWolf** [comment]
I have filed [a bug report with the Wine project](https://bugs.winehq.org/show_bug.cgi?id=47813), and as of Wine version 4.17, a patch that fixes the issue described in this issue report has been mainlined.  Anyone else who experiences this issue should be able to address it by changing the Lutris settings for the Itch.io app to use a version of Wine that is at least 4.17 (forks of Wine, such as Proton and Lutris's flavor of Wine, probably do not include the relevant patch as of this writing, but may presumably incorporate it eventually).
