### ISSUE TITLE
Failure to create shortcut on desktop fails the whole installation?

### ISSUE THREAD

**Issue by birbilis** [itchio/itch#2330]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 14:29:17, ref 57838bc373361f2c8938336674247f869999e862

Exception occurred. (Unable to save shortcut "C:\Users\xx\OneDrive\\?p?????st??\itch.lnk".)
while creating shortcut
----

Note: 
- xx is the username (replaced here)
- "?p?????st??" displayed in the path seems to be the Greek word "Υπολογιστής" which OneDrive uses for the desktop folder when it is set to store Documents, Desktop etc. folders (which tends to be the norm in more recent Win10 versions with Defender to help against ransomware that encrypt one's files [since on can get older file versions from the cloud storage history]). Should in fact be saying "Επιφάνεια Εργασίας" but that's an OneDrive peculiarity (calling the Desktop as Computer in Greek)
- question is why fail the whole installation if just the shortcut can't be created on the desktop. I would be able to use the start menu entry and make a desktop shortcut myself

**Comment by birbilis** [comment]
had to use an extra \\ before ?p above so that it displayed correctly in the markdown (it was eating up the \\ after "OneDrive" in the path )

**Comment by birbilis** [comment]
just verified that the issue is with those Greek characters in the pathname of the redirected (by OneDrive) desktop folder. 
I renamed Desktop folder in OneDrive to Desktop1 (if one right-clicks and selects Properties they can see that its real name is Υπολογιστής, but uses a desktop.ini system+hidden file to define a local resource name). 
Then created a Desktop folder in there.
Then right clicked the Desktop1 and at Properties/Location (refers to the redirected desktop location) selected the newly created Desktop folder.
Replied Yes to the question about moving all files. 
Then deleted the old Desktop1 (the one that was called "Υπολογιστής" in the filesystem) folder 
and installed itch.io client app file

so some fix is needed there regarding Unicode (?) characters in filepaths or something like that

**Comment by birbilis** [comment]
...after installation when I first run it tries to do some post-installation steps and has some failure validating butler, don't think it is related to the issue above though, will post a separate issue if it keeps on doing it

**Comment by mbkh** [comment]
same here, with the windows user name written in russian: "C:\Users\????\Desktop\itch.lnk"

**Comment by fasterthanlime** [comment]
@mbkh also with OneDrive enabled?

I'm thinking this may be more closely related to another Windows security feature which "prevents system modifications".

I'm gonna have to figure this one out as I wasnt to add shortcut creation for games too, but if we need to go through an UAC prompt for that well, that won't be fun.

**Comment by birbilis** [comment]
I think the issue may be with the encoding of the filenames and not security-related. After all I managed to work arround the issue by getting rid of the Greek characters in the pathname

**Comment by birbilis** [comment]
anyway the first step would be to make the installation not fail if it can't create the shortcut, just show a message or open a webpage where the user can see instructions on how to create a shortcut themselves (say drag-dropping the icon from the start menu to the desktop)

**Comment by birbilis** [comment]
btw, if the installer is running under user's account it should definitely have full access (same as the user has) to the desktop (so no UAC needed), whether it is redirected to onedrive folder for auto backup to cloud or not (that feature is promoted by MS [and actively suggested via the Windows Defender UI] as extra security against ransomware, since OneDrive has free undo functionality for several days)

**Comment by birbilis** [comment]
In what installation-authoring environment or language/compiler is that installer authored? Could help with looking up if others are having this issue (with paths containing localized characters) with installers or software authored in the same environment

**Comment by mbkh** [comment]
@fasterthanlime, no OneDrive here. feels like it's entirely about having non-English letters in the username. i created a new windows user without Russian letters and installation completed successfully

**Comment by birbilis** [comment]
Not just the username (I have english one), the path in general

**Comment by fasterthanlime** [comment]
itch-setup 1.19.0 is out (and is what's served on https://itch.io/app) and it handles non-ANSI characters properly.

If you were still having the issue, please re-download the latest installer and confirm here that it's fixed for you.
