### ISSUE TITLE
Cannot install itch 25.4.0 

### ISSUE THREAD

**Issue by redkatgames** [itchio/itch#2333]
Cannot install itch 25.4.0 on Windows 7 64 bit via itch-setup.exe

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 14:28:23, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP Range header not supported
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:133
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.readDirectoryEnd
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:476
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*Reader).init
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:80
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.NewReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:73
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:261
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:263
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
while installing
Error during warm-up

**Comment by fasterthanlime** [comment]
Not sure what happened there, maybe a problem on the CDN in front of broth.itch.ovh?

Latest installer works fine here, does it still happen for you?
