### ISSUE TITLE
SDL2 prerequisites

### ISSUE THREAD

**Issue by andreas-jonsson** [itchio/itch#2347]
It would be nice if [SDL2](https://www.libsdl.org/download-2.0.php) (+ mixer, image etc.) would be an option as a prerequisite.
I think it is a quite common framework for games to use.

**Comment by fasterthanlime** [comment]
There is no standard "redistributable package"

**Comment by fasterthanlime** [comment]
I'm not inclined to do that but I'll explain more:

  * I know Steam Runtime ships with SDL2 - one reason for that is they have core members of SDL on their payroll.
  * There is no standard redistributable for SDL2 the way there is for, say, VC++, .NET, etc. - there is no standard install location, just zips full of .DLL files
  * I'm worried about compatibility issues
  * Downloading and running the game individually is an option on itch.io, the app is not the only way to launch games

For that reason, I'd recommend that developers bundle whichever version of SDL2 they built against *directly with the game*, much like most libraries. Redists/prerequisites are the exception, not the rule.
