### ISSUE TITLE
Something with the old version

### ISSUE THREAD

**Issue by SergentMarvyn** [itchio/itch#2349]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/LATEST: dial tcp 35.186.213.53:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up

**Comment by fasterthanlime** [comment]
Does it work for you now? That link seems up
