### ISSUE TITLE
No Compatible Uploads Were Found For This Title

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#2352]
The author of [Sarah's Run](https://sophieh.itch.io/sarahs-run) ([SophieH](https://sophieh.itch.io/)) uploaded a zip file containing a directory with all the standard Unity game files in it. But Itch doesn't seem to recognize that it should look for the executable in the directory when there isn't one in the root of the zip file.

![Download Sarah's Run by Sophie Houlden - itch io - itch](https://user-images.githubusercontent.com/227734/70485849-57079300-1aad-11ea-9f70-b8daad7408af.png)

![Download Sarah's Run by Sophie Houlden - itch io - itch Error](https://user-images.githubusercontent.com/227734/70485862-5cfd7400-1aad-11ea-97fe-babaf202f89d.png)

Is this expected behavior? Or should Itch be smart enough to look for an executable in a subdirectory?

Oh, and this is the download for Windows. I didn't try the Mac or Linux downloads.

**Comment by fasterthanlime** [comment]
> But Itch doesn't seem to recognize that it should look for the executable in the directory when there isn't one in the root of the zip file.

That's not it - it can't find compatible uploads, not launch targets.

And that's because none of the uploads were tagged:

![image](https://user-images.githubusercontent.com/7998310/70503463-bd2efd00-1b23-11ea-9eb0-bf24a117f826.png)

I went ahead and fixed the game page :)

**Comment by Deozaan** [comment]
I see. Thanks for clearing that up.

Is there something that can or should be done to make better from a user experience perspective? Such as allowing the user select which zip file should be downloaded/installed?

**Comment by fasterthanlime** [comment]
> Is there something that can or should be done to make better from a user experience perspective? Such as allowing the user select which zip file should be downloaded/installed?

Although I'd still like tagging to be properly done (and that part can be automated, still haven't been able to deploy it yet), I'm working on including an "others" section when picking uploads so that you can install untagged uploads (or bonus content, etc.)

**Comment by CalAlaera** [comment]
This seems like something the user should be able to override by selecting one of the available uploads. This has happened again with https://unboundcreations.itch.io/headliner-novinews/ and it's an easy slip for the developer to make - perhaps, instead of simply saying "No compatible uploads", the client could offer the user the choice of the uploads which are there? This way we don't have the wait for the devs to tag their uploads.
