### ISSUE TITLE
When running the itch-setup it gives an error

### ISSUE THREAD

**Issue by KadenT8** [itchio/itch#2358]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 03:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://w3g3a5v6.ssl.hwcdn.net/build/116009/437355-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1579571803&Signature=P6CMwC8xlYiCkaAPVX3KYt9CJ57fLtovBG0C1EkTB20Y4BOOG2RyyHeTVuTtzalAqqFFynDXhwHrmsABpXLScG5EWyN4Na1C4jLpM1HQZdVDkGYhyvtCjC76zkR%2B5pWA%2B48Uh1CqB7%2Bo7F3ZicpOBj0tPdZAVDUbh0MKY2H%2FIDLvhK5CWcbXdhynwJ5is4YquwBygFxe6nXtuvb%2Fty7SdGY6Ecr0xheZA8Pf9C6bjYj3R%2FFdoaYW2T1wlClJJCAwCrk87JuK8B1J6rEnQ7V8KygNNfSErkaIKKtkIkNe6LxHtiQdNPT1sizDfsqSHgEW2UlR75mxgTr16CDNdjAFtw==&hwexp=1579572093&hwsig=b94a40f40c3e0aab51ca46df3968c361: x509: certificate has expired or is not yet valid
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

![itcherror](https://user-images.githubusercontent.com/47905721/72769113-0ef88780-3ba6-11ea-9fb5-3d8fb3fee1ae.png)

**Comment by fasterthanlime** [comment]
Apparently our CDN was slightly late in renewing the certificate but
everything should be working now

**Comment by KadenT8** [comment]
yup all good
