### ISSUE TITLE
Error during warm-up

### ISSUE THREAD

**Issue by Kirbyrocket** [itchio/itch#2371]
```
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/LATEST: dial tcp 35.186.213.53:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up
```

**Comment by fasterthanlime** [comment]
Well, I've never seen that *specific* error before, but it shouldn't be a permanent thing. Did launching it again fix it?

**Comment by Kirbyrocket** [comment]
> Well, I've never seen that _specific_ error before, but it shouldn't be a permanent thing. Did launching it again fix it?

Launching again didn't work and opening on a different drive didn't work.

**The only solution that I found was to run the initial installation wizard as Administrator.**

**Comment by fasterthanlime** [comment]
> The only solution that I found was to run the initial installation wizard as Administrator.

I see. That it worked when you ran as administrator was pure luck - it definitely won't have an effect on "how long either host takes to respond to a network connection attempt".

As a general rule of thumb:

  * Running itch-setup as administrator never fixes anything - it's especially designed to run as a regular, unprivileged user. Administrator privileges only cause more trouble, I'm thinking of disallowing that completely
  * Network errors come and go, there's many many potential suspects, including your Internet service provider, our CDN provider, and everything in between.

Glad it's working for you now, though!
