### ISSUE TITLE
RenPy app save failures

### ISSUE THREAD

**Issue by LukeVaxhacker** [itchio/itch#2372]
When I launch a RenPy app from within the itch.io client and try to save, I get an exception Not saved - no valid save locations. If I launch from the MacOS Finder, works fine. Also seems to not save various states. RenPy seems to use ~/Library/RenPy for its files.

itch.io client is in Applications (general one, not user). Install location is in a public folder but different.

PhillyGames is saying your client should only be used for installs and not launching, which doesn't seem right, but somehow is right in his head.

**Comment by fasterthanlime** [comment]
Do you have the itch.io sandbox enabled?

(That's the most likely explanation)

**Comment by LukeVaxhacker** [comment]
Yes, I'll disable and give it a try, although it's curious that PhillyGames was recommending against using the itch.io to launch.

**Comment by LukeVaxhacker** [comment]
Able to save in Queen's Curse and City of Broken Dreamers. Thanks, I'll let PhillyGames know.
