### ISSUE TITLE
Error: HTTP 405 /login     at Client.<anonymous> 

### ISSUE THREAD

**Issue by squidlin** [itchio/itch#2375]
it won't start and it says 

Error: HTTP 405 /login
    at Client.<anonymous> 
 
I don't know what that means or how to fix it (sorry in advance but I don't know anything about coding, just want to play some viddy games)

**Comment by fasterthanlime** [comment]
No problem. Just exit the app (Ctrl+Q), download the latest version from https://itch.io/app and you should be good to go!
