### ISSUE TITLE
Add game shortcuts to desktop or system menu

### ISSUE THREAD

**Issue by SolarLune** [itchio/itch#2383]
Hey, there.

I looked around and didn't see any issues for this, but it feels like it would be a good option to be able to add shortcuts to games in the library to the desktop and to the start / system menu. 

Not sure how complex that would be to add with the current codebase; if it's prohibitively expensive, then this can be closed.

Thanks!

**Comment by gardenappl** [comment]
#864 covers this already. The dev says there might be some progress, but that was more than a year ago sadly.

**Comment by SolarLune** [comment]
Ah, so it does. I'll close this, then. Thanks!
