### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by gleblebedev** [itchio/itch#2384]
Hey.

With .net core I can make an app that runs everywhere. For the same .net assembly could be executed on every platform. Under the hood the app can use SDL for window management, etc.

Currently itch.io only supports .net framework as a prerequisity but not .net core.

Is it possible to fix this?

Is there an open source part of the itch that community can work on to extend the compatibility?

**Comment by fasterthanlime** [comment]
Seems like we have .NET Core 2, only for Windows though: https://github.com/itchio/itch/issues/1746#issuecomment-378549499

The desktop app is entirely open source, the prerequisites repository isn't though - we want to control closely what executables get to run with Administrator privileges, for obvious reasons :)

For distributing .NET apps in general (Core or not), I recommend bundling the required runtime with them. Installing prerequisites is not a great experience, even when it's automated (ie. for users of the itch desktop app). For example, all Unity games (except for IL2CPP ones) require a .NET runtime, they just bundle it, and then the game runs without any prior setup :)

**Comment by gleblebedev** [comment]
If you have .net core then please update documentation to list it among valid frameworks.
