### ISSUE TITLE
🏁 Issue v23.6.1 - Unity-made games won't launch when UnityCrashHandler64 is present

### ISSUE THREAD

**Issue by Racso** [itchio/itch#2387]
Hi!

Since some version ago, Unity builds include one or two "UnityCrashHandler" .exe files. It seems that Itch is unable to launch games that include those (possibly because it tries to run one of them instead of the game's .exe?).

I've managed to check this by deleting the UnityCrashHandler file of a game that didn't launch. It then launched correctly.

**Comment by fasterthanlime** [comment]
Hi, v23 isn't supported anymore. You can download v25 from https://itch.io - it's a manual upgrade.

That bug shouldn't be an issue in v25 as it handles launch target detection and scoring differently.
