### ISSUE TITLE
I'm try to reinstall itch.io and this happen 

### ISSUE THREAD

**Issue by Servaral** [itchio/itch#2390]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 18:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://w3g3a5v6.ssl.hwcdn.net/build/116009/437355-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1588766409&Signature=falAbMBvtNex3NIG26edlqFvfBJ5BgyMXimlOvHrlHN7usEMaJOVaDlGLNcsTpQWa09%2BgTsMVHOvbY1gRrxXx1dPOJRUasS8nwUD6h%2FYufnKB9lnCZSbpgZnFlTpbpEE1Op2PpxWaH3gNE2peQidZL8lxRvdzSLiJWfBcK70h0zjbQMMNt3cvS%2Fs2jddlWKPnH3dcd%2BRESNukWM8qEJ9p7BBl8MaviHDLZibi3Hp1boezzGaz1bg96H5XtgbdqxvD3NpPCR60m%2ByzgvPXJ5nSbIXHbj0qWt781fuLnjPZZWsg0IL0s%2FRkdHtNEf6AR%2F0iXoVmfb1zHgXtTldDWTfhw==&hwexp=1588766699&hwsig=2aa44286d4fcd55787b206d8914be570: x509: certificate signed by unknown authority
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by Servaral** [comment]
If there any way to fix this

**Comment by fasterthanlime** [comment]
Are you on Windows? macOS? Linux ?

**Comment by Servaral** [comment]
> Are you on Windows? macOS? Linux ?

I'm using window 7

**Comment by Servaral** [comment]
> > Are you on Windows? macOS? Linux ?
> 
> I'm using window 7

64

**Comment by fasterthanlime** [comment]
What Antivirus do you have installed? Are you behind a proxy?

Can you try running https://fasterthanlime.itch.io/itch-diag ?

**Comment by Servaral** [comment]
i use avg and i'm just unstall it yesterday 
i have try and open itch-diag but it automastic close

**Comment by fasterthanlime** [comment]
Ah, it's possible that itch-diag just does not work on Windows 7, I don't remember trying it there.

Did uninstalling AVG help? Are you still getting that error? I'm not sure exactly where the problem comes from exactly, there can be a variety of causes, some local, some not.

**Comment by Servaral** [comment]
> Ah, it's possible that itch-diag just does not work on Windows 7, I don't remember trying it there.
> 
> Did uninstalling AVG help? Are you still getting that error? I'm not sure exactly where the problem comes from exactly, there can be a variety of causes, some local, some not.

I have try and it showing the same thing

**Comment by Servaral** [comment]
i have delete the itch.io folder in my c drive by doing delete

**Comment by Servaral** [comment]
Before this happen

**Comment by Xananax** [comment]
It seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by aktentasche** [comment]
Duplicate of #2389
