### ISSUE TITLE
25.4.0 "broth.itch.ovh: HTTP 404: Invalid file requested"

### ISSUE THREAD

**Issue by hmaon** [itchio/itch#2397]
Getting this error when trying to install the app:

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP 404: Invalid file requested

github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:148
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
io.(*SectionReader).Read
	C:/Go/src/io/io.go:475
bufio.(*Reader).fill
	C:/Go/src/bufio/bufio.go:100
bufio.(*Reader).ReadByte
	C:/Go/src/bufio/bufio.go:249
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).moreBits
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:713
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).nextBlock
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:317
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).Read
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:365
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*pooledFlateReader).Read
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/register.go:92
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*checksumReader).Read
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:200
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy.DoBuffer
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy/ctxcopy.go:26
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy.Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy/ctxcopy.go:13
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).healOne
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:318
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:272
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by fasterthanlime** [comment]
Hey, I'm not able to reproduce the issue.

Are you still experiencing that?

**Comment by anb9008** [comment]
I am having exactly the same error

**Comment by Yernemm** [comment]
I have a similar error. Trying to install this app for the first time on this PC and it doesn't seem to work. Seems like a web server issue?

**Comment by Kreuger** [comment]
I have this error as well, on linux.

**Comment by ghost** [comment]
Me too. Also on Linux.

**Comment by ghost** [comment]
I reran the installer and it works. Intermittent server issue maybe? (Github isn't letting me edit my previous comment for some reason.)

**Comment by keysmashes** [comment]
It certainly seems like an intermittent server issue; I got this error twice:

    broth.itch.ovh: HTTP 404: Invalid file requested

then:

    htfs.Open (initial request): HTTP file not found on server

then on the fourth try it worked fine.

**Comment by Corni-B** [comment]
-EDIT: I got the installer to run and installed the app. Guess it just takes some persistence to connect to the servers right now.-

Having this problem too. Tried re-running the installer a few times, then deleting and re-downloading it. Couldn't get it to work. Could it have something to do with higher server traffic from the bundle?

**Comment by firewaran** [comment]
I had the same error .
I solved it by redownloaded the setup manually from here: https://itch.io/app

After that the steup continued with the warmup and the installation continued.
I noticed that both versions had different file size, 
the one which got downloaded in the "older" client had only 11.791kb on windows
and second one directly from the link above was 13.652kb.

**Comment by hmaon** [comment]
No error today installing with the same binary I'd downloaded previously.  Everything installs fine.

**Comment by wchristian** [comment]
Still happening.

**Comment by wchristian** [comment]
The main download link here also fails occasionally: https://itch.io/app

**Comment by Brokemia** [comment]
I'm having this issue, also on Linux

**Comment by BloomNobly** [comment]
Having this issue too, ran the setup as an administrator after first warmup failed. (Run 64 bit Windows)

**Comment by darthdeus** [comment]
Having the same issue, tried re-downloading which didn't help, but running as Administrator did. The download was incredibly slow though, so if others are still having this issue it could be just itch.io being overloaded from the bundle sales or something.

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
