### ISSUE TITLE
Tried to install and it imediatly failed. 

### ISSUE THREAD

**Issue by jediknight36** [itchio/itch#2400]
Win 10

Dbl clicked exe and this came up

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 04:29:17, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP 404: Invalid file requested

github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:148
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
io.(*SectionReader).Read
	C:/Go/src/io/io.go:475
bufio.(*Reader).Read
	C:/Go/src/bufio/bufio.go:223
io.ReadAtLeast
	C:/Go/src/io/io.go:310
io.ReadFull
	C:/Go/src/io/io.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.readDirectoryHeader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:257
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*Reader).init
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:104
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.NewReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:73
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:261
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:263
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by jediknight36** [comment]
Tried again and it worked

**Comment by anb9008** [comment]
For anyone else - I had same issue and I'd guess I had to try around 10 times. Just keep trying.

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. As the two users above said: wait a bit and try again

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
