### ISSUE TITLE
Can't install launcher

### ISSUE THREAD

**Issue by pengawill** [itchio/itch#2405]
I'm having some trouble installing. Sometimes the installer will fail during Warm Up, and sometimes it'll fail as soon as it tries to download anything. I have my antivirus off as well. Here's the log:

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:29:17, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP 404: Invalid file requested

github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:148
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.readDirectoryEnd
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:476
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*Reader).init
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:80
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.NewReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:73
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:261
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:263
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by Courage-pupper** [comment]
I'm having the same issue. My guess it's servers overloaded because it gets stuck trying to go through the download process

**Comment by dustypants2005** [comment]
Same.

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:253
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by kaosine** [comment]
Yeah same here on linux. Kinda stinks since I decided to change distros out of the blue so that means I gotta reinstall it...it'd be nice if we could just download it from this github instead....I just wanted to install some of the games from that massive bundle that I've been trying to get all the games and tools to show up in my library since they don't just automatically add them when you buy something like that...

**Comment by ghost** [comment]
I assume it's something server side. It didn't work for me a few hours ago but just checked it now and it downloads fine.

**Comment by AihjawvBawiuojfvnW0of92** [comment]
Same issue, im just gonna keep trying untill it works

**Comment by Xananax** [comment]
> I'm having the same issue. My guess it's servers overloaded because it gets stuck trying to go through the download process

Yep, most probably. Keep trying peeps, but leave a bit of time between tries

**Comment by EugeneGGHQ** [comment]
Samesies.

**Comment by Courage-pupper** [comment]
Worked for me late at night after a few tries. Definetly server issues probs a ton of people got the bundle and servers are overloaded.

**Comment by dustypants2005** [comment]
The app finally installed. 

But all the games from the "Bundle for Racial Justice and Equality" are not showing up in the app. I'm guessing the servers are getting hit hard and that's why I'm running into issues.

**Comment by fasterthanlime** [comment]
> But all the games from the "Bundle for Racial Justice and Equality" are not showing up in the app. I'm guessing the servers are getting hit hard and that's why I'm running into issues.

That's a separate issue. The games from that bundle will only show up:

  * After you click "Download" from the bundle page, which will add them to your account proper (this used to be automatic, but this bundle has nearly 1500+ games, and has been purchased 360K+ times)
  * After the app refreshes your library data from the server (there's a local cache)

I believe if you just follow the "web download" flow but from within the app everything should work fine as in that case it's getting download information directly from the web page, but other recent changes may have broken that too.

**Comment by Courage-pupper** [comment]
> That's a separate issue. The games from that bundle will only show up:
> 
>     * After you click "Download" from the bundle page, which will add them to your account proper (this used to be automatic, but this bundle has nearly 1500+ games, and has been purchased 360K+ times)


I even find this useful for this kind of bundle. Easier to just start by creating the collections of the ones you're truly interested and not bloat your library.

**Comment by mircohacker** [comment]
see https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for a workaround

**Comment by AihjawvBawiuojfvnW0of92** [comment]
> see [#2403 (comment)](https://github.com/itchio/itch/issues/2403#issuecomment-641644737) for a workaround

On linux does this add the desktop icon

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
