### ISSUE TITLE
Something went wrong- Itch setup 25.4.0

### ISSUE THREAD

**Issue by EmmyFem** [itchio/itch#2407]
I would just like a bit of support just so I can understand what the following error message means.

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by EchoBaz** [comment]
I got the same problem.

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
