### ISSUE TITLE
cannot download set up

### ISSUE THREAD

**Issue by worm72** [itchio/itch#2409]
i keep getting this error:

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:28:23, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP 404: Invalid file requested

github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:148
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
io.(*SectionReader).Read
	C:/Go/src/io/io.go:475
bufio.(*Reader).Read
	C:/Go/src/bufio/bufio.go:223
io.ReadAtLeast
	C:/Go/src/io/io.go:310
io.ReadFull
	C:/Go/src/io/io.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.readDirectoryHeader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:257
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*Reader).init
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:104
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.NewReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:73
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:261
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:263
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
while installing
Error during warm-up

**Comment by thesquaregroot** [comment]
It seems like there's something going on with broth.itch.ovh right now which is preventing the install from continuing.

https://www.isitdownrightnow.com/broth.itch.ovh.html

Here's the output I got on my Pop!_OS system:

> 2020/06/09 21:13:42 itch-setup will log to /tmp/itch-setup-log.txt
> 2020/06/09 21:13:42 =========================================
> 2020/06/09 21:13:42 itch-setup "v1.18.0, built on Apr 10 2019 @ 07:30:34, ref 57838bc373361f2c8938336674247f869999e862" starting up at "2020-06-09 21:13:42.339736375 -0400 EDT m=+0.003528339" with arguments:
> 2020/06/09 21:13:42 "./itch-setup"
> 2020/06/09 21:13:42 =========================================
> 2020/06/09 21:13:42 App name specified at build time: itch
> 2020/06/09 21:13:42 Locale:  en-US
> 2020/06/09 21:13:42 Initializing installer GUI...
> 2020/06/09 21:13:42 Using GTK UI
> 2020/06/09 21:13:42 Initializing (itch) multiverse @ (/home/groot/.itch)
> 2020/06/09 21:13:42 No multiverse information yet
> 2020/06/09 21:13:42 Loading image resources...
> 2020/06/09 21:13:42 Setting up progress bar...
> 2020/06/09 21:13:42 Positioning and showing window...
> 2020/06/09 21:13:47 Will install version 25.4.0
> 2020/06/09 21:13:49 Reading signature...
> 2020/06/09 21:13:49 Installing 161.71 MiB (72 files, 2 dirs, 0 symlinks)
> 2020/06/09 21:13:49 (25.4.0) is not installed yet, let's go through staging
> 2020/06/09 21:13:49 Installing to (/home/groot/.itch/staging/app-25.4.0)
> 2020/06/09 21:13:49 Healing (/home/groot/.itch/staging/app-25.4.0)...
> 2020/06/09 21:14:03 Fatal error: Warm-up error: while installing: broth.itch.ovh: HTTP 404: Invalid file requested

**Comment by sdubrick** [comment]
This workaround seemed to work for me - go to https://broth.itch.ovh/itch/windows-amd64/25.4.0 and download 'archive-default' and extract the zip to some folder.

**Comment by thesquaregroot** [comment]
I had to change "windows" to "linux" but that worked for me as well.

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
