### ISSUE TITLE
OS X - "click to restart and update" doesn't fully close the app, doesn't update.

### ISSUE THREAD

**Issue by latenitecali** [itchio/itch#241]
It seems that clicking the "click to restart and update" link after the update downloads only closes the app window, but keeps the app running, so it doesn't update.

**Comment by fasterthanlime** [comment]
@jonathanhirz what version did you experience that on? if it's before 0.10.4, it's a known issue (#167).

**Comment by fasterthanlime** [comment]
Newer versions handle that properly. To work around the bug in <0.10.4, just quit the app completely (Cmd-Q) and launch it again, it should be the new version.

**Comment by latenitecali** [comment]
Sorry I didn't catch the version number when I updated today, but it's been at least a few days since I updated it last. I'm sure I was on an old version, glad it's known and fixed :)

Great app!

**Comment by fasterthanlime** [comment]
Alright, good to hear! Had a few false starts as far as auto-updating is concerned, both on windows & osx, I'm really glad it's over :)

Thanks for the kind words!
