### ISSUE TITLE
HTTP file not found on server

### ISSUE THREAD

**Issue by Snesmocha** [itchio/itch#2410]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:253
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

the error

**Comment by ScottBeeson** [comment]
Same

**Comment by ypemma** [comment]
Glad to see lots of other folks opening this issue. Same issue here, now I know it's not my fault!

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by igromad** [comment]
If the bundle costs $5 and it raised $4 million, imagine how many people are downloading it

**Comment by mircohacker** [comment]
see https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for a workaround

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
