### ISSUE TITLE
Cannot install launcher

### ISSUE THREAD

**Issue by Ideal-Void** [itchio/itch#2414]
The installer tells me the following message...
```
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 04:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
while opening remote signature file
Error during warm-up
```
I've looked at the other issues of similar errors, but I haven't found this one yet.

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by davr** [comment]
See https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for workaround

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
