### ISSUE TITLE
Cannot install launcher

### ISSUE THREAD

**Issue by ThreadingFate** [itchio/itch#2415]
[ItchLauncherError.txt](https://github.com/itchio/itch/files/4756005/ItchLauncherError.txt)
I've attached the error log along with this post.

**Comment by avascherocman** [comment]
Have the exact same problem and same error log. On Windows 10 Build 18362 if that's helpful.

**Comment by ThreadingFate** [comment]
I should have mentioned this was also Windows 10. Please let me know if I can provide any additional information to help resolve this problem for everyone it's happening to.

**Comment by Ptmc518** [comment]
Same error on Windows 10 Build 19041

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:28:23, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/signature/default?downloadSessionId=d508e5e1-05bf-4de4-aae3-2b9cba54cb6e: unexpected EOF
htfs connect
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by mircohacker** [comment]
see https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for a workaround

**Comment by ThreadingFate** [comment]
Comment #2403 solved this issue for me.
