### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by Feral-Void** [itchio/itch#2418]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 08:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default?downloadSessionId=551dd9f4-d3aa-42be-bb04-d53c0fa1d552: unexpected EOF
htfs connect
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:263
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by Ptmc518** [comment]
Similar error for me.

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:28:23, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/signature/default?downloadSessionId=d508e5e1-05bf-4de4-aae3-2b9cba54cb6e: unexpected EOF
htfs connect
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by Xananax** [comment]
Seems like the servers are under a lot of stress. Wait a bit and try again

**Comment by davr** [comment]
See https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for workaround
