### ISSUE TITLE
Another error on Installer

### ISSUE THREAD

**Issue by Feral-Void** [itchio/itch#2419]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 08:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/signature/default?downloadSessionId=7beb0c2b-c825-4e28-927e-676e2a454e59: unexpected EOF
htfs connect
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by davr** [comment]
See https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for workaround

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
