### ISSUE TITLE
[win32] game BoltStorm broken for v0.11.3

### ISSUE THREAD

**Issue by mxjones** [itchio/itch#242]
:rotating_light: Game [BoltStorm](http://kualitygames.itch.io/boltstorm) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9b68df6d4e4718872528).

I only posted this because I clicked the button - It seems it is because the download is a rar file.

**Comment by fasterthanlime** [comment]
> It seems it is because the download is a rar file.

Yep, that's it! Can you try to contact the developer and tell them [about this page](http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games)? Let me know if you need help doing that and/or would rather not do it.
