### ISSUE TITLE
Warm-up error

### ISSUE THREAD

**Issue by RazorManager89** [itchio/itch#2421]
I'm getting this very strange error that seems to pop up arbitrarily when I try to install Itch on Linux.

`
```
itch-setup, v1.18.0, built on Apr 10 2019 @ 13:30:34, ref 57838bc373361f2c8938336674247f869999e862

Open issue tracker

Warm-up error: while installing: broth.itch.ovh: HTTP 404: Invalid file requested

```
Sometimes, I get this other one:
```
`itch-setup, v1.18.0, built on Apr 10 2019 @ 13:30:34, ref 57838bc373361f2c8938336674247f869999e862

Open issue tracker

Warm-up error: while installing: htfs.Open (initial request): HTTP file not found on server`


```
What makes this even more annoying and arbitrary is that progress is completely random when installing. Sometimes it happens at 30%, others at 24% but most times at 0%.
What is going on?

**Comment by seecinq** [comment]
running this file https://broth.itch.ovh/install-itch/linux-portable-amd64/_14/unpacked/default produces same error.

**Comment by davr** [comment]
See https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for workaround

**Comment by seecinq** [comment]
it 

> See [#2403 (comment)](https://github.com/itchio/itch/issues/2403#issuecomment-641644737) for workaround

works on debian.

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
