### ISSUE TITLE
Hi, I can't download the app it keeps giving me errors

### ISSUE THREAD

**Issue by ElleKade** [itchio/itch#2423]
I am trying to download the app so I can play the amazing bundle deal I just bought, but it keeps giving me this error code, and I am lost when it comes to code. Is there anyone that can help me? 

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:28:23, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP 404: Invalid file requested

github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:148
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
io.(*SectionReader).Read
	C:/Go/src/io/io.go:475
bufio.(*Reader).fill
	C:/Go/src/bufio/bufio.go:100
bufio.(*Reader).ReadByte
	C:/Go/src/bufio/bufio.go:249
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).moreBits
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:713
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).huffSym
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:735
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).huffmanBlock
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:512
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).nextBlock
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:341
github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate.(*decompressor).Read
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/kompress/flate/inflate.go:365
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*pooledFlateReader).Read
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/register.go:92
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*checksumReader).Read
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:200
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy.DoBuffer
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy/ctxcopy.go:26
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy.Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/ctxcopy/ctxcopy.go:13
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).healOne
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:318
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:272
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_386.s:1321
while installing
Error during warm-up

**Comment by mircohacker** [comment]
see https://github.com/itchio/itch/issues/2403#issuecomment-641644737 for a workaround

**Comment by Xananax** [comment]
The bundle's success broke all expectations and is putting the servers under a lot of stress. It's good news in general, but unfortunately for us, it means we're going to have some problems accessing the servers. You can keep trying to download, or wait it out.
Itch is actively working on fixing that problem.

@mircohaug I don't think downloading manually is any different than using the app; it's the same servers, and they are under the same load. But it might feel nicer to have control over it.

**Comment by fasterthanlime** [comment]
This should be fixed now, closing.
