### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by MacGregorsk** [itchio/itch#2424]
1/ THIS :

Un problème est survenu

itch-setup, v1.18.0, built on Apr 10 2019 @ 13:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:253
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

2/ OR SOMETIMES THIS :

Un problème est survenu :

itch-setup, v1.18.0, built on Apr 10 2019 @ 13:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by epiccelt** [comment]
Per dev, it's a server load issue. Keep trying.
https://github.com/itchio/itch/issues/2403#issuecomment-641966476

**Comment by Xananax** [comment]
The bundle's success broke all expectations and is putting the servers under a lot of stress. It's good news in general, but unfortunately for us, it means we're going to have some problems accessing the servers. You can keep trying to download, or wait it out.
Itch is actively working on fixing that problem.

**Comment by MacGregorsk** [comment]
Reading you, I tried once more (was maybe the 5 or 6th time in days) and it finally worked.

Thank you for your thorough answers.
