### ISSUE TITLE
wth

### ISSUE THREAD

**Issue by mcandre** [itchio/itch#2429]
![Capture](https://user-images.githubusercontent.com/5316/84334966-4ec20a80-ab59-11ea-9ba0-019e4dcb9f04.PNG)

**Comment by Xananax** [comment]
The bundle's success broke all expectations and is putting the servers under a lot of stress. It's good news in general, but unfortunately for us, it means we're going to have some problems accessing the servers. You can keep trying to download, or wait it out.
Itch is actively working on fixing that problem.

**Comment by fasterthanlime** [comment]
This should be fixed now.
