### ISSUE TITLE
Warm Up Error

### ISSUE THREAD

**Issue by PhasedFox** [itchio/itch#2432]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

broth.itch.ovh: HTTP 404: Invalid file requested

github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:148
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/conn.go:56
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:329
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).readAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:473
github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs.(*File).ReadAt
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/httpkit/htfs/file.go:444
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.readDirectoryEnd
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:476
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.(*Reader).init
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:80
github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip.NewReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/arkive/zip/reader.go:73
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:261
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:263
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by Skyl3lazer** [comment]
Same here

**Comment by jakeinator21** [comment]
I got this error when running as admin so I could install to Program Files instead of AppData. When I ran it as non-admin it worked fine, but I had to install to AppData instead because without admin access I didn't have permission to install to Program Files.

**Comment by PhasedFox** [comment]
Does the itch app run as admin natively? I didn't elevate it

**Comment by PhasedFox** [comment]
I am running the install from a NAS on the local network. Would that cause a problem?

**Comment by matbonucci** [comment]
same as sudo
Linux x64

**Comment by Xananax** [comment]
It shouldn't have anything to do with needing to be ran as admin.

The bundle's success broke all expectations and is putting the servers under a lot of stress. It's good news in general, but unfortunately for us, it means we're going to have some problems accessing the servers. You can keep trying to download, or wait it out.

Itch is actively working on fixing that problem.

**Comment by fasterthanlime** [comment]
This should be fixed now.
