### ISSUE TITLE
cant install launcher, already bought games

### ISSUE THREAD

**Issue by sparks567** [itchio/itch#2439]
Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default?downloadSessionId=21bfb045-3a3b-4206-8220-28eef7ac12eb: unexpected EOF
htfs connect
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pools/zippool.(*ZipPool).GetReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pools/zippool/zippool.go:116
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).healOne
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:300
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:272
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

**Comment by celadith** [comment]
same error here. looks like a lot of people having the same problem :(

running windows 10.

**Comment by aktentasche** [comment]
You can download what is mentioned in the GET: https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default?downloadSessionId=21bfb045-3a3b-4206-8220-28eef7ac12eb

Install works but servers are not available. Just give it some time, this is surely not a bug but an availability problem.

**Comment by sparks567** [comment]
thank you!

**Comment by fasterthanlime** [comment]
> Just give it some time, this is surely not a bug but an availability problem.

That's correct. I'd recommend just retrying the installer though - there's no reason it would work any better or worse than downloading manually.

I'm not seeing elevated error rates anymore, so I think this is safe to close.
