### ISSUE TITLE
itchio app download and installation issue

### ISSUE THREAD

**Issue by PingasoFromHell** [itchio/itch#2441]
While downloading/installation of the app I get this

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default?downloadSessionId=2e9d0a8d-c5e6-40af-a0fc-80ce802d6662: unexpected EOF
htfs connect
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pools/zippool.(*ZipPool).GetReader
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pools/zippool/zippool.go:116
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).healOne
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:300
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:272
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:274
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:102
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/archive_healer.go:209
github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func5
	C:/Multi-Runner/builds/58469115/0/itchio/itch-setup/src/github.com/itchio/itch-setup/vendor/github.com/itchio/wharf/pwr/validator.go:138
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1337
while installing
Error during warm-up

Please help

**Comment by infinstarlight** [comment]
I am seeing this issue too running on Ubuntu 18.04.4 LTS on Wayland. Not sure if that is related to the issue.

**Comment by lifeindecember** [comment]
Having the same issue on Windows 10, 1909 (Build 18363.900) running on an original SurfaceBook.

Tried running installer with/without "As Admin".

To be clear, I'm getting the exact same error output.

**Comment by oakjwe** [comment]
Same here with Windows 10, 1909

**Comment by lhp22** [comment]
Same issue on Windows 10 1903.

**Comment by nixtaoz** [comment]
Same on Windows 10, 1909

**Comment by MellowedMatt** [comment]
Exact same issue here, Windows 10, 2004. This appears to be a duplicate of #2389

**Comment by sniarchos** [comment]
same here, linux mint 19.3

**Comment by ChunwingNg** [comment]
I had this problem also. It only happens when I try to install it on another drive. I let it install to the default C: drive and it was able to install.

**Comment by zapper83** [comment]
Go to the folder you installed the app, default is C:\Users\USERNAME\AppData\Local\itch, delete it and try to install again. Worked for me.

**Comment by ClarkEagling** [comment]
My fix: download the install zip manually at  https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default 
put the unzipped contents in C:\Users\USERNAME\AppData\Local\itch\staging\ 
and run the itch app found there.

**Comment by amoebaOfDoom** [comment]
That fix did not work for me. I verified that was the correct bundle and downloaded it. I get an error after running saying "There was an problem during setup: Could not retrieve latest version of (itch-setup): net::REQUEST_ERROR::" Seems like there's still connectivity issues.

**Comment by fasterthanlime** [comment]
> My fix: download the install zip manually at https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default
> put the unzipped contents in C:\Users\USERNAME\AppData\Local\itch\staging\
> and run the itch app found there.

This does nothing to help - when there are availability issues, only retrying helps.

I'm not seeing elevated error rates aynmore, closing this. Sorry for the trouble everyone.
