### ISSUE TITLE
Error During Install

### ISSUE THREAD

**Issue by Snozbear** [itchio/itch#2442]
> Something went wrong
> 
> itch-setup, v1.18.0, built on Apr 10 2019 @ 23:28:23, ref 57838bc373361f2c8938336674247f869999e862
> 
> Get https://broth.itch.ovh/itch/windows-amd64/25.4.0/signature/default?downloadSessionId=bc98ff16-631a-43e2-b30c-c0f997172b1b: unexpected EOF
> htfs connect
> htfs.Open (initial request)
> while opening remote signature file
> Error during warm-up

**Comment by zapper83** [comment]
Go to the folder you installed the app, default is C:\Users\USERNAME\AppData\Local\itch, delete it and try to install again. Worked for me.

**Comment by Absentity** [comment]
Retried installing some time later and it worked. No other changes.

**Comment by Snozbear** [comment]
> Go to the folder you installed the app, default is C:\Users\USERNAME\AppData\Local\itch, delete it and try to install again. Worked for me.

I had to do it twice but that worked, thanks!
