### ISSUE TITLE
Windows installer fails if desktop shortcut can't be created

### ISSUE THREAD

**Issue by DeciusMagnus** [itchio/itch#2449]
My desktop folders don't have write permissions so programs don't install icons there; most installers ignore this, but itch.io's installer fails if this occurs.

```
Something went wrong

itch-setup, v1.19.0, built on Jun 16 2020 @ 10:55:56, ref 00c273bf9308a3130b27617727c96ab743ba0d11

husk error: IPersistFile::Save returned system error -2147024891 (0x80070005)
while creating shortcut

**Comment by fasterthanlime** [comment]
I just released itch-setup v1.20.0, which [ignores shortcut creation errors and continues anyway](https://github.com/itchio/itch-setup/commit/53ead45f0d95ff12c6279088fc1960e1335c332a).

You can download it from https://itch.io/app as usual.
