### ISSUE TITLE
[linux] game The Tree broken for v0.11.3

### ISSUE THREAD

**Issue by ericlathrop** [itchio/itch#245]
:rotating_light: Game [The Tree](http://razveck.itch.io/thetree) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cf4a8be31c6516a557ef).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This is actually by design — you can point the developers to http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games
