### ISSUE TITLE
The pt.json file does not exist, which exist are pt_PT.json and pt_BR.json

### ISSUE THREAD

**Issue by bugcrazy** [itchio/itch#2451]
This error message appears when you define languages in Portuguese pt and br in the app "No such locale /home/bcrazy/.itch/app-25.4.0/resources/app.asar/src/static/locales/pt.json"
The app tries to download pt.json, that there is no link https://locales.itch.ovh/itch/pt-PT.json and the same occurs with pt-PT and pt-BR, there are only links to https://locales.itch.ovh/itch/pt_PT.json and https://locales.itch.ovh/itch/pt_BR.json

**Comment by fasterthanlime** [comment]
Yeah, sorry about that - some locales are affected by changes we've made related to the upcoming release of the new version of the app :(

**Comment by fasterthanlime** [comment]
So, that server is legacy - it's just serving static files. For v26 on, the plan is to just ship locales with the app and not rely on an external server at all. It's a compromise, but it is what it is.

For v25 (the current version), I've aliased:

  * `pt_PT` to `pt-PT`
  * `pt_BR` to `pt-BR`
  * `pt` to `pt-PT`
