### ISSUE TITLE
Can't add install location that isn't on C:/

### ISSUE THREAD

**Issue by pengawill** [itchio/itch#2453]
I have my itch app installed to another hard drive, and I'm trying to get it to pick a different folder for installing games that isn't my appdata. For some reason, even when I find the folder I want and select it, it doesn't change or add an install location at all. Help?

**Comment by fasterthanlime** [comment]
I'm not sure what could cause that exactly. Do you see any messages in the app log (you can find it in Preferences => Advanced) that would help?

Are you sure you have write permissions to that other folder? If it's `C:\Program Files` or the x86 variant, you don't - that's admin-only. Network drives should work - folders of your own should also work. Just avoid system folders.

**Comment by pengawill** [comment]
I have itch installed at "D:\Program Files\itch\" and I'm trying to make my game install folder "D:\Program Files\itch\games"

Here's the output from the log:

{"time":1592676196821,"level":50,"msg":"Golang stack:\nCan't write to (D:\\Program Files\\itch\\games) not adding as an install location: open D:\\Program Files\\itch\\games\\.butler-test-file-11176: Access is denied.\ngithub.com/itchio/butler/endpoints/install.InstallLocationsAdd\n\tC:/Multi-Runner/builds/58469115/0/itchio/butler/endpoints/install/locations.go:95\ngithub.com/itchio/butler/butlerd/messages.(*InstallLocationsAddType).Register.func1\n\tC:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/messages/messages.go:2057\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch.func2\n\tC:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:310\ngithub.com/itchio/butler/butlerd.(*Router).Dispatch\n\tC:/Multi-Runner/builds/58469115/0/itchio/butler/butlerd/router.go:319\ngithub.com/itchio/butler/cmd/daemon.(*handler).Handle\n\tC:/Multi-Runner/builds/58469115/0/itchio/butler/cmd/daemon/daemon.go:115\nruntime.goexit\n\tc:/go/src/runtime/asm_amd64.s:1337","name":"mcall"}
{"time":1592676196822,"level":50,"msg":"JavaScript stack: Error: Can't write to (D:\\Program Files\\itch\\games) not adding as an install location: open D:\\Program Files\\itch\\games\\.butler-test-file-11176: Access is denied.\n    at Conversation.handleMessage (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:21579:28)\n    at Transform.sock.pipe.on.message (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:21447:22)\n    at emitOne (events.js:116:13)\n    at Transform.emit (events.js:211:7)\n    at addChunk (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:19243:12)\n    at readableAddChunk (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:19225:11)\n    at Transform.module.exports.Readable.push (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:19189:10)\n    at Transform.module.exports.Transform.push (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:20993:32)\n    at push (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:18879:10)\n    at Transform.transform [as _transform] (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:18860:5)","name":"mcall"}
{"time":1592676196822,"level":50,"msg":"while reacting to addInstallLocation: Error: Can't write to (D:\\Program Files\\itch\\games) not adding as an install location: open D:\\Program Files\\itch\\games\\.butler-test-file-11176: Access is denied.\n    at Conversation.handleMessage (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:21579:28)\n    at Transform.sock.pipe.on.message (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:21447:22)\n    at emitOne (events.js:116:13)\n    at Transform.emit (events.js:211:7)\n    at addChunk (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:19243:12)\n    at readableAddChunk (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:19225:11)\n    at Transform.module.exports.Readable.push (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:19189:10)\n    at Transform.module.exports.Transform.push (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:20993:32)\n    at push (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:18879:10)\n    at Transform.transform [as _transform] (D:\\Program Files\\itch\\app-25.4.0\\resources\\app.asar\\dist\\main\\main.bundle.js:18860:5)"}
{"time":1592676197984,"level":20,"msg":"🙏 Fetch.Commons","name":"mcall"}
{"time":1592676203661,"level":20,"msg":"🙏 Profile.Data.Put","name":"mcall"}
{"time":1592676218010,"level":30,"msg":"Opening app log at C:\\Users\\Will\\AppData\\Roaming\\itch\\logs\\itch.txt","name":"m/reac/preferences"}

**Comment by fasterthanlime** [comment]
Right! So your account doesn't have permission to write there. Like I said, Program Files is a system directory, you'll have to pick another.
