### ISSUE TITLE
Windows 7 not compatible with itch-setup.exe // CoIncrementMTAUsage in ole32.dll only exists in Windows 8.0, 8.1 and 10

### ISSUE THREAD

**Issue by pl4hh** [itchio/itch#2454]
Title says it all. current install throws error:

"The procedure entry point CoIncrementMTAUsage could not be located in the dynamic link library ole32.dll"

Upon investigating the requirements for the windows application, itch.io FAQ states it will run at windows 7 and higher,
but that function missing was introduced first in windows 8.

https://docs.microsoft.com/en-us/search/?category=All&scope=Desktop&terms=coincrementmtausage

**Comment by djmattyg007** [comment]
Can confirm, I'm experiencing the same issue.

**Comment by pl4hh** [comment]
Mitigation is to get the zip from the github without the installer and unzip it where you want it installed.
e.g. from here:
https://broth.itch.ovh/itch/windows-amd64/25.4.0/archive/default

**Comment by fasterthanlime** [comment]
I've just released itch-setup v1.24.0, which no longer uses `CoIncrementMTAUsage` and *should* work on Windows 7.

You can download the latest version from <https://itch.io/app>, as usual.

Please report back whether it does or doesn't work for you on Windows 7. (If you've gotten itch installed in the meantime - it'll just verify and repair your existing install, you won't lose any data).

**Comment by pl4hh** [comment]
Looking good, install went fine this time.
@fasterthanlime Thanks for the work!
