### ISSUE TITLE
[win32] game White Rose broken for v0.11.3

### ISSUE THREAD

**Issue by OmarWKH** [itchio/itch#246]
:rotating_light: Game [White Rose](http://dissonent.itch.io/white-rose) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/15316851f62b80c9c104).

:running: The game runs fine when the .rar archive is unpacked mnaually.

**Comment by OmarWKH** [comment]
This seems to be a known issue (or non-issue). I'll inform the developer of the game.
Reference:
http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games

**Comment by fasterthanlime** [comment]
It is! Thanks for taking the time to look around. Let me know if you need
help reaching the developer.
