### ISSUE TITLE
Trying to download the application in a Windows 7 PC

### ISSUE THREAD

**Issue by Sornoz** [itchio/itch#2460]
Something went wrong

itch-setup, v1.24.0, built on Jun 30 2020 @ 00:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

open C:\Users\EFEKARTAL\AppData\Local\itch\staging\app-25.4.0\api-ms-win-core-console-l1-1-0.dll: Erişim engellendi.
github.com/itchio/wharf/pwr.(*ArchiveHealer).heal
	C:/Users/amos/go/pkg/mod/github.com/itchio/wharf@v0.0.0-20200618125324-225b1d4a2468/pwr/archive_healer.go:282
github.com/itchio/wharf/pwr.(*ArchiveHealer).Do.func3
	C:/Users/amos/go/pkg/mod/github.com/itchio/wharf@v0.0.0-20200618125324-225b1d4a2468/pwr/archive_healer.go:92
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
github.com/itchio/wharf/pwr.(*ArchiveHealer).Do
	C:/Users/amos/go/pkg/mod/github.com/itchio/wharf@v0.0.0-20200618125324-225b1d4a2468/pwr/archive_healer.go:222
github.com/itchio/wharf/pwr.(*ValidatorContext).Validate.func6
	C:/Users/amos/go/pkg/mod/github.com/itchio/wharf@v0.0.0-20200618125324-225b1d4a2468/pwr/validator.go:158
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while installing
Error during warm-up

**Comment by fasterthanlime** [comment]
"Erişim engellendi" seems like Turkish for "Access denied" so I'm going to go ahead and assume you have some sort of third-party Antivirus running? Avast, Avira, Norton, Qihoo360, something like that?

**Comment by Sornoz** [comment]
> "Erişim engellendi" seems like Turkish for "Access denied" so I'm going to go ahead and assume you have some sort of third-party Antivirus running? Avast, Avira, Norton, Qihoo360, something like that?

You're right on the ''Access Denied'' part but I'm pretty sure that my anti-virus is causing no problems. (I'm not sure about that don't take my word on it) The Anti-Virus that I'm using is 360 Anti-Virus Do you have any tips to like download it? cause I'm just on a rock bottom rn
Edit: I just tried to close my Anti-Virus and tried to download it again. Didn't work, same problem
Edit 2: Just uninstalled my Anti-Virus and tried downloading it again. Did work so I was wrong. thanks for the help.
