### ISSUE TITLE
Itch app only downloads some files

### ISSUE THREAD

**Issue by MarjaE2** [itchio/itch#2468]
I have 1 game that comes with 4 books.

If I click "install" in the Itch app, it only selects 1 book, and ignores the other 3. And doesn't note that it has ignored the others.

If I go into the gear icon to figure out what's going on, find the other 3, and try to install them, it creates 4 folders for the 4 files.

**Comment by fasterthanlime** [comment]
Hi, unfortunately this is by design. Each "upload" is a separate install, it has its own folder, etc.

I've been thinking about ways to allow installing multiple uploads in one go for the next version of the app, but I don't have a finished design yet. Sorry!
