### ISSUE TITLE
How do you launch HTML games? (not open them. the actual script run for them to work including arguments and stuff)

### ISSUE THREAD

**Issue by CoffeeIsLife87** [itchio/itch#2469]
I am developing a tool that adds itch games to your steam library as shortcuts and I am working on adding support for html games currently
I want to know how to you guys (itch developers) make them launch in your client
thanks :)

**Comment by ryliejamesthomas** [comment]
Itch is an Electron app, so the whole thing's a webpage essentially.

**Comment by fasterthanlime** [comment]
> Itch is an Electron app, so the whole thing's a webpage essentially.

That's a bit of an oversimplification! There's a lot of native code in the app, and that code drives the whole launch process, see https://github.com/itchio/butler/blob/dad86a5007313f5bfabc44d22fdf1c551040b0b4/butlerd/types.go#L2359-L2376 for example

However in the case of HTML games, they are indeed served via Electron, see https://github.com/itchio/itch/blob/d86344d70a78262dc1b50e8f2c936f53d604d813/src/main/reactors/launch/perform-html-launch.ts

**Comment by CoffeeIsLife87** [comment]
thanks for the help!
I am sure I will be able to do something with this info :)
