### ISSUE TITLE
How are settings stored? is it in a file or somehow internally in the executable

### ISSUE THREAD

**Issue by CoffeeIsLife87** [itchio/itch#2470]
I want to extract install paths so that the user doesn't have to add them manually in my tool https://github.com/herosilas12/Batch-steam-shortcut-creator

**Comment by fasterthanlime** [comment]
Install locations are stored in an sqlite3 database, see https://github.com/itchio/butler/blob/master/database/models/install_location.go

**Comment by CoffeeIsLife87** [comment]
thanks! hopefully I can work something out of this
