### ISSUE TITLE
Itch.io client doesn't recognize if disk space is running out

### ISSUE THREAD

**Issue by janne-j** [itchio/itch#2477]
Had 12.x GB of free disk space when I started installing Night In The Woods via Itch client. 

The download part went OK, but upon installing MacOs prompted that I've run out of disk space yet the Itch client got stuck on installation part.

Itch client should check free disk space before starting the download? Should count download file + installation together.

MacOs 10.14.6 
itch v20.0.2

**Comment by fasterthanlime** [comment]
> Itch client should check free disk space before starting the download?

itch v25 does. It even preallocates enough disk space!

v20.0.2 is from November 2016, you can download the latest version from https://itch.io/app

**Comment by janne-j** [comment]
Okay, checked the updates via Itch v20.0.2 app and the result was "itch is up to date". Downloading new client now.
