### ISSUE TITLE
Quitting while installation in progress and then uninstalling the game leaves download cache on disk

### ISSUE THREAD

**Issue by janne-j** [itchio/itch#2478]
Dear itch app team, 

While installing Night In The Woods I run into an issue #2477 and this one is related to that.

1. Itch app gets stuck while installing when out of disk space
2. Quit Itch app while installation is in progress
3. Relaunch app
4. Uninstall the game that was being installed before quitting
5. Game is uninstalled but the download files are left on disk cache

Cache should be cleared as well when uninstalling

MacOs 10.14.6
itch v20.0.2

**Comment by fasterthanlime** [comment]
Also fixed in v25, see https://github.com/itchio/itch/issues/2477#issuecomment-668166883
