### ISSUE TITLE
Failure to play GNU/Linux executables with extensions ".x86"/".x86_64"

### ISSUE THREAD

**Issue by YeldhamDev** [itchio/itch#2480]
Some binaries in the GNU/Linux world can have the extensions ".x86" or "x86_64" to indicate if they're 32 or 64 bits. The Godot Engine for example, exports binaries ending with those extensions.

The itch client however, fails to execute those binaries, stating that there are no mappings for such extensions.

**Comment by fasterthanlime** [comment]
Can you link to a game I can repro this with? That's not enough detail to figure out exactly which stage is failing

**Comment by YeldhamDev** [comment]
@fasterthanlime ~~Yep, mine! :stuck_out_tongue:~~
~~https://yeldham.itch.io/librerama~~

**Comment by YeldhamDev** [comment]
I compressed the files as a workaround, so my game can't be used to reproduce the bug anymore, but the problem still exists.

BTW, executables with no extension also give an error.

**Comment by akien-mga** [comment]
I opened #2701 which is a duplicate but has more details. This one could possibly be closed as superseded by #2701.
