### ISSUE TITLE
Manual download of receipt file

### ISSUE THREAD

**Issue by julikaiba** [itchio/itch#2481]
Some games refuse to install using the itchio desktop client (for example externally hosted downloads). However when downloading them manually and putting them in the itch folder they wont get recognised by the launcher. This could be achieved by also manually creating the receipt.json in the .itch folder. However I and probably many others dont know what to put in it and thus it would be helpful if the launcher or website allowed to download only the .itch folder/receipt file instead of the full game. This way manually downloaded games could be installed easily as well.

**Comment by leafo** [comment]
Closing out old tickets.

We will not support installing projects from third party hosts and we will not support loading in downloads of games from other sources. Sorry, but it creates too many potential issues.

If you want your users to take advantage of the app then you will need to host your project on itchio directly and have them download the games through the app.

**Comment by julikaiba** [comment]
Just wanted to clarify because the answer really seems to be missing the point: 
I'm not a game creator! 
And I dont want to automatically install projects from third party hosts! 

I'm an end user who would like to create the receipt file, fully aware of it not beeing official, just to see the game in my library as "installed" instead of "download". I dont want the client to download from third party, I dont want it to install the game for me, I just want the already downloaded and installed game to be visibly installed in my library, so I dont forget about it and dont always try to download it again.

**Comment by mayera123** [comment]
What the OP has requested would actually be a simple process of adding the ability to point to an existing folder from the install button within the app which would then generate the game receipt file into the folder, providing the same management as any other game installed through the application, other than automatic updates.  The fact that some developers feel the need to use outside storage systems other than Itch,io (in my collection it is about 10%) means that there are likely a large number of users who encounter this same problem.  It would definitely be a great QOL improvement for all users.

**Comment by diedyesterdaywashere** [comment]
sorry for necro-posting i guess, but that would be really useful, because a lot of games that are hosted fully on itch cant be downloaded using launcher too, so you have to download them yourself and then run them using exe every time you want to play it

**Comment by leafo** [comment]
Change of plans we support this in https://github.com/itchio/itch/releases/tag/v26.20.0

Enjoy
