### ISSUE TITLE
kitch (itch beta) installer download URLs

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2485]
Here's some links:

  * [🖥 Windows 64-bit](https://broth.itch.ovh/install-kitch/windows-amd64/_7/unpacked/default), [🖥 Windows 32-bit](https://broth.itch.ovh/install-kitch/windows-386/_30/unpacked/default)
  * [🐧 Linux 64-bit](https://broth.itch.ovh/install-kitch/linux-portable-amd64/_19/unpacked/default)
  * [🍎 macOS 64-bit](https://broth.itch.ovh/install-kitch/darwin-amd64/_31/unpacked/default)

**Comment by fasterthanlime** [comment]
For those stumbling upon that; this is my last day @ itch, I'm doing a patch release today, just doing a QA round before I ship it.

What's new:

  * Electron v10, Chromium v85
  * "Fixes and optimizations"
  * macOS build is now notarized
  * Zero new features

If you see this and want to help me test it before it goes out, feel free to install it and click around, make sure whatever you use still works.

**Comment by Gaboris** [comment]
OH! Nice!
How stable/safe is it? I've been itching(no pun intended) to see a new version.

**Comment by fasterthanlime** [comment]
Should be just as stable and a bit safer, again, no new features though. The version of Electron shipped with v25.4.0 was just pretty old.

**Comment by Gaboris** [comment]
So same system just with a new backbone? Got it!
Sorry to hear you go. Hope it's not due to "unpleasant" circumstances.
