### ISSUE TITLE
Feature In The Windows App: Opening The Installer During Downloading

### ISSUE THREAD

**Issue by CharlesCanlom** [itchio/itch#2487]
I Found That When You Install The Game By Its .EXE Installer, By Launching It, It Justs Opens The Installer. Is That Confusing?????
Example: https://owl-skip.itch.io/family
That Game Has A EXE Installer
Can You Implement This??

**Comment by leafo** [comment]
We recommend developers provide portable apps. We will not be supporting third party installers due to the wide range of complexity introduced by them. https://itch.io/docs/itch/integrating/compatibility-policy.html
