### ISSUE TITLE
[linux] game The Terror Aboard The Speedwell: Special Edition broken for v0.11.3

### ISSUE THREAD

**Issue by KureHumanite** [itchio/itch#249]
:rotating_light: Game [The Terror Aboard The Speedwell: Special Edition](http://jgwaltneiv.itch.io/the-terror-aboard-the-speedwell) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6b0c09feb2488bf9debf).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
The linux download is actually an html game, but it doesn't even respect itch.io's conventions (there's no `index.html` at the root foolder), so even when #328 lands, it probably won't work right. The developer should fix it.
