### ISSUE TITLE
Register itchio:// protocol

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#25]
Pointers:
- Linux: gotta check if [this solution](http://superuser.com/a/309343) is enough, saint XDG pray for us
- Windows: a few registry tricks in squirrel handler, see [the basic format](http://stackoverflow.com/a/8752527) and [how atom modifies the registry](https://github.com/atom/atom/blob/5b522f70c234ebc373351ae7bcfd3d8627946e9d/src/browser/squirrel-update.coffee)
- OSX: can specify in Info.plist, even supported by [electron-packager](https://github.com/maxogden/electron-packager/issues/136#issuecomment-143393812)

When it's correctly registered, the Electron app [will receive an `open-url` event](https://github.com/maxogden/electron-packager/issues/121#issue-102164562).

To do all things properly, we should probably get in touch with someone at IANA, perhaps [Dave Thaler](http://www.iana.org/assignments/uri-schemes/prov/spotify) ?

**Comment by fasterthanlime** [comment]
Seems to work pretty well on OSX!

![itchio-protocol](https://cloud.githubusercontent.com/assets/7998310/10865898/29e12984-801c-11e5-8783-87e37f9c885b.gif)

**Comment by alexnask** [comment]
Nice!
Looks really slick

**Comment by fasterthanlime** [comment]
Closed in favor of #69, #70, #71
