### ISSUE TITLE
Can't Install, Something went wrong.

### ISSUE THREAD

**Issue by Diavoloo** [itchio/itch#2519]
When trying to download and set up the app, I get this (I removed my name in the info below):

Something went wrong

itch-setup, v1.24.0, built on Jun 29 2020 @ 16:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

rename C:\Users\NAME\AppData\Local\itch\staging\app-25.4.1 C:\Users\NAME\AppData\Local\itch\app-25.4.1: Acess is denied.
moving ready version to its proper place
Error during warm-up

I don't know what I did wrong and I'm not sure what it's asking me to do to fix the problem.

**Comment by zeramorphic** [comment]
I have the same problem (on Windows 10). Prior to this, I tried installing an app on itch.io, but it kept giving me "access denied" errors on various JSON files in the downloads temp directory, so I tried reinstalling the app.

**Comment by zeramorphic** [comment]
```
Something went wrong

itch-setup, v1.24.0, built on Jun 29 2020 @ 22:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

rename C:\Users\<NAME>\AppData\Local\itch\staging\app-25.4.1 C:\Users\<NAME>\AppData\Local\itch\app-25.4.1: Access is denied.
moving ready version to its proper place
Error during warm-up
```

**Comment by schmidthappens4** [comment]
Yep, I'm getting the same error as well.  Tried installing in different locations with no success.

**Comment by zeramorphic** [comment]
I fixed the problem by disabling McAfee Endpoint Security for the installation.

**Comment by schmidthappens4** [comment]
Thank you.  That worked.

**Comment by Diavoloo** [comment]
Thank you, @thirdsgames that fixed the problem.
