### ISSUE TITLE
[darwin] book The Art of Glitch broken for v0.11.3

### ISSUE THREAD

**Issue by reversefold** [itchio/itch#252]
:rotating_light: Game [The Art of Glitch](http://meowza.itch.io/the-art-of-glitch) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e54f81968ef52f4d7a36).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
That's a book :) Closing this in favor of #96
