### ISSUE TITLE
[linux] game Crystonal broken for v0.11.3

### ISSUE THREAD

**Issue by beansmyname** [itchio/itch#253]
:rotating_light: Game [Crystonal](http://kapura.itch.io/crystonal) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8b47ea3be863bcd125fe).

:running: There is no data folder - Output to console with executable downloaded from itch.io website

**Comment by fasterthanlime** [comment]
Get in touch with the dev, they should zip their Unity output & distribute that, not just pluck the exe from it.
