### ISSUE TITLE
Error in installation: Could not retrieve latest version of Butler: net::ERR_FAILED

### ISSUE THREAD

**Issue by mapl-e** [itchio/itch#2531]
I already installed butler latest version and it don't works
First time i install this it tells Butler is not installed
and second time when i disable avast it doesn't says that what it says is what i said
in the title...
![image](https://user-images.githubusercontent.com/70176410/97336884-894ceb00-184d-11eb-8b80-cb84f2c5aac8.png)

**Comment by leafo** [comment]
I see an ENOENT error above, suggesting that the butler executable has been removed from your system. You likely have antivirus or security software that has deleted the file and is breaking the app. Please try temporarily disabling it and reinstalling the app.
