### ISSUE TITLE
No "Physical Games" Library Search filter in itch desktop client

### ISSUE THREAD

**Issue by gsantner** [itchio/itch#2533]
The itch.io desktop client has no option to filter against phyical/tabletop/board games.  
Would be cool if you can add it.

Theres i.e. books - (URL similar `https://itch.io/books` VS `itch://library/owned?classification=book`

![Screenshot_20201027-223607](https://user-images.githubusercontent.com/6735650/97365139-7b2ab900-18a5-11eb-9853-68516b334e4c.png)

Theres i.e. comics - (URL similar `https://itch.io/comics` VS `itch://library/owned?classification=comic`)

![Screenshot_20201027-223742](https://user-images.githubusercontent.com/6735650/97365144-7e25a980-18a5-11eb-8ffb-a42859926732.png)

But there is NO tab/option for physicals games. Also I tried to change manually to url to physical-game/s/pyhsical etc...which doesn't work either:
`https://itch.io/physical-games` VS `itch://library/owned?classification=physical-game`

![Screenshot_20201027-223752](https://user-images.githubusercontent.com/6735650/97365042-4d457480-18a5-11eb-860f-03cb377a07f3.png)

**Comment by leafo** [comment]
Will be part of the next release

**Comment by gsantner** [comment]
Cool thanks for fast response
