### ISSUE TITLE
rename D:\itch\staging\app-25.4.1 D:\itch\app-25.4.1: Access is denied.

### ISSUE THREAD

**Issue by Deepfried-Chips** [itchio/itch#2534]
Something went wrong

itch-setup, v1.24.0, built on Jun 30 2020 @ 00:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

rename D:\itch\staging\app-25.4.1 D:\itch\app-25.4.1: Access is denied.
moving ready version to its proper place
Error during warm-up

**Comment by leafo** [comment]
This error can likely happen for a number of reasons, you have security software interrupting the install, the user you're using doesn't have permission to actually move that directory, there may already be that directory there from a failed previous installation. I recommend deleting those directories and restarting the install. Note that deleting them will remove any saved preferences and installed games (unless you have configured games to install elsewhere)

**Comment by Deepfried-Chips** [comment]
My user is an administrator

**Comment by Deepfried-Chips** [comment]
Hold on kaspersky very often acts stupid i'll inform you shortly

**Comment by Deepfried-Chips** [comment]
Kaspersky was causing problems
