### ISSUE TITLE
Deleting collections should delete them from client

### ISSUE THREAD

**Issue by dmfay** [itchio/itch#255]
Potentially related to #108 although that's more of a general improvement.

**Comment by fasterthanlime** [comment]
Another local db issue in the vein of #262 

:star2: If someone wants to try fixing it, here's one bit of fetching logic that does handle both pagination and deletions: https://github.com/itchio/itch/blob/0d325a6186d5b7ee7c565267b430993b4eab8363/app/stores/game-store.js#L100

Basically, while we're fetching, we just add new items, only when we're done fetching do we have complete knowledge of "all games developed" or "all collections", etc. — and then we can delete the others.

Note that game-store doesn't actually remove game from the local DB it simply stops listing their ID in `game_ids`. Database cleanup isn't a subject I've tackled yet in the app (how aggressive it should be is a trade-off between disk space & amount of things you can do offline)
