### ISSUE TITLE
installer not working

### ISSUE THREAD

**Issue by jamerz06** [itchio/itch#2555]
every time i try to install it it says there's and error during warm up and I've tried deleting the folders holding the data please tell me how to fix this, this is what it says

Something went wrong

itch-setup, v1.24.0, built on Jun 29 2020 @ 16:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

remove C:\Users\WALDO\AppData\Local\itch\app-25.4.1\chrome_100_percent.pak: Access is denied.
making sure ready version's folder does not exist
Error during warm-up

**Comment by XDRSZYHRL** [comment]
发生了一些错误

itch-setup, v1.24.0, built on Jun 30 2020 @ 05:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255

Get "https://w3g3a5v6.ssl.hwcdn.net/build/295201/1125554-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1607092219&Signature=Idjqx%2F91IDNrVv6UN8TV9ER6cdvh6B3hm352EA3aQehkNuc7QKUkXJgGp5v7rueCTINVYbYDUEXdzYij2imR5Cx%2BjEPGcUtAT6ZNcFBdw5K2Pk8cu3wUwaoZ%2FZXP5LewKgKP58TP2FMA53NqeHuFBmo4B9yJDyz5ER7oHNi4Pf0q1%2FuwuFgXLXJprZ78GyQ0iKKwG666mtxFMnwQ2XGfYkg8uHOmHlLY7HBQZspMGfEkcdns%2FB3MYs8aGA%2FbGLAD%2FopQijK4x8RmZKBoo0OsElqG7iHb2dtIcZKkk8id1zLUjm%2Bm7v55cAxGGeLhg6kypBFgNxkS671bHevSDgNFMw==&hwexp=1607092509&hwsig=505ebd7c3f71d90863e8576e7677464d": unexpected EOF
in conn.tryConnect, while doing GET request
github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:128
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:56
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
in conn.Connect, exhausted retry context
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:88
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
htfs.Open (initial request)
github.com/itchio/httpkit/htfs.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:182
github.com/itchio/httpkit/eos.realOpen
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while opening remote signature file
Error during warm-up

**Comment by leafo** [comment]
> every time i try to install it it says there's and error during warm up and I've tried deleting the folders holding the data please tell me how to fix this, this is what it says
> 
> Something went wrong
> 
> itch-setup, v1.24.0, built on Jun 29 2020 @ 16:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255
> 
> remove C:\Users\WALDO\AppData\Local\itch\app-25.4.1\chrome_100_percent.pak: Access is denied.
> making sure ready version's folder does not exist
> Error during warm-up

The app isn't able to install because something about your computer's configuration is blocking it from placing files into the local app directory. You either have security software that is blocking it, or your computer has been configured (or misconfigured) in a way that prevents writing to directories that should be written to. (eg. Perhaps you're using a school computer with a policy that blocks software installs?)

Generally we recommend you work backwards by temporarily disabling any third party security software, then test if the app can work, to see if you can narrow down the cause of the issue. We ask that you entirely disable it the security software, and not try to add an exception, since it's easy to incorrectly add an exception, or we've even seen cases when added exceptions do not work.

**Comment by leafo** [comment]
> 发生了一些错误
> 
> itch-setup, v1.24.0, built on Jun 30 2020 @ 05:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255
> 
> Get "https://w3g3a5v6.ssl.hwcdn.net/build/295201/1125554-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1607092219&Signature=Idjqx%2F91IDNrVv6UN8TV9ER6cdvh6B3hm352EA3aQehkNuc7QKUkXJgGp5v7rueCTINVYbYDUEXdzYij2imR5Cx%2BjEPGcUtAT6ZNcFBdw5K2Pk8cu3wUwaoZ%2FZXP5LewKgKP58TP2FMA53NqeHuFBmo4B9yJDyz5ER7oHNi4Pf0q1%2FuwuFgXLXJprZ78GyQ0iKKwG666mtxFMnwQ2XGfYkg8uHOmHlLY7HBQZspMGfEkcdns%2FB3MYs8aGA%2FbGLAD%2FopQijK4x8RmZKBoo0OsElqG7iHb2dtIcZKkk8id1zLUjm%2Bm7v55cAxGGeLhg6kypBFgNxkS671bHevSDgNFMw==&hwexp=1607092509&hwsig=505ebd7c3f71d90863e8576e7677464d": unexpected EOF
> in conn.tryConnect, while doing GET request
> github.com/itchio/httpkit/htfs.(*conn).tryConnect
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:128
> github.com/itchio/httpkit/htfs.(*conn).Connect
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:56
> github.com/itchio/httpkit/htfs.(*File).borrowConn
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.(*Installer).doInstall
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
> github.com/itchio/itch-setup/setup.(*Installer).Install.func1
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> in conn.Connect, exhausted retry context
> github.com/itchio/httpkit/htfs.(*conn).Connect
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:88
> github.com/itchio/httpkit/htfs.(*File).borrowConn
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.(*Installer).doInstall
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
> github.com/itchio/itch-setup/setup.(*Installer).Install.func1
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> htfs.Open (initial request)
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:182
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.(*Installer).doInstall
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
> github.com/itchio/itch-setup/setup.(*Installer).Install.func1
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> while opening remote signature file
> Error during warm-up

The error message says your computer was unable to download the app's installation files from our CDN. The likely cause is that your network, or software on your computer, is blocking access. Hope that helps you find out what the problem is.

**Comment by XDRSZYHRL** [comment]
我更换了一个网络环境（中国电信），他就可以下载安装了，已经安装好了，之前使用的是（中国移动）的网络环境。

**Comment by XDRSZYHRL** [comment]
> 发生了一些错误
> 
> itch 设置， v1.24.0， 基于 6 月 30 日 2020 @ 05：24：16， 参考 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255
> 
> Get "https://w3g3a5v6.ssl.hwcdn.net/build/295201/1125554-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1607092219&Signature=Idjqx%2F91IDNrVv6UN8TV9ER6cdvh6B3hm352EA3aQehkNuc7QKUkXJgGp5v7rueCTINVYbYDUEXdzYij2imR5Cx%2BjEPGcUtAT6ZNcFBdw5K2Pk8cu3wUwaoZ%2FZXP5LewKgKP58TP2FMA53NqeHuFBmo4B9yJDyz5ER7oHNi4Pf0q1%2FuwuFgXLXJprZ78GyQ0iKKwG666mtxFMnwQ2XGfYkg8uHOmHlLY7HBQZspMGfEkcdns%2FB3MYs8aGA%2FbGLAD%2FopQijK4x8RmZKBoo0OsElqG7iHb2dtIcZKkk8id1zLUjm%2Bm7v55cAxGGeLhg6kypBFgNxkS671bHevSDgNFMw==&hwexp=1607092509&hwsig=505ebd7c3f71d90863e8576e7677464d": unexpected EOF
> in conn.tryConnect, while doing GET request
> github.com/itchio/httpkit/htfs.（*conn）.tryConnect
> C：/用户/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go：128
> github.com/itchio/httpkit/htfs.（*conn）。连接
> C：/用户/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn：56
> github.com/itchio/httpkit/htfs.(*File).borrowConn
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.（*安装器）.doInstall
> C：/msys64/家庭/阿莫斯/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup.go：162
> github.com/itchio/itch-setup/setup.（*安装程序）。安装.func1
> C：/msys64/home/amos/gitlab/生成/eJ5Rnxef/1/itchio/itch-setup/setup.go：142
> 运行时.goexit
> c：/go/src/运行时/asm_amd64.s：1373
> 在康康。连接，已用尽重试上下文
> github.com/itchio/httpkit/htfs。（*conn）。连接
> C：/用户/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go：88
> github.com/itchio/httpkit/htfs。(*File).borrowConn
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.（*安装器）.doInstall
> C：/msys64/家庭/阿莫斯/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup.go：162
> github.com/itchio/itch-setup/setup.（*安装程序）。安装.func1
> C：/msys64/home/amos/gitlab/生成/eJ5Rnxef/1/itchio/itch-setup/setup.go：142
> 运行时.goexit
> c：/go/src/运行时/asm_amd64.s：1373
> htfs.打开（初始请求）
> 
> github.com/itchio/httpkit/htfs.Open C：/用户
> /amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go：182 github.com/itchio/httpkit/eos.realOpen
> C：/用户/amos/go/pkg/30.com 00618110940-5044e418b971/eos/eos.go：137
> github.com/itchio/httpkit/eos.Open
> C：/用户/阿莫斯/go httpkit@v0/pkg/mod/github.com/itchio/httpkit@v0.0. 0-202006181810940-5044e418b971/eos/eos.go：67
> github.com/itchio/savior/filesource.OpenPaused C：/用户/阿莫斯/go/pkg/mod/github.com/itchio/savior@v0.0.0-2020030303195615-7cac79
> 98294c/filesource/filesource.go：11
> github.com/itchio/savior/filesource.Open
> C：/用户/阿莫斯/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac798294c/文件源/文件源.go：25
> github.com/itchio/itch-setup/setup.（*安装器）.doInstall
> C：/msys64/家庭/阿莫斯/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup.go：162
> github.com/itchio/itch-setup/setup.（*安装程序）。安装.func1
> 
> C：/msys64/home/amos/gitlab/生成/eJ5Rnxef/1/itchio/itch-setup/setup.go：142 运行时.goexit
> c：/go/src/运行时/asm_amd64.s：1373，
> 
> 同时在预热期间打开远程签名文件错误



> 发生了一些错误
> 
> itch-setup, v1.24.0, built on Jun 30 2020 @ 05:24:16, ref 083c5ca31bf1ee69dc9a7ece8ffb65ef3e421255
> 
> Get "https://w3g3a5v6.ssl.hwcdn.net/build/295201/1125554-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1607092219&Signature=Idjqx%2F91IDNrVv6UN8TV9ER6cdvh6B3hm352EA3aQehkNuc7QKUkXJgGp5v7rueCTINVYbYDUEXdzYij2imR5Cx%2BjEPGcUtAT6ZNcFBdw5K2Pk8cu3wUwaoZ%2FZXP5LewKgKP58TP2FMA53NqeHuFBmo4B9yJDyz5ER7oHNi4Pf0q1%2FuwuFgXLXJprZ78GyQ0iKKwG666mtxFMnwQ2XGfYkg8uHOmHlLY7HBQZspMGfEkcdns%2FB3MYs8aGA%2FbGLAD%2FopQijK4x8RmZKBoo0OsElqG7iHb2dtIcZKkk8id1zLUjm%2Bm7v55cAxGGeLhg6kypBFgNxkS671bHevSDgNFMw==&hwexp=1607092509&hwsig=505ebd7c3f71d90863e8576e7677464d": unexpected EOF
> in conn.tryConnect, while doing GET request
> github.com/itchio/httpkit/htfs.(*conn).tryConnect
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:128
> github.com/itchio/httpkit/htfs.(*conn).Connect
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:56
> github.com/itchio/httpkit/htfs.(*File).borrowConn
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.(*Installer).doInstall
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
> github.com/itchio/itch-setup/setup.(*Installer).Install.func1
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> in conn.Connect, exhausted retry context
> github.com/itchio/httpkit/htfs.(*conn).Connect
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:88
> github.com/itchio/httpkit/htfs.(*File).borrowConn
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.(*Installer).doInstall
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
> github.com/itchio/itch-setup/setup.(*Installer).Install.func1
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> htfs.Open (initial request)
> github.com/itchio/httpkit/htfs.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:182
> github.com/itchio/httpkit/eos.realOpen
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
> github.com/itchio/httpkit/eos.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
> github.com/itchio/savior/filesource.OpenPaused
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
> github.com/itchio/savior/filesource.Open
> C:/Users/amos/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
> github.com/itchio/itch-setup/setup.(*Installer).doInstall
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:162
> github.com/itchio/itch-setup/setup.(*Installer).Install.func1
> C:/msys64/home/amos/gitlab/builds/eJ5Rnxef/1/itchio/itch-setup/setup/setup.go:142
> runtime.goexit
> c:/go/src/runtime/asm_amd64.s:1373
> while opening remote signature file
> Error during warm-up

我更换了一个网络环境（中国电信），他就可以下载安装了，已经安装好了，之前使用的是（中国移动）的网络环境。
