### ISSUE TITLE
Why ask for two-step authentication every time you open the Itch app?

### ISSUE THREAD

**Issue by anonymous725195** [itchio/itch#2559]
Seriously, what's the need to keep asking this EVERY TIME I start the app on the computer? If I were to ask once ok, but EVERY TIME I'm going to open it?

**Comment by leafo** [comment]
Are you also logging in again? Once you have an active session it should no longer ask for your two factor authentication code that I'm aware of. If you log in with a new session, then it will ask you for the code again.

**Comment by anonymous725195** [comment]
He stopped asking when logged in, whatever you did thanks :)
