### ISSUE TITLE
is there anything that can be done about self-extracting zips / installers

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#259]
e.g http://mason-lindroth.itch.io/hylics which when i run it runs the extractor and obviously doesn't know where to find the game afterwards

i guess there's really no solution but to have devs provide normal .zip ?

**Comment by fasterthanlime** [comment]
Well, we already support .msi, nsis & inno setup, so I think we can support a few other 'installer formats'.

Do you know what Hylics' one is made with? I think 7-zip can produces self-extractors, probably WinRar too (sigh). The non-a version of 7-zip can even extract some self-extracting .exes, but we use 7za which I don't think has it.

Basically the process is this:
- For a given game with a self-extracting .exe, find out what it was made with
- Read everything you find on that format/tool, post links here
- Using an hex viewer/editor (I use Hex Fiend on OSX, HxD on Windows, Bless on Linux), find a uniquely identifiable string (see [existing ones](https://github.com/itchio/itch/blob/master/app/tasks/install/exe.js#L38))
- If the format has command-line options that let us specify destination + silent operation, we're golden

For formats that don't let us do that, I would be against supporting them. Even Inno/NSIS sometimes require privilege elevation (UAC prompt) and that's almost too much, I think. For more exotic cases, I don't think it's unreasonable to ask users to repack. (An existing set of installer configuration files might be annoying to migrate/convert/port to something else whereas a self-extracting archive doesn't have any customization applied to it afaik)

**Comment by fasterthanlime** [comment]
@Ragzouken oh hey 0.12 correctly sniffs, extracts and runs Hylics.

Update with `Help -> Check for Update` and enjoy!
