### ISSUE TITLE
[win32] game Ethereal broken for v0.11.3

### ISSUE THREAD

**Issue by Techwolf12** [itchio/itch#260]
:rotating_light: Game [Ethereal](http://pixlwalkr.itch.io/ethereal) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e13b536137560368750b).

:running: Any additional details can go here!

**Comment by erbridge** [comment]
The developer used to use RAR until prompted to switch to ZIP, but it looks like they just renamed the files rather than recompressing them.

http://pixlwalkr.itch.io/ethereal/comments

**Comment by erbridge** [comment]
Should be fixed now.

**Comment by fasterthanlime** [comment]
Can confirm, I can download & run the game on OSX.

**Comment by Techwolf12** [comment]
Can confirm it works again. Thanks!
