### ISSUE TITLE
[win32] Game bought as gift not appearing in itch's purchases (v0.11.3)

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch#261]
Hey hey,

A friend of mine bought me Subterrarium on itch.io over Christmas:

http://slimefriend.itch.io/subterrarium/

It's not appearing either in the itch.io app, or on my purchases page:

http://itch.io/my-purchases

(apologies if I'm just doing something stupid)

**Comment by fasterthanlime** [comment]
Hey terry!

Not sure what happened, looks like the gift was properly sent, and to your account's e-mail.

I linked the purchase to your account manually, should be all working now!

**Comment by TerryCavanagh** [comment]
Great, thanks!
