### ISSUE TITLE
Deleting game should remove them from 'My creations' tab

### ISSUE THREAD

**Issue by erbridge** [itchio/itch#262]
Clicking the main link directs a browser to where the game was (now a dead link).

e.g.

![image](https://cloud.githubusercontent.com/assets/1027364/12026744/1fd005ac-adb5-11e5-8003-e002f77aedf4.png)

**Comment by fasterthanlime** [comment]
Good point, client deals with deleted games in collections but doesn't purge old developed games from its local DB.

**Comment by juzimmer** [comment]
This is still happening to me. I deleted a project and its still showing up in the desktop application under My Creations. For the time being is there anyway to manually delete ?
