### ISSUE TITLE
Make offline support work on Windows

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch#263]
Gives this very cryptic error right now:

`
Error: getaddrinfo ENOENT itch.io:443 at Object.exports._errnoException (util.js:837:11) at errnoException (dns.js:30:15) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
`

**Comment by fasterthanlime** [comment]
Absolutely. The app is designed from the ground up to work offline, but there's a few changes that still need to be made for it to work well.

(e.g. it caches everything locally but still expects some API requests to succeed / won't gracefully continue when they fail)

**Comment by fasterthanlime** [comment]
v17 lets you use a remembered session, search your installed games & launch them, no problem :+1:

**Comment by ke** [comment]
@fasterthanlime still a problem on Windows itch v20.0.2.

**Comment by fasterthanlime** [comment]
@ke the exact error mention in the original post? or something else? please give as much detail as you can!

**Comment by ke** [comment]
@fasterthanlime the exact error mentioned. You cannot get past the login error when launching the itch app offline.

**Comment by fasterthanlime** [comment]
@ke with a remembered session? or when entering username/password?

**Comment by fasterthanlime** [comment]
@ke also, which version of windows? (or macOS, or which linux distribution)

**Comment by ke** [comment]
@fasterthanlime with a remembered session. Clicking it in Saved logins brings you back to the login error.
***
Problem with Windows, works fine on macOS. Here is the error for v20.0.2.

`Error: getaddrinfo ENOENT itch.io:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
From previous event:
    at Client.<anonymous> (C:\Users\kevin\AppData\Local\itch\app-20.0.2\resources\app.asar\appsrc\util\api.ts:101:31)
    at next (<anonymous>)
    at fulfilled (C:\Users\kevin\AppData\Local\itch\app-20.0.2\resources\app.asar\app\util\api.js:4:58)`

**Comment by fasterthanlime** [comment]
@ke oh! I did most of my offline testing on mac, that's why (easier to disable wifi on my MBP). I'll do some Windows testing as well, thanks. Reopening!
