### ISSUE TITLE
Unable to paste text

### ISSUE THREAD

**Issue by kwoodhouse93** [itchio/itch#2637]
Version: itch@25.5.1
OS: MacOS BigSur 11.2.3

Initially spotted this when I was presented with the login screen - pressing Cmd+V does not paste into either the username/email field or the password field.

This is a pain for those used to using a password manager. Password managers facilitate the use of long, randomly generated passwords unique to each site. If they can't be pasted or auto-filled, I have to type it out character by character.

Once logged in, it seems other text fields also don't support pasting. For example, the browser address bar and filter.

**Comment by chrisman** [comment]
I basically cannot log into the app because I cannot paste my password.

**Comment by agnesnutter** [comment]
+1. As a workaround, pasting is available from the context menu (right-click > paste).

But it's been over a year since this issue was reported, I'm not sure if itch even pays attention to these...

**Comment by OddHouseGames** [comment]
+1 and thanks for the suggestion of the right click context menu, incredibly strange not being able to paste from a password manager.

**Comment by alts** [comment]
Sorry for the wait. This had been bothering me, too. This was fixed in bb5e0f6. The latest [beta](https://itchio.itch.io/kitch) has the fix in place, and a full release should go live this week with it.

Thanks for the heads up @thejustinwalsh
