### ISSUE TITLE
Clarify API key scopes, and site-wide 2FA policy

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch#264]
I have two factor authentication on my itch.io account, but right now I can log into the itch app and access all my games without it!

**Comment by fasterthanlime** [comment]
Known issue, thanks for reporting it here

Note that you do need 2FA to purchase (from the app) a game linked to your account. API keys give mostly read-only access. Needs to be part of a bigger discussion with @leafo

**Comment by fasterthanlime** [comment]
So! The situation was already handled in v23, but in v25 the 2FA dialog is prettier.

![image](https://user-images.githubusercontent.com/7998310/45638281-0cb38400-baad-11e8-99f9-eda5f00efc90.png)

  * Logging into the app now requires entering a two-factor code (if you have 2FA enabled)
  * ..and it sets a cookie for that profile, logging you into the website.

Calling it done.
