### ISSUE TITLE
Cannot paste into the password field with CMD+V

### ISSUE THREAD

**Issue by flying-sausages** [itchio/itch#2660]
I'm on MacOS 11.4, on an M1 Macbook Pro. I cannot paste into the password field when using CMD+V

There's no "Edit" item on the menu bar when the itch app is open either, so I cannot use the system paste there.

The **only** way to paste is by right-clicking the text field.

**Comment by agnesnutter** [comment]
See also #2637

**Comment by alts** [comment]
This was fixed in bb5e0f6. The latest [beta](https://itchio.itch.io/kitch) has the fix in place, and a full release should go live this week with it.

Thanks for the heads up @thejustinwalsh
