### ISSUE TITLE
[linux] game 2:22AM broken for v0.11.3

### ISSUE THREAD

**Issue by tsbarnes** [itchio/itch#267]
:rotating_light: Game [2:22AM](http://robocicero.itch.io/222am) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8e2c7a7d1e9c1c59720d).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like the game straight up crashed. You should get in touch with https://twitter.com/wuhwuhwhat about that :)
