### ISSUE TITLE
[linux] game GUM WILL NEVER GO OUT OF STYLE BUT YOU WILL broken for v0.11.3

### ISSUE THREAD

**Issue by tsbarnes** [itchio/itch#268]
:rotating_light: Game [GUM WILL NEVER GO OUT OF STYLE BUT YOU WILL](http://primaerfunktion.itch.io/gum-will-never-go-out-of-style-but-you-will) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e725ff66134cfc66dab6).

:running: Resolution and graphics quality selection worked, but then the game immediately crashes.

**Comment by fasterthanlime** [comment]
From this and your other issue, I suspect you may be having video driver issues.

At any rate, this is the game's problem, not itch's. Closing!
