### ISSUE TITLE
[win32] game Mobsferatu broken for v0.11.3

### ISSUE THREAD

**Issue by themorfeus** [itchio/itch#269]
:rotating_light: Game [Mobsferatu](http://cremagames.itch.io/mobsferatu) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2ba17f551628d62bf039).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Hey, thanks for your report! :star2:

That game is broken on itch because it uses .rar - here's an explanation: http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games
