### ISSUE TITLE
Itch.IO app doesn't download

### ISSUE THREAD

**Issue by NightwingFang** [itchio/itch#2709]
i went onto the itch site to go try a game out and it gave me an error then i went to epic (somehow it has the launcher now dunno why) and i get this each time i am trying to download it
Something went wrong

itch-setup, v1.26.0, built on Apr 21 2021 @ 21:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Got HTTP 500 for https://broth.itch.ovh/itch/windows-amd64/LATEST
github.com/itchio/itch-setup/setup.(*Installer).brothGetBytes
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/broth.go:64
github.com/itchio/itch-setup/setup.(*Installer).brothGetString
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/broth.go:76
github.com/itchio/itch-setup/setup.(*Installer).getVersion
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:131
github.com/itchio/itch-setup/setup.(*Installer).warmUp
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:107
github.com/itchio/itch-setup/setup.(*Installer).WarmUp.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:98
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while getting latest version
Error during warm-up
i have no idea what's wrong here and it looks like it's a previous version of Itch launcher, is it gone or is it bugged?

**Comment by jakedp** [comment]
I get the same HTTP 500 error as the above post. Output is below:

2021/09/02 23:17:14 itch-setup will log to /tmp/itch-setup-log.txt
2021/09/02 23:17:14 =========================================
2021/09/02 23:17:14 itch-setup "v1.26.0, built on Apr 21 2021 @ 18:48:12, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd" starting up at "2021-09-02 23:17:14.158393129 -0700 PDT m=+0.003667139" with arguments:
2021/09/02 23:17:14 "./itch-setup"
2021/09/02 23:17:14 =========================================
2021/09/02 23:17:14 App name specified at build time: itch
2021/09/02 23:17:14 Locale:  en-CA
2021/09/02 23:17:14 Initializing installer GUI...
2021/09/02 23:17:14 Using GTK UI
2021/09/02 23:17:14 Initializing (itch) multiverse @ (/home/hh/.itch)
2021/09/02 23:17:14 No multiverse information yet
2021/09/02 23:17:14 Loading image resources...
2021/09/02 23:17:14 Setting up progress bar...
2021/09/02 23:17:14 Positioning and showing window...
2021/09/02 23:17:14 Install error: while getting latest version: Got HTTP 500 for https://broth.itch.ovh/itch/linux-amd64/LATEST
2021/09/02 23:17:14 Fatal error: Warm-up error: while getting latest version: Got HTTP 500 for https://broth.itch.ovh/itch/linux-amd64/LATEST
Opening in existing browser session.

**Comment by NightwingFang** [comment]
so i am not the only one good to know, i am happy to know that (just woke up and typed this message)

**Comment by NightwingFang** [comment]
it's working now, had to wait a day
