### ISSUE TITLE
install task should check that upload exists & requeue if needed

### ISSUE THREAD

**Issue by oatycreates** [itchio/itch#271]
:rotating_light: Game [Return of the Obra Dinn](http://dukope.itch.io/return-of-the-obra-dinn) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8021660699119905f9e6).

:running: Any additional details can go here!

Deleting and re-downloading fixed this.

**Comment by fasterthanlime** [comment]
Ah, interesting, the 'install' step should probably check that the installation file exists, and go back to download if it doesn't

**Comment by fasterthanlime** [comment]
(I'm still curious what happened though — I don't see any message from butler (our command-line downloader) in that log...)

**Comment by oatycreates** [comment]
If it helps, I do run COMODO Internet Security for anti-virus and firewall protection. I wonder if that may have interfered?

**Comment by fasterthanlime** [comment]
Closed by 784498d11e006fa0b638ddd6db4efa99c09e8472
