### ISSUE TITLE
Hide incompatible games when browsing grid

### ISSUE THREAD

**Issue by kevindjacobson** [itchio/itch#272]
![itch 2015-12-31 11-43-27](https://cloud.githubusercontent.com/assets/1500557/12067726/c00e4146-afb3-11e5-9a9c-559f3117aa31.png)

Screenshot taken on OSX

When browsing a collection, it would be nice if games which I can't run on my platform could be hidden.

**Comment by leafo** [comment]
:+1: problem is especially worse on linux when large percentage of my collection games aren't available

**Comment by fasterthanlime** [comment]
I feel like this should probably be an option, either preference-level or grid-level — it would be kinda confusing to add a game and then not see it in the collection

Or maybe have `+ 18 items not available on linux [Show them]` at the bottom of the grid? Seems like a good way to go about it.

**Comment by fasterthanlime** [comment]
To me, this is blocked by #328 and #135 — I want to support more games before we actually start hiding games

**Comment by fasterthanlime** [comment]
Doing that now
