### ISSUE TITLE
[win32] game Forbidden planet broken for v0.11.3

### ISSUE THREAD

**Issue by merder** [itchio/itch#273]
:rotating_light: Game [Forbidden planet](http://yukihirotkyo.itch.io/forbidden-planet) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2a1e5a18bdff72839add).

:running:
only recently got it via a promotion but i can't play it at all :(

**Comment by fasterthanlime** [comment]
Oh yeah the app doesn't support .rar and never will.

The developer should repack the game, you can point them to http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games
