### ISSUE TITLE
Remove useless & checks in command-line launcher

### ISSUE THREAD

**Issue by Felegz** [itchio/itch#274]
:rotating_light: Game [Schiaffi&Fagioli [demo]](http://lochiamavanotriniteam.itch.io/schiaffifagioli) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/09d7f5d4506e4f9db794).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Ah fun, it looks like my useless checks are actually harmful: https://github.com/itchio/itch/blob/3de2bb5905858ebc3fe934a47facaedf23738c5b/app/tasks/launch.js#L22

Gotta fix that
