### ISSUE TITLE
Consider removing menu bar

### ISSUE THREAD

**Issue by smiley** [itchio/itch#275]
I don't see a real reason to have a menu bar, and on Windows it's a bit jarring:
![image](https://cloud.githubusercontent.com/assets/354181/12071871/9ddf3a8a-b0cb-11e5-8cdb-1de6d8e22ffd.png)

I think we can do away with the whole thing:
- The `Edit` menu is unnecessary
- `Account` can become a menu triggered by clicking the username, or `Change user...` could just be made into a logout icon docked to the right, near the username
- `Close window` is already implemented by the OS, and `Quit` can also be made to a username-near button
- `Help` can be made into a sidebar-width button on the bottom of the sidebar, which opens a dialogue with all those options. `F1` could also trigger it.

What do you think?

**Comment by fasterthanlime** [comment]
It's less of a problem on OSX or with Ubuntu's Unity launcher. I suppose we could consider making the menu completely redundant & then providing an option to hide it (or even have it be the default on Windows?)

**Comment by smiley** [comment]
It's less of a problem on OS X & Unity, but it's still a little useless. I think options should be moved to empty corners of the app, with these commands only kept as keyboard shortcuts. (It could also be made hidden & triggered with "Alt" on Windows as other applications do)

_(I'm also setting an environment up so I could implement this)_

**Comment by LiamDawe** [comment]
I prefer the option of having one, to flat out not having one. It gives people a clear-cut place for certain options, rather than hunting for icons and hidden menus in the app.

**Comment by fasterthanlime** [comment]
@smiley Don't hold your breath on that one btw, it's top-level nitpicking (and that's fine) but not very high on the priority list :) app still has a lot to learn before we start addressing that.

**Comment by smiley** [comment]
Yeah, after I brought it up I realised it's pretty nit-picky.

**Comment by fasterthanlime** [comment]
Glad you understand — it's real easy to feel overwhelmed by an issue tracker. To reporters, every single issue seems small, but to maintainers, they have to juggle a priority list with hundreds of items. Anyway, I'll stop before going full rant :)

**Comment by smiley** [comment]
Don't worry, I know what you mean. I've had that happen with users, some even trying to go over my head and prioritise their issues above the rest. I just wanted to have it written down somewhere, no need to tackle it now. :sweat_smile:

**Comment by fasterthanlime** [comment]
Well, it's removed now (or at least, auto-hidden). Still haven't translated all items into in-app UI but.. getting there. Cf. #608 for example.
