### ISSUE TITLE
install fail V25.5.1 for Windows 10

### ISSUE THREAD

**Issue by Lone102246** [itchio/itch#2755]
itch-setup, v1.26.0, built on Apr 22 2021 @ 09:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://w3g3a5v6.ssl.hwcdn.net/build/396930/1518903-signature-default?GoogleAccessId=uploader@moonscript2.iam.gserviceaccount.com&Expires=1640318644&Signature=hD1uPExmNCBk7%2F88%2FH9sm8W7MUh%2Ft46zlQApsrN%2F%2BjbYynuoSVLIlwgerhQmniW5GOejoGgsHHUrXxt5MepjYaIdww3OR4ImQ7KoiKjrcZUvbFPMHEb0tZKv321MfiDXeKVZYxmQQLwg2wygQT3fUgR2CYVGeeOCzsMQF9fxmlLF9EseWvazzZSvHR5rNOn6mTFr912E%2B9sVVCTXtRdnpSPi3onei0icicw88ewblfY8aLdJfcvGrIQJKbK%2BY5MoyUHZtJTTVXetyMAbPitdU%2BsrQ%2BXr3OzIJSnbv5gYoLdQS8LjoTzakW00sO9Bm31%2FhWCcBis3qzBJYAUN9529WQ==&hwexp=1640318934&hwsig=124278d188d494dbadd393c70860e214": x509: certificate signed by unknown authority
in conn.tryConnect, while doing GET request
github.com/itchio/httpkit/htfs.(*conn).tryConnect
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:128
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:56
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
in conn.Connect, non-retriable error
github.com/itchio/httpkit/htfs.(*conn).Connect
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/conn.go:77
github.com/itchio/httpkit/htfs.(*File).borrowConn
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:336
github.com/itchio/httpkit/htfs.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:180
github.com/itchio/httpkit/eos.realOpen
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
htfs.Open (initial request)
github.com/itchio/httpkit/htfs.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/htfs/file.go:182
github.com/itchio/httpkit/eos.realOpen
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:137
github.com/itchio/httpkit/eos.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/httpkit@v0.0.0-20200618110940-5044e418b971/eos/eos.go:67
github.com/itchio/savior/filesource.OpenPaused
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:11
github.com/itchio/savior/filesource.Open
	C:/Users/Administrator/go/pkg/mod/github.com/itchio/savior@v0.0.0-20200303195615-7cac7998294c/filesource/filesource.go:25
github.com/itchio/itch-setup/setup.(*Installer).doInstall
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:162
github.com/itchio/itch-setup/setup.(*Installer).Install.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:142
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while opening remote signature file
Error during warm-up

**Comment by leafo** [comment]
Please try again if you're still having an issue. Our certificates are up to date, there could have been a temporary issue with a cert update. If it's still happening then you have third-party software injecting itself in your network connection and that is outside our control.
