### ISSUE TITLE
Support third party sources

### ISSUE THREAD

**Issue by ColonelPanic-42** [itchio/itch#2757]
It seems an increasing number of games are being hosted on third party sites (GDrive, Mega etc.) which makes the app essentially useless as there's no way to download and install from these sources, and no way to import games installed externally.

**Comment by leafo** [comment]
I believe there was another ticket about this somewhere, but we will never support these types of installs in the app. At one point we did support third party hosting, but it creates a large amount of reliability issues,  prevents the app from taking advantage of the infrastructure we provide for updates and verification, among other issues. For that reason, any "external" download links will not be supported by the app, and I encourage all developers to host their files directly on itchio if they want to support app users.

**Comment by ColonelPanic-42** [comment]
So... you'll support third party hosting on the website, but you won't support it on the app. And then when developers use the third party hosting (that you support on the website), you blame the developers for not supporting the app? You control both sides of the equation, the poor user experience is on your (itch.io) head, not on the developers.

**Comment by aethaedd** [comment]
If you can't support third party hosting in the app can you give us an option to pay for more storage for bigger games?
