### ISSUE TITLE
Something went wrong (immediately after running installer)

### ISSUE THREAD

**Issue by q00u** [itchio/itch#2781]
Got this popup immediately after running the installer:
```
Something went wrong

itch-setup, v1.26.0, built on Apr 21 2021 @ 18:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Got HTTP 500 for https://broth.itch.ovh/itch/windows-amd64/LATEST
github.com/itchio/itch-setup/setup.(*Installer).brothGetBytes
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/broth.go:64
github.com/itchio/itch-setup/setup.(*Installer).brothGetString
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/broth.go:76
github.com/itchio/itch-setup/setup.(*Installer).getVersion
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:131
github.com/itchio/itch-setup/setup.(*Installer).warmUp
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:107
github.com/itchio/itch-setup/setup.(*Installer).WarmUp.func1
	C:/msys64/home/amos/gitlab/builds/v4hXCzbZ/1/itchio/itch-setup/setup/setup.go:98
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1373
while getting latest version
Error during warm-up
```

(This says `itch-setup, v1.26.0` but the window says `itch Setup - 25.5.1`.)

Presumably this is a temporary itch server error, but it should probably fail more gracefully than this.

**Comment by beepboop1234** [comment]
Similar error here.

```
Something went wrong

itch-setup, v1.26.0, built on Apr 21 2021 @ 21:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": EOF
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up
```

**Comment by vikodine** [comment]
Also similar error. I am trying to buy the bundle for Ukraine but i can't install the app.

_Algo salió mal_

_itch-setup, v1.26.0, built on Apr 21 2021 @ 20:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd_
 
_rename C:\Users\Hector\AppData\Local\itch\staging\app-25.5.1 C:\Users\Hector\AppData\Local\itch\app-25.5.1: Acceso denegado._
_moving ready version to its proper place_
_Error during warm-up_

**Comment by leafo** [comment]
I can confirm https://broth.itch.ovh/itch/windows-amd64/LATEST is now loading correctly, and the issue should be resolved.

@vikodine Your error appears to be different. Please ensure you aren't using any virus software that may be impacting software you've downloaded off the internet.

Thanks

**Comment by beepboop1234** [comment]
I'm still getting the same error I posted previously. The address listed in my error seems to resolve in browser and I get a page with "25.5.1" on it.
