### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by bsobotka** [itchio/itch#2787]
Just installed the app (Win 10) and tried to log in to the app, keep getting this error: "There was a server error". I'm able to access the itch.io website just fine, and confirm that my login username/password are both correct.
![2022-03-10 08_02_27-Window](https://user-images.githubusercontent.com/21044951/157677954-c37db315-7fdd-4ba3-9613-6ddde63b675a.png)

**Comment by bsobotka** [comment]
Following up, looks like it's saying there's a password error, but I guarantee the password I'm entering is correct (I copy/pasted the same password that I had just previously used to log in to itch.io in my browser):
![2022-03-10 21_49_55-Window](https://user-images.githubusercontent.com/21044951/157798713-2213a82f-29e4-4a36-94a6-a9e1413d9f5f.png)

**Comment by leafo** [comment]
It's possible there was as separate server error happening when you initially reported this issue as we had some minor downtime. I recommend trying again and feel free to open the ticket if it's still happening.

**Comment by bsobotka** [comment]
Hello --

It is still happening. I have been trying now and again since I posted this just to check, and I've been getting the error every time. Just tried again now and no change.
