### ISSUE TITLE
Sticky tabs (preferences, etc.)

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#279]
Tabs like 'preferences' or 'install location contents' are transient for now — once you focus on something else, they disappear.

This is bad UX. Things shouldn't disappear unless you've asked them to.

I'd like the sidebar to work more like a tabset:
- `Cmd{,-Shift}-Tab` to go back & forth
- `Cmd-W` to close a tab (`Ctrl-W` on windows)
- `Cmd-1` to move to first tab, etc. (problematic because dashboard offsets everything, but it could be bound to Cmd-0 ?)
- Need to move 'Close window' to `Cmd-Shift-W` on mac

**Comment by smiley** [comment]
Tabsets might actually be clumsy for users like me who have a lot of collections:
![image](https://cloud.githubusercontent.com/assets/354181/12076464/8bc6d27e-b1b4-11e5-9069-75bfafeb8747.png)

Why not use pre-set keyboard shortcuts for "system" tabs, and not bind anything to collections?

**Comment by fasterthanlime** [comment]
Maybe as the UI evolves not all collections should always be shown in the sidebar, but rather they should be tabs that you can open & close at will.

I agree having to 'Ctrl-Tab' your way to a collection isn't really practical but then again you could still click on it :) (And by tabset I just really meant the switching behavior, I'm not planning on moving to horizontal tabs a-la Chrome/Firefox)

**Comment by smiley** [comment]
No, I got that you meant vertical tabs -- but since Preferences is at the bottom, Ctrl-Tab-ing would be hectic and Ctrl-(1-9) may not work. Plus, it messes with muscle memory. (New collection? Offset by 1)

If collections do end up not shown by default, they _should_ be grouped inside a `Collections` item, with the option of "pinning" specific collections to under the general menu. (Owned, Installed, Collections, etc.)

**Comment by fasterthanlime** [comment]
> If collections do end up not shown by default, they should be grouped inside a Collections item, with the option of "pinning" specific collections to under the general menu. (Owned, Installed, Collections, etc.)

Yeah that was mostly what I had in mind

> No, I got that you meant vertical tabs -- but since Preferences is at the bottom

Preferences has its own shortcut (`Cmd+,` on mac, `Ctrl+P` elsewhere I think). I actually moved it to before collections in master:

![screen shot 2016-01-03 at 11 23 34](https://cloud.githubusercontent.com/assets/7998310/12078301/81d258e4-b20c-11e5-90d8-63f9b9073742.png)

Maybe 'system tabs' should have their own number (that show up when you press 'Ctrl' ?) and additional tabs just shouldn't be part of the numbering system.

**Comment by fasterthanlime** [comment]
Tabs definitely work like a tabset now.

> (that show up when you press 'Ctrl' ?)

We even do that now! And it's super annoying b/c the keyup events get lost all the time (e.g. Cmd-Tab on mac) and the help text is stuck, haha.
