### ISSUE TITLE
Desktop app does not allow me to log in: "There was a server error"

### ISSUE THREAD

**Issue by bsobotka** [itchio/itch#2802]
Hello --
Please see issue #2787. This was closed, however the problem has not been solved. I have tried to login several times since then and am getting the same error every time. For additional context, I created a dummy account with a new e-mail address and have no problems logging into the app using that account's login info -- however I have been unable to do so with my main account.

Failing solving this particular issue, would it be possible to transfer all my purchases from one account to another, since it appears that the problem may be related with my account and not the app itself?

**Comment by leafo** [comment]
Can you please message support with more details about the account you're trying to log in with (email or username). You can reply back to me with the support ticket id here so I can followup.

https://itch.io/support

Thanks

**Comment by leafo** [comment]
It looks like you leaked your username in the previous issue, not sure if that was intentional.

I was able to identify the problem and it should be fixed now. Thanks for the report
