### ISSUE TITLE
itch fails to launch on Fedora 36

### ISSUE THREAD

**Issue by papasfilmsofficial** [itchio/itch#2840]
[Screencast from 08-01-2022 06:11:58 PM.webm](https://user-images.githubusercontent.com/50630783/182181667-fdf9664d-7d40-4612-8313-42bed2e76018.webm)

**Comment by YRTV** [comment]
[INFO itch@25.5.1 on electron@10.4.5 in production

https://github.com/electron/electron/pull/31091

Electron needs update. `--no-sandbox` can be used as temporary fix.

**Comment by papasfilmsofficial** [comment]
This seems to have fixed it but it definitely is a hustle having to do this every time.
