### ISSUE TITLE
Refresh locale from github on setup and/or on request

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#288]
May need to fork the file backend

Not sure about hitting github directly, but a hassle to mirror

This means we cannot change the meaning / interpolation of strings (needs to be new keys)

**Comment by smiley** [comment]
What about doing this asynchronously? The client could use "baked-in" files at first, and check GitHub for updated copies every day or so. It'd never block the UI, and the app could wait until it's put in the background to actually reload the strings.
