### ISSUE TITLE
Copy/Paste not working on macOS itch.io app

### ISSUE THREAD

**Issue by Sparen** [itchio/itch#2934]
For the past few years, one of my biggest gripes with the itch.io MacOS App has been the fact that you cannot copy/paste to/from the app. If I get a link to a game, I can't paste it into the internal app search bar. And if the default search doesn't work, that means I need to manually type out the URL to access the page in the app.

I saw that there was finally an update to the standalone macOS app and got my hopes up. My hopes were dashed like usual.

The inability to copy/paste is incredibly detrimental to the app and the only reason I haven't gotten rid of it entirely is because it manages a single download location for all of the stuff I've already downloaded, including free games that don't show up under purchases otherwise.

Currently on 25.6.1 for the Mac standalone app. macOS Ventura 13.4 (M1)

**Comment by alts** [comment]
Sorry for the wait. This had been bothering me, too. This was fixed in bb5e0f6. The latest [beta](https://itchio.itch.io/kitch) has the fix in place, and a full release should go live this week with it.

Thanks for the heads up @thejustinwalsh
