### ISSUE TITLE
Bug that scraps itch

### ISSUE THREAD

**Issue by Spyro24** [itchio/itch#2937]
If you enter Google's address in the address line, Itch will crash and you will have to delete everything from "/home/$user/.config/itch". Could you please fix the bug? (Triggered it with google.de!) PLUS: Please do it in such a way that you can also start the games via the start menu of the system.

**Comment by jls47** [comment]
@Spyro24 Are you still encountering this?  As of testing just now, it looks to have been resolved by one of the updates made since this issue was opened.

**Comment by alts** [comment]
As of the most recent version of the app, entering a url like `google.de` will open the url in a separate browser, so this issue shouldn't be possible anymore
