### ISSUE TITLE
URL routing doesn't canonicalize //, rendering 404 for new tab buttons in client

### ISSUE THREAD

**Issue by nc7s** [itchio/itch#2975]
<img width="1343" alt="image" src="https://github.com/itchio/itch/assets/4474501/05251a19-9a7a-4f52-8794-06c79e3ebcd1">

That's actually two problems:

- Your backend routing doesn't canonicalize `//`, so `//games` isn't canonicalized to and recognized as `/games`, which should be.
- The base URL constant has a slash, while added components have one too.
  - https://github.com/itchio/itch/blob/102011c51dc26a3142795c67394c365bb09cb309/src/common/constants/urls.ts#L1-L2
  - https://github.com/itchio/itch/blob/102011c51dc26a3142795c67394c365bb09cb309/src/renderer/pages/BrowserPage/newTabItems.ts#L33-L35

**Comment by 3ter** [comment]
This seems like a valid improvement. Perhaps a good first issue.
