### ISSUE TITLE
Game jam entries text colour in dark mode

### ISSUE THREAD

**Issue by madmarcel** [itchio/itch#2979]
Dark dark grey text on a black background.
Can't read that!
Have checked other gamejams, same issue.

See pic.

![SmartSelect_20240102_143954_Chrome](https://github.com/itchio/itch/assets/2075299/6397f971-b4c7-47a6-8a3c-d5f2e86fd350)

**Comment by Raccoon-Formality** [comment]
There is also a similar issue on the jam submission pages

See photo:

![image](https://github.com/itchio/itch/assets/120414230/ec49afdb-7cca-4b59-a9d0-acb742e2102b)

This also was happening on desktop but I don't have a screenshot of that right now.

**Comment by leafo** [comment]
Thanks for the report, issue is now fixed
