### ISSUE TITLE
Red rogue SWF upload is incorrectly tagged Linux

### ISSUE THREAD

**Issue by Jord-JD** [itchio/itch#298]
:rotating_light: Game [Red Rogue](http://st33d.itch.io/red-rogue) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d3b091f153b6abad3a41).

Game will not install. This was found in the current 'Bite-sized gems' section of the itch.io app.

**Comment by fasterthanlime** [comment]
That's actually an .swf file tagged as a linux executable, supporting those is out of scope for itch right now.
