### ISSUE TITLE
Users easily miss "No thanks, just take me to the downloads"

### ISSUE THREAD

**Issue by jestarray** [itchio/itch#2986]
I currently have a free published game on itch and I had probably 10% of players tell me they thought they had to pay leading them not to download it at all. I'd suggest adding a $0.00 button? Or a free button where the $1.00 button is?

**Comment by 3ter** [comment]
This repository is about the desktop app. When there's a free game or a game you own the app allows you to install with a big red button 😃 (without having to answer the payment request).

For the web version I agree, **in case you allow the option to be paid** (e.g. [allow to be paid](https://hengikken.itch.io/replay) in contrast to [free as in free beer](https://cm9-animation.itch.io/another-princess-is-in-our-castle)) it's a little bit too "greyed out" for me as well.
![image](https://github.com/itchio/itch/assets/11499929/47692b54-18a6-46d0-bf03-99f76816c94f)

Please take the issue to the itch community: https://itch.io/board/580406/ideas-feedback and close this one.

**Comment by jestarray** [comment]
Alright, closed in favor of dropping the report here: https://itch.io/t/3567113/users-easily-miss-no-thanks-just-take-me-to-the-downloads
