### ISSUE TITLE
Unable to access website or app

### ISSUE THREAD

**Issue by ChickenChunk579** [itchio/itch#3001]
A few days ago, an issue started for me where when i try to access the itch.io website in Chrome, I get this error: 
![image](https://github.com/itchio/itch/assets/87714759/b8436533-0427-40bd-8205-d8ba1d453441)
In the app, a similar thing happens:
![image](https://github.com/itchio/itch/assets/87714759/c1dc19ad-eb6d-4147-b840-2e33e1cd5d3a)
even though i definitely have internet connection since any other site works. Using dig on WSL2, using the same DNS servers as my host machine, I tried requests using 8.8.8.8, 8.8.4.4, 1.1.1.1 etc DNS servers and it all send the ip 0.0.0.0. My ISP doesn't block custom DNS servers, and it works when using mobile data on my phone but not with WiFi.

Additionally, using a website like www.nslookup.io, i get the A record the address 173.255.250.29 and when I open that in a browser, i get this error:
![image](https://github.com/itchio/itch/assets/87714759/8cc01ca8-783e-4140-84ae-f31870fad3c1)

**Comment by HaydenBat** [comment]
Did you find the problem? I am having this exact issue. Am on arch linux and tried with both Firefox and Chrome.

**Comment by ChickenChunk579** [comment]
No, although I did find that it works on Edge, but not on Chrome. It also happens with a few other websites like the ngrok tcp tunnels, but that works if I lookup the ip

**Comment by zipzapchap** [comment]
same issue here. Both Chrome and Librewolf refuse to allow me access any .itch.io links. If anyone figures this out I would be very grateful.

**Comment by Teptagon** [comment]
same issue but edge doesnt work... so i completely have no access.
edit: phones dont work as well, even logged out

**Comment by zipzapchap** [comment]
For anyone who is still in this thread, the only solution I've found so far is using Croxy Proxy:
https://www.croxyproxy.com/

**Comment by ChickenChunk579** [comment]
Update: This seems to work fine now for me? On chrome, the web-page now opens correctly.

**Comment by zipzapchap** [comment]
Agreed. This is now functional on Librewolf (firefox-based) as well. Thank you to whomever fixed this

**Comment by madara991** [comment]
same issue  in Chrome and any another browser
