### ISSUE TITLE
[linux] game This Little Piggy broken for v0.11.3

### ISSUE THREAD

**Issue by Seegras** [itchio/itch#301]
:rotating_light: Game [This Little Piggy](http://danielsnd.itch.io/this-little-piggy) is broken for me.

:running: On 64bit Linux, strace:

write(2, "Got a bad hardware address lengt"..., 55) = 55
write(2, "\n", 1)                       = 1
write(2, "Got a bad hardware address lengt"..., 55) = 55
write(2, "\n", 1)                       = 1
write(2, "Got a bad hardware address lengt"..., 55) = 55
write(2, "\n", 1)                       = 1

etc. It's a known Unity/Mono bug with older Unity versions on 64bit Linux.

**Comment by fasterthanlime** [comment]
Again, I suggest contacting the developer directly - this issue tracker is for when it's itch's fault.

In doubt, anyone is welcome to open an issue but when it's clearly a game bug, it shouldn't be reported here.
