### ISSUE TITLE
[linux] game The Lighthouse Keeper's Treasure broken for v0.11.3

### ISSUE THREAD

**Issue by Seegras** [itchio/itch#303]
:rotating_light: Game [The Lighthouse Keeper's Treasure](http://stone-baked-games.itch.io/the-lighthouse-keepers-treasure) is broken for me.

:running: Game runs, Hints appear but scenery is blank. On Linux 64bits, Nvidia drivers.

**Comment by fasterthanlime** [comment]
That sounds like a problem to take up directly with the developer, as it's not itch-specific.

You can apparently reach them at https://twitter.com/StoneBakedGames

**Comment by Seegras** [comment]
Allright; the point is, if you click in the itch client on the broken heart for a game, it automatically opens a new issue for itch on github. So that's why I thought it needs to be reported here.

**Comment by fasterthanlime** [comment]
Of course :) It's not wrong of you to actually post the issue that itch creates, and it's not wrong of me to close it once I've made sure it wasn't the client's fault. The system is working!

That auto-report functionality is early alpha stuff btw — hopefully later on we'll have a problem to report problems directly to the developers. We do have their e-mail but don't want to spam their mailbox. Instead, it should be a proper functionality on the itch.io website, where they can manage their notification settings, etc. — I hope you see my point.
