### ISSUE TITLE
Registration button opens browser with incorrect URL

### ISSUE THREAD

**Issue by veatla** [itchio/itch#3047]
Version:
  - itch 26.1.9
  - butler 15.21.0
  - itch-setup 1.16.0

![image](https://github.com/itchio/itch/assets/38946653/b4fb4934-4b53-42fb-b031-8cb77c48d674)

**Comment by Sahil-Gulihar** [comment]
Works fine for me

**Comment by veatla** [comment]
> Works fine for me

😤😤😤😤😤😤

**Comment by veatla** [comment]
here is video
[New Project.webm](https://github.com/itchio/itch/assets/38946653/8f68fff2-ff3d-4fd2-840e-11fcc53c0b8f)

**Comment by alts** [comment]
This was recently fixed in f91e12af2fb425882dff3a36da9d9ecc49c1f3dd

The next release will resolve the issue. Until then, please register on the itch site 🙇 sorry!
