### ISSUE TITLE
[win32] game Nusantara: Legend of The Winged Ones broken for v0.11.3

### ISSUE THREAD

**Issue by hugoleguellec49** [itchio/itch#310]
:rotating_light: Game [Nusantara: Legend of The Winged Ones](http://sweetchiel.itch.io/nusantara-legend-of-the-winged-ones) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c69d4091ccb258d06ffe).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This is because the game is packaged using rar — the best thing you can do is get in touch with the developer & point them to this page: http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games
