### ISSUE TITLE
No Such Host during App Setup/install

### ISSUE THREAD

**Issue by worthyone** [itchio/itch#3117]
On Linux Mint:
2024/11/29 03:43:57 Install error: while getting latest version: While performing GET request to https://broth.itch.ovh/itch/linux-amd64/LATEST: Get "https://broth.itch.ovh/itch/linux-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
2024/11/29 03:43:57 Fatal error: Warm-up error: while getting latest version: While performing GET request to https://broth.itch.ovh/itch/linux-amd64/LATEST: Get "https://broth.itch.ovh/itch/linux-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host

**Comment by NOLEGAS** [comment]
Just got the same error on windows

Something went wrong

itch-setup, v1.26.0, built on Apr 22 2021 @ 03:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up

**Comment by AvenIsHere** [comment]
yep same error here too on windows 11

Something went wrong

itch-setup, v1.26.0, built on Apr 22 2021 @ 02:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up

**Comment by Pemarces273** [comment]
Something went wrong

itch-setup, v1.26.0, built on Apr 22 2021 @ 09:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up

huh???

**Comment by pacnpal** [comment]
Same issue here on macOS. I did find you can download and run the latest build from here, you just have to create the install directory yourself: https://itchio.itch.io/itch

**Comment by dsenyushkindev** [comment]
Same issue on Pop OS, however from the variety of platforms error shows up on it might not be related to the OS

**Comment by Zizzs** [comment]
Encountering the same when installing the Itch launcher on Windows 10.

**Comment by TheLounger** [comment]
Well, this is awkward. The server from which the setup should download the latest version is supposed to be `broth.itch.zone`, as written [here](https://github.com/itchio/itch?tab=readme-ov-file#about-itch-setup) and [here](https://github.com/itchio/itch-setup/commit/5b9c9e11377c93ac906a4c1c587905eb8e08c7b7). They must be serving us an old `itch-setup.exe` or something.

### Dirty fix
I made it work by putting this into my `hosts` file (`C:\Windows\System32\drivers\etc\hosts`)
```172.67.132.40 broth.itch.ovh```

Proof that `172.67.132.40` is legit: https://who.is/dns/broth.itch.zone

### Result
![Annotation](https://github.com/user-attachments/assets/6e98452b-9d4c-478d-a62c-c10df7297f10)

**Comment by leafo** [comment]
Can you please test the "bleeding edge" version of itch setup located here for your platform: https://itchio.itch.io/itch-setup

It should be the one with the date 2023

**Comment by baptisteguidoux** [comment]
> Can you please test the "bleeding edge" version of itch setup located here for your platform: https://itchio.itch.io/itch-setup
> 
> It should be the one with the date 2023

It worked for me, thanks.

**Comment by worthyone** [comment]
> Can you please test the "bleeding edge" version of itch setup located here for your platform: https://itchio.itch.io/itch-setup
> 
> It should be the one with the date 2023

Fixed with this. Thank you!

**Comment by leafo** [comment]
Please try again, we had some downtime with our legacy update server that was still hard-coded in a few places.

That said, we've since pushed out patched versions of the app and related software. Please make sure you update to the latest version to ensure you don't have any issues accessing the app in the future: https://itch.io/t/4351835/app-and-butler-updates-may-require-manual-intervention
