### ISSUE TITLE
Instalación errónea de Itch.io

### ISSUE THREAD

**Issue by LegitJD** [itchio/itch#3126]
"Algo salió mal

itch-setup, v1.26.0, built on Apr 22 2021 @ 03:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up"

Según varios problemas, la solución es variable:

El error que estás enfrentando con el instalador de Itch.io está relacionado con problemas para conectarse a la URL https://broth.itch.ovh, que el programa utiliza para descargar archivos necesarios durante la instalación. Este problema puede deberse a varias razones, como:

1. Problemas de Conexión a Internet
Verifica que tu conexión a internet esté funcionando correctamente.
Intenta abrir otros sitios web en tu navegador para confirmar que no es un problema generalizado.

2. Restricciones de DNS
El mensaje "lookup broth.itch.ovh: no such host" indica que el sistema no puede resolver el nombre de dominio broth.itch.ovh. Esto puede deberse a problemas con tu servidor DNS.
Prueba cambiando tu servidor DNS por uno público, como:
Google DNS: 8.8.8.8 y 8.8.4.4
Cloudflare DNS: 1.1.1.1 y 1.0.0.1
Para cambiar el DNS en Windows:
Ve a Configuración de red.
Selecciona tu conexión activa (Wi-Fi o Ethernet).
Edita las propiedades del protocolo IPv4 e ingresa los valores de DNS públicos.

3. Problemas del Servidor de Itch.io
Es posible que los servidores de Itch.io estén caídos o experimentando problemas. Esto puede ser temporal.
Verifica el estado de los servidores de Itch.io en sitios como [DownDetector](https://www.downdetector.com/) o consulta sus redes sociales para actualizaciones.

4. Bloqueo por Firewall o Antivirus
Algunos programas de seguridad pueden bloquear el acceso del instalador a internet.
Desactiva temporalmente tu firewall o antivirus y prueba nuevamente. Si funciona, deberás agregar una excepción para el instalador de Itch.io.

5. Descargar Manualmente el Programa
Si el problema persiste, puedes intentar descargar Itch.io de manera manual:
Ve a la página de descargas directa: https://itch.io/app.
Descarga y ejecuta la versión más reciente del programa desde allí.

6. Modo de Compatibilidad
Si estás usando una versión antigua del instalador, actualízala.
Ejecuta el archivo en modo de compatibilidad (clic derecho > Propiedades > Compatibilidad > Ejecutar como administrador).

**Comment by lexi-the-cute** [comment]
so, there's 5 separate issues open for the same error. i'm not part of the Itch team, so i can't comment on if they read these issues. would like to report that we should focus on a single issue. the original one being https://github.com/itchio/itch/issues/3122

you should be able to manually download at copy at https://itchio.itch.io/butler until the automation friendly server's dns is back up

**Comment by leafo** [comment]
Please try again, we had some downtime with our legacy update server that was still hard-coded in a few places.

That said, we've since pushed out patched versions of the app and related software. Please make sure you update to the latest version to ensure you don't have any issues accessing the app in the future: https://itch.io/t/4351835/app-and-butler-updates-may-require-manual-intervention
