### ISSUE TITLE
[linux] [pico-8] game CELESTE broken for v0.11.3 

### ISSUE THREAD

**Issue by smeir** [itchio/itch#320]
:rotating_light: Game [CELESTE](http://mattmakesgames.itch.io/celeste) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/39a10328521c3974cf94).

**Comment by fasterthanlime** [comment]
That's a pico-8 game, but I'm interested in supporting those — cf. #170

**Comment by smeir** [comment]
That would be really nice.

**Comment by fasterthanlime** [comment]
Closing in favor of #170
