### ISSUE TITLE
[win32] tool Tiled map editor broken for v0.11.4

### ISSUE THREAD

**Issue by bjorn** [itchio/itch#322]
:rotating_light: Tool [Tiled map editor](http://thorbjorn.itch.io/tiled) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/57ae5c6f88e57f59d5e2).

I'm the developer of Tiled and would like to know what may be wrong. The debug log does not really say anything else than "nsis installer exited with code 127". What may be the issue?

I'm not sure which file itch downloaded. I tried the 32-bit Windows installer outside of itch, and there it worked fine.

Thanks for any help!

**Comment by fasterthanlime** [comment]
Hey Thorbjørn, thanks for testing it with the app, I'll take a look tomorrow before releasing 0.12!

Haven't experienced issues with silent NSIS installations yet but debugging installers is my jam this week so.. looking forward to find out why.

(Btw, if your NSIS script/config is readily available somewhere (since Tiled is open source, right?) that could be useful to help figure it out)

**Comment by bjorn** [comment]
Thanks for looking into it!

Indeed my NSIS script is available over here: https://github.com/bjorn/tiled/blob/master/dist/win/tiled-mingw.nsi

**Comment by fasterthanlime** [comment]
Alright, it's because of external downloads - I think I have a way around it

**Comment by fasterthanlime** [comment]
Related issues: https://github.com/leafo/itch.io/issues/307 and https://github.com/leafo/itch.io/issues/306

**Comment by fasterthanlime** [comment]
Worked around it in master by copying to '.exe' variant before installing.

Next problem is that it identifies the wrong executable (launches the automappingconverter). I'll add a few more heuristics.

**Comment by fasterthanlime** [comment]
All issues above are resolved by https://github.com/itchio/itch/commit/443caf3e53e438dad120aafb4af563803bc400bf — will be fixed in next release

**Comment by bjorn** [comment]
Wow, that was fast, thanks!

Interesting approach with those heuristics. I do think it would make sense to add support for a more explicit manifest/settings file that could be included with the release, but I understand you're trying to make as many of current packages work out of the box as possible.

**Comment by fasterthanlime** [comment]
> Interesting approach with those heuristics. I do think it would make sense to add support for a more explicit manifest/settings file that could be included with the release, but I understand you're trying to make as many of current packages work out of the box as possible.

You read my mind many times in that sentence — for manifest support, see https://github.com/itchio/itch/issues/92

Adding better support for installers made me think though: I'm not sure the manifest file should be shipped in the game archive. Repacking a new archive & uploading it all over again seems wasteful. Maybe it should just be a separate text field / upload in the itch.io UI.

What do you think @leafo  ?

**Comment by bjorn** [comment]
It would definitely be nice if this information could be provided through the itch.io website, especially given that it is only relevant for itch and is otherwise another strange file sitting around. Also, that would give you a place where people can provide the version of Love2D that is required for example, in case of pure .love files.
