### ISSUE TITLE
itchio://launch/GAME_ID url support

### ISSUE THREAD

**Issue by RobLoach** [itchio/itch#324]
Allow launching and installing games from the command line.

**Comment by fasterthanlime** [comment]
Currently if you do `itch itchio://install/GAME_ID` it'll go and install that game.

(Actually it's broken on Linux in 0.11.x but you get the idea)

That said, if the client isn't running yet, it'll start it - it's still the full GUI thing, etc.

If you're talking about a small CLI tool that would just install a game and that's it, it's out of scope for this particular project.

**Comment by RobLoach** [comment]
> Currently if you do itch itchio://install/GAME_ID it'll go and install that game.

That's excellent! Thanks a lot. Is there a way to launch the given game? Looking at [url-store.js](https://github.com/itchio/itch/blob/master/app/stores/url-store.js#L58), it looks like it only handles `install` URLs. Would be nice to add a `launch`, possibly. Like you mentioned, it may be out of scope for this project as it's all the GUI.

> Actually it's broken on Linux in 0.11.x

Worked just fine here. `0.11.3`

**Comment by fasterthanlime** [comment]
> Would be nice to add a launch, possibly.

Yeah definitely

> Worked just fine here. 0.11.3

Ah maybe I forgot that I fixed it earlier? The problem was in the .deskop file, it was missing a '%U'. Maybe it worked with some desktop environments, not all. Not sure.
