### ISSUE TITLE
[linux] game Rebuild / Resist broken for v0.11.3

### ISSUE THREAD

**Issue by Aricg** [itchio/itch#330]
:rotating_light: Game [Rebuild / Resist](http://studiominiboss.itch.io/rebuild-resist) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/be86eb331534f4b54c28).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Unfortunately .love files aren't supported out of the box yet — closing this in favor of #135
