### ISSUE TITLE
[linux] game Monster RPG 2 broken for v0.11.4

### ISSUE THREAD

**Issue by ghost** [itchio/itch#331]
:rotating_light: Game [Monster RPG 2](http://nooskewl.itch.io/monster-rpg-2) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/af2d31e8b8895addebb9).

:running: The problem is not that it failed the first time, I'm just wondering if the archives are cached, because I updated the TAR.GZ file but I'm still getting the old one when I download.

**Comment by fasterthanlime** [comment]
Ah, might be the same issue as #336

**Comment by ghost** [comment]
In my case the folder name hasn't changed, nor has the filename of the archive. When it installs there's only one directory. Although that issue would apply on a normal update, I think this one may be different?

**Comment by fasterthanlime** [comment]
(Btw "not launching .so files" has been fixed in 0.12)

It's hard to tell what it's actually downloading with that log. I'll look into it more later

**Comment by fasterthanlime** [comment]
@trentg Are you still experiencing the issue with v0.12.4 ?

**Comment by ghost** [comment]
No, it's working fine now. Thanks!

**Comment by fasterthanlime** [comment]
Great, thanks for reporting back! :star2:
