### ISSUE TITLE
[linux] tool Superpowers broken for v0.11.4

### ISSUE THREAD

**Issue by Valdaria** [itchio/itch#334]
:rotating_light: Game [Superpowers](http://sparklinlabs.itch.io/superpowers) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/df3e26c3e4ff528974ee).

:running: I'm on the latest linux Gnome version.

**Comment by fasterthanlime** [comment]
Ah yeah, sure enough it's launching a library...

It's been fixed in v0.12, let's see if it works better there

**Comment by fasterthanlime** [comment]
@Valdaria a few v0.12.x versions have been released already, v0.12.4 definitely should launch superpowers on Linux :)
