### ISSUE TITLE
[darwin] game VA-11 HALL-A broken for v0.11.4

### ISSUE THREAD

**Issue by mipstian** [itchio/itch#335]
:rotating_light: Game [VA-11 HALL-A](http://kiririn51.itch.io/valhalla-bar) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/af886b0312241685a4db).

:running: Seems like there are "no downloads" available for this title, in which case the download button probably shouldn't be displayed at all :)

**Comment by fasterthanlime** [comment]
So, this is a tricky one — there are $0-minimum uploads available, and the game does have OSX uploads, just not a combination of those.

ideally the game page would be adjusted by the developer with:
- The special demo version marked as a 'demo' download.
- $4.99 being the regular price of the game
- The soundtrack being a $7.99 unlock

**Comment by fasterthanlime** [comment]
@mipstian Anyway, buying the game will solve the issue :) Things are working as expected except for the Install button that shouldn't be there, but there's not really a way to figure that out without spamming the API server for now.
