### ISSUE TITLE
Updating Superpowers fails

### ISSUE THREAD

**Issue by elisee** [itchio/itch#336]
Hey ^_^,

The Superpowers folder has a different name for each release, for instance `superpowers-0.17.0-win-x64` and `superpowers-0.18.0-win-x64`. When an update is released, it looks like itch unzips it next to the existing one instead of deleting the old one.

This causes two issues:
- When launching, itch finds `Superpowers.exe` from the old version first and decides to launch it, rather than the new one.
- When restarting itch, it will try to update Superpowers again every time.

**Comment by fasterthanlime** [comment]
So there's 0 data from the old version that needs to carry over to the new version ?

> When restarting itch, it will try to update Superpowers again every time.

actually that one's a feature

**Comment by elisee** [comment]
> So there's 0 data from the old version that needs to carry over to the new version ?

Not inside the `superpowers-x.y.z-platform` folder. All user data is stored in `%APPDATA%/Superpowers`.

**Comment by fasterthanlime** [comment]
> All user data is stored in %APPDATA%/Superpowers.

Alright we'll need to talk about that too

**Comment by fasterthanlime** [comment]
Collateral issue: the reason it downloads the full thing everytime is because GitHub releases doesn't support partial HTTP requests.

As a result, butler tries to resume download, but github serves the entire file instead. butler should compare sizes, decide it's the same file, close the http connection and be happy.

Could you  open a butler issue for that @elisee  ?

**Comment by fasterthanlime** [comment]
@elisee you owe me so many :beers:

**Comment by elisee** [comment]
@fasterthanlime :+1: You're welcome to grab a shandy at my place anytime! :shandy:

**Comment by fasterthanlime** [comment]
@elisee It's your turn to visit dear
