### ISSUE TITLE
Support linux text installer of Super Hexagon

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#337]
Same questions as always:
- Can we uniquely identify the installer type by looking at the file?
- Does it have a 'silent' switch?
- Does it have an 'install folder' flag?

**Comment by fasterthanlime** [comment]
Just mailed Ethan asking for help from the source :star2:

**Comment by flibitijibibo** [comment]
These are MojoSetup packages:

https://icculus.org/mojosetup/

They're self-extracting zipfiles, so you can just treat them like zips and grab the game from data/. I dunno exactly how you'd autodetect them though.

**Comment by fasterthanlime** [comment]
Alright, here's a reasonable way to sniff it: file(1) --brief's output has to start with the `ELF`, and `7za l thefile` exits with 0.

That'll work for other self-extracting zip files too :)

**Comment by fasterthanlime** [comment]
Success!

![super-hexagon-success](https://cloud.githubusercontent.com/assets/7998310/12217130/878de934-b6f7-11e5-9495-a678b4eb5d02.png)
