### ISSUE TITLE
[darwin] tool Aseprite broken for v0.11.4

### ISSUE THREAD

**Issue by Alyxdev-xyz** [itchio/itch#338]
:rotating_light: Game [Aseprite](http://dacap.itch.io/aseprite) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8c40d85420967e2ef2dd).

:running: Any additional details can go here!

I downloaded Aseprite on my mac, but instead of being "installed", it's "broken" :(

**Comment by fasterthanlime** [comment]
Hey @rtauziac, good news, 0.12 is out with DMG support, which should fix that issue.

Use the 'Help -> Check for Update' menu to upgrade or download directly from itch.io/app
