### ISSUE TITLE
Launching Ultra Hat Dimension from Itch.io launcher v0.12.0 starts wrong exe

### ISSUE THREAD

**Issue by DEagleson** [itchio/itch#339]
Keeps using vcredist_x86.exe instead of UltraHatDimension.exe and removing vcredist_x86 makes it think the game is broken and wants to redownload it.

**Comment by fasterthanlime** [comment]
`*vcredist*` sounds like a good pattern to penalize in sniffing, thanks

**Comment by fasterthanlime** [comment]
Link to game http://eniko.itch.io/uhd
