### ISSUE TITLE
[linux 64-bit] Missing dependency libnotify.so.4 in v. 0.12.0

### ISSUE THREAD

**Issue by fleskesvor** [itchio/itch#343]
After updating to v. 0.12.0 on 64-bit Linux (Mint 17), I'm no longer able to launch the client because of the missing dependency libnotify.so.4. To launch the client, I have to point LD_PRELOAD at the library in the Steam runtime, since that's the only 32-bit version of the dependency on my computer.

**Comment by fasterthanlime** [comment]
@fleskesvor wait, why are you running the 32-bit version of itch on 64-bit linux? we have both!

**Comment by fleskesvor** [comment]
I didn't realize that there was one. :$ I just clicked the "Linux" link on
http://itch.io/app and that gave me the 32-bit installer. The "Download
now" button gives me the 64-bit version though. Sorry for not checking that
before.

**Comment by fasterthanlime** [comment]
@fleskesvor not sure which distro you're running but we also have APT & YUM repositories: https://bintray.com/itchio

**Comment by fleskesvor** [comment]
I'm on Mint, so .deb works well for me. Both nuts.itch.zone/ and nuts.itch.zone/download/ serves the 64-bit .deb for me, while nuts.itch.zone/download/linux/ serves 32-bit.
