### ISSUE TITLE
[linux] Broken game for v0.10.2

### ISSUE THREAD

**Issue by bobvanderlinden** [itchio/itch#346]
Game [AirC.A.T](http://tsfreddie.itch.io/aircat) is broken for me.

Here's the [debug log](https://gist.github.com/0a200b96cd4adb7a158e).

**Comment by fasterthanlime** [comment]
@bobvanderlinden this has been fixed a while ago. Please upgrade to v0.12.0.

Also, since v0.11.4, we have APT & YUM repositories so you can stay up-to-date more easily on linux: https://bintray.com/itchio

**Comment by bobvanderlinden** [comment]
I thought I had just updated to 0.12.0, but checking again I was indeed using an earlier version. Sorry for the confusion!

**Comment by fasterthanlime** [comment]
@bobvanderlinden no problem :) (you can always check in the issue title that gets filed - or in the help menu if the app is still running)
