### ISSUE TITLE
[linux] Issue for v0.12.2

### ISSUE THREAD

**Issue by mstfacmly** [itchio/itch#353]
I've gotten the following error after upgrading from 0.11 to 0.12.2:
ENOENT: no such file or directory, lstat '/home/moustafa/.config/itch/bin/butler.7z'

I was able to get around it by creating the missing directory, and then faking the butler.7z file using 'touch', but then this error pops up:

Error ENOENT: no such file or directory, lstat '/home/[user]/.config/itch/bin/butler.7z-stage'

Currently running Ubuntu 15.10, using the precompiled amd64 .deb package provided on the itch website.

**Comment by fasterthanlime** [comment]
That certainly doesn't sound good..

I pushed a new butler version tonight, so it must've been trying to upgrade.

So, `/home/moustafa/.config/itch/bin/` didn't exist before?

**Comment by fasterthanlime** [comment]
Pushing new version asap.

**Comment by mstfacmly** [comment]
Just to confirm, the ./config/itch directory was there, but not the ./config/itch/bin dir. I'll check the new build as soon as it's up!

**Comment by fasterthanlime** [comment]
Makes sense. fstream/mkdirp used to handle all that for us, whereas now we have to be more careful. (Whole FS layer was rewritten between 0.12.0 and 0.12.1)

**Comment by fasterthanlime** [comment]
@MoustafaC 0.12.3 is out, let me know if it fixes it for you

**Comment by fasterthanlime** [comment]
More details available in the v0.12.3 release notes: https://github.com/itchio/itch/releases/tag/v0.12.3

**Comment by mstfacmly** [comment]
Confirm this fixes the issue!
