### ISSUE TITLE
Public restricted games should only be accessible to developer & buyers

### ISSUE THREAD

**Issue by Alamantus** [itchio/itch#356]
[The Midnight Station](http://studioanjin.itch.io/the-midnight-station) had an [alternate holiday version](http://studioanjin.itch.io/tms-se) in 2014 for the holidays that they made unavailable after the end of December 2014. I happened to still have the holiday version in one of my collections, and even though you can't download it from the game page, I was able to download it without any issue from the desktop itch.

That probably shouldn't work, right?

I have not tested this problem with any other games.

**Comment by fasterthanlime** [comment]
ping @leafo

**Comment by fasterthanlime** [comment]
A fix has been deployed

**Comment by newroser** [comment]
Thanks
