### ISSUE TITLE
Always load built-in locale before loading remote locale to avoid showing strings

### ISSUE THREAD

**Issue by donbright** [itchio/itch#358]
I am getting some humorous placeholders when I start Itch.io on my machine

![delme](https://cloud.githubusercontent.com/assets/896858/12224227/c1b49626-b7b0-11e5-9651-cfab325f9d03.png)

My machine is a ~5 year old HP Pavilion DV6 amd64 Laptop with graphics AMD Mobility Radeon HD 4225/4250, which was recently upgraded from ubuntu 14.04 to Ubuntu 15.04. 

The inciting incident was having to do a hard-lock poweroff reboot after attempting to start "Orchids to Dusk" in windowed mode. (The hard lock and reboot seems to be an ubuntu 15.04 thing, i have had it with other non-itch games)

**Comment by fasterthanlime** [comment]
Interesting. Are you running it in English? Is there an `en.json` file in `~/.config/chromium/itch/locales/en.json` ? If so, deleting it should work around that.

**Comment by fasterthanlime** [comment]
@donbright were you able to find out what happened?

**Comment by tylergregg** [comment]
This just happened to me on Windows 10, itch version 0.12.4. Deleting ~/AppData/Roaming/itch/locales/en.json fixed it.

**Comment by fasterthanlime** [comment]
Thanks for the report @tylergregg :star2: 

I've got a fairly good idea how to fix this (see new issue title), will include in a patch release soon

**Comment by fasterthanlime** [comment]
Should be closed by 2bca644ab1503efade0ce9768c29b11e2fd1835a — releasing new version soon.

**Comment by donbright** [comment]
update / upgrade of itch.io program (from ubuntu software center) has fixed this issue, thanks!

**Comment by fasterthanlime** [comment]
Great, thanks for reporting back! :star2:
