### ISSUE TITLE
[win32] game Conquest broken for v0.11.4

### ISSUE THREAD

**Issue by zga** [itchio/itch#359]
:rotating_light: Game [Conquest](http://outlands.itch.io/conquest) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f78b22917261dd885e47).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
itch does not support the .rar format by design — see http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games

also, you should upgrade to v0.12.3+ :) it has an explicit dialog for that.

**Comment by zga** [comment]
Thanks for the fast response!

My client just restarted to that update :)
