### ISSUE TITLE
[darwin] game Double Kick Heroes broken for v0.12.3

### ISSUE THREAD

**Issue by michieldegraaf** [itchio/itch#360]
:rotating_light: Game [Double Kick Heroes](http://blackmag-c.itch.io/double-kick-heroes) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1886c450e1553c9ac9de).

**Comment by fasterthanlime** [comment]
Unfortunately the game shouldn't be tagged osx / linux, as the 'upload' is actually a link to the web version.

@delahee should put that in the game's description rather than an upload :)

**Comment by delahee** [comment]
Will do it :)

As a side note, a "web" icon checker could be convenient for us web game creator. You could say that it is useless but I think of games like 
1- Mush which cannot be externalised to itch.
2- If we want to host the game ourself for analytics or version centralisation reason

![capture d ecran 2016-01-11 09 32 49](https://cloud.githubusercontent.com/assets/644444/12229290/99283352-b846-11e5-9c67-85bfa1c32af8.png)

If you think that what I say make sense, do you want me to open a ticket for this @fasterthanlime ?

++ and sorry for the nuisance.

**Comment by fasterthanlime** [comment]
> As a side note, a "web" icon checker could be convenient for us web game creator.

If your game can be embedded (as a .zip with an index.html in there - it can even itself be an iframe that presents your own website, but you won't get offline support in the app then), and you set your page type to 'HTML', you can check 'This upload will be played in the browser' on a particular upload.

**Comment by michieldegraaf** [comment]
Or simply download all files and run it locally in a WebKit wrapper.

**Comment by fasterthanlime** [comment]
> Or simply download all files and run it locally in a WebKit wrapper.

That's the plan (already done in https://github.com/itchio/itch/pull/328 - not merged yet) but that's not what david's link was. He was linking to his own web page, not to a downloadable archive that could be extracted then opened by itch.
