### ISSUE TITLE
[darwin] game Rebuild / Resist broken for v0.12.3 (.love mac)

### ISSUE THREAD

**Issue by astra-midnight** [itchio/itch#361]
:rotating_light: Game [Rebuild / Resist](http://studiominiboss.itch.io/rebuild-resist) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/087171016f1b2b46d3db).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Hey, thanks for reporting! :star2:

This game is distributing a `.love` file and tagging it as a native Linux & OSX version, which isn't true.

It's planned for the app to support that, see #135 - but until it does, developers should pack their games properly. Here's a guide: http://itch.io/t/11920/how-to-get-your-game-running-in-the-itch-app
