### ISSUE TITLE
[win32] game RK3000 broken for v0.12.3 (ENOTEMPTY)

### ISSUE THREAD

**Issue by primaerfunktion** [itchio/itch#362]
:rotating_light: Game [RK3000](http://primaerfunktion.itch.io/rk3000) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/35d978d34f2464e87571).

:running: Updated the game on itch, the update got downloaded by the app and got stuck while installing and put out an error that a folder wasn't empty. One file somehow couldn't be removed. Redownloading and reinstalling always stopped with the same error. Had to manually remove that folder that contained the file. Installing worked after I did that.

**Comment by fasterthanlime** [comment]
@primaerfunktion If you try 'Re-install' several times, can you reproduce the problem?

**Comment by primaerfunktion** [comment]
@fasterthanlime Wasn't able to reproduce it at all. Reinstalled a couple times without any problem and just uploaded a new build for the app to update and it worked as well. So yeah. Pretty weird. Don't know what happend there.

**Comment by fasterthanlime** [comment]
There's many possible causes and all of them are annoying. My plan is to start moving the fs layer over to butler, which is in golang, rather than to keep doing it in node.js

**Comment by fasterthanlime** [comment]
Closing in favor of #372

**Comment by fasterthanlime** [comment]
v0.12.6 shipped and no longer uses node.js for most filesystem operations
