### ISSUE TITLE
Open installation folder option vanishes if game fails to launch

### ISSUE THREAD

**Issue by Enichan** [itchio/itch#364]
When a game fails to launch the usual workaround method (opening the installation folder and starting the exe manually) vanishes as the options are replaced by the bug report/debugging options. This seems like an oversight to me.

**Comment by fasterthanlime** [comment]
It is. In the meantime, 'Alt-Click' and 'Shift-Click' should still work, as described in http://itch.io/t/11920/how-to-get-your-game-running-in-the-itch-app
