### ISSUE TITLE
[win32] game Super Sculptor! broken for v0.12.3

### ISSUE THREAD

**Issue by lonelydarksider** [itchio/itch#367]

**Comment by fasterthanlime** [comment]
@lonelydarksider was it a temporary fluke? It might happen if your computer/network is really slow, the link is only valid 10 seconds.

**Comment by lonelydarksider** [comment]
@fasterthanlime IDK what was it... seems like it just sorted itself out :walking:
will send crash reports if it happens again

**Comment by fasterthanlime** [comment]
Alright, thanks!
