### ISSUE TITLE
Make item order consistent in list/grid

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#368]
My Creations (and other tabs) in Itch don't seem to be sorted in any way that makes sense to me.

It's not alphabetical. It's not chronological according to when the game was added to Itch. It's not even sorted according to how I have set up my Itch.io profile page to display my games.

As a result, some of my creations that I'm most interested in working with are at the bottom of the list rather than at the top where I'd like them.

Can we get either one of the following: Games/items sorted one of the ways listed above (alphabetical, chronological, or according to my profile) or a feature to allow us to reorganize the lists?

**Comment by fasterthanlime** [comment]
Ah, so it's not the order in which tabs are displayed, it's the order in which items are displayed in the grid?

That's true, there's no order for them. I think they should be sorted by ascending alphabetical order, then by descending last_interacted_with_at.

**Comment by Deozaan** [comment]
> Ah, so it's not the order in which tabs are displayed, it's the order in which items are displayed in the grid?

Yes. Sorry for the ambiguity. :)

I like your proposed solution.

**Comment by fasterthanlime** [comment]
Note that in my fix, collections retain their original order, since collections you can control the order of in the website.
