### ISSUE TITLE
[linux] tool Aseprite broken for v0.11.0

### ISSUE THREAD

**Issue by ktallett** [itchio/itch#369]
:rotating_light: Game [Aseprite](http://dacap.itch.io/aseprite) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1daa1ab66947db7eeef2).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Known issue, for now David only distributes a .deb on Linux. I've poked him about a zipped portable version for Linux and he said he'd get back to me after his vacation (~ 2 weeks)

**Comment by fasterthanlime** [comment]
@ktallett also, you're using v0.11.0, which is old — you should upgrade to v0.12.4 or higher!

**Comment by ktallett** [comment]
Thanks for the response. I shall update in a mo. Seems as though the AUR
isn't up to date yet. A really nice, simple to install app though, great
job.

**Comment by fasterthanlime** [comment]
Updating the AUR now :)

**Comment by fasterthanlime** [comment]
Ah jeebus, had to upgrade my whole system, quadruple the amount of RAM my Arch VM has, and grab yaourt just so I could get all the deps, but 0.12.4 is on AUR right now. Enjoy! :tada:

**Comment by ktallett** [comment]
Thanks a lot for all that man. I will. I'll update now. :)
