### ISSUE TITLE
AIR installer exits with code 10 (double kick heroes, win32, v0.12.4)

### ISSUE THREAD

**Issue by chunkymoe** [itchio/itch#370]
:rotating_light: Game [Double Kick Heroes](http://blackmag-c.itch.io/double-kick-heroes) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5cb5567eb65bae30a138).

:running: Game keeps trying to install. Asks to finalize install, then runs numbered .exe file. Game never finishes install process.

**Comment by fasterthanlime** [comment]
Exit code 10 isn't documented in air installer docs: http://help.adobe.com/en_US/air/redist/WS485a42d56cd19641-70d979a8124ef20a34b-8000.html :panda_face: 

Can you take a look into these folders:

```
The AIR installer automatically creates log files in the following locations:

- Windows XP: C:\Documents and Settings\user name\Local Settings\Application Data\Adobe\AIR\logs 
- Windows Vista / Windows 7: C:\Users\user name\Local Settings\Application Data\Adobe\AIR\logs (Note that some of these folders are hidden by default.) 
- Mac OS X: Open "Console" to view logging. 
- Linux - an Install.log file is automatically created during installation in the following folder: ~/.appdata/Adobe/AIR/Logs
```

**Comment by fasterthanlime** [comment]
@delahee any ideas?

**Comment by delahee** [comment]
For further reference : 

Docs : https://helpx.adobe.com/air/kb/air-developer-tool-adt-error.html

I don't understand a damn thing except that "maybe" you need an internet connection at install time so that the package is validated against its certificate..

Don't even know if it is making sense...

**Comment by fasterthanlime** [comment]
@jdwohlever Could you try installing https://get.adobe.com/air/ and installing DKH again using the app?

**Comment by fasterthanlime** [comment]
I don't think I want to add any more AIR installer support to itch for now.
