### ISSUE TITLE
Add desktop-file-utils as a deb dependency

### ISSUE THREAD

**Issue by ghost** [itchio/itch#371]
On Debian Stable (amd64) itch deb package (0.12.4) is reporting errors on post-install script, it can't execute update-desktop-database. Could you please add "desktop-file-utils" as a dependency to the package

**Comment by fasterthanlime** [comment]
Good catch, thanks. Out of curiosity, what desktop environment are you running, that doesn't have desktop-file-utils as a dependency?

(My main Linux test box is running Debian wheezy, so that I don't fall into too many Ubuntuisms)

**Comment by fasterthanlime** [comment]
If anyone wants to beat me to the punch, they can submit a PR to this repo: https://github.com/itchio/ci.itch.ovh/blob/master/src/jobs/itch.yml

**Comment by ghost** [comment]
KDE 4.14.2 is the one to blame here

**Comment by fasterthanlime** [comment]
Won't be in 0.12.5, which was cut before this issue was opened, apologies in advance.

**Comment by fasterthanlime** [comment]
Will be in v0.12.6 or above, thanks again for bringing this to my attention! :star2:

**Comment by Bugsbane** [comment]
Still getting this more than 3 years later, using current Kubuntu 18.10

**Comment by fasterthanlime** [comment]
Well, the .deb package has been deprecated since v25 was released.

You can grab the latest auto updating build of itch from https://itch.io/app

**Comment by Bugsbane** [comment]
Yeah, that's what I grabbed, not a deb, and it's giving me the same error as the OP. I installed desktop-file-utils and then it worked fine.
