### ISSUE TITLE
[linux] game Untold Universe (Alpha Demo) broken for v0.12.3

### ISSUE THREAD

**Issue by Jord-JD** [itchio/itch#373]
:rotating_light: Game [Untold Universe (Alpha Demo)](http://fenrislairstudio.itch.io/untold-universe) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/99b36ca7ae1b174fc108).

**Comment by fasterthanlime** [comment]
.deb packages are unfortunately unsupported

I know 7-zip can extract them, with some LD_LIBRARY_PATH magic we might even be able to launch them, but there's still things like dependencies etc. that I'm not sure we'd be able to support.

We might, of course, just run `apt-get` on Debian platforms but that would exclude all other Linux flavors. I still recommend that developers follow #86 when distributing linux guides — having a .deb or a .rpm is a nice bonus, but the portable version of a game really should be the primary way to distribute it.
