### ISSUE TITLE
Add facility to probe linux executables for missing dependencies

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#375]
Basically, `LD_LIBRARY_PATH` all the .so we find, and parse `ldd` output. Don't prevent the game from launching, but if it crashes, it'll give us a good idea why.

**Comment by fasterthanlime** [comment]
> it'll give us a good idea why.

And ultimately it should prevent people from reporting games as broken on this issue tracker, but tell them to install dependencies instead — if we can figure out which packages provide which libs, even better.

**Comment by fasterthanlime** [comment]
Beware ldd: http://www.catonmat.net/blog/ldd-arbitrary-code-execution/

**Comment by probonopd** [comment]
See [this thead](http://lists.qt-project.org/pipermail/development/2016-September/thread.html#27204) for ideas on how to do what ldd does without actually using ldd.

**Comment by fasterthanlime** [comment]
butler's elfprops command has logic for that now:

```
☁  SermentBetaDemo $  butler elfprops --trace lib/linux-x86_64/SermentBeta
{
  "arch": "amd64",
  "imports": [
    "libpython2.7.so.1.0",
    "libpthread.so.0",
    "libdl.so.2",
    "libutil.so.1",
    "libm.so.6",
    "libc.so.6"
  ]
}

- /home/amos/.config/itch/apps/serment-contract-with-a-devil-beta-demo/SermentBetaDemo-steam/lib/linux-x86_64/SermentBeta
  - /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
    - /lib/x86_64-linux-gnu/libz.so.1
      - /lib/x86_64-linux-gnu/libc.so.6
        - /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    - /lib/x86_64-linux-gnu/libpthread.so.0
    - /lib/x86_64-linux-gnu/libdl.so.2
    - /lib/x86_64-linux-gnu/libutil.so.1
    - /lib/x86_64-linux-gnu/libm.so.6
```

It's not used for anything yet.
