### ISSUE TITLE
itch says "Payments disabled" but they are not

### ISSUE THREAD

**Issue by elisee** [itchio/itch#379]
We accept donations for [Superpowers](http://sparklinlabs.itch.io/superpowers) but the itch app thinks we do not:

![image](https://cloud.githubusercontent.com/assets/446986/12334576/f781388e-bafa-11e5-92c7-3130ffb2f89a.png)

Running v0.12.6. Tried with both the elisee and sparklinlabs users

**Comment by fasterthanlime** [comment]
@elisee Does it pop the purchase window first, or does it just go straight to this dialog?

Do the logs show anything interesting?

**Comment by fasterthanlime** [comment]
Btw I can't reproduce this in master, it does prompt me to purchase it.

**Comment by elisee** [comment]
I get this dialog right away. Nothing relevant in devtools console. Anything else I should be looking at?

Could it be happening because I don't actually own Superpowers and/or I'm the author / a contributor?

**Comment by fasterthanlime** [comment]
I'll look at what's happening in 0.12.6, or just release 0.12.7 and see what's up

**Comment by elisee** [comment]
As mentioned in DM: `game.can_be_bought` is `undefined` for me. Accessing it through the API link you gave me _does_ return `"can_be_bought": true` though.

I tried deleting `db.jsonl` and it was recreated with the `can_be_bought` key still missing for Superpowers. Not sure where to look first. If you have pointers, I'm willing to spelunk. :hammer:

**Comment by fasterthanlime** [comment]
Interesting tidbit: when I get the Superpowers game entry from http://itch.io/api/1/me/game/23136, can_be_bought is true, but when I get it from a collection, can_be_bought is false.

I'm not sure how it's possible that you got undefined @elisee (I'm interested in your code) but I'll stop relying on `can_be_bought` for now.

**Comment by fasterthanlime** [comment]
v0.13.0 shipped with a workaround for that
