### ISSUE TITLE
Allow downloading demo for paid game

### ISSUE THREAD

**Issue by lockvia** [itchio/itch#385]
:rotating_light: game [Prank Masters](http://lockviastudios.itch.io/prankmasters) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3a8b7e4ba9708a6fd39b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
https://redsplatgames.itch.io/eron is affected too

**Comment by fasterthanlime** [comment]
The app is now able to install demos (since 19.0.0)
