### ISSUE TITLE
[win32] Issue for v0.13.0

### ISSUE THREAD

**Issue by nickfourtimes** [itchio/itch#387]
Hi, I've noticed that often enough I get what seems to be the internal placeholder variable-names for items, such as "menu.help.help" and so on, as shown in the attached photo. This has been happening for the past 4-5 versions of the app.

![bug](https://cloud.githubusercontent.com/assets/215674/12372996/65fa7454-bc38-11e5-85a5-0f29b6ec60b3.jpg)

**Comment by fasterthanlime** [comment]
@newton64 so it only happens some of the time, not on all startups of the app ?

**Comment by nickfourtimes** [comment]
Yeah, usually it's just a matter of closing and re-opening the app once or twice, and the text then renders properly.

**Comment by fasterthanlime** [comment]
I'm starting to suspect a race condition between i18n-store and the frontend, I'll keep investigating before 0.13.1

**Comment by nickfourtimes** [comment]
Awesome, thanks!

**Comment by fasterthanlime** [comment]
@newton64 Alright, I can reproduce at home, that'll be easy!
