### ISSUE TITLE
[win32] game Dissonance: An Interactive Novelette broken for v0.12.4

### ISSUE THREAD

**Issue by philroyer** [itchio/itch#389]
:rotating_light: Game [Dissonance: An Interactive Novelette](http://littletinman.itch.io/dissonance) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/ed0f30c8310834bbce85).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
@littletinman hey, can you upgrade to v0.13.0 and reopen if that's still an issue?

(I changed the way files are copied/wiped between those two releases)
