### ISSUE TITLE
[linux] game Anubis And The Buried Bone DEMO broken for v0.11.3

### ISSUE THREAD

**Issue by smeir** [itchio/itch#390]
:rotating_light: Game [Anubis And The Buried Bone DEMO](http://harmarist.itch.io/anubis) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2a958c9c8b248ee72cbc).

:running: I think its a libgdx game.

**Comment by fasterthanlime** [comment]
Closing in favor of #134
