### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by ghost** [itchio/itch#395]
I have downloaded the itch application, and upon an attempt to install, I'm hit with the error below (in the image).

Running: Windows 10 Pro 64 bit
![image](https://cloud.githubusercontent.com/assets/5943031/12375611/eb8965c4-bc8f-11e5-9efe-c4d0388ef670.png)

**Comment by fasterthanlime** [comment]
Closing in favor of #214

**Comment by fasterthanlime** [comment]
Actually not a duplicate, reopening.

**Comment by ghost** [comment]
It looks as if my network failed when downloading (file is 15,526KB). I'll redownload, and if the issue persists, then I will reopen this.

**Comment by fasterthanlime** [comment]
> file is 15,526KB

Oh right, that's too small, windows setups are around 45mb
