### ISSUE TITLE
Application name is "The best way to play itch.io games" - it would make more sense to be itch.io or itch

### ISSUE THREAD

**Issue by adam-binks** [itchio/itch#396]
For example, if you right click or hover over the app in your taskbar it shows up like this:

![Image](http://i.imgur.com/Ciog2wq.png)

Seems a bit wonky to me.

**Comment by fasterthanlime** [comment]
@jellyberg2 which version are you running? on Win8.1, when I right click on itch I get "itch"

![win7-v0 13 0](https://cloud.githubusercontent.com/assets/7998310/12378091/bd7682c6-bd33-11e5-9d68-115ab927f184.png)

**Comment by fasterthanlime** [comment]
The only place there's "The best way to play itch.io games" in the Windows package is for the `description` field of https://github.com/atom/grunt-electron-installer - `title` is set to "itch" - cf. [our Gruntfile](https://github.com/itchio/itch/blob/master/Gruntfile.js)

I guess we could try setting the description to "itch" too :/

**Comment by adam-binks** [comment]
I just updated to the latest version (0.13.1) and it looks like the thing is persisting. Sorry!

**Comment by fasterthanlime** [comment]
@jellyberg2 What happens if you uninstall and reinstall? (Your user settings should persist)

**Comment by fasterthanlime** [comment]
@jellyberg2 Alright so I just spent 6 hours installing Windows 10 I can confirm that on a fresh itch install, the name is itch

![name-is-itch](https://cloud.githubusercontent.com/assets/7998310/12379853/5c1144fa-bd63-11e5-8834-dbe9471fa738.png)

**Comment by jellyberg2** [comment]
Woah thanks man, sorry the inconvenience - I've been away from my desktop since this morning.

**Comment by fasterthanlime** [comment]
Haha, no problem, I wanted to upgrade for a while anyway :) I'm just happy to know it's not an issue with more recent versions, pity there's no way to change it for us when users upgrade :(
