### ISSUE TITLE
support .unitypackage files 

### ISSUE THREAD

**Issue by selfsame** [itchio/itch#397]
itch.io app is sniffing the tar+gz compression in .unitypackage files and auto uncompressing (found issue on windows 7)

**Comment by fasterthanlime** [comment]
> itch.io app is sniffing the tar+gz compression in .unitypackage files and auto uncompressing (found issue on windows 7)

As in, when you download an asset pack, itch just unpacked it instead of giving you a usable .unitypackage file?

**Comment by selfsame** [comment]
yes, also adding a `.itch` directory inside the unitypackage

**Comment by fasterthanlime** [comment]
Doing that now

**Comment by fasterthanlime** [comment]
(Was a duplicate of #453)
