### ISSUE TITLE
Sniff & exclude flixel.exe

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#399]
(Or at least give it a slightly lower score)

**Comment by initials** [comment]
I would hate to have code in the itch app specific to my games. What about choosing a name like "run_itch.bat" that is highly scored, and everyone that wants to run their game from a bat file chooses the same file name knowing that it will be highly scored?

**Comment by fasterthanlime** [comment]
You're hardly the only one who uses flixel :) I'll figure out a smart way to do it.

What's happening with your games, from what I can see in the screenshot, is that there are two top-level .exe files: Flixel.exe, and YourGame.exe - and Flixel is the bigger one, so it gets picked.

If Flixel.exe was in a subfolder, then itch would have no problem launching it (and it would be less confusing to users who manually download & extract from itch.io, too!).

**Comment by fasterthanlime** [comment]
Even though @initials updated all games with a manifest, this is still nice to have :) I tested with a version of SLF2 without .itch.toml (as a private page).
