### ISSUE TITLE
[win32] game Vulture for NetHack Community Edition broken for v0.13.2

### ISSUE THREAD

**Issue by clivecrous** [itchio/itch#404]
:rotating_light: game [Vulture for NetHack Community Edition](http://darkartsstudios.itch.io/vulture-for-nethack-community-edition) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3c98912213bdd1c05d9d).

:running: Installer doesn't launch ; game doesn't start "No executable found"

**Comment by fasterthanlime** [comment]
Hey @clivecrous! :star2: 

itch is attempting to do a silent install, since Vulture is using InnoSetup - however, it seems the exits with code 5 (which according to the [inno docs](http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline) means `The user clicked Cancel during the actual installation process, or chose Abort at an Abort-Retry-Ignore box.` - a bit silly since in silent mode there are no dialog boxes).

Would you consider shipping a portable version of the game (as a `.zip` or `.7z` archive) or making sure your InnoSetup installer works in silent mode? The command itch runs is (as of v0.13.2):

``` sh
your_installer.exe /VERYSILENT /SUPPRESSMSGBOXES /NOCANCEL /NORESTART /LOG=C:\test\log.txt /DIR=C:\test\target_directory
```

(See also [inno.js](https://github.com/itchio/itch/blob/master/appsrc/tasks/install/inno.js) if you prefer reading code than explanations)

I haven't seen an InnoSetup installer fail that so far, but maybe your installer has additional steps that require user input?

Here's our general guide, in case you haven't seen it yet: http://itch.io/t/11920/how-to-get-your-game-running-in-the-itch-app

**Comment by clivecrous** [comment]
Hmm, there are component selections during installation.

I'll think about how to tackle this.

Thanks for the info

**Comment by clivecrous** [comment]
I ran the command, as you provided as an example, of what runs as of v0.13.2 and it installed perfectly on my machine without an error when run manually from the command-line.

After some more investigation it appears itch is (might be) corrupting the file during download.

Relevant snippet from inno log:

2016-01-20 19:12:09.645   Source file corrupted: lzmadecomp: Compressed data is corrupted (3)
2016-01-20 19:12:09.645   Defaulting to Abort for suppressed message box (Abort/Retry/Ignore):
                          C:\Users\Clive\AppData\Roaming\itch\users\40699\apps\8hQV6eoR5YUUD7qx\Variants\SlashEM\nhshare

```
                      An error occurred while trying to read the source file:
                      The source file is corrupted.

                      Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
```

**Comment by fasterthanlime** [comment]
Interesting. Have you tried comparing the SHA-1 sums of your original file & the one itch downloaded in `%APPDATA%/Roaming/itch/users/USER_ID/archives` ?

**Comment by fasterthanlime** [comment]
As far as network corruptions go, I'd suspect the upload side before the download side.

[butler](https://github.com/itchio/butler) checks for size & two checksums, so there's a pretty good chance that what's in `archives` is also what is on our cloud storage provider.

**Comment by clivecrous** [comment]
I'm uploading using dropbox, I just uploaded again and tried download again, same result.

Will check checksums now.

Installation directly from file within Dropbox path being used -- works perfectly and is my baseline.  Will hash sum download against it now.  Can't find a way to download an app I uploaded from within the browser so can't check non-app download against app download.

**Comment by clivecrous** [comment]
shasum's don't match, either dropbox upload is corrupting the file, or itch app download is corrupting the file.

original shasum:

```
35f902a25123598f91686800e4a13f2c162fcb8f *Install-Vulture-for-NetHack-itch.io-Community-Edition-2016-01-07.01.exe
```

itch app download shasum:

```
26fd56d7280a9fad23f8db45d3eb7601abbb80d4 *150045.exe
```

**Comment by fasterthanlime** [comment]
what about file sizes?

**Comment by clivecrous** [comment]
File sizes follow, they match ...

original:

```
-rwxr-xr-x 1 Clive 197609 187377677 Jan  8 05:52 Install-Vulture-for-NetHack-itch.io-Community-Edition-2016-01-07.01.exe*
```

itch.io downloaded:

```
-rwxr-xr-x 1 Clive 197609 187377677 Jan 20 20:04 150045.exe*
```

**Comment by clivecrous** [comment]
and `cmp` results, as well:

```
$ cmp Install-Vulture-for-NetHack-itch.io-Community-Edition-2016-01-07.01.exe ~/AppData/Roaming/itch/users/40699/archives/150045.exe
Install-Vulture-for-NetHack-itch.io-Community-Edition-2016-01-07.01.exe     /c/Users/Clive/AppData/Roaming/itch/users/40699/archives/150045.exe differ      : byte 50532168, line 198037
```

**Comment by fasterthanlime** [comment]
I also have `26fd56d7280a9fad23f8db45d3eb7601abbb80d4` when downloading here.

Can you try uploading directly, without using dropbox?

**Comment by fasterthanlime** [comment]
@clivecrous As far as I can tell it sounds like a backend issue so I've opened https://github.com/itchio/itch.io/issues/333 to give @leafo a chance to track it

**Comment by clivecrous** [comment]
I can try ... :/ it'll be a while before I can verify that for you unfortunately. I'm in Cape Town (South Africa) and I have very very slow upload speeds // thus dropbox, but I'll fire it up so long.

**Comment by fasterthanlime** [comment]
@clivecrous Can you send me a dropbox share link to amos@itch.io ? I want to make sure of what's actually on the Dropbox servers (maybe the corruption is actually on their side?)

**Comment by clivecrous** [comment]
@fasterthanlime : It's uploading on my end (directly) in the background, and I've sent you a link.

**Comment by fasterthanlime** [comment]
@clivecrous I'll check the link tomorrow, thanks!

**Comment by clivecrous** [comment]
Possibly redundant test (on my side):

I too downloaded from the dropbox link I sent you, `shasum` success, and installed correctly without issue. So Dropbox itself, or that file on Dropbox, is not an issue.

**Comment by clivecrous** [comment]
I can confirm that a manual upload (not using dropbox) appears to have worked. Not sure how to add multiple executables as alternate launch options (since it's actually 3 games in one that ship), but that's completely unrelated to this issue.

It's definitely the Dropbox cycle then.

**Comment by fasterthanlime** [comment]
Since it wasn't an itch issue per se, closing in favor of https://github.com/itchio/itch.io/issues/333
