### ISSUE TITLE
Can't run Raining Blobs on Linux

### ISSUE THREAD

**Issue by jhasse** [itchio/itch#405]
When starting Raining Blobs on Linux via the app, nothing happens. When I open the game folder though and execute `./RainingBlobs` it works. When executing `./RainingBlobs.sh` in the game folder I'm getting an exception. Maybe the app is trying to launch the wrong file?

**Comment by fasterthanlime** [comment]
.sh files are prioritized by itch, so it's up to the game developer to fix it.

Can you paste a log of what running the `./RainingBlobs.sh` file does? You can open the debug log by alt-clicking the game's thumbnail — posting it to https://gist.github.com/ and posting the link here would be helpful.

**Comment by jhasse** [comment]
> .sh files are prioritized by itch, so it's up to the game developer to fix it.

Good to know! The developer already answered: The .sh file is obsolete :)

http://itch.io/post/11898

**Comment by fasterthanlime** [comment]
Great, thanks for the report & speedy resolution! :stars:
