### ISSUE TITLE
open: no such file in util/extract

### ISSUE THREAD

**Issue by Cheeseness** [itchio/itch#406]
After upgrading to 0.13.1 (and 0.13.2) from 0.9.x, I've found that I can't install several of my games (Above The Waves, Voices of the Past, Super Happy Fun Sun and Robin's Rescue).

Looking at the failed [install logs](https://gist.github.com/Cheeseness/3df9799312cc65ca1f41), it seems like it's failing to find some files in the downloaded archive, but if I open up the archive from any of the -stage folders for these games, everything seems to be in there.

I use the same packaging structure for all of my games (tar.gz archive with binary and launcher script in the game's root folder), and Voices of the Past uses the same engine as Winter's Wake and Memories of Myst (which both install fine).

I'd be happy to update my games to get them behaving, but I can't work out what's different between those that do install and those that don't.

**Comment by fasterthanlime** [comment]
Can you give me the itch.io link to Voices of the Past?

**Comment by Cheeseness** [comment]
Sure thing. Probably should've included that to begin with, sorry.

http://cheeseness.itch.io/voices-of-the-past

IIRC, the Voices and Winter's Wake packaging was done by the same version of the same makefile.

**Comment by fasterthanlime** [comment]
(The way games are installed/setup has changed between 0.9 and 0.13, btw, among other to deal with #340 and stuff like #355, so there's a good chance that it is a legitimate bug in itch)

**Comment by fasterthanlime** [comment]
I see the issue - the .tar archives I tested had directory entries before they had file entries, so `butler untar` was working well, but yours seems to straight to a file entry, so it doesn't go over as well.

The good news is that I can ship a new version of butler without having to ship a new version of itch. Give me a few minutes.

**Comment by Cheeseness** [comment]
Ah-ha! Thank you <3

**Comment by fasterthanlime** [comment]
(For reference, if someone digs up this issue in a bit, we have our own untar command because `tar(1)` isn't shipped with Windows and golang has good untar support)

**Comment by fasterthanlime** [comment]
@Cheeseness butler 0.10.2 is out, which fixes the issue - rebooting your itch client (not just closing the window) should fix it!

Relevant commit: https://github.com/itchio/butler/commit/2c2be8f04b5f55dd2c7ee47913c94255b293bf09

**Comment by Cheeseness** [comment]
Confirmed as fixed at this end. Thanks again!

**Comment by fasterthanlime** [comment]
Thanks for reporting! :stars:
