### ISSUE TITLE
[linux] Kareokeyboard Doesn't Install

### ISSUE THREAD

**Issue by Cheeseness** [itchio/itch#407]
[Kareokeyboard](http://terminajones.itch.io/karaokeyboard-2014) doesn't seem to install happily in 0.13.2 (I'm told it did in 0.9.4 though).

The [install log](https://gist.github.com/Cheeseness/f3640c03624cc61500d2) shows an UnhandledFormat error.

**Comment by fasterthanlime** [comment]
Installs & runs fine on 18.3.0 :)

![karaokeyboard](https://cloud.githubusercontent.com/assets/7998310/16924972/3c54d8d0-4d22-11e6-8834-fee4cbdf0e54.png)
