### ISSUE TITLE
"Other" classification can be downloaded & opened (as expected)

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#409]
In the Itch.io app:

![whyyyyy](https://cloud.githubusercontent.com/assets/15093567/12492949/aae41e14-c037-11e5-9931-52263769c515.png)

Both of these games are identical (except of course for what they actually are) except one is listed as "Other" and the other as "Game". The "Other" can be installed, but the "Game" can't. Why?

**Comment by fasterthanlime** [comment]
I'm guessing the other one _also_ has a native Windows version available?

**Comment by TangentFoxy** [comment]
@fasterthanlime Both are strictly web embeds on Itch.io

Edit: Links to the ["Installable"](http://guard13007.itch.io/psychology) and [not installable](http://guard13007.itch.io/300-words-to-save-your-ship) games if that helps any.

**Comment by fasterthanlime** [comment]
@Guard13007 ah, yes, of course, "Other" classifications are considered non-launchables and thus can be downloaded & opened via the app even though their uploads aren't tagged with any platform. (My bad, I didn't read your original report closely enough!)

Launchable items should be classified under "Game" or "Tool" (even if you don't subscribe to what the general view of what a "game" should be) - you can use a custom verb in the "Edit game" page.

**Comment by TangentFoxy** [comment]
Ah, thank you! I'll go fix that.

**Comment by TangentFoxy** [comment]
@fasterthanlime Suddenly it seems the app has detected Psychology (the one set to Other) as launchable, instead of openable. When I discovered that, I set 300 Words to Save Your Ship as Other as well, and restarted the app and downloaded it, and then restarted several times and opened it a few times, trying to get it to recognize it as launchable too..but it seems it won't:

![untitled](https://cloud.githubusercontent.com/assets/15093567/12511467/5fc66e8e-c0c6-11e5-9709-1c6b8505a51a.png)

Any idea why this is happening?

(On a sidenote: ~~It seems the app isn't saving itself in my start menu when installed? I have just been using the installer to restart it since I can't find how I'm supposed to be able to launch it.~~ It took me launching the installer 3 times to install a star menu shortcut.)

**Comment by fasterthanlime** [comment]
> It took me launching the installer 3 times to install a star menu shortcut

If you can find a reliable way to reproduce this, please tell me so!

> Suddenly other

At the time of this writing:

![its-a-game](https://cloud.githubusercontent.com/assets/7998310/12511731/e3490922-c113-11e5-9458-39f20b000894.png)

**Comment by TangentFoxy** [comment]
@fasterthanlime I will try to reproduce that error if I can, as for my own fuckups: I should not have been trying to work this out at 4 am. o.o

**Comment by fasterthanlime** [comment]
@Guard13007 thanks! g'night :)

**Comment by TangentFoxy** [comment]
@fasterthanlime No no no, good morning! XD I had to get up ridiculously early. I'm on plenty of coffee now though.
