### ISSUE TITLE
Set up APT repository

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#41]
Basically, use [fpm](https://github.com/jordansissel/fpm)

**Comment by fasterthanlime** [comment]
fpm won't allow us to have a PPA but we can use this instead:
- http://xn.pinkhamster.net/blog/tech/host-a-debian-repository-on-s3.html

**Comment by fasterthanlime** [comment]
We have bintray's blessing: https://twitter.com/bintray/status/676279768837447681 — sounds like a good way to get off the ground quickly

**Comment by mdeguzis** [comment]
It's quite easy to do this with reprepro (I use that for SteamOS-Tools). I play on at least doing a rebuild with any corrections for dependencies later tonight. Even being new to packaging at the time, it was a few steps to start up.

**Comment by fasterthanlime** [comment]
> It's quite easy to do this with reprepro

that was my original plan as well. I might still do that actually. will see!

**Comment by mdeguzis** [comment]
Ok, sounds good just a suggestion. Going to look at your build process tonight and see if I can start up a traditional "debianized" debian/ folder set. I'll just start by unpacking the deb and checking out your .yml build process and what not. Thanks for the open source work!

**Comment by fasterthanlime** [comment]
Just set up the dns for http://apt.itch.ovh — will host that on GCS, hoping to set it up later this evening, if I can get the other issues I care about fixed quickly

**Comment by fasterthanlime** [comment]
> checking out your .yml build process

I'm assuming you mean https://github.com/itchio/ci.itch.ovh/blob/master/src/jobs/itch.yml ?

You might also be interested in looking at actual output/commands run on the CI: https://ci.itch.ovh/job/itch/JENKINS_ARCH=amd64,JENKINS_XOS=linux/ — although keep in mind only deploy builds run the packaging part of the script — to find one, start [with itch <- on tag](https://ci.itch.ovh/view/Triggers/job/itch%20%E2%86%90%20on%20tag/) and find your way downstream :)

**Comment by fasterthanlime** [comment]
I actually set that up for 0.11.3 https://github.com/itchio/itch/releases/tag/v0.11.3
