### ISSUE TITLE
[linux] game Pockette Rox broken for v0.12.3

### ISSUE THREAD

**Issue by Riokei** [itchio/itch#416]
:rotating_light: Game [Pockette Rox](http://solarlune.itch.io/pockette-rox) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/559ebbda3e232fc3d790).

:running: Also seems to effect Syrup and the Ultimate Sweet.

**Comment by fasterthanlime** [comment]
Looks like butler installation went wrong for you (should be addressed by #137 eventually).

Can you try restarting the app? (Using Ctrl-Q / File menu -> quit, not just closing the window)

**Comment by Riokei** [comment]
Just tried that and got the same issue.

**Comment by fasterthanlime** [comment]
@Riokei Can you post the output of `ls -lhA ~/.config/itch/bin` ?

Here's what I have:

```
$ ls -lhA ~/.config/itch/bin
total 18M
-rwxr-xr-x 1 amos amos  15M Jan 20 22:24 butler
-rwxrwxr-x 1 amos amos 2.9M Jan 20 22:40 butler.7z
```

**Comment by Riokei** [comment]
I get:

```
     ls -lhA ~/.config/itch/bin
    total 0
    -rwxrwxr-x 1 kage kage 0 Jan 22 13:01 butler.7z
```

**Comment by fasterthanlime** [comment]
@Riokei can you try deleting this file & relaunching the app?

**Comment by Riokei** [comment]
Right back at square one, deleted, relaunched, can't install anything and re-running `ls -lhA ~/.config/itch/bin` gives me the same thing as earlier.

**Comment by fasterthanlime** [comment]
It looks like it's plain just not downloading butler :disappointed: 

Can you post the output of:

``` bash
curl https://dl.itch.ovh/butler/linux-amd64/v0.10.2/butler.7z -o /dev/null
```

Also - v0.12.3 is outdated, v0.13.2 is the latest version, you can stay up-to-date using the APT repository: https://github.com/itchio/itch.io/issues/300

**Comment by Riokei** [comment]
I got:

```
curl https://dl.itch.ovh/butler/linux-amd64/v0.10.2/butler.7z -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                             Dload  Upload   Total   Spent    Left  Speed
100 2912k  100 2912k    0     0  2465k      0  0:00:01  0:00:01 --:--:-- 2466k
```

Ah I'll try to update it to the latest version.

**Comment by Riokei** [comment]
I installed the newest release and it seems to be working now! I can install games now. Thanks for the help!

**Comment by fasterthanlime** [comment]
@Riokei awesome, thanks for your patience! :stars:
