### ISSUE TITLE
Don't show "Check for update" on Linux

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#417]
Since there's no Squirrel.Linux.

Maybe show repo info instead?

**Comment by josefnpat** [comment]
So I find that the itch app `0.14.0` does not have any way (that I see) to update a game. I am assuming that from #662 it should be possible but I don't see.

Can you elaborate on this bug?

I don't know if I should open a new ticket, or if it's this issue.

**Comment by fasterthanlime** [comment]
@josefnpat this issue is for the self-updater (app updating itself). The self-updater works on OSX & Mac. On Linux, it (now) notifies you when there's a new version available, but doesn't download it for you.

So, actually, this issue should not be open! As far as game updates go: 0.14.0 is quite old already, the latest is 17.6.6 at the moment, I recommend upgrading asap.

(If I recall correctly, the behavior in 0.14.0 is to check for game updates on startup, which isn't practical if you leave the client running for a long time).

Feel free to open an issue if you have any further questions!

**Comment by josefnpat** [comment]
Thank you very much - I will update now!
