### ISSUE TITLE
Support gameboy ROMs (.gb) out of the box?

### ISSUE THREAD

**Issue by patrickpistor** [itchio/itch#420]
:rotating_light: Game [Happy Hedgehog (Beta)](http://patchworkgames.itch.io/happyhedgehog) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b1a50d2ed4780e34a89a).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
That's a gameboy rom tagged with linux/windows/mac so yeah it won't run.

Supporting gameboy ROMs would be fun though.

**Comment by fasterthanlime** [comment]
v25 is out, and when you install a gameboy ROM with it, well, it doesn't emulate a Gameboy, but at least it lets you open the folder so you can open it with an emulator you already have installed!

You can download itch v25 here: https://itch.io/app

**Comment by patrickpistor** [comment]
Yo I don't even remember opening this, but thanks for the memories haha! (Looks like it was auto generated)
