### ISSUE TITLE
[darwin] game YOU are the HERO: Custom games broken for v0.13.2

### ISSUE THREAD

**Issue by EleoraFranklin** [itchio/itch#421]
:rotating_light: game [YOU are the HERO: Custom games](http://trumroom.itch.io/youarethehero) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/134c5e0aee99805fa16c).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
> [Fri, 22 Jan 2016 22:22:59 GMT] [util/extract] archive contains 0 files, 0 bytes total

Looks like the .zip of this game is invalid. Extracting it with OSX's archive utility errors out. The developer of the game should reupload a valid .zip file.
