### ISSUE TITLE
[darwin] game YOU are the HERO: Custom games broken for v0.13.2

### ISSUE THREAD

**Issue by EleoraFranklin** [itchio/itch#422]
:rotating_light: game [YOU are the HERO: Custom games](http://trumroom.itch.io/youarethehero) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f69e174a129819de0cfc).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Duplicate of #421
