### ISSUE TITLE
Download fails when both zip and rar

### ISSUE THREAD

**Issue by erbridge** [itchio/itch#424]
The following game has added `.zip` files after I pointed it out to them, but kept their `.rar`s. I would have expected the app to just download the appropriate `.zip`.

http://btseven.itch.io/deepflareexplorer

**Comment by fasterthanlime** [comment]
I believe this issue is resolved now: the app now lets you pick which file to download (excluding .rars), and it there's only .rar, it shows a dialog explaining why it can't install it.

also, #795 will just straight up support rars, so this will be made even more irrelevant.
