### ISSUE TITLE
[win32] game Super Lefty Garden Fighty broken for v0.13.2

### ISSUE THREAD

**Issue by AzeyDutch** [itchio/itch#426]
:rotating_light: game [Super Lefty Garden Fighty](http://hexagore.itch.io/super-lefty-garden-fighty) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/47827559d52d3fe3d0ad).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
No wmic in path, no 7za.. could you try restarting the app?

Which version of Windows are you running?

**Comment by AzeyDutch** [comment]
i am running windows 10

**Comment by AzeyDutch** [comment]
i have the error almost with every game i dont know why

**Comment by fasterthanlime** [comment]
> i have the error almost with every game i dont know why

Normally, the app downloads a copy of 7-zip when first starting up. Maybe it failed for you, and that's why you're seeing this error. If you try quitting the itch.io app (with File -> quit) & starting it up again, it should work better.

**Comment by fasterthanlime** [comment]
@AzeyDutch could you re-open the issue if it's still happening with the latest version of the app? thanks! (you can get the latest from https://itch.io/app)
