### ISSUE TITLE
[win32] game 2 broken for v0.13.2

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#428]
:rotating_light: game [2](http://hubol.itch.io/2) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/aa938123ec3d712c9fcc).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Here's what's happening:
- Game has external uploads only
- External uploads point to naked .exe
- itch app can't tell file extension of external uploads
- itch app copies 'XXXXXX' file to install dir
- itch app doesn't find any .exe in install dir

Any of these would fix it:
- uploading the .exe directly to itch.io
- having the external upload point to a .zip or .7z archive instead

**Comment by fasterthanlime** [comment]
(If someone would be so kind as to point hubol to this thread - note that uploading frequent new versions of games is made very easy by https://docs.itch.ovh/butler/master/ - read the docs to find out more.)
