### ISSUE TITLE
Cannot stop selling game without locking out customers

### ISSUE THREAD

**Issue by Bradshaw** [itchio/itch#430]
I no longer want to sell one of my games (prevent purchases), but there's no option that allows my previous customers to be able to access their downloads.

My interim solution has been to remove all information about the game and list it at 1000€, which _should_ stop more people buying it, but it's rather inelegant

**Comment by fasterthanlime** [comment]
For now the best option is "Public restricted" which is badly named & badly described :(

The net result will be that no new people will be able to purchase the game, but download keys (existing purchases) will still work.

**Comment by fasterthanlime** [comment]
Also, this is technically a https://github.com/itchio/itch.io issue :) And you re-enabled purchases for LAZR anyway. Woo!
