### ISSUE TITLE
[linux] tool Superpowers broken for v0.11.3

### ISSUE THREAD

**Issue by MilanPingel** [itchio/itch#431]
:rotating_light: Game [Superpowers](http://sparklinlabs.itch.io/superpowers) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1d47f580e4ee0dfe48ed).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
hey milan :wave: !

Looks like you're running an old version of the app. Can you upgrade & re-open if it still happens with the latest version? Thanks! https://github.com/itchio/itch.io/issues/300

**Comment by MilanPingel** [comment]
You solved the mystery  /shamefulgazetowardsfloor

Amos Wenger notifications@github.com schrieb am Fr., 29. Jan. 2016 3:31
nachm.:
