### ISSUE TITLE
[linux] game Red Rogue broken for v0.13.2

### ISSUE THREAD

**Issue by mstfacmly** [itchio/itch#432]
:rotating_light: I seem to be unable to install [Red Rogue](http://st33d.itch.io/red-rogue).

:book: Here's the complete [debug log](https://gist.github.com/1d69f3608234a9e496b7).

:running: Currently running UbuntuGNOME 15.10, 64-bits.

**Comment by fasterthanlime** [comment]
Closing in favor of #226
