### ISSUE TITLE
[linux] games written in Love2d broken for v0.13.2

### ISSUE THREAD

**Issue by TimseineLPs** [itchio/itch#434]
:rotating_light: game [Disposable](https://martincohen.itch.io/disposable) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9e029546ab44b68a6933).

:rotating_light: game [Sagittarius](https://gprosser.itch.io/sagittarius) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2953070eafb2aebce279).

:running: For Linux a Love2d package is downloaded instead of an executable. Itch will therefore not find any executable.

I tried manually installing Love2d and creating a script that will be executed by Itch, but the games crashed immediately. I think this is because there are libraries missing.

**Suggestion:**
I don't know how one would fix this the 'right' way, but I would like an option to install a game to run through wine. This solves the executable issue and also makes more games run on Linu

**Comment by fasterthanlime** [comment]
Closing in favor of #135 and #433
