### ISSUE TITLE
[win32] game Terry the Cave Explorer broken for v0.13.2

### ISSUE THREAD

**Issue by JoseRivas1998** [itchio/itch#436]
:rotating_light: game [Terry the Cave Explorer](https://joserivas1998.itch.io/terry-the-cave-explorer) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/111869633f16fc18a001).

I made this game in Java with libGDX

**Comment by fasterthanlime** [comment]
Closing in favor of #243
