### ISSUE TITLE
[win32] tool Verbal broken for v0.13.2

### ISSUE THREAD

**Issue by beppe9000** [itchio/itch#439]
:rotating_light: tool [Verbal](https://jarnik.itch.io/verbal) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5c62694178abf4c5ae85).

:running: Cool idea opening issues automatically!

**Comment by fasterthanlime** [comment]
Looks like they're just distributing an .swf file, but tagging as Windows/Linux/Mac on itch.io means there's an actual executable to run. The app can't run .swf files.

The developers should start distributing an .exe on Windows, etc.

**Comment by beppe9000** [comment]
since this application is web based you could open another windo with some basic swf embedding. This could be done for any other game/program requiring a web browser to operate. Or just pass the swf file to a local copy (downloaded by the store) of the SWF projector.

**Comment by fasterthanlime** [comment]
Adding swf support to the app (one way or the other) is something we could consider, however:
- Flash isn't as popular as it once was (and our resources are limited)
- It is a potential security risk (we'd have to make sure the Flash version we distribute is up-to-date and address security issues in a timely manner).

Support for web games is tracked in #47 — HTML5 games are already in. Thanks for your feedback!
