### ISSUE TITLE
[win32] game Lumberjack Jacques and the Ritual of Doom broken for v0.13.2

### ISSUE THREAD

**Issue by achiardi** [itchio/itch#440]
:rotating_light: game [Lumberjack Jacques and the Ritual of Doom](https://sparklinlabs.itch.io/lumberjack) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d42486322992bf278a32).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Might not have worked back in v0.13.2 but v15.0.0 has web game support, so it works beautifully now.

Please upgrade to the latest app version & re-open if still a problem!
