### ISSUE TITLE
[win32] tool Duality broken for v0.13.2

### ISSUE THREAD

**Issue by JoseRivas1998** [itchio/itch#441]
:rotating_light: tool [Duality](https://adamslair.itch.io/duality) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/4a588246d400d9a3a3d8).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like the download link is actually an html page that tries to download in your browser. That's not compatible with the app. The developer of Duality should just directly upload on itch.io instead.

Automating this is easy now, with butler: https://docs.itch.ovh/

**Comment by ilexp** [comment]
I've changed the download link to use a direct URL instead. Should be fixed now.
