### ISSUE TITLE
Log in is failed in v0.13.2

### ISSUE THREAD

**Issue by Emily135** [itchio/itch#442]
![itch](https://cloud.githubusercontent.com/assets/17060507/12808517/c314ac5a-cb5a-11e5-9b74-225573ef19ab.PNG)

This warning message is came up when I tried to log on app v0.13.2
(OS is Windows 7, 64 bit.)
I couldn't find any reported issue connected with 'local issuer certificate' yet.

**Comment by fasterthanlime** [comment]
@Emily135 are you still experiencing the issue with the latest version of the app? (you can get it from https://itch.io/app)
