### ISSUE TITLE
[win32] game Glitch (Alpha 5 b13112015) broken for v0.13.2

### ISSUE THREAD

**Issue by DukeBammerfire** [itchio/itch#443]
:rotating_light: game [Glitch (Alpha 5 b13112015)](https://superbuff-games.itch.io/glitch) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3c45789bf74b4b131174).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like the game was unpublished.
