### ISSUE TITLE
[linux] game Tanks of Freedom broken for v0.13.1

### ISSUE THREAD

**Issue by only1thor** [itchio/itch#445]
:rotating_light: game [Tanks of Freedom](https://w84death.itch.io/tanks-of-freedom) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6d872c405faa24094def).

:running: Any additional details can go here!

Just clicking install did not work. idk where it's stored on disk or i could check if it's chmod'ed to include execute. when i downloaded it from the browser i just chmod'ed and ran it via ./[Bin_name.bin] and that worked like a charm. 
(I'm runnig Antergos(Arch linux), and installed itch via yaourt (AUR).)

**Comment by fasterthanlime** [comment]
Works great in the current dev version - should work fine in the next stable release.
