### ISSUE TITLE
Download buttons unresponsive, download started twice

### ISSUE THREAD

**Issue by leafo** [itchio/itch#446]
The download button was being unresponsive, clicking it did nothing. So I clicked it a bunch and eventually when downloads did start it started downloading the same game twice

![](http://leafo.net/shotsnb/2016-02-06_01-23-58.png)

**Comment by fasterthanlime** [comment]
That's quite an old report but - starting from v0.14.x, the app has logic not to start downloads twice for a given game, so that should never happen anymore :)
