### ISSUE TITLE
Launch app from website?

### ISSUE THREAD

**Issue by kg** [itchio/itch#448]
If I'm looking at a page on the itch website and I want to download the game in the itch app, there's no obvious way to do it.

For example, I'm looking at http://foxboard.itch.io/the-sacrifice and I want to install the game using the itch app.

The download button just downloads a zip file. The itch app doesn't have any way to search for games by name or URL, and I can't paste the URL in anywhere. The only way I've found to get the game into the itch app is to add the game to a collection, at which point it's available in 'my collections'. But if you don't have any collections you have to create one first and then add the game to it, which is kinda nonobvious.

From the app side you could solve this by adding a simple way to consume itch URLs - for example, if I copy a game page URL into the clipboard while the app is running, maybe it automatically adds it to a list in the UI so I can download it?

Or implement a URL handler so that something like `itch://foxboard/the-sacrifice` would start downloading the game in question in the app, and then get the website tweaked a little bit so it can call out to the URL handler if you have the app installed.

**Comment by fasterthanlime** [comment]
> Or implement a URL handler so that something like itch://foxboard/the-sacrifice would start downloading the game in question in the app, and then get the website tweaked a little bit so it can call out to the URL handler if you have the app installed.

Yup, we've already done that. Haven't added it to the website yet before the app matures a bit to keep the number of issues open manageable :)

**Comment by aaronfranke** [comment]
In the meantime, before it's an official part of the site, you can use fasterthanlime's Tampermonkey script https://fasterthanlime.itch.io/open-in-app-button-for-itchio-userscript

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/947
