### ISSUE TITLE
[win32] game Lightyear. broken for v0.13.2

### ISSUE THREAD

**Issue by Kaspol** [itchio/itch#449]
:rotating_light: game [Lightyear.](https://chromebookbob.itch.io/lightyear) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/905298e40969eba5eb45).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It's probably picking up the 'HTML' version rather than the Windows version. Having the developer untag 'Windows' for the HTML version or just swap the order would fix it.
