### ISSUE TITLE
Unknown installer type that requires privilege elevation (Raziel)

### ISSUE THREAD

**Issue by Kaspol** [itchio/itch#450]
:rotating_light: game [Raziel](https://gamingpixie.itch.io/raziel-upgraded) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d323d48652240114068b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Not sure what's happening with this one - will have to try and reproduce it on my side. Reading the logs, it looks as if it's an installer type we don't support, but that doesn't tell us why trying to run it results in 'spawn UNKNOWN'.

**Comment by fasterthanlime** [comment]
Still a problem with v15.0.0. If someone has insight on which installer it is, I'm listening

**Comment by fasterthanlime** [comment]
It's a Clickteam installer, those have no silent switches and so we won't be able to support them :(
