### ISSUE TITLE
Support naked .jar files

### ISSUE THREAD

**Issue by PentaHelix** [itchio/itch#452]
:rotating_light: game [MoonBase](https://cairn4.itch.io/moonbase) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a9c87ff0919cd15858c4).

:running: I think that the .jar which is the game executable get's unpacked by itch and can obviously not run because of this

**Comment by fasterthanlime** [comment]
Ah, we'll have to make a special case for .jar files uploaded as-is, thanks for reporting :+1:
