### ISSUE TITLE
Treat .unitypackage files as asset packs, even when misclassified

### ISSUE THREAD

**Issue by beppe9000** [itchio/itch#453]
:rotating_light: tool [TOWN - Tiny prOcedural World geNerator](https://delca.itch.io/town) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2c7596fb949e86022241).

:running: There is no exe file in the directory, btw.

**Comment by fasterthanlime** [comment]
Yeah, it's actually an unity asset pack, so it can't be run on its own.

App is behaving as expected given that the page is set as a 'tool'. It should probably be set to 'asset pack' instead (even though it is, technically, a tool for Unity)

**Comment by fasterthanlime** [comment]
However, what we could do is detect .unitypackage files and treat them as assets.

**Comment by beppe9000** [comment]
Nice, looks like the right thing to do :) Maybe some visual cue could be added to highlight that the package has not an executable and so it needs special treatment because it is not standalone.

**Comment by fasterthanlime** [comment]
Asset packs are visually distinct in the app, they have an 'Open' button instead of a 'Launch' button. Still room for improvement, but it's a start.

![open](https://cloud.githubusercontent.com/assets/7998310/12957301/4cf9f468-d02c-11e5-88da-b442f4bf7f44.png)
