### ISSUE TITLE
Stuck on 'Installing...'

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#455]
Several people have reported games being stuck on 'Installing...'.

Potential culprits:
- Inconsistent state between browser and renderer side
- butler getting stuck when wiping out stage

To those experiencing a similar problem:
- do you see a `butler` or `butler.exe` in your process manager? If so, can you give me the arguments it was launched with?
- does clicking on the progress bar do anything?
- are you running antivirus software?

**Comment by ghost** [comment]
@fasterthanlime I checked my process manager and had three instances of `butler.exe` (presumably one for each game having this issue). I tried killing one of the processes and a progress bar changed from `Installing...` to `Installing... (100%)`. The butler process restarted on its own. I killed it a second time and the progress bar changed to a Launch button, which seems to launch my game with no issue.

So, it seems like everything works properly if I kill those processes a few times. Hopefully that information is helpful. Also, how do I check the arguments on the process?

**Comment by fasterthanlime** [comment]
@donkeyspaceman this page seems to have some info http://stackoverflow.com/questions/821837/how-to-get-the-command-line-args-passed-to-a-running-process-on-unix-linux-syste

**Comment by Dukmos** [comment]
@fasterthanlime `butler.exe` was launched wit `butler -j wipe E:\itch-io\archives\115014.zip-stage`. This folder exists. 
After killing it, it starts extracting the files but stopps at `Installing..(100%)`.
Again `butler.exe` is startet with `butler -j wipe E:\itch-io\archives\115014.zip-stage`. This folder only contains two empty Folders(`Audio` and `Music loops (30 files)`.
Tested on the Kenney Game Asset Pack https://kenney.itch.io/kenney-donation

**Comment by fasterthanlime** [comment]
@Dukmos @donkeyspaceman are you running an antivirus software (that might prevent file deletion) ?

**Comment by ghost** [comment]
@fasterthanlime No antivirus outside of whatever Windows 10 has built-in.

**Comment by Dukmos** [comment]
@fasterthanlime I have ESET Smart Security, but disabeling it dont help. When executing butler manualy it repeatst this Error
`{"message":"got E:\\itch-io\\archives\\115014.zip-stage, but not giving up","type":"log"}
{"message":"trying to wipe E:\\itch-io\\archives\\115014.zip-stage again","type":"log"}`

**Comment by fasterthanlime** [comment]
@Dukmos can you try running the exact same 'wipe' command with the butler executable I've attached to this comment?

It's a digitally signed executable, with the same certificate used for itch.io/app - you can verify it by doing a right click -> 'Properties' -> 'Digital signatures' tab. You should see one signature, by "Open Source Developer, Amos Wenger" - if the signature isn't there, don't run it.

Here's the SHA-1 hash of the butler.exe I'm uploading:

> ac0247e93af2aa37808a2182c59fe2f9dc332547 *butler.exe

I'm uploading it compressed by .zip, as the .exe is actually around ~15MB, but the .zip is only around ~4.2MB

Download here: [butler.zip](https://github.com/itchio/itch/files/142447/butler.zip)

**Comment by Dukmos** [comment]
@fasterthanlime now it works
`C:\Users\Dukmos\Desktop\tmp>butler -j wipe E:\itch-io\archives\115014.zip-stage
{"level":"debug","message":"rm -rf E:\\itch-io\\archives\\115014.zip-stage","type":"log"}
{"level":"info","message":"While removing: remove E:\\itch-io\\archives\\115014.zip-stage\\Audio\\Music loops (30 files): Zugriff verweigert","type":"log"}
{"level":"info","message":"Trying to brute-force permissions, who knows...","type":"log"}
{"level":"info","message":"Sleeping for a bit before we retry...","type":"log"}
{"level":"debug","message":"rm -rf E:\\itch-io\\archives\\115014.zip-stage","type":"log"}`

**Comment by fasterthanlime** [comment]
@Dukmos awesome! It'll be fixed in the next release of the app then.

**Comment by fasterthanlime** [comment]
Just wanted to mention that this issue was brought to my attention again on Twitter & I realized it has been a while! I was planning to release a public version earlier than that, but a rewrite got in the way.

I've been working most of the day on migrating the butler deploy pipeline to our new CI server, so that I can easily deploy the version of butler that worked for @Dukmos - it won't fix UI inconsistencies, but at least it own't actually get stuck trying to wipe files. I'll update when I do manage to deploy the new version.

**Comment by fasterthanlime** [comment]
butler v0.11.0 was released yesterday and should fix this issue for the most part. to upgrade butler, simply restart the app.
