### ISSUE TITLE
Not displaying properly on arch

### ISSUE THREAD

**Issue by ogbaba** [itchio/itch#458]
Hello, I installed itch via the AUR and the app displayed like that after I tried to login with my username and password (even after restarting or reinstalling it stays the same)

<a href="http://i.imgur.com/OJF1mOT.png">
  <img src="http://imgur.com/OJF1mOTl.png" />
</a>

Here is the console output : 
[console.txt](https://github.com/itchio/itch/files/130879/console.txt)

The version seems to be 0.13.1 and clicking the buttons in the bar doesn't seem to work :(

**Comment by fasterthanlime** [comment]
@baptistepouget can you run OpenGL apps successfully? (`glxgears` for example)

**Comment by fasterthanlime** [comment]
@baptistepouget also, try running with `DEVTOOLS=1 itch`, see if there's any interesting errors in the console

**Comment by ogbaba** [comment]
@fasterthanlime weird it says Inspected target disconnected and nothing special in the console

![screenshot_2016-02-15_16-24-27](https://cloud.githubusercontent.com/assets/13153084/13052713/477df29e-d3f8-11e5-9b30-34a8d4f1b1e0.png)

And glxgears runs fine :/

**Comment by fasterthanlime** [comment]
> Inspected target disconnected

Sounds like a renderer process crash. Which `electron` version do you have? (`electron --version`)

**Comment by ogbaba** [comment]
[baptiste@Arch-Baptiste ~]$ electron --version
v0.36.7

**Comment by fasterthanlime** [comment]
@baptistepouget could you try downgrading a few electron versions & see if you still have the same error ?

**Comment by ogbaba** [comment]
@fasterthanlime I downgraded to v0.30.3 and it still doesn't work :/ maybe it's not related to electron and it's a missing library or something

**Comment by fasterthanlime** [comment]
aw, v0.30.3 is a bit old, I was thinking more like an earlier v0.36.x, or a v0.35.x

**Comment by ogbaba** [comment]
Same bug on electron v0.35.2

**Comment by erbridge** [comment]
This happens for me too. It's a recent issue (within the last couple of weeks), since I have used the app in the past.

**Comment by fasterthanlime** [comment]
My other suspect (apart from electron/chromium renderer breaking) is #457 which I suspect only affects AUR

**Comment by s0r00t** [comment]
I'm also affected by this problem.
Does downgrading to a particular version of electron works?

**Comment by fasterthanlime** [comment]
> Does downgrading to a particular version of electron works?

It doesn't seem to.

I'm suspecting #457 because, from the screenshot, it looks like it might just not be using any of the CSS. Does 'running `grunt sass` wherever itch is installed by pacman' help?

**Comment by s0r00t** [comment]
Default install folder in the PKGBUILD is /opt/itch.
There's no local grunt install there; can't run `grunt sass`.

**Comment by fasterthanlime** [comment]
Does following the instructions to run a dev version of itch work? https://github.com/itchio/itch/blob/master/docs/developing.md

**Comment by s0r00t** [comment]
Downloaded a zip of the repo, ran `npm install`, and right when doing either `grunt sass` or `npm start` : 

```
Running "sass:dist" (sass) task
>> File to import not found or unreadable: main/common
>> Parent style sheet: /<REPO>/appsrc/style/main.scss
>>   Line 2  Column 1  appsrc/style/main.scss

```

**Comment by fasterthanlime** [comment]
@s0r00t that's really strange, could it be using a version of sass that doesn't support partials? (cf. http://sass-lang.com/guide, search for 'Partials') — `main/_common.scss` definitely exists: https://github.com/itchio/itch/blob/master/appsrc/style/main/_common.scss

**Comment by erbridge** [comment]
I've also tried running off master, and the app builds fine, but this issue is still present. It might also be worth mentioning that for me the UI seems to be unresponsive.

**Comment by s0r00t** [comment]
@fasterthanlime It searched for main/common, not main/_common. 
I'll retry building, this time using npm tools, and not packaged tools.

**Comment by s0r00t** [comment]
Alright, managed to build with node 5.6.0, electron-prebuilt 0.36.7 and latest version of dependencies.
Still glitches.

**Comment by fasterthanlime** [comment]
I managed to reproduce the problem in an ArchLinux VM, but it turns out it had an old version of electron.

I'm trying to install the latest `electron-prebuilt`, which keeps failing with EACCESS (even with sudo). This is going to be fun.

**Comment by s0r00t** [comment]
What are the permissions of /usr/bin and /usr/lib/node_modules ? Should be 755 for both.
EDIT : Just tested with latest electron-prebuilt (0.36.7), still glitched.

**Comment by fasterthanlime** [comment]
> What are the permissions of /usr/bin and /usr/lib/node_modules ? Should be 755 for both.

I eventually installed electron v0.36.7 locally, launched it via `nodes_modules/.bin/electron`, `process.versions` checks out in the Devtool js console, it looks like the renderer is crashing after login. Still investigating

**Comment by ogbaba** [comment]
The issue is still the same but now there is a segmentation fault after a few seconds :octopus: 

[log output](https://gist.github.com/fasterthanlime/c362be4988212e4992b8)

_edit fasterthanlime 2016-03-16: turned upload into gist_

**Comment by fasterthanlime** [comment]
Does it also happen with electron 0.36.11 ? Does it also happen with the 'redux' branch ?

**Comment by ogbaba** [comment]
I was on electron 0.35.2 then 37.2 but on 37.2 no segfault i tell you once i'm on 36.11

**Comment by ogbaba** [comment]
Well it doesn't seem it's an electron issue :electric_plug:

**Comment by fasterthanlime** [comment]
> Well it doesn't seem it's an electron issue

mh ? it does very much seem like it's an electron issue seeing as I can run the app flawlessly on Windows 10, OSX 10.11, Ubuntu 15.10 and Debian 8.. I'm sorry for the issues, and I'll take a look again before 0.14, but right now I still don't know where it comes from.

In the meantime, if any arch users could try and attach gdb to the chromium process before it crashes: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_debugging.md & see if they can gather some info, that'd be most helpful.

Also, are the people affected by this bug running dual graphic card? (intel+nVidia for example) could you post `xdpyinfo` and your `/var/log/Xorg.0.log` - there has to be a common factor, seeing as not everybody on arch has that problem.

**Comment by ogbaba** [comment]
Oh okay sorry, I thought it was not an electron issue since this problem is the same with all electron versions and because of erbridge comment :

> This happens for me too. It's a recent issue (within the last couple of weeks), since I have used the app in the past.

I'm not running dual graphic card, only a single AMD HD 7870 OC gpu

[Xorg.0.log.txt](https://github.com/itchio/itch/files/178771/Xorg.0.log.txt)
[xdpyinfo.txt](https://github.com/itchio/itch/files/178773/xdpyinfo.txt)

**Comment by leafo** [comment]
Same thing happens to me when I install from AUR. The development version works fine. (I'm also now running the development app with the version of electron installed by aur, v0.37.2, and it seems to be okay)

**Comment by erbridge** [comment]
It never crashes for me, and window events work fine (like closing the window and minimizing to tray, restoring, exiting), but the internal UI is unresponsive and broken.

I am running a machine with two graphics cards, and the issue is the same with or without using `primusrun`.

https://gist.github.com/erbridge/8f53bb6d2ef0b21f7195

**Comment by erbridge** [comment]
Ok, and `master` runs fine.

**Comment by ogbaba** [comment]
Well i installed itch from github master branch directly this time without using the aur and it seems to work fine :+1: maybe there is a problem in the makepkg :/ In fact I always tried to install from the aur and not from the direct source

**Comment by fasterthanlime** [comment]
> Well i installed itch from github master branch directly this time without using the aur and it seems to work fine  maybe there is a problem in the makepkg :/ In fact I always tried to install from the aur and not from the direct source

Well, I don't know what's wrong with the AUR :(

Note that, for the ~next 48hours, master isn't able to install games, etc. - if you want a stable version from the git repo, I recommend checking out tag v0.13.2

**Comment by ogbaba** [comment]
@fasterthanlime Thanks I just tried 0.13.2 and it works fine too ! not as fancy as the master branch however :smile_cat:

**Comment by fasterthanlime** [comment]
> not as fancy as the master branch however

ah, you have to choose between "fancy UI + search but can't install games" or "actually working app" for now ;)

**Comment by ogbaba** [comment]
Well it seems to be working fine on the new 14.0 release through the aur :+1:

**Comment by fasterthanlime** [comment]
@baptistepouget it does? hallelujah! 🎉 🎈 🍰 

edit: it's 0.14.0 btw but I might move to major version numbers later on, a-la react. hmm.

**Comment by FrozenCow** [comment]
Same here. AUR is updated too.
