### ISSUE TITLE
protocol-less image URLs broke the app

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#46]
Here's what I think happen{ed,s}:
- image URLs used to be `https://img.itch.io/something`
- now they're `//img.itch.io/something` (protocol-relative URL)
- since electron is loading a `file://` resource, it's trying to open `file://img.itch.io/something`

**Comment by fasterthanlime** [comment]
So I looked into serving the app from a local http server but it seems to break Electron's node-integration (can't require stuff we need).

@leafo it looks like protocol-relative URLs are now [an anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/) — is there any objection to just using https URLs everywhere? Even if a page is actually loaded over http, it won't cause a warning or anything.

**Comment by leafo** [comment]
Sure, just pushed change.

**Comment by fasterthanlime** [comment]
Awesome, this fixed all the things :)
