### ISSUE TITLE
[win32] game Mutilate-a-Doll 2 broken for v0.13.2

### ISSUE THREAD

**Issue by unixfy** [itchio/itch#460]
:rotating_light: game [Mutilate-a-Doll 2](https://dashrava.itch.io/mutilate) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/bca4d5e0d8be89fcf852).

**Comment by fasterthanlime** [comment]
It's probably grabbing the flash version, which shouldn't be tagged with Windows/Linux/Mac by the developer.

If the developer were to re-order the downloads to have the native version first, or untag the flash version, it would start working on Windows.
