### ISSUE TITLE
[win32] game Skelemania broken for v0.13.2

### ISSUE THREAD

**Issue by DallyBear** [itchio/itch#466]
:rotating_light: game [Skelemania](https://beanallean.itch.io/skelemania) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cb70165b486b7af7da83).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
What happens if you completely uninstall & reinstall the game?

**Comment by fasterthanlime** [comment]
Works great on v15.0.0 of the app - could you upgrade to it, uninstall & install the game and see if it's still an issue?
