### ISSUE TITLE
[linux] game Rebuild / Resist broken for v0.13.1 (LOVE game)

### ISSUE THREAD

**Issue by forest-hermit** [itchio/itch#469]
:rotating_light: game [Rebuild / Resist](https://studiominiboss.itch.io/rebuild-resist) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cf4112b8d430e86571c2).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Duplicate of #135
