### ISSUE TITLE
Allow installing web games

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#47]
@leafo all that's needed to support that is for the various download API endpoints to also list 'web' downloads (possibly with a new field, embed = true ? and have the game type (html5, flash, etc.) in the various game json objects in collection endpoints etc.) - ideally the client would directly download the zip and extract it locally.

**Comment by Jord-JD** [comment]
Question to consider: would the clientitopen the `index.html` for HTML5 games as a new Electron window in the itch client or just open in the default web browser?

The former may visually look more elegant but we'd have to make sure there is no way the game's JS could interfere with the client itself.

**Comment by fasterthanlime** [comment]
@DivineOmega thankfully, Electron has webviews, which are completely sandboxed from the client — so there's no risk a web game could access electron APIs (and touch your filesystem for example).

However, note that native apps do have access to your filesystem etc., so only install the native apps you trust.

I was hoping to support HTML5 games, incl. WebGL, and hopefully [Flash ones too](https://github.com/atom/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md).

**Comment by fasterthanlime** [comment]
This has been merged quite some time ago!
