### ISSUE TITLE
[darwin] game The Legend of Hulk Hogan broken for v0.13.2

### ISSUE THREAD

**Issue by arnaudbenard** [itchio/itch#470]
:rotating_light: game [The Legend of Hulk Hogan](https://kiddfrog.itch.io/hogan) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/aec6582ad7b30f5b7ec2).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Not sure how this was ever tagged as OSX, looks like an .exe? Tagged it as windows.
