### ISSUE TITLE
[win32] Issue for v0.13.2 - Kenney Game Assets (the first one) does not install

### ISSUE THREAD

**Issue by joserocha3** [itchio/itch#471]
Kenney Game Assets (the first one) does not install using the itch application on Windows 10. It downloads, starts installing, and the "Installing" percent stays at 100. I have uninstalled and reinstalled the itch application with the same outcome.

**Comment by joserocha3** [comment]
duplicate issue https://github.com/itchio/itch/issues/455

**Comment by fasterthanlime** [comment]
:stars: Thanks for finding a duplicate so quickly! The issue had two sources, both of which are fixed in the upcoming version, which I'm working hard on getting ready for release.

**Comment by joserocha3** [comment]
Great news. Thanks!
