### ISSUE TITLE
[win32] game Syrup and the Ultimate Sweet broken for v0.13.2

### ISSUE THREAD

**Issue by eltorga** [itchio/itch#473]
:rotating_light: game [Syrup and the Ultimate Sweet](https://nomnomnami.itch.io/syrup-and-the-ultimate-sweet) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1f546aa2c98c47105285).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
From "socket hang up", looks like it's a network problem.

**Comment by fasterthanlime** [comment]
it looks like you keep having network problems. are you on a particularly unreliable network connection ?

**Comment by fasterthanlime** [comment]
do some games install succeed or do they all fail?
