### ISSUE TITLE
Support naked mac executables

### ISSUE THREAD

**Issue by albronca** [itchio/itch#474]
:rotating_light: game [Hack and Slash](https://samgeen.itch.io/hack-and-slash) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e7a46366fc9b6278ee79).

**Comment by fasterthanlime** [comment]
Looks like a naked mac executable, I didn't think anyone was doing that, but we can support it I guess

**Comment by fasterthanlime** [comment]
Will be fixed in the next version, but: in the case of Hack & Slash, they mean for you to run it in a terminal, and that's something the app doesn't do yet. Your best bet is to open a terminal yourself & run the game there, for now.
