### ISSUE TITLE
[win32] game Hustle Cat broken for v0.13.2

### ISSUE THREAD

**Issue by tanyaneko** [itchio/itch#476]
:rotating_light: game [Hustle Cat](https://datenighto.itch.io/hustle-cat) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0c399b2154ef4b50857a).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Hah, the first launch failed with EPERM, interesting.

What happens if you use the 'folder' icon to open the game's install folder and then double-click on 'Hustle Cat.exe' ?

**Comment by tanyaneko** [comment]
It works now, just needed to turn off my antivirus and reinstall apparently!

**Comment by fasterthanlime** [comment]
Ah, so antivirus software can prevent launching executables by throwing a permission error, that's good to know!

**Comment by fasterthanlime** [comment]
@tanyaneko out of curiosity, which antivirus software was it exactly ?

**Comment by tanyaneko** [comment]
@fasterthanlime it was the free version of Panda
