### ISSUE TITLE
API returns object rather than arrays for empty collections

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#48]
Ideally that'd be fixed server-side but we already kind of have schemas for client-side data persistence so we might as well normalize it in the client too.

**Comment by fasterthanlime** [comment]
ping @leafo btw

**Comment by fasterthanlime** [comment]
As of ee644dccea690f807582b49f004a08ee81436215, `save_records` will ignore empty objects

**Comment by leafo** [comment]
it's annoying to fix with lua json encoding, passing nil in place of empty object is maybe better typewise for js

**Comment by fasterthanlime** [comment]
@leafo `nil.map` still isn't going to go well :/

**Comment by leafo** [comment]
well at least you can do nil?.map

**Comment by fasterthanlime** [comment]
haha, not in ES2015 :)

(besides, `nil?.map` would return nil, not [] right?)
