### ISSUE TITLE
Revamp update checking / applying / downloads

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#490]
Checking for an update (or downloading one) shouldn't block playing a game. _Applying_ the update is the only part that should block launching the game.

Potential behavior when clicking play:
- If it currently has an update check queued (e.g. on app start), it'll bump the priority of the update check to the top of the list, while allowing you to 'ignore it'.
- If an update is downloading (or pending download, depending on your settings), it should ask you if you want to wait for the latest version, _then_ launch, or if you just want to launch now.

Downloads should set progress globally so it appears in OSX dock / Windows progress bar / Unity dock, one should be able to re-order downloads by priority easily (by drag & dropping, or buttons)

**Comment by ghost** [comment]
Yes that should be done (:

**Comment by fasterthanlime** [comment]
> Checking for an update (or downloading one) shouldn't block playing a game.

That part is done! cf. other issues like #158 #609

**Comment by fasterthanlime** [comment]
Downloads have been vastly improved in v18 (pause/resume, prioritizing)
