### ISSUE TITLE
[win32] game Double Kick Heroes broken for v0.13.2

### ISSUE THREAD

**Issue by eltorga** [itchio/itch#492]
:rotating_light: game [Double Kick Heroes](https://blackmag-c.itch.io/double-kick-heroes) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7f87c1d653219e4b5880).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
@AndresLiveEc the game is already installed — try uninstalling it from Windows' "Add & Remove software", then installing it again with the itch application.
