### ISSUE TITLE
Hustle Cat not launching on Windows

### ISSUE THREAD

**Issue by jovialslothicality** [itchio/itch#510]
Hustle cat is not launching for me. When I click launch, it just opens up to a black screen. I've tried to run the program as administrator, have tried suspending my anti-virus, and I've tried uninstalling and reinstalling multiple times with no luck. ) : 

Is there anybody with some advise? Or is there anybody having the same problem?

**Comment by fasterthanlime** [comment]
Hustle Cat installs & launches great on v17.1!
