### ISSUE TITLE
App should remember window size on subsequent starts + shouldn't spawn bigger than the screen

### ISSUE THREAD

**Issue by lahtis** [itchio/itch#515]
default window is too big.

**Comment by fasterthanlime** [comment]
@lahtis by "too big" did you it was mean larger than your screen's resolution? or it did fit in the screen, but was too big for your taste?

**Comment by lahtis** [comment]
yes. it is too large in my screen resolution.

**Comment by fasterthanlime** [comment]
App does remember window size now!
