### ISSUE TITLE
[win32] game Tanks of Freedom broken for v0.13.2

### ISSUE THREAD

**Issue by KevMorelli** [itchio/itch#516]
:rotating_light: game [Tanks of Freedom](https://w84death.itch.io/tanks-of-freedom) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f1c73a35a45fd260054e).

:running: Any additional details can go here!

the windows build doesnt open from itch client

**Comment by fasterthanlime** [comment]
Looks like the game's uploads aren't tagged with a platform at all, the developer of the game can fix that
