### ISSUE TITLE
Game won't launch on Linux

### ISSUE THREAD

**Issue by adolson** [itchio/itch#517]
This game:
https://smugames.itch.io/tetrarkhout-alpha

Does not launch correctly on Linux. Itch reports it as running, but the game never comes up.
I can manually run the game from the installed directory and it works.

It also downloads the 32-bit version, even though I am running a 64-bit distro and there is a 64-bit version available.

**Comment by fasterthanlime** [comment]
Although automatic detection would be nice (#419), the app now (18.2.0+) lets you pick which version to download, which should address that particular use-case.
