### ISSUE TITLE
[darwin] game STAR GUARD broken for v0.13.2

### ISSUE THREAD

**Issue by catnipped** [itchio/itch#518]
:rotating_light: game [STAR GUARD](https://lorenschmidt.itch.io/star-guard) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cb2c97390e8d3a709e24).

:running: "broken" when launching from the itch app

UPDATE: didn't have flash installed :)

**Comment by fasterthanlime** [comment]
Unfortunately I'm assuming the .swf file is just tagged as 'Mac / Linux' when really it isn't either mac or linux. Platform tags used to be informational but with the app they actually have meaning now.

It would be possible for the dev to distribute proper mac & linux builds of the game, though (bundling a flash player, etc.)
