### ISSUE TITLE
[darwin] game Project Arrhythmia broken for v0.13.2

### ISSUE THREAD

**Issue by zedwick** [itchio/itch#519]
:rotating_light: game [Project Arrhythmia](https://limestudios.itch.io/project-arrhythmia) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9e5ccedf4bb1e5105063).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like the latest uploads were incorrectly tagged, I fixed them by hand.
