### ISSUE TITLE
Disable gifs while a game is running

### ISSUE THREAD

**Issue by leafo** [itchio/itch#524]
I have no numbers, but I think leaving the itch up in the background with the GIFs running consumes a decent amount of CPU and potentially slows down the running game (I was also doing screen recording at the time, so performance was a bit more critical). What if we disabled the GIFs while a game launched by the app is running?

I'm thinking the API can return both gif and non-gif urls for those games, but IJ'm open to other implementations.

**Comment by fasterthanlime** [comment]
> I'm thinking the API can return both gif and non-gif urls for those games, but IJ'm open to other implementations.

yup, that's what I've been wishing for for a while :)

**Comment by fasterthanlime** [comment]
(disabling the GIFs when the window doesn't have focus is trivial once I have the actual images)

**Comment by fasterthanlime** [comment]
Closing in favor of #118
