### ISSUE TITLE
[win32] game King Machine broken for v0.13.2

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#528]
:rotating_light: game [King Machine](https://bateleur.itch.io/king-machine) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/23618704ac4690f9f699).

:running: Any additional details can go here!

should be marked correctly according to the dev https://twitter.com/ragzouken/status/712359144158797825

**Comment by Ragzouken** [comment]
(is fixed by the dev now, but I don't know what the problem was)

**Comment by domcamus** [comment]
[I am the developer of King Machine]

Thanks for the report. :-)

The problem was of no technical interest, just me being daft. I'd uploaded a new build of the game to fix a minor graphical problem and had forgotten to mark the new version as "Windows". Sorry about that!
