### ISSUE TITLE
[win32] game PRiO broken for v0.13.2

### ISSUE THREAD

**Issue by glc-mvion** [itchio/itch#529]
:rotating_light: game [PRiO](https://danieldavis.itch.io/prio) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c0ebadea2e8d220f2982).

:running: Any additional details can go here!

PC specs : Intel Pentium B960 + GeForce GT710M

**Comment by fasterthanlime** [comment]
Unfortunately, the developer removed the game from itch.io. I suggest you contact them & tell them you'd like it to be back!
