### ISSUE TITLE
[win32] game Rebound broken for v0.13.2

### ISSUE THREAD

**Issue by glc-mvion** [itchio/itch#530]
:rotating_light: game [Rebound](https://bilalitani.itch.io/rebound) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/78f1b51d7aa403878c1f).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like there were no downloads available at the time you tried it - tried it today, worked just fine :)
