### ISSUE TITLE
Stuck on buying games

### ISSUE THREAD

**Issue by Espoiry** [itchio/itch#532]
Whenever i try to buy a game in beta 1.2.3 the game is stuck, i can't choose games or buy them or go back, i can't even close the game, i have to Ctrl+alt+del in order to close it, i can't find anyone else with this problem?

i have tried reinstalling the game up to multiple times, but i can still only create films due to the fact that the game won't allow me to buy games

**Comment by fasterthanlime** [comment]
I really don't understand this bug report, sorry.

Can you upgrade to v15.0.0 and see if it still happens for you? And if so, try to describe it using other terms?
