### ISSUE TITLE
Some MSIs won't install without administrator privileges (even with all the right flags)

### ISSUE THREAD

**Issue by ghost** [itchio/itch#536]
:rotating_light: tool [Tiled Map Editor](https://thorbjorn.itch.io/tiled) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5c81853204e6e3addc4d7895c8429deb).

:running: Any additional details can go here!

Nothing happens when I click run. When I click show in explorer it opens a text files at
[userdir]\AppData\Roaming\itch\users[number]\logs\PZpMMelaWH429poM.txt

**Comment by fasterthanlime** [comment]
Hey, what's the contents of `C:\Users\Cathal\AppData\Roaming\itch\users\141809\archives\178302.i.log.txt` ?

**Comment by ghost** [comment]
Hi sorry I was away on holiday and didn't see your response till now, I actually tried to reinstall and run Tiled Map Editor again through the client and as a result the contents of 178302.i.log.txt are overridden from when you originally asked (I can see it's after logging today's date on the top of the log) but the behaviour is still the same on my end so I would guess it's after logging about the same info anyway.

[178302.i.log.txt](https://github.com/itchio/itch/files/216131/178302.i.log.txt)

**Comment by fasterthanlime** [comment]
@Oakreef is your windows user account an Administrator account? if not, that might be the problem.

**Comment by fasterthanlime** [comment]
see this line in particular:

```
MSI (s) (80:14) [00:10:50:060]: Product: Tiled -- Error 1406. Could not write value InstallDir to key \Software\mapeditor.org\Tiled.  System error .  Verify that you have sufficient access to that key,
or contact your support personnel.
```

**Comment by ghost** [comment]
I am running from an admin account but Itch doesn't pop up a UAC prompt to ask for admin privileges at any point. Manually telling Itch  to run as administrator I was able to successfully install and launch Tiled. Now that it's installed it can launch with or without admin privileges.

**Comment by fasterthanlime** [comment]
> I am running from an admin account but Itch doesn't pop up a UAC prompt to ask for admin privileges at any point. Manually telling Itch to run as administrator I was able to successfully install and launch Tiled. Now that it's installed it can launch with or without admin privileges.

There is built-in support into the itch app to ask for Administrator privilege (via [elevate](https://github.com/itchio/elevate)), but the few .msi files I had tested were able to install without administrator privileges. I'm wondering whether to always run msiexec elevated or whether it's worth trying without first, & parsing the logs for an error message and trying with afterwards..
