### ISSUE TITLE
[win32] game 2 broken for v0.13.2

### ISSUE THREAD

**Issue by hmv9999** [itchio/itch#538]
:rotating_light: game [2](https://hubol.itch.io/2) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e87b610256ab845e7a36616689b65e15).

:running: "Java was not found on your computer. Would you like to download it?" Clicking OK brings up a separate window that says "Downloading" but disappears after a second or so. Latest Java is installed and latest runtime is enabled. Running Windows 10 64-bit.

**Comment by fasterthanlime** [comment]
Hey @hmv9999, thanks for the report! However, the itch app isn't responsible for those messages, I suppose it's "2"'s launcher that is responsible for them. I suggest you contact the developer of the game directly.

**Comment by hmv9999** [comment]
That's what I was afraid of. Thanks anyway!
