### ISSUE TITLE
Les projets supprimés restent sur l'application

### ISSUE THREAD

**Issue by ghost** [itchio/itch#539]
J'ai crée des jeux "test", ouvert Itch, puis je les ai supprimés par la suite.
Il reste néanmoins une trace en local sur l'application et aucun moyen de l'enlever.

![issue](https://cloud.githubusercontent.com/assets/6897521/14234310/8dbc3e88-f9e0-11e5-8ac9-3623d2589e23.jpg)

**Comment by fasterthanlime** [comment]
Ce bug est corrigé dans la version 0.14.x dont la sortie ne saurait se faire attendre.. :)

**Comment by fasterthanlime** [comment]
La version actuelle (v15) ne devrait pas avoir ce problème :)
