### ISSUE TITLE
[darwin] game Cuckoo Castle broken for v0.13.2

### ISSUE THREAD

**Issue by geekytime** [itchio/itch#541]
:rotating_light: game [Cuckoo Castle](https://rilem.itch.io/cuckoo-castle) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/99fb846bfdbcec8544fefeab18bd5c5e).

:running: Any additional details can go here!

Looks like maybe it's in a folder that's not expected? I can get it to run if I open the folder and run the app.

**Comment by fasterthanlime** [comment]
Hmm the app should just detect the `.app` folder and attempt to launch that. I'll take a look.

**Comment by fasterthanlime** [comment]
> I can get it to run if I open the folder and run the app.

Also, this may be caused by the fact that cuckoo castle only has an OSX 32-bit build whereas you are running OSX 64-bit (like 95% of people in the Steam Hardware Survey)

**Comment by fasterthanlime** [comment]
> Also, this may be caused by the fact that cuckoo castle only has an OSX 32-bit build whereas you are running OSX 64-bit

Actually it had nothing to do with it! For the curious folks:
- We were using [glob](https://www.npmjs.com/package/glob) to find app bundles
- When using `**/*.app`, glob was crawling symlinks, which was especially problematic when installing from dmg images, which usually have a symlink back to `/Applications`
  - (That means itch was crawling your entire `/Applications` folder at some point — only enumerating files though, nothing harmful)
- When using `**.app`, glob was _not_ finding app bundles in subdirectories, even though we had fixtures to do that, the tests weren't checking for that (and got lost when I had to ship v0.14.x anyway).

I replaced glob with node-walk for the darwin configure task, and now it works :)
