### ISSUE TITLE
Some InnoSetup installers require elevated privileges

### ISSUE THREAD

**Issue by ShadeJackrabbit** [itchio/itch#542]
:rotating_light: game [Myha](https://the-icehouse.itch.io/myha) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/ea61392a5eef7c51345e63fa55543298).

**Comment by fasterthanlime** [comment]
I'm guessing the game uses InnoSetup, but the kind of InnoSetup installers that doesn't know how to request elevated privileges, and just _needs_ to be launched with elevated privileges.

**Comment by fasterthanlime** [comment]
After testing a bit: Myha uses a very old version of InnoSetup that - indeed - didn't know how to ask for elevated privileges when needed. Supporting that kind of installer is out of scope for itch, closing.
