### ISSUE TITLE
Adobe AIR install failed (no log)

### ISSUE THREAD

**Issue by alfblack** [itchio/itch#544]
Installed Double Kick heroes. it installed. It's now in the installed section. Now I dont know how to run it!
- Clicked on image > sent to webpage
- Clicked on folder > opened notepad install notes (bug!)
- clicked on event log > opened notepad install notes

Ahh other program i installed has a launch button. Now trying to reinstall double kick heroes. Failed again.

**Comment by fasterthanlime** [comment]
Yeah, air installers are really fiddly and many people have reported problems with it. I hope the developers of DKH upload an alternative installer soon :(

**Comment by fasterthanlime** [comment]
I'm giving up on Air installers for now. They're already the most complicated codepath we have, and _still_ really unreliable. I've seen other games relying on Air that run well through itch, but I can't remember which one it was.
