### ISSUE TITLE
[win32] JS error when starting app.

### ISSUE THREAD

**Issue by nickfourtimes** [itchio/itch#548]
This happens right when I start the app.

![capture](https://cloud.githubusercontent.com/assets/215674/14387039/78b98e6c-fd75-11e5-98c5-b06c572349be.PNG)

**Comment by fasterthanlime** [comment]
My best guess is that it was a network error. Can you try seeing what happens with v17.1.0 ? - https://itch.io/app

**Comment by nickfourtimes** [comment]
Oh, hmm. Works perfectly in the latest version. Sorry for the false alarm!

**Comment by fasterthanlime** [comment]
Cool! Handling network errors more gracefully is planned (cf. #498 for example), but newer versions of the app are already quite a bit more tolerant towards them. Thanks for reporting back!
