### ISSUE TITLE
[darwin] game CELESTE broken for v0.13.2

### ISSUE THREAD

**Issue by realmgate** [itchio/itch#549]
:rotating_light: game [CELESTE](https://mattmakesgames.itch.io/celeste) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9e29c08833f2b7c0f38454b8d99a8031).

:running: I can't install it on OS X 10.11.4, as it keeps asking me to re-download.

**Comment by fasterthanlime** [comment]
That's a pico-8 game, closing in favor of #170
