### ISSUE TITLE
[win32] game Adventure Craft Pre-Alpha 1.02 broken for v0.13.2

### ISSUE THREAD

**Issue by nutellaaa** [itchio/itch#550]
:rotating_light: game [Adventure Craft Pre-Alpha 1.02](https://edibleentertainment.itch.io/adventure-craft) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3c64dc283731ba68f7bbe440023ad7f3).

:running: ITS BROKEN IT WONT OPEN PLS FIX

**Comment by fasterthanlime** [comment]
Just tried with v15.0.0 of the app and it works fine. Can you 1) upgrade to the latest version of the app 2) uninstall Adventure Craft Pre-Alpha 1.02 3) install it again 4) accept UAC prompts / follow the installer until the end, and tell me if it's still a problem for you.

edit: screenshot proof
![proof](https://cloud.githubusercontent.com/assets/7998310/14770459/64c2146a-0a72-11e6-8fc3-032077587e71.png)

note: if you already installed adventure craft from somewhere else you might have to uninstall it first from 'Add & Remove Programs'
