### ISSUE TITLE
[darwin] tool Tilemancer broken for v0.13.2

### ISSUE THREAD

**Issue by jain7th** [itchio/itch#551]
:rotating_light: tool [Tilemancer](https://led.itch.io/tilemancer) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8672738b7bc160e9cd3c330633a88b83).

:running: Any additional details can go here!

I just downloaded it in the itch app

**Comment by fasterthanlime** [comment]
This has been fixed since v16 at least. Re-open if still an issue on v17.2.0 or above!
