### ISSUE TITLE
Logs say out of space but 400mb free space (ENOSPC, copying naked exe)

### ISSUE THREAD

**Issue by aveao** [itchio/itch#554]
:rotating_light: game [Planetarium](https://managore.itch.io/planetarium) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0ba0a5e68d117d940e68f4622178117b).

:running: Logs say that I'm out of space, but I have ~400mb free space (120gb ssd was a bad pick :/).

**Comment by fasterthanlime** [comment]
@ardaozkal does adding an install location, setting it as default (star icon), and attempting installation again fix it? — if you have another disk available, of course.

(That said, 400mb does sound like more than enough for a 5mb game.)

**Comment by aveao** [comment]
Setting up a new install location worked.

![It worked](https://0ws.pw/3a2u.png)

I'm not closing this as your solution was a workaround and this is a probably a bug, feel free to close it if you think that this is resolved.

(Also I have more space right now (~900mb)- I moved my builds to my external hdd after posting the issue, that might be the reason, but as you said, 400mb is more than enough for a 5mb game)

**Comment by fasterthanlime** [comment]
I'm going to close it for now b/c I can't think of a good way to reproduce it. But it's good that it's there so that if any similar issues arise in the future we'll have this issue as a data point.
