### ISSUE TITLE
[linux] game Red Rogue broken for v0.13.2

### ISSUE THREAD

**Issue by levisjani** [itchio/itch#558]
:rotating_light: game [Red Rogue](https://st33d.itch.io/red-rogue) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/65bfca13b9a418b268835af8e8a65bd0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
@levisjani just tested with v15.0.0, and it worked great. Can you upgrade to the latest version of the app, uninstall/install red rogue again and let me know if it's still a problem? Thanks!
