### ISSUE TITLE
:bug: Bug on My Creations on Desktop App

### ISSUE THREAD

**Issue by Palups** [itchio/itch#559]
I created a project, but I didn't like it and I deleted it. Ok, fine. But when I open the desktop app and I go to My Creations, the project is still there! How do I remove it from there?

**Comment by fasterthanlime** [comment]
It's a known bug of 0.13.x, the 0.14.x series will solve that :)

**Comment by Palups** [comment]
oh, ok then. it's just a matter of time! haahha thanks! =D
