### ISSUE TITLE
debounce saving preferences

### ISSUE THREAD

**Issue by leafo** [itchio/itch#562]
every sidebar resize event causes preferences to save and app lags (maybe lagging for some other reason)

![](http://leafo.net/shotslp/2016-04-14_20-22-45.png)

**Comment by fasterthanlime** [comment]
> maybe lagging for some other reason

yeah, note that the development version is _much slower_ — due to react proptypes validation and redux devtools mostly

**Comment by fasterthanlime** [comment]
also, it's already debounced:

<img width="439" alt="screen shot 2016-04-15 at 12 32 46" src="https://cloud.githubusercontent.com/assets/7998310/14559000/37ac1ea8-0306-11e6-9b60-258dff0de58c.png">

you may be experiencing something else

**Comment by fasterthanlime** [comment]
I increased the debounce value recently
