### ISSUE TITLE
[win32] game Mutilate-a-Doll 2 broken for v0.13.2

### ISSUE THREAD

**Issue by dcsilver** [itchio/itch#565]
:rotating_light: game [Mutilate-a-Doll 2](https://dashrava.itch.io/mutilate) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/834b30e972e66ca2323db4824861dce0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
The developer had their 'flash' build tagged as Linux/Mac/Windows, which isn't what the app expects.

I flipped the order of the uploads, can you try again? It should grab the windows .exe now.

**Comment by dcsilver** [comment]
Hey - that worked! Thanks. :+1:
