### ISSUE TITLE
[win32] game Space Gardener broken for v0.13.2

### ISSUE THREAD

**Issue by hokku** [itchio/itch#566]
:rotating_light: game [Space Gardener](https://like100bears.itch.io/space-gardener) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/798fd8d7108664ca432cae67d1f943f2).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Works great for me with v15.0.0 of the app. Can you ugprade to that & try again? (uninstall/install if needed)
