### ISSUE TITLE
[win32] game Monstershifter broken for v0.13.2

### ISSUE THREAD

**Issue by Cerno-b** [itchio/itch#568]
:rotating_light: game [Monstershifter](https://dielmormac.itch.io/monstershifter) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/76c1a3f69a5f2a8d91ba6fa141fbc7dc).

:running: Any additional details can go here!

Tried running it from the itch.io client.
I didn't see any executable in the install folder

**Comment by fasterthanlime** [comment]
Answered on game page, should be fixed.
