### ISSUE TITLE
[win32] game Future Love Space Machine broken for v0.13.2

### ISSUE THREAD

**Issue by OneSubtractOne** [itchio/itch#572]
:rotating_light: game [Future Love Space Machine](https://ripenedpeach.itch.io/future-love-space-machine) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c69e19900a8b889c2feb3f982a3a0cff).

:running: Installed via Itch.io, Game never booted. No error messages and no notifications. Just a no start.

**Comment by fasterthanlime** [comment]
Looks like an unsupported type of installer. The developer could fix that by simply distributing a .zip archive.
