### ISSUE TITLE
Preferences gear background icon displayed on top

### ISSUE THREAD

**Issue by elisee** [itchio/itch#573]
When opening the preferences tab, the background gear icon seems to appear on top of all tabs instead of appearing in the background of the preferences tab.

![image](https://cloud.githubusercontent.com/assets/446986/14641988/f1d68580-0648-11e6-848d-c8e2609142fc.png)

Closing the preferences tab makes the icon disappear.

**Comment by fasterthanlime** [comment]
yea I just removed for now
