### ISSUE TITLE
[darwin] game Tube Tycoon broken for v0.13.2

### ISSUE THREAD

**Issue by Momlol37** [itchio/itch#574]
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c72b28c40fda83528c6d892f51b42a42).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Was finally able to test it: the osx version of Tube Tycoon is a .dmg file _inside_ a .zip file. That won't work. Here's what the dev should do:

  1) Zip the .app, upload that, or
  2) Just upload the .dmg
