### ISSUE TITLE
[win32] game miniLAW - Early Alpha broken for v0.13.2

### ISSUE THREAD

**Issue by SkyTech6** [itchio/itch#579]
:rotating_light: game [miniLAW - Early Alpha](https://lassogames.itch.io/minilaw) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7d0b4efec6dcdcea97128d4c80e1396d).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
@SkyTech6 works fine with v15.0.0, can you check that it's still an issue with it?
