### ISSUE TITLE
[win32] game 90 Second Portraits broken for v0.13.2

### ISSUE THREAD

**Issue by Reptilinator** [itchio/itch#580]
:rotating_light: game [90 Second Portraits](https://tangramgames.itch.io/90-second-portraits) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d4627894841f80d20eeee8f062fb4f74).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Hey @Reptilinator! that's a network error, retrying should fix it. Also, v0.14.0 is out! Upgrading is strongly advised. 🌠
