### ISSUE TITLE
game audio playing on game tabs

### ISSUE THREAD

**Issue by Mrmaxmeier** [itchio/itch#581]
HTML games that start playing audio without user interaction (like [Mobs, Inc.](https://pietro-ferrantelli.itch.io/mobs-inc)) will do so on the game tab webview.
Would replacing [`.hide()`](https://github.com/itchio/itch/blob/master/appsrc/inject/browser.js#L83) with `.remove()` for the `game_frame` break anything? Removing the iframe would probably improve idle load as well.

**Comment by fasterthanlime** [comment]
Wait, we're doing hide right now? lemme look into it

**Comment by fasterthanlime** [comment]
@Mrmaxmeier thanks for catching this, I can't believe I shipped that :( crunch is bad kids, don't do it. 🌙
