### ISSUE TITLE
Self-update on Linux should not wait on electron

### ISSUE THREAD

**Issue by ogbaba** [itchio/itch#584]
Hello, I have this message at the bottom right that says itch is downloading an update but it seems it's not : 
<a href="http://i.imgur.com/FnCIMvH.png">
  <img src="http://imgur.com/FnCIMvHl.png" />
</a>

Here is the log from the terminal :
[log.txt](https://github.com/itchio/itch/files/235454/log.txt)

**Comment by fasterthanlime** [comment]
Linux right? I remember this bug. I was expecting electrons' auto-updater to throw since it doesn't support self-updating on Linux but it doesn't, so I'll have to platform sniff instead.

**Comment by ogbaba** [comment]
Yep, Arch  :cow: Gnu/Linux :penguin: more precisely
