### ISSUE TITLE
not logged in to webview by default -> private collections 404

### ISSUE THREAD

**Issue by Mrmaxmeier** [itchio/itch#586]
Trying to open private collections using a wiped profile results in this state:
![no way to login](https://cloud.githubusercontent.com/assets/3913977/14854961/1258a6ae-0c92-11e6-9660-aebfbf6cd8c2.png)
This could be fixed by setting the auth cookies via `<webview>.getWebContents().session.cookies`.

**Comment by fasterthanlime** [comment]
> This could be fixed by setting the auth cookies via <webview>.getWebContents().session.cookies.

Well we'd have to have cookies first :)

App & website login are decoupled for now. App login is less powerful and doesn't have 2FA flow. Site login is all-powerful, has 2FA flow, and expires.

In the meantime I want the code injected into the web view to detect if you're 1) browsing itch.io 2) not logged, and have a little nudge to get you to log in. Later on we can maybe merge both.

Also about collections: having them open the webview is a temporary measure, I still need to implement a proper collection view (that works offline). All the data is there, just ran out of time before v0.14.0

**Comment by Mrmaxmeier** [comment]
Different level of permissions for web/app logins totally make sense. Checking whether the cookies match could've been useful before opening the issue :smile:

I guess something like this would work as a temporary fix:
(~~It doesn't redirect to the source page after logging in though~~)

``` diff
--- a/appsrc/inject/browser.js
+++ b/appsrc/inject/browser.js
@@ -94,6 +94,19 @@ function itchInject () {
       $page.find('.main_column').css('margin', 0)
     }
   }
+
+  {
+    const logged_in = $('.user_panel_widget.logged_in').length === 1
+    const collection_404 = $('.page_widget.not_found_page').length === 1
+    if (collection_404 && !logged_in) {
+      let link = $('.bottom_links>a')[0]
+      link.textContent = 'Login'
+      link.href = '/login?return_to=' + window.location.pathname
+      link.style.color = '#d14343'
+      link.style.fontSize = '15px'
+    }
+  }
 }
```

Native collections would definitely be nice. I might look into opening a pr for that.

**Comment by fasterthanlime** [comment]
We have a `return_to` url param that `/login` honors btw, if you want to make your fix even better ;)

**Comment by Mrmaxmeier** [comment]
Closing due to https://github.com/itchio/itch/commit/76b6fca68da8d1909764b2880467350cff7e0f88 and 17.0.0 release. :+1:
