### ISSUE TITLE
[win32] game The Soccer Player Manager broken for v0.13.2

### ISSUE THREAD

**Issue by CANADAEH** [itchio/itch#589]
:rotating_light: game [The Soccer Player Manager](https://kickoffworld.itch.io/the-soccer-player-manager) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f9582d98393419937e67f9fea99a633d).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Web version of the game advertised as native Windows/Linux/Mac version, I retagged them properly, works in the app now! :soccer:
