### ISSUE TITLE
[Suggestion] Light up download button if game is available to downlaod 

### ISSUE THREAD

**Issue by LadyAijou** [itchio/itch#593]
Version 15.6.7
Windows 10

For new users, browsing their collections, it could be hard to notice the download button at the top of the app view. I entered my collection, brought up a free game, but didn't immediately see the button. It would be user friendly to have the button turn red/pink to indicate that game is available to you at that time. Having the button gray could indicate they need to buy the game or it isn't available. If you're used to the web experience, the instinct is to look on the game page for a download button, rather than at the top. 

![screen shot 05-05-16 at 02 14 pm](https://cloud.githubusercontent.com/assets/19212374/15054269/19de1da6-12cc-11e6-9e5e-b312df459e7b.PNG)

**Comment by fasterthanlime** [comment]
> the instinct is to look on the game page for a download button, rather than at the to

One way I wanted to address this was to maybe keep the download buttons on the game page but have them open `itchio://` URLs instead, which require us changing the way we render game pages

**Comment by LadyAijou** [comment]
I really like the big button, it just needs to pop a little more, to shout at the user "YOU HAVE THIS GAME AND CAN PLAY IT!"

**Comment by fasterthanlime** [comment]
> I really like the big button, it just needs to pop a little more, to shout at the user "YOU HAVE THIS GAME AND CAN PLAY IT!"

Install button used to be itch-red too, I guess I'll make it red again :)

**Comment by fasterthanlime** [comment]
coming in v16.2.0, when buyable:

![screen shot 2016-05-05 at 22 42 00](https://cloud.githubusercontent.com/assets/7998310/15056594/a84b674c-1312-11e6-8f07-dd2d1bcdc380.png)

when installable:

![screen shot 2016-05-05 at 22 42 46](https://cloud.githubusercontent.com/assets/7998310/15056613/b65e086c-1312-11e6-855d-867a6abcd5dc.png)

**Comment by fasterthanlime** [comment]
Closing since fixed in upcoming v16.2.0
