### ISSUE TITLE
[Suggestion] Make the Collections easier to navigate to + Collection page feedback 

### ISSUE THREAD

**Issue by LadyAijou** [itchio/itch#594]
Version 15.6.7
Windows 10

Currently, it's not obvious how to bring up a collection to browse. It would be a lot easier if it displayed a tab for collections along with the Press Hub, Library, and Itch.io tabs on the left hand side under essentials. It does show up under the library, at the very bottom, but if you have a large library it's very easy to miss. 

Additionally, the collections currently come up in a web view, with a white background, it's a little jarring compared to the way the main page and library pages display. I would love to see the collections page formatted more like the library page, with the dark background, and with the buttons to edit your collection in a similar format to the main page. 

Another idea would be to have an "add to library" option on the collections page for free/pwyw/already owned titles that are still in your collection. I would love to be able to have my favorite free games on my library page. It does show in library if you install a title, but it would be so convenient to be able to add freebies to library without an immediate download, so I can play at a later time.

**Comment by fasterthanlime** [comment]
> Currently, it's not obvious how to bring up a collection to browse. It would be a lot easier if it displayed a tab for collections along with the Press Hub, Library, and Itch.io tabs on the left hand side under essentials. It does show up under the library, at the very bottom, but if you have a large library it's very easy to miss.

fixed

> Additionally, the collections currently come up in a web view, with a white background, it's a little jarring compared to the way the main page and library pages display. I would love to see the collections page formatted more like the library page, with the dark background, and with the buttons to edit your collection in a similar format to the main page.

fixed!

> Another idea would be to have an "add to library" option on the collections page for free/pwyw/already owned titles that are still in your collection. I would love to be able to have my favorite free games on my library page. It does show in library if you install a title, but it would be so convenient to be able to add freebies to library without an immediate download, so I can play at a later time.

That might be better handled in a separate issue. I like the way the itch.io library works now (only stuff you've paid for), and if we make it really easy to add to any collection, I don't think people will mind much.
