### ISSUE TITLE
[Suggestion] My Library - 3 Recent Games

### ISSUE THREAD

**Issue by junklatch** [itchio/itch#595]
I can't screenshot it because I broke itch, but possibly might want to re-look at the 'recent 3 games' approach on the "My Library" section. 

For me, being kind of a neat freak with apps, I like to be able to hide and have stuff uniform so I would prefer an option to having those 3 recent games always there. Maybe the Download/Recent Activity section could become it's own tab?

**Comment by fasterthanlime** [comment]
I agree, I'm not happy with those 3 recent games either

**Comment by fasterthanlime** [comment]
Closing since disabled in v16.2.0 (except when in filter mode)
