### ISSUE TITLE
[Suggestion] App icon!

### ISSUE THREAD

**Issue by junklatch** [itchio/itch#596]
We should use that spiffy new app icon that Leaf made- maybe a pink square BG with white for the icon itself?

**Comment by fasterthanlime** [comment]
Are we talking about dock / desktop / tray icons?

**Comment by leafo** [comment]
wherever possible? Here's the high res version http://itch.io/static/images/app-icon.svg

**Comment by fasterthanlime** [comment]
> Here's the high res version

Well, as-is it wouldn't look great as an icon:

![not-great-icon](https://cloud.githubusercontent.com/assets/7998310/15089082/328bbc9c-13fc-11e6-87c8-851c5080778f.png)

But cut down.. it could work:

![better-icon](https://cloud.githubusercontent.com/assets/7998310/15089277/38c5afa6-1400-11e6-846f-274bbb313997.png)

**Comment by fasterthanlime** [comment]
Here's a line-up:

![itch-icon-lineup](https://cloud.githubusercontent.com/assets/7998310/15089421/ed99d126-1402-11e6-9a11-3540ee0892f6.png)

**Comment by fasterthanlime** [comment]
Fixed in v17.2.0

**Comment by fasterthanlime** [comment]
<img width="101" alt="screen shot 2016-05-08 at 14 19 13" src="https://cloud.githubusercontent.com/assets/7998310/15097777/e55ab3ec-1527-11e6-8f0c-cb7ba0eb75e7.png">

Still not super happy with how it looks — it does look out of place in a dock imho. And the color is in the itch family, but not the pink one would expect (too bright/light/white)

**Comment by notNSANE** [comment]
um, hi (?)

I think the idea is great but the execution is so-so. Too many jagged edges, can we get a better one? Shall we open a ticket about this?

**Comment by fasterthanlime** [comment]
Hey @notnsane! I agree, next update has this instead:

![icon256](https://cloud.githubusercontent.com/assets/7998310/15153665/5c7c2df8-16da-11e6-86e3-20d4146fc9b3.png)

(plus a different resize filter so that downscaled versions look better)
