### ISSUE TITLE
Featured top 3 games image previews 1 pixel off

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#597]
The top three games in my Library either have their preview images offset by 1 pixel or the image area is 1 pixel too wide which lets me see the first pixel of the image repeating on the right side of the image.

Screenshot for details:

![itch app images](https://cloud.githubusercontent.com/assets/227734/15056510/28ccac30-12cf-11e6-9227-564e7d8394bf.png)

**Comment by fasterthanlime** [comment]
That's actually on purpose :) but it looks bad, I'm removing it.
