### ISSUE TITLE
Can't buy Lenna's Inception

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#598]
The Buy Now button is not showing up in the Itch app for me for [Lenna's Inception](https://tccoxon.itch.io/lennas-inception). But the option to buy it is there on Itch.io's website.

In the Itch app:
![itch app nobuy](https://cloud.githubusercontent.com/assets/227734/15056733/6cdb423c-12d0-11e6-9dd7-bf32f75bf37f.png)

![itch app nobuy 2](https://cloud.githubusercontent.com/assets/227734/15056742/7bf439e0-12d0-11e6-950e-8e69f6ba05f3.png)

On the website:
![itch io buy](https://cloud.githubusercontent.com/assets/227734/15056771/af1b5b1e-12d0-11e6-9a90-7a17f7ecc9de.png)

**Comment by fasterthanlime** [comment]
A 'Buy now' button is supposed to appear in the top right corner, so it's a navigation issue really (until v16.2.0 comes out — reloading the page or alt-tabbing away from and back to the app should fix it)

**Comment by Deozaan** [comment]
@fasterthanlime I wasn't clear enough. That "Buy Now" button appears for me on other games. But not on Lenna's Inception. That's why I highlighted the area where it should appear in my first screenshot.

Ctrl-F5, alt-tabbing, closing the tab and opening it again all **do not** make the Buy Now button appear.

**Comment by fasterthanlime** [comment]
![screen shot 2016-05-05 at 23 02 12](https://cloud.githubusercontent.com/assets/7998310/15057105/6b764c58-1315-11e6-9012-7ffc014c76bc.png)

seems to work in the current dev release (upcoming v16.2.0) — it changes the way this kind of info is fetched, can't think of another workaround for now, sorry!

**Comment by Deozaan** [comment]
@fasterthanlime OK, nevermind. I found it was happening on some other game pages too, and I noticed the "reload" icon near the address bar. Pressing the reload button does indeed make it appear. :)

**Comment by Deozaan** [comment]
I guess this can be closed since it should work in v16.2.0 and I can work around it for now.
