### ISSUE TITLE
Dropdown next to Buy Now is empty or behind other content

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#599]
There's a big down arrow next to the buy button. I wanted to know what it did, so I clicked it and a small window appeared, but it looks like it's behind the game page's content. Or possibly it's just an empty window.

This seems to only happen for games that cost money. The dropdown works for free games.

![itch bug](https://cloud.githubusercontent.com/assets/227734/15056942/8f490ba0-12d1-11e6-906c-57a4d06d5bf9.gif)

**Comment by fasterthanlime** [comment]
@Deozaan it is empty in this case :) a bug indeed.
