### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by kristenpen** [itchio/itch#602]
to reproduce: enter search query, press return, nothing happens
expected: something happens

version 17.0.0

**Comment by fasterthanlime** [comment]
Which operating system are you running itch on? Windows, Mac, Linux ?

**Comment by leafo** [comment]
Mac

**Comment by fasterthanlime** [comment]
I wasn't able to reproduce that issue. My best guess is that somehow a saga broke somewhere, and it stopped fetching search.

Was the icon at least animated after pressing enter? Have you tried hitting 'Shift-F12', seeing if the chrome devtools log contained anything?

**Comment by jaminscript** [comment]
Same issue, on Windows 10. No animating icon. Nothing happens. Version 17.2.0

**Comment by fasterthanlime** [comment]
To people having this issue: if you press Shift-F5, what happens?

**Comment by jaminscript** [comment]
Tried on Ubuntu 16.04. Same issue. Pressing Shift+F5 seems to refresh the entire app (flashes white and then load screen again), but the search still does nothing.

You can click into the search field and it will animate bigger, but typing in some text and hitting enter does nothing at all.

**Comment by fasterthanlime** [comment]
Search has changed significantly in v18, hopefully solves this. Reopen if you can reproduce on >18.2.0!
