### ISSUE TITLE
Empty downloads tab confusing

### ISSUE THREAD

**Issue by leafo** [itchio/itch#603]
When you boot up the app and head to downloads tab it's empty. Given the context that's available a new user might expect to see things they've downloaded there.

**Comment by fasterthanlime** [comment]
> When you boot up the app and head to downloads tab it's empty. Given the context that's available a new user might expect to see things they've downloaded there.

There's 2 issues:
- Current/finished downloads should persist
- Truly empty downloads tab should show something

**Comment by leafo** [comment]
Even then, having a entire sidebar item called "Downloads" for your download history is confusing. It seems like a secondary thing.

**Comment by fasterthanlime** [comment]
> Even then, having a entire sidebar item called "Downloads" for your download history is confusing. It seems like a secondary thing.

Well it's only open when you actually download things? Right now it behaves exactly like Google Chrome's download tab, for example. Should the `Downloads` tab _also_ display information an `Installed` tab would ? I'd be fine with that :)

**Comment by fasterthanlime** [comment]
The downloads tab now opens when you start to download something, and looks like this when empty:

![screen shot 2016-07-06 at 04 51 20](https://cloud.githubusercontent.com/assets/7998310/16606087/5012f3d0-4335-11e6-953f-78fa5789e7f7.png)

You can still open it explicitly in the bottom-left menu if you want to. Does it seem clear enough to you?

**Comment by fasterthanlime** [comment]
I guess we could have some onboarding that says "Looking for cool things to download? Check out X" where X is one of our featured sources. Unfortunately 0 featured API support so I'd have to hardcode a link to somewhere :(

**Comment by fasterthanlime** [comment]
@leafo is the new downloads tab still confusing?

**Comment by fasterthanlime** [comment]
I'm assuming that means no, re-open otherwise ✨
