### ISSUE TITLE
Consider checking for update *when* launching game ?

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#609]
I want to have preferences on this (maybe it should be the default so beginners don't get confused, but annoying-power-user-I might not want _my_ install to do that).

**Comment by quyse** [comment]
It also might be useful to have a button "check for updates for this game", in case more control is needed, for example for testing. Like I don't want to upgrade to latest version every time I run a game, but another time I'll want to upgrade. Also a useful configurable option would be to check for updates automatically but don't upgrade, just show a notification instead, so user or tester can decide.

**Comment by fasterthanlime** [comment]
Closing as:

  - Checking for upgrades on every launch is a bad idea
  - We do have an individual game update check
  - "Ask before updating" still checks for update in the background but lets you pick between updating now or just launching.
