### ISSUE TITLE
"View community profile" url should be generated from slug, not username

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#631]
![404 porifle](https://cloud.githubusercontent.com/assets/15093567/15096078/0c3588aa-149e-11e6-8133-b84b545853d5.png)

It seems the actual URL is https://itch.io/profile/guard13007

**Comment by fasterthanlime** [comment]
(Side note: wow, the app looks heinous without aliasing! 🐙)

**Comment by TangentFoxy** [comment]
Lol. Any idea why it's doing that? (It doesn't bother me any, but I'm sure it's something else that should be fixed.)

**Comment by fasterthanlime** [comment]
> Lol. Any idea why it's doing that? (It doesn't bother me any, but I'm sure it's something else that should be fixed.)

Well I was just assuming you had antialiasing disabled for font rendering on Windows? (in 'Appearance & Performance' settings)

**Comment by TangentFoxy** [comment]
Would that be the "Smooth edges of screen fonts" setting under System -> Advanced -> Performance -> Visual Effects?
