### ISSUE TITLE
Feedback from Connor Shea

### ISSUE THREAD

**Issue by connorshea** [itchio/itch#634]
I didn't want to spam the issue tracker with all the feedback I'll be giving, so instead I'll put it in this issue. This is in response to @fasterthanlime's [request on twitter](https://twitter.com/fasterthanlime/status/729122585644929025) for feedback. This is feedback on UI/UX mostly, but some of these gripes will be with things other than design.
### The Good Stuff
- Tabs are 👍, nice choice adding those!
- Open source!
- The New Tab view is awesome (it's probably too hidden, IMO it should be the Home view when you load the client)
- Big 👍 for the "Accessibility features" search filter
- Overall I quite like the design, although I will say the website at times doesn't fit well with the client. I personally quite like the brighter, pink/white design of some parts of the website, so if you choose to unify on one "theme" I'd rather choose that.
- Using GitLab CI (What can I say, I'm a shill)
### Issues
- [x] I'm not logged into the store session when browsing on itch.io from the client, which is a bit annoying. It _should_ be possible to add a `X-ITCHIO-SESSION-KEY` header or something similar with Electron (although I'm not 100% sure about that, also be sure to look into security implications).
- [x] Clicking "Purchase or Donate money" for a free game gives me a 404 error (e.g. https://onagrostudios.itch.io/moira-demo/purchase)
- [x] "Show in Finder, where is this item installed" text for games that have been installed sounds weird.
- [x] "Check for update" should be "Check for updates"
- [x] Collections aren't syncing, and there's no "Refresh" button as far as I can tell.
- [ ] It'd be nice if the itch.io store/browse page were auto-filtered to my platform. If a game doesn't support OS X, then I'd rather than not see it as an option when on the OS X client.
- [x] "Things you gave money to" isn't necessarily true, since I downloaded some of them for free.
- [x] Search is displayed everywhere, but doesn't work in the store view. It only shows the currently-downloaded games.
- [x] Go to the itch.io tab => click "All games" => note that the back button in the browser view doesn't take me back to the home page. This is disorienting.
- [x] The "All games" view hides the header bar, which is a weird choice given that the Search bar in the client itself doesn't work.
- [x] The Shopping Cart icon doesn't fit with the rest of the icons (and is a bit ugly IMO), why not use [the one from Google's icon set](https://design.google.com/icons/#ic_shopping_cart)?
- [x] Probably don't [let me do this](https://cloud.githubusercontent.com/assets/2977353/15101495/17cfaf22-154f-11e6-83d1-3385dcda5253.png)
### Suggestions
- [x] I should be logged in by default, having to click on my same user every time I open the client is annoying.
- [x] I'd like to be able to "Close All Tabs" after I've been browsing for a while and have a bunch of tabs open.
- [x] Add a "download" progress bar at the bottom of the client when downloading or updating a game.
- [x] The Help icon would work better if it were in color, but since that'd go against the aesthetic of the client, it may be a better idea to just replace the icon. I really only understood it because I'd used Slack before :P
- [x] Move "Check for Updates" as well as the version number to the "itch" dropdown on OS X (and presumably Windows/Linux)

<img width="215" alt="screen shot 2016-05-08 at 6 13 00 pm" src="https://cloud.githubusercontent.com/assets/2977353/15101264/8fa20c4a-1548-11e6-8f5b-ee9a57141eb2.png">
- When I'm in a collection I should see a "breadcrumb" that can be used to go back to the main Collections view.
- The Collections view is very very simple right now. It should include the name of the collection, whether it's Public/Private (maybe a lock icon if it's private?), thumbnails of a few games in the Collection, 
- The dialog that opens on OS X (and Windows/Linux too) should have a list of my recently played games, Steam does this (and so does Atom if you need a reference implementation).

<img width="450" alt="screen shot 2016-05-08 at 6 17 09 pm" src="https://cloud.githubusercontent.com/assets/2977353/15101283/33c49982-1549-11e6-945b-e160f22fdba9.png">
- [ ] Back Button! I keep clicking things and then wanting to go back to the last view!
- [ ] The buttons on the store page are very out-of-place, in my opinion. It'd look and work a lot better if it was in a horizontal row.

<img width="162" alt="screen shot 2016-05-08 at 6 48 00 pm" src="https://cloud.githubusercontent.com/assets/2977353/15101434/7532ee10-154d-11e6-9611-290d1f1935d5.png">
### CSS Feedback
- I noticed you're switching your linters to Ruby. For SCSS Linting GitLab uses [the SCSS Lint gem](https://github.com/brigade/scss-lint) ([Here's our config](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/.scss-lint.yml), you can also look in the `doc/development/` folder for the Styleguide which includes rationale and whatnot. MIT Licensed, so go crazy!)
- [ ] NEVER EVER USE `!important`, **EVER**. You _will_ regret it. Instead, did you know you can override other CSS by hacking the specificity?

Before:

``` scss
.override-the-evil-item {
  color: $pretty-color !important;
}

.evil-overriding-item {
  color: $ugly-as-hell-color; // mwahahahaha
}
```

After:

``` scss
.override-the-evil-item.override-the-evil-item {
  color: $pretty-color;
}

.evil-overriding-item {
  color: $ugly-as-hell-color; // it doesn't work D:
}
```

Alternatively, you could use `div.override-the-evil-item` which would automatically have a higher specificity and therefore take priority. Unless you're overriding an external style library or (god help you) the browser, there's never ever a reason to use `!important` that isn't solved by specificity. See also [this article](https://medium.com/@dte/understanding-css-selector-specificity-a02238a02a59#.mxsw5m3z9).

I know you didn't come here for CSS feedback, but I gave it anyway :P

**Comment by notNSANE** [comment]
Close all tabs button is a must.

**Comment by fasterthanlime** [comment]
> Back Button! I keep clicking things and then wanting to go back to the last view!

How would you envision an "app-wide" back button working? There's a back button for views that are improved webviews (game tabs, mostly).

> Search is displayed everywhere, but doesn't work in the store view. It only shows the currently-downloaded games.

Oh but on the contrary, hitting enter should search the entire store. Are you not experiencing that? Or maybe you're hit by #602 ?

**Comment by fasterthanlime** [comment]
@connorshea turned your original message into a list of checkboxes, will check them as I address items

**Comment by connorshea** [comment]
@fasterthanlime Steam does the "global" back button pretty well, IMO.

Let's say I navigate through the client in this order:
- Library
- itch.io
- Nuclear Throne store page
- Back to itch.io (by clicking the store tab)
- Super Hexagon store page
- Buy Super Hexagon

If I press back, I expect to go backwards through the pages/sections of the client I've visited. The only exception to this would be when navigating with the back/forward buttons themselves.

As for the search, I'm not sure exactly why it's happening.

**Comment by fasterthanlime** [comment]
So if you do this:
- Open new tab ('x')
- Open google.com in tab 'x'
- Navigate 3 times in tab 'x'
- Switch to itch.io tab
- Switch back to tab 'x'
- Press previous

Should it take you back to the itch.io tab, or to the previous page in the 'x' tab ?

**Comment by connorshea** [comment]
Back to the itch.io tab.

My logic is that oftentimes actions will open up new tabs, so it feels like the interactions should be related in a history like that.

**Comment by fasterthanlime** [comment]
So then the we browsing history of tab 'x' is just trashed? Would the user not be able to go back to a page previously browsed in 'x' ?

**Comment by connorshea** [comment]
@fasterthanlime ideally you'd have only one set of back/forward buttons, as implementing two would be confusing and complicated. The only way to go back in that tab is to continue pressing the global back button.

I'm not sure which would be the expected UX for this, maybe it's best to keep it as-is.

**Comment by fasterthanlime** [comment]
The thing with the Steam client is that it doesn't, in fact, have tabs. Only one view is shown/active at any given time. Changing itch to behave more like it would be losing in functionality, and I don't think I'm ready to do that.

However I'm not completely happy with my current approach of having pinned tabs (that open links in new tabs) and transient tabs (the navigate within themselves).

But I do think the itch approach (of behaving more like an enhanced browser) is superior and want to keep finding ways to improve it rather than just piggybacking the steam approach just because people/we are used to it.

What if 'itch.io' / 'Library' / 'Collections' / 'My creations' weren't treated especially - what if the app just started out as the 'new tab' view, but the 'new tab' view would also contain one row with the few most relevant games from your library, one row with the few most relevant games from your dashboard (with buttons to "View all", which would open the library/dashboard in a new tab) - and then, they'd be just regular tabs - you could navigate to a particular game, maybe even a web page, and back would behave like in a web browser, even though some 'pages' aren't web pages but native components (such as library, collections, etc.)

**Comment by fasterthanlime** [comment]
Also, one thing that might help address the issue you're actually bothered by: closing tab should switch back to the most recently used tab (MRU) rather than the tab before it. That way you could open a game from the itch.io tab, browser around, close the tab (maybe even from a cross in the top-right corner where people expect it?) and it'd go back to the itch.io tab

**Comment by connorshea** [comment]
@fasterthanlime I wouldn't think a close button in the top right of the web view would make much sense, looking at how browsers handle it. I'd be good with the MRU fix, since I can understand the reasoning behind your choice, and agree we shouldn't let an anti-pattern in Steam hold itch back.

**Comment by fasterthanlime** [comment]
I checked a bunch of checkboxes from stuff that was fixed in the past year or so - looking good!

**Comment by fasterthanlime** [comment]
I think v25 addresses most of those, so I'm going to close this now! The remaining items are website issues, feel free to open a sister issue at https://github.com/itchio/itch.io/issues

**Comment by connorshea** [comment]
:o the mad man, congrats on v25!
