### ISSUE TITLE
Blank icon after update

### ISSUE THREAD

**Issue by junklatch** [itchio/itch#635]
17.2.0

I updated to latest version, my taskbar icon wasnt updating (still showed old) so I removed it and restarted the app, and now just shows a blank white page icon

**Comment by fasterthanlime** [comment]
I've been experiencing this too but haven't had external reports, my intuition is that it was `itch_canary` clashing with `itch`, that's why I renamed it to `kitch`, cf. https://github.com/itchio/kitch

(I think some part of the Squirrel.Windows pipeline was trimming `itch_canary` to `itch` and it used to overwrite some files. Pro-tip to anyone who wants to distribute parallel versions of their software: don't use dots, hyphens, underscores, ANYTHING. Just name it something completely different.)

**Comment by junklatch** [comment]
Just uninstalled canary and itch, and re-installed itch

Still the white paper of death :(

**Comment by fasterthanlime** [comment]
So it's not just us / people using kitch (confirmed by many twitter responses).

... dang it. I think I'll just make it update the shortcut whenever the app launches (even not-on-update), but must be careful not to reproduce #239

**Comment by Deozaan** [comment]
I'm not sure if this is related, but:

I noticed last night when I tried to update the icon in the shortcut that the shortcut's "Start In" field was still pointing to an old version of the app (0.13.x) even though that's been long gone. I think it had cached the icon, as the executable it used for the icon was obviously not there anymore. I couldn't update the icon without also updating the "Start in" part of the shortcut.

**Comment by fasterthanlime** [comment]
> ... the "Start in" part of the shortcut.

definitely related, `Update.exe --createShortcut` is supposed to do that job too. I'll keep looking into it, but I can't help thinking that Squirrel.Windows is doing funny things. Updating used to work fine (but had to upgrade Squirrel to fix a security issue)

**Comment by fasterthanlime** [comment]
Current working theory: when moving metal.js from `require` to `import` (v0.14.x), the app's startup time when called with `--squirrel-update` shot up from <1s to around 10s, and this is too slow for Squirrel.Windows.

**Comment by fasterthanlime** [comment]
> Current working theory: when moving metal.js from require to import (v0.14.x), the app's startup time when called with --squirrel-update shot up from <1s to around 10s, and this is too slow for Squirrel.Windows.

This was fixed

> ... dang it. I think I'll just make it update the shortcut whenever the app launches (even not-on-update),

This wasn't done. But regardless, the issue should be fixed. Please re-open if you see it again!
