### ISSUE TITLE
itch launches wrong .html file for web game

### ISSUE THREAD

**Issue by nclm** [itchio/itch#637]
I installed https://pierrec.itch.io/crow-foxy from the Itch app, but when launching it shows `credits.html` instead of `index.html`. There should be some system to prefer index files rather than other html files.

**Comment by fasterthanlime** [comment]
@nclm works fine for me! are you sure you're not running an old version of the itch app? you can get the latest from itch.io/app - please reopen if you're able to reproduce with the latest version!
