### ISSUE TITLE
Games Listed As Higher Price On App

### ISSUE THREAD

**Issue by SolarLune** [itchio/itch#641]
Hey, there. So if you look at a game that is on sale, like [Neurovoider](https://flyingoakgames.itch.io/neurovoider), on the app, it shows up as the full price, even though the game is on sale at 30% off in the header bar (where the "Buy Now" button appears).

Using itch app version 17.2.0, Ubuntu Gnome 16.04.

**Comment by Deozaan** [comment]
Not only that, but it seems to show the wrong currency.

The normal price for Neurovoider is 13.99€. The Itch app shows me that I can buy it for $13.99 or more.

Itch 17.2.0, Windows 10

**Comment by fasterthanlime** [comment]
cf. https://github.com/itchio/itch.io/issues/374

And the API probably doesn't take sale price into account!
