### ISSUE TITLE
Don't hijack standard shortcuts like `Cmd + H` on Mac

### ISSUE THREAD

**Issue by unindented** [itchio/itch#646]
According to the [OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Keyboard.html) (emphasis theirs):

> Key sequences that are reserved by OS X.
> Users rely on these shortcuts to perform the specified actions no matter which app is currently running (these include shortcuts reserved for accessibility purposes). _Don’t override these shortcuts._

See _Table 68-3_ for the list of reserved shortcuts. `Cmd + H` and `Alt + Cmd + H` are in there, so you should find something else for the `History` tab.

**Comment by fasterthanlime** [comment]
It looks like Google Chrome uses `Commmand+Y` - I'm okay with switching to that.

[source](https://sites.google.com/a/umich.edu/going-google/accessibility/google-chrome-keyboard-shortcuts---mac)
