### ISSUE TITLE
On Windows, doesn't respect user profile Downloads location

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch#65]
On my PC, I have my downloads folder on another hard drive because the SSD Windows is on is very small. I noticed by accident when going to my Downloads that a Downloads folder has been created for the Itch.io app in the standard location instead of where it should be.

![wrong location](https://cloud.githubusercontent.com/assets/15093567/11615679/40fe1f3e-9c1c-11e5-8736-a475691f33a3.png)

**Comment by fasterthanlime** [comment]
Can you post the output of:

``` batch
SET
```

Ran in `cmd.exe` ?

**Comment by TangentFoxy** [comment]
As myself, yes?

![set](https://cloud.githubusercontent.com/assets/15093567/11615714/4e44d5ba-9c1d-11e5-92ed-d65dedf4020f.png)

Is it because you're using `HOMEPATH` or `USERPROFILE` and since it's not the entire profile that's moved, you can't see that it should be different?

**Comment by fasterthanlime** [comment]
> As myself, yes?

yup

> Is it because you're using HOMEPATH or USERPROFILE and since it's not the entire profile that's moved, you can't see that it should be different?

Yep :( Using something like electron's `app.getPath("home") + "/Downloads"`

Although I see they recently added some code to support getting the download folder:

https://github.com/atom/electron/commit/d3caea91b073b1c38117135c7e720b2a7deef047

I'm still not sure the library should actually be in the Downloads folder. The Downloads folder is a temporary storage space that a use should be able to clear out from time to time. If one does that with itch.io it has to redownload everything, so, probably not the best place to put things into.

**Comment by TangentFoxy** [comment]
How about AppData?

(And ultimately, perhaps an option for the user to specify a custom location?)

**Comment by fasterthanlime** [comment]
> How about AppData?

That does sound like the best solution for now

> (And ultimately, perhaps an option for the user to specify a custom location?)

Was definitely planning on adding that sooner rather than later (even if perhaps there's no UI for it at first?) because my SSD is getting crowded

**Comment by fasterthanlime** [comment]
Closing in favor of #55
