### ISSUE TITLE
Configurable install location (blocked by Squirrel.Windows)

### ISSUE THREAD

**Issue by notNSANE** [itchio/itch#650]
Not sure if doable due to the way itch/electron app works, but... here's the request.
I'm sure I'm not the only one with limited space on my C:\ partition, probably several SDD users also struggle a bit with this.

**Comment by fasterthanlime** [comment]
@notnsane just to be clear: we're talking about the 150MB the app takes, not the space taken by installed games, right?

**Comment by fasterthanlime** [comment]
> Not sure if doable

Well, we can ship a portable version — but the self-updater won't work (at all). I can make the app notify you when there's a new version, but we kind of intend on releasing new versions frequently (continuous delivery and all that) — so it wouldn't really be practical for someone to upgrade by hand all the time :/

As for making the installer install the app somewhere else, Squirrel.Windows doesn't support that at the moment.

**Comment by Deozaan** [comment]
@notnsane What I do for apps that don't let me customize their install location is make a junction in my AppData folder (assuming Windows) to another drive.

If you don't know what a junction is, it's _kind of_ like a shortcut to another directory, but it tricks the OS into thinking the shortcut is the real thing. Or, to use a programming term, it's essentially a pointer to another location. So the data is actually stored (and accessed) on your D drive (for example) but your OS will think it's also on your C drive, without taking up the space on C.

This tool (for Windows) makes it easy to make junctions and symlinks, etc.: http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html

**Comment by fasterthanlime** [comment]
@Deozaan can you confirm junctions work with Squirrel.Windows (and thus itch?)

**Comment by Deozaan** [comment]
@fasterthanlime is this good enough? :)

![itch junction](https://cloud.githubusercontent.com/assets/227734/15226942/2bb15018-1842-11e6-89fa-6d79d6c78d4d.png)

**Comment by notNSANE** [comment]
@fasterthanlime - yes, that 150 MB.

And yeah, all the "electron" apps I'm using aren't portable. Franz, Discord, itch also Github Desktop, all of them reside in C:\
Not entirely sure what tech uses GOG Galaxy, they can be installed anywhere and they allow auto-updates.

I know about junctions and Link Shell Extension is great, I use it for Unity Cache, but in Windows 10 I'm having some issues regarding permissions and I'm not sure why. It's a very complex system and sometimes it breaks completely, or they disable stuff (like not being able to drag and drop from an elevated app to a non-elevated app).

**Comment by pbondoer** [comment]
Sorry to bump an old issue, but have you considered using a packer like [UPX](http://upx.sourceforge.net/)? I've had pretty good results in the past when using it in conjuction with nwjs (which is basically node and chromium packed together) and no performance issues as far as I could tell (haven't done any profiling but that wouldn't be too difficult).

**Comment by Faedelity** [comment]
Relevant to the closed issue just above me; the name of this issue should probably be adjusted. Portable apps are ones you can use on multiple computers, running them off of a thumb drive or something similar. This doesn't sound like what's being requested here, although it would be awesome. Being able to configure a different install location doesn't inherently make an app portable, but that's all I was looking for, and it sounds like what most of the others in this issue are looking for. 

If I am correct in this, I suggest that this issue be renamed to something along the lines of "Configurable Install Location". If I am wrong, and true portability is what is aimed for in this issue, then #946 is not a duplicate.

**Comment by notNSANE** [comment]
It's actually both things (by making itch portable you're also setting up an "install location"), but I'd take the easier solution anytime. 

The way to go with software IMHO is just upzip it and let it live where you deployed it, no external access of any kind. Some other people prefer having an installer (with custom install location available), but that also creates registry entries which are a problem in case _something goes wrong_.

BTW, by making the app not write any registry entries nor generating custom data on %appdata% or similar, you're effectively _also_ making it a strong candidate for a Universal Windows Package (UWP) for short.

**Comment by Faedelity** [comment]
Making it portable would also solve the "install where you want it" issue, but installing in an alternate location doesn't inherently give the option to use as a portable app. I learned that the hard way the first time I tried to make a portable app thumb drive. :-) Portability requires it to also not rely on anything outside its own folder, as notnsane  mentions. I, personally, like programs that make a listing in the Installed Programs list and have an Uninstaller for use on my hard drive, but I cope if it's set up to just run in and of itself, and I have to make my own start menu entries.

**Comment by fasterthanlime** [comment]
Just a quick note that:
- The app can be launched from any folder and
- It doesn't write anything to the registry

Like I said earlier, the fact that it installs to `%APPDATA%` is just how Squirrel.Windows works, a framework we use both for installation and for self-updating the app — so I'm waiting until they add the feature or we find a suitable replacement (my money's on the former rather than the later).

It's also still not a super high priority, as the app itself is pretty small, and choosing where to install games is a much bigger deal (and it lets you do that already!)

**Comment by fasterthanlime** [comment]
Hey, v25 is out and it lets you pick where to install it :)
