### ISSUE TITLE
Zen and the art of transhumanism broken on windows

### ISSUE THREAD

**Issue by ragekit** [itchio/itch#652]
Hello !
As stated the game doesn't want to download on windows (say there is no version for my os)

here is the game https://deconstructeam.itch.io/zen-and-the-art-of-transhumanism

Maybe it is because the game is in a rar archive ?

**Comment by Deozaan** [comment]
> Maybe it is because the game is in a rar archive ?

@ragekit Sounds likely: https://itch.io/t/11918/rar-support-is-not-happening-repack-your-games

**Comment by notNSANE** [comment]
I sent a tweet to Deconstructeam, they will fix this ASAP.

**Comment by fasterthanlime** [comment]
App behaving as intended (although not showing a rar-specific warning is a regression.. but pretending that rar doesn't exist anymore does wonder to my health)
