### ISSUE TITLE
App window displays nothing after left open for a while

### ISSUE THREAD

**Issue by ghost** [itchio/itch#653]
So, this may be a pretty low priority issue, but I left the itch app open overnight (likely through one or two computer sleep cycles) and when I un-minimized it just now, there was no content in the window.

![Image](http://i.imgur.com/XPBm1dL.png)

I tried closing the app and reopening, but it did the same thing. It only started working again after I manually killed the two itch processes running.

I'm on Windows 10 if that helps!

**Comment by fasterthanlime** [comment]
Please re-open if you manage to reproduce in v25!
