### ISSUE TITLE
Diacritics are not stripped for search purposes (Maître != Maitre)

### ISSUE THREAD

**Issue by JeroenDStout** [itchio/itch#656]
(In the Itch app) Searching the store for "Maitre" will yield no results, whereas "Maître" returns the correct result (https://powerhoof.itch.io/the-maitre-d).

When searching for installed applications, "Maitre" and "Maître" both return the correct result on top, but return slightly different other results (which have nothing at all to do with maitre).

I dare to think expected behaviour is not counting diacritics in search results.

**Comment by fasterthanlime** [comment]
This seems like a website issue, /cc @leafo 

The app could strip diacritics before issuing the "search" API call, but it won't help here as https://api.itch.io/search/games?query=maitre returns 0 results indeed

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/906
