### ISSUE TITLE
Can't log in (does the app support proxies?)

### ISSUE THREAD

**Issue by UtkrishtDhankar** [itchio/itch#659]
I'm behind a university proxy. At the moment, I can't get past the log in screen in version 17.6.0 on OS X El Capitan. Here's what happens.

I enter my username and password. The logging you graphic appears. In the lower right, it says "Looking for updates". In the lower left, the "History items" goes to 2, but whenever I click on it, it goes back down to zero without showing me anything.

After a bit, an error shows up above the username field. I'd copy/paste the text, but I can't select it, and the window showing it is too tiny for me to screenshot all the trace, but the error is "socket hang up". I suspect this is due to my university proxy, as most other programs fail this way as well (Steam, for one).

Any fixes, anything I'm doing wrong?

**Comment by UtkrishtDhankar** [comment]
Just confirmed that the issue does happen on my Windows 10 machine as well, exactly how I described it for the mac.

**Comment by fasterthanlime** [comment]
> most other programs fail this way as well

most, but not all? is the proxy properly configured at the OS level?

**Comment by UtkrishtDhankar** [comment]
Yes. By most other programs mean things like steam, unreal (they fixed that recently, yay), and team speak. 

The Os level settings don't seem to affect the program, although this is just a guess. Perhaps you could push a branch making the error text copyable? I'd do it myself, but I have no idea how electron works.

**Comment by fasterthanlime** [comment]
Does setting the `HTTP_PROXY` environment variable impact the app at all? (It looks like it should but I'm unfamiliar with how Node.js handles proxies)

**Comment by UtkrishtDhankar** [comment]
Nope. I've had it set all this time.

I have no experience with Node.js, but perhaps look at [Atom Package Manager](https://github.com/atom/apm)? I used to use Atom for text editing, and its package manager APM has configuration options to set the proxy. It didn't read the `HTTP_PROXY` as well.

If you do work on this, I'll be happy to help with testing/bugfixing the new proxy settings, btw. Thanks for looking into this and making such an awesome platform!

**Comment by fasterthanlime** [comment]
It looks like this could be as simple as reading `process.env.http_proxy` / `process.env.HTTP_PROXY` and passing the `proxy` option to [needle](https://github.com/tomas/needle)

**Comment by fasterthanlime** [comment]
Interesting thread to retrieve proxy settings from OS: http://arstechnica.com/civis/viewtopic.php?t=147601

I wonder how feasible it is to use Chrome's network stack to retrieve proxy settings on startup. It probably already does the right thing.

_edit: There's a `resolveProxy` method on the Electron session object: https://github.com/electron/electron/blob/master/docs/api/session.md#sesresolveproxyurl-callback_

**Comment by fasterthanlime** [comment]
Woo, seems to work well!

<img width="1376" alt="screen shot 2016-07-28 at 23 41 45" src="https://cloud.githubusercontent.com/assets/7998310/17230524/eadb0468-551c-11e6-9c02-2c0e40d89d02.png">
