### ISSUE TITLE
When updating, version number shown isn't the one assigned via butler

### ISSUE THREAD

**Issue by slowriot** [itchio/itch#662]
![](http://i.imgur.com/Jn5uSA9.png)
It would be nice if the version displayed here was the one specified by the --userversion flag given to butler, so it would make sense to players in correlating with the displayed game version.

**Comment by fasterthanlime** [comment]
Need API support for that, cf. https://github.com/itchio/itch.io/issues/412

**Comment by fasterthanlime** [comment]
It does that now! (see bottom-right)

![screen shot 2016-11-15 at 13 58 02](https://cloud.githubusercontent.com/assets/7998310/20306621/8dd594b6-ab3b-11e6-9284-c85a696d9c76.png)
