### ISSUE TITLE
Add option to disable "close to tray"

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#666]
cf. comment by @quyse:

> @fasterthanlime On my development machine (Arch Linux) I'm using xmonad tiling window manager, which doesn't have any sort of traditional tray panel. So after closing the window it's still running invisibly, and the only way to actually close itch app is to manually kill the process. Therefore the option to disable 'close to tray' behavior would be much appreciated :)

(link: https://github.com/itchio/itch/issues/140#issuecomment-221848285 )

**Comment by har0ld** [comment]
I'm on Windows using the Itch app and I would love an option to disable "close to tray" because I don't want to manually kill the process or toy with right clicks in the taskbar. I would like to close the Itch app by clicking the red button, I think that's pretty normal :) Thank you so much!
