### ISSUE TITLE
Browsing doesn't stop videos.

### ISSUE THREAD

**Issue by lvictorino** [itchio/itch#667]
If you start playing a Youtube video and change page you can still hear the video's music playing.

Example:
- In the app go to a game page with a video ( ex: https://stellar-jockeys.itch.io/brigador )
- Press play
- Navigate to another tab (ex: itch.io landing page)

**Comment by fasterthanlime** [comment]
@lvictorino by "change page" you mean navigate within the same tab? or switch to another tab?

**Comment by lvictorino** [comment]
@fasterthanlime navigate to another tab... sorry.

**Comment by fasterthanlime** [comment]
Ah, well that's a feature then :)

**Comment by lvictorino** [comment]
...hhmmm I'm pretty sure it doesn't look like a feature... but I can never tell with you :confused:

**Comment by fasterthanlime** [comment]
@lvictorino well, they're tabs, just like browser tabs. What did you expect to happen? If you start playing a youtube video in a web browser, then open a new tab, it doesn't mute the video. The itch app behaves the same, so I'm not sure what you were expecting!

**Comment by lvictorino** [comment]
Ok sorry I got confused by their position... I haven't even realized they were actual tabs (I'm dumb), I thought they were something like a browser history or something.
Sorry for that.

**Comment by fasterthanlime** [comment]
Haha, you're not dumb :) the user is never dumb! I suppose the current layout is a bit confusing, I'm open to suggestions on how to make it better!
