### ISSUE TITLE
Key combo to kill last-launched game

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#668]
cf. https://github.com/itchio/itch/issues/294#issuecomment-221861051 by @professorkaos64

> I wouldn't use just Escape, as games may use that for something, and it's been a hot topic of contention with some emulators, such as RetroArch (accidental use of it etc.). What's your thoughts? I would use a combo that all keyboards support (Standard keyboard/Mac keyboard). I think ergonomically, a combo that uses both hands seems less error prone.
> 
> Some ideas:
> 
> ALT+F4
> CTRL+SHIFT+X
> CTRL+ALT+BACKSPACE (this feels pretty natural, this is my vote)
> Of course this is up to you. I would of course (and I haven't checked yet) add this to the help/readme in the Itch interface itself.

**Comment by fasterthanlime** [comment]
Ah, good comment from @quyse:

> Hm, historically Ctrl+Alt+Backspace was used for killing X server, wasn't it? Although not sure if and in what distributions it might work now.

cf. https://github.com/itchio/itch/commit/4c13c222db1c3444d8ed733fb4dfc95688c23bb2#commitcomment-18082706

**Comment by mdeguzis** [comment]
Thanks! Will try this out soon.

**Comment by fasterthanlime** [comment]
Note that this isn't in a stable build yet! Will be soon (TM).
