### ISSUE TITLE
Create META file for configuring launch execution

### ISSUE THREAD

**Issue by erodozer** [itchio/itch#677]
App launching is currently limited by only executing the top-most executable within the installation directory of a game.  Some games don't even have executables, or bundle batch/shell scripts to launch their game (such as mine does with a bundled jre).

I propose a more generic approach to launching apps, with a fallback option to launching the top-most executable, using a simple config/meta file in a common formatting standard, such as ini, yaml, or json.  This config file would be located in the top-most directory of the app, and can have a list of run options, in case the developer wants the user to have access to different run configurations or tools.

An example would be something like this

```
[default]
cmd=bin/jre/javaw.exe -cp assets/:mygame.jar com.nhydock.MyGame
arch=x64|x32
platform=win32

[default]
cmd=bin/jre/javaw -cp assets/;mygame.jar com.nhydock.MyGame
arch=x64
platform=mac os|linux

[debug_mode]
cmd=bin/jre/javaw.exe -cp assets/;mygame.jar com.nhydock.MyGame -debug
arch=x64
platform=win32

[level_editor]
cmd=bin/jre/javaw.exe -cp assets/;mygame.jar com.nhydock.LevelEditor
arch=x64
platform=win32
```

Architecture and Platform definitions would follow node.js standard values for detection, as produced by the `process` variable.  It's important to allow platform detection for apps that prefer to have one bundle for all platforms.

Run options would be populated in a dropdown extending from the launch button in the interface, with Launch executing the `default` option.  Run options can be titled with underscores dividing words, so in the execution dropdown it will render as spaces (eg. `Launch Level Editor`)

This approach can make bundles platform agnostic if necessary, and dynamically allows for launching any kind of app from the itch.io app regardless of how it was bundled or compiled.

**Comment by fasterthanlime** [comment]
(cf. #92)

**Comment by fasterthanlime** [comment]
closing in favor of #92, feedback welcome there!
