### ISSUE TITLE
Itch App Using CPU When Minimized

### ISSUE THREAD

**Issue by SolarLune** [itchio/itch#685]
Hey, there. 

So, I'm looking in my Task Manager, and I'm seeing 4 itch processes, each taking some amount of CPU. The app is minimized to the notification area, and isn't downloading anything right now. Overall, it's taking around 17% of my CPU. I'm running Ubuntu Gnome 16.04.

Thanks!

**Comment by fasterthanlime** [comment]
Hopefully will be solved by #118

**Comment by SolarLune** [comment]
Cool! I'll close this for now and reopen it if the update that includes that GIF change doesn't solve it. Thanks!
