### ISSUE TITLE
Upgrade weblate + delegate approving translation suggestions

### ISSUE THREAD

**Issue by quyse** [itchio/itch#694]
Hi @fasterthanlime, I just want to point out some issues with weblate app used for itch translation (https://weblate.itch.ovh/).

It's not very usable at the moment. For example, I don't see any way to get list of untranslated strings in a given language. "Untranslated strings" link at main page of a language actually shows list of strings which has translation, and sometimes even has translation and suggestions, i.e. it's simply incorrect. In a History pane there're some "Resource update" events (I guess that means some new source strings have been added), but click on the link just redirects you back to main page, so to actually find those new strings you need to click through all the strings. There's no simple list of strings with like two columns - source string and current translation, so if you lost some string you wanted to make a suggestion for, again you often need to search for it by clicking through (because "search" feature doesn't work well for non-English languages). There's "Nearby messages" list on every string's page, but looks like it shows some random set of strings, i.e. not really helps, for example when context is unclear. (Opening `en.json` file from Github repo helps a lot, as you can see other strings related to the string in question). No way to see my own list of suggestions to review. Etc, etc.

Maybe some of these issues are solved in latest version of weblate? Or maybe I miss something, then it might be worth to make a documentation page explaining how to properly use it :) Currently, given the issues above, instead of struggling with web app I would strongly prefer doing straight pull requests into github repo. You may lose some "collaboration" possibilities and non-developer people willing to translate, but anyway.

BTW despite all the struggle I've added suggestions for all untranslated strings in Russian localization like a month or two ago, and they still haven't been approved. :) Also, maybe it's good to have localization managers for some languages who would be able to approve suggestions and participate in discussion, in that case I can happily be the one for Russian (I am native speaker).

**Comment by fasterthanlime** [comment]
Hey @quyse, thanks for bringing all these issues up! Let me address them one by one.

> "Untranslated strings" link at main page of a language actually shows list of strings which has translation, and sometimes even has translation and suggestions, i.e. it's simply incorrect.

I think this is a side-effect of how Weblate works — even if a string has suggestions, it's considered "Untranslated" until one is approved. Furthermore, if the source string is changed, then the translation is marked as "Fuzzy" and the string goes back to the "untranslated" state, to give the translators a chance to review the source string change and see if the translation needs to be adapted as well!

> Maybe some of these issues are solved in latest version of weblate? Or maybe I miss something, then it might be worth to make a documentation page explaining how to properly use it :)

Actually, there is! https://itch.io/t/11917/translating-the-app-continuously — but it should probably be migrated to the itch app manual instead.

It also looks like the Weblate team has been busy: https://github.com/nijel/weblate/blob/master/docs/changes.rst — I'll take a look at deploying 2.7 asap.

> BTW despite all the struggle I've added suggestions for all untranslated strings in Russian localization like a month or two ago, and they still haven't been approved. :)

You're right, I've fallen way behind on reviewing translations, I'm sure there are many more suggestions waiting in many other languages.

I like the idea of having managers for languages. I've just added you to the 'Managers' group, which means you should be able to start accepting suggestions (or translate directly without going through suggestions).

I'm not sure where to go to find managers for other languages, maybe I'll get in touch with the top translators for a given language!

**Comment by quyse** [comment]
> if the source string is changed, then the translation is marked as "Fuzzy" and the string goes back to the "untranslated" state, to give the translators a chance to review the source string change and see if the translation needs to be adapted as well!

Oh, that's what "Fuzzy" means. So I need to un-check "Fuzzy" if I think the translation is OK and want it to become a "translated" string?

> Actually, there is!

Yeah, I saw this doc page about translation on itch, and it actually explained some unclear things, like source/translation scopes of comments. Looks like it could be expanded :)

> I've just added you to the 'Managers' group

Thanks! I'll review Russian again then and accept/unfuzzy everything I can, so itch app can finally be fully Russian-translated.

**Comment by fasterthanlime** [comment]
> So I need to un-check "Fuzzy" if I think the translation is OK and want it to become a "translated" string?

Yes!

> Looks like it could be expanded :)

Apart from the fuzzy thing, can you think of other things that are missing?

> Thanks! I'll review Russian again then and accept/unfuzzy everything I can, so itch app can finally be fully Russian-translated.

Thanks a lot! 🌠

**Comment by fasterthanlime** [comment]
(Note: the translation server is currently having some downtime as I'm upgrading to weblate 2.7)

**Comment by quyse** [comment]
> Apart from the fuzzy thing, can you think of other things that are missing?

I think fuzzy thing (i.e. misunderstanding that it's actually a list of updated strings) was the biggest one, making an impression of complete chaos in the app. You may also put an advice to look at `en.json` from repo in order to understand context, there were a lot of questions about context in comments which could be easily resolved by looking at the file. I'll wait until weblate server is functional and then may add something more, maybe some things are actually improved :)

**Comment by fasterthanlime** [comment]
I've finished upgrading the server to Weblate 2.6, and it looks like I won't even need to update the guide for 'fuzzy'!

<img width="669" alt="screen shot 2016-06-13 at 15 05 55" src="https://cloud.githubusercontent.com/assets/7998310/16008554/cfea714c-3178-11e6-9b6a-2cf8edc7b548.png">

What do you think @quyse ?

**Comment by quyse** [comment]
@fasterthanlime Yeah I noticed they renamed that thing, now it's clear :D

The webapp appears to be not configured properly yet: changes are not going through. For example I cannot accept a suggestion or un-check "needs review". Looks like browser sends POST request to "http" endpoint, which gets 301 redirect to "https" version, and browser turns that into GET request, so it doesn't work.

**Comment by fasterthanlime** [comment]
@quyse better now?

**Comment by quyse** [comment]
@fasterthanlime Yep, looks good now!

**Comment by fasterthanlime** [comment]
Since weblate was upgraded, I'm closing in favor of #696
