### ISSUE TITLE
Name 'translation managers' for approving suggestions

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#696]
I have fallen behind on reviewing translations, which means the app isn't as well-translated as it could be.

On @quyse's suggestion, I'm in the process of promoting contributors on https://weblate.itch.ovh/ to the "Managers" group, which allows approving/rejecting suggestions, and translating directly without going through the suggestion system.

Here's a list of current managers:
- [x] Arabic: [yjaffal](https://weblate.itch.ovh/user/yjaffal)
- [x] Bulgarian: [lyubomirv](https://weblate.itch.ovh/user/lyubomirv)
- [x] Catalan: [xesa](https://weblate.itch.ovh/user/xesa) + [cegonse](https://weblate.itch.ovh/user/cegonse)
- [x] Chinese: [cyrilis](https://weblate.itch.ovh/user/cyrilis)
- [x] Czech: [p-bo](https://weblate.itch.ovh/user/p-bo)
- [x] Danish: [cybolic](https://weblate.itch.ovh/user/cybolic)
- [x] Dutch: [velddev](https://weblate.itch.ovh/user/velddev)
- [x] Englitch: @elisee
- [x] Esperanto: [vanege](https://weblate.itch.ovh/user/vanege)
- [x] Finnish: [jussi-kalliokoski](https://weblate.itch.ovh/user/jussi-kalliokoski)
- [x] French: [fasterthanlime](https://weblate.itch.ovh/user/admin)
- [x] German: [jonasmumm](https://weblate.itch.ovh/user/jonasmumm) + [mrmaxmeier](https://weblate.itch.ovh/user/mrmaxmeier)
- [x] Greek: [batig](https://weblate.itch.ovh/user/batig)
- [x] Hebrew: [smiley](https://weblate.itch.ovh/user/smiley)
- [x] Hungarian: [beeci](https://weblate.itch.ovh/user/beeci)
- [x] Indonesian: [NeithR](https://weblate.itch.ovh/user/NeithR) + [ari_linux](https://weblate.itch.ovh/user/ari_linux)
- [x] Italian: [somepx](https://weblate.itch.ovh/user/somepx)
- [x] Japanese: [jupitris96](https://weblate.itch.ovh/user/jupitris96)
- [x] Korean: [sunbkim](https://weblate.itch.ovh/user/sunbkim)
- [x] Norwegian Bokmål: [fleskesvor](https://weblate.itch.ovh/user/fleskesvor)
- [ ] Persian: (vacant)
- [ ] Polish: (vacant)
- [x] Portuguese (Brazil): [yanko](https://weblate.itch.ovh/user/yanko)
- [x] Portuguese (Portugual): [sorcerystory](https://weblate.itch.ovh/user/sorcerystory)
- [x] Romanian: [felixplesoianu](https://weblate.itch.ovh/user/felixplesoianu)
- [x] Russian: [quyse](https://weblate.itch.ovh/user/quyse) 
- [ ] Serbian: (vacant)
- [ ] Slovak: (vacant)
- [x] Spanish: [notnsane](https://weblate.itch.ovh/user/notnsane)
- [x] Swedish: [local-minimum](https://weblate.itch.ovh/user/local-minimum)
- [ ] Turkish: (vacant)
- [x] Ukrainian: [probil](https://weblate.itch.ovh/user/probil)
- [x] Welsh: [dafrancis](https://weblate.itch.ovh/user/dafrancis)

(If you're on the list and would not like to be, please comment here. Similarly, if you'd like to be added as manager for a language, please say so here as a comment!)

**Comment by fasterthanlime** [comment]
I'm still looking for Persian, Serbian, Slovak and Turkish managers. There have been some translations in these languages, but not many.

**Comment by felixp7** [comment]
Oh my. I completely neglected my contributions there lately due to other obligations. I'll try to be more present on weblate.

**Comment by cegonse** [comment]
Awesome to see my name here! I'll keep contributing with the translations as much as I can.

**Comment by Cybolic** [comment]
Happy to help! I don't see any way on Weblate to actually accept translation suggestions, though. Are you sure I'm set as manager for Danish?

**Comment by fasterthanlime** [comment]
> Happy to help! I don't see any way on Weblate to actually accept translation suggestions, though. Are you sure I'm set as manager for Danish?

Ha, I was sure I messed one up! All fixed now 🌈

**Comment by aoyawale** [comment]
helo, I'm interested in helping for spanish.

**Comment by fasterthanlime** [comment]
Hey @chagara, looks like the Spanish translation is [100% complete](https://weblate.itch.ovh/projects/itch/itch/es/) right now!

As strings evolve, you can sign in with GitHub & submit suggestions for @notnsane to review and accept!

**Comment by dafrancis** [comment]
I'm not really understanding the purpose of this. Any change I seem to make isn't really being changed, and any suggestions I'm adding to a word or phrase doesn't seem to add it to "translated". This makes it rather frustrating to translate.

**Comment by fasterthanlime** [comment]
> I'm not really understanding the purpose of this. Any change I seem to make isn't really being changed, and any suggestions I'm adding to a word or phrase doesn't seem to add it to "translated". This makes it rather frustrating to translate.

It looks like I added you to that list but forgot to give you the proper credentials on Weblate! All fixed now, you should be seeing a 'Save' button in addition to the previous 'Suggest' button, and be able to accept/reject other people's suggestions.

Other issues I just fixed since I was doing maintenance on the translation server:
- The translation server wasn't sending e-mails anymore (account confirmation, password reset, notifications)
- The translation server wasn't able to commit changes anymore (I did it manually some time ago, but it's working now - was a combination of problems).

**Comment by fasterthanlime** [comment]
Many managers have been named, I'm still open to naming new ones for languages that don't have one yet, please open an issue if you want to take on a language.
