### ISSUE TITLE
Install -> Installing... -> Install (no message or history)

### ISSUE THREAD

**Issue by IBwWG** [itchio/itch#698]
This is my first try putting up a game on itch.io.  I used butler to upload it, channel windows-beta, and it correctly tagged the download as Windows.  The itch.io desktop app shows my game, and lets me click Download (well, actually, it let me do this twice for some reason)...and then lets me click Install, which then switches to Installing... for a few moments, then switches back to Install.  No messages appear anywhere and it's repeatable, but I have no idea what's going wrong.  On Win7x64.

My itch.io is up to date according to the app (and I only installed it yesterday.)  I successfully installed someone else's game no problem on Windows via the app.

I just went to Preferences and found the app data directory--it's downloaded 4 copies now, but all of them have only the assets dir and the .exe--none of the required DLLs and crashdumper and other things my game needs to run.  (BTW, the preferences view shows 376 MB used...but that's the size of the successfully installed game, and not the four copies of mine.)

Each of them takes up 233 MB (so much for diffing ;) ):

Willy and Mathildas Houseboat Adventure The Game
Willy and Mathildas Houseboat Adventure The Game 2
Willy and Mathildas Houseboat Adventure The Game 3
Willy and Mathildas Houseboat Adventure The Game 4

I'm not sure if things got confused somewhere, but my game's name has a colon in it, which isn't allowed in NTFS.  I see it correctly made the above directories, but maybe somewhere in there it's causing an issue where not all files get copied?

a) I think it should delete unsuccessful copies (or have the option to) and probably include their size in the prefs window
b) how can I get my game to install? :)

**Comment by fasterthanlime** [comment]
Ah, that sounds interesting! Can you link me to your itch.io game?

**Comment by IBwWG** [comment]
It's still restricted, if that's a problem I can unrestrict it but it's not ready for beta release quite yet :) https://ibwwg.itch.io/mathildagame

**Comment by fasterthanlime** [comment]
Hmm, the game downloads, installs and runs just fine for me on Windows. Could you post the contents of `%APPDATA%\itch\logs` ? There should be a bunch of .txt files in there.

**Comment by IBwWG** [comment]
Looks like I broke everything.  My game has some really long asset names...(line 203)

[itch-2016.06.14-07.25.AM.txt](https://github.com/itchio/itch/files/313645/itch-2016.06.14-07.25.AM.txt)

Is this an itch limit, or is it running into an NTFS limit?

Which version of Windows and which FS are you using?

**Comment by fasterthanlime** [comment]
Definitely sounds like you're running into a Windows limit :) itch doesn't have any similar limits.

> C:\Users\Kev\AppData\Roaming\itch\apps\Willy and Mathildas Houseboat Adventure The Game 4\assets\sounds\announcerWiththeacrobaticsandaikidogamesyoudonotchooseadifficultylevelinsteadyouplayaslongasyouwanttoandwhenyouclickbackyoumightearnbooksdependingonyourscore.wav

That's 255 characters long! I installed the game to a slightly shorter install location, which is probably why it worked for me?

It should definitely wipe the unsuccessful install attempts though, that one's a bug.

**Comment by IBwWG** [comment]
OK, I'll redesign the system.  :)  Thanks for your help :)

**Comment by fasterthanlime** [comment]
I opened #699 to deal with the confusing part of this issue. Thanks for reporting!
