### ISSUE TITLE
Inverse Tag Filtering

### ISSUE THREAD

**Issue by khbecker** [itchio/itch#702]
I really like the tagging system and I really like the wide variety of content. However, you guys have a TON of games now. (Good problem to have!) Would it be possible to have filtering by games that don't have a certain tag? Like "NOT 2D and NOT visual novel", for example. My interest is in filtering out genres and types of games that I know I have no interest in, so I can get to the games I might like without having to drill into a lot of specific tags.

**Comment by fasterthanlime** [comment]
Transferred to https://github.com/itchio/itch.io/issues/475 !
