### ISSUE TITLE
Can't update Language

### ISSUE THREAD

**Issue by CreeperChief** [itchio/itch#704]
Can't update the app
http://imgur.com/6sjNiyE
http://imgur.com/6NUIBAv
stuck at "Looking for updates"
http://imgur.com/waRYlCP

**Comment by fasterthanlime** [comment]
@CreeperChief both those update servers are up and running:
- http://locales.itch.ovh/itch/en.json
- https://nuts.itch.zone/notes/17.6.0

Can you access those URLs from your web browser?

Are you behind a proxy? (I suppose not otherwise #659 would've prevented you from logging in)

**Comment by CreeperChief** [comment]
Yes, I can acces these URLs from my web browser.
No, I'm not behind a proxy.

**Comment by fasterthanlime** [comment]
What operating system are you on?

Also, could you post your itch log file? You can find it here:
- `%APPDATA%\Roaming\itch\logs` on Windows
- `~/.config/itch/logs` on Linux
- `~/Library/Application Support/itch/logs` on Mac

**Comment by CreeperChief** [comment]
I'm using Windows 10.
Here's the log file.
[itch-2016.06.15-16.01.PM.txt](https://github.com/itchio/itch/files/316145/itch-2016.06.15-16.01.PM.txt)

**Comment by CreeperChief** [comment]
Problem solved.
You can close the issue.

**Comment by fasterthanlime** [comment]
Did you find out what was causing it?
