### ISSUE TITLE
[linux] game Pixel Dungeon broken for v0.13.2

### ISSUE THREAD

**Issue by peregrin-tux** [itchio/itch#717]
:rotating_light: game [Pixel Dungeon](https://watabou.itch.io/pixel-dungeon) is broken for me.

:book: Here's the complete [debug log]().

:running: The game don't start in Ubuntu 14.04. :(

**Comment by fasterthanlime** [comment]
v0.13.2 is quite old! Support for launching .jar files was added since, please upgrade to the latest stable: https://itch.io/app
