### ISSUE TITLE
can't move the app window

### ISSUE THREAD

**Issue by MTawalker** [itchio/itch#718]
I cant drag and move the application window around my desktop. where ever it opens, thats where it stays.

using; 

MacBook Pro (Retina, 13-inch, Early 2015)
10.11.5

**Comment by fasterthanlime** [comment]
@MTawalker if you install the latest beta build, named kitch, from here: https://github.com/itchio/kitch/releases/tag/v17.6.23-canary (`kitch-mac.dmg`) — do you see the same issue in it? (It'll install in parallel)

**Comment by MTawalker** [comment]
@fasterthanlime that version works fine.

**Comment by fasterthanlime** [comment]
@MTawalker good! the fix will ship in the stable version soon ™️

**Comment by MTawalker** [comment]
@fasterthanlime thanks! that was super quick.

**Comment by fasterthanlime** [comment]
I apologize for the issue remaining in stable for so long — what happened was:
- I released a new stable version of the app using a newer Electron version without doing proper QA on it
- Electron's behavior changed and didn't have a 20px draggable region on the top of OSX borderless windows by default
- I fixed it in the development version
- Stabilizing the development version took longer than expected / got into a bit of scope creep

Dev version is now in feature freeze, so it shouldn't be too long now, for real (hence the soon ™️ ) 🌟
