### ISSUE TITLE
more information link on game pages doesn't work

### ISSUE THREAD

**Issue by leafo** [itchio/itch#739]
Clicking the link does nothing
Expecting more information panel to open

![](http://leafo.net/shotsnb/2016-07-01_12-34-48.png)

**Comment by fasterthanlime** [comment]
it works for me :o

**Comment by fasterthanlime** [comment]
@leafo you can open the devtools with Shift+F12 — do you see any error message there? (there should be two devtools instances: one for the app UI, one for the actual tab)

**Comment by fasterthanlime** [comment]
Haven't heard another complaint about this, and it works fine for me in v25:

![more-info](https://user-images.githubusercontent.com/7998310/45697692-a8ed9180-bb66-11e8-97e8-a2c881b8f496.gif)
