### ISSUE TITLE
Move website modifications out of the app

### ISSUE THREAD

**Issue by leafo** [itchio/itch#750]
There are a few pages that the app manipulates the html/css of. I'd prefer if this was done on the server so there are no surprises when doing refactors. I'll be using user agent to detect whether the user is browsing from the app
- [x] Buy and download buttons on game pages
- [x] Banners on top of game page (jam, goal, etc.)
- [x] Embedded game on game pages
- [x] Intro banners for app and anonymous user on homepage
- [x] trigger `analyzePage` when viewing a game's page
- [x] Login page that has user account prefilled

**Comment by fasterthanlime** [comment]
> I'll be using user agent to detect whether the user is browsing from the app

Thankfully since v18, this is reliable :) (wasn't before because of bad react/electron interactions)

> Can I get a list of all the changes so I can start bringing them over to the server?

All changes are here: https://github.com/itchio/itch/blob/master/appsrc/inject/browser.js - I can take the time to describe them in English later this week-end/next week

**Comment by leafo** [comment]
How do you want to handle buying in the future, do you think it should always go through the website? or should there be a "native" app interface to pay for something?

**Comment by fasterthanlime** [comment]
While that'd be interesting, I'm looking forward to saved cards and if I had to choose between native buy flow and itch bucks or cart/"buy collection" functionality I'd prioritize the latter.

Also, I'd rather integrate 2FA properly and have the login endpoint return cookies so you're logged into the website when you log into the app (we can always have a setting to disable that for the truly careful folks).
