### ISSUE TITLE
Launch of a game with wrongly formatted `.itch.toml` fails silently

### ISSUE THREAD

**Issue by quyse** [itchio/itch#760]
I made a mistake when trying new manifest feature, and wrote `[[action]]` instead of `[[actions]]` in the manifest. When I tried to launch my game via itch, nothing happens except flashing `Launch` button for a short moment. Only when I tried to run it via development version of itch, I saw in console:

```
[reactors/tasks] Task ended, err: TypeError: Cannot read property 'length' of undefined
    at /home/quyse/thirdparty/itch/appsrc/tasks/launch.js:122:9
    at undefined.next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
... // long event trace
```

But when you use release version, you usually don't see console output.

**Comment by fasterthanlime** [comment]
Here's the new behavior: the app will show a dialog and let you open the game log, which contains a dump of the manifest as the app parsed it (serialized to JSON), which is more informative as to where the error come from.

📷 screenie:

![screen shot 2016-07-19 at 23 53 24](https://cloud.githubusercontent.com/assets/7998310/16967950/21223874-4e0c-11e6-9c84-a2ef06300df0.png)
