### ISSUE TITLE
Prevent other programs from screen-grabbing app (macOS+windows)

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#767]

**Comment by quyse** [comment]
Hmm, isn't it absurd? What sorts of confidential data are expected in a gaming client? Now I cannot make a screenshot of itch app in Windows in order to report a visual bug. I can make screens of my regular browser with web banking opened in it, why it's forbidden to screenshot itch?

**Comment by fasterthanlime** [comment]
@quyse you raise an excellent point! I didn't realize it would prevent users from screenshotting the app themselves.

I'll disable it for the main window and enable it only for the purchase window that pops up when you hit donate / buy. Sounds good?

**Comment by quyse** [comment]
> I'll disable it for the main window and enable it only for the purchase window that pops up when you hit donate / buy. Sounds good?

Yes, I think that makes sense, thanks!
