### ISSUE TITLE
Wrong exe gets picked for windows games

### ISSUE THREAD

**Issue by DukeBammerfire** [itchio/itch#77]
Around half the games in my collection break in install, or hitting Launch targets the wrong .exe (i think) 
It'd be very nice if there was an option to open the install folder and either change what the launcher points to, or just launch it manually.

**Comment by DukeBammerfire** [comment]
Also I have no idea where these games are installing to, since the launcher is tucked in the appdata files.

**Comment by fasterthanlime** [comment]
> It'd be very nice if there was an option to open the install folder and either change what the launcher points to, or just launch it manually.

yep

> Also I have no idea where these games are installing to, since the launcher is tucked in the appdata files.

`%APPDATA%/itch/users/USER_ID/apps` (and downloads are in `archives`, next to it)

**Comment by ghost** [comment]
+1 on the "wrong exe" issue, I just tried to install one of my games and it runs the optional DirectX installer exe instead of the actual game exe.

**Comment by fasterthanlime** [comment]
> it runs the optional DirectX installer exe

this sounds really easy to avoid, as it probably has a predictable name and/or signature we can scan for.

we already scan exes to determine installer types: https://github.com/itchio/itch/blob/master/app/tasks/install/exe.js

**Comment by ghost** [comment]
Glad it sounds like an easy fix! Here's the specific game I tried if you need to check out the exe for reference: http://virtually-competent.itch.io/skullshot

**Comment by fasterthanlime** [comment]
v0.12.4 is better at that, please re-open separate issues (one per broken game) or wait for #92
