### ISSUE TITLE
Different look of Latin and Cyrillic letters

### ISSUE THREAD

**Issue by quyse** [itchio/itch#772]
I noticed that itch app uses different fonts for Latin and Cyrillic letters.
Here is screenshot on Linux with Russian language enabled ("installing sandbox" dialog):
![screenshot](http://i.imgur.com/FEfxKIA.png)
(I cannot make a screenshot on Windows where the difference is more visible because of #767).
You can see that `itch.io` and `root` words are displayed with sans-serif font, and the rest of the text in Russian is displayed with serif font.
As I understand, you're using sans-serif Lato font (in `appsrc/static/fonts/lato/font`), and looks like it's actually LatoLatin subset which includes only glyphs for Latin-based European languages. So system is replacing non-latin characters with some other available font.

**Comment by fasterthanlime** [comment]
It looks like Lato 2.0 includes cyrillic characters, I'll make sure the app ships with a complete set!

**Comment by fasterthanlime** [comment]
![screen shot 2016-07-05 at 12 51 13](https://cloud.githubusercontent.com/assets/7998310/16582507/9d17efea-42af-11e6-9988-a83f538a52fa.png)

😎

**Comment by quyse** [comment]
Perfect!
