### ISSUE TITLE
🏁 Issue v18.2.0

### ISSUE THREAD

**Issue by Moth-Tolias** [itchio/itch#775]
I am having the following problem:

attempting to printscreen, record, or otherwise capture images from the itch.io app results in failure, even when it's me trying to do so and not an installed game.

maybe it'd be worth having the screengrab prevention as a [on by default] option, rather than something set in stone?

**Comment by quyse** [comment]
See https://github.com/itchio/itch/issues/767#issuecomment-230335844

**Comment by Moth-Tolias** [comment]
huh, i searched for screengrab and didn't find anything... oh well. at least i know it's been dealt with now.

**Comment by fasterthanlime** [comment]
(I meant to release 18.3.0 earlier but a few more fixes sneaked in, so the release was delayed. Thanks for your patience!)
