### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by ghost** [itchio/itch#777]
I downloaded the app for the first time. When I put in my credentials and tried to log in, I got these two errors. First error says - "**There was a problem during setup: got HTTP 403 while fetching https://dl.itch.ovh/7za/darwin-amd64/LATEST?t=1467704678426**". Second error at the bottom says - "**Update error: While trying to reach update server: undefined**". What's going on?

**Comment by fasterthanlime** [comment]
It's the second time someone reports a 403 from dl.itch.ovh, I'm starting to look at Cloudflare funny...

**Comment by ghost** [comment]
Alright. Keep me posted about this issue

**Comment by fasterthanlime** [comment]
It looks like Cloudflare is having a minor outage at the moment, hoping this is related? https://www.cloudflarestatus.com/

_edit: just seeing now the outage is in Moscow, so probably not related.._

I should modify the setup phase to ignore those errors when packages (like 7za) are already installed locally.

In the meantime, as a workaround: can you try disabling your network connection, launching the app, letting it "log in" (it should work), and re-enabling your network connection? It should let you use it until either Cloudflare or I fix either issue.

**Comment by ghost** [comment]
Hey. I was able to log in, but using a different method. I disconnected from my home wifi and connected my mac to my mobile data hotspot. And I was able to login without any error. So, is there any issue with my ISP?

**Comment by fasterthanlime** [comment]
> So, is there any issue with my ISP?

Unfortunately, this is hard to tell. We might want to move away from Cloudflare at some point (at least for non-browser stuff), because their approach to locking out some people (or countries..) is a bit hit and miss and hard to look into.

I might just disable cloudflare in front of dl.itch.ovh for now

**Comment by fasterthanlime** [comment]
> I might just disable cloudflare in front of dl.itch.ovh for now

Actually can't do that, since cloudflare is supplying an HTTPS certificate for dl.itch.ovh right now, disabling it would cause all requests to https://dl.itch.ovh to fail, so we're effectively hostages of Cloudflare for the time being.

**Comment by ghost** [comment]
The weird thing is only my home wifi network was causing this cloudflare issue. Once I logged in the app using my mobile data network, I'm now able to use the app even on my home wifi network. But, I still get the update error. It's always there. Really annoying. 
And it's not just your app, I'm getting an issue with cloudflare on almost any website that uses it. I have to always complete a captcha before accessing the site that uses it. Annoying

**Comment by fasterthanlime** [comment]
Confirmed the error from Libya: https://twitter.com/itameio/status/752568994226397184

**Comment by fasterthanlime** [comment]
Just whitelisted Iran, Libya and India in our Cloudflare settings, hopefully should resolve the issue! Thanks to xxdesmus on Twitter for the hint.

**Comment by ghost** [comment]
This is happening to me in Windows 10.

**Comment by ghost** [comment]
I'm from Peru

**Comment by fasterthanlime** [comment]
@Ufeldraku just whitelisted Peru, can you try again?

**Comment by ghost** [comment]
Yeah It works, thanks!
