### ISSUE TITLE
🏁 v18.2.0, unsupported installer format

### ISSUE THREAD

**Issue by alfredmakes** [itchio/itch#789]
I am having the following problem:
Attempting to download and install '[There You Go](https://evyatron.itch.io/there-you-go)' using windows 10 client.
Click Install -> Game downloads -> "Installing" -> reverts to 'Install' button instead of play, no error report, download has been completed.

**Comment by fasterthanlime** [comment]
Most probable cause is the installer being an unsupported format. The developer releasing a portable build would resolve the issue :) https://itch.io/docs/itch/integrating/platforms/windows.html

**Comment by evyatron** [comment]
Hi there, I've uploaded a standalone version of the game - **There You Go (Windows Portable ZIP)**. It's an archive with the game files ready to play without the need to install. Hopefully this solves it for you, I admit I haven't tested the game on Windows 10 yet :)

**Comment by fasterthanlime** [comment]
Works great!
