### ISSUE TITLE
when hitting back in itch app browser, please return scrolling to previous level

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#792]
So I scroll through the itch store a lot in the Itch app now because it's lovely.

My main issue now is when I go to a game page to add it to a collection and then go back, my scrolling is reverted to the start of the page.

Is it possible you can put it back to where I was?

It's fine in Chrome, but not in the App.

**Comment by fasterthanlime** [comment]
This is going tricky, as with electron we have no choice but to change the webview size to 0x0 to hide it (which is why the scroll offset gets lost). I can try implementing a custom solution that saves/attempts to restores scroll offset but I'm not entirely sure it would work (as with everything DOM I expect weird edge cases). Worth a shot though!

**Comment by fasterthanlime** [comment]
Oh, I understood the original issue incorrectly — you mean clicking the back button, not navigating between tabs (between tabs, it works fine).

We definitely have to have make own solution for that, see https://github.com/electron/electron/issues/5884

**Comment by fasterthanlime** [comment]
Just implemented a (rather dirty) solution to that, but lazy loading complicates everything, of course :)

edit: Actually Chrome doesn't wait for the page to lazy load all the way and just restores the bottom of the first page, it seems

**Comment by fasterthanlime** [comment]
Actually my code is a bit overzealous and will try restoring scroll even if you just 'end up on the same page again', not necessarily hitting back. I wonder if that's a big problem.

**Comment by LiamDawe** [comment]
Is there no event within the app that triggers when you go back to hook into?

**Comment by fasterthanlime** [comment]
Chrome's behavior is to do it both when going back & forward. There's no event, but I'm calling `goBack` and `goForward` myself, so I guess I can activate a flag there

**Comment by LiamDawe** [comment]
Sounds good, looking forward to seeing it in action :+1:

**Comment by fasterthanlime** [comment]
Going to reopen until I make it trigger only on back/forward
