### ISSUE TITLE
sometimes the app page top right buttons don't appear

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#793]
See here: http://imgur.com/rPcYYSs

Clearly the buttons should be there, but the add to collection and so on aren't appearing. I can still click the links there, as when I hover the cursor does change to a hand for a link (ss doesn't show it).

Sometimes they do, sometimes they don't.

**Comment by fasterthanlime** [comment]
That's really strange, I have no idea what could cause that (short of responsive mode / custom CSS hiding them, but doesn't seem to be the case).

I'm really hoping it's a duplicate of https://github.com/itchio/itch/issues/763 - does it appear in the latest kitch? https://github.com/itchio/kitch

**Comment by LiamDawe** [comment]
Yep seems perfect in the latest kitch.

**Comment by fasterthanlime** [comment]
Cool! That code is also in 18.3.0 (stable), so that should be working fine for you too. If not, re-open.
