### ISSUE TITLE
Consider using FormatJS for better localization

### ISSUE THREAD

**Issue by quyse** [itchio/itch#798]
Currently some strings aren't localized perfectly.

A few strings doesn't reflect number (singular/plural) even in English, probably because it's cumbersome to add both forms?
- `A collection of {{itemCount}} items`
- `+ {{count}} items hidden by filters`

Some strings do support singular/plural forms, but it doesn't work for languages with more than two number categories (such as Russian).
- `an hour` / `{{x}} hours`
- `a minute or less` / `{{x}} minutes`

And here sentence is constructed using string from other source, which doesn't work at all for languages with extensive declension:
- `Perhaps this {{classification}} isn't compatible with it yet?`

We need a way to express these things correctly. [FormatJS](http://formatjs.io/) (and [react-intl](https://github.com/yahoo/react-intl) for integration with React) looks good for that. It knows about different languages, and can easily construct sentences correctly using [ICU Message Syntax](http://userguide.icu-project.org/formatparse/messages). Examples:

| English | Russian |
| --- | --- |
| `+ {count} {count, plural, one {item}, other {items}} hidden by filters` | `+ {count} {count, plural, one {приложение}, few {приложения}, many {приложений}} скрыто фильтрами` |
| `{x, plural, one {an hour}, other {{x} hours}}` | `{x, plural, one {час}, few {{x} часа}, many {{x} часов}}` |
| `Perhaps this {classification, select, game {game}, game_mod {game mod}, book {book}, comic {comic}} isn't compatible with it yet?` | `Возможно {classification, select, game {эта игра ещё не совместима}, game_mod {этот игровой мод ещё не совместим}, book {эта книга ещё не совместима}, comic {этот комикс ещё не совместим}} с ней?` |

Note in last example I had to put almost whole Russian sentence into `select` clause because of word changes due to grammatical gender.

So, it will make easier adding even English singular/plural dependent phrases, and will allow to use correct wording in more complicated cases. It does require some time to get used to the syntax though.

I would say it's low priority, there're just a few problematic strings, and at the moment it's very possible to do quality localization. Still there's difference between good and perfect :)

**Comment by fasterthanlime** [comment]
I knew this day would come.. and I want to do it! There's a few things I really want to get out the door first, but it's definitely in the scope of our localization efforts.

We used to rely on i18next, but I found it too complicated for my taste (it tried to handle language sniffing, locale loading, etc.). It looks like [the intl APIs](https://github.com/yahoo/intl-messageformat) beneath formatjs are just the right level we need to replace my ad-hoc 'localizer' module.

**Comment by fasterthanlime** [comment]
(also, want to emphasize that the quality of your issues has been tremendous! relevant, well-researched, complete, often with ready solutions — and even with titles aligned with the wording of other issues! couldn't help but [give you a nod](https://twitter.com/fasterthanlime/status/752612949018218500) on my twitter 👏)

**Comment by fasterthanlime** [comment]
Closing in favor of #1300 😉
