### ISSUE TITLE
Include 'embed' info in /my-games API endpoint

### ISSUE THREAD

**Issue by seleb** [itchio/itch#802]
When launching a web game from the app, the window is always ~1280x720 instead of matching the viewport dimensions. The size doesn't seem to be resolution dependent (tested at 1080p, 900p, 720p, and 480p with no change).

App version: itch v18.3.0
Platform: Windows 10

**Comment by fasterthanlime** [comment]
By 'viewport dimensions' you mean the ones you specify in the edit game page? Did you try reinstalling the game after changing the viewport dimension in edit game page? It's possible that it only picks them up at install time.

**Comment by seleb** [comment]
These are the options on the edit game page I'm talking about (I don't see any others for dimensions):
![image](https://cloud.githubusercontent.com/assets/6496840/16857670/66768202-49ef-11e6-83d3-076d1dfc0c15.png)

Uninstalling and reinstalling the game doesn't seem to change anything.

**Comment by fasterthanlime** [comment]
Can you link me to the game page in question? (even if it's private)

**Comment by seleb** [comment]
[This is the game I've been testing with](https://seleb.itch.io/star-picker-upper).

**Comment by fasterthanlime** [comment]
Seems to open at the correct resolution for me on macOS

![screen shot 2016-07-15 at 00 52 50](https://cloud.githubusercontent.com/assets/7998310/16858332/7e060a14-4a26-11e6-85fd-d3b00610e45b.png)

**Comment by fasterthanlime** [comment]
So the actual app bug that I could see (with 18.3.0 — make sure you're running the latest version!) was that it attempted to make the canvas fit the whole screen. Since the pico8 player UI isn't rendered in canvas but as separate HTML elements, it resulted in what you see in [my previous comment](https://github.com/itchio/itch/issues/802#issuecomment-232815620).

Future versions of the app will no longer attempt to fit pico8's canvas to the window as it just makes things worse.

**Comment by seleb** [comment]
That's not quite the issue I meant, though it's good to hear that that's going to be fixed.

When I open the game from the app, this is what I get:
![image](https://cloud.githubusercontent.com/assets/6496840/16963140/f71e363e-4dc2-11e6-8571-fda2b34de3e3.png)

**Comment by seleb** [comment]
Okay, I did a bit more testing and found a couple web games which do launch at their web viewport dimensions. Looking at the local files, the games which launch correctly-sized have an "embed" property in .itch/receipt.json which specifies the width/height and a fullscreen bool. This property isn't there when I download any of my projects, so it just defaults to 1280x720.

(Changing receipt.json manually doesn't make a difference, though I'm guessing that's to be expected)

**Comment by fasterthanlime** [comment]
I have an idea: when you install your own games, the app gets info from `/my-games`. When you install someone else's games, it does a request to `/game/:GAME_ID`. I think `/my-games` might be lacking `embed` info, which would explain why installing your own games doesn't respect viewport size!

**Comment by fasterthanlime** [comment]
@seleb you can confirm my theory by comparing the results of the following:
- https://itch.io/api/1/me/game/68977
- https://itch.io/api/1/me/my-games

(⚠️ open in your web browser where you're logged into your itch.io account — don't paste the result of `/my-games` to not leak your download counts)

**Comment by seleb** [comment]
Looks like that's it! me/game has the embed, me/my-games doesn't.

**Comment by fasterthanlime** [comment]
Cool! then the good news is: your game isn't broken for others. The bad news is: ~~I~~ someone need to fix the API ;)

**Comment by GranPC** [comment]
This is now fixed!
