### ISSUE TITLE
Can't install from list of games

### ISSUE THREAD

**Issue by stuartlangridge** [itchio/itch#807]
When browsing a list of games, a free game can't be installed from that list. You have to go into the game's individual page and say "install", and then come back out into the main list again. That's a bit clunky. What I've ended up doing is creating a collection and adding things I want to download to that collection, and then going into the collection and setting them all to install. But it would be handy if there were an install button on free games in the game list as well as on each game's page.

**Comment by fasterthanlime** [comment]
Are we talking game lists as in browsing the itch.io website from the app? We do need better integration between the website and the app, lots of potential integration points, we haven't really come up with a full list yet.

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch.io/issues/908
