### ISSUE TITLE
Chromium renderer occasionally crashes on Linux with GPU acceleration enabled

### ISSUE THREAD

**Issue by quyse** [itchio/itch#809]
Sometimes itch starts showing white pages instead of web content. Seems like it happens randomly, but on average I can get this result pretty quickly - in one or two minutes, by just opening tabs and clicking through links. When it starts, itch shows fully white page instead of web content (but UI on the left/right, Library/My creations/Collection views and even web games launched from app all work normally, so I guess it's only webview). Moving mouse over page does change mouse cursor, i.e. it looks like page is loaded, but not displayed.

I believe it's electron/electron#6139, as it's consistent with what I see: I can only reproduce it on my main machine, which is Arch Linux with AMD GPU. Itch works flawlessly on Arch Linux+Intel GPU, Windows and OS X.

The workaround is to run `itch --disable-gpu`, itch works fine then, but WebGL games started from app don't (they fail to get WebGL context). I'm wondering if there's better workaround, like automatically disable hardware acceleration for specific hardware/OS combination, but not for electron process where web games run.

**Comment by fasterthanlime** [comment]
Ouch, that's a tough one :(

I don't like to answer negatively to issues, but looking at the associated electron thread, I'd rather wait and see if the Chromium/electron bug gets fixed rather than add a workaround that might cause more trouble than it's worth.

It doesn't look like BrowserWindow creation options have anything GPU-related? https://github.com/electron/electron/blob/master/docs/api/browser-window.md

**Comment by quyse** [comment]
> I'd rather wait and see if the Chromium/electron bug gets fixed rather than add a workaround that might cause more trouble than it's worth.

I agree any sort of automatic blacklist always causes troubles, but I think it's OK to add well-explained "experimental" checkbox in Preferences to enable workaround manually, only by users having problems.

> It doesn't look like BrowserWindow creation options have anything GPU-related?

Hmm, looks like hardware acceleration can only be disabled for the whole app only :(
https://github.com/electron/electron/blob/454dd00597c06745284bf8378b14ee4e4e1b73f2/atom/browser/api/atom_api_app.cc#L762-L769

**Comment by fasterthanlime** [comment]
I added an option to disable hardware acceleration in itch master, this will ship in v25.

**Comment by quyse** [comment]
The checkbox fixes the problem, thanks! WebGL games stop working though. Well, as expected.
