### ISSUE TITLE
games that need love on linux does not start

### ISSUE THREAD

**Issue by hero1900** [itchio/itch#811]
i found out that when the games got downloaded it will be in source code not love file which result the inability of launching the game from the itch app

**Comment by fasterthanlime** [comment]
See #135 and #808, well underway now :)

**Comment by fasterthanlime** [comment]
(.love files are actually just .zip archives of the source code, so the app will eventually be able to detect both formats & launch them appropriately)

**Comment by fasterthanlime** [comment]
Closing this in favor of #135 and #808
