### ISSUE TITLE
When hand-picked, update will prompt indefinitely (in UTC-x timezones)

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#815]
cf. https://itch.io/t/32095/keeps-prompting-to-update-games

**Comment by fasterthanlime** [comment]
The bug affect various users in various ways:
- People in UTC+0 are not affected
- People behind UTC (UTC-X) see what @newton64 sees — keeps prompting for update even though update is installed
- People ahead of UTC (UTC+X) might miss an update if it happens X hours of their install date.

The reason is: upload `created_at` dates are UTC, but the app parses that as if they were local time.

**Comment by cdfranck** [comment]
Okay, I see that the issue is something to do with the timezone settings... what is the fix??

**Comment by fasterthanlime** [comment]
Hey @cdfranck, this was fixed months ago and isn't a problem in current versions of the itch app. You can always get the latest version here: https://itch.io/app
