### ISSUE TITLE
Collections don't seem to show up unless e-mail is verified

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#83]
Possibly an API problem? /cc @leafo 

https://twitter.com/Oujevipo/status/676350519372304384

**Comment by leafo** [comment]
only your library should be invisible unless you've verified your email address. I've since changed how purchases are associated to accounts though so that email check should no longer be necessary.

**Comment by fasterthanlime** [comment]
@leafo what do you think happened for Pierrec ?

**Comment by fasterthanlime** [comment]
closing until someone experiences this again
