### ISSUE TITLE
When multiple downloads are available, dialog says "0 bytes" for external links

### ISSUE THREAD

**Issue by elisee** [itchio/itch#842]
Superpowers isn't currently hosting its files on itch.io directly, we just link to the GitHub files.

As a result, this happens in the "Multiple downloads are available" dialog:

![image](https://cloud.githubusercontent.com/assets/446986/17265204/5a07ae4c-55ed-11e6-9584-23b18b6724fb.png)

Maybe the app should not display a size at all or say "Unknown size" in that case?

Running itch v18.4.0, Windows 10 64-bit.

**Comment by fasterthanlime** [comment]
This was fixed a loooooong time ago in https://github.com/itchio/itch/commit/1c4f0b88446f28a288467a47f994c638180a72bd
