### ISSUE TITLE
The itch sandbox prevents Superpowers v1.1 from loading its settings

### ISSUE THREAD

**Issue by elisee** [itchio/itch#843]
After enabling the experimental itch sandbox, I get the following error message when starting Superpowers from itch:

![image](https://cloud.githubusercontent.com/assets/446986/17265311/17392dd8-55ee-11e6-99ca-c8f9058917aa.png)

The first part of the error message is buggy ([now fixed](https://github.com/superpowers/superpowers-app/commit/7ad2489a14a593cced828740514c2784ded6e1d2)) so don't worry about that, but basically Superpowers tries to access stuff in `%APPDATA%` for the current user and then fails because `EPERM`.

I'm not sure if there's something we can / should change in Superpowers, or if there's something to be done on itch's sandbox side.

Running itch v18.4.0, Windows 10 64-bit.

**Comment by fasterthanlime** [comment]
Well, reading `%APPDATA%` is the wrong way to go about it, but the app should still allow for that. I'll take a look at what elevate does.

**Comment by elisee** [comment]
> Well, reading %APPDATA% is the wrong way to go about it, but the app should still allow for that. I'll take a look at what elevate does.

What should we do instead?

**Comment by fasterthanlime** [comment]
> What should we do instead?

I don't know if you actually meant using `process.env.APPDATA` — but windows has API calls like `SHGetFolderPath` which are exposed in Electron by [app.getPath()](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname)

Normally, when launched via the sandbox, the environment is set up in such a way that this correctly returns the AppData/Roaming folder of the sandbox user `itch-player`, so if you're seeing `C:\Users\elisee`, something's going wrong somewhere :)

**Comment by fasterthanlime** [comment]
> something's going wrong somewhere :)

See https://github.com/itchio/elevate/blob/master/src/elevate.c — elevate sets `%USERPROFILE%`, and that's enough for `SHGetFolderPath` calls to return the right thing. I guess the old `%APPDATA%` leaks through, though

**Comment by elisee** [comment]
Ah OK, we do use APPDATA directly in several places. I'll look into getting that changed! https://github.com/superpowers/superpowers-app/search?utf8=%E2%9C%93&q=appdata

**Comment by fasterthanlime** [comment]
And I'll look into making it work regardless ;) you might beat me to it though, since I'm not planning to work this week-end :)

**Comment by elisee** [comment]
Fixed this on our side in https://github.com/superpowers/superpowers-app/commit/07210b41867ee666c2c6a58754c3c15d40786fc0, will be in Superpowers v2 coming soon.

**Comment by fasterthanlime** [comment]
> Hey I beat you to the fix

Called it! I'm elbows-deep into http://github.com/itchio/capsule right now :)

**Comment by elisee** [comment]
I wasn't showing off, I kindly shared an update so you know a fix on your side is not time-sensitive anymore! :stuck_out_tongue: 

But hey. I _did_ beat you to the fix.

:grinning:
