### ISSUE TITLE
You may not unsubscribe from a store listener while the reducer is executing

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#846]
Error thrown spuriously from the chrome side. Wonder what _that's_ about?

**Comment by fasterthanlime** [comment]
happened again:

![virtualbox_archlinux_02_08_2016_19_40_00](https://cloud.githubusercontent.com/assets/7998310/17338767/086707aa-58e9-11e6-8ef5-9b2aa8f01825.png)

**Comment by fasterthanlime** [comment]
Happens with kitch 18.4.5-canary on ArchLinux (haven't seen the bug anywhere else yet).

I'm trying to remove react-safe, see if it's causing it.

**Comment by fasterthanlime** [comment]
This sounds like a timing issue but I don't know which side is to blame! And it only happens on my ArchLinux VM.

**Comment by fasterthanlime** [comment]
Not a timing issue, see https://github.com/samiskin/redux-electron-store/issues/27

**Comment by samiskin** [comment]
Yep this is 100% my fault, will get to fixing this as soon as I can, sorry!

**Comment by fasterthanlime** [comment]
@samiskin I was working on getting you an actual stack trace - still useful or no?

**Comment by samiskin** [comment]
Definitely useful, I haven't had time to reproduce and investigate yet.

**Comment by fasterthanlime** [comment]
Cool. There's no pressure - I'll pin to a version that's not affected by it so I can ship 18.5.0, and you'll have time for a good fix :)
