### ISSUE TITLE
Google Cloud Storage blocks Iran IPs

### ISSUE THREAD

**Issue by Sinaxx** [itchio/itch#860]
every time i try to install something it try to start but it respond "uploadserver at commondatabase.googleapis.com responed with HTTP 403 forbidden"

**Comment by fasterthanlime** [comment]
Which country are you downloading from?

**Comment by Sinaxx** [comment]
Iran. is because of my ip?
cuz i try it with vpn but i doesn't work either

**Comment by fasterthanlime** [comment]
It could be - we whitelisted Iran on our CloudFlare configuration a while ago but some service providers still blacklist it indescriminately

Are you downloading via itch.io/app or directly from the website?

**Comment by Sinaxx** [comment]
thanks for puting Iran into your whitelist. :D 
the website works, i have problem with the app

**Comment by fasterthanlime** [comment]
Alright, then it's Google Storage blacklisting Iran, I'm sorry :( the site uses a download proxy of our own which bypasses that, and the app doesn't make use of it right now. We're reworking our content delivery infrastructure and hopefully this will solve that issue too.

**Comment by Sinaxx** [comment]
thank you very much i hope it solve real soon :)
