### ISSUE TITLE
Bug: Need to Log-in For Client

### ISSUE THREAD

**Issue by SolarLune** [itchio/itch#865]
Hey, there. 

So basically, you aren't considered "logged in" to itch if you view a page through the client (where you already logged in earlier, on start-up). It's weird to not be able to leave a comment on a page because you need to "log in" again in the browser.

**Comment by fasterthanlime** [comment]
(see #672)

**Comment by SolarLune** [comment]
Ah, I see. I did a search for "log in"; guess that space made the difference, haha. I'll close this, then.
