### ISSUE TITLE
Windows defender is not always playing nice

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#867]
See https://github.com/itchio/itch-compatibility-watchlist/issues/127 - long delays in launching a game (long enough that it prompted the user to cancel the launch).

I'm not even sure what steps should be taken here. Advising users to disable it is certainly not an option.

Hopefully we can find contacts at Microsoft to work something out, but that might take some time (and we'd need to find folks not entirely devoted to the Windows Store/UWP cause).

**Comment by jurgentreep** [comment]
I did download and install some other games though and they don't seem to have this issue.

**Comment by fasterthanlime** [comment]
Well, no one else with *just Windows Defender* has complained about this in a long while, closing.
