### ISSUE TITLE
itch is not picking up latest locales

### ISSUE THREAD

**Issue by quyse** [itchio/itch#869]
I remember itch was updating locales automatically before, but now it's not happening.

Particularly, I made a few changes into Russian localization, and I wasn't able to make itch 18.6.2 show new strings, both on Linux and Windows, both itch launched from git workdir via `DID_I_STUTTER=1 npm start` and as installed by official installer. I see that `~/.config/itch/locales/ru.json` is stale, and if I removed it itch doesn't download it again (there's a line `[locales] Downloading fresh locale file from https://locales.itch.ovh/itch/ru.json` in a log though if I click "refresh locale" button in preferences, but seems like nothing happens really).

Now 18.6.3 is out, and after update itch still doesn't show new strings (even those committed into git in 311e0fc3354028b4204a012df7982057d679730b). Removing that stale `ru.json` by hands helped, and itch now shows strings as in git, but again without the latest uncommitted change I just made on Weblate. I can confirm that `https://locales.itch.ovh/itch/ru.json` returns the latest (i.e. correct) version of strings, so something must be wrong with the app?

**Comment by fasterthanlime** [comment]
@quyse sure enough, thanks for the report!

**Comment by fasterthanlime** [comment]
18.6.4 is out with the fix.
