### ISSUE TITLE
GIFs as cover images occasionally fail to show up

### ISSUE THREAD

**Issue by dmliao** [itchio/itch#873]
itch v18.7.0, Windows.

Noticed that GIFs in cover images sometimes fail to preview, displaying as broken image (despite working fine on itch.io website) or as a blank image slot. In the case where the gif showed up as a blank image slot, hovering over it still displays the GIF correctly.

Issue seems to be sporadic, though I have consistently seen it with the same games. I have not seen this issue in any cover images that weren't GIFs.

![q2eekorn](https://cloud.githubusercontent.com/assets/769957/18363907/1e9678ae-75da-11e6-9d01-f4e4c7eaa05c.jpg)
Example of GIF cover image displaying as broken image (first game, Excerpts from the journal of a lost soul)
This screenshot is not from my itch.io account, and was taken on Windows 10.

![itch](https://cloud.githubusercontent.com/assets/769957/18363922/2d18880e-75da-11e6-86d5-97908baa6b33.png)
Example of GIF showing up as a blank image slot (Apartment Complex)
This screenshot is using my itch.io account, and was taken on Windows 8.0.

I'm not entirely sure they are the same issue, but they seem related enough that I'm putting them together for now. I don't remember exactly which screens these showed up on, either. None of the games on the itch.io front page had this issue, and I only recall seeing it in itch-app specific pages (so not while browsing itch.io the site in the app) - though I have no record of that.

**Comment by fasterthanlime** [comment]
apartment complex's still cover URL definitely seems broken: https://img.itch.io/aW1hZ2UvODMyNTMvMzkyMDY1LmdpZg==/315x250%23cm/d8%2F0%2BN.gif

then again the original cover isn't great either: https://img.itch.io/aW1hZ2UvODMyNTMvMzkyMDY1LmdpZg==/original/nJgoob.gif

so it's just games with missing/invalid covers then

**Comment by dmliao** [comment]
Is this an error on the user side, or the itch.io side? (i.e. is there an easy way for the game's creator to fix the cover image? I don't recall there being an option to upload a still cover and a GIF cover on the same game)

**Comment by fasterthanlime** [comment]
Actually, both URLs above seem to work now — so it probably was an error with itch.io's img server. Closing since the issue seems resolved for the moment (but will be adding more health checks for the image server in the future)!

**Comment by aviraccoon** [comment]
This just happened to me. img server was showing a 500 with this stacktrace.

![stacktrace](https://cloud.githubusercontent.com/assets/368677/19255484/c5deabde-8f5e-11e6-8acb-f045a721a36d.png)

**Comment by leafo** [comment]
Should be good now @TomasDuda, image server was having an issue

**Comment by TackerTacker** [comment]
I have the same problems 
https://img.itch.zone/aW1hZ2UvMjI3ODMyLzEwOTEyMzguZ2lm/315x250%23cm/eloyhh.gif
![firefox_2018-03-02_19-22-27](https://user-images.githubusercontent.com/18266300/36914950-429aa8be-1e4f-11e8-90fd-6da4dfcf7f96.png)
