### ISSUE TITLE
[win32] game Lads in Distress broken for v0.13.2

### ISSUE THREAD

**Issue by programtester806** [itchio/itch#926]
:rotating_light: game [Lads in Distress](https://catfishcrew.itch.io/lads-in-distress) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f0a4b3ba778818e318e7d2121cd85051).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Thanks a bunch for all the reports, but 0.13.2 is really quite old — the latest version atm is 18.9.0. Some of those might be working with the latest version.
