### ISSUE TITLE
App not installing

### ISSUE THREAD

**Issue by Nktgwtg** [itchio/itch#932]
I have tried multiple times to get the app to install on my computer, and I got it once. However, now when I try to do it I receive this error message, "Windows cannot access this."
![untitled](https://cloud.githubusercontent.com/assets/17885555/18862082/e0c1a12a-8457-11e6-990e-1acd07461d92.png)

**Comment by Nktgwtg** [comment]
I figured out why it wasn't working.

**Comment by fasterthanlime** [comment]
Just in case someone gets a similar message, what was the problem and how
did you fix it?

**Comment by Nktgwtg** [comment]
It was Avast interfering with the installation. I basically tried to fixed something a while back that wasn't broken, and it messed with Itch.
