### ISSUE TITLE
Game version tooltip displays wrong date

### ISSUE THREAD

**Issue by quyse** [itchio/itch#934]
I'm confused by date shown in a tooltip which is displayed when you mouse over game version.
![image](https://cloud.githubusercontent.com/assets/416215/19015055/3cf1f098-8805-11e6-91ee-60df26fe160a.png)
I would expect here a timestamp of this particular version, i.e. when this version was released. Instead itch seems to show time _when the game was installed first time on this computer_. So when I install a game in the first time, I see current time there like on the picture; and if I installed a game long time ago, I see time far in the past, even if game was updated recently. Version number is shown correctly, but it's not really helping you in understanding if the version you have is the latest one.

**Comment by fasterthanlime** [comment]
Sounds like a bug indeed! Would have to dig in the code to see which date exactly gets displayed!
