### ISSUE TITLE
Games are downloaded satisfactorily, but Itch can't extract them from the zip file

### ISSUE THREAD

**Issue by shackra** [itchio/itch#936]
This is on GNU/Linux. For some reason butler is not decompressing the zip file of the game downloaded. So far the only games I can play from Itch are _Tanks of Freedom_ and _Strange Things_.
- [itch.txt](https://github.com/itchio/itch/files/515100/itch.txt)

**Comment by fasterthanlime** [comment]
I just installed extracted and played Badb's Tea House on Linux without any issues — can you try again with the latest itch and re-open if it's still an issue?
