### ISSUE TITLE
Handle case where sanitizing game title results in a single space / empty name

### ISSUE THREAD

**Issue by Ragzouken** [itchio/itch#939]
https://ragzouken.itch.io/the-dark-third

possibly because the whole name is unicode? look at the empty space in the file path

[2016-10-16 @ 14:50:49.691] [reactors/tasks] Install failed, attempting to destroy cave
[2016-10-16 @ 14:50:49.695] [reactors/tasks] Error in install: *os.PathError mkdir C:\Users\mark\AppData\Roaming\itch\apps\ \aeropause-windows: The system cannot find the path specified.
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/fs.go:148 (0x407995)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/fs.go:106 (0x417d17)
C:/Go/src/path/filepath/path.go:351 (0x529ff0)
C:/Go/src/path/filepath/path.go:376 (0x52a346)
C:/Go/src/path/filepath/path.go:398 (0x52a4a7)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/fs.go:137 (0x4077a4)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:394 (0x416939)
C:/Go/src/runtime/proc.go:183 (0x4490de)
C:/Go/src/runtime/asm_386.s:1612 (0x472e81)

**Comment by fasterthanlime** [comment]
Interesting, all non-alphanumeric characters are stripped and all that remains is.... a space. Not good!

**Comment by fasterthanlime** [comment]
Install folder names in itch v25 are derived from the upload name instead (and that one can't be empty / have funky characters), so this isn't an error condition anymore.
