### ISSUE TITLE
Not correctly escaping paths, at least under Linux.

### ISSUE THREAD

**Issue by Glanzer** [itchio/itch#940]
It's probably just a weird edge-case, but it breaks under Linux by using a '$'-sign instead of the letter 'S'. [https://github.com/itchio/itch-compatibility-watchlist/issues/203]
I'm not sure if that kind of behaviour is intentional - thought I'd link it here for reference.

**Comment by fasterthanlime** [comment]
Indeed a bug! Will fix.

**Comment by fasterthanlime** [comment]
Well, that game has changed its upload/folder names, but at no point is the shell involved in launching games on linux with itch v25 (released last week), so I'm assuming this is no longer an issue.
