### ISSUE TITLE
Crash when closing a full-screen web game on macOS

### ISSUE THREAD

**Issue by wjlroe** [itchio/itch#944]
# Steps to reproduce:
1. Find and download a web game in the Itch client app (https://ncase.itch.io/coming-out-simulator-2014 works well for this, but any web-based game that's embedded in Itch.io will work)
2. Set the Itch client app to full-screen on macOS
3. Launch the game while the Itch app is full-screen (the game should open in a tab).
4. Close the tab the game is in
# Expected results:

The game closes, taking the user back to the main Itch app's user interface
# Actual results:

Itch crashes with a segmentation fault [an example of which I've uploaded to a gist](https://gist.github.com/wjlroe/e9f647915d196e622cdbdc22226c3174). When running from Terminal, there is no output indicating why it crashed.
# Versions

macOS 10.12
Itch 18.10.1

**Comment by fasterthanlime** [comment]
I've noticed that before! The fact that it opens in a new tab is almost certainly an electron bug (or perhaps a feature?)

**Comment by retropipes** [comment]
Retesting in itch v25.4.0 with tabs DISABLED: No crash!
Retesting in itch v25.4.0 with tabs ENABLED: No crash here either!
Looks like this is fixed! (Tests done on macOS Mojave 10.14.1)

**Comment by fasterthanlime** [comment]
Thanks @wrldwzrd89 - tabs have been reimplemented almost completely in v25, so I'm happy to learn this is fixed.

Closing! 🌟
