### ISSUE TITLE
Location of Install Not Configurable

### ISSUE THREAD

**Issue by Faedelity** [itchio/itch#946]
I don't mean the location to install games, I found that. I mean the location to install the client itself. Currently, it automatically installs in a location deep in my user directory. I have an entire drive dedicated to games, and I would prefer that it be installed there, but I am never given a choice. There isn't even a significant "installing" screen, just a large splash screen, and Itch is installed. This is opaque and unusual; it would be much better (and more the usual way of doing things) to have a quick dialog confirming that the user actually wants to install Itch and didn't just click on a mysterious executable to see what it is, and ask them if they want it in the default location or somewhere else.

**Comment by fasterthanlime** [comment]
I hear you! Duplicate of #650 though (limitation of Squirrel.Windows, junction workaround, etc.)

**Comment by Faedelity** [comment]
A renaming or something similar on #650 would be appropriate if you're going to consider this a duplicate. "Portable" means being able to take the app from computer to computer and use it, for example on a thumb drive. It's not the correct term for having a configurable install location. As most of the comments there seem to mean the same thing I did, I do think this is a duplicate, but the name of the issue doesn't correctly reflect the contents.
