### ISSUE TITLE
make AUR package for archlinux

### ISSUE THREAD

**Issue by leafo** [itchio/itch#95]

**Comment by fasterthanlime** [comment]
@leafo fpm can do that, read https://github.com/itchio/ci.itch.ovh/blob/master/src/jobs/itch.yml

**Comment by FrozenCow** [comment]
@leafo I've just added it to AUR: https://aur.archlinux.org/packages/itch/

@fasterthanlime fpm didn't seem to create pkgbuilds, which are needed to get into AUR (Arch User Repostory). The packages are built by each user individually.

**Comment by fasterthanlime** [comment]
@FrozenCow ah, neat! expect the app to be updated often, I hope you have free time :)

**Comment by josefnpat** [comment]
:+1:

**Comment by fasterthanlime** [comment]
@jordansissel can you confirm that fpm doesn't create pkgbuilds ? I forgot how Arch works.

**Comment by josefnpat** [comment]
only a few minor issues with the AUR (missing `nodejs-grunt-cli` dep), otherwise I got everything rolling!

**Comment by fasterthanlime** [comment]
note that running tests is a good idea and requires node 4.x (some level of ES6 supports like 'let' in strict mode, etc.)

**Comment by FrozenCow** [comment]
@fasterthanlime fpm does create ArchLinux packages (`.pkg.tar.xz`), but those are usually for manual installation and when you host a package repository. Most third-party packages are built from source using the `PKGBUILD` file to define how to build and package it in addition to some metadata (dependencies). These `PKGBUILD` files can be uploaded to AUR (Arch User Repository). Users have tools to easily download, build and install packages from AUR. It's convenient. Added bonus, if the package does well (enough votes) the PKGBUILD will be used in the official repository and maintainance transferred to an ArchLinux maintainer.

It does `npm test` now too. Seems to work fine atm.

**Comment by fasterthanlime** [comment]
> Added bonus, if the package does well (enough votes) the PKGBUILD will be used in the official repository and maintainance transferred to an ArchLinux maintainer.

That's good to hear! I'll tweet about it.

> It does npm test now too. Seems to work fine atm.

I released 0.9.4 earlier today. Any chance to see the upgrade in the AUR package?

**Comment by fasterthanlime** [comment]
So I guess we can close it now since it's on AUR ?
