### ISSUE TITLE
Allow opening assets instead of marking them as broken

### ISSUE THREAD

**Issue by phrounz** [itchio/itch#96]
I tried to install "Kenney Game Assets" http://kenney.itch.io/kenney-donation in my owned list (I bought it).

And it displays "Error: No download available" and the icon ":( Broken"

If it is because it's a game assets package with no executable, I think that it would be interesting to add in the future "manifest" feature mentioned in https://github.com/itchio/itch/issues/92 the possibility to say: "just open the folder with the file explorer". The assets packages developers could then use this.

**Comment by fasterthanlime** [comment]
True, for now the app will only download something that's tagged for your platform, so assets are out at the moment

**Comment by fasterthanlime** [comment]
Closed by 183752a04e56e6e482c593ffcca0e54e7d757154
