### ISSUE TITLE
deps packaging

### ISSUE THREAD

**Issue by sylware** [itchio/itch#961]
Hi. For minimal gnu/linux distros, would it be reasonnable to package the apps with all its deps above the C runtime and x11/alsa libs?
(in order to avoid conflicts, the best would be to have it statically linked with only the above system deps kept as a shared so)

**Comment by fasterthanlime** [comment]
Hey,

The portable Linux build we release is already quite light on dependencies — which distros are you talking about in particular? Would it make sense to list the dependencies in the docs instead so you can just install them from their package manager?

If not, would you be willing to champion the "batteries included" build of the app or at least do the initial research?

**Comment by sylware** [comment]
On Fri, Nov 04, 2016 at 03:43:04AM -0700, Amos Wenger wrote:

> The portable Linux build we release is already quite light on dependencies —
> which distros are you talking about in particular? Would it make sense to
> list the dependencies in the docs instead so you can just install them from
> their package manager?
> 
> If not, would you be willing to champion the "batteries included" build of
> the app or at least do the initial research?

It's a custom minimal gnu/linux distro (not like the huge mainstream ones).
A real minimal distro: basic C runtime libs and x11/alsa libs only.

I _may_ try to do it myself since it's an open source app. Of course if the deps
are technically expensive and massive then ... :(

BTW, can we buy games with your app? (usually, the real issue is the payment
infrastructure kludge which is a pain).

## 

Sylvain

**Comment by fasterthanlime** [comment]
> It's a custom minimal gnu/linux distro (not like the huge mainstream ones).
> A real minimal distro: basic C runtime libs and x11/alsa libs only.

Have you tried running the app on it? What was it missing?

> BTW, can we buy games with your app? (usually, the real issue is the payment
> infrastructure kludge which is a pain).

Yep, but it's via a webview — when you click Purchase, it opens a window with this, for example: https://leafo.itch.io/x-moon/purchase and when you complete the purchase flow, it closes the window and the game appears in your library, ready to install!

We might have a more integrated purchase flow eventually, but for now it works well enough.

**Comment by sylware** [comment]
On Fri, Nov 04, 2016 at 05:02:49AM -0700, Amos Wenger wrote:

> > It's a custom minimal gnu/linux distro (not like the huge mainstream ones).
> > A real minimal distro: basic C runtime libs and x11/alsa libs only.
> 
> Have you tried running the app on it? What was it missing?

From memory, gtk+ libs were missing already.
I have a shared libgcc_s only for glibc which needs it for pthread_cancel, but
I may migrate to musl clib which does not need libgcc_s for pthread_cancel
(then you can go full statically linked libgcc for the whole system). Some
light distros are already dropping glibc, for instance alpine gnu/linux.  The
trick it to link statically the app, except for basic C runtime services
x11/alsa lib (pulseaudio support would be done through the alsa pulseaudio
plugin).

Regarding the toolkit, if the app is not linked explicitely to gtk-_x11_, that would be a
"system" lib to abstract away x11/wayland. Then the "basic" gfx libs to be
dynamically linked to would be gtk+ libs with x11/wayland abstracted away.

I'll download your last release build and check...

> > BTW, can we buy games with your app? (usually, the real issue is the payment
> > infrastructure kludge which is a pain).
> 
> Yep, but it's via a webview — when you click Purchase, it opens a window with
> this, for example: https://leafo.itch.io/x-moon/purchase and when you
> complete the purchase flow, it closes the window and the game appears in your
> library, ready to install!

You mean it's a web engine inside the app which will display the purchase flow?
Or is the app redirecting the url to heavy browsers (biggest kludges mankind
sick brain ever created :( )?

## 

Sylvain
P.S. I don't understand why we need unwinding code from libgcc_s in
pthread_cancel since the thread stack is gone as a whole. Devil hides in the
details I guess.

**Comment by fasterthanlime** [comment]
> You mean it's a web engine inside the app which will display the purchase flow?
> Or is the app redirecting the url to heavy browsers (biggest kludges mankind
> sick brain ever created :( )?

Haha, the whole app is a ~~kludge~~ browser :) http://electron.atom.io/

**Comment by sylware** [comment]
On Fri, Nov 04, 2016 at 05:49:17AM -0700, Amos Wenger wrote:

> > You mean it's a web engine inside the app which will display the purchase flow?
> > Or is the app redirecting the url to heavy browsers (biggest kludges mankind
> > sick brain ever created :( )?
> 
> Haha, the whole app is a ~~kludge~~ browser :) http://electron.atom.io/

"Electron uses Chromium", then I guess I would drop any attempt.
blink|webkit/geecko are products of sick brains :(

If I want to produce a build of the blink engine with lean deps, I'll go crazy
on SDK deps and configuration and lose sanity.

Then, would you mind providing a noscript/0-javascript www purchase workflow
and/or a light www API for it (usually for integration with third-party and
industrialization)?

regards,

## 

Sylvain

**Comment by fasterthanlime** [comment]
> Then, would you mind providing a noscript/0-javascript www purchase workflow
> and/or a light www API for it (usually for integration with third-party and
> industrialization)?

**Comment by fasterthanlime** [comment]
> Then, would you mind providing a noscript/0-javascript www purchase workflow
> and/or a light www API for it (usually for integration with third-party and
> industrialization)?

Sounds like an issue for https://github.com/itchio/itch.io :) but I don't really see it happening currently — payment processors rely a lot on browsers for things like fraud detection.

**Comment by sylware** [comment]
On Fri, Nov 04, 2016 at 07:51:11AM -0700, Amos Wenger wrote:

> > Then, would you mind providing a noscript/0-javascript www purchase workflow
> > and/or a light www API for it (usually for integration with third-party and
> > industrialization)?
> 
> Sounds like an issue for https://github.com/itchio/itch.io :) but I don't
> really see it happening currently — payment processors rely a lot on browsers
> for things like fraud detection.

fraud detection? This is a fallacy. The better guess would be to force upon
people some brain damaged software components whose dev and code are controlled
by some corporations.

To tell you the truth, I'm about to sue some payment processors providers.
Could not renew my domain name becoze I **MUST** use gecko or blink|webkit. A
noscript/0-javascript basic form would be fairly enough. Moreover, it kills in
the egg any alternative since you need years of man work to get something like
blink|webkit/geeko working reasonnably.

I feel quite "screwed", and I won't let "them" screw me as much as they want.
Hope, I did open your eyes on the matter.

## 

Sylvain
