### ISSUE TITLE
itch fails to recognize new Tiled version on Linux

### ISSUE THREAD

**Issue by bjorn** [itchio/itch#963]
I've released Tiled 0.17.1 today, including a new build for Linux. However, the itch app remains convinced that I already have the latest version of Tiled installed:

![tiled-up-to-date](https://cloud.githubusercontent.com/assets/531764/20022430/da224dbe-a2da-11e6-8fd4-ef10d7cf6baf.png)

I could probably work this around by uninstalling and re-installing Tiled, but I'd really like for anybody who had installed that old build to get properly notified.

One thing that may be related, is that the old file was uploaded to itch whereas the new file is an external link to GitHub. The old file is also still around on itch.io, but disabled.

**Comment by bjorn** [comment]
I'll just add that on another Linux PC I have uninstalled Tiled and then tried to install this new release. However, it could not download the new release for some reason (don't have any logs now, unfortunately). The release downloads fine through itch.io.

**Comment by fasterthanlime** [comment]
> One thing that may be related, is that the old file was uploaded to itch whereas the new file is an external link to GitHub. The old file is also still around on itch.io, but disabled.

It is definitely related. There is no way for us to check that the content an external upload URL is pointing to has changed. I know external uploads seem tempting, but I beg you to consider using [butler](http://itch.io/docs/butler) instead for this reason and many others (patches, integrity checking, etc.)

**Comment by fasterthanlime** [comment]
> However, it could not download the new release for some reason (don't have any logs now, unfortunately)

This is another issue, see #964

**Comment by fasterthanlime** [comment]
> but I beg you to consider using butler instead for this reason and many others

However, as long as external uploads are an itch.io feature it's reasonable to expect pointing to github release URLs to function, so I'm going to:
- Make sure github downloads work
- Implement external upload URL comparison for update checking

The latter will mean the app will re-install all games with external uploads when it first gets updated, because it'll have no memory of what external upload URL was originally installed. Which is bad, but it's only a transition thing!

**Comment by fasterthanlime** [comment]
Closing in favor of #964, #965, #966.

**Comment by bjorn** [comment]
> It is definitely related. There is no way for us to check that the content an external upload URL is pointing to has changed.

Right, I'll just point out that I never changed the content an external upload URL is pointing to. I always create new file entries on the itch.io interface and would expect itch to assume it has changed.

> I know external uploads seem tempting, but I beg you to consider using butler instead for this reason and many others (patches, integrity checking, etc.)

I'd love to, but the dilemma is that I don't want to force people to install the itch app to keep their Tiled up to date. So Tiled is doing its own update checking and installing as well, necessarily based on external URLs. I also don't want to maintain even more packages, one set for without itch app and another optimized for the itch app. I'll definitely want to try butler on Linux though, since I didn't set up an auto-update mechanism there.

Maybe I will eventually decide to just rely on itch for updates, and replace the auto-update mechanism in Tiled with a simple new version notification.

**Comment by fasterthanlime** [comment]
> Right, I'll just point out that I never changed the content an external upload URL is pointing to. I always create new file entries on the itch.io interface and would expect itch to assume it has changed.

So you're actually creating a new upload, and setting to the github release's url, not editing an upload an changing its URL?

> Maybe I will eventually decide to just rely on itch for updates, and replace the auto-update mechanism in Tiled with a simple new version notification.

I completely understand not wanting to rely on the itch app for that — note that anything uploaded with butler is available as a web download, and since the downloader+updater the itch app uses is open source, if you're interested, I can definitely help you integrate it in Tiled itself so that it can update itself when not launched by the itch app :)

**Comment by bjorn** [comment]
> if you're interested, I can definitely help you integrate it in Tiled itself so that it can update itself when not launched by the itch app :)

Just a note, that I'm definitely interested in this possibility. Since I read you're going to use this system also for itch itself, maybe eventually you could provide a bit of documentation about how such a thing would work.
