### ISSUE TITLE
Display patch download speed, not container processing speed

### ISSUE THREAD

**Issue by jareth314** [itchio/itch#973]
Dear itch app team, 

I was downloading an update to Aven Colony and noticed the reported download speeds were odd.  First I was getting 15 MB, which is odd since my internet service is 15 megabit.  It then went into the 100's of MB and even GB.  Not sure why this happened, and didn't see anything related to this on a quick search via the search issue button.

**Comment by fasterthanlime** [comment]
Hey jareth, what you're actually seeing is patching speed (how fast it's processing files of your local install to bring them up-to-date) — many files are untouched, so it can easily process multiple GB in a few seconds.

However, I agree that it's confusing, and I may change it to the speed at which the patch is downloaded instead. Did the update go over well? We're testing a new system that should work better for large games like Aven Colony.

**Comment by fasterthanlime** [comment]
itch v25 does show the network bandwidth by default, not the processing bandwidth, so looks like this has been taken care of!
