### ISSUE TITLE
🏁 Issue v19.0.0

### ISSUE THREAD

**Issue by Ecochi** [itchio/itch#974]
Dear itch app team, 

I can't browse within the app , because I get the error code "400 bad request" - Request header or cookie too large since yesterday evening.
It's really annoying and I just want to play via the launcher games. But I can't even open the tabs of the games.

**Comment by fasterthanlime** [comment]
That sounds like a website bug, I've seen that before :( (see #931).

I can give you instructions to make your itch work again, all I need is your itch.io username!

**Comment by Ecochi** [comment]
I guessed it could be something like this but I dunno how to treat it XD

The username would be Ecochi 

Thank you!

**Comment by fasterthanlime** [comment]
Alright, touch wood and follow these instructions:
- Press Shift-F12: this should open a new window named 'Developer tools'
- In that new window's "Console" tab, paste the following code:

```
require('electron').remote.require('electron').session.fromPartition("persist:itchio-273761").clearStorageData()
```
- Press enter
- Reload any tabs you want

This should clear the cookies. Let me know if it works for you!

**Comment by Ecochi** [comment]
Yes !! Thank you so much!! Saved my day hahaha

**Comment by fasterthanlime** [comment]
Awesome! I'll keep #931 in mind so you don't have to go all matrix if it ever happens again.
