### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by StripedMonkey** [itchio/itch#978]
:penguin: Running Arch Linux 
When trying to get the package from the AUR I get this error while installing. 
http://hastebin.com/ezupemosir.coffeescript

The particular part of this that's the error is 
TypeError: Cannot read property 'join' of undefined

I noticed this also being an issue for someone over in the comments on the package. Any ideas as to what could have caused this issue? I've tried reinstalling and that did nothing. According to the bit of reading I did it seemed to be something to do with this:
https://github.com/npm/npm/issues/7927
but I'm unfamiliar with how this works

**Comment by fasterthanlime** [comment]
It's the same error, but in completely unrelated code — it was appearing now and again in my own `npm test` runs, but I've finally squatched it for good in master. Next release will fix that for everyone hopefully! Getting it out as fast as I can :)

**Comment by StripedMonkey** [comment]
That's good to know, thanks for the quick response. Its such a generic response and from what I can tell (by the fact that its because you aren't allowed to have a capital) it could be in any program.

**Comment by StripedMonkey** [comment]
Is there an ETA on when this will be fixed?

**Comment by fasterthanlime** [comment]
the port to typescript is complete, I'll QA and hopefully get a release out this monday.

**Comment by fasterthanlime** [comment]
@StripedMonkey can you tell me if https://aur.archlinux.org/packages/kitch @ v19.1.1-1 installs cleanly for you?

**Comment by StripedMonkey** [comment]
I can although it will probably be late tonight when I get home.

**Comment by StripedMonkey** [comment]
@fasterthanlime It works :D at least to the point where it runs. Any other issues (I've yet to run into) are besides the point. Thanks for fixing this.

**Comment by fasterthanlime** [comment]
Awesome! Got a few more issues to iron out and we'll be ready for a stable release.

**Comment by fasterthanlime** [comment]
(Closing since it's been fixed in master/kitch)
