### ISSUE TITLE
Appimages are extracted

### ISSUE THREAD

**Issue by Sarah-Duck** [itchio/itch#983]
I've been distributing my game on Linux through an app image. I just released and update, and I found out that for some reason the itch.io client wasn't launching my game. I opened up the local files of the game, and it was the AppDir of the AppImage. It seems to be extracting it, I'm not sure why.

https://1029chris.itch.io/dont-get-a-virus My game is here. It's made with Love2D.

![screenshot from 2016-11-13 21-31-05](https://cloud.githubusercontent.com/assets/15712599/20254349/8a9529f0-a9e8-11e6-88c4-56847e1f733c.png)

**Comment by fasterthanlime** [comment]
Yep! That's a bug, technically a #683 duplicate but I don't mind keeping both open since this gives us a good test case.

**Comment by fasterthanlime** [comment]
I've just tested this again in itch v25 and a different but related error popped up, so I fixed that bug, and it's going to ship within the next hour.

Game's fun by the way!
