### ISSUE TITLE
Getting Error HTTP 403 while fetching a file

### ISSUE THREAD

**Issue by DeltaZero** [itchio/itch#984]
Hey there! I'm getting this error when I try to open the itch.io desktop app. 

![image](https://cloud.githubusercontent.com/assets/11534729/20259609/c7682bf4-aa90-11e6-989f-1cf372800b46.png)

I just installed the app. Everytime I open the app, I'm greeted with that error. I never got to the 'homepage' of the app.

**Comment by fasterthanlime** [comment]
Hey there,

Which country are you launching the app from? It might hit one of Cloudflare's built-in filters.

**Comment by DeltaZero** [comment]
I'm launching it from the Philippines :)

**Comment by fasterthanlime** [comment]
Just whitelisted Philippines, try again?

**Comment by DeltaZero** [comment]
It works now! Thank you very much! 👍

**Comment by fasterthanlime** [comment]
Awesome, thanks for reporting back! 🌠
