### ISSUE TITLE
Physical games with type HTML don't launch with electron

### ISSUE THREAD

**Issue by seleb** [itchio/itch#987]
After installing a game which has both "classification: Physical game" and "Kind of project: HTML" (i.e. anything in this list: https://itch.io/physical-games/platform-web), the app does not present the expected electron "Launch" button. Instead, the app shows an "Open" button which brings up a file explorer in the game directory.

Possibly related: including a ".itch.toml" file in the root directory with the contents
```
[[actions]]
name = "play"
path = "index.html"
```
does not change this behaviour.

App version: itch v19.0.0
OS: Windows 10

**Comment by fasterthanlime** [comment]
I can see a fix for that, but it won't be real clean.

**Comment by fasterthanlime** [comment]
Fix wasn't that bad after all. Thanks for the report @seleb!
