### ISSUE TITLE
🏁 Issue v19.0.0

### ISSUE THREAD

**Issue by hobothulhu** [itchio/itch#989]
Dear itch app team, 

I like the application. The layout is pleasant and clean. My one recommendation is to allow starting at boot up time, and then to be able to start minimized to the taskbar tray. I searched through the open issues and did not see an existing case with these two suggestions.

Thank you for this neat program.

-Tomas

**Comment by fasterthanlime** [comment]
Hey there, thanks for the kind words!

Your first request is already tracked in #627, and I just opened #990 to deal with the second one.

Hope we can ship those features soon!

Cheers,
- Amos

**Comment by hobothulhu** [comment]
Amos,

Awesome news! Is there a beta channel for the application? I can do QA, a
bit.

**Comment by fasterthanlime** [comment]
There is! It lives at https://github.com/itchio/kitch/releases/ — more info is available here: https://itch.io/docs/itch/hacking/continuous-deployment.html#the-canary-channel

There's not yet a good process for involving external (non-itch.io-employees) folks in the QA process yet, but we should come up with one.
