### ISSUE TITLE
🏁 Issue v19.1.2-canary

### ISSUE THREAD

**Issue by hobothulhu** [itchio/itch#994]
Dear itch app team, 

Issue:
Clicking Preferences from menu does not open Preferences tab.

Steps:
Open kitch v19.1.2 -> Click on lower right menu button -> Select Preferences
   Expected -> Preferences Menu opens in tab
   Actual -> Nothing visually changes
Using keyboard command of CTRL+, does bring the menu up
The Preferences menu functions as expected in stable release of itch v19

Details
Windows 10 x64, running parallel with itch v19
No known relevant logs
I searched for pre-existing issues by "is:open preferences" and found none referring to this issue.

**Comment by fasterthanlime** [comment]
Thanks a lot! This must be what @ESWAT meant in https://github.com/itchio/itch/pull/972#issuecomment-260805173

**Comment by fasterthanlime** [comment]
(Note: this will be fixed in v19.1.4-canary, not v19.1.3-canary)

**Comment by hobothulhu** [comment]
Indeed, looks like it. Happy to help.
-Tomas
